### ISSUE TITLE
Host Dummy App on Github.io

### ISSUE THREAD

**Issue by kylemellander** [simplabs/ember-simple-auth#1000]
It'd be great to have the dummy app loaded on github.io so that people can see a bit how it works without having to install it on their computer.

**Comment by marcoow** [comment]
Yep, that's a great idea! We'd need an API somewhere though. 

Congrats to issue #1000 btw ;)

💯💯💯💯💯💯💯💯💯💯

**Comment by kylemellander** [comment]
Could we use mirage to mock the data?

**Comment by marcoow** [comment]
We could but I think it helps people more when they can see the requests in the network tab. Shouldn't be a huge thing to set up an API somewhere though.

**Comment by marcoow** [comment]
The dummy app is available at http://ember-simple-auth.now.sh now
