### ISSUE TITLE
support anonymous or not authenticated users during fastboot

### ISSUE THREAD

**Issue by dulmandakh** [simplabs/ember-simple-auth#1006]
Hi,

There is a interesting case where some will want to render content or page + login/register buttons for everyone on Fastboot, then require authentication for further navigation. Or hide login/register buttons if user is authenticated.

It seems that current fastboot development won't support above case, and I would like to offer a help

**Comment by marcoow** [comment]
Can you be a bit more specific about the use care you're referring to? I'm not 100% sure i understand it yet.

The idea behind the FastBoot support we're currently implementing is that the developer shouldn't care about whether a URL is entered via a `{{link-to …}}` or `transitionTo` in the already started app or a `GET` request to the FastBoot server - the rendered DOM or response from the FastBoot server would just always be correct as the session is transparently being transferred synchronized between the client and server.

**Comment by dulmandakh** [comment]
The idea is to render content on fastboot even if user is not authenticated, instead of redirecting him/her to a login page as normally do. Also this will make it possible to share pages on social networks and help with search engine optimization even if we require authentication.

Sorry for my bad english.

**Comment by marcoow** [comment]
If the app requires the session to be authenticated in order to access a particular page that's usually because the user isn't allowed to see the page's contents and rendering it would most likely fail anyway as the API server would reject to respond with the data that that page tries to load as no valid token is present to inject into the request.

Maybe in your use case the route in question shouldn't require the session to be authenticated in the first place?

**Comment by dulmandakh** [comment]
let's take Quora as an example, where allows users visit the page read part of the page, but requires authentication to read whole page. Or is there anyway I can handle the case with current implementation?

**Comment by marcoow** [comment]
Yes, in that case the route itself should not require the session to be authenticated as users should be able to access it and the API server would respond with the required data for anonymous requests as well. You'd only require the session to be authenticated if users click a "read all" link or so or you might render different DOM (e.g. full article whether excerpt) depending on whether the session is authenticated or not - in any case for accessing the route the session doesn't have to be authenticated and in that case FastBoot would never respond with a redirect.

**Comment by dulmandakh** [comment]
Is there anyway to disable ember-simple-auth on fastboot? Because fastboot fails when ember-simple-auth is in packages.json, even when there is no other code that works with ember-simple-auth. FYI, I have latest version of both packages.

**Comment by marcoow** [comment]
You cannot currently use Ember Simple Auth with FastBoot but will be with the 1.2.0 release that should come out soon
