### ISSUE TITLE
Can't access to the stored token in a session

### ISSUE THREAD

**Issue by enrimr** [simplabs/ember-simple-auth#1007]
How can I get the stored token in my session?

I need to get it to add it to the Authorization header inside my adapter, but I can't do     console.log(this.get('session.content.secure.token'));

**Comment by marcoow** [comment]
Assuming you're using ESA 1.0 or later you can do `console.log(this.get('session.data.authenticated.token'));`.

Please use stackoverflow.com for questions and github only for issues.
