### ISSUE TITLE
The authenticator "authenticator:devise" rejected to restore the session - invalidating…

### ISSUE THREAD

**Issue by ghoshnirmalya** [simplabs/ember-simple-auth#1008]
Whenever I refresh after logging in, I get the following error:
`The authenticator "authenticator:devise" rejected to restore the session - invalidating…`

Link to the sample app: https://github.com/ghoshnirmalya/hub-client

Value in local storage after logging in:
`{"authenticated":{"authenticator":"authenticator:devise","accessToken":null,"expiry":null,"tokenType":null,"uid":null,"client":null}}`

Any help will be highly solicited.

**Comment by marcoow** [comment]
@ghoshnirmalya: the repo seems to be private.

On a general note make sure that the server responds with the data that the devise authenticator expects, see http://ember-simple-auth.com/api/classes/DeviseAuthenticator.html#method_authenticate and https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L164

**Comment by ghoshnirmalya** [comment]
@marcoow I made the repo public.

**Comment by marcoow** [comment]
In your authenticator's `restore` method you're checking for the existence of `accessToken` etc. in the session data but all of those values are `null` in the session data actually (see your above comment) - so the `restore` method returns a rejecting promise and the session is not restored.
