### ISSUE TITLE
Feature: How to login user without network call but known response

### ISSUE THREAD

**Issue by RobIsHere** [simplabs/ember-simple-auth#1016]
Hi!

When a new user registers i call a /api/register hook that responds with:

``` json
{
user: {
    /* Data for pushPayload the user */
},
meta: {
    login: {
        /* same response like from /api/login */
    }
}
```

Is there some method alongside the authenticate("authenticator", username, password)
like authenticateWithServerResponse(meta.login)?

I think the use case is pretty common and this would be helpful.
And how could i achieve this?

Best regards,
Rob

**Comment by mupkoo** [comment]
Hey @RobIsHere. 

I haven't used `ember-simple-auth`, but I think that you can use the [restore](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L162) method of the authenticator.

**Comment by RobIsHere** [comment]
I tried that (and every other possible and impossible hack). It didn't work. I was always forwarded to the login page when i tried to manipulate the data via restore or on localstorage.

I think ember-simple-auth has some really intransparent things going on in the background.

**Comment by mupkoo** [comment]
Yep, looks like you have to use *session*'s `authenticate` method.

A work around is to create a dummy authenticator like


```javascript
// app/authenticators/register.js
import Base from 'ember-simple-auth/authenticators/base';

export default Base.extend({
  authenticate(data) {
    return Ember.RSVP.resolve(data);
  }
});
```

and then use it, for authenticating the session after successful registration - `this.get('session').authenticate('authenticator:register', meta.login)`

**Comment by stevenwu** [comment]
Join us in #e-simple-auth in [Ember Slack](https://ember-community-slackin.herokuapp.com/) if there are more questions.
