### ISSUE TITLE
Timed out access_token is not handled gracefully on page load

### ISSUE THREAD

**Issue by dschmidt** [simplabs/ember-simple-auth#102]
Hey,

I was wondering why my timed out `access_token` was not refreshed on page load or my session was at least invalidated (granted I'm using a custom authentication provider but it's based on the upstream OAuth2 implementation).

I think the `expiresAt > now` check here 
https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/authenticators/oauth2.js#L151
does not make sense because according to 
http://tools.ietf.org/html/rfc6749#section-4.2.2
http://tools.ietf.org/html/rfc6749#section-5.1
`expires_in` defines the lifetime of the access_token not of the refresh_token, so it might very well be possible to request a new `access_token` even if the old one is timed out because the `refresh_token` is still valid.

Afaict trying to refresh with an invalid `refresh_token` would trigger a logout anyway. 
If you still don't want to refresh the `access_token` in this case, you should consider to at least invalidate the session.

P.S.: A lot of people seem to use a `refresh_token_expires_in` value in their server responses to mark how long the `refresh_token` is valid. It's not part of the standard afaik tho.

**Comment by basz** [comment]
I think I have devised a workaround the refresh token race issue - unfortunately not without a server

In a custom authenticator I create an uuid (random v4) when the authentication method receives a token, so that is then stored onto the session. When refreshing the token I send that uuid along, special REST endpoint PATCH /refresh-session/uuid. 

This endpoint accepts this uuid and creates a hash from the uuid and refresh token. After sending the refreshed token it stores a flag in a shortlived memcached under that hash key. 

Whenever a second or third window tries to refresh with the same uuid and refresh_token the server simply ignores the request (send an HTTP 429 response).

**Comment by marcoow** [comment]
@basz: this should actually long be fixed. Are you on the latest version of Ember Simple Auth actually?

**Comment by basz** [comment]
yes, think so '0.8.0-beta.2'

does that fix entails the random subtraction from the refresh timeout as mentioned previously in this issue? Could be that my local server is just really slow (~>5 seconds per request).

> @basz <https://github.com/basz>: this should actually long be fixed. Are you on the latest version of Ember Simple Auth actually?

**Comment by marcoow** [comment]
Yes, the fix also includes randomization of refresh to decrease the likelihood of multiple refresh requests.

**Comment by basz** [comment]
So with a fast responding server this issue should -almost- never arrise?

**Comment by marcoow** [comment]
exaclty; also if the situation should actually arise it's not a hard problem as you're only refreshing the token more often than necessary but don't log the user out or so.

**Comment by basz** [comment]
I’m under the impression that when a server refuses to refresh a token (because the refresh_token has expired) it should logout asap? 

On the other hand, any calls to any Bearer token protected endpoints would do that anyway.

**Comment by marcoow** [comment]
The problem that the random delay tries to solve is that when you have multiple tabs of the same application open and the access token expires all the tabs would send a request to refresh the tokens while only one refresh would be sufficient as the new access token would propagate to the other tabs through the store anyway. If in that situation there are multiple refresh requests that's still not actually a problem as you're just refreshing a few times too often which should't really have any side effects though.

**Comment by basz** [comment]
I understand the problem. But does't an auth server will return an invalid_grant any subsequent time a refresh_token is being used whenever that server is configured to always always create a new refresh_token.

// time goes by here

i guess it depends on these settings for the oauth server - think I found a bug in apigility where unset_refresh_token_after_use was always true.

```php
'always_issue_new_refresh_token' => false,
'unset_refresh_token_after_use' => false,
```

Problem might still happen with incorrect settings (basically unset_refresh_token_after_use = true).

thanks marco for pingponging some thoughts

**Comment by marcoow** [comment]
You're right of course. The situation I describe above would actually be a problem. Not sure how to make sure it can ever happen though. Maybe it could be stored in the store somehow if there's a refresh going on already.

**Comment by basz** [comment]
> The syncing issue is really a pain - locking doesn't really work with the store mechanisms (as there are no atomic read-updates); also I don't want the authenticator to have access to the store. Besides that locking also causes some problems as you also have to make sure you remove that lock once the user closes the tab etc.

Considering the complications I would 'box' this issue.

**Comment by marcoow** [comment]
Yeah, unfortunately that's a bit of a problem actually. Maybe someone comes up with a two clever idea ;)
