### ISSUE TITLE
Set authentication on route conditionally

### ISSUE THREAD

**Issue by ghoshnirmalya** [simplabs/ember-simple-auth#1021]
I wanted to know how I can do authentication on a route conditionally. 

Suppose, I wanted to have a cards route which is visible only to the authenticated users. Now, a user can make the card public and the card will be visible to the unauthenticated users also.

How can I achieve this functionality?

So, here, we can set some flag once the card is public and make the route authenticated or unauthenticated based on the flag.

**Comment by marcoow** [comment]
You can simply override the `beforeModel` method and conditionally check for the session's authentication state - see the implementation of [`beforeModel` in the `AuthenticatedRouteMixin`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/authenticated-route-mixin.js#L56) (which you wouldn't use in that case of course).

Please ask questions like this on stackoverflow.com though and use github for issues only.
