### ISSUE TITLE
Uncaught Error: Attempting to inject an unknown injection: `service:session-account`

### ISSUE THREAD

**Issue by flyrev** [simplabs/ember-simple-auth#1022]
Hi

Trying to mimic some of the functionality in the sample app, I added
  sessionAccount: service('session-account'),

however, I get the error in the title of this issue.

What do I need to make that work?

**Comment by marcoow** [comment]
The `session-account` service isn't part of Ember Simple Auth. You'll have to define it yourself if you want to use it. Please post questions like this to stackoverflow.com though and use github for issues only.

**Comment by marcoow** [comment]
no, that is **not** part of ESA

**Comment by flyrev** [comment]
You could comment it in the example app, for example.
