### ISSUE TITLE
Rename "block" to "setHeader" in authorizer

### ISSUE THREAD

**Issue by daliwali** [simplabs/ember-simple-auth#1024]
I think that the naming should be consistent with prior art:
- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/setRequestHeader
- https://nodejs.org/api/http.html#http_response_setheader_name_value

This would require renaming it in existing authorizers and in the generators. It should not break anything.

**Comment by marcoow** [comment]
The original idea was that you might be authorizing sth. other than an XHR (e.g. a call to a library that expects the token as an argument). Since that never actually worked well though, the plan now is to deprecate authorizers (see #979) and remove them in 2.0 altogether.

**Comment by marcoow** [comment]
Closing as we'll probably be deprecating authorizers altogether as stated above.
