### ISSUE TITLE
'ApplicationRouteMixin.sessionRequiresAuthentication' is gone

### ISSUE THREAD

**Issue by konradjurk** [simplabs/ember-simple-auth#1025]
Back with version 0.0.8 I used the 'sessionRequiresAuthentication' method in my application route  to call my custom authenticator if the session was not authenticated.

```
export default Ember.Route.extend(ApplicationRouteMixin, {
  actions: {
    sessionRequiresAuthentication: function () {
      this.get('session').authenticate('authenticator:backend');
    },
    sessionAuthenticationFailed: function () {
      this.transitionTo('index');
    }
  }
});
```

As I can see in the source code, these two hooks are gone. What is the preferred way to do that with v1.0+?

**Comment by konradjurk** [comment]
@marcoow Do you think you can answer this? :) Am I missing an obvious solution?

**Comment by marcoow** [comment]
Please move questions like this to stackoverflow.com - there are much more people there who can help than here.

This post should help upgrading to 1.0: http://simplabs.com/blog/2015/11/27/updating-to-ember-simple-auth-1.0.html

**Comment by konradjurk** [comment]
Okay, found it. The solution is to handle it in the fail callback instead.

`this.get('session').authenticate('authenticator:backend').catch(sessionAuthenticationFailedFn)`

However, that was not part of the migration guide :)
