### ISSUE TITLE
Redefine restore method in Devise

### ISSUE THREAD

**Issue by firstsano** [simplabs/ember-simple-auth#1028]
Hello, we have server settings (which I don't like) where signing in is hapenning through `email` field, but response is `user_email`. So technically I need to redefine `identificationAttributeName` during restoration. I have

```
export default DeviseAuthenticator.extend({
  tokenAttributeName: 'user_token',
  restoreIdentificationAttributeName: 'user_email',
  retore(data) {
    let identificationAttributeName = this.get('identificationAttributeName');
    this.set('identificationAttributeName', this.get('restoreIdentificationAttributeName'));
    this._super.apply(this, arguments);
    this.set('identificationAttributeName', identificationAttributeName);
  }
});
```

the problem is my `restore` method never called, it's calling default `DeviseAuthenticator` method.

**Comment by marcoow** [comment]
What file are you defining that authenticator in and what authenticator do you specify in the call to `session.authenticate`?

**Comment by firstsano** [comment]
1. `app/authenticators/devise.js` <-- file
2. login controller
```
import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service(),

  actions: {
    authenticate() {
      const { identification, password } = this.getProperties('identification', 'password');
      this.get('session').authenticate('authenticator:devise', identification, password);
    }
  }
});
```

**Comment by marcoow** [comment]
ah, you have a typo in the authenticator implementation:

```js
retore(data) {
```

(missing _"s"_)

**Comment by firstsano** [comment]
Oh my god! Thank you! You saved my day! Gonna be careful next time!
