### ISSUE TITLE
Cannot get session in model

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#1029]
In one of my models I need to access the session object.

I'm using ember-auth 0.8.0 and noticed in the code that the session is not injected into the model.

Is there still a way to be able to access it?

**Comment by marcoow** [comment]
You'll need to update to 1.x which exposes the `session` service that you could then inject into the model (`session: Ember.inject.service()`).

**Comment by kgish** [comment]
But my question was whether it is still possible to do this with the older version 0.8.0, since I cannot upgrade yet.

**Comment by marcoow** [comment]
You can manually inject the session into models with a custom initializer. Please post questions like this one on stackoverflow.com or in the Ember Community Slack though.
