### ISSUE TITLE
Can the identificationAttributeName be different in the authorizer and the authenticator?

### ISSUE THREAD

**Issue by kbullaughey** [simplabs/ember-simple-auth#1038]
I ran into problems when I tried to configure a different `identificationAttributeName` on the devise authenticator from the authorizer. Perhaps I'm not understanding something.

I wanted to use `email` to authenticate but use some other identifier in the `Authorization` HTTP header so that the user's email can be changed. But it seems that when the devise authenticator restores the session, it is checking for `email` in the data returned by the server to form the `Authorization` header.

Should this be possible?

**Comment by marcoow** [comment]
Closing this as it's really a question.

And no, I don't think we allow the properties to be called different in the authenticator and authorizer ;)
