### ISSUE TITLE
Defining `ajaxOptions` in `DataAdapterMixin` disables `ds-improved-ajax`

### ISSUE THREAD

**Issue by lolmaus** [simplabs/ember-simple-auth#1042]
This is how Ember Data Canary checks for `ds-improved-ajax`:

``` js
if (isEnabled('ds-improved-ajax') && !this._hasCustomizedAjax()) {
```

where `_hasCustomizedAjax` is `this.ajax !== RESTAdapter.prototype.ajax`.

As a result, including `DataAdapterMixin` disables `ds-improved-ajax` and methods like `methodForRequest`, `dataForRequest`, etc are never invoked on the adapter.

**Comment by lolmaus** [comment]
Found a workaround. Adding

```js
{
  ajaxOptions: undefined
}
```

to the adapter resolves the issue.

**Comment by vlascik** [comment]
I have the same problem, lolmaus's workaround works, but this should be solved in a better way in simple-auth directly.

**Comment by marcoow** [comment]
@lolmaus: I guess you're using the ESA `master` branch? I guess we could make the mixin conditionally add either `ajaxOptions` or `headersForRequest` depending on the Ember Data version that we find.

PR would be awesome!

**Comment by lolmaus** [comment]
> @lolmaus: I guess you're using the ESA master branch?

Yes.

**Comment by cibernox** [comment]
I just found myself. I don't make promises, but I really hate deprecations, so maybe I can make a PR at some point this week.

**Comment by cibernox** [comment]
@marcoow would dropping support for `ajaxOptions` in Ember-data > 2.7 be acceptable if it gets an explicative entry in the changelog & release docs?

The purpose with which ember-simple-auth uses that hook is not covered by `headersForRequest`. Actually, that behaviour at the moment is already implemented by duplicate. The easiest fix would be detect support for `headersForRequest` and if present, just don't define `ajaxOptions` at all.

I have a PR that works locally, if that is ok I can push it.

**Comment by marcoow** [comment]
@cibernox: yeah, I guess that should work well.

**Comment by marcoow** [comment]
This is actually on hold until https://gitlab.tools.trainline.eu/capitainetrain/mweb/merge_requests/455 gets resolved.

**Comment by marcoow** [comment]
cleaning up old issues
