### ISSUE TITLE
Problem - Error - Cannot find module 'lodash/lang/isFunction'

### ISSUE THREAD

**Issue by dominiquecharlebois** [simplabs/ember-simple-auth#1046]
<img width="471" alt="capture d ecran 2016-08-04 a 11 34 45" src="https://cloud.githubusercontent.com/assets/19155476/17413776/7910c258-5a37-11e6-990c-5fa6357196ab.png">

**Comment by dominiquecharlebois** [comment]
Downloaded the github repo, installed npm, bower and ran the server.

**Comment by marcoow** [comment]
You might be running into a variant of this: https://github.com/jscs-dev/node-jscs/issues/1730

Try running `npm cache clean`, `npm install` and check if the problem persists. I cannot reproduce the bug with a fresh clone.

**Comment by dominiquecharlebois** [comment]
That fixed the problem. Sorry for the issue.
