### ISSUE TITLE
OAuth2 Implicit Grant Flow Authenticator

### ISSUE THREAD

**Issue by 256dpi** [simplabs/ember-simple-auth#1054]
Hi! I'm currently working on a OAuth2 Implicit Grant Flow authenticator for ember-simple-auth as part of the [fire](https://github.com/256dpi/fire) framework and the [fire-auth](https://github.com/256dpi/fire-auth) add-on:

Source: https://github.com/256dpi/fire-example/blob/master/ui/app/authenticators/oauth2.js

The authenticator can be used in conjunction with the already built-in OAuth2 Bearer authorizer to authenticate and authorizer users using the OAuth2 Implicit Grant Flow. As I plan to use the implementation in multiple projects I was wondering if you would be interested in adding the implementation to the ember-simple-auth repository?

I thought about creating an extension module, but it seems to me a little too much boilerplate for just this one class...

Implementation Details: The Authenticator must be called in the callback route that receives the access token via a HTTP redirection: https://github.com/256dpi/fire-example/blob/master/ui/app/routes/auth/callback.js#L9.

Based on that, the authenticator should support many established providers (google, facebook, ...) as well as custom implementations. It even allows multiple login strategies (normal, pop-up, iframe): https://github.com/256dpi/fire-example/blob/master/ui/app/templates/application.hbs#L9.

If you're interested I would love to submit a PR with some tests.

**Comment by marcoow** [comment]
Looks good, yeah. I remember discussing adding sth. like this to the library with someone else a few months ago. There might be an open PR with sth. similar already. Adding support for the functionality you're describing would definitely be cool. Besides the authenticator we should definitely also include the route mixin for the callback route that triggers authentication with the new authenticator.

**Comment by 256dpi** [comment]
I started working on the PR. I'm almost finished, but there is one test case that seems a little complicated: https://github.com/256dpi/ember-simple-auth/blob/implicit-grant/tests/unit/mixins/callback-route-mixin-test.js

The tests currently break as the fake InternalSession seems to have no `lookup` method defined and therefore `authenticate` cannot locate the authenticator to authenticate the request. Any ideas?

Here is the simplified trace:

```
undefined is not an object (evaluating '(0, _emberGetownerPolyfill['default'])(this).lookup')

_lookupAuthenticator@http://localhost:7357/assets/vendor.js:88131:58
authenticate@http://localhost:7357/assets/vendor.js:87915:52
activate@http://localhost:7357/assets/vendor.js:88430:39
```

**Comment by marcoow** [comment]
I'd say for the mixin test you can simply use a mock session that just like this:

```js
const MockSession = Ember.Object.create({
  authenticate() {
    return RSVP.resolve();
  }
});
```

**Comment by marcoow** [comment]
This has been added in #1252
