### ISSUE TITLE
With two open tabs, second tab restores session when invalidating in first tab

### ISSUE THREAD

**Issue by matthias-k** [simplabs/ember-simple-auth#1063]
Hi,

I use ember-simple-auth 1.1.0 with ember 2.4.6 to manage the user authentication for an ember app using a custom authenticator which mainly keeps track of a session token. When the user logs out, I call `session.invalidate`. If I have only one open tab, everything works fine: The session gets invalidated, the page reloads. However, if I have a second open tab, then the following happens: The first tab invalidates the session and reloads. In the second tab, in the same moment the authenticators restore method is called with the old session data, which the authenticator happily restores. This restored session is then synchronized in the first tab, resulting in the user being logged in again. If I understand the documentation correctly, this is not supposed to happen, right?

In case it helps, here my authenticator:

```coffeescript
APIAuthenticator = Base.extend(

  session: Ember.inject.service('session')

  authenticate: (name, pass) ->
    return new Ember.RSVP.Promise( (resolve, reject) =>
      if !(name)
        return reject('Need username')

      if !(pass)
        return reject('Need password')

      Ember.$.post("#{EmberENV.APIHOST}/auth/token", {
        username: name,
        password: pass,
        grant_type: "password"
      }).then(((data)=>
          #success
          Ember.Logger.info "Got API token", data.access_token
          this.get('session').set('data.access_token', data.access_token)
          this.get('session').set('data.mail', name)

          resolve({ user_token: data.access_token })
        ),((xhr, status, error) =>
          #error
          Ember.Logger.log('error while login')
          reject({
            xhr: xhr
            status: status
            error: error
          })
        ))
      )

  restore: (data) ->
    return new Ember.RSVP.Promise( (resolve, reject) =>
      if not Ember.isEmpty(data.user_token)
        _data = data
        console.log "Restoring API session", data.user_token
        return Ember.RSVP.cast(Ember.$.ajax("#{EmberENV.APIHOST}/auth/me", {
          headers:
            Authorization: 'Bearer ' + data.user_token
        })).then( (data) =>
          return resolve(_data)
        )
      else
        reject()
    )

  invalidate: () ->
    Ember.Logger.log('invalidate!')
    if (this.get('session'))
      this.get('session').set('data.access_token', "")
      this.get('session').set('data.userInfo', undefined)
      this.get('session').set('data.mail', undefined)
      this.get('session').set('data.expireDate', undefined)
      this.get('session').set('data.verified', undefined)
    return Ember.RSVP.resolve()
)```

**Comment by marcoow** [comment]
You should never use the session service and modify its contents from the authenticator. Instead simply return a promise that resolves with auth data from `authenticate`. That data will then be assigned to the session's `data.authenticated` property. In the `invalidated` method, simply return a resolving promise which will cause the promise to unset all authenticated data automatically.

**Comment by linearza** [comment]
Just ran into this exact issue on our side as well, working on an older codebase and just trying to fix this up - @matthias-k did you manage to find the solution here? In our case we are resolving promises in all the hooks as per the docs
