### ISSUE TITLE
Causes build failure when used as nested addon

### ISSUE THREAD

**Issue by AndyPyeSC** [simplabs/ember-simple-auth#1072]
I have an addon, say `my-addon` which has `ember-simple-auth` as a dependency. When I try running an app that uses `my-addon`, I get an error message from the ember-cli build:

```
version: 2.4.2
app.import is not a function
TypeError: app.import is not a function
    at Class.module.exports.included (C:\Projects\sc-pp\pixelpipe-show-control-player\node_modules\ember-simple-auth\index.js:15:15)
```

This appears to be related to ember-cli/ember-cli#5747 - I noticed there's already a check for one level of "nestedness" in index.js - perhaps that could be replaced with a loop to account for deeper nesting.

**Comment by marcoow** [comment]
This should be fixed in 1.2.0 by the use of ember-cli-import-polyfill - see #1162
