### ISSUE TITLE
I lost my head for this problem: init and sessionAuthenticated in ApplicationRouteMixin can not be together!

### ISSUE THREAD

**Issue by johnunclesam** [simplabs/ember-simple-auth#1073]
I lost my head for this problem: `init` and `sessionAuthenticated` in `ApplicationRouteMixin` can not be together!

In my _routes/application.js_ I have something like this:

```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
import other from '../other';

export default Ember.Route.extend(ApplicationRouteMixin, {

init: function () {
    otherJsImImportingMainFunction();
},

sessionAuthenticated() {
    this.transitionTo('someRoute');
    debugger;
}

actions: {
    ...
}

};
```

In this situation my code doesn't work.

I authenticate and then sessionAuthenticated() is never called.

If I comment out "init:" it works good.

How to fix this?

I'm doing well importing this way?

**Comment by marcoow** [comment]
Whenever overriding `init` in Ember.js you have to make sure to call `_super`, otherwise you might break framework functionality:

```es6
init() {
  this._super(...arguments);

  … // you code
}
```
