### ISSUE TITLE
Store not updating when modifying a nested property in the session data

### ISSUE THREAD

**Issue by tehmaestro** [simplabs/ember-simple-auth#1075]
Hi. If I try to update the session data like this: `this.get('session').set('data.profile.name', 'x');` it doesn't work.
  I understand why it doesn't work, I assume it is because of the `setUnknownProperty` function not triggering, which is to be expected .. but how can I solve this? Any way I could work around this? Do you guys think this is an issue we should solve?

Thank you so much.

**Comment by marcoow** [comment]
This is a known issue and will probably be hard to solve. I'd appreciate anyone who comes up with an idea. I assume one option would be to whenever an object gets assigned to the session data, recursively define observers for all of the object(s) keys (which sounds like it's not really a great solution but I couldn't think of a different one right now).

**Comment by tehmaestro** [comment]
Thanks for the quick answer. I 'll try to find a solution too .. in the meantime, I guess I could do it like this:
`var profile = this.get('session.data.profile'); profile.name = 'x'; this.get('session').set('data.profile, profile);`

**Comment by marcoow** [comment]
Yep, that should probably work.

**Comment by tehmaestro** [comment]
So this is how I'm working around this. Maybe it will help others .. I was already extending the session, so inside my custom session I created a function:
```
    setNested: function(key, subKey, value) {
        this.set('data.' + key + '.' + subKey, value);
        this.set('data.' + key, this.get('data.' + key));
    },
```

Which I call like this: `this.get('session').setNested('profile', 'name', 'x');`

**Comment by courajs** [comment]
This is an incredibly confusing issue to run into. Can we add a "Caveat:" to the docs, since there's no obvious fix to this? Probably where [`session.data` is mentioned](https://github.com/simplabs/ember-simple-auth#the-session-service)

**Comment by marcoow** [comment]
I hope we can fix this by explicitly making this impossible soon. One idea would be to only accept frozen objects to be stored or only accepting scalar values or so.

**Comment by marcoow** [comment]
This is the same as #805 - we'll track everything there from now.
