### ISSUE TITLE
Including authenticationRouteMixin in the application route causes an infinite loop

### ISSUE THREAD

**Issue by bencates** [simplabs/ember-simple-auth#1078]
I have an app which I want to be entirely behind a login gateway; consequently I did this:

```javascript
App.ApplicationRoute = Ember.Route.Extend(ApplicationRouteMixin, AuthenticatedRouteMixin);

App.LoginRoute = Ember.Route.extend(UnauthenticatedRouteMixin);
```

Now trying to load any page in my application causes an infinite redirect loop.

What is the right way to lock down every possible route in my app except for the login route?

**Comment by marcoow** [comment]
You cannot include the `AuthenticatedRouteMixin` into the application route as that makes all of your app require authentication, including the login route. There should probably be an assertion that checks that but it's definitely not possible.

**Comment by bencates** [comment]
I guess consider this a feature request then.  It'd be nice to have a way to make routes locked by default and unlock on a per-route basis instead of the other way around.
