### ISSUE TITLE
session.authenticate().catch does not return an error

### ISSUE THREAD

**Issue by eighteight** [simplabs/ember-simple-auth#1079]
I want to catch an exception on user authentication, specifically, when the server is down.

``` js
var session = this.get('session');

        session.set('data.userId', login);
        session.authenticate('authenticator:oauth2', login, password)['catch'](function (reason) {
          {
            {
              debugger;
            }
          }
...
}
```

I see that the authenticate's catch clause is called when the server is down, however, contrary to the api [description](https://github.com/simplabs/ember-simple-auth), the reason object is undefined.

![screen shot 2016-10-10 at 1 36 37 pm](https://cloud.githubusercontent.com/assets/542368/19245493/793451fe-8eef-11e6-919b-b89d57aa96a9.png)

How this can be fixed?

Thanks.

**Comment by hasib32** [comment]
Same here. I'm not getting error too.

**Comment by marcoow** [comment]
Switch on the [`rejectWithResponse`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L161) behavior in the OAuth 2.0 authenticator to have the authenticator reject with the response object.
