### ISSUE TITLE
Ignore While In Fastboot

### ISSUE THREAD

**Issue by The-Don-Himself** [simplabs/ember-simple-auth#1080]
I know this is somewhat related to https://github.com/simplabs/ember-simple-auth/issues/1045 but with a twist (I think).

I've seen add-ons like Liquid-Fire simply add a 
````
if (!process.env.EMBER_CLI_FASTBOOT) {
````
or
````
if ((process.env.EMBER_CLI_FASTBOOT !== 'true')) {
````

to the build to omit scripts from running in Fastboot. 

Would it be possible and if so, a quicker way to get Simple-Auth somewhat compatible with Fastboot by not running it in Fastboot. Templates using the Simple-Auth helper will have to precede with an if fastboot checker first, and since the client side is always re-rendered anyway I think this could be an acceptable work-around. Or am I mistaken?

**Comment by marcoow** [comment]
The main point with FastBoot compatibility in ESA is to transfer the session between the browser and FastBoot server transparently. There is not much work left to be done in the FastBoot branch and we'll soon be able to release it. Simply Switching off ESA in FastBoot doesn't work.
