### ISSUE TITLE
Devise Adapter + JSON API

### ISSUE THREAD

**Issue by shunchu** [simplabs/ember-simple-auth#1084]
For the life of me, I can't find a clean way to make the `devise` adapter to play nice with JSON API. Looking at the dummy app and the mocks provided, it seems like things are JSON API-ready. But in practice, it's not so straight forward. Has anyone been able to work this through? Is there a happy path for this? Am I missing out on something obvious?

Thank you.

**Edit:**

* backend services returns JSON API formatted payloads (Rails 4.x + Devise)
* front-end running Ember 2.8LTS with latest `ember-simple-auth` (v1.1.0)

Current solution is to force Devise to return plain Rails JSON payload since that's how the ESA `devise` adapter prefers it.

**Comment by marcoow** [comment]
I'm not sure what you're trying to accomplish here. The Devise adapter works with requests and responses as defined in [this gist](https://gist.github.com/josevalim/fb706b1e933ef01e4fb6) (as per the ESA API docs).

I'm also not sure it's actually advisable at all to use JSON API for authentication requests and responses - it's really a resource-focussed spec.

**Comment by shunchu** [comment]
@marcoow, thanks. Rails APIs are being consolidated to comply with JSON API formats. I didn't want to make an exception only for auth. But seeing that the happy path is a simple serialized Rails resource, that's what I'll go with. No overrides on `devise` adapter or anything else necessary. 

Thanks again.
