### ISSUE TITLE
How to persist oauth_token_secret in custom Authenticator

### ISSUE THREAD

**Issue by drewcovi** [simplabs/ember-simple-auth#1085]
I'm attempting to write a custom authenticator that leverages oauth1. As it stands, the oauth_token_secret needs to be persisted somehow (localstorage) so that after authentication and redirect, that secret can be used for access moving forward (it's lost on page refresh).

I've been digging for a while, but can't seem to sort out how I could use simpleauth session storage to persist that oauth_token_secret...

**Comment by marcoow** [comment]
I think torii has some [support for torii 1](https://github.com/Vestorly/torii#supporting-oauth-10a). You can use that via the torii authenticator in ESA. In any way you'll need quite some server code as well though.

**Comment by drewcovi** [comment]
thanks! i think i have another question that is a little more relevant... ill close this for now!
