### ISSUE TITLE
Can't add to session when using a Torii authenticator 

### ISSUE THREAD

**Issue by itsluke** [simplabs/ember-simple-auth#1086]
**Problem**

I've got what looks like a bug when trying to add attributes to the `data.authenticated` object.

I've been trying to use a create a spotify login with a torii authenticator with the flow below:

```
[frontend] authenticate -> spotify
[spotify] returns auth 'code' -> frontend
[frontend] sends code -> backend
[backend] exchanges code for access token, creates/finds User
[backend] sends database API token (not spotifys token) -> frontend
[frontend] resolves `authenticate()` promise and adds `user_token` attribute
```

When trying to set the `user_token` in the resolved promise everything works fine but the `sessionData` that's passed to the authorizer doesn't contain the `user_token` value.

**Odd Fix**

I've found a strange fix where if I change the authenticates `data.provider` to another value then when the `data.user_token` is assigned it sticks. However this then means that I need to remove the change on the `#restore` and `#invalidate` methods.

**Code**

_app/authenticators/spotify-oauth2.js_

```
  ...
  authenticate() {

    return this._super(...arguments)
      .then( function(data) {

        var authorizationCode = data.authorizationCode;

        data.provider = 'spotifyOauth2removeThis';

        return new Ember.RSVP.Promise( function(resolve, reject){
          Ember.$.ajax({
            url: '<callback url>',
            type:     'GET',
            dataType: 'json',
            data:     { 'grant_type': 'spotify_auth_code', 'code': authorizationCode },
            success: Ember.run.bind(null, resolve),
            error: Ember.run.bind(null, reject)
          });
        }).then(
          function (response) {
            return {
              provider: 'spotifyOauth2',
              // jscs:disable requireCamelCaseOrUpperCaseIdentifiers
              user_token: response.access_token,
              // person: response.person,
              // jscs:enable requireCamelCaseOrUpperCaseIdentifiers
              provider: data.provider
            };
        });

    });
  },
  ...
```

```
  ....
  invalidate(data) {
    console.log( 'invalidate', data , this._provider);

    if ( data.provider.match(/removeThis/g) ) {
      data.provider = data.provider.replace( /removeThis/g, '' );
    }
    if ( this._provider.match(/removeThis/g) ) {
      this._provider = this._provider.replace( /removeThis/g, '' );
    }

    return this.get('torii').close(this._provider, data).then(() => {
      delete this._provider;
    });
  },
  ....
```

If I remove the code that alters the `data.provider` then the `data.user_token` doesn't stick.

**Comment by marcoow** [comment]
In the authenticator you're using the `provider` key twice:

```es6
return {
  provider: 'spotifyOauth2',
  // jscs:disable requireCamelCaseOrUpperCaseIdentifiers
  user_token: response.access_token,
  // person: response.person,
  // jscs:enable requireCamelCaseOrUpperCaseIdentifiers
  provider: data.provider // overrides 'spotifyOauth2'
};
```

If fixing that doesn't fix the error a demo project would be handy.

**Comment by itsluke** [comment]
@marcoow yeah sorry that was me trying to see if that would set it correctly afterwards. Unfortunately the same thing happens if I have it once (or not at all) I'll make an example repo and throw it up.

**Comment by itsluke** [comment]
@marcoow here you go https://github.com/itsluke/simple-auth-bug

**Comment by marcoow** [comment]
The problem is that you're not implementing the `fetch` method in the torii provider as [explained here](http://ember-simple-auth.com/api/classes/ToriiAuthenticator.html#method_restore).

**Comment by itsluke** [comment]
Thanks for your help @marcoow.  I completely missed that.
