### ISSUE TITLE
How does OAuth1 fit into Ember-Simple-Auth? (or does it?)

### ISSUE THREAD

**Issue by drewcovi** [simplabs/ember-simple-auth#1087]
I'm working with a number of different approaches to sort out how to "authorize" a session using an external login form.

To obtain the required oauth variables and external urls (access, authorize, request), I built a custom session that
1. checks the existing session data
1. if needed, makes a series of ajax requests to sign and obtain temporary request tokens
1. stores this authentication data in an authentication key under session.data

I'd like to call the session.authorize method to follow patterns, but it would need to open a new window (or redirect the current window) to an authentication url (compiled in the steps above). After external sign-in then has a **redirect** back with an oauth_verifier in a query string.  For this reason, a session isn't truly "authorized" unless that verifier exists either in the session store, or in the querystring when loaded.

However it's expected that an authorizer returns proper credentials from the authorize() promise.

So as best practice, should I trigger the authorize method to launch the external login, and then automatically re-trigger authorize when the session is restored (thus storing the credentials in the "authorized" key)?

**Comment by marcoow** [comment]
The best solution for supporting OAuth 1.0a providers is using [torii](https://github.com/vestorly/torii#supporting-oauth-10a) via the Torii authenticator.

**Comment by marcoow** [comment]
Closing as this is supported by Torii and can be integrated in ESA via the Torii authenticator as mentioned above.

**Comment by drewcovi** [comment]
👍
