### ISSUE TITLE
Adding a custom session store requires an app.js

### ISSUE THREAD

**Issue by arschmitz** [simplabs/ember-simple-auth#1088]
When i add a custom session store ( which the docs say must be named application.js ) the build fails with file not found `session-stores/app.js `

**Comment by marcoow** [comment]
Any more info on this?

* Ember CLI/ESA versions
* stack
* contents of `session-stores/application.js`

Are you maybe trying to import `session-stores/app.js` somewhere yourself? ESA does use `session-stores:application` but certainly never `app`.

**Comment by marcoow** [comment]
Closing due to lack of feedback.
