### ISSUE TITLE
Automatically logged out after refresh

### ISSUE THREAD

**Issue by anthonycollini** [simplabs/ember-simple-auth#1090]
I am having this issue where the system is logging me out. I have found a pattern that causes it. A logged out user makes an unauthorized call the to the API, then logs in. The next refresh will log you out. I can't see anything in my code, or anything that jumps out that would cause this. My local storage looks fine before and after logging in.

- Before logging in:
```
{"authenticated":{}}
```

- Make an authenticated call.

- After logging in:
```
{"authenticated":{"authenticator":"authenticator:oauth2-gateway","access_token":"XXXXX","token_type":"bearer","expires_in":600,"refresh_token":"XXXXXX","created_at":1477929759,"expires_at":1477930359010}}
```

- Refresh, and it logs you out of the ember app

**Comment by owldesign** [comment]
@anthonycollini does local storage still have `authenticated` object set or is it cleared out after refresh? Is `oauth2-gateway` a custom authenticator, I don't see it in the list of built in once?

I recently had a similar issue with my custom authenticator, in my case I missed setting up the `restore(data)` method. 

I think when page refreshes `restore` gets run with the data from your `authenticated` object, it needs to return a resolved promise with passed data `resolve(data)`. See this example [authenticators/oauth2-password-grant.js](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L162)

Again, that is what I ran into and it sounds similar, good luck!

**Comment by jfschaff** [comment]
Hi guys! And thanks! I had a similar issue with a custom Torii provider, in which I had not implemented the `fetch` function, which is called by ESA `restore`. Implementing `fetch` fixed it!

**Comment by marcoow** [comment]
@anthonycollini: any more info on this? Particularly, can you share the code of your custom authenticator?

**Comment by marcoow** [comment]
Closing for lack of feedback

**Comment by jamiechong** [comment]
@marcoow I'm having a similar issue. Using a custom authenticator. When I login, I can see the localStorage is set correctly, but when I refresh the page, the localStorage is wiped clean. I never see the `restore` method of my authenticator called (likely because on page load the localStorage data is missing).

**Comment by marcoow** [comment]
> I never see the restore method of my authenticator called (likely because on page load the localStorage data is missing).

Yes, that sounds like a good explanation. Please post the source of your Authenticator and the session store definition. Also, which ESA Version are you using?

**Comment by jamiechong** [comment]
@marcoow Hmm... I assumed the session store was setup with some default. Do I need to explicitly set something here? If so I may have missed that in the docs. ESA version is current (just installed today).

**Comment by jamiechong** [comment]
Regardless here's my authenticator (using AWS Cognito)

```
/* global AWSCognito */
import Ember from 'ember';
import ENV from '../config/environment';
import Base from 'ember-simple-auth/authenticators/base';

const Promise = Ember.RSVP.Promise;
const Cognito = AWSCognito.CognitoIdentityServiceProvider;

const userPool = new Cognito.CognitoUserPool({
  UserPoolId: ENV.APP.AWS.Cognito.poolId,
  ClientId: ENV.APP.AWS.Cognito.clientId
});

function cognitoUser(username) {
  return new Cognito.CognitoUser({
    Username: username, 
    Pool: userPool 
  });
}

export default Base.extend({
  restore(data) {
    console.log('restore session');
    return new Promise((resolve, reject) => {
      if (data.user) {
        data.user.getSession((err, session) => {
          if (!err && session.isValid()) {
            data.session = session;
            resolve(data);
          } else {
            reject();
          }
        });
      } else {
        reject();
      }
    });

  },

  authenticate(username, password) {
    console.log('authenticate');
    return new Promise((resolve, reject) => {
      cognitoUser(username).authenticateUser(new Cognito.AuthenticationDetails({
        Username: username,
        Password: password
      }), {
        onSuccess: (session) => resolve(session),
        onFailure: (err) => reject(err)
      });
    }).then(session => {
      return {
        user: userPool.getCurrentUser(),
        session: session
      };
    });

  },

  invalidate(data) {
    console.log('invalidate');
    if (data.user) {
      data.user.signOut();
    }
    return Promise.resolve();
  }
});
```

**Comment by jamiechong** [comment]
@marcoow Some more info that _might_ be relevant. In Chrome developer tools, while viewing the Application tab and looking at Local Storage: data is stored at `ember_simple_auth-session`. If I attempt to _delete_ this item, it's instantly regenerated and set to: `{"authenticated":{}}`.  Is there some polling happening? Perhaps on page refresh the polling preempts or overwrites the persisted key with an empty object?

**Comment by jamiechong** [comment]
@marcoow 
I traced it to `internal-session.js::setUnknownProperty`, which, upon page load, calls `_updateStore`, which calls `persist` with `this.content`, but the content is `null`.  The `persist` method trashes the localStorage because it's given `null` to persist. 

If I comment out `this._updateStore` in the  `setUnknownProperty` method, then reloads seem to work, but clearly I have no idea what the consequence of that is.

It seems like `_updateStore` is called _too_ early via `setUnknownProperty`, before the `content` property is set within `internal-session`. Some sort of chicken/egg issue perhaps.

`setUnknownProperty` is called twice, while loading the page. With these keys: `__OWNER__` and `__NAME_KEY__`. 

Hopefully with this you can debug and figure out a fix! Have you been able to reproduce the error? 

Let me know if you need more info!

**Comment by marcoow** [comment]
It seems you're trying to store the `Cognito.CognitoUser` object in the session which won't work. You can only store POJOs with atomic members (strings, ints, etc.) in the session. In your case you might be able to store some sort of ID in the session (e.g. resolve with that from the authenticator's `authenticate` method) and then restore the user from that in the `restore` method.

**Comment by jamiechong** [comment]
@marcoow I did end up changing to just storing my token. Everything is work fine right now with the code I have in the PR.
