### ISSUE TITLE
component trigger is not a function

### ISSUE THREAD

**Issue by cmartinez84** [simplabs/ember-simple-auth#1091]
i have followed this four time to the T, checking my project's status along the way, and when i get to writing the js for the log-in component my page then refuses to load and i am stuck with "component.trigger is not a function(…)". deleting my component js or even removing with the command line does not remedy my project and i have to revert back to an old function. thoughts?

**Comment by marcoow** [comment]
This is either unrelated or if not impossible for anyone to help you with as you provide 0 detail. See the contribution guidelines.
