### ISSUE TITLE
How can I customize time to send refresh_token request?

### ISSUE THREAD

**Issue by ServiceTo** [simplabs/ember-simple-auth#1094]
I've updated my API to use Laravel's Passport OAuth2 library and now the issue I'm seeing is that the ember-simple-auth code is sending refresh token requests at the same as they expire so pretty often the session is invalidated since it gets revoked in the same second the request comes in to refresh.

Other than making longer timeouts for the tokens, is there a way to have ember-simple-auth refresh tokens 10 seconds or so before they expire?

**Comment by marcoow** [comment]
What's the server response for token requests?

**Comment by ServiceTo** [comment]
`{"token_type":"Bearer","expires_in":900,"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImEwNGU5YTkxZTM3NGM0YjE2ZTc2ODEwOWI3NDdkZTBjNmE2MTE2OTM1ZDA1NDIzZWNkOGY5ZDQ1ZmYwYjY2NzQ2NWM1NmFkNTM3YTFhYmQwIn0.eyJhdWQiOiIzIiwianRpIjoiYTA0ZTlhOTFlMzc0YzRiMTZlNzY4MTA5Yjc0N2RlMGM2YTYxMTY5MzVkMDU0MjNlY2Q4ZjlkNDVmZjBiNjY3NDY1YzU2YWQ1MzdhMWFiZDAiLCJpYXQiOjE0Nzg2MjQxOTYsIm5iZiI6MTQ3ODYyNDE5NiwiZXhwIjoxNDc4NjI1MDk2LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.fpa4oxX_ydbxobdBzo05riRJgz7j-T-Oc0nauv8dqqXR3HAngg6RJcQTvt2dXQo58fad4oYrroLzzvcQRmi7sHbvq8XUBob7ClHCGBSXdzowr1BREftyyaeU-SmGoVwht4ST9TC8LVQXUucZ33rUlIJBFknmtY9IaYChVcVQ9GG3kkduCKvo3HMJxtEh4CC_SNeVAWuLTWPwAWjg-8HoNSsh3BfUGvy-WDI_3FPPUZyvrHrInTZZq9Vjqlh_1jIR0zXaml78OGD8JUPnfOwAe--r3tRZniAa7DBppkjbjDk7mWdsSkn0huhCJdS2jClLuu2WW4kEfBXHWwiVWo3oLwG317_0RCPLUMUnEQYJUFow56tkYTCPrOK9y61jC3XGmCu9ROJmIlAmm_mxwMmRNay4_aYpcV7isHN7UJWh2P7pfzgOtJuyLaoPTPQjnXie6IyYmdU7Do15TjUShAjus1cJ-yt6E6v5aLYyl9ym0ztjHml08XOnbYn4W0QqX-gLSyy1qvtt1MLD4IZHMJLfH8xIGhd2QKx6AMjy936ohqPtUYTwvufPowCmxVg8KKXIFn4AU9xWGZLKRaa2Zrj3fXvkTTdYzrvFOB7ZcDi1zt18phLqWxqZuUzJTCKKiGlbKDv2q1I8fXaLEY41YnOO3X4MUQKNq390moT_nN1C6T4","refresh_token":"YLo+ZNGw4qI\/UiniCJlzs4DtQWsyBKYErM6gQBJ1lIXmMmY66oDUJqeRm8LQ6eEqviP8xdQlmXCs6OYthGL1Mk\/vJru8cP4BkJasFjaJHRxiyN2WWh2641asDPkHJmCNYDlaY6Fyz\/x0onzmKZ\/goPdC810fMl80hLPcd91+Ig3rBXrmv2bFlXnd6+mWjMPVUwQWf9rD19ke2Eg+x1z4iMwMf07CKI25Swi8oPKjNWgrGaz4T98JgkFH5vu6y64TPM2UZNLIm2ik\/YgFPme4ny58TE4kFZHh1noQ1ctnoRJbN+N+gbDE3CVJIHdZaFh\/pPQ5DDkB4vkn970VtLuUXn2ny2JG89bIIevgC6YjZFUWdOXqdaN1FeK1BzR6ox36DaIx2nxfZiFA3psBYB85JIGSi2ZhzyOTl8CezDrXxHrh3uHzVFXfTeM\/r7qfegbvVYw5Q\/S3U1q7Q5CGKIR5kon3AtL5AfhCs6J0An94lmD6gsG0v\/DpQCP1wKS2BgflZxiRj0Bijud2tTD2LW9fdAV5v0leDQ4N+uy13SFZPwzaNQPzgCGsLwE+hfGm47uPzU+a\/GQFrejULkNxFykpcuAP1PGQuMr9lCZ3Mj9jn0fxzGbdbsbrMe2CZfR3EOplJ2hCOpFk8GSX+3c7eNs1q92agmtA4++hWrTx1no0zjM="}`

**Comment by marcoow** [comment]
ESA should actually send the refresh request with a random offset between 5 and 10 seconds before the actual token expiration time - see https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L323

**Comment by ServiceTo** [comment]
Cool, so if I can add an offset on that end that would fix this up perfectly, I'll see what I can do.  Thanks for the prompt responses.

**Comment by marcoow** [comment]
No, this might be a bug - ESA should always send the refresh requests between 5 and 10 seconds __before__ the actual expiration time.

**Comment by ServiceTo** [comment]
Ah, gotcha, anything I can do to help debug?

**Comment by marcoow** [comment]
dummy app showing the error is always super helpful

**Comment by marcoow** [comment]
> So can I prevent requests from being sent while tokens are being updated?

ESA doesn't offer any functionality for that.
