### ISSUE TITLE
Authenticate with already known token

### ISSUE THREAD

**Issue by ivandokov** [simplabs/ember-simple-auth#1095]
A really useful functionality will be to add a method to authenticate with already known token.
For example if you get the token from a GET variable you should be able to authenticate with this token.
I've searched the documentation but I cannot seem to find such method except for the tests helpers, but I don't think they have to be used outside tests.

**Comment by marcoow** [comment]
You can simply create your own authenticator for that that can read the token from somewhere and authenticate the session with it.
