### ISSUE TITLE
Send a param to invalidate

### ISSUE THREAD

**Issue by hajjem-ayoub** [simplabs/ember-simple-auth#1096]
inside the custom authenticator i want my invalidate function to receive a param that i send by calling 
this.get('session').invalidate(myParam);
this is used to have a different behaviour from where i invalidate, i have a logout and a deactivateMySelf that should have different behaviour

**Comment by hajjem-ayoub** [comment]
i did add the ...arguments inside my local dev environment and i can make a pull request, if feature is approved.

**Comment by marcoow** [comment]
This is already handled in #1093 - feel free to reach out to @leuprechtroman and collaborate on that!

**Comment by hajjem-ayoub** [comment]
Yes thanks, that's exactly what i also did :)
