### ISSUE TITLE
New parameters documentation in testing helpers

### ISSUE THREAD

**Issue by DylanGuedes** [simplabs/ember-simple-auth#1100]
So, I'm trying to test my application and can't find the proper way to use the acceptance helpers, because the API now needs the "app" parameter and I can't find anywhere what is this attribute for. I followed [this](http://simplabs.com/blog/2014/07/25/testing-with-ember-simple-auth-and-ember-cli.html) post, that worked great except that the API changed a little and now I need to pass this "app" parameter. So, can you guys write in the [Testing](https://github.com/simplabs/ember-simple-auth#testing) session about it? 

Thank you so much!

**Comment by marcoow** [comment]
See the example acceptance tests in the dummy app: https://github.com/simplabs/ember-simple-auth/blob/master/tests/acceptance/authentication-test.js.

Your're right about the README though - there should be an example in the testing section.

**Comment by DylanGuedes** [comment]
Thank you so much! Actually I looked for examples in the dummy app, instead of the 'tests' repo.

**Comment by redbmk** [comment]
The test you linked to also seems to be set up quite a bit differently than they suggest in the [ember docs](https://guides.emberjs.com/v2.10.0/testing/acceptance/) (which is also more like what is generated via `ember g acceptance-test routename`). How would you do this when using `moduleForAcceptance`?

Do we also need to do something with the environment config like explained in the deprecated [ember-cli-simple-auth-testing](https://github.com/simplabs/ember-cli-simple-auth-testing) package?

**Comment by DylanGuedes** [comment]
Hi,
Maybe the question was directed to @marcoow, but otherwise, I writed the tests using `moduleForAcceptance` and it worked pretty ok - the setup was pretty much done with the `authenticateSession` mock that needs the `app` parameter (that is mainly a result of `startApp()` method - startApp is imported from `helpers/start-app`). I don't think that you need any additional setup to mock login, really.

**Comment by redbmk** [comment]
I'm not sure what I'm missing then. This is how I wrote it for an authenticated route, but it doesn't work. In this test, I get `/myroute` each time (i.e. the 1st and 3rd assertions fail, but the 2nd passes). However, when actually using the app it works as expected (If I'm not logged in I get kicked back to `/`, and if I am logged in I can visit `/myroute`).

```
let application;

moduleForAcceptance('my module', {
  beforeEach() {
    application = startApp();
  },
  afterEach() {
    Ember.run(application, 'destroy');
  }
});

test('requires authentication', function(assert) {
  visit('/myroute');

  // because unauthenticated routes should send the user back to "/"
  andThen(() => assert.equal(currentRoute(), '/'));

  authenticateSession(application);

  visit('/myroute');
  andThen(() => assert.equal(currentRoute(), '/myroute'));

  invalidateSession(application);
  andThen(() => assert.equal(currentRoute(), '/'));
});
```

**Comment by DylanGuedes** [comment]
Hmm I used the 2nd parameter in my tests, maybe you should try it too. [Here's one](https://github.com/DylanGuedes/fgapp-testdrive/blob/master/tests/acceptance/user-test.js) test that I did (the repository isn't up to date, but the test can be helpful). The only relevant difference that I see is the 2nd parameter in `authenticateSession`, really.

**Comment by redbmk** [comment]
Hmm, yeah I tried cloning that repo and it seems pretty broken. That test doesn't pass either - it's getting "signin" as the current route instead of "users". That's not too far off from what I'm doing, but for me it seems to be doing the opposite - getting to a route that requires authentication even before I authenticate the session.

**Comment by DylanGuedes** [comment]
It was just for reference, sorry - the repository isn't up to date for a while, but I tough that the tests used to pass. Do you tried to use the 2nd parameter in `authenticateSession?` I remember it doing the trick for me.

**Comment by marcoow** [comment]
The way the acceptance tests in the ESA repo itself are written is the old way basically - using `moduleForAcceptance` and omitting `startApp` and `destroyApp` is essentially the same thing (have a look at the generated `tests/helpers/module-for-acceptance.js`).

It would be great if someone could create a PR updating the tests to use `moduleForAcceptance` and another one adding a testing example to the testing section in the README.

**Comment by marcoow** [comment]
I removed this from the 1.3 milestone so we don't block release of that waiting for this to be completed.

**Comment by jessica-jordan** [comment]
We added another section explaining how to use the `simple-auth` test helpers together with the testing API provided by `ember-cli-qunit < v.4.1.0` for reference [in the README](https://github.com/simplabs/ember-simple-auth#ember-cli-qunit-410-and-earlier)
