### ISSUE TITLE
Clearing session.data.XXX after rejecting in restore()

### ISSUE THREAD

**Issue by kaiwah** [simplabs/ember-simple-auth#1101]
In my restore() function on the custom authenticator, I resolve/reject the session based on their token. On the instances that I reject the session, the `session.data.authenticated` clears out but leaves in tact everything else. I want to manually clear this data, is there any way to do this?

Doing `this.set('session.data', {authenticated:{}});` works but when you try to re-authenticate within the same instance, it cannot write into the `session.data.authenticated` so the application goes into a 'empty' state where they're logged in but missing all the data.

Calling `this.invalidate();` does work but it clears everything including things I need. I just need to clear our 3-4 keys within `session.data.xxx`.

I've been trying to find documentation or open/closed issues on this but can't seem to find a solution to this. Any help would be appreciated!

**Comment by marcoow** [comment]
You can implement the [`sessionInvalidated` method on the application route](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionInvalidated) and unset the session data keys there.
