### ISSUE TITLE
redirectUri functionality broken/confusing?

### ISSUE THREAD

**Issue by mdbr000** [simplabs/ember-simple-auth#1102]
My super simple test app does not redirect to the desired URI after authentication using the torii:google-oauth2 wrapper provided by ember-simple-auth.  I'm at the end of my rope on this one.  Seems like it should just work, right?

I've stepped through the code multiple times, going deep into the ESA and torii libraries, and cannot figure it out.  The popup window to google opens, obtains an auth code, and stores it in local storage, but the redirect is not performed after the popup window closes.  ESA should be taking me to the 'protected' route at that point, but it just sits on the login page.

```
// config/environment.js
  ENV.torii = {
    providers: {
      'google-oauth2': {
        apiKey: '2983948905-p886jmjpam371fjoitktoec8hretkoo8.apps.googleusercontent.com',
        redirectUri: 'http://localhost:4200/protected',
      }
    }
  };
...
  ENV['ember-simple-auth'] = {
    routeAfterAuthentication: 'protected'
  };
```

```
// controllers/application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),

  actions: {
    invalidateSession() {
      this.get('session').invalidate();
    }
  }
});
```

```
// controllers/login.js
import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),

  actions: {
    authenticate() {
      this.get('session').authenticate('authenticator:torii', 'google-oauth2');
    }
  }
});
```

```
// authenticators/torii.js
import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii';

export default ToriiAuthenticator.extend({
  torii: Ember.inject.service(),
});
```

```
// templates/application.hbs
{{!-- app/templates/application.hbs --}}
<div>
  {{#if session.isAuthenticated}}
    <a {{action 'invalidateSession'}}>Logout</a>
  {{else}}
    {{#link-to 'login'}}Login{{/link-to}}
  {{/if}}
</div>
<div class="main">
  {{outlet}}
</div>
```

```
// templates/login.hbs
<div {{action 'authenticate'}}>Login with Google</div>
{{outlet}}
```

**Comment by marcoow** [comment]
Are you mixing in the `ApplicationRouteMixin` in your application route? [These lines](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/application-route-mixin.js#L98) should redirect to the correct route after the session becomes authenticated.

**Comment by mdbr000** [comment]
Ah, yes.  My mistake!  Sure enough, the issue was not applying the `ApplicationRouteMixin` appropriately to the application route.

For those who may have eyes as bad as mine, here's the [ApplicationRouteMixin API documentation](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html), and the relevant lines from [the walkthrough section of the README.md](https://github.com/simplabs/ember-simple-auth#walkthrough):

> The session service also provides the authenticationSucceeded and invalidationSucceeded events that are triggered whenever the session is successfully authenticated or invalidated (which not only happens when the user submits the login form or clicks the logout button but also when the session is authenticated or invalidated in another tab or window of the application). To have these events handled automatically, simply mix ApplicationRouteMixin into the application route:

Many thanks @marcoow. :)
