### ISSUE TITLE
Should allow us to change name of submitted parameter away from user_token

### ISSUE THREAD

**Issue by joelpresence** [simplabs/ember-simple-auth#1103]
Hi,

I'm using Knock as my JWT gem on my rails-api backend.  It expects the email and password to come in on a param mapped from key `auth` but ember-simple-auth uses `user_token`.  I can't find any way to change this in ember-simple-auth.  I want to change ember-simple-auth so that instead of submitting
```
"user_token": { "email" : "the_email", "password": "the_password" }
```
as the POST params, it should instead send
```
"auth": { "email" : "the_email", "password": "the_password" }
```

As it stands, I have to munge the params on the server side with a before_filter to set `params[:auth] = params[:user_token]` but this feels hacky.

I have searched and can confirm that I am not using the key `user_token` anywhere in my Ember code, so ember-simple-auth is somehow using it.  But I grep'd and can't find where ..

I need this to be a config option: to change the send param name to be something like `auth` if desired.

Any hints!  :-)

Thanks

**Comment by marcoow** [comment]
You should be able to configure what you describe by overriding the [`DeviseAuthenticator`'s respective properties](http://ember-simple-auth.com/api/classes/DeviseAuthenticator.html#property_identificationAttributeName).
