### ISSUE TITLE
How to redirect to login route after logout?

### ISSUE THREAD

**Issue by joelpresence** [simplabs/ember-simple-auth#1107]
Hi,

I have ember-simple-auth working with JWT against a Rails API.  All is good, thanks for this awesome addon!

However, I would like to do the following when the user logs out:
- perform the normal `sessionInvalidated` that comes with `ApplicationRouteMixin`
- then redirect to the login route.

I can't seem to get this working.

My current configuration is:
```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
import config from '../config/environment';

export default Ember.Route.extend(ApplicationRouteMixin, {
  session: Ember.inject.service(),
  localUser: Ember.inject.service(),

  sessionInvalidated() {
    this.__super();
    this.transitionTo('login');
  }
});
```
But this seems to go nuts and talk about "route undefined" and such.  I think the transitionTo is happening before the __super method (which is ESA code that resets the window location to the app base url) and something is getting confused.  I'm not sure how to do this ... Can somebody give me some hints and I'd be happy to update the Wiki with an example through a PR?

I have also done:
```
  sessionInvalidated() {
    this.get('store').unloadAll();
    this.transitionTo('login');
  }
```
but I'm not sure how secure this is - it unloads the store, but the comment in [the default ESA sessionInvalidated code](https://github.com/simplabs/ember-simple-auth/blob/1.1.0-beta.3/addon/mixins/application-route-mixin.js#L94) says "all in-memory data (such as Ember Data stores etc.) gets cleared" and I'm not sure that unloadAll on the store "clears all in-memory data" like changing the window location (reloading the Ember app) would ...

I also tried mixing in *both* `ApplicationRouteMixin` and `AuthenticatedRouteMixin` to the application, but then ESA gets stuck in an infinite loop, pegs my CPU at 100% and I have to force quit the browser tag ...

I'm not saying there's a bug here, but I'm looking for some guidance on this common use case.

I'd rather leave things as is and not factor out the login into a shared component, so I'm looking to just redirect to the login route after `window.location.replace(Configuration.baseURL);` is complete ...

Any help would be hugely appreciated!  :-)

**Comment by marcoow** [comment]
> I also tried mixing in both ApplicationRouteMixin and AuthenticatedRouteMixin to the application, but then ESA gets stuck in an infinite loop, pegs my CPU at 100% and I have to force quit the browser tag ...

You can't use the `AuthenticatedRouteMixin` in the application route as then **all** of your application would require authentication, including the login route so that you'd have to be logged in in order to access the login route.

Also when doing this

```js
sessionInvalidated() {
  this.__super();
  this.transitionTo('login');
}
```

you're combining the code from the [`ApplicationRouteMixin` which will reload the app](https://github.com/simplabs/ember-simple-auth/blob/1.1.0-beta.3/addon/mixins/application-route-mixin.js#L109) with the transition which will most likely lead to weird behavior as you're triggering a route transition while the app is already being unloaded.

If you want to redirect people to the `/login` route after they log out, you could do sth. like

```js
sessionInvalidated() {
  if (!testing) {
    window.location.replace('/login');
  }
}
```
