### ISSUE TITLE
Replace baseURL by rootURL

### ISSUE THREAD

**Issue by urbany** [simplabs/ember-simple-auth#1108]
Hi, if rootURL is defined instead of baseURL, the rootURL should be used instead of the baseURL in: https://github.com/simplabs/ember-simple-auth/blob/726e59bb3c966a2f5cab5075a510a165f8c7a46c/addon/mixins/application-route-mixin.js#L123

**Comment by marcoow** [comment]
see #1048, #1051, #1070
