### ISSUE TITLE
Cannot use multiple authorizers , eg; facebook and devise

### ISSUE THREAD

**Issue by talhaobject90** [simplabs/ember-simple-auth#1111]
The structure of my app is like 

I am using dataadapter mixin and it should directly configure the authorizer there.

Ember App:

                    Authentication:                 

 -------facebook authenticator with torii from ember-simple-auth
----- devise authenticator with ember-simple-auth-devise

Rails side
------Devise for authenticating with  with ember-simple-auth-devise  
------Rails_api_auth to authenticate facebook with torii from ember-simple-auth.

Question:
How to configure the adapter  to use which authorizer based on the authentication type(facebook / devise)

i tried like this, but no luck

```
// adapters/application.js


import Ember from 'ember';
import DS from 'ember-data';
import ENV from '../config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
const { inject: { service } } = Ember;
export default DS.JSONAPIAdapter.extend(DataAdapterMixin,{
  session: service('session'),
  host: ENV.APP.host,
  
 headers: Ember.computed('session.authToken', function() {
    return {
      'Authorization': ' Token ' + 'token="'  + this.get('session.data.authenticated.token') + '", email="' +  this.get('session.data.authenticated.email') +'"',

    };
  }),

  authorizer: 'authorizer:application'
});
```

```
//authorizers/application.js

import OAuth2Bearer from 'ember-simple-auth/authorizers/oauth2-bearer';

export default OAuth2Bearer.extend();
```

```
authorizers/devise.js
import DeviseAuthorizer from 'ember-simple-auth/authorizers/devise';

export default DeviseAuthorizer.extend({
  actions: {
    authorize: function(){
      this.get('session').authorize('authorizer:devise', () => {
      });
    }
  }
});

```

and it would be helpful if someone could tell me how rails could understand the incoming request and handle them based on authorizations, (token method / bearer method).

Right now rails -devise uses 
```
  before_filter :authenticate_user_from_token!
   before_filter :authenticate_user!
```
And rails_api_auth prescribes this method
```
  include RailsApiAuth::Authentication
  before_action :authenticate!
```

**Comment by srvance** [comment]
The `headers` CP in your application adapter might be overriding what the authorizer is injecting.

The way I would do this is have an `authorizers/devise.js` and an `authorizers/facebook.js` and reference the appropriate one from each adapter. It's a bit of a PITA as `ember-data` seems a bit weak on the multiple data source story. You could have one be the primary and use the application adapter and authorizer, but at least one of them is going to have to exhaustively have an adapter for each model that references the secondary authorizer.

**Comment by lcpriest** [comment]
Ugly workaround:

- Authenticate with torii (I use Google OAuth2)
- Exchange tokens on the server and return { token: token, email: email }
- Add token and email to the authenticated data that ember-simple-auth use
- And set the authenticator as 'authenticator:devise' (this is the dirty part), on refresh Ember will reauthorize just fine.

**Comment by talhaobject90** [comment]
could anyone please give me an example?

**Comment by marcoow** [comment]
Closing this as it's out of scope for ESA. Generally, questions like this are better suited for stackoverflow.com (there's an _"ember-simple-auth"_ tag).
