### ISSUE TITLE
How to restore session from token of cookies

### ISSUE THREAD

**Issue by kaermorchen** [simplabs/ember-simple-auth#1112]
Hello.

I have external login/logout html pages, which create cookie token if user is authenticated, not user data, only token.

I created authenticators/appication.js file which has all needs methods (restore, authenticate, invalidate) and I understand how they should work. Authenticate method do redirect to login external page and invalidate method do redirect to logout external page. Restore method shoul check if cookies has token, then load a user's data. 

But I don't understand how can I init restore function in authenticator, if localStorage has only 
```
ember_simple_auth:session -> {"authenticated":{}}
```

if I change it manually to 
```
ember_simple_auth:session -> {"authenticated":{"authenticator":"authenticator:application"}}
```
it work fine

How can I set default authenticator if user isn't authenticated? Or what should I do?

**Comment by jeroenhouben** [comment]
Maybe my problem is related. This used to work, maybe it stopped working on Ember 2.10 (I was on 2.9)

My problem:

I'm logged succesfully via Facebook Connect. 

![image](https://cloud.githubusercontent.com/assets/10760/20859307/3f42ad24-b95b-11e6-848a-38c81bc69d73.png)

Then I refresh my browser.
this.get('session.isAuthenticated') still returns TRUE

but the data doesn't contain the access_token etc anymore:

![image](https://cloud.githubusercontent.com/assets/10760/20859302/1a71426c-b95b-11e6-8196-bc3b268397e2.png)

**Comment by marcoow** [comment]
This is more suited for stackoverflow.com actually.
