### ISSUE TITLE
Handle large cookies / Check whether cookie save was successful

### ISSUE THREAD

**Issue by abirtley** [simplabs/ember-simple-auth#1113]
Many browsers have a max cookie size (eg, 4096 bytes). If the `authenticated` data object returned by an authenticator is large enough, the resulting cookie can be too large to save. 

On Chrome 54.0.2840.98, the [attempt to write this cookie](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L195) fails, but ember-simple-auth currently doesn't detect this failure. The flow-on effect is that [when _syncData is next called](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L207), it detects a change (because while the main cookie failed, the [cookieExpirationTime cookie was set successfully](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L201)), and without the main cookie, it logs the user out.

In an ideal world, ember-simple-auth would handle this automatically behind the scenes, eg by splitting the data over multiple cookies and reassembling them again later.

In a more realistic world, ember-simple-auth might detect cookie-writing failure, and send an appropriate error back to the application to make debugging easier. 

At the least, the docs could warn that when using the cookie store to be mindful of data sizes, and consider saving additional information in separate cookies.

Needless to say, this problem does not occur when using local storage.

Happy to submit a PR for documentation change, but I couldn't find them in the repo.

On the whole though, great plugin, very helpful.

---
Other details:
ember-simple-auth version: #274f0e7
operating system: OSX 10.12 (Sierra)
browser: 54.0.2840.98 (64-bit)
reproduction steps:

1. Use cookie session storage
1. Create a custom authenticator
1. Implement `authenticate` to resolve with a very large object, eg one containing very long strings
1. Try to log in
1. Observe that the user is successfully logged in, then immediately logged out

**Comment by marcoow** [comment]
Yeah, good point. I think mentioning the maximum cookie size in the docs would be a good idea. Maybe there should also be an assertion in the code.

> In an ideal world, ember-simple-auth would handle this automatically behind the scenes, eg by splitting the data over multiple cookies and reassembling them again later.

I'm actually not sure this is a good idea as it would add a ton of complexity to ESA. Storing more data in the cookie is an antipattern anyway IMO.

**Comment by geekygrappler** [comment]
This is fixed now in version 1.6 of ESA as `ember-cookies` will now check for max 4kb cookie size.
