### ISSUE TITLE
TypeError: Cannot read property 'container' of undefined

### ISSUE THREAD

**Issue by XavG** [simplabs/ember-simple-auth#1119]
Hi, 
So I'm trying to test my ember application.
But I have some pages which require authentification.
I used ember-simple-auth with firebase, so for the test , I followed the ember-simple-auth documentation.

config:
```
if (environment === 'test') {
		ENV['simple-auth'] = {
			store: 'simple-auth-session-store:ephemeral'
		};
```

my test : 
```
...
import {
	currentSession,
	authenticateSession,
	invalidateSession
} from 'tpjsv2login/tests/helpers/ember-simple-auth';
....

test('should access /vehicule if authenticate', function (assert) {
	authenticateSession();
	visit('/vehicule');

	andThen(function () {
		assert.equal(currentURL(), '/vehicule');
	});

});
```
And I have the following issue in my test : 
`TypeError: Cannot read property '__container__' of undefined`
Thanks for your help !
Xavier

**Comment by marcoow** [comment]
Is this on the current master branch?

**Comment by XavG** [comment]
I'm on the "ember-simple-auth": "1.1.0".
Yes I think it is.

**Comment by marcoow** [comment]
> I'm on the "ember-simple-auth": "1.1.0".
> Yes I think it is.

so are you on `master` or 1.1.0 then ;)

**Comment by XavG** [comment]
I just update it, I'm on the **1.2.0-beta.1** version.

**Comment by marcoow** [comment]
You need to pass the application instance to the `authenticateSession` helper method (and all other helper methods that ESA provides):

```js
authenticateSession(this.application);
```

**Comment by XavG** [comment]
Thank you !!!
Its working :)

**Comment by sumn2u** [comment]
@marcoow so what if anyone wants to use the custom test helper and use it as session. for example i can define a test helper named get-login-token.js which goes through login page and in my application we do have define ember-simple-auth. 

Now can't i use that helper ? It seems to be working on 0.8.0 but at that time i need to  use ember-simple-auth-testing . I cant do same thing in ember simple auth 1.0 ? why is that ?

**Comment by marcoow** [comment]
I'm not sure what you're asking.

**Comment by sumn2u** [comment]
Sorry my question was not so clear above. I have a file name get-login-token.js which is a test helper.
```
import Ember from 'ember';
import { invalidateSession, authenticateSession, currentSession } from 'suman-web/tests/helpers/ember-simple-auth';

export default Ember.Test.registerAsyncHelper('login', function(app, assert, email, password) {
email = email || 'suman-test@mail.com';
	password = password || 'test-1';
  visit('/login');
	fillIn('input.login-email', email);
	fillIn('input.login-password', password);
	click('button.login-submit');
  andThen(()=> {
    assert.ok(currentRouteName() === 'discover' || currentRouteName() === 'welcome', 'logged in successfully...');
  });
});
```
And this test helper is called in module-for-acceptance.js 
```
import { module } from 'qunit';
import startApp from '../helpers/start-app';
import destroyApp from '../helpers/destroy-app';

import fetchValidToken from './get-login-token';
export default function(name, options = {}) {
  module(name, {
    beforeEach() {
      this.application = startApp();

      if (options.beforeEach) {
        options.beforeEach.apply(this, arguments);
      }
    },

    afterEach() {
      destroyApp(this.application);

      if (options.afterEach) {
        options.afterEach.apply(this, arguments);
      }
    }
  });
} 

```
And i am using that same helper for numerous of my other test case. Eventually what it does is it logins the user and get the token and that token is used in other API request so far it was working in ember-simple-auth but when i migrate to 1.2.0 its seems to so me 
`TypeError: Cannot read property '__container__' of undefined`

```
import { test } from 'qunit';
import { invalidateSession, authenticateSession, currentSession } from 'suman-web/tests/helpers/ember-simple-auth';
moduleForAcceptance('Acceptance | add email to suppression list');
test('open Personal Restriction form', function(assert) {
	fetchValidFuseprospectorToken(assert);
      ///and my rest logic 
```
Its working fine in 0.8.0 but not with new version.

**Comment by marcoow** [comment]
Hm, it doesn't look like you're using neither the `fetchValidToken` nor any of the `invalidateSession`, `authenticateSession`, `currentSession` helpers anywhere. What the error you're seeing probably means though is that you're calling one of the latter helpers without passing the application instance as the first argument.

**Comment by sumn2u** [comment]
I just updated my code sorry for that it should be `fetchValidToken`. If i do `authenticateSession(this.application)` in helper it will generate sessions but for my case I need to use the session value provided after login. Is there any way i can achieve this?

**Comment by marcoow** [comment]
> but for my case I need to use the session value provided after login

I'm not sure what you mean actually. `authenticateSession` and the other helpers need the application instance as their first argument or they will raise an error. You can specify a custom session content as the second argument but that's optional.

**Comment by sumn2u** [comment]
Thank you . I think I got it where I was missing.

**Comment by fuse-mars** [comment]
@marcoow by **helpers need the application instance**, you mean
```
...
import { invalidateSession, authenticateSession, currentSession } from 'suman-web/tests/helpers/ember-simple-auth';

// delete the session
invalidateSession(this.applicationInstance)

// get current session
currentSession(this.applicationInstance)
...
```
The reason I am asking is because i remember using `invalidateSession()` without any arguments and the test worked well!

**Comment by marcoow** [comment]
@fuse-mars: all of the test helpers use the `container` property that's defined on the application instance and will throw an error if the application instance is not passed: https://github.com/simplabs/ember-simple-auth/blob/master/test-support/helpers/ember-simple-auth.js

**Comment by fuse-mars** [comment]
oh i see, that makes sense thx!

**Comment by paulbhartzog** [comment]
> You need to pass the application instance to the authenticateSession helper method (and all other helper methods that ESA provides):
> 
> authenticateSession(this.application);

and

> all of the test helpers use the container property that's defined on the application instance and will throw an error if the application instance is not passed: https://github.com/simplabs/ember-simple-auth/blob/master/test-support/helpers/ember-simple-auth.js

Is this mentioned in some docs somewhere?  I lost several hours trying to find this out. :-(

**Comment by marcoow** [comment]
@paulbhartzog: see [README](https://github.com/simplabs/ember-simple-auth#testing)

**Comment by paulbhartzog** [comment]
> @paulbhartzog: see README

Totally weird that I didn't see that since I spent all day working with the README. :-D

**Comment by NullVoxPopuli** [comment]
so, I can use test helpers the clean way, if write my own async helpers and just wrap the simple auth ones...

but is there any way to import the helpers provided by this repo?
reason why I ask, is because when I do `currentSession().get('data.authenticated.token')` I get undefined.
where as if I import currentSession, build the application instance in my test manually, and then pass that to the ESA currentSession(), then I get a value.

Here is my helper:
```js
import Ember from 'ember';

import {
  currentSession
} from 'aeonvera/tests/helpers/ember-simple-auth';

export default Ember.Test.registerHelper('currentSession', function(app) {
  return currentSession(app);
});
```

and then:
```js
//tests/helpers/start-app.js
import Ember from 'ember';
import Application from '../../app';
import config from '../../config/environment';
// I'd like just import the ESA helpers here, and have them auto-register.

import './authenticate-session';
import './current-session';
import './logout';

export default function startApp(attrs) {
  let attributes = Ember.merge({}, config.APP);
  attributes = Ember.merge(attributes, attrs); // use defaults, but you can override;

  return Ember.run(() => {
    let application = Application.create(attributes);
    application.setupForTesting();
    application.injectTestHelpers();
    return application;
  });
}
```

**Comment by NullVoxPopuli** [comment]
omg, I just needed to pass data along with my authenticateSession Helper.... T_T

```js
import Ember from 'ember';

import {
  authenticateSession
} from 'aeonvera/tests/helpers/ember-simple-auth';

export default Ember.Test.registerAsyncHelper('authenticateSession', function(app, data) {
  authenticateSession(app, data);
});
```
