### ISSUE TITLE
Session seems to get invalidated upon refresh.

### ISSUE THREAD

**Issue by gin93r** [simplabs/ember-simple-auth#1120]
I'm using `google-oauth2`. The pop-up window appears, I click "Allow".

The "Login" button changes to "Logout" due to `session.isAuthenticated` being true:
```
{{!-- \app\templates\application.hbs --}}
{{#if session.isAuthenticated}}
<a {{action 'invalidateSession'}}>Logout</a>
{{else}}
<a {{action 'authenticateSession'}}>Login</a>
{{/if}}
{{outlet}}
```

Upon refresh, `isAuthenticated` returns false. I've noticed that my application doesn't show up in my Google Account's list of "Apps connected to your account" section either.

```
// \app\authenticators\torii.js
import Ember from 'ember';
import Torii from 'ember-simple-auth/authenticators/torii';

const { service } = Ember.inject;

export default Torii.extend({
  torii: service('torii'),
  authenticate(options) {
    return this._super(options).then(function (data)
    {
      alert(`authorizationCode:\n${data.authorizationCode}\nprovider: ${data.provider}\nredirectUri: ${data.redirectUri}`);
    });
  }
});

// \app\controllers\application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),
  actions: {
    authenticateSession()
    {
        this.get('session').authenticate('authenticator:torii', 'google-oauth2');
    },
    invalidateSession() {
        this.get('session').invalidate();
    }
  }
});

// \config\environment.js
var ENV = {
  /* ... */

  // torii configuration
  torii: {
    providers : {
      "google-oauth2": {
        apiKey: "MYAPIKEY.apps.googleusercontent.com",
        redirectUri: "http://localhost:4200/"
      }
    }
  }
};
```

Any thoughts? This is with v1.1.0

**Comment by gin93r** [comment]
I'm curious if it's related to #927. I looked at the local storage when authenticating and it does get set to 'authenticator:torii' as expected. But upon refresh, it gets cleared.

**Comment by marcoow** [comment]
Have you implemented the `fetch` method in the torii provider (e.g. [like in the dummy app](https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/torii-providers/facebook.js#L4))?

**Comment by gin93r** [comment]
@marcoow - I hadn't. I've added one for google-oauth2 with the same results, though I'm more than likely doing something wrong... though the dummy app seems to be fixing Facebook and not Google, if that matters. Here's what I added.

```
// \app\torii-providers\google.js
import GoogleOauth2Provider from 'torii/providers/google-oauth2';

export default GoogleOauth2Provider.extend({
  fetch(data) {
    return data;
  }
});
```

**Comment by marcoow** [comment]
You're using the `google-oauth2` torii provider

```js
this.get('session').authenticate('authenticator:torii', 'google-oauth2');
```

but added the `fetch` method in `app\torii-providers\google.js`. You'll either have to change the authentication call to

```js
this.get('session').authenticate('authenticator:torii', 'google');
```

or rename the file to `app\torii-providers\google-oauth2.js`

**Comment by gin93r** [comment]
Ok. I renamed the file to `app\torii-providers\google-oauth2.js`

Still have the same results.

Thanks for the help, btw.

**Comment by marcoow** [comment]
Anything in the console?

**Comment by gin93r** [comment]
Hmm.. this apparently.

`The authenticator "authenticator:torii" rejected to restore the session - invalidating…` I must have missed that since it was blue like the other Ember logs. Maybe it's an issue with Torii?

**Comment by marcoow** [comment]
No, that means sth. is wrong with the `fetch` method in the torii provider. Put a breakpoint in that method and check whether it's ever called.

**Comment by gin93r** [comment]
So I googled the error and found #345. Adding `return data` seemed to fix the persistence issue for refreshing.

```
// \app\authenticators\torii.js
import Ember from 'ember';
import Torii from 'ember-simple-auth/authenticators/torii';

const { service } = Ember.inject;

export default Torii.extend({
  torii: service('torii'),
  authenticate(options) {
    return this._super(options).then(function (data)
    {
      alert(`authorizationCode:\n${data.authorizationCode}\nprovider: ${data.provider}\nredirectUri: ${data.redirectUri}`);
      return data;
    });
  }
});
```

This also changed the the value for `session` in local storage to more than just the authenticator.

I tried adding that line before, but I didn't have the `fetch` method in the provider.

**Comment by marcoow** [comment]
Oh, right - your authenticator didn't resolve with anything before, hadn't seen that.

👍

**Comment by gin93r** [comment]
Thanks @marcoow - I appreciate the help. :)
