### ISSUE TITLE
[Proposal] Store accessed route before redirection to authentication route while using Fastboot

### ISSUE THREAD

**Issue by juanazam** [simplabs/ember-simple-auth#1127]
Hi,

First of all, thanks for this great addon and the efforts done to make it work with fastboot. Most of the things I had in place, worked without any changes except the `attemptedTransition` functionality on the `authenticated` and `unauthenticated` mixins.

Storing the transition in the session works perfectly on regular ember apps, but it doesn't work while running on fastboot mode.

In order to do so I had to implement support for that explicitly. I think it would be great if the addon could handle both cases out of the box without too much work.

In order to make it work with both cases, I overrode those mixins and added a conditional:

```
export default Mixin.create(AuthenticatedRouteMixin, {
  fastboot: service(),
  routing: service("-routing"),
 
  beforeModel(transition) {
    if (!get(this, 'session.isAuthenticated')) {
      assert('The route configured as Configuration.authenticationRoute cannot implement the AuthenticatedRouteMixin mixin as that leads to an infinite transitioning loop!', this.get('routeName') !== Configuration.authenticationRoute);

      set(this, 'session.attemptedTransition', transition);

      if (get(this, "fastboot.isFastBoot")) {
        /*global FastBoot*/
        let querystring = FastBoot.require('querystring');
        let url = querystring.escape(get(this, "fastboot.request.path"));

        return this.transitionTo(Configuration.authenticationRoute, { queryParams: { redirectUrl: url } });
      } else {
        return this.transitionTo(Configuration.authenticationRoute);
      }
    } else {
      return this._super(...arguments);
    }
  }
});
```

What do you think?

**Comment by marcoow** [comment]
Yeah this is a good point. I think supporting that might be a bit trickier though. When redirecting in FastBoot, you could get the target ember route from the `transition` and e.g. submit it back to the client in a response header. In order to use that transition on the client then, a new transition object would have to be created (e.g. in an initializer) but I'm not sure how that object would look like. Also I think it's probably not public API…

**Comment by juanazam** [comment]
Building a transition again might be a bit too tricky, that's why opted out for using a query param in the redirection for that particular case, so when the app gets on the auth route on fastboot (and then after loading the ember app), there is a simple way to retrieve that path. I know is not exactly the same workflow as for the regular ember app case, but it serves the same purpose.

As far as I have played around with transitions, they are not very friendly, for example building a path out one is more difficult than it should (IMHO).

**Comment by marcoow** [comment]
I'd actually like to investigate the possibility of having a more integrated solution using a transition and avoid a query param if possible. In theory that query param might interfere with one that the application defines and it would generally be nicer if we would use the same redirect url in the browser as well as in FastBoot.

**Comment by juanazam** [comment]
Yes, that's the strongest downside of using query param for this. I will investigate too, if I find something worth mentioning I will get back to you.

**Comment by DrewCarlson** [comment]
The fastboot server uses redirects for on-server transitions so (afaik) you wouldn't be able to pass headers through.  A cookie would be possible and is still less intrusive than a query param.  As far as recreating the transition, I wouldn't imagine it's simple (or possible in some cases) to rebuild every app's state with a simple object.  The easiest solution that comes to mind is storing `transition.intent.url` as it will hold the model id and any query parameters.

**Comment by juanazam** [comment]
@DrewCarlson Awesome! I was checking out Router.js transition creation and was thinking on using the shoebox to store and retrieve the url. It's a bit tricky, but I think a transition can be built from a url.

Anyway, if we are good with storing this in a cookie, I think this is way less complicated and solves the problem.

**Comment by marcoow** [comment]
> The fastboot server uses redirects for on-server transitions so (afaik) you wouldn't be able to pass headers through.

It should be no problem to send additional headers with the redirect response. After all, the location that's being redirected to is sent in a header as well (`Location`).

**Comment by juanazam** [comment]
After investigating more, I don't think a cookie is necessary for this. The shoebox approach should work, instead of fetching the url from a cookie we could just use that instead.

@marcoow @DrewCarlson thoughts?

**Comment by marcoow** [comment]
Ah right, shoebox is actually made for this kind of thing. Ideally we'd just have an initializer that sets `session.attemptedTransition` if sth. is present in the ESA shoebox.

**Comment by juanazam** [comment]
Actually, storing the transition in JSON format may be difficult, what do you think about storing the url only as done on @DrewCarlson implementation?

I can implement something using the shoebox approach.

**Comment by marcoow** [comment]
I'd store only the data that's needed to rebuilt the transition instance. Going that route would allow the rest of the code base to remain unchanged and also the session's `attemptedTransition` property would always be set to the transition that will be retried on next login regardless of where that transition came from.

**Comment by juanazam** [comment]
Sounds reasonable, I will give try to give it a shot this week.

**Comment by juanazam** [comment]
I started implementing this and then realized that after hitting a protected URLm the fastboot server responds 307 (and redirects to the authentication url). Since this is a new request, we cannot rely on the shoebox, so we are back to a cookie/header based solution.

**Comment by DrewCarlson** [comment]
@juanazam That's the same problem I mentioned with headers.  The server has the transition only up until it sends the 307 redirect, the browser immediately loads the target url provided in the `location` header.  The target wouldn't know anything about that transition unless you put it in the URL or a cookie.

**Comment by marcoow** [comment]
Argh, you're right of course - header doesn't even work. It seems a cookie is the only option then really.

We're having the ESA status call every Wednesday 18:30 CET if you'd like to join. This seems like sth. that would be great to discuss their before starting to implement sth. Check the `#dev-simple-auth` channel on the community slack for details.
