### ISSUE TITLE
Better feedback for invalid authorizer

### ISSUE THREAD

**Issue by srvance** [simplabs/ember-simple-auth#1129]
I created an authorizer reference from my adapter `authorizer: 'authorizer:github'` but mistyped the directory name when creating the authorizer (i.e., `authorizer/github.js` rather than authorizers/github.js`). The result was a message like "Can't invoke authorize() of undefined". While it was clear that it wasn't finding the authorizer, it wasn't apparent to me why as I kept overlooking the lack of a plural.

I believe a little defensive programming [here](https://github.com/simplabs/ember-simple-auth/blob/master/addon/services/session.js#L228) would do the trick. I'll be glad to do it, but I wanted to get core contributor feedback on whether that was deliberate to avoid the runtime overhead and that I've isolated the right code.

All the other checks seem satisfied with verifying that the adapter's `authorizer` property is set, but not that it points to a valid authorizer.

**Comment by marcoow** [comment]
Yep, would be nice if you could add an assertion along the lines of [this](https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L36).

**Comment by srvance** [comment]
Will do. Watch for it soon.

**Comment by marcoow** [comment]
fixed by #1132
