### ISSUE TITLE
Interested in additional docs?

### ISSUE THREAD

**Issue by srvance** [simplabs/ember-simple-auth#1130]
I find the ESA docs useful once I understand the overall flow, but I had to spend a bit of time on stackoverflow, blogs, and the code to really grok it. And then understanding how it interacted with torii in a full OAuth2 explicit grant flow and how to use authorizers needed additional digging.

I found various blog posts and source code examples, but many of them were dated and/or incomplete. Most of them haven't kept up with the evolution of ESA and don't take full advantage of what ESA offers now.

I would like to offer to write some additional documentation, either as supplemental guides or as part of the README, if you're interested. Here are the docs I would propose:

1. A flowchart or sequence diagram showing how each of the types and hooks are invoked and applied during a fairly comprehensive interaction to provide a big picture overview.
2. A similar depiction to address the torii provider and its interactions.
3. A full end-to-end GitHub OAuth2 flow pulling it all together with code.

This is a non-trivial bit of writing, so I wanted to get some feedback before jumping into it.

**Comment by marcoow** [comment]
Help on docs is always appreciated. I think the README can certainly be improved and the start [page of the API docs](http://ember-simple-auth.com/api/) would probably also be a great place for a general overview of the concepts etc. I think docs on torii and Github OAuth 2.0 would probably best go to the [guides](https://github.com/simplabs/ember-simple-auth/tree/master/guides)?

Let me know how we can support you in creating more/improving existing docs, we'd definitely love to improve ESA's docs!

**Comment by srvance** [comment]
Great. I'll start with the guide to capture my experience while it's fresh. Then I'll jump in on the other topics.

**Comment by srvance** [comment]
If you want to see the first doc before I do the PR, look at https://github.com/srvance/ember-simple-auth/blob/auth-torii-github-guide/guides/auth-torii-with-github.md.

I have images with it. Do you think I should move everything into a dedicated subdirectory or are you fine with the images mixed in?

**Comment by marcoow** [comment]
I think it would be good to have a `guides/assets` folder, yes.

**Comment by srvance** [comment]
Done.

I'm creating a sample app that follows the guide. Would you like it pushed under `simplabs` or should create my own repo? I was thinking it would confuse things to have an ember app nested inside an addon, other than `dummy`.

**Comment by marcoow** [comment]
We already have an example for torii auth in the dummy app. I think ideally we should keep all of the examples we're using in the guides in that app as that's already part of the repo here and can also be tested with the addon's integration and acceptance tests.

**Comment by srvance** [comment]
This is going to need a GitHub API Key, have exclusive authenticated and unauthenticated routes, and follows along exactly with the guide. I'm not sure it would serve double duty with the dummy app. I'm writing it primarily to make sure there are no technical errors in the guide. I'll share it with you when it's done and we can decide the best way to make it available.

**Comment by marcoow** [comment]
OK, cool - maybe we can simply mock the server part in the dummy app or so.

**Comment by marcoow** [comment]
@srvance: I think we can close this? Thanks again for the awesome docs effort!

**Comment by srvance** [comment]
@marcoow Sounds good. Any other follow up will come in PRs.It's on my todo list to write some specific docs about the big picture flow of things. I found the current docs to be great once you figure out some context and would like to write something to provide that context and maybe soften the learning curve.

**Comment by marcoow** [comment]
> It's on my todo list to write some specific docs about the big picture flow of things.

awesome 🎉
