### ISSUE TITLE
Cookie store session always expires after cookie Expiration Time even with user activities

### ISSUE THREAD

**Issue by msalahz** [simplabs/ember-simple-auth#1134]
I'm using ember simple auth using cookie store and session always expires after cookie Expiration Time even with user activities. Is this is the default behavior ? Shouldn't we renew session expiration if user is not idle 

Ember	2.9.1
Ember Data	2.10.0
Ember Simple Auth	1.1.0

**Comment by stevenwu** [comment]
@msalahz what is your cookie expiration time?

**Comment by msalahz** [comment]
@stevenwu I tried 30 sec and 1 min to test but it always expires when I have browser tab opened

**Comment by marcoow** [comment]
The absolute cookie expiration time is only extended every 60 seconds. If the configured expiration time is below that the cookie will actually expire before it can be extended. Please try an expiration time of 90 seconds or so. There should certainly be a warning when an expiration setting that's below the extension interval is detected.

Also, what's your motivation for such a short expiration?

**Comment by msalahz** [comment]
I was just making a quick testing @marcoow, and I didn't know about extended period. I tested this with 90 sec and it's working fine Thank you!

**Comment by marcoow** [comment]
Reopening this as we should have a warning logged when we detect the expiration is below the renewal interval.
