### ISSUE TITLE
How to redirect to login page when not logged in?

### ISSUE THREAD

**Issue by tmclouisluk** [simplabs/ember-simple-auth#1137]
Hello everyone,

I have set this in environment.js

```
ENV['ember-simple-auth'] = {
	authenticationRoute: '/login',
};
```

however, when i go to localhost:4200/, it won't redirect to login page.
How to make it? 
Thanks

**Comment by marcoow** [comment]
It only redirects when accessing an authenticated route without the session being authenticated. The root route of an app should almost never be authenticated.
