### ISSUE TITLE
crossLink resolution issue

### ISSUE THREAD

**Issue by srvance** [simplabs/ember-simple-auth#1144]
It looks like the crossLink element in an inherited docs is not being resolved properly. I don't see a syntax problem with [this](http://ember-simple-auth.com/api/classes/AdaptiveStore.html#event_sessionDataUpdated) but the markup is shown instead of the link. This is not the case in the other extended stores like [this one](http://ember-simple-auth.com/api/classes/CookieStore.html#event_sessionDataUpdated). I don't see the difference.

**Comment by marcoow** [comment]
I'm not exactly sure what the difference between the 2 is TBH.

**Comment by srvance** [comment]
I tried several things. Changing the imports to relative paths, changing the import name `Base` to `BaseStore`, and moving the `Base` import below the others in any combination did not fix it. The biggest difference I see is that this is the only one that imports multiple instances of `Base`, although two aren't directly visible.

**Comment by marcoow** [comment]
Ah, now I see what you mean - it render the source for the `{{crossLink` (_"'{{#crossLink "BaseAuthenticator/restore:method"}}{{/crossLink}}"_). That is indeed strange… …and I have no idea what could cause it…

**Comment by marcoow** [comment]
cleaning up old issues
