### ISSUE TITLE
OAuth2Authenticator add property identificationAttributeName

### ISSUE THREAD

**Issue by esbelf** [simplabs/ember-simple-auth#1145]
Could we add a property 'identification' to our OAuth2Authenticator so we don't always have to send the key name 'username' for identification but instead it could be 'email' just like in the devise authenticator? 

Or is there a reason why the decision was made not to do such? If so could you explain why so I could learn. Thank you

**Comment by marcoow** [comment]
`identification` is defined in RFC6479 which the OAuth 2.0 authenticator implements.

**Comment by esbelf** [comment]
yeah but why cant you change the key name for the identification value so it is not always username?

**Comment by esbelf** [comment]
or would that be something you extend on your own implementation of an authenticator on top of simple auth?

**Comment by marcoow** [comment]
You can always override that in a custom authenticator of course but the whole point on the OAuth 2.0 authenticator is that it implements the spec and that's pretty clear about names etc.

**Comment by esbelf** [comment]
okay thanks for the response

**Comment by adamw005** [comment]
How could I customize this? 

I've tried:
```
#app/authenticators/oauth2.js
import OAuth2PasswordGrant from 'ember-simple-auth/authenticators/oauth2-password-grant';

export default OAuth2PasswordGrant.extend({
  serverTokenEndpoint: "/oauth/token",
	identification: "email"
});

```
