### ISSUE TITLE
Ember simple Auth-not case sensitive

### ISSUE THREAD

**Issue by chansaRob112** [simplabs/ember-simple-auth#1146]
I have used ember simple auth to create the login of my application but I have discovered that  when login in the application is accepting the capitilised or upper case password even if the password word was created in lower case

**Comment by marcoow** [comment]
Ember Simple Auth never validates any passwords. That would be a problem on the server you're using.

**Comment by chansaRob112** [comment]
Thanks for the reaction marcoow

I am using sane stack
