### ISSUE TITLE
How to configure to work with an API on a different host/subdomain?

### ISSUE THREAD

**Issue by stephencarr** [simplabs/ember-simple-auth#1150]
My API is not on the same subdomain, for example:

```
www.example.com --> Ember app
api.example.com/v1/ --> API app
```

How can I configure the API host and path for authorized data calls?

The `authenticator` allows for configuring `serverTokenEndpoint` which allows me to auth, but I am unsure about treating `authorizer`.

**Comment by marcoow** [comment]
Authorizers don't require any knowledge about hosts. All they do is provide authorization data to a callback - in most cases that's building a header that can then be inserted into the request by the callback. See the docs for [authorizers](http://ember-simple-auth.com/api/classes/BaseAuthorizer.html) and the [`DataAdapterMixin`](http://ember-simple-auth.com/api/classes/DataAdapterMixin.html).
