### ISSUE TITLE
Make `routeAfterAuthentication` more flexible

### ISSUE THREAD

**Issue by srvance** [simplabs/ember-simple-auth#1151]
I would like to propose allowing `routeAfterAuthentication` optionally to be defined as an array that would then be applied to `transitionTo` to take full advantage of the route transition options. A string would still behave as currently.

This is not a performance-critical section of code, so an array test to fork the behavior shouldn't be an issue. It's also a backwards-compatible change as proposed.

I have a situation where I would like to use the same route with an ID that is reserved for the default. I can work around this be creating an extra route for this case and using that, but it results in seemingly unnecessary special case handling and extra code for no clear reason.

I'll be glad to code it up and submit the PR once we refine the idea.

**Comment by marcoow** [comment]
I'm not sure I like this idea to be honest. It seems that would add quite a bit of cognitive load to the config setting for a case that's pretty special. It seems that applying defaults for dynamic query path segments would be something that would better be done in the respective route's `model` method anyway as opposed to the links to that route.

**Comment by srvance** [comment]
I've figured other ways to deal with it involving index routes and redirect. I think you're right that it's too much complexity for too narrow a use case.
