### ISSUE TITLE
More complete OAuth2 story

### ISSUE THREAD

**Issue by srvance** [simplabs/ember-simple-auth#1152]
I wanted to start a design discussion about a more complete story for OAuth2 auth for the auth code flow. The piece that ends up being very manual is the auth code token exchange call. It has some standard characteristics:

* It will usually be a GET or a POST
* It will often be to a URI on a domain separate from the source of the auth token or the API being authenticated against if it's for trusted authorization of a third-party app.
* The response representation tends to be simple with a suggested form implicitly in the RFC. Variations could be easily mapped and overridable.
* It could easily be a no-op for auth protocols that don't require it.
* The current implementations set `isAuthenticated` on obtaining the auth code even though that's not sufficient.

This is what I originally thought an `authorizer` would be. It would be confusing to repurpose it, but the name would make sense.

Do you feel ESA should address this part of the flow more explicitly? Do you have thoughts on how this might be addressed?

I'll be glad to help code it up.

**Comment by marcoow** [comment]
I think there is some potential to add some more code to the torii authenticator (or add a second torii-based authenticator) that makes it easier to implement the auth code flow with it. The torii authenticator in its current form is never usable as it is and you're right, ESA doesn't make that clear enough.

I'd be happy to improve ESA in that way. Maybe some of the `ToriiAuthenticator` code from the [guide](https://github.com/simplabs/ember-simple-auth/blob/master/guides/auth-torii-with-github.md#obtaining-an-access-token) could be moved to the base class?

**Comment by jfschaff** [comment]
I have spent some time understanding OAuth2 in the particular case where the client directly connects and authenticates (no server other than the API provider's, like Google, or Facebook) and I have looked at the way Torii handles things with e.g. Google, and I agree that there is something wrong:
1. for instance, it looks like Torii's google provider is outdated. It does not connect to the right server (which is now [https://accounts.google.com/o/oauth2/**v2**/auth](https://accounts.google.com/o/oauth2/v2/auth), not https://accounts.google.com/o/oauth2/auth as in Torii),
2. it looks like Torii does not verify the token (maybe it was not possible with OAuth2 on the previous URL) which makes the authentication vulnerable to the "confused deputy issue" (just repeating what is written [there](https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation), not sure I understand all the subtleties of this yet...).
3. one would have to check if similar issues are present with other providers and scenarios though...

I could spend some time as well. Have you started working on improving that?

**Comment by marcoow** [comment]
I don't think Ember Simple Auth should try and reimplement what's already in torii as that's a lot actually and would require serious effort to build and maintain. Also torii has a vivid community behind it already. Instead if we find bugs or missing features in torii we should help fix them there instead.

Ember Simple Auth's main focus is managing the session (in the browser as well as in FastBoot) and providing hooks to authenticate/invalidate it as well as persisting it. If we can add some hooks that many or most people will actually need to the current Torii authenticator that's awesome but the goal should be to leverage torii for the actual (client side) communication with the identity providers instead of trying to reimplement it.

**Comment by srvance** [comment]
It's going to take me some time to get back around to this work. I agree with what you're saying and would keep it in mind. There are some additional phases for complete auth that are needed to complement torii properly depending on which flow is being followed.

**Comment by marcoow** [comment]
cleaning up old issues
