### ISSUE TITLE
ember-getowner-polyfill is depracated

### ISSUE THREAD

**Issue by rhadoo200** [simplabs/ember-simple-auth#1159]
Hi,
Ember cli is giving me this notification:

DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]

Could you please remove the import of ember-getowner-polyfill and replace it with the given function? I've noticed that in every file where the module is imported you are importing some constants objects from ember. Please add also getOwner in that list of constants. 

Thanks,
Radu

**Comment by marcoow** [comment]
This is fixed with #1124 already.

**Comment by rhadoo200** [comment]
If I install the package with just npm install it will install the project with the old import lines.
When I specify a commit ID then the latest sources are installed. The npm repository is up to date with this fix?

**Comment by marcoow** [comment]
This has not been released yet.

**Comment by rhadoo200** [comment]
ok thanks. i will stick to a commit id then.
