### ISSUE TITLE
refresh_token security alternative

### ISSUE THREAD

**Issue by noslouch** [simplabs/ember-simple-auth#1163]
Hey @marcoow, have you thought about allowing for alternative `refresh_token` storage methods?

We don't want to store the `refresh_token` in browsers because of their long-life and potential security hole (as I understand it). We're opting to save the `refresh_token` on a trusted server and allow clients to retrieve a new `access_token` from a different endpoint.

What are your thoughts on accepting a PR that allows for different token refresh strategies?

**Comment by marcoow** [comment]
Can you elaborate on that a bit? I'm not sure I understand how you're using that trusted server/how it improves security.

**Comment by noslouch** [comment]
Thanks for the response. My understanding of oAuth is still rudimentary, so I'm open to learning from your experience.

The idea is to keep the `refresh_token` safe from potentially malicious clients, since it is long-lived. I've done some reading and I'm using these spots as references for my thinking:
* https://auth0.com/learn/refresh-tokens/ (scroll down to security considerations, near the bottom)
* ^^^ is linked to from this SO thread: http://stackoverflow.com/questions/14163632/how-refresh-token-should-be-saved

As I understand it, the `refresh_token` is used to retrieve a new `access_token` *without further authentication*. So if a malicious client gets a hold of a `refresh_token`, they may retrieve as many `access_tokens` as they please to perform authorized actions.

In our proposed model, the client only gets an `access_token`, which is `PUT` against a token endpoint (server 1) to retrieve a new `access_token`. Our server accepts the `access_token` (in the form of a JWT), performs some validations against its signature and other values found in the JWT headers, and then looks up a locally saved `refresh_token`, which was saved at authentication-time. 

The retrieved `refresh_token` is presented to our auth server (server 2), which returns an `access_token`. 

Thoughts? Doesn't saving the long-lived `refresh_token` make it a vulnerability?

**Comment by marcoow** [comment]
If I understand correctly you could get a new access token by presenting your current access token to that proxy server that knows the access token's refresh token? What would you do if the current access token has expired then? The purpose of the refresh token is usually allowing to retrieve a fresh access token when the current one has expired as the refresh token does not expire.

**Comment by noslouch** [comment]
When a user authenticates, the proxy server receives an access token, which is a JWT that includes a UUID, and a refresh token from the auth server. The proxy server saves the refresh token in a local DB, using the UUID as a key.

When the client presents an expired access token, its signature is validated and the UUID is extracted for use in a local db lookup to retrieve a refresh token. Then the proxy server uses that refresh token to retrieve a fresh access token from the auth server.

Does that make sense? Is it unnecessary as you understand oAuth flows? I'm still digging through the [threat model as described here](https://tools.ietf.org/html/rfc6819), but I haven't found a clear answer yet.

**Comment by marcoow** [comment]
I don't think that solution adds any security. As I understand is the potential attack you want to prevent by never exposing the refresh token to the browser is if an attacker could get a hold of someone's refresh token and then use that to generate fresh access tokens ever after. If the proxy server would issue fresh access tokens when presented with an expired access token as you explain above the attack scenario would be the same though - once you get a hold of someone's access token you can use that to issue fresh access tokens ever there after - regardless of whether the access token has already expired or not.

Basically what your solution comes down to is every access token also effectively being a refresh token.

**Comment by noslouch** [comment]
is this any more vulnerable than saving a refresh token in the same location as an access token?

**Comment by marcoow** [comment]
What I'm saying above is that your approach is the same thing as saving the refresh token along with the access token.

**Comment by noslouch** [comment]
Yeah, you're right.

So what to do? Isn't this a security vulnerability or am I overthinking it?

**Comment by marcoow** [comment]
Refresh tokens are certainly more sensitive secuity-wise than access tokens. You can of course always invalidate all tokens server-side though.

**Comment by noslouch** [comment]
True, but by the time a dev is intervening to invalidate tokens a breach has likely already done its damage. Are we all just comfortable living with potentially compromised clients?

**Comment by marcoow** [comment]
Yes, there's not much you can do if someone loses their token. Same thing if someone loses their session cookie (which is harder to invalidate server side though).

**Comment by noslouch** [comment]
security!!! (╯°□°）╯︵ ┻━┻
