### ISSUE TITLE
Cookie session store keeps attempting to sync data after being destroyed

### ISSUE THREAD

**Issue by teddyzeenny** [simplabs/ember-simple-auth#1167]
Details explained in https://github.com/simplabs/ember-simple-auth/pull/1131#issuecomment-269229865:

> The debounce is leaking after the object has been destroyed. So when you destroy and recreate the container (via an app reset for example) the destroyed session store will keep syncing data and there's no way to break the loop. It will also throw errors if it detects changes because it will attempt to set the content property on a destroyed object (the destroyed internal session). This bug actually existed before this PR but the PR made it impossible to break the loop in a subclass as the debounced tasks are no longer tracked.
As a result, I believe we need to keep track of these timers (as we were before this PR) and Ember.run.cancel them in a willDestroy hook. However, it seems it's currently not possible to cancel a debounce created by another debounce so going back to run.later and calling run.cancel when destroying may be the most straightforward approach. Thoughts?

**Comment by marcoow** [comment]
closed by #1178
