### ISSUE TITLE
Tag 1.2.0-beta.1 version as `beta` and 1.1.0 as `stable`

### ISSUE THREAD

**Issue by Floby** [simplabs/ember-simple-auth#1168]
Hello,

Could someone tag the current `1.2.0-beta.1` version as `beta` on npm and the `1.1.0` version as `stable` ?

Many tools used to check dependencies like `npm-check-updates` rely on these tags for their processing.

Thank you =)

**Comment by Floby** [comment]
any news on this?

**Comment by marcoow** [comment]
Done; we should make this part of a to-be-developed automated build process /cc @Turbo87

**Comment by Turbo87** [comment]
@marcoow you could use something like https://github.com/ember-cli/core-object/blob/v2.x/package.json#L40-L42 on the `beta` branch

**Comment by marcoow** [comment]
We don't have a beta branch. There's only `master` that we publish releases from every now and then.

**Comment by Turbo87** [comment]
yeah, noticed that after I wrote the comment...

right now this repo doesn't seem to use automatic publishing via TravisCI so I'm assuming you run `npm publish` manually. in that case you have two options:

- use e.g. `npm publish --tag beta` whenever you do a beta release

- write the `beta` tag in the `package.json` as linked above and remove it again once you do a stable releases

if you want to use TravisCI for publishing you will have to use the second option as the `npm publish` command that's run there isn't configurable other than through the `package.json` file. 

it might make sense to have a `stable` branch, and merge the `master` branch with the new stuff in, once you want to promote the beta to stable. at the point of the merge we'd then need to make sure that the `publishConfig` in `package.json` is not merged in too, but once that is established it should work fine for future merges.

**Comment by marcoow** [comment]
Yeah, I'd like to keep branching structure simple as long as possible. Right now it seems that automatic tagging support would be the only reason to split `master`/`stable` branches and I don't really think that's worth it. I also wasn't aware that these tags were even supported be npm. Are other Ember projects using them as well?

**Comment by Turbo87** [comment]
yes, we use them in Ember CLI itself, and now that `ember-source` is a thing they are used there as well. we've also used them for e.g. `ember-cli-eslint` last year when we had to support ESLint 2 and 3 at the same time.

**Comment by marcoow** [comment]
OK, sounds like ESA should do so as well then. I'll make a mental note for now and we'll see whether that works or we need to set some process up for releases in the future.
