### ISSUE TITLE
Using ESA to store session data

### ISSUE THREAD

**Issue by Nikash** [simplabs/ember-simple-auth#1171]
I'm storing some session data such as session timeout values in ESA's session store. This value gets updated with every XHR request the application makes.

When our application is open in more than one tab, the `restore` method from the second tab in our custom authenticator makes an XHR request which updates the timeout values in the session store. This change to the session store fires the listeners attached by ESA in the first tab which calls the `restore`. The first tab then makes the same XHR request in the `restore` and also updates the timeout values in the store causing the listener in the second tab to fire. This causes an infinite loop and each tab constantly fires out the said XHR request. 

My question is whether ESA's session store can be used to store session data which we would like invalidated when the session ends or only be used to store the `data.authenticated` value? If in the case of the former, should the listeners for change in the session store calling the `restore` be triggered only for a change in the `data.authenticated` property instead of the whole `data`?

**Comment by marcoow** [comment]
> My question is whether ESA's session store can be used to store session data which we would like invalidated when the session ends

Yes, that's actually one of ESA's features.

> If in the case of the former, should the listeners for change in the session store calling the restore be triggered only for a change in the data.authenticated property instead of the whole data?

I'm not sure actually. From the session store's perspective it makes sense to always fire the event on any changes as it doesn't (and shouldn't) care about the actual contents of the session. The session itself would only have to care (and call it's own `restore` method) about changes in the `data.authenticated` part, that's correct. This would be an optimization that could be applied in the session class actually.
