### ISSUE TITLE
Stub currentUser in Test

### ISSUE THREAD

**Issue by dja** [simplabs/ember-simple-auth#1174]
I'm trying to stub `currentUser` with a fresh user (via factory_guy) in testing, but running into issues..

```
let user = make('user');
authenticateSession(this.application);
currentSession(this.application).set('currentUser', user);
```

I’m fully following the guide here: https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md and using a dedicated endpoint for the current user, as stated here: https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md#using-a-dedicated-endpoint

All the testing stubs that i’m seeing are with setting the `user_id` on the session when authenticating like `authenticateSession(this.application, { user_id: user.get('id')})`

I’d like to do something like `authenticateSession(this.application, { currentUser: user })`

Anyone done this before that can help me out and also document it?

**Comment by marcoow** [comment]
In the guide you're linking to above we're using a dedicated service to keep the current user but you're trying to set the property on the session service itself. Also `authenticateSession(this.application, { currentUser: user })` won't work as the session can not store `Ember.Object`s - only serializable data that can be stored in the session store as JSON (we might actually remove even that in the future and only allow atomic values like strings and integers and not even hashes or arrays).

I think the best solution in you case would be to simply stub the server response for loading the current user as that's also the most acceptance test-like approach as it would execute all of the code that loads the current user from the backend. You can use either mirage or just plain Pretender (or another solution even if you prefer that) for stubbing the response.

**Comment by dja** [comment]
Got it, thanks @marcoow.  For reference, I solved it by extending the `ModuleForAcceptance` like this:

```
import { module } from 'qunit';
import Pretender from 'pretender';

var pretender;

export default function moduleForAcceptance(name, options = {}) {
  module(name, {
    beforeEach() {
      // Stub currentUser
      this.currentUser = make('user');
      let userJSON = this.currentUser.toJSON({includeId: true});
      pretender = new Pretender(function() {
        this.get('/api/v1/user', function() {
          return new Promise(function(resolve) {
            var response = [
              200,
              {'content-type': 'application/javascript'},
              `{"user": ${JSON.stringify(userJSON)}}`
            ];
            resolve(response);
          });
        });
      });
    },

    afterEach() {
      pretender.shutdown();
    }
  });
}
```
