### ISSUE TITLE
Remote window closed issue

### ISSUE THREAD

**Issue by anthonycollini** [simplabs/ember-simple-auth#1179]
I'm not sure if this is a simple-auth issue or a torii issue.

When authenticating through Slack using oAuth, everything seems to work fine, except about 50% of the time, the system comes back with the following error:

`remote was closed, authorization was denied, or a authentication message otherwise not received before the window closed.`

The authentication call basically looks like this:

`session.authenticate('authenticator:oauth2-gateway', 'slack-signin-oauth2')`

and the authenticator looks like this:

```
  authenticate(torii_provider) {
    return new Ember.RSVP.Promise((resolve, reject) => {
      this.get('torii').open(torii_provider).then(data => {
        data["scope"] = "read write";
        return this.makeRequest(config.apiURL + '/oauth_gateway/authenticate', data);
      }).then(response => {
        // Copied from OAuth2PasswordGrant#authenticate
        Ember.run(() => {
          const expiresAt = this._absolutizeExpirationTime(response['expires_in']);
          this._scheduleAccessTokenRefresh(response['expires_in'], expiresAt, response['refresh_token']);
          if (!Ember.isEmpty(expiresAt)) {
            response = Ember.assign(response, { 'expires_at': expiresAt });
          }
          resolve(response);
        });
      }).catch(error => {
        reject(error);
      });
    });
  }
```

Any thoughts as to why this is happening?

**Comment by marcoow** [comment]
That's an error coming from torii: https://github.com/Vestorly/torii/blob/606334ca1832ecadc75628f8b6a2c4e110c1e642/addon/mixins/ui-service-mixin.js#L75
