### ISSUE TITLE
sessionInvalidated immediately being called after login

### ISSUE THREAD

**Issue by gep13** [simplabs/ember-simple-auth#1187]
I have implemented a custom authenticator for use with an in-house application, and everything seems to be working, with one exception...

Once the authenticator resolves the promise, and returns to the home page, my application immediately gets invalidated and essentially log's out the user again 😢 

I have added this in my `route/application.js` file:

```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

const { inject: { service }, Route } = Ember;

export default Route.extend(ApplicationRouteMixin, {
  sessionAccount: service('session-account'),

  beforeModel() {
    return this._loadCurrentUser();
  },
  sessionAuthenticated() {
    this._super(...arguments);
    this._loadCurrentUser().catch(() => this.get('session').invalidate());
  },
  sessionInvalidated() {
    console('shouldnt get here');
  },
  _loadCurrentUser() {
    return this.get('sessionAccount').loadCurrentUser();
  }
});
```

And when debugging, I can see that the `sessionAuthenticated method is called, and correctly exits (i.e. doesn't call the invalidate()), however, almost immediately after the sessionInvalidated method is called.

I have checked my code, and the places where I am calling invalidate() are never accessed.

Looking at the Call Stack for when the sessionAuthenicated is hit, I see the following:

![image](https://cloud.githubusercontent.com/assets/1271146/22381957/9684ffa2-e4bb-11e6-90cd-e4bcf97582d9.png)

But I don't know if that helps or not.  Is there something that I have missed?

Any ideas on how to go about debugging into this to see what is going on?  Thanks in advance!

**Comment by gep13** [comment]
Ok, just read this little nugget:

>Triggered whenever the session is successfully invalidated. This happens when the session gets invalidated via invalidate but also when the session is invalidated in another tab or window of the same application and the session state gets synchronized across tabs or windows via the store (see sessionDataUpdated).

And on an off chance, I closed all the open tabs that I had open, and the login process started working correctly.

Can you help me understand exactly what might have been happening here, and what I can do to resolve this, or rather, hand this in a more graceful manner, as this was a little unexpected.

**Comment by marcoow** [comment]
Whenever the session changes authentication state it persists the new state to the session store (e.g. `localStorage` or a cookie, depending on what you chose or what's available in the current browser). That session state change will result in the `restore` method of the authenticator instances in any other open tabs or windows being called. If any of the authenticators rejects restoration (by returning a rejecting promise from the `restore` method or by throwing an error), the session will invalidate itself. This state change is again propagated to all other open tabs or windows of the same application.

I assume you implemented a custom authenticator? Can you share the code here?

**Comment by gep13** [comment]
@marcoow  Thank you very much for getting back to me, I really appreciate it!

>@marcoow said...
I assume you implemented a custom authenticator? Can you share the code here?

Yes, I have implemented a custom authenticator, unfortunately, I am not able to share the code, as some of it contains sensitive information.  However, based on what you have said, I think I see where the issue lies.  Currently, I have only implemented the `authenticate` and `invalidate` method.  This was based on the dummy app sample in this repository.  My assumption is that the `restore` method, if not implemented, will simply reject the promise, leading to the functionality that you describe.  I will need to implement the `restore` method and handle the case correct flow for the application.

Can you point me to further information about this?  Thanks!

**Comment by marcoow** [comment]
> My assumption is that the restore method, if not implemented, will simply reject the promise, leading to the functionality that you describe.

correct: https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/base.js#L110

See API docs for more info: http://ember-simple-auth.com/api/classes/BaseAuthenticator.html#method_restore
