### ISSUE TITLE
How to create a custom authenticator

### ISSUE THREAD

**Issue by prakashraman** [simplabs/ember-simple-auth#1195]
Hi

I am creating a simple authenticator called "db".

The "restore" method seems to be called on page load (as expected). And the "authenticate" method runs the authentication logic.

What I did not understand how to do is.
I would like to set a "token" in the localStore (Adaptive Store). And I would like the "restore" method to be able to read from that store.

How can I go about doing this?

**Comment by marcoow** [comment]
The `restore` method is called with the current session data. Please refer to the [README](https://github.com/simplabs/ember-simple-auth#readme), [API docs](http://ember-simple-auth.com/api/) and [dummy app](https://github.com/simplabs/ember-simple-auth/tree/master/tests/dummy) for info.

**Comment by prakashraman** [comment]
Yes, thanks! It made sense.

I also, figured that the "restore" method is *only* called if there is any authenticate data in the localStore (store).

Thanks though!
