### ISSUE TITLE
App does not build on 1.2.0 because of ember-cli-import-polyfill

### ISSUE THREAD

**Issue by lucasm-iRonin** [simplabs/ember-simple-auth#1199]
Hi,
I've found a strange issue with latest version of `ember-simple-auth` (1.2.0). It added `ember-cli-import-polyfill` as dependency which destroys import paths for our app. We share common code between apps using ember addons and those addons contain some other add-ons. With `ember-cli-import-polyfill` being installed as part of `1.2.0` version, the whole app refuses to build.

What's the purpose of `ember-cli-import-polyfill` here?

**Comment by marcoow** [comment]
ember-cli-import-polyfill fixes a bug in Ember CLI's `import` method for addons: https://github.com/ember-cli/ember-cli/pull/5877.

ESA currently [works around that issue in the `index.js`](https://github.com/simplabs/ember-simple-auth/blob/master/index.js#L11) which we actually shouldn't do anymore as we have the polyfill. Maybe your addons are not compatible with the changes introduced with the change in ember CLI or the polyfill?

**Comment by lucasm-iRonin** [comment]
@marcoow thanks for explaining but I'm not sure I understand it correctly.

Do I need to `app` object juggling:

```
if (typeof app.import !== 'function' && app.app) {
  app = app.app;
}
```

when I have that polyfill? If I still need to do that then what's the polyfill for?

PS. Sorry for questions not directly related to the `ember-simple-auth`.

**Comment by marcoow** [comment]
Actually it seems using the polyfill in an addon is not actually correct as it's actually intended for apps (https://github.com/ember-cli/ember-cli-import-polyfill/issues/1#issuecomment-237672090). I guess we should probably remove it from ESA again. I'd suggest you look for more info on the ember-cli/ember-cli-import-polyfill repos.

**Comment by marcoow** [comment]
Oops - leaving this open as we should actually remove the polyfill again.

**Comment by lucasm-iRonin** [comment]
@marcoow thanks for quick reaction!
