### ISSUE TITLE
Setting headers before request.

### ISSUE THREAD

**Issue by AramAnd** [simplabs/ember-simple-auth#1203]
How can i set Accept: 'application/json Header before sending request. I am using the following method 

this.get('sessions').authenticate('authenticator:oauth2') and i did not override authenticate method.

**Comment by marcoow** [comment]
The OAuth 2.0 authenticator implements RFC 6749 and is not supposed to be customized in that way.

**Comment by AramAnd** [comment]
@marcoow So in the request it is putting Accept: */*, is it correct ?

**Comment by AramAnd** [comment]
@marcoow  also the response should be like this 
 {
       "access_token":"2YotnFZFEjr1zCsicMWpAA",
       "token_type":"example",
       "expires_in":3600,
       "refresh_token":"tGzv3JOkF0XG5Qx2TlKWIA",
       "example_parameter":"example_value"
     }
