### ISSUE TITLE
Can't access isAuthenticated in template

### ISSUE THREAD

**Issue by zeiv** [simplabs/ember-simple-auth#1205]
Hello there,

First off, thanks for a fantastic addon!  I use it in all my ember projects.

I'm encountering an interesting problem I can't quite figure out.  I have one route in my app.  I have configured a custom authenticator and everything is working (I can see in my Ember Inspector that the session is authenticated), but for some reason I can't access the session in my template.

If I type `{{session.isAuthenticated}}`, it renders as `<!--- --->`.

However, if I manually set the session in the controller like so, it works:

```javascript
setupController(controller, model) {
  controller.set('session', this.get('session'));
}
```

Am I doing something wrong here?  Here is my full route:

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  session: Ember.inject.service(),

  model() {
    return Ember.RSVP.hash({
      listing: this.store.queryRecord('listing', { last: true })
    });
  },

  setupController(controller, model) {
    controller.set('listing', model.listing);
    controller.set('session', this.get('session'));

    // if (!this.get('session').isAuthenticated) {
    //   var newUser = this.store.createRecord('user');
    //   controller.set('newUser', newUser);
    // }
  }
});
```

**Comment by marcoow** [comment]
You need to inject the [`Session` service](http://ember-simple-auth.com/api/classes/SessionService.html) into the controller.

**Comment by zeiv** [comment]
Yes, I'm injecting it in my application.js controller.  No luck.

**Comment by marcoow** [comment]
In which template are you trying to use the session? You have to inject it into the controller or component that's backing the template you're using the session in.

**Comment by zeiv** [comment]
I have a single `index` route with `index.js` route and `index.hbs`.  That index template yields to application template (not sure if that makes a difference).  I am trying to use session in the index template.  I have tried injecting the session service on `controllers/application.js`, `controllers/index.js`, and `routes/index.js`.

Using Ember 2.6.2, node 4.4.7, npm 4.2.0, ember-simple-auth 1.2.0, mac...

**Comment by marcoow** [comment]
If you have `{{session.isAuthenticated}}` in the `index.hbs` template you need to inject the session service in the `controllers/index.js` controller.

**Comment by zeiv** [comment]
Ok, just ran `npm install` and suddenly things are working now.  No idea what was going on there since ember-simple-auth was already loaded.

Anyway, thanks for the help!
