### ISSUE TITLE
Generate `register-version.js` file automatically

### ISSUE THREAD

**Issue by Turbo87** [simplabs/ember-simple-auth#1207]
Instead if hardcoding the version in https://github.com/simplabs/ember-simple-auth/blob/1.2.0/vendor/ember-simple-auth/register-version.js we should probably generate that file automatically based on the information in the `package.json` file.

/cc @marcoow

**Comment by marcoow** [comment]
❤️ It actually happened a few times already that we released a new version without updating that file correctly.
