### ISSUE TITLE
Session cookie data gets rewritten with object instead of string

### ISSUE THREAD

**Issue by ktrhn** [simplabs/ember-simple-auth#1218]
**Prerequisites:**
- ember-simple-auth 1.2.0
- using Cookiestore
- nothing special, only thing I do is setting the cookie lifetime `this.set('session.store.cookieExpirationTime', 60 * 60 * 24 * 14);`

**What happens:**
- the cookie gets created with the data `{"authenticated":{}}`
- in session-stores/cookie:rewriteCookie the data gets read, but _read returns an **object** and not a string: `{cookie-name: "{"authenticated":{}}"`
- the object gets written as the cookie data: `%5Bobject%20Object%5D`
- reading the data throws an error (visible after first reload of app):
```
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Class.restore (cookie.js:190)
    at Class._syncData (cookie.js:242)
    at cookie.js:155
    at fn (ember.debug.js:922)
    at invoke (ember.debug.js:339)
    at Queue.flush (ember.debug.js:407)
    at DeferredActionQueues.flush (ember.debug.js:531)
    at Backburner.end (ember.debug.js:601)
    at Backburner.run (ember.debug.js:724)
```

**Comment by marcoow** [comment]
This looks like a regression that was probably introduced with #1056. @stevenwu: can you have a look?

**Comment by stevenwu** [comment]
Sure, I'll take a look.

**Comment by sevab** [comment]
I've debugged [the code](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js) a bit, and got the following results:

When `cookieExpirationTime` is being set and `rewriteCookie` is being called, `rewriteCookie`  tries to read the old cookie with `const data = this._read(this._oldCookieName);`

However, value of `this._oldCookieName` is undefined, and so
`this._read(undefined)` returns the whole cookie object:

`{ fbsr_1481704...: 'EJPZExSRF...long...hash', 'ember_simple_auth-session': '{"authenticated":{"authenticator":"authenticator:email-token","token":"...","email":"..."}}' }`

...which `rewriteCookie` then tries to write to cookie and we get the initial error.

So either the `_oldCookieName` is not being set to anything meaningful or the value for cookie should be read from `cookieName` instead. I've tried `const data = this._read(this.get('cookieName'));`and it works, user gets authenticated and expiration time is set.

But on logout expiration time doesn't seem to be cleared, and so when retying to authenticate, the session doesn't seem to persist.

**Comment by stevenwu** [comment]
@sevab thanks for investigating. Yes, `_oldCookieName` is not set if `cookieName` is not renamed. We will get the fix in soon.

**Comment by ktrhn** [comment]
I can confirm it is working. Thanks!

**Comment by sevab** [comment]
Works for me too, but there seems a strange side effect, would appreciate if someone can explain if I'm doing something wrong or if there's a bug:

When `cookieExpirationTime` is set to some value other than `null` (I set it to 10 years in seconds), a session that's persisted on FastBoot server (via a url token for instance) doesn't seem to persist to front-end.

This doesn't happen after deleting `ember_simple_auth-session-expiration_time` cookie or when `cookieExpirationTime` is not set and defaults to `null`. In these cases FastBoot successfully authorizes user on the server and `ember_simple_auth-session` cookie is persisted to front-end .

**Comment by sevab** [comment]
Another thing to note is that this side effect does not happen in the browser, only in Fastboot. So as a temp fix I skip authentication in FastBoot and set the cookie in the browser.
