### ISSUE TITLE
Session not persisted in "Bookmark to Homescreen" view on iOS

### ISSUE THREAD

**Issue by sevab** [simplabs/ember-simple-auth#1221]
I'm running in FastBoot mode using `Cookie Store` as suggested, but there seems to be an issue at least on the latest iOS when viewing website via fullscreen webapp view (bookmark saved to home screen), where cookies are not being persisted between opening and closing the webapp.

This is possibly due to the way the [sandboxed webapp has access to cookies](http://stackoverflow.com/questions/3813599/iphone-bookmark-to-homescreen-removes-cookies-and-session). So a possible solution would be to have an option to backup & sync session data to `localStorage` alongside cookies in `Cookies Store`, and try restoring from `localStorage` if cookies aren't available. 

Not sure if this is for `ember-simple-auth` to take care of, or to be done on an individual app basis.

**Comment by marcoow** [comment]
Are you using a session cookie? I think in this case it's correct that the session is gone as the cookie is supposed to not live across multiple browser sessions.

Backing up the cookie contents in `localStorage` would lead to a pretty complex setup with lots of edge cases to handle and if cookies actually aren't available in websites that are installed on the home screen I'd say this should be an application concern for now.

**Comment by sevab** [comment]
Right, I think I was simply not setting `cookieExpirationTime` correctly. Apologies for opening the issue.

Setting `cookieExpirationTime` does throw an error on `1.2.0` though, but #1218 seems to be addressing it already.

**Comment by marcoow** [comment]
> Right, I think I was simply not setting cookieExpirationTime correctly. Apologies for opening the issue.

Don't apologize - happy that we figured this out!

> Setting cookieExpirationTime does throw an error on 1.2.0 though, but #1218 seems to be addressing it already.

correct
