### ISSUE TITLE
except external authenticators, what's here?

### ISSUE THREAD

**Issue by kucaahbe** [simplabs/ember-simple-auth#1225]
Hello, I'm trying to understand the purpose of library and have issues, please help me.

On http://ember-simple-auth.com/ it's mentioned:
* "it maintains a client side session and synchronizes its state across multiple tabs/windows of the application", which is usually done by browsers, keeping session, or session id in cookies.
* "it authenticates the session against the application's own server" could be easily by by performing good request to back-end, getting session data, stated above
* "it authorizes requests to backend servers" done by browser out of the box for cookies-persisted session data

So, if my understanding correct, we should use this library when some external authenticators should be used, otherwise it looks like not a big deal to authenticate agains own back-end with classic "session" thing? Thanks in advance.

**Comment by marcoow** [comment]
Feel free to roll your own solution.

**Comment by marcoow** [comment]
The video on http://ember-simple-auth.com as well as the [project's README](https://github.com/simplabs/ember-simple-auth#readme) might help understanding what this library does.

**Comment by kucaahbe** [comment]
@marcoow I'm pretty good at what this library does, we use it in our project and have a lot of trouble (not by library itself, but it could be related, which should not be related to this discussion). My intention to understand the use-case (probably would be good for other readers of this issue), as it turned out, from our project's perspective, it's less code and less error-prone, to remove this lib, as it basically implements existing in browsers behavior. So the question is, maybe I'm missing something big in this picture, or this lib only helps with external authenticators?

**Comment by marcoow** [comment]
What ESA does basically it adds an abstraction layer over all the browser and Ember low level primitives it builds on. Also it handles a bunch of edge cases. You can of course implement a similar solution using these low level primitives that browsers and Ember provide directly but you'll most likely come up with a pretty similar solution. Also you would be maintaining that solution yourself then while ESA is maintained by a community of collaborators.

**Comment by kucaahbe** [comment]
@marcoow thanks for the answer!
