### ISSUE TITLE
Expiration time from cookie isn't restored in session

### ISSUE THREAD

**Issue by stevenwu** [simplabs/ember-simple-auth#1237]
When an expiration time is set and saved to a cookie, it doesn't not restore to the session when the page is reloaded.

`$E.get('store.cookieExpirationTime')` will be `null` even though the expiration cookie has a value.

May be related to #854, fastboot comment in #1218.

**Comment by marcoow** [comment]
fixed via #1257

**Comment by sevab** [comment]
Having just tested `1.2.1` can confirm that the FastBoot restore bug described in https://github.com/simplabs/ember-simple-auth/issues/1218#issuecomment-282790330 is still there. Let me know if you need more details.

**Comment by marcoow** [comment]
@sevab: there seems to be an issue with the expiration time cookie still, see https://github.com/simplabs/ember-simple-auth/issues/854#issuecomment-289818243
