### ISSUE TITLE
AuthenticatedRouteMixin

### ISSUE THREAD

**Issue by devtoro** [simplabs/ember-simple-auth#1238]
Hello,

On line 96 of the authenticated-route-mixin.js file, why is the transition to the authenticationRoute returned? 

`...`
`return this.transitionTo(authenticationRoute);`
`...`

This made me to waste quite some time today. After I overrode the beforeModel in my app and removed the return statement, the application worked as expected. 

Is there a reason for the return statement?

**Comment by marcoow** [comment]
What kind of error were you seeing before removing the `return` in the overridden method?

I don't think there's a need/reason for the `return` and it should be fine to remove it.

**Comment by devtoro** [comment]
No error, but when I extended the application route with the mixin the transition never happened. That was the funny part, no errors - no transition 😄

**Comment by marcoow** [comment]
Hm, strange. We definitely shouldn't need the `return` though - want to submit a PR?
