### ISSUE TITLE
Duel write to local storage and cookie store for fastboot.

### ISSUE THREAD

**Issue by seawatts** [simplabs/ember-simple-auth#1245]
It would be nice to still have the functionality of local storage when the app hits the browser. 

In order to do this, we would need to dual write to the cookie store and local storage. Are there any implications with this?

**Comment by marcoow** [comment]
What would be the benefit of having the session data duplicated in both stores?

**Comment by seawatts** [comment]
So you get the functionality of localStorage while you are in the browser. i.e. when logging in on one tab, the other tab also becomes authenticated.

**Comment by marcoow** [comment]
The cookie store support tab/window syncing as well.
