### ISSUE TITLE
Error while loading route: TypeError: Invalid Fullname, expected: `type:name` got: null

### ISSUE THREAD

**Issue by ivpusic** [simplabs/ember-simple-auth#126]
My application route is:

```
App.ApplicationRoute = Ember.Route.extend(Ember.SimpleAuth.ApplicationRouteMixin, {
  model: function (params, transition) {
    var that = this;

    return App.Ajax.invoke('GET', '/api/users/logged')
      .then(function (user) {
        that.set('session.content', user);
        console.log('ok');
      }, function (err) {
        return that.get('session').invalidate();
      });
  }
});
```

So I want to try to get user from server, and if user is in server session it will return that user, otherwise it will return 401. If we get 401 I want to remove user from session. But above example doesn't work, it throws `Error while loading route: TypeError: Invalid Fullname, expected: `type:name` got: null` exception. 

I also tried with something like this

```
   error: function(reason) {
          if (reason.status === 401) {
            this.send('authorizationFailed');
          }
          return true;
        }
```

but I am getting the same error.

Do you know what can cause problem?

**Comment by BJKPriyanka** [comment]
Hi all, 

I am new to ember.I am getting the following error when during login and when trying to access localhost:4200.

TypeError: Invalid Fullname, expected: 'type:name' got: route:
    at Registry.validateFullName (vendor.js:17326)
    at Container.lookup (vendor.js:16298)
    at Class.lookup (vendor.js:49363)
    at C.getHandler (vendor.js:44902)
    at C.fetchHandler (vendor.js:63583)
    at C.get (vendor.js:63748)
    at C.becomeResolved (vendor.js:63719)
    at calculatePostTransitionState (vendor.js:45427)
    at Class._hydrateUnsuppliedQueryParams (vendor.js:45139)
    at Class._prepareQueryParams (vendor.js:45070)
