### ISSUE TITLE
How could we specify a different method to run session.restore / how to make this work with ember-prefetch?

### ISSUE THREAD

**Issue by erichonkanen** [simplabs/ember-simple-auth#1263]
We're using this package for auth and we implemented [ember-prefetch](https://github.com/nickiaconis/ember-prefetch/) for the performance gains however the two packages don't play nice with eachother because of how ember-prefetch works.

That package effectively runs network requests BEFORE the `ApplicationRoute.beforeModel()` by checking through all parent -> child routes for a `Route.prefetch()` method and if it exists, pulling the required data from it before the main ember route hooks. The problem we run into is for resources which require authorization, on a page reload and in other cases, prefetch is making the network request BEFORE ember-simple-auth has restored (or authenticated) and thus the requests get `401` and the user is logged out.

We tried to get around this by moving the specific redirect logic we need in our `ApplicationRoute.beforeModel()` to be inside `ApplicationRoute.prefetch()` but this unfortunately runs into other issues where it is called multiple times etc.

After investigating how ESA does the restore inside the instance-initializer, I'm wondering if there's a way to specify a different method besides `ApplicationRoute.beforeModel()` where the restore occurs? We were thinking to have it happen inside the `prefetch()` method in our case.

Or, if you have any other thoughts on this let me know... It's been hard to find information concerning these two packages working together but we're hoping we can make it happen somehow!

Thanks

https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js#L11

https://github.com/nickiaconis/ember-prefetch/issues/40

**Comment by jamiechong** [comment]
@erichonkanen Is the `session` service present at the time you need it for prefetch? 

I just discovered this workaround, that access a private api:

`this.get('session').get('session').restore()`

the first `session` is the service, the second one is the internal/private session.

**Comment by erichonkanen** [comment]
@jamiechong thanks, that's good to know! we ended up figuring out a different solution but ill relay that to coworkers too

**Comment by brandynbennett** [comment]
@erichonkanen What did you end up doing to make this work? or did you not use ember-prefetch?

**Comment by erichonkanen** [comment]
@brandynbennett i'll have to verify later but I glanced at the code and it looks like:
`app/mixins/route/maybe-prefetch.js`
```
import { resolve } from 'rsvp';
import Mixin from '@ember/object/mixin';
import config from 'client-web/config/environment';

export default Mixin.create({
  prefetch() {
    return this.maybePrefetch(...arguments);
  },

  model() {
    return this.prefetched(this.routeName)
      .then(model => model ? model : this.maybePrefetch(...arguments));
  },
});
```
`app/routes/index.js`
```
import Route from '@ember/routing/route';
import MaybePrefetch from 'client-web/mixins/routes/maybe-prefetch';
import PaginationMixin from 'client-web/mixins/routes/pagination';

export default Route.extend(
    MaybePrefetch,
    PaginationMixin, {

  maybePrefetch() {
    return this.queryPaginatedData('content', 'next', {}, 'below');
  }
});
```

**Comment by brandynbennett** [comment]
Thanks @erichonkanen. So I gave that a try and I'm still seeing the same behavior where the session gets invalidated.

**Comment by erichonkanen** [comment]
@brandynbennett yeah to be honest I think bc we're actually using a slightly different control flow right now where we route around that logic that it may still exist and we just haven't come back to it :D working another thing atm but i'll look later... I may just not use prefetch if it's too much effort for now

**Comment by brandynbennett** [comment]
I ended up overriding the instance-initializer that does the `restore`

```
// instance-initializers/setup-session-restore.js
function setupSessionRestoration(instance) {
  const applicationRoute = instance.lookup('route:application');
  const session = instance.lookup('session:main');

  applicationRoute.reopen({
    prefetch() {
      return session.restore().then(() => true, () => true);
    },
  });
}

export default {
  name: 'ember-simple-auth-with-prefetch',
  after: 'ember-simple-auth',

  initialize(instance) {
    setupSessionRestoration(instance);
  },
};
```

Then in my prefetched, authenticated routes I wait for the prefetched application

```
// routes/some-route.js
Route.extend({
  prefetch() {
    return this.prefetched('application').then(() => {
      return this.store.findAll('foo');
    });
  }
});
```

**Comment by erichonkanen** [comment]
interesting! thanks for that I'm gonna give it a spin
