### ISSUE TITLE
Inject custom token/session during fastboot

### ISSUE THREAD

**Issue by dulmandakh** [simplabs/ember-simple-auth#1264]
Hello,

I have a case where I need to require authentication to access a page, but render the page or part of it for crawlers during fastboot. I've configured fastboot and simple-auth on ember and it works like a charm, and renders a page if cookie exists, but login page if not.

I would like to inject custom token/session (or way to authenticate) for API service during fastboot if cookie doesn't exist. I wandered through documentation and code, but couldn't find a way to implement this correctly. I think that this feature would be super useful for a lot of cases.

Could you please advice on how I can implement above use case using fastboot and simple-auth.

**Comment by marcoow** [comment]
I'm not sure what the requirement is here tbh. By default the `AuthenticatedRouteMixin` will transition to the `login` route if a route that requires authentication is accessed without the session being authenticated. If you don't want that behavior you can just as well not use the mixin and always render the route and render/not render certain parts of the template depending on whether the session is authenticated or not.
