### ISSUE TITLE
DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill

### ISSUE THREAD

**Issue by dzbo** [simplabs/ember-simple-auth#1265]
I'm seeing this deprecation warning after upgrading Ember to 2.12.0

```
DEPRECATION: ember-getowner-polyfill is now a true polyfill. Use Ember.getOwner directly instead of importing from ember-getowner-polyfill [deprecation id: ember-getowner-polyfill.import]
```

From deprecation stack trace seems like its comming from `ember-simple-auth`

**Comment by marcoow** [comment]
Ember Simple Auth [does never import from `ember-getowner-polyfill`](https://github.com/simplabs/ember-simple-auth/search?utf8=✓&q=ember-getowner-polyfill). This is either an older version of Ember Simple Auth or coming from a different dependency.
