### ISSUE TITLE
Passing arbitrary context through to the `authenticationRoute` when transition is rejected by the AuthenticatedRouteMixin

### ISSUE THREAD

**Issue by Duder-onomy** [simplabs/ember-simple-auth#1268]
Great tool! Thanks so much. I rely on this code heavily at work. 

If a user hits a page where they must be authenticated, we currently kick them out and over to the `authenticationRoute` as provided by the `AuthenticatedRouteMixin`.  I have been tasked with adding context to this rejection. Basically, showing the user 'WHY' we kicked them out and over to the login page. In my implementation, I would do this by passing a queryParam through to the `authenticationRoute` transition, making it easy to define on each authenticatedRoute a reason why someone would not be allowed to go there unauthenticated. 

I would like to change [this line in the `authenticatedRouteMixin`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/authenticated-route-mixin.js#L96) to pass arbitrary context to the `authenticationRoute`

from: 
```javasacript
this.transitionTo(authenticationRoute);
```
to:
```javasacript
this.transitionTo(authenticationRoute, get(this, 'authenticationRouteContext'));
```

Is anyone else interested in this? or should I abandon my quest to push this upstream from my implementation into `ember-simple-auth` core.

**Comment by marcoow** [comment]
I don't think changing the code in ESA to

```js
this.transitionTo(authenticationRoute, get(this, 'authenticationRouteContext'));
```

is the way to go really as you then have to pass the context as the route's model but sometimes that might be better as a query param etc.

I guess we could change it to

```js
this.transitionToAuthenticationRoute();
```

though with a default (but overridable) implementation of `transitionToAuthenticationRoute` of

```js
transitionToAuthenticationRoute() {
  let authenticationRoute = this.get('authenticationRoute');
  assert('The route configured as Configuration.authenticationRoute cannot implement the AuthenticatedRouteMixin mixin as that leads to an infinite transitioning loop!', this.get('routeName') !== authenticationRoute);

  this.transitionTo(authenticationRoute);
}
```

That would allow what you need but in a more generic way.

**Comment by Duder-onomy** [comment]
@marcoow That sounds great. Thanks for taking the time to respond. This would fix my problem and also allow for even more flexibility. 

Would you like me to add this and PR?

**Comment by marcoow** [comment]
> Would you like me to add this and PR?

That would be awesome!

I think we should maybe even name the method `triggerAuthentication` or so as depending on the mechanism you might not even want to transition but maybe open a new window or so.
