### ISSUE TITLE
Session persistence is broken in Ember 2.13

### ISSUE THREAD

**Issue by ef4** [simplabs/ember-simple-auth#1284]
Using ember 2.13.0-beta.1, the adaptive session storage doesn't successfully restore your session. 

To reproduce make sure you're using ember-simple-auth's provided ApplicationRouteMixin. 

What happens is the following.

1. `ember-simple-auth/instance-initializers/setup-session-restoration` looks up `application:route`.
2.  Via injections, this causes `session:main` to be created, which causes `ember-simple-auth/internal-session` to be created. 
3. During internal-session's constructor, it's own `setUnknownPropery` is firing for `key="__OWNER__ [id=__ember14915407849691325476096106]"` (the ember-generated key used for tracking object ownership).
4. This causes `_updateStore()` to run, which overwrites the valid session with `null`.
5. Then the application route's beforeModel runs and tries to restore the session, but it has already been destroyed.

**Comment by ef4** [comment]
I see this is a duplicate of https://github.com/simplabs/ember-simple-auth/pull/1267

**Comment by marcoow** [comment]
Yep, fixed already - we need to release 1.2.1.

**Comment by marcoow** [comment]
I mean we need to release 1.2.2 actually which I'll do in a minute…
