### ISSUE TITLE
Better way to inject authentication data after registration

### ISSUE THREAD

**Issue by ruz** [simplabs/ember-simple-auth#1286]
Hello,

I hope community and/or developers can come up with better way to do the following:

```
       let {email, name, password} = this.getProperties('email', 'name', 'password');
        this.set('errors', null);
        Ember.$.ajax({
          method: 'POST',
          url: "/api/v1/auth/register",
          data: { email, name, password }, 
        }) 
       .then(
         (data) => {
           // DIRTY HACK to avoid login procedure:
           //this.get('session').authenticate('authenticator:oauth2', email, password);
           this.get('session.session')
           ._setup('authenticator:oauth2', data, true)
           .then(() => { this.dialog.close() });
         }
       )
```
Our registration API generates session token and I don't want to pass login/password twice what will result in two sessions on the server.

**Comment by marcoow** [comment]
Why do you want to avoid the login procedure?

**Comment by ruz** [comment]
second session generation, two requests to the server. are these not enough?

**Comment by marcoow** [comment]
Preventing a second request seems like over-optimization to me to be honest. I'm not sure about the point with preventing a second session. I'd say the registration endpoint should not create a session at all as registration as such shouldn't necessarily be coupled to logging in.

If you absolutely want to do this though you could create a custom authenticator (as an extension of the OAuth 2.0 authenticator) that can either take a username and password or an object with an access token in it. In the former case it would simply delegate to it's parent and in the latter case it would resolve with the object that's being passed right away.
