### ISSUE TITLE
Method to restore session manually instead of just on page refresh

### ISSUE THREAD

**Issue by jamiechong** [simplabs/ember-simple-auth#1287]
My authentication service (AWS Cognito) expires its token every 30 minutes. This doesn't mean the user is logged out, it just means I need to get a new token. 

Currently I have this implemented in my ESA authenticator's `restore` method, which only runs on page load. If the user sits idle, without refreshing the page, my API calls fail because their Access token is no longer valid. 

I'd like to repeatedly _restore_ my session at some  interval to ensure my access token is fresh. Is it possible to expose a method on the session service to achieve this? 

`this.get('session').restore()`

**Comment by jamiechong** [comment]
Shoot, just realized #1263  is related and possibly a duplicate. This issue/feature-request would be a general case that could probably help those guys out as well.

**Comment by marcoow** [comment]
The OAuth 2.0 authenticator [refreshes tokens periodically as well](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L358). I guess a similar mechanism would work for you as well?

**Comment by jamiechong** [comment]
Hmm. so put the polling inside the actual custom authenticator. Can you help me understand how this code works? How does the new token that is retrieved at some future time get set to the session? It seems like this code spawns a scheduled promise from within the `restore` method, but I don't understand how the new token gets set back to  `session.data`

**Comment by marcoow** [comment]
Whenever the token is refreshed, the authenticator triggers the [`sessionDataUpdated` event](http://ember-simple-auth.com/api/classes/BaseAuthenticator.html#event_sessionDataUpdated) that the session is subscribed to automatically.

**Comment by marcoow** [comment]
Closing this as a (solved) question.
