### ISSUE TITLE
authenticate redirect fails on second attempt

### ISSUE THREAD

**Issue by michael-lynch** [simplabs/ember-simple-auth#1296]
I have my login working but there seems to be a bug and I'm not sure if it's my code or simple auth. When I enter the proper credentials, the login form works. When I put in the wrong credentials, the proper error is thrown. _But then when I fix the error and submit the form again, I get this error:_

`TypeError: this.transitionTo is not a function`

I am using an action on a _component_. I believe components use `transitionToRoute()` and not `transitionTo()`. Does simple auth expect the action to be on a route?

Here is my action:

	export default Ember.Component.extend(ApplicationRouteMixin, {
	    session: Ember.inject.service('session'),
	    actions: {
	        authenticate: function(form) {

		    let email = form.get('email');
		    let password = form.get('password');
		    let _this = this;

		    _this.set('hasError', false);

		    _this.get('session').authenticate('authenticator:login', email, password).catch((reason) => {

			_this.set('errorMessage', reason.error || reason);
			_this.set('hasError', true);
					
		    }).then(function() {
			console.log('finished');
		    });
	        }
	    }
    });

Here is my config:

    ENV['ember-simple-auth'] = {
	    authenticationRoute: '/',
	    store: 'simple-auth-session-store:local-storage',
	    authorizer: 'authorizer:custom',
	    routeAfterAuthentication: '/dashboard'
    };

Am I missing something?

**Comment by marcoow** [comment]
You cannot use the `ApplicationRouteMixin` in a component. The only way the mixin can be used is by mixing in to the application route.
