### ISSUE TITLE
OAuth2 authenticator does not handle html response

### ISSUE THREAD

**Issue by janmisek** [simplabs/ember-simple-auth#1298]
In case response with with `content-type: text/html` is returned to method makeRequest method reject callback is not called and error is thrown outside of promise . 

https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L328

Following error leaks to ember.logger:
```
 Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
```

**Comment by marcoow** [comment]
I don't think that needs to be handled by ESA. It's just an invalid response that the authenticator cannot understand.

**Comment by janmisek** [comment]
So how should I catch this JSON.parse error in context of authenticate promise ?

**Comment by marcoow** [comment]
The OAuth 2.0 authenticator only works with OAuth 2.0 endpoints. Your server does not seem to be one - this is an error on the server side, not the client side.

**Comment by janmisek** [comment]
We have compliant OAuth 2.0 server. But there are valid use cases that even oauth compliant server returns unexpected response. e.g load balancer / proxy error ...e.g standard nginx 500 error page in that case I need to somehow handle it.
