### ISSUE TITLE
Shared session between domains

### ISSUE THREAD

**Issue by villander** [simplabs/ember-simple-auth#1309]
My app changes url when I change client, this is I can change company in my application and url change to `http://company.localhost: 4200`, then go to `http://company2.localhost: 4200` and so on.

Most of the time I change of company and the login is restored, but sometimes the session together with the localStorage is lost. So I can not simulate this error. Can anyone help me with this?

look my custom authenticator

```javascript
import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';
import gql from 'graphql-tag';

const {
  RSVP,
  isEmpty,
  get,
  inject: { service }
} = Ember;

export default Base.extend({
  session: service(),
  apollo: service(),

  restore(data) {
    return new RSVP.Promise((resolve, reject) => {
      if (!isEmpty(data.token)) {
        resolve(data);
      } else {
        reject();
      }
    });
  },

  authenticate(options) {
    if (options.token) {
      return this.withToken(options.token);
    } else {
      return this.withPassword(options.email, options.password);
    }
  },

  invalidate() {
    let mutation = gql`
      mutation Logout {
        logout(input: { clientMutationId: "" }) {
          session {
            token
          }
        }
      }
    `;
    return this.get('apollo').mutate({ mutation }).then((data) => data.logout.session);
  },

  withPassword(email, password) {
    let mutation = gql`
      mutation Login($input: LoginInput!) {
        login(input: $input) {
          session {
            token
          }
        }
      }
    `;
    let variables = { input: { email, password, clientMutationId: '' } };

    return get(this, 'apollo').mutate({ mutation, variables }).then((data) => data.login.session);
  },

  withToken(token) {
    return RSVP.Promise.resolve({ token });
  }
});

```

@marcoow

**Comment by marcoow** [comment]
You should not use the session service in the authenticator. The session calls the authenticator but not the other way round. Also what does your session store definition look like? You cannot actually share `localStorage` between subdomains as it is isolated per origin which includes the subdomain. You can use the cookie store and set the cookie domain so that the cookie will be shared across all subdomains though.

**Comment by The-Don-Himself** [comment]
I've also been looking into achieving this using Localstorage as it's benefits greatly outweigh Cookies for my use case.

So far, it seems the acceptable hack to this is using iframes and postMessage 
 - https://stackoverflow.com/a/7722326/5100895
A hack similar to how Google uses it's AMP cache. Also, a pretty nice library has been open-sourced by Zendesk for the same 
 - https://github.com/zendesk/cross-storage

Wondering if these hacks are worth looking into for the core ember-simple-auth or just to be left to individual developers to work it out for their projects.

**Comment by marcoow** [comment]
> Wondering if these hacks are worth looking into for the core ember-simple-auth or just to be left to individual developers to work it out for their projects.

This is out of scope for ESA. Tackling this means opening a huge can of problems and edge cases only to fix something that only a minority of ESA's users need anyway.

Of course that doesn't mean it wouldn't be valuable to some if a reusable solution for this problem existed. You could publish this in its own package though that provides a session store based on `localStorage` but with cross-origin support, e.g. `ember-simple-auth-cross-origin-localstorage` or whatever name you come up with ;)
