### ISSUE TITLE
Add example with multiple authenticators

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#131]
This would help people to understand that Ember.SimpleAuth supports multiple authenticators in one app, while only one is active at a time.

**Comment by mmahalwy** [comment]
Not possible to have multiple active? For example, I am using devise and created my own provider for Shopify with Torii.

**Comment by marcoow** [comment]
@mmahalwy: the application can support multiple authentication mechanisms but the session can only be authenticated with one authenticator at a time. Actually there should even be an assertion somewhere in the code that asserts that the session is not already authenticated when calling the `session` service's `authenticate` method.

**Comment by mmahalwy** [comment]
Ah, makes sense! I haven't seen any race condition when authenticating on top of another.

**Comment by marcoow** [comment]
@mmahalwy: there is no race condition really but also no use case. If a user is currently not logged in to their account that they defined credentials for as well as connected their Twitter account to, as soon as they log in with either entering credentials or clicking "Login with Twitter" there's no point in also logging in with the other mechanism anymore.

Please correct me if I'm just not seeing sth. here.

**Comment by mmahalwy** [comment]
Yep, completely agree. I guess my use case was you signed up and now need you to authenticate other services you use (eg. Twitter, Facebook) but using `this.get('torii').open()` has been the better was to go through this. 

Thank you!

**Comment by sescobb27** [comment]
Hi, I have an use case for this, i have an app in which we have customers and admins, customers can log in with email and password via JWT (we are using Ember Simple Auth Token for this), but admins can only be logged in via Google OAuth with it's google corporate email (we are using torii for this), the problem is that we need to keep the request authenticated for admins with JWT so we can know if the customer issuing some request is an admin or not.

this is what we are doing right now but don't know if that's the correct approach because it feels hacky
```js
export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:token'
});
```

```js
// authenticator:torii
import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii';
export default ToriiAuthenticator.extend({
  torii: Ember.inject.service(),
  authenticate() {
    let args = arguments;
    return new Ember.RSVP.Promise((resolve, reject) => {
      this._super(...args)
        .then((data) => {
          Ember.$.ajax({
            url: `/auth/admin`,
            type: 'POST',
            contentType: 'application/json',
            dataType: 'json',
            headers: {
              Authorization: `Bearer ${data.authorizationToken.access_token}`
            }
          }).then(resolve, reject); // it returns { token: 'JWT TOKEN' }
        }, reject);
    });
  },
  restore(data) {
    return Ember.$.ajax({
      url: `${config.api.host}/auth/refresh`,
      type: 'POST',
      contentType: 'application/json',
      dataType: 'json',
      data: JSON.stringify({
        token: data.token
      })
    }); // it returns { token: 'JWT TOKEN' }
  },
  invalidate() {
    return new Ember.RSVP.resolve();
  }
});
```

```js
export default Ember.Route.extend(UnauthenticatedRouteMixin, {
  session: Ember.inject.service('session'),
  actions: {
    // action to trigger authentication with Google+
    authenticateWithGooglePlus: function () {
      return this.get('session')
        .authenticate('authenticator:torii', 'google-oauth2-bearer');
    }
  }
});
```
it works but it will be great to have an example of how to handle multiple authenticators. thanks

**Comment by marcoow** [comment]
The dummy app included in the repo uses multiple authenticators actually. Does that example not illustrates the use case you're looking for?

**Comment by sescobb27** [comment]
@marcoow wow you are right, thank you, i didn't look at it before
