### ISSUE TITLE
How to use esa in acceptance tests ?? import ? configurations ?

### ISSUE THREAD

**Issue by BnitoBzh** [simplabs/ember-simple-auth#1315]

**Comment by marcoow** [comment]
https://github.com/simplabs/ember-simple-auth/blob/master/README.md#testing

**Comment by BnitoBzh** [comment]
I already add this import, but it doesn't work ... is there any other configuration ?

**Comment by BnitoBzh** [comment]
not ok 8 PhantomJS 2.1 - Acceptance | login: visiting /login should redirect to / when user is already connected
    ---
        actual: >
            null
        expected: >
            null
        stack: >
            authenticateSession@http://localhost:7357/assets/tests-78332128ddd696f21735d10ded231ff8.js:234:24
            http://localhost:7357/assets/tests-78332128ddd696f21735d10ded231ff8.js:24:61
            runTest@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:3852:34
            run@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:3838:13
            http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:4030:15
            advance@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:3515:26
            begin@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:5206:27
            http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:4400:11
        message: >
            Died on test #1 http://localhost:7357/assets/tests-78332128ddd696f21735d10ded231ff8.js:23:19
            exports@http://localhost:7357/assets/vendor-b57f2d4134d0ddfd0190099e4e4ae7ec.js:119:37
            requireModule@http://localhost:7357/assets/vendor-b57f2d4134d0ddfd0190099e4e4ae7ec.js:34:25
            require@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7672:14
            loadModules@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7664:21
            load@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7694:33
            http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7577:22: undefined is not an object (evaluating 'app.__container__')
        Log: |
    ...

**Comment by BnitoBzh** [comment]
`not ok 8 PhantomJS 2.1 - Acceptance | login: visiting /login should redirect to / when user is connected
    ---
        actual: >
            null
        expected: >
            null
        stack: >
            authenticateSession@http://localhost:7357/assets/tests-78332128ddd696f21735d10ded231ff8.js:234:24
            http://localhost:7357/assets/tests-78332128ddd696f21735d10ded231ff8.js:24:61
            runTest@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:3852:34
            run@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:3838:13
            http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:4030:15
            advance@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:3515:26
            begin@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:5206:27
            http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:4400:11
        message: >
            Died on test #1 http://localhost:7357/assets/tests-78332128ddd696f21735d10ded231ff8.js:23:19
            exports@http://localhost:7357/assets/vendor-b57f2d4134d0ddfd0190099e4e4ae7ec.js:119:37
            requireModule@http://localhost:7357/assets/vendor-b57f2d4134d0ddfd0190099e4e4ae7ec.js:34:25
            require@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7672:14
            loadModules@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7664:21
            load@http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7694:33
            http://localhost:7357/assets/test-support-bf3770aa0cec70dbf5edbf4f4330b09c.js:7577:22: undefined is not an object (evaluating 'app.__container__')
        Log: |
    ...
`

**Comment by marcoow** [comment]
You need to provide some detail to enable people to help you with this (ideally just the source of your acceptance test file). You can have a look at Ember Simple Auth's own acceptance tests for guidance: https://github.com/simplabs/ember-simple-auth/blob/master/tests/acceptance/authentication-test.js#L36
