### ISSUE TITLE
Cookie store setting expiration_time cookie on every FastBoot request

### ISSUE THREAD

**Issue by dbbk** [simplabs/ember-simple-auth#1323]
I have my `cookieExpirationTime` set to 2 years. Every time a FastBoot-served request is made, this response header is getting sent:

`set-cookie:cookiename-expiration_time=63072000; expires=Mon, 06 May 2019 17:17:44 GMT; path=/`

The issue that arises is that the FastBoot-rendered output cannot be CDN cached as the server response is sending `set-cookie` every time. Is there any way around this? Could it perhaps only be set on the client-side?

**Comment by marcoow** [comment]
Syncing cookies between FastBoot and the browser is the fundamental mechanism that enables out-of-the-box FastBoot support in Ember Simple Auth.

I'm also not sure caching FastBoot responses is desirable at all actually. How do you invalidate that cache?

**Comment by dbbk** [comment]
Caching is important for us in terms of performance and scale. Cloudflare brings our page load times down from around 5 seconds to 52ms.

Though we use Ember Simple Auth, much of our site content is static. You can programatically invalidate the edge cache, but we tend to just keep it at around 1 hour.

For a more content heavy site, doing a direct FastBoot render every time is going to be difficult and costly to scale.

**Comment by marcoow** [comment]
I don't see how caching responses in a CDN ever makes sense for authenticated pages which potentially contain user-specific information to be honest. If anyone comes up with an implementation for #1322 it would of course be possible to not store the expiration time cookie when the data cookie doesn't exist.

I'm closing this for now - feel free to reopen if there's a solution for #1322.
