### ISSUE TITLE
JSON Parse error Unrecognized token '<' parse@[native code]

### ISSUE THREAD

**Issue by EmberJSParis** [simplabs/ember-simple-auth#1324]
I have a problem with https://github.com/simplabs/ember-simple-auth. It works perfect in localhost but deployed on Firebase there is a bug common to all login (email, Google or Facebook) The bug is here https://artadysgouv.fr and is: "JSON Parse error: Unrecognized token '<' parse@[native code]" .

**Comment by marcoow** [comment]
That error usually means that your API returns HTML instead of JSON so that the authenticator fails to parse the response as JSON.

**Comment by EmberJSParis** [comment]
I agree Marco but what API ? I just run the code from GitHub https://github.com/simplabs/ember-simple-auth <https://github.com/simplabs/ember-simple-auth> and I just deployed on Firebase 

is the same code that run in localhost. No modifs I made.

I checked according to this link to solve the bug http://stackoverflow.com/questions/23558907/convert-text-file-into-clean-json-format
………but I got a conflict because in the original code you don't parse JSON but something else ??????
line 329 oauth2-password-grant.js "let json = text ? JSON.parse(text) : {};" in oauth2-password-grant.js ???????line 329 but I am not sure


Thanks Marco

**Comment by marcoow** [comment]
I assume you're using the OAuth 2.0 authenticator. That only works with servers that implements the [_"Recource Owner Password Credentials"_ OAuth 2.0 grant type](https://tools.ietf.org/html/rfc6749#section-1.3.3).

Ember Simple Auth does not include any server component.
