### ISSUE TITLE
Session Service and Cookie Store Not Getting Initialized

### ISSUE THREAD

**Issue by RambleOn** [simplabs/ember-simple-auth#1327]
I am using ember-simple-auth across multiple Ember projects. I recently added another Ember project to the mix and am having issues with this project's front-end authentication.

My Ember project structure has a main application that handles the initial authentication. Once a user is authenticated, a session token is stored in the CookieStore. From this application, I can navigate to other Ember applications and retain the session by pulling the session data from the CookieStore.

However, this fails for the latest application, but only on the first try. When I initially navigate to the new application, I am kicked back to the authentication app but remain logged in. When I navigate again to the new application, I am successfully authenticated in the new application.

Also, I am unable to destroy the session cookie from the new application. Upon logout, I am returned to the authentication application but remain logged in. If I logout from other applications, the session cookie is completely destroyed, and I am logged out of all applications.

All session logic is stored in an Ember add-on that is re-used across all applications, so there is no code differences for how session data is stored and retrieved. The only difference is that the latest application was created with Ember 2.13.1. All other applications were created with earlier versions of Ember but have since been updated to 2.13.1.

**Comment by marcoow** [comment]
You'll need to provide some more detail so we can investigate this further.

- Which version of ESA are you on?
- Do the apps run on different domains maybe
- Ideally link to the app's sources or a demo project that shows the same behavior
- Do you see any errors?

**Comment by RambleOn** [comment]
@marcoow:

* Which version of ESA are you on?
I'm using version 2.1.0.

* Do the apps run on different domains maybe?
All applications are on the same domain but with different endpoints.
** Auth App: http://localhost:4200 (dev), https://domain.com (prod)
** App #1: http://localhost:4201 (dev), https://domain.com/app1/ (prod)
** App #2: http://localhost:4202 (dev), https://domain.com/app2/ (prod)
** App #3: http://localhost:4203 (dev), https://domain.com/app3/ (prod)

- Ideally link to the app's sources or a demo project that shows the same behavior.
I can't provide the full code, as this is a proprietary application for my company. However, I will attach relevant code snippets
[ember-simple-auth-snippets.zip](https://github.com/simplabs/ember-simple-auth/files/993175/ember-simple-auth-snippets.zip)
.

- Do you see any errors?
There are no errors generated. Furthermore, if I delete the cookie in the debug console while logged into any app but app #3, I am automatically logged out. For app #3, nothing happens.

**Comment by marcoow** [comment]
> I'm using version 2.1.0.

I assume 1.2.0? Try upgrading to 1.3.0 and check whether the problem persists.

> All applications are on the same domain but with different endpoints.

What is the sessions cookie's `path`? Is it actually sharable between the 4 apps?

**Comment by RambleOn** [comment]
I'm sorry about the version. I am actually using 1.3.0 currently. The 2.1.0 version is for ember-simple-auth-token.

The path is simply "/" and is accessible from all applications. For app 3, the cookie works after entering the application after the initial attempt, so I wouldn't think that there is an issue with the path. The problems are the following:
* App 3 doesn't believe the session is authenticated upon first entry.
* When invalidating the session in app 3, a user is not fully logged out but is taken back to the auth app and remains logged in. If I logout from any other app, the session is correctly invalidated, and the user returns to the login prompt.
* Upon logging out from app 3 and returning to the auth app with a still validated session, I can access any other app but app 3. It acts like problem 1 above (cannot access app on initial try but can on subsequent tries).

This issue is very bizarre. I am going to recreate app 3 from an older version of ember and see if the problem persists.

**Comment by RambleOn** [comment]
No luck in creating the application with an older version of Ember. I did find that the problem seems to be that the Session Store does not get initialized the first time the application loads. The authenticated cookie exists. However, the first time the application loads, the isAuthenticated call returns false.

**Comment by RambleOn** [comment]
This issue has been fixed. I had named the session store directory in my app to session-store and not session-stores.
