### ISSUE TITLE
Uncaught Error: Could not find module `ember-simple-auth/configuration

### ISSUE THREAD

**Issue by v3ss0n** [simplabs/ember-simple-auth#1331]
In a new ember app , i am getting

```
loader.js:243 Uncaught Error: Could not find module `ember-simple-auth/configuration` imported from `simpauth/initializers/ember-simple-auth`
    at missingModule (http://localhost:8988/assets/vendor.js:248:11)
    at findModule (http://localhost:8988/assets/vendor.js:259:17)
    at Module.findDeps (http://localhost:8988/assets/vendor.js:199:24)
    at findModule (http://localhost:8988/assets/vendor.js:262:11)
    at requireModule (http://localhost:8988/assets/vendor.js:29:15)
    at http://localhost:8988/assets/vendor.js:114941:20
    at Array.forEach (native)
    at exports.default (http://localhost:8988/assets/vendor.js:114938:8)
    at Module.callback (http://localhost:8988/assets/simpauth.js:17:41)
    at Module.exports (http://localhost:8988/assets/vendor.js:140:32)

```

**Comment by marcoow** [comment]
@v3ss0n: does this problem persist after a `rm -rf node_modules && npm install`?

**Comment by srvance** [comment]
I just got back to an app that I haven't built and run for awhile but have updated ESA with GreenKeeper. I'm running into the same thing even after deleting `node_modules` and doing an `npm install`. This is with ember-cli 2.12.3, loader.js 4.5.1 and ESA 1.3.0.

I've verified that there is a `node_modules/ember-simple-auth/addon/configuration.js` but none in the `app` directory. I'm happy digging into it. Any suggestions where to look, @marcoow?

**Comment by srvance** [comment]
I can repeat this by doing

```
$ ember new esa-config-error
$ cd esa-config-error
$ ember install ember-simple-auth
$ ember s
```

with ember-cli 2.13.0.

Using `npm link` to a local copy of ESA, I tried adding

```js
// app/configuration.js
export { default } from 'ember-simple-auth/configuration';
```

and it did not fix the problem. The error originates from [this line](https://github.com/simplabs/ember-simple-auth/blob/master/app/initializers/ember-simple-auth.js#L2).

I'll set up a PR if I find a solution but wanted to share the additional details and repro steps.

**Comment by srvance** [comment]
Additionally, changing the order of the imports in the initializer always fails on the first `ember-simple-auth`-anchored import.

**Comment by srvance** [comment]
Update on my situation: After repeated attempts of changing node and nuking and rebuilding my node installations, I looked elsewhere. It turns out a Chrome extension called "REST client" was the culprit. Disabling it restored proper function, so I deleted it. I can't even find it on the Chrome web store now. 

@v3ss0n Any chance this is your problem?

**Comment by v3ss0n** [comment]
Yes i have that installed tooo!

**Comment by marcoow** [comment]
guess this is fixed
