### ISSUE TITLE
redirect in AuthenticatedRouteMixin fastboot mode

### ISSUE THREAD

**Issue by zion03** [simplabs/ember-simple-auth#1334]
When I try to access router with `AuthenticatedRouteMixin` under https proxy I receive following redirecting:

Request: `https://domain.com/secured_route` --> `http://domain.com:3001/login`

The same request under `http` works fine.
These happened because `fastboot` works behind proxy server on http protocol.
Any solution how to fix it?

**Comment by marcoow** [comment]
Does the proxy not correctly set the `X-Forwarded-Proto` header maybe?

**Comment by zion03** [comment]
I tried locally on Apache 

`RequestHeader set X-Forwarded-Proto "https"` 

and logs

` X-Forwarded-Proto: https - - [16/May/2017:11:06:06 +0300] "GET /user/12/settings HTTP/1.1" 307 106 "-Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.89 Safari/537.36"  `

But it's can't helps, still redirect to `http`

**Comment by marcoow** [comment]
Closing this as this would be a FastBoot issue anyway. FastBoot is setting the location header in its [override of the `none` location](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/app/locations/none.js#L46).
