### ISSUE TITLE
Using assert outside of promise context causes async function to become sync

### ISSUE THREAD

**Issue by steffansluis** [simplabs/ember-simple-auth#1335]
An example of this can be found [here](https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L51), however it's probably that this is the case in more places. Is this intended behavior? :confused:

**Comment by marcoow** [comment]
I think as the invocation is supposed to fail anyway that is fine. Ember Data is doing the same thing [e.g. in the `find` method](https://github.com/emberjs/data/blob/58bd3960071784304a5bc5b6c8dac2a50358951b/addon/-private/system/store.js#L459).
