### ISSUE TITLE
Deploy dummy app the https://ember-simple-auth.com/demo

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#1339]
Running the dummy app on some server would be hugely benefitial for people to have an easy look at a running example. We need that to run FastBoot so we have a full-featured example - ideally we can also reuse the fake server from the repo.

- [ ] see whether we can deploy the dummy app to heroku or now or whatever (incl. FastBoot support then which we wouldn't have if we deployed to github pages)
- [x] see whether we can deploy the [mock server](https://github.com/simplabs/ember-simple-auth/tree/master/server) to heroku or now or whatever
- [ ] add links in README and ember-simple-auth.com
- [ ] auto-deploy when we release (similar to the way we [release tags automatically](https://github.com/simplabs/ember-simple-auth/blob/master/.travis.yml#L31))

**Comment by stevenwu** [comment]
@Turbo87 deploying to now.sh requires removing `ember-cli-build.js` from [.npmignore](https://github.com/simplabs/ember-simple-auth/blob/master/.npmignore). Are there any issues with this?

**Comment by Turbo87** [comment]
aside from the increased archive size for the npm package I don't expect any issues when doing that. seems strange though that now.sh relies on that...

**Comment by marcoow** [comment]
This was done actually
