### ISSUE TITLE
Allow to have an "isAuthenticating"

### ISSUE THREAD

**Issue by bakura10** [simplabs/ember-simple-auth#135]
Hi,

It would be nice to have a property (called "isAuthenticating" in the LoginController mixin) that would be set to true when an authentication process is started, and to false when it has finished. This would allow to have some feedback to the user :).

**Comment by kenips** [comment]
hey @marcoow I just came across this and I think it's actually more natural to use `{{session.isAuthenticating}}` than having some random state in my controller to take care of it. Would you reconsider adding this? I can submit a PR essentially bringing the above into session's `authenticate`.

**Comment by marcoow** [comment]
Maybe it would be good to have a state machine then like torii has: https://github.com/Vestorly/torii/blob/master/lib/torii/session/state-machine.js. This should be done post 1.0 though as it wouldn't be a breaking change and I don't want to postpone the 1.0 release unnecessarily.

**Comment by kenips** [comment]
:+1: thanks for considering it. It might be beyond me to bring state machine over, but I can definitely see the benefits to it. Currently I rely on route / controller to sync `currentUser` information but I can foresee leveraging session success / restore state for cleaner code.
