### ISSUE TITLE
Use ember-fetch instead of ember-network

### ISSUE THREAD

**Issue by cmitz** [simplabs/ember-simple-auth#1350]
I've been running into problems with dependencies, packages etc and stumbled upon a comment from the ember-network package: https://github.com/ember-cli/ember-cli/issues/6946#issuecomment-293133803

It suggests to move from ember-network to ember-fetch, since is is actively maintained.
Maybe ember-simple-auth should use ember-fetch as well?

**Comment by scottwernervt** [comment]
The latest release [1.3.0](https://github.com/simplabs/ember-simple-auth/blob/1.3.0/package.json) uses ember-fetch instead of ember-network, see pull #1288.

**Comment by cmitz** [comment]
Sorry for not having seen the new release!
