### ISSUE TITLE
Allow rejectWithResponse for successful but malformed responses

### ISSUE THREAD

**Issue by The-Don-Himself** [simplabs/ember-simple-auth#1352]
Before you submit an issue, please review [the guidelines](https://github.com/simplabs/ember-simple-auth/blob/master/CONTRIBUTING.md) for this repository.
-Done.

1. Please only create issues for bugs, feature requests etc. - mere questions can be asked (and usually will be answered) on stackoverflow.
- This issue is a feature request

2. Update to the latest release of Ember Simple Auth if possible (see the releases page).
- As of the time of writing, it applies to the latest versions 1.2 and below.

3. Update to the latest releases of Ember.js, jQuery, Ember Data if possible
- Done.

4. Include as much information as possible - this includes full stack traces etc.
- The issue is to suggest that the rejectWithResponse be activated even when there was a successful response but missing token. Currently, it's only set for 4xx and 5xx responses but I have a use case where a 2xx response is returned intentionally without a token. I have implemented service workers for my ambitious [web app](https://campus-discounts.com/), leveraging https://github.com/DockYard/ember-service-worker. I have now created a plugin extending it (beta) to enqueue requests that fail because of a flaky network and/or server errors https://github.com/campus-discounts/ember-service-worker-enqueue. It currently only applies to mutation requests POST/PUT/DELETE etc. The service worker intercepts all such requests and for those that fail because of no network or server errors. it responds with a 202 HTTP_ACCEPTED response then queues them in localforage to be processed later via background sync and/or periodically.

The issue is that Ember Simple Auth treats a 202 response as successful but then fails to authenticate because of a lack of token which is ok, but I would like to get the response status code so as to tell the user that the login attempt has been queued and will automatically be processed later, but this is not exposed. My current ugly hack is this:-
````
            this.get('session').authenticate('authenticator:oauth2', identification, password).catch((reason) => {
                if(reason == 'access_token is missing in server response') {
                    this.get('systemMessages').show('Your login attempt has been queued & will be processed when the network is stable');
....
````
But I can't rely on that for the long term, I propose to allow us to expose the response in the event of authentication failure not just if on error. If this is OK, I can submit a PR.

5. Set up a demo that demonstrates the issue on JSFiddle or JSBin. If your project is open source, provide a link to the online repo.
- N/A

**Comment by marcoow** [comment]
> but I would like to get the response status code so as to tell the user that the login attempt has been queued and will automatically be processed later,

I'm not sure this makes sense for login at all to be honest as if the user had a typo in their password everything they did afterwards would have to be trashed. I guess you just can't login when you're offline as you can't validate the credentials then. Also the response you get isn't a valid OAuth 2.0 response as per the spec and I don't think something that ESA should handle. You could of course override the respective methods of the authenticator and I think that's the way to go here.

**Comment by The-Don-Himself** [comment]
@marcoow thanks for getting back on this.

I think (without hard facts) that so many users use remember me that a password typo for repeat logins would be rare. Modern browsers like chrome not only notify users to save a passwords but also offer syncing them across devices.

Also, perhaps you might have slightly misunderstood this issue, its not about Offline logging in per say but queuing failed login attempts either because of a network error(e.g subways) or server error (e.g in case of upgrades or traffic spikes). When the network is stable, I process the queue and simply postMessage from service worker to client logging him in if successful or alert if not.

If this seems like a valid use case, then I'd be glad to send in a PR which basically changes the line e.g here
https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L239

````
reject('access_token is missing in server response');
````
to something like
````
useResponse ? reject(response) : reject('access_token is missing in server response');
````

I wonder if this subtle change would break any existing applications, because at the moment for me even adding a full stop or space in the current error message would break my app while overriding the entire authenticate function seems like overkill to me.

Kindly advise.

**Comment by marcoow** [comment]
I think the rejections are somewhat wrong anyway. What we should do is reject with a proper `error` object instead of either the response or a string anyway. I guess a good change would be to make the promise reject with an `Error` that could have the response as a property.

**Comment by marcoow** [comment]
cleaning old issues
