### ISSUE TITLE
Multiple ember_simple_auth:session localStorage sessions?

### ISSUE THREAD

**Issue by tiandavis** [simplabs/ember-simple-auth#1354]
Hi @marcoow!

I know https://github.com/simplabs/ember-simple-auth/issues/859 has been closed for awhile, but is there a way to have multiple `ember_simple_auth:session` for this scenario where you need to run two or more different app versions side by side in separate tabs? 

Say you're working on an application like:
https://bigco.com/companies/123/
https://bigco.com/companies/456/

And each `companies/XXX` has to authenticate w/ the API separately. If we have a tab open for company 123 and a separate tab open for company 456, what we're seeing is 123 authenticates and then 456 authenticates and overwrites the session. So the session ends up looking like this:

Key
```
ember_simple_auth:session
```

Value
```
{"authenticated":{"authenticator":"authenticator:bigco","company":{"companyId":"456","key":"fb0427a0-06f2-4dc6-b402-3ff46dce1e40","expiresAt":"2017-06-08T15:35:51.152Z"}}}
```

Ideally, we'd have two sessions somehow like:

Key
```
ember_simple_auth:session_company_123
```

Value
```
{"authenticated":{"authenticator":"authenticator:bigco","company":{"companyId":"123","token":"db0427a0-06f2-4dc6-b202-3ff46dce1e39","expiresAt":"2017-06-08T15:35:51.152Z"}}}
```

and:

Key
```
ember_simple_auth:session_company_456
```

Value
```
{"authenticated":{"authenticator":"authenticator:bigco","company":{"companyId":"456","token":"gb0427a0-06f2-4dc6-b202-3ff46dce2e49","expiresAt":"2017-06-08T15:35:51.152Z"}}}
```

How do we go about accomplishing this? Thanks @marcoow!

**Comment by marcoow** [comment]
Two apps running on the same domain with 2 different `localStorage` keys (or cookie names) should have 2 separate session that don't share anything. If that's not the case please open an issue.
