### ISSUE TITLE
Feature: Name mixins and other exports of this addon

### ISSUE THREAD

**Issue by pichfl** [simplabs/ember-simple-auth#1357]
I work on large projects and more than often I find myself wading through a whole bunch of `UnknownMixin` and similar objects inside of Ember Inspector. 

We recently discovered that Ember Inspector reads the `[Ember.NAME_KEY]` property of each Ember Object to display a proper name.

Therefore I propose to add this property to all mixins and objects exported by this addon, making the object stack a bit easier to read. 

If this sounds interesting, I'll supply a pull request for this. 🙂

**Comment by marcoow** [comment]
Seems like a worthwhile addition. I'm not sure `Ember.NAME_KEY` is public or there's a public way of accessing it though?

**Comment by pichfl** [comment]
It's not quite public. Though others are using it as well:
- https://github.com/emberjs/ember-inspector/issues/284
- https://github.com/DockYard/ember-validations/pull/389
- https://github.com/offirgolan/ember-cp-validations/issues/306

**Comment by marcoow** [comment]
guess it's _"intimate"_ API then ;)

So yeah, PR would be 👍

**Comment by pichfl** [comment]
After talking to @rwjblue on Slack I'd consider wrapping these calls with the DEBUG flag described here: https://github.com/babel/ember-cli-babel#general-purpose-env-flags (and in [his blog post here](http://rwjblue.com/2017/05/01/enabling-debug-code-stripping/)), making this only available in development

**Comment by marcoow** [comment]
This should actually be fixed in the Ember Inspector - see https://github.com/ember-cli/ember-rfc176-data/issues/12#issuecomment-320232883
