### ISSUE TITLE
Token Expiration

### ISSUE THREAD

**Issue by joshjeppson** [simplabs/ember-simple-auth#1358]
Using this awesome library and ember-simple-auth-auth0, I've got my ember apps talking to Auth0 and talking securely to my backend API. However, when the token expires, my backend API detects that and replies with a 401. ember-simple-auth should invalidate the session and then I would need to re-login or renew the session. Instead, I get two errors from Ember: **Error while processing route** (model failed) and **The adapter operation was aborted**.

Any suggestions on what I am doing wrong?

I'm using the ApplicationRouteMixin and DataAdapterMixin and using Ember Data to query the server.

Relevant versions:
- ember-cli: 2.13.2
- ember-simple-auth: 1.2.2
- ember-simple-auth-auth0: 3.0.1
- auth0.js: 8.6.0
- auth0-lock: 10.15.1

**Comment by marcoow** [comment]
Can you provide a stack trace? Is the 401 response the only response you're seeing or are there other responses as well?

**Comment by joshjeppson** [comment]
Thanks for responding @marcoow. I lost track of this because I was working on other projects. I was able to return to this problem late last week and today. Fortunately, I finally figured it out. Turns out that my Web API backend wasn't sending the proper CORS headers back with the 401 response. Thus ember-simple-auth couldn't process it because the browser errored out underneath it.
