### ISSUE TITLE
Add cookie warning

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#1368]
I think we're required to show a cookie warning on the website actually 😬

https://www.cookielaw.org/the-cookie-law/

There might be an external service we can use rather than implement it ourselves.

**Comment by RobIsHere** [comment]
Please don't! Let the application developer choose library, design and style of the warning he wants to use!

There are many different applications out there. So I think this should really be up to the plugin user. The user probably has to consult a lawyer on this anyway.

IMO: Maybe just include a big hint to the README and a link to the EU legislation documents.

(In my case if you add it I just have work with figuring out how to switch it off on one server where consent is given offline and redesign it on the other ;(

**Comment by marcoow** [comment]
@RobIsHere: don't worry, this is for ember-simple-auth.com only ;)
