### ISSUE TITLE
Support FastBoot 1.0

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#1371]
Currently, at least the test suite does not work with FastBoot 1.0 (or its latest release candidate). This obviously needs to be fixed or we might end up blocking people from switching to FastBoot 1.0.

**Comment by simonihmig** [comment]
@marcoow I think this can be closed now as well! :)

**Comment by marcoow** [comment]
Let's close when we're we actually support 1.0 and not the latest RC.

**Comment by simonihmig** [comment]
Ok, your call. But I _think_ they want to release 1.0 soon, just waiting for some popular addons to get fixed, so I don't expect any substantial changes in FastBoot itself, at least no breaking ones...
