### ISSUE TITLE
Disable authentication in dev env

### ISSUE THREAD

**Issue by z6aak** [simplabs/ember-simple-auth#1384]
Hi guys,

First and foremost thank you for the nice work here. My question is if it is possible to disable authentication while in dev env? Maybe using feature flags or something like that.

**Comment by marcoow** [comment]
You can certainly do that but I wouldn't recommend it as your app is going to behave significantly different in dev than in the prod mode then. You could do something like that by using a common parent route for all authenticated routes that conditionally mixes in the `AuthenticatedRouteMixin` (or doesn't do so in dev mode).

As I said I'd strongly recommend against that though. You could have something in dev mode that allows you to login with a fake session or so with a simple button click.

**Comment by z6aak** [comment]
Thank you, I will try it out :)
