### ISSUE TITLE
Opening new tab trigger restore, but doesn't restore data.

### ISSUE THREAD

**Issue by olavnyy** [simplabs/ember-simple-auth#1385]
Hello
I have an issue with loosing session.data.currentUser in first tab if I open second tab.
Restore function get triggered

```
restore(data) {
    return new Ember.RSVP.Promise((resolve, reject) => {
        if (!Ember.isEmpty(data.user_email) && !Ember.isEmpty(data.user_token)) {
            console.log(this.get('session.data.currentUser'));
            console.log(data);
            resolve(data);
        } else {
            reject();
        }
    });
}
```

Class {store: Class, _internalModel: InternalModel, currentState: Object, isError: false…}
Object {user_token: "9AzABU8H9ZiAjL8dBGVW", user_email: "testemail@example.com"}

But it seems not resolve the data!

What can be the problem?

Ember             : 2.11.3
Ember Data        : 2.10.0
jQuery            : 3.2.1
Ember Simple Auth : (test on - 1.2.0, 1.2.2, 1.3.0)

**Comment by marcoow** [comment]
It seems like you're storing an Ember Data model in the session data which doesn't work. Instead you should only store the user ID or anything that would allow you to restore the user from later in the session data. See the [guide on implementing a `currentUser` property with ESA](https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md) for more info.
