### ISSUE TITLE
Not redirecting on root index page

### ISSUE THREAD

**Issue by vfonic** [simplabs/ember-simple-auth#1387]
I'm trying to setup ember-simple-auth to redirect to login when user accesses the root index page: `"/"`.

I have had success setting this up for any other page, such as `"/tickets"`, but for some reason it doesn't work for root index.

Here's my `routes/index.js`:
```js
import Ember from 'ember';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin, {
});
```

`router.js`:

```js
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('app', { path: '/' }, function() {
    this.route('tickets', function() {});
    this.route('login');
    this.route('logout');
  });
});

export default Router;

```

`config/environment.js`:

```js
...
  ENV['ember-simple-auth'] = {
    authenticationRoute: 'app.login',
    routeAfterAuthentication: 'app.tickets',
    routeIfAlreadyAuthenticated: 'app.tickets'
  }
...
```

`routes/application.js`:

```js
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin);
```

What am I missing?

**Comment by marcoow** [comment]
Can you add what the error/bad behavior is you're seeing and what exact steps you're taking to reproduce it?

**Comment by vfonic** [comment]
@marcoow 
I just figured out what was the issue. I didn't nest index route under `/app` and so `routes/index.js` wasn't used at all and Ember was just using default route.

I moved `routes/index.js` to `routes/app/index.js` and now everything works!

Thanks!

**Comment by marclundgren** [comment]
I know what's going on here. when using `ember g route login`, this places the login folder at `app/login/route.js`. 

I fixed this error by moving the generated folder to `app/routes/login`

BTW, i am using pods structure
