### ISSUE TITLE
Documentation is unclear regarding `ajaxOptions` vs `headersForRequest`

### ISSUE THREAD

**Issue by afreem66** [simplabs/ember-simple-auth#1398]
I am trying to upgrade my project from ember-cli and ember-data 2.5.x to 2.12.x. I tried updating all packages and experienced auth issues do to `ajaxOptions` not being supported in favor of `headersForRequest`. It seems to me that `headersForRequest` is only available in canary at the moment until this [rfc](https://github.com/pangratz/rfcs/blob/ember-data-improved-ajax/text/0000-ember-data-improved-ajax.md) is merged. Is there any chance we can add a note to the docs until this happens? Right now it says <= 2.6 use `ajaxOptions` and later use `headersForRequest`?

**Comment by marcoow** [comment]
This has been addressed in #1366 already, just not released yet. We'll publish a release this week.
