### ISSUE TITLE
ember-simple-auth 1.4.0 create a strange file when I "ember build -prod"

### ISSUE THREAD

**Issue by johnunclesam** [simplabs/ember-simple-auth#1416]
I switched from `1.3.0` to `1.4.0` and now when I `ember build -prod` I have a new file in:

`dist/ember-fetch/fastboot-fetch-a4c28b6b7b24781cc7616fb44c1def25.js`:

`(function(){define('fetch',['exports'],function(a){var b=FastBoot.require('node-fetch');a['default']=b,a.Headers=b.Headers,a.Request=b.Request,a.Response=b.Response}),define('fetch/ajax',['exports'],function(){throw new Error('You included `fetch/ajax` but it was renamed to `ember-fetch/ajax`')})})();`

**Why this?**

I don't want this file in my prod dist folder.

**I'm not using `fastboot`.**

**Comment by marcoow** [comment]
If you don't use FastBoot that asset would simply not be used by anything. I believe https://github.com/ember-cli/ember-fetch simply always creates that file.
