### ISSUE TITLE
Credential Management API

### ISSUE THREAD

**Issue by dbbk** [simplabs/ember-simple-auth#1418]
Are there any plans to incorporate the new [Credential Management API](https://developers.google.com/web/fundamentals/security/credential-management/) with Ember Simple Auth? I think it'd be great if this could be something that works out of the box for cross-device auto sign in.

I'm not quite sure how it could be integrated for federated login though.

**Comment by marcoow** [comment]
I'm not familiar with the details of the Credential Management API but this seems like it's worth exploring probably.

Would you be willing to come up with a rough concept, outlining how this could be done, what the benefits for users would be, what potential challenges we'd have to overcome etc.?

**Comment by dbbk** [comment]
Sure, might take a while as things are a bit busy but will give it a go 👍

**Comment by marcoow** [comment]
cleaning old issues
