### ISSUE TITLE
[QUESTION] Support for multiple session storage

### ISSUE THREAD

**Issue by mfeckie** [simplabs/ember-simple-auth#1419]
When using simple-auth with an ember-engine, I would like to be able to store more than one `authenticated session`.

As the API exists, the `key` used for localStorage sits very high up the chain which makes this challenging.

Would you have a recommendation for the best way to achieve this or is this just not possible?

I was thinking that there could be a way of defining which key is used on a per authenticator basis?

Suggestions?

**Comment by marcoow** [comment]
> When using simple-auth with an ember-engine, I would like to be able to store more than one authenticated session.

Could you elaborate on the use case a bit?

**Comment by mfeckie** [comment]
The longer version of this is having two different authenticators.  One within the host and one in the engine.

The two can be open independently in different tabs.

Because ESA uses the same localStorage key, you can't independently sign in them.  e.g. with the event listeners, sign out of one, it trashes the session for both.

At the same time, sign in to one, you can't sign in to the other because the session data gets overwritten in the original one.

I suspect this is a fairly niche use case, so not criticising the library 😄

**Comment by marcoow** [comment]
Oh I see, so basically you want to disable session syncing between tabs/windows. While that's not officially supported you could simply override the (private) [`_handleStorageEvent` method](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/local-storage.js#L105) in the `localStorage` session store (or implement your own session store altogether which is pretty straight forward actually). Of course you could use the ephemeral session store as well but then you'd lose session persistence altogether.

**Comment by mfeckie** [comment]
OK, I think I was hoping that it would be possible to have two different `key` names.

I can see how your suggestion would achieve a part solution, but I think we'd still be in the situation that the session stored in localStorage would get overwritten by each window, so they'd still get out of sync on page refresh, for example.

Will explore a bit more.

Thanks for the ideas

**Comment by marcoow** [comment]
Hm, I might have gotten that wrong. You can probably use 2 different session stores in the host app and the engine as well, both using `localStorage` but different keys. See the [API docs](http://ember-simple-auth.com/api/classes/LocalStorageStore.html#property_key).

**Comment by mfeckie** [comment]
👍

**Comment by rwwagner90** [comment]
@marcoow @mfeckie I'm not sure if this is exactly the same use case, but would this work for a single app to have two session stores or would it have to be an app and a separate engine? 

We have a special case in our app where users typically log in with a username and password, but there are some links with a query param token. 

For those special cases, we would love to bypass the stored user and load a new one from the query param, but simple auth seems to get stuck loading the old user.

**Comment by mfeckie** [comment]
@rwwagner90 we've long since removed simple-auth from our stack so no longer a thing for me.

**Comment by rwwagner90** [comment]
@mfeckie do you know if you were using the same `session` service and passing it into the engine as shared or if you were using different ones? I'm a bit confused on how to use different stores for each. We want to make the engine store ephemeral, but are having trouble with the current user caching.

**Comment by mfeckie** [comment]
@rwwagner90 It was an experiment that we abandoned in the end.  Using an engine didn't really solve the problem well and we found it better to host two separate apps.

In the interim period before we separated them, we implemented a totally separate auth system for the engine, so simple-auth was no longer involved.
