### ISSUE TITLE
Authenticated session is redirected to login in fastboot on 1.4.0

### ISSUE THREAD

**Issue by billdami** [simplabs/ember-simple-auth#1420]
This behavior appears to be a regression in 1.4.0, as I am not able to reproduce it if I downgrade to 1.3.0.

On ember-simple-auth 1.4.0, ember 2.14.1, and fastboot 1.0.1, using the required application session-store that extends `ember-simple-auth/session-stores/cookie`, it seems that authenticated sessions are either not found or respected by simple-auth's AuthenticatedRouteMixin in fastboot, as the server will return a 307 redirect to the login route. However, upon client side boot, the UnauthenticatedRouteMixin for this route will take over and transition the user back to the intended destination. As noted above, if I downgrade to 1.3.0, this does not happen at all, and I am able to access authenticated routes in fastboot with no redirects when authenticated.

**Comment by willviles** [comment]
This perhaps could be related to [#1138](https://github.com/simplabs/ember-simple-auth/issues/1138#issuecomment-319684132)?

**Comment by billdami** [comment]
@willviles yeah I'd say its extremely likely that this is the same issue, given that it doesnt happen on 1.3.0

**Comment by Zorig** [comment]
This is also happened to me either. On fastboot i used cookieStore, and in network requests cookie also sent. Still simpleauth redirect to login page.

**Comment by marcoow** [comment]
Closing as #1138 has been closed as well and there were no new reports. Please reopen if this is still an issue.
