### ISSUE TITLE
Links to source code on documentation page seem to be broken

### ISSUE THREAD

**Issue by mariogintili** [simplabs/ember-simple-auth#1423]
Hello peeps,

I tried clicking on the `source` btn next to a method signature's in [this page](https://ember-simple-auth.com/api/classes/SessionService.html#method_authenticate) and the linked pointed [here](https://github.com/simplabs/ember-simple-auth/blob/1.4.0//Users/marcoow/Documents/Code/ember-simple-auth/tmp/broccoli_yuidoc-input_base_path-WPLtIIHm.tmp/0/services/session.js#L146)

**Comment by marcoow** [comment]
Argh, somehow seems to generate links to files on my disk…

**Comment by mariogintili** [comment]
@marcoow well looks like you gotta give the community access to your disk 😄 !

**Comment by marcoow** [comment]
This has been fixed
