### ISSUE TITLE
Page Reload causes Logout

### ISSUE THREAD

**Issue by mlb5000** [simplabs/ember-simple-auth#1424]
Ember: 2.14.2
Simple Auth: 1.4.0

I'm fairly certain I have this configured correctly, but any time the app loads it immediately logs me out. Login causes data to be stored in Local Storage as expected, on startup my `authenticator.restore` method is called, with `data` containing a valid token (verified using a breakpoint) and then successfully resolves, but then as soon as I continue execution the page reloads again and I'm logged out.

Local storage after login:

```
ember_simple_auth-session - {"authenticated":{"authenticator":"authenticator:custom","token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOjEzNTYsInNjaG9vbElkIjoyfQ.YxJRwKJR8SS17_9GUteKNUvF6Q-c3pXdiG7qgqkXqIM"}}
```

```
// app/adapters/application.js
import DS from 'ember-data';
import config from '../config/environment';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:custom',
  host: config.apiUrl,
  namespace: 'api/v1',
});
```

```
// app/controllers/application.js
import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),

  actions: {
    invalidateSession() {
      this.get('session').invalidate();
    }
  }
});
```

```
// app/authenticators/custom.js
import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';

export default Base.extend({
    tokenEndpoint: 'http://localhost:62225/api/v1/account/login',
    restore: function (data) {
        console.log('restore called');
        return new Ember.RSVP.Promise(function (resolve, reject) {
            if (!Ember.isEmpty(data.token)) {
              console.log('Resolved');
              resolve(data);
            } else {
              console.log('Rejected');
              reject();
            }
          });
      },

    authenticate: function (school, username, password) {
        return new Ember.RSVP.Promise((resolve, reject) => {
            Ember.$.ajax({
                url: this.tokenEndpoint,
                type: 'POST',
                data: JSON.stringify({
                    school: school,
                    username: username,
                    password: password,
                  }),
                contentType: 'application/json;charset=utf-8',
                dataType: 'json',
              }).then(function (response) {
                Ember.run(function () {
                    resolve({
                        token: response.token,
                      });
                  });
              }, function (xhr, status, error) {

                var response = xhr.responseText;
                Ember.run(function () {
                    reject(response);
                  });
              });
          });
      },

    invalidate: function () {
        console.log('invalidate...');
        return Ember.RSVP.resolve();
      },
  });
```

```
// app/authorizers/custom.js
import OAuth2Bearer from 'ember-simple-auth/authorizers/oauth2-bearer';

export default OAuth2Bearer.extend();
```

**Comment by mlb5000** [comment]
ok, so one thing down. The `user` lookup in the Application route was returning a 401, which caused the session to be invalidated. My guess is that the `session` Authorizer hasn't been hooked up at the point the `activate` is called on the application route, so it doesn't link up the necessary Authorization header.

Where is the appropriate place to perform some object retrievals on application initialization given that the session needs to be restored first?

**Comment by marcoow** [comment]
See this guide for docs on how to manage a current user: https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md

**Comment by mlb5000** [comment]
@marcoow OK I've set that up, but for some reason my authorizer must never be called. No request ever gets the `Authorization` header attached to it, so everything results in a 401.

**Comment by mlb5000** [comment]
And to be clear, I do have these set in `environment.js`

```
    crossOriginWhitelist: ['http://localhost:62225'],
    apiUrl: 'http://localhost:62225',
```

**Comment by mlb5000** [comment]
@marcoow The issue was the value stored in `authenticator.authenticate` was `token`, where `oauth2-bearer` was expecting that field to be called `access_token`. I wonder what would make the expectation for resolved value in `authenticate` more clear?

**Comment by marcoow** [comment]
To the Oauth 2.0 bearer authorized the session appears to be unauthenticated. I guess we could have a warning in the authorized that fires when the authorized detects some session data to be present but not the value it's looking for. PR adding that would be appreciated.

**Comment by marcoow** [comment]
I'm closing this - this is an error in the app code and authorizers will be deprecated eventually anyway.
