### ISSUE TITLE
Controller init is called even though not authenticated

### ISSUE THREAD

**Issue by Nohcho** [simplabs/ember-simple-auth#1428]
Hi. We are using ESA with torii provider. We are having problems when deep linking to a case. The case controller's init method is called, even though the user is not authenticated and once the user gets authenticated the init is not called again, when the transition continues.
Can you help us find where the issue might be?

Using latest ESA and torii.

**Comment by marcoow** [comment]
Please provide more information, ideally a sample app that illustrates the case - at the least though people will need your routing structure, source for the application route, the route causing the problem (as well as any route in the hierarchy between those 2), your config, which authentiator, authorizer and session store you're using.

**Comment by Nohcho** [comment]
I have another project where I don't use torii. Here there is no problem - controller's init method is called on successfull authentication.

**Comment by Nohcho** [comment]
Our routes:
this.route('cases')
this.route('user')
this.route('case', { path: '/cases/:case_id' })
this.route('login')

The problem is at localhost:4200/cases/2114

Authenticator:
```
import Ember from 'ember';

import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii';

export default ToriiAuthenticator.extend({
  torii: Ember.inject.service()
});
```
Authorizer: 
```
import OAuth2Bearer from 'ember-simple-auth/authorizers/oauth2-bearer';

export default OAuth2Bearer.extend();
```

**Comment by marcoow** [comment]
> at the least though people will need your routing structure, source for the application route, the route causing the problem (as well as any route in the hierarchy between those 2), your config, which authentiator, authorizer and session store you're using.

**Comment by Nohcho** [comment]
Case route has the AuthenticatedRouteMixin
```export default Route.extend(AuthenticatedRouteMixin, {```

**Comment by z6aak** [comment]
You can close this issue. Eventually I found out why I had this behavior. It turns out Ember changed the life cycle of route/controller in 2.14 (https://github.com/emberjs/ember.js/issues/15565)
We moved the code to setupController where it should have been from the start. But we are still having issues with sessionAuthenticated not pausing the transition until some data are loaded. Again the solution will be to move it elsewhere.
