### ISSUE TITLE
Support for customizing the host & port of outgoing authentication requests

### ISSUE THREAD

**Issue by myartsev** [simplabs/ember-simple-auth#1431]
I have my authentication server running on a different port and (potentially) host that the ember server.
So far, I have achieved this by overriding the server endpoint in the authenticator itself.

````
serverTokenEndpoint: 'http://localhost:16006/api/token-auth', 
````

I could make this come from a config instead to handle different values for dev/test/prod.

However, it seems like this should belong elsewhere as I am not really trying to customize the default "/api/token-auth" value, I'm fine with the default, I just want the request to go out to a different host:port.

My first thought was that the [baseURL](http://ember-simple-auth.com/api/classes/Configuration.html#property_baseURL) was the place to configure this, but looking at the code, it is only used to re-direct to a URL once the session is invalidated.

I propose to re-purpose the baseURL to customize the host (_baseHost_?) and add another _basePort_ to customize the port.
The current usage of baseURL can be renamed to _routeAfterInvalidation_ or something like that? Or _baseInvalidatedURL_ if there is a need to support a URL outside of the ember app.

Thoughts?

**Comment by marcoow** [comment]
`baseURL` is the [root URL that your application is running at](https://ember-cli.com/user-guide/#history-api-and-root-url) - that is something completely unrelated to what you>'re doing. It is also a read-only property.

I'd consider splitting up `serverTokenEndpoint` into `serverTokenEndpointHost` and `serverTokenEndpointPath` overkill tbh - I think repeating the path is fine.
