### ISSUE TITLE
Avoiding preflight requests by moving bearer token to the URL query?

### ISSUE THREAD

**Issue by matixmatix** [simplabs/ember-simple-auth#1434]
I've been noticing the preflight requests are considerably slowing my Ember application down. I understand it's happening due to sending custom headers to my API, which qualifies requests sent by the Ember app to not be simple, thus requiring a preflight. I also understand this issue is out of scope of Ember Simple Auth, but I'm curious if there's a plug and play solution around which would move the bearer token to the URL query, which would eliminate the need to for preflight OPTION requests.

Thanks for making Ember Simple Auth. 🙏

**Comment by marcoow** [comment]
The best way to do this for now is to override [`ajaxOptions`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/data-adapter-mixin.js#L77) in your Ember Data adapter. We have plans for making this easier in the future when authorizers will be deprecated.

**Comment by matixmatix** [comment]
@marcoow I'm a bit surprised - do people usually tolerate constant preflight requests when using ESA?
