### ISSUE TITLE
Custom authorizer is ignored by DataAdapterMixin if promise is awaited

### ISSUE THREAD

**Issue by CrushedPixel** [simplabs/ember-simple-auth#1435]
In my `ember-simple-auth` setup, I want to use a custom `authorizer` to fetch an `accessToken`, as it is called before every Ember Data request when using the `DataAdapterMixin`, and can therefore fetch `accessTokens` for API requests on demand.

The `refreshToken` required to obtain an `accessToken` is retrieved by the `authenticator`.

This is my custom authorizer code:
``` javascript
import Ember from 'ember';
import Base from 'ember-simple-auth/authorizers/base';

export default Base.extend({

  apiCalls: Ember.inject.service(),
  session: Ember.inject.service(),

  async authorize(data, block) {
    if (!data.refreshToken) throw new Error('No refreshToken provided');

    const session = this.get('session');

    // if the certificate expires in less than 10 seconds
    // fetch a new one to avoid latency causing an unauthorized request
    const date = new Date();
    date.setSeconds(date.getSeconds() + 10);

    let accessToken = session.get('data.accessToken');
    console.log(accessToken);

    // check if access token is still valid
    if (!accessToken || new Date(accessToken.expires) < date) {
      // renew access token if it's invalid
      accessToken = await this.get('apiCalls').getAccessToken(data.refreshToken);
      session.set('data.accessToken', accessToken);
    }
    
    return block('Authorization', `Bearer ${accessToken.value}`);
  }
});

```

It's fairly straight forward, fetching a new accessToken if none is set (which is the default upon the first ember data request).

**The problem is**, that for some reason, `block` is executed without the accessToken fetched from my API, which should definitely happen before `block` is called by my `authorize` function.
This happens both when using the ES7 `async/await` pattern and using `.then()` and calling the Promise returned by `this.get('apiCalls').getAccessToken` the conventional way.

**One workaround for this is** making `this.get('apiCalls').getAccessToken` a synchronous method by setting `async: false` on the jQuery AJAX call invoked by that function - if I do this, `block` is always executed with the `Authorization` header set correctly. Obviously, this isn't a long-term solution though, so I'm looking for feedback on fixing this issue.

**Comment by CrushedPixel** [comment]
I've looked into the `DataAdapterMixin` source code and the issue seems to be the `ajaxOptions()` function, which does not seem to be fit for promises. I will probably have to find a different way of fetching my `accessTokens` on demand. Any suggestions?

**Comment by villander** [comment]
@CrushedPixel you found a solution for this? I have the same issue #1707
