### ISSUE TITLE
After restoring a session, the authoriser doesn't get setup.

### ISSUE THREAD

**Issue by JonathanBristow** [simplabs/ember-simple-auth#1436]
The code below currently works. If I remove the line with _setup then the outgoing requests don't have the Authorization header.

It doesn't feel like I should be using the _setup function as it isn't in the documentation.

What am I doing wrong?

```
Ember.getOwner(this).lookup('authenticator:custom').restore(token).then(() => {
    Ember.getOwner(this).lookup('session:main')._setup('authenticator:custom', token, true);
});
```

**Comment by marcoow** [comment]
I don't understand what this is about.

But yes, you should not use `_setup` as it is private (not documented and prefixed with an underscore). In fact, `session:main` is private. In order to learn how to implement a custom authenticator, refer to [the docs](http://ember-simple-auth.com/api/classes/BaseAuthenticator.html).

**Comment by JonathanBristow** [comment]
@marcoow Sorry I should have been more specific. 
I have a custom an authenticator & authorizer setup and working. Everything works find when I login using my login form and call `this.get('session').authenticate('authenticator:custom', username, password)` but when I try and restore an existing token in to my authenticator using the code above, all my outgoing requests don't get the Authorization header applied.

Is it almost like the restore function isn't setting up the session to use that authorizer? 

Does that make a bit more sense?

**Comment by marcoow** [comment]
The above code is not supposed to work. The session will automatically call the authenticator's `restore` method when it needs to restore itself - the method should never be called manually. `session:main` and `_setup` are private and should not be used anyway.

If you want to authenticate the session from an existing token you'll have to through `session#authenticate`:

```js
this.get('session').authenticate('authenticator:custom', token).then(…)
```

**Comment by JonathanBristow** [comment]
@marcoow I managed to fix it by returning this.restore(data) from the authorize function in the custom authenticator.

Thank you for your help.
