### ISSUE TITLE
The session service data property is always empty during restore call

### ISSUE THREAD

**Issue by myartsev** [simplabs/ember-simple-auth#1441]
In an authenticator, the session-service data property is always empty in the call to restore, even if there is data from a previous call to _set_.

Consider this:

authenticators/foo.js
```
...

restore(data) {
  if(!this.get('session.data.foo')) {
    console.log('Setting');
    this.set('session.data.foo', Math.floor(Math.random() * 100) + 1);
  }
  console.log(this.get('session.data.foo'));
}

...
```

If you run this on multiple tabs, or refresh the same page, you'll see that we always go into the if loop and attempt to set _session.data.foo_,

**Comment by marcoow** [comment]
You must not access the session service from an authenticator. The restored session data is passed in as the `data` argument into the authenticator's `restore` method. If the authenticator detects the data is sufficient for the session to be authenticated, it returns a promise that resolves with the data (it might potentially modify it) which will lead to the session be restored with that data.
