### ISSUE TITLE
Django - oauth2 auth, client_id on body

### ISSUE THREAD

**Issue by diogoalexsmachado** [simplabs/ember-simple-auth#1447]
Hi,

This issue can be replicated by using oauth2-toolkit on Django (backend).

In the requirements of oauth2 toolkit I got the client_id key inside the Body of the request.

Is there any way to define it to be sent in Body instead of in Headers? 

As a temporary solution I'm hardcoding it into oauth2-password-grant.js :

const data = { 'grant_type': 'password', username: identification, password, client_id: 'myclientid_key' };

**Comment by marcoow** [comment]
Sending the client id in the request body is not currently supported. You can of course define your own authenticator that extends the OAuth 2.0 Password Grant one and overrides the respective method.

A PR adding support for sending the client id in the body would be cool if you'd like to open one!
