### ISSUE TITLE
Hi, Can i hire you?  I want to build a simple Login/Signup system on my Mining pool app which is in go and ember?

### ISSUE THREAD

**Issue by Coinizy1** [simplabs/ember-simple-auth#1454]
I am using Sammy's Open Ethereum Pool.  I want to make a login and Signup page and i want to hide my all pages to only logged in users.
I have a budget of $100 can you do it?
Please Thanks.

**Comment by marcoow** [comment]
Thanks for the inquiry. Of course - being a consultancy - we're available for hire by clients but I'm afraid that budget won't work…

**Comment by Coinizy1** [comment]
Hi, I am sorry if my budget offended anyone.  The problem is I am a student and want to earn so i setup the Sammy's pool and i want this signup system so people must register first to see all pages.  If i can make you happy in $150 then please help me.  I am tierd finding freelancers on upwork and codementor. Please help

**Comment by marcoow** [comment]
No one feels offended - don't worry ;) I think the best thing you can do is invest the 150$ in an online course to get more familiar so you can build your app yourself. @mike-north's Frontend Masters courses are well worth their money, e.g. https://frontendmasters.com/courses/ember-2/

**Comment by Coinizy1** [comment]
I will still have to learn golang too right?

On Oct 11, 2017 2:43 PM, "Marco Otte-Witte" <notifications@github.com>
wrote:

No one feels offended - don't worry ;) I think the best thing you can do is
invest the 150$ in an online course to get more familiar so you can build
your app yourself. @mike-north <https://github.com/mike-north>'s Frontend
Masters courses are well worth their money, e.g.
https://frontendmasters.com/courses/ember-2/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/simplabs/ember-simple-auth/issues/1454#issuecomment-335755596>,
or mute the thread

**Comment by marcoow** [comment]
Not for the Ember app at least

**Comment by Coinizy1** [comment]
How much you need for this job?
Thanks
