### ISSUE TITLE
login not working after migrate "1.1.0-beta.3" to "ember-simple-auth": "^1.4.0",

### ISSUE THREAD

**Issue by cmonzon44** [simplabs/ember-simple-auth#1457]
Hello, after i upgrade addon the login on my app not working, it not redirect to my dashboard, but if I send a wrong password, error message appear correctly, i'm using **devise** authenticator and authorizer

when i debug, addon throw an exception after makeRequest inside authenticate function, exactly on line 149 when it do `response.json().then((json) => {`
after that, the debbuger jump to catch(error).

![recorte](https://user-images.githubusercontent.com/11430219/31557547-9abfa600-b01f-11e7-9ab4-dfcd547859a4.png)

i'm using the same backend when it used 1.1.0-beta.3 version, 
the response from backend contain token, email and user object
`{"token":"ef10a1b5032263b53311a2f9e79839b4","email":"test@test.com","user":{"id":2,"email":"test@test.com","name":"name test","lastname":"lastname test"}}`

any suggestions?
Thanks

**Comment by marcoow** [comment]
What's the error you're getting?

**Comment by Palkiarora11** [comment]
@marcoow 
I am also facing the same issue. 
my Login was working fine before when I used 1.1.0-beta.3 and simply passing username and password from UI.

But when I updated the ember-simple-auth": "^1.4.0", then I am getting an error on my console. and it's not working for me 

and here I am getting "access_token is missing in server response" error in console.

please suggest. How I can use Latest version of ember-simple-auth": "^1.4.0", or any modification needed from server-side response/ or this is an ember issue?

**Comment by marcoow** [comment]
Server responses are validates as of ESA 1.2.0 - see https://github.com/simplabs/ember-simple-auth/pull/957.

This only worked by accident in previous versions. If you cannot fix the server response you need to customize the authenticator so it can work with the non-standard response.
