### ISSUE TITLE
Cannot read property 'hasRoute' of undefined

### ISSUE THREAD

**Issue by jamesdixon** [simplabs/ember-simple-auth#1458]
Hello,

I just upgraded my app from Ember 2.12 to 2.16 and upgraded from ESA 1.3 to 1.4 and am now seeing the following error:

```
rollbar.js:18 TypeError: Cannot read property 'hasRoute' of undefined
    at routeHasBeenDefined (router.js:996)
    at findRouteSubstateName (router.js:958)
    at router.js:868
    at forEachRouteAbove (router.js:837)
    at error (router.js:853)
    at Router$1.triggerEvent (router.js:1036)
    at trigger (router.js:111)
    at Transition.trigger (router.js:645)
    at router.js:456
    at tryCatch (rsvp.js:411)
```

I'm using this [recipe](https://github.com/simplabs/ember-simple-auth/wiki/Recipe:-Defaulting-to-Authentication-Required-Routes) for securing routes by default.

It appears the issue is caused when the following line is called in the `SecureDefaultRouteFactory` referenced in the recipe:

```js
AuthenticatedRouteMixin.apply(route);
```

Any suggestions?

Thank you!

**Comment by marcoow** [comment]
The recipe you're linking to is not officially part of ESA and we don't endorse it (see https://github.com/simplabs/ember-simple-auth/issues/578 for details). That should probably made clearer on the Wiki page - I'll make a note.

**Comment by jamesdixon** [comment]
Bummer! Given this is a common scenario, any chance an official method can be endorsed? Thank you!

**Comment by marcoow** [comment]
That scenario should always be solvable by the much simpler route nesting approach where you simply nest all routes under a common parent that requires authentication. Why does that not work for you?

**Comment by jamesdixon** [comment]
@marcoow thanks. I found what you were referring to and it was very simple to do. To be honest, I feel like the recipe confuses things a bit as it definitely overcomplicates the solution.
