### ISSUE TITLE
Your docs sites links are broken

### ISSUE THREAD

**Issue by robclancy** [simplabs/ember-simple-auth#1460]
http://ember-simple-auth.com/api/classes/OAuth2PasswordGrantAuthenticator.html

Clicking source on a method will give a link which includes your local paths.

For example:
https://github.com/simplabs/ember-simple-auth/blob/1.4.0//Users/marcoow/Documents/Code/ember-simple-auth/tmp/broccoli_yuidoc-input_base_path-WPLtIIHm.tmp/0/authenticators/oauth2-password-grant.js#L298

**Comment by marcoow** [comment]
fixec
