### ISSUE TITLE
Is out there something like this project for react-redux?

### ISSUE THREAD

**Issue by johnunclesam** [simplabs/ember-simple-auth#1464]
Is out there something like this project for react-redux?

**Comment by marcoow** [comment]
perhaps - https://github.com/search?utf8=✓&q=react+redux+auth&type=

**Comment by johnunclesam** [comment]
Thanks @marcoow, I know how to search and in fact there is nothing comparable to this masterpiece. My question was also to see if there's a plan to create one for that world too.

**Comment by marcoow** [comment]
We have no plans on doing that, no.
