### ISSUE TITLE
Authenticate method on session service doesn't return the value from the authenticator's promise

### ISSUE THREAD

**Issue by ddoria921** [simplabs/ember-simple-auth#1465]
I'm running into a problem where I'm extending one of the existing authenticators and I want to access the server response from the Session Service's `authenticate()` method. I noticed that the value that the authenticate's promise resolves with is always `undefined`. 

```js
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service('session'),
  actions: {
    signIn() {
      this.get('session').authenticate().then((data) => {
        console.log(data) // undefined
      });
    }
  }
});
```

Is this behavior intentional? On the other hand, when the promise rejects, it returns the server's response value as the rejection error.

**Comment by marcoow** [comment]
Yes, this is intentional - the data that the authenticator resolves with is available via

```js
this.get('session.data.authenticated')
```

e.g.

```js
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service('session'),
  actions: {
    signIn() {
      this.get('session').authenticate().then((data) => {
        console.log(this.get('session.data.authenticated')) // the session data
      });
    }
  }
});
```

**Comment by ddoria921** [comment]
Gotcha, thanks for the quick response! I'm glad there's a way to access that. Would you see any value in returning the data as part of the promise? 

In my current scenario, the server response looks like this:
```json
{
  "otherData": {},
  "user": {
    "user": "some-user-id",
    "token": "some-token-id"
  }
}
```

where I use `resourceName` to only save the information inside of the `user` key because I don't need ember-simple-auth to save the entire payload on the session service, but I do want to perform some action after auth has completed with the side-loaded data. In this case, having the complete server response come back as the promise resolution value is extremely valuable. 

e.g. 
```js
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service('session'),
  actions: {
    signIn() {
      this.get('session').authenticate().then((data) => {
        console.log(data) // { "otherData": {}, "user": { "user": "some-user-id", "token": "some-token-id" } }
        console.log(this.get('session.data.authenticated')); // { user: "some-user-id", token: "some-token-id" } }
      });
    }
  }
});
```

I am happy to submit a PR that would add this behavior, if you would accept it 🙂

**Comment by marcoow** [comment]
`session.data.authenticated` is set to whatever the promise returned by the authenticator's `authenticate` method resolves with. I guess that's what you'd like the promise returned by the **session**'s `authenticate` method to resolves with as well? But how would you know what data should be used where (e.g. in your above example `data` is the complete response while `session.data.authenticated` is only part of it while both origin in whatever the authenticator resolves with)?

**Comment by ddoria921** [comment]
Oh I see. I misunderstood the way `resourceName` worked (from the Devise Authenticator). For some reason I thought you could resolve the authenticator with a certain value and then the session service would only save the data under the `resourceName` key.
