### ISSUE TITLE
AuthenticatedRouteMixin redirects to localhost when deployed

### ISSUE THREAD

**Issue by Zorig** [simplabs/ember-simple-auth#1466]
Hi, I am using Ember Simple Auth 1.3.0 with Ember-2.15.1+ ember-cli-fastboot-1.1.0. When i try to access my admin which require Login by `AuthenticatedRouteMixin` it redirects me to `localhost/login`. on a localhost it was works fine, but server. Has anyone faced this problem???

**Comment by marcoow** [comment]
This is likely caused by wrong config. Can you share your settings for http://ember-simple-auth.com/api/classes/Configuration.html#property_authenticationRoute or http://ember-simple-auth.com/api/classes/AuthenticatedRouteMixin.html#property_authenticationRoute ?

**Comment by Zorig** [comment]
@marcoow i did not override any of them only did change to `routeAfterAuthentication` here is my `environment.js`

```
    'ember-simple-auth': {
      routeAfterAuthentication: 'https://localhost:4200/admin'
    },
    'ember-cli-head': {
      suppressBrowserRender: true
    }
  };


  if (environment === 'production') {
    ENV['host'] = 'https://api.example.com'
    ENV['ember-simple-auth'] = {
      routeAfterAuthentication: 'https://www.zoog.mn/admin'
    }
  }
```

**Comment by marcoow** [comment]
This cannot be in ESA - there is no mention of `localhost` anywhere in the code even (except for tests of course - see https://github.com/simplabs/ember-simple-auth/search?utf8=✓&q=localhost&type=). Do you maybe use a custom authenticator that might store a redirect URL or so?

**Comment by Zorig** [comment]
Nope, i use oauth2 authorizer and authenticator. Also i used authenticator like this 
```
export default OAuth2PasswordGrant.extend({
  serverTokenEndpoint: `${ENV.host}/auth/token`
});
``` 
application adapter is 

```
export default DS.RESTAdapter.extend(DataAdapterMixin,{
  "host": `${ENV.host}`,
  authorizer: 'authorizer:oauth2'
});
```

on environment i used `{{host}}` 
```
let ENV = {
    modulePrefix: 'my-web',
    podModulePrefix: 'my-web/pods',
    environment,
    rootURL: '/',
    host: 'http://localhost:3000',
    ....
}

  if (environment === 'production') {
    ENV['host'] = 'https://api.example.com'
    ENV['ember-simple-auth'] = {
      routeAfterAuthentication: 'https://example.com/admin'
    }
  }

```
does it affect them?

**Comment by marcoow** [comment]
Are you sure you're deploying a production build?

I can't really see how this could be related to ESA - I'd look for something in your config or deployment setup.
