### ISSUE TITLE
No successful redirect to "routeAfterAuthentication" after login

### ISSUE THREAD

**Issue by Schnodderbalken** [simplabs/ember-simple-auth#1469]
I have the issue that after the login there is an attempt to redirect to the defined `routeAfterAuthentication` ('main-app.inbox') but this takes forever (loading route appears). The login, however, is successful because after a manual reload I find myself on the correct page.

This is the relevant part of the content of my `environment.js`: 

```
 ENV['ember-simple-auth'] = {
    baseURL: '',
    authenticationRoute: 'frontpage.login',
    routeAfterAuthentication: 'main-app.inbox',
    routeIfAlreadyAuthenticated: 'main-app.inbox',
  };
```

I'm taking a dummy authenticator right now:

```
import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';

const { RSVP } = Ember;

export default Base.extend({
  restore(data) {
    return RSVP.resolve(data);
  },

  authenticate(data) {
    return RSVP.resolve(data);
  },

  invalidate() {
    return RSVP.resolve();
  }
});
```
The login component looks like this:
```
import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default Component.extend({
  classNames: ['login'],
  session: service('session'),
  routing: service('-routing'),
  actions: {
    login() {
      var login = this;
      this.get('session').authenticate('authenticator:custom');
    }
  }
});
```

`router.js`:
```
Router.map(function() {
  this.route('frontpage', function() {
    this.route('signup');
    this.route('login');
  });

  this.route('main-app', function() {
    this.route('inbox');
    this.route('usersettings');
  });

  this.route('loading');
  this.route('main-app', { path: '/*main-app' }); // Catch everything else!
});
```

Version of esa:
`"ember-simple-auth": "^1.4.0"`

`ember --version`:
```
ember-cli: 2.16.2
node: 8.7.0
os: darwin x64
```

**Comment by marcoow** [comment]
> to redirect to the defined `routeAfterAuthentication` ('main-app.inbox') but this takes forever (loading route appears). The login, however, is successful

This sounds to me like something is going wrong in the `main-app.inbox` route. Have you tried debugging its `beforeModel`/`model`/`afterModel` methods?

**Comment by Schnodderbalken** [comment]
Thanks for your advice.
I just debugged it and found out: as long as I have a promise in the `model()`-function in the route, the redirect fails. If I, for example, just `return [];` in the `model()`-function, it works.
I noticed that the failing redirect is only a symptom. Even if I manage to make the redirect work when I return an empty array, I can not follow a link to a different route (example: 'main-app.inbox'). If I reload the site (and the session is restored), everything works.

So concluded:
If I manage to login I can not open any route that fetches a model and returns a promise (until I refresh)
If I login and reload the page afterwards (using refresh in the browser) which causes the session to be restored, everything works. 

It seems like some problem with unfulfilled promises or something. I notice, however, that the request that was originally in the `model()`-function goes out and successfully receives data so the promise should resolve.

**Comment by marcoow** [comment]
> …so the promise should resolve.

I'd check whether it **actually** resolves

**Comment by Schnodderbalken** [comment]
Okay I found out that the promise neither resolves nor rejects because the handlers had not been registered. That is because the simple-auth-service inits all services during the session restoration (see https://imgur.com/5G9OOo9). I expected a certain service (the one that connects to the backend via websocket) to be initiated later on.

Conclusion: 
Not directly related to simple-auth. However it has to be kept in mind that during session restoration all services seem to be initiated which *can* influence the original flow. Thanks for your help.
