### ISSUE TITLE
Failure to remove bound event handlers

### ISSUE THREAD

**Issue by williamhector** [simplabs/ember-simple-auth#1471]
In the local storage and session storage stores, during willDestroy, there is an attempt to remove the event listeners, but on a new binding instead of the binding that was used in the call to addEventListener, so the listener remains.
Ember.run.bind creates a new binding each time it is called with the same arguments:
https://ember-twiddle.com/101f54da40947e4b2029c1eaadce5c9a?openFiles=controllers.application.js%2C

**Comment by marcoow** [comment]
Yep, that's a bug
