### ISSUE TITLE
Fix Build

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#1472]
The build is failing since this commit https://travis-ci.org/simplabs/ember-simple-auth/builds/298626798 which is likely unrelated to the failures though 😞

**Comment by marcoow** [comment]
This is very strange actually - tests fail for Ember 2.2.2, 2.1.2 and 1.12.2 but not for e.g. 1.13.13, 2.0.3 and 2.3.2…

**Comment by stevenwu** [comment]
I can confirm all tests pass locally.

**Comment by marcoow** [comment]
This is reproducible when running `yarn install --no-lockfile` locally which is what we do on Travis. I guess this is due to the fixed version of ember-try that is then being used and the failings tests are actually failing legitimately.
