### ISSUE TITLE
custom data on authenticate result is removed (when token is refreshed?)

### ISSUE THREAD

**Issue by BryanCrotaz** [simplabs/ember-simple-auth#1474]
Extended `OAuth2PasswordGrant`, and as per documentation, augmented the response with user_id.

As expected it turns up in `session.data.authenticated`.

A few moments later, check again and it's gone - just the data from the ancestor authenticator remains. I expect it's being stomped on during a token refresh?

**Comment by BryanCrotaz** [comment]
Fixed in PR #1475

**Comment by marcoow** [comment]
> and as per documentation, augmented the response with user_id.

What specifically are you referring to here? How do you augment the response?

**Comment by BryanCrotaz** [comment]
extend OAuth2PasswordGrant
override authenticate
this._super().then(response => {
  response.user_id = got_it_from_somewhere
  return response;
}

**Comment by BryanCrotaz** [comment]
https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md

**Comment by marcoow** [comment]
This works as intended.
