### ISSUE TITLE
Destructuring of `Ember.testing` will not work.

### ISSUE THREAD

**Issue by rwjblue** [simplabs/ember-simple-auth#1476]
Just happened to notice this:

https://github.com/simplabs/ember-simple-auth/blob/c295fee9b0bab6fdf7dcfca0cb706b68415caa95/addon/mixins/application-route-mixin.js#L10

Which is used here:

https://github.com/simplabs/ember-simple-auth/blob/c295fee9b0bab6fdf7dcfca0cb706b68415caa95/addon/mixins/application-route-mixin.js#L141-L149

`Ember.testing` is a getter/setter in Ember, and destructuring like this will only read its value at the time the module is evaluated. In this case, `Ember.testing` will most likely be `false` when the module is evaluated, then change to `true` _during_ the test. This behavior somewhat recently changed in https://github.com/emberjs/ember-test-helpers/pull/227 (which is included in `ember-cli-qunit@4.1.0` / `ember-qunit@3.0.0`).

I believe the fix here would be to remove the destructuring, and use `Ember.testing` directly inline.

**Comment by rwjblue** [comment]
Found another destructuring (via GH search):

https://github.com/simplabs/ember-simple-auth/blob/c295fee9b0bab6fdf7dcfca0cb706b68415caa95/addon/session-stores/cookie.js#L13

Which is used:

https://github.com/simplabs/ember-simple-auth/blob/c295fee9b0bab6fdf7dcfca0cb706b68415caa95/addon/session-stores/cookie.js#L250-L260

and 

https://github.com/simplabs/ember-simple-auth/blob/c295fee9b0bab6fdf7dcfca0cb706b68415caa95/addon/session-stores/cookie.js#L273-L283

**Comment by rwjblue** [comment]
FYI - This is likely to bite folks updating to the latest ember-cli-qunit version (4.1.1)...

**Comment by marcoow** [comment]
Thanks for the notice!

**Comment by Turbo87** [comment]
FWIW this will also be an issue for the next release of `ember-cli-mocha`. We should probably release this soon :)
