### ISSUE TITLE
The browser refreshes itself when I invalidate the session.

### ISSUE THREAD

**Issue by JonathanBristow** [simplabs/ember-simple-auth#1478]
Hi,

I've got some strange behaviour which I have not seen before.
When I call `this.get('session').invalidate();` the following happens:

- The session data is deleted (expected)
- Redirected back to the login page. (expected)
- **The browser then reloads the whole app. (not expected)**

Has anyone else come across this?

**Comment by marcoow** [comment]
The reload is expected actually - see http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionInvalidated.

**Comment by JonathanBristow** [comment]
@marcoow  Thanks for pointing that out...  *facepalm*
