### ISSUE TITLE
Importing Test Helpers readme incorrect.

### ISSUE THREAD

**Issue by Parrryy** [simplabs/ember-simple-auth#1483]
`import { currentSession, authenticateSession, invalidateSession } from '<app-name>/tests/helpers/ember-simple-auth';`

I couldn't get this working in my application with my application. Ember v2.16. 

`import { currentSession, authenticateSession, invalidateSession } from '../helpers/ember-simple-auth';`

The above seems to work though. Not sure if I've done something wrong or if it has been changed recently but the <app-name> import didn't work.

**Comment by marcoow** [comment]
You did replace

`<app-name>` in

```js
import { currentSession, authenticateSession, invalidateSession } from '<app-name>/tests/helpers/ember-simple-auth';
```

with your app's actual name though?

**Comment by Parrryy** [comment]
Yes I did

**Comment by Parrryy** [comment]
Apparently, not properly no...
