### ISSUE TITLE
Fix store creation

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#1490]
Currently the creation of stores is pretty messed up. In particular the adaptive store creates instances without owners/containers which of course leads to a lot of problems - in app code as well as in tests. All of this needs to be cleaned up and the tests need to be simplified.

**Comment by marcoow** [comment]
@stevenwu: I just looked into this again and it's lightly outdated. The [`AdaptiveStore` does create its underlying store with an owner now](https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/adaptive.js#L145) which is a good first step. **But** the tests are actually a huge mess as:

* we are overriding the (private) store creation method: https://github.com/simplabs/ember-simple-auth/blob/master/tests/unit/session-stores/adaptive-test.js#L26
* we are creating instances of the store to be tested manually vs. getting instances from the tests's owner

I think that could be cleaned up greatly. It might make sense to pair on this and have a look at where the problems are exactly, why the private method override was even necessary in the first place etc.

**Comment by stevenwu** [comment]
Ok, I'll bring this up in a future call after I'm done with one of the other issues.

**Comment by marcoow** [comment]
cleaning old issues
