### ISSUE TITLE
not going forward after submit button..I'm getting credentials if i console instead of this.get('session') line..I extended jwt authenticators and mentioned servertokenendpoint..I'm very new in ember,please help me out

### ISSUE THREAD

**Issue by mehrajpasha** [simplabs/ember-simple-auth#1499]
- `routes/login.js

1. 

import Route from '@ember/routing/route';
import Ember from 'ember';
export default Route.extend({
   session: Ember.inject.service('session'),
	model:function(){
		return Ember.Object.create({identification: '', password : ''});
	},

	setupController: function(controller, model){
		controller.set('credentials', model);
	},

	actions: {
		authenticate: function(credentials) {
		this.get('session').authenticate('authenticator:jwt',credentials).catch((reason)=> {
			this.set('errorMessage',reason.error||reason);
		});
		}
	}
});`

**Comment by marcoow** [comment]
Please provide a proper description of the problem - you'll want to write that in complete sentences in the issue description rather than random keywords in the title. Also please make sure markdown formatting isn't broken (see [https://guides.github.com/features/mastering-markdown/](https://guides.github.com/features/mastering-markdown/) for help).

I'm closing this as in its current form it's not actionable. Please feel free to fix and reopen afterwards.

**Comment by mehrajpasha** [comment]
`ENV['ember-simple-auth-jwt']={
      identificationField:'identification',
      passwordField: 'password',
      serverTokenEndpoint:'/tokens'
    `};``

`import JWTAuthenticator from 'ember-simple-auth-jwt/authenticators/jwt';

export default JWTAuthenticator.extend({
serverTokenEndpoint: "/tokens"
});`

I'm trying to do login authentication using jwt..I followed https://github.com/myartsev/ember-simple-auth-jwt for installing ember simple auth jwt..I'm getting credentials from my component..The thing is I still haven't assigned the token..If I press submit I need to get 404 because I haven't written any response for servertokenendpoint url /tokens..but submit isn't going anywhere.please help

**Comment by mehrajpasha** [comment]
sorry I really don't know how to use this platform..sorry again

**Comment by mehrajpasha** [comment]
The problem is with the this.get('session') line..I don't know what dependencies to be added..I'm so much new to ember

**Comment by marcoow** [comment]
This sounds like it might be an issue with ember-simple-auth-jwt which actually is a separate project. You might want to have a look at https://github.com/myartsev/ember-simple-auth-jwt.

**Comment by marcoow** [comment]
I'm not sure what error you're actually seeing.

**Comment by mehrajpasha** [comment]
I'm not seeing any error..the browser almost crashing after I click submit..I don't know why..If I remove that line and console crdentials credentials are getting printed

**Comment by mehrajpasha** [comment]
Hi,I'm getting new debugging error that authenticator is not defined..here's my code..can u help ?

`import Route from '@ember/routing/route';
/*import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';*/
import Ember from 'ember';
export default Route.extend({
  
	model:function(){
		return Ember.Object.create({identification: '', password : ''});
	},

	setupController: function(controller, model){
		controller.set('credentials', model);
	},

	actions: {
		authenticate: function(credentials) {
			 session: Ember.inject.service('session'),
			 authenticator = 'simple-auth-authenticator:jwt';
		this.get('session').authenticate(authenticator,credentials).catch((reason)=> {
			this.set('errorMessage',reason.error||reason);
		});
		}
	}
});
`

**Comment by mehrajpasha** [comment]
Do we definitely need custom authenticators for login service ?
