### ISSUE TITLE
session XHR error 

### ISSUE THREAD

**Issue by mehrajpasha** [simplabs/ember-simple-auth#1501]
I'm trying to authenticate using pouch db..I'm getting following error in pouchdb.min.js

pouchdb.authentication.min.js:1
XHR failed loading: OPTIONS "http://_session/"

My custom authenticator : 

`import Ember from 'ember';
import PouchDB from 'pouchdb';
import Base from 'ember-simple-auth/authenticators/base';
import config from "../config/environment";
export default Base.extend({
init() {
this._super(...arguments);
let remoteDb = new PouchDB('http://localhost:5984', { skipSetup: true });
this.db = remoteDb;
},

authenticate(username, password) {
    return new Ember.RSVP.Promise((resolve, reject) => {
        this.db.login(username, password).then((response) => {
            console.log("hajal");
            Ember.run(function() {
                resolve({
                    name: response.name
                });
            });
        }).catch((e) => {
            Ember.run(function() {
                reject(e);
                console.log(e);
            });
        })
    });
},`

**Comment by marcoow** [comment]
This looks like a misconfiguration of PouchDB to me - seems like you're missing the host name somewhere.
