### ISSUE TITLE
Using test helpers with new ember-qunit test hooks

### ISSUE THREAD

**Issue by jordpo** [simplabs/ember-simple-auth#1512]
I'm trying to use `authenticateSession` for an acceptance test that is using the new `setupApplicationTest` method and I get an error related to the `wait` helper not being defined. 

Is there support for the new test methods and if so, is there an example of usage?

```
import { module, test } from 'qunit';
import { setupApplicationTest } from 'ember-qunit';
import { visit, } from '@ember/test-helpers';
import { authenticateSession,  } from 'app/tests/helpers/ember-simple-auth';

module('Acceptance | auth/login', function(hooks) {
  setupApplicationTest(hooks);

  hooks.beforeEach(function() {
    this.user = server.create('user');
    server.create('company');
  });

  test('visiting / when already authenticated', async function(assert) {
    assert.expect(1);

    authenticateSession(this.owner, {user_id: 1});
    await visit('/');

    assert.equal(currentURL(), '/main');
  });
});
```

**Comment by marcoow** [comment]
`wait` is no longer a global apparently (and even renamed in the latest ember-test-helpers). I'll check for a way to import it that works in all supported Ember versions.

**Comment by 0xadada** [comment]
This is affecting me as well 🎉

**Comment by 0xadada** [comment]
I'm on Ember 3.0.0.beta.1 and `app.testHelpers` is `undefined`. I'm also passing `this.owner` to `authenticateSession()`

![screen shot 2018-01-18 at 7 27 21 am](https://user-images.githubusercontent.com/51207/35098231-5802edec-fc21-11e7-98dd-b284678eb24d.png)

**Comment by marcoow** [comment]
Hm, #1516 which relies on `app.testHelpers` was tested with the latest beta successfully though: https://travis-ci.org/simplabs/ember-simple-auth/jobs/330018617

**Comment by 0xadada** [comment]
i'm using `ember-simple-auth` from master. Where does the `app.testHelpers` property come from? 

package.json:
`"ember-simple-auth": "git://github.com/simplabs/ember-simple-auth.git"`

**Comment by marcoow** [comment]
`app.testHelpers.wait()` is what [Ember itself uses in its test helpers](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers/click.js#L35).

**Comment by 0xadada** [comment]
Hmm, i'm using @cibernox new article https://dockyard.com/blog/2018/01/11/modern-ember-testing to rewrite the tests, and indeed `app.testHelpers` property is not available. I'm passing in `this.owner` as the app your code references:

https://github.com/mirai-audio/mir/blob/16/library-test-helpers/tests/acceptance/media/new-test.js#L16

**Comment by cibernox** [comment]
@0xadada I'll publish an article this week about how to refactor helpers. Ping me in slack if you want early access to it.

**Comment by 0xadada** [comment]
@cibernox sure. In this case, the lack of `app.testHelpers` could it be the `setupApplicationTest(hooks)` isn't setting up the owner properly?

**Comment by marcoow** [comment]
The thing is ESA's test helpers need to work in all Ember versions ranging from 1.12 to 3.0 (until we release ESA 2.0 which drops support for Ember < 2.0).

**Comment by cibernox** [comment]
@marcoow I believe the helper can be refactored to work in both testing approaches. I'll link you to the blog post when I publish it.

**Comment by 0xadada** [comment]
@marcoow i took a first-pass here https://github.com/simplabs/ember-simple-auth/pull/1519  @cibernox moving towards new qunit, hows this look?

**Comment by 0xadada** [comment]
@marcoow @cibernox i updated the README, and refactored the helper a bit. Moved it into the new-style `addon-test-support` directory to it will be exported into the addon namespace rather than the consuming application namespace. 

I import the The `wait()` function from `ember-test-helpers` rather than rely on the global `app.testHelpers` property.

here https://github.com/0xadada/ember-simple-auth/commit/575d5589cd82c6318eced9fea0aa0f3716340e4e
