### ISSUE TITLE
Jwt and localStorage

### ISSUE THREAD

**Issue by mapeveri** [simplabs/ember-simple-auth#1514]
Hi everyone, i have a problem with the authentication jwt and localStorage, the process work well, but i go to the console and modified the localStorage that ember-simple-auth generated, the changes are applied. For example i have one property if the user logged is 'Owner', 'Admin' or a simple 'member', the property is user_type, if i go to the the console and modified the key in the localStorage i see options in the menu that I would not have to see. How I can avoid this?. Thanks!

**Comment by marcoow** [comment]
You cannot avoid this. All data that ESA stores (as well as all code in your Ember app) is visible and editable to users. All authorization has to happen on the server side. The client side can only show or hide parts of the UI that a user is supposed to see or not supposed to see but the server needs to make sure it never exposes any data to the client that the user is not supposed to see.

**Comment by mapeveri** [comment]
Hi @marcoow thanks for your answer.
