### ISSUE TITLE
Error in IE 11 on 1.4.2

### ISSUE THREAD

**Issue by john-griffin** [simplabs/ember-simple-auth#1524]
Seeing the following error in IE 11 on `1.4.2`:

<img width="636" alt="screen shot 2018-01-22 at 09 00 23" src="https://user-images.githubusercontent.com/19490/35225080-50266482-ff55-11e7-8a5a-c0431d91d0d3.png">

That's on Ember `2.17.0` with cli `2.17.1`. It prevents the app from booting.

Downgrading simple auth to `1.4.0` fixes it.

**Comment by marcoow** [comment]
I'm labeling this `good first issue` as the first step is to track this down to a concrete line (probably best by using the dummy app) which doesn't require much familiarity with the codebase.

**Comment by john-griffin** [comment]
Seems to be fixed in 1.5.1
