### ISSUE TITLE
application.__container__ undefined in new test style

### ISSUE THREAD

**Issue by erichonkanen** [simplabs/ember-simple-auth#1530]
Hey just fyi I think https://github.com/simplabs/ember-simple-auth/blob/master/test-support/helpers/ember-simple-auth.js#L13 is deprecated when using the [new qunit test module style](https://dockyard.com/blog/2018/01/11/modern-ember-testing)

I did `hooks.beforeEach(function() { this.owner.application.__container__ (undefined) })`

**Comment by 0xadada** [comment]
@erichonkanen @olenderhub checkout this PR, it solves the problem https://github.com/simplabs/ember-simple-auth/pull/1519

**Comment by erichonkanen** [comment]
@0xadada awesome i'll close this, looks like that will solve it once merged thanks!

**Comment by 0xadada** [comment]
@erichonkanen just included in 1.5.0 https://github.com/simplabs/ember-simple-auth/releases/tag/1.5.0
