### ISSUE TITLE
Dummy app - unless session.isAuthenticated is not working

### ISSUE THREAD

**Issue by belgoros** [simplabs/ember-simple-auth#1533]
I cloned available in the code source [dummy app](https://github.com/simplabs/ember-simple-auth/tree/master/tests/dummy) and discovered a strange or incoherent behaviour:
in `index.hbs` there is the following lines:
```
{{#unless session.isAuthenticated}}
  <div class="alert alert-info">
    You can {{#link-to 'login' classNames='alert-link'}}log in{{/link-to}} with login <code>letme</code> and password <code>in</code>.
  </div>
{{/unless}}
```
what supposes that once authenticated, the above block should not be displayed. But it is not the case, at least when using _Implicit Grant_ authentication.

There is almost the same check in `components/main-navigation.hbs`:
```
{{! display logout button when the session is authenticated, login button otherwise }}
    {{#if session.isAuthenticated}}
      <a {{action 'logout'}} class="btn btn-danger navbar-btn navbar-right">Logout</a>
      {{#if sessionAccount.account}}
        <p class="navbar-text pull-right">Signed in as {{sessionAccount.account.name}}</p>
      {{/if}}
    {{else}}
      <a {{action 'login'}} class="btn btn-success navbar-btn navbar-right">Login</a>
    {{/if}}
```
The problem that the display of **Login/Logout** buttons works but it doe not work for `index.hbs` template, the above div with describing how to to log in is always displayed.

Reproduced on:
```
ember-cli: 2.18.1
node: 8.9.1
os: darwin x64
```

**Comment by geekygrappler** [comment]
Right you are @belgoros. Nice catch, thanks.
