### ISSUE TITLE
Session is being invalidated straight after login, unable to pinpoint why.

### ISSUE THREAD

**Issue by omairvaiyani** [simplabs/ember-simple-auth#1534]
I've just upgraded ember-simple-auth and ember to the current latest versions (1.4.2 and 2.18.1 respectively). As part of these changes, I'm undergoing a cleanout from jQuery, replacing it with ember-fetch.

Now, I have a way to go to get this working (e.g. getting the Authorizer.authorize hook to trigger), but before I can get to that step, I'm blocked by this issue of the session being invalidated as soon as I login.

My login API call returns a 200, normal response. I follow it through as far as I can to look for errors and can't spot any.

I've tried to dig into the call stack, and managed to override ApplicationRouteMixin#sessionInvalidated, but the stack from here is unhelpful as it points me to an event handler, SessionService#_forwardSessionEvents, wherein the information from the triggering function is not present.

Is there a way I can dig into this and figure out what's happening?

**Comment by marcoow** [comment]
Please provide some additional data to help us track this down:

* what authenticator are you using
* what session store are you using
* please enable router transitions logging and post the output here (https://guides.emberjs.com/v2.18.0/configuring-ember/debugging/#toc_routing)

**Comment by omairvaiyani** [comment]
I'm using a custom authenticator that extends the base. It returns a promise with this object structure:
```
{ sessionToken: "", userData: { ... } }
```

I used to use ```AdaptiveStore``` but have switched to ```CookieStore``` for FastBoot compatibility.

Router Transitions are not helpful in my case as we can login from a modal without a route change.

I have however pinpointed the issue. It seems that the event ```sessionDataUpdated``` is triggered with the following content:
```{authenticated:{}}```

The ```authenticated``` object is empty, and therefore the following function has an empty ```authenticatorFactory```:

```
_bindToStoreEvents() {
    this.store.on('sessionDataUpdated', (content) => {
      if (!this._busy) {
        this._busy = true;
        let { authenticator: authenticatorFactory } = (content.authenticated || {});
        if (authenticatorFactory) {
          delete content.authenticated.authenticator;
          const authenticator = this._lookupAuthenticator(authenticatorFactory);
          authenticator.restore(content.authenticated).then((authenticatedContent) => {
            this.set('content', content);
            this._busy = false;
            this._setup(authenticatorFactory, authenticatedContent, true);
          }, (err) => {
            debug(`The authenticator "${authenticatorFactory}" rejected to restore the session - invalidating…`);
            if (err) {
              debug(err);
            }
            this._busy = false;
            this._clearWithContent(content, true);
          });
        } else {
          this._busy = false;
          this._clearWithContent(content, true);
        }
      }
    });
  }
```

My custom authenticator's ```authenticate``` hook is definitely being called, and it is definitely returning a valid promise object with the ```sessionToken``` and ```userData``` objects.

Any advice on how to proceed?

**Comment by marcoow** [comment]
Can you post the code for your custom authenticator please?

**Comment by omairvaiyani** [comment]
Sure, thanks for helping out!

```
// authenticators/parse-username.js
import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';

const {inject:{service}} = Ember.inject;

export default Base.extend({
	/**
	 * @Service
	 */
	store: service(),
	userSession: service(),

	/**
	 * @method
	 *
	 * @param data
	 */
	restore(data = {}) {
		
		if (data.sessionToken) {
			return this.get('userSession')
				.initialiseApp(data.sessionToken)
				.then((user) => {
					return normalizeSessionData(user);
				})
				.catch((error) => {
					console.log("error", error);
					return Ember.RSVP.reject("Session token invalid");
				});
		} else {
			// Doesn't happen - restore only called when session token is set.
			return Ember.RSVP.reject("Session token not found");
		}
	},

	/**
	 * @method
	 *
	 * Here, we can utilise ParseUser
	 * class to make the call; this
	 * is so that we can use this function
	 * for both email and facebook.
	 *
	 * The response is a DS.Record,
	 * which we simplify for normalization.
	 *
	 * @param data
	 */
	authenticate(data = {}) {
		let ParseUser = this.get('store').modelFor('parse-user'),
			promise = new Parse.Promise();

		if (data.newUser) {
			// Sign up a new email based user
			delete data.newUser;
			promise = ParseUser.signup(this.get('store'), data);
		} else {
			// Regular email login
			promise = ParseUser.login(this.get('store'), data);
		}

		return promise
			.then((user) => {

				// user is a DS.Record, we want to send a POJO to match restore's REST call
				let data = user.data;
				data.id = user.get('id');

				return normalizeSessionData(data); // code definitely reaches this point.
			})
			.catch((error) => {
				return Ember.RSVP.reject({message: error});
			});
	},

	/**
	 * @method
	 *
	 * Invalidates session token.
	 *
	 * Called on logout and by simple-auth
	 * when it deems the session is invalid.
	 */
	invalidate() {
		let ParseUser = this.get('store').modelFor('parse-user');		
		return ParseUser.logout(this.get('store'));
	}
});
/**
 * @method
 *
 * Normalize for ember-simple-auth.
 *
 * @param {Object} user
 * @returns {{sessionToken, userData}}
 */
const normalizeSessionData = function (user) {
	let data = {
		sessionToken: user.sessionToken,
		userData: user
	};
	delete data.userData.sessionToken;
	return data;
};

```

**Comment by omairvaiyani** [comment]
@marcoow I've found the problem and solution.

My userData exceeded the maximum cookie length; it wasn't a problem with ```localStorage``` but [apparently the maximum cookie size is 4096 bytes](https://www.thoughtco.com/cookie-size-limit-3466810). This was silently failing. I'll submit a PR to help warn users in the future. Would you say that ```session-stores/cookie.js#persist``` is the ideal location for such a check/warning?

**Comment by marcoow** [comment]
@omairvaiyani: I'd add an assertion on the size of `value` to [write](https://github.com/simplabs/ember-cookies#api) in simplabs/ember-cookies.

**Comment by danilovaz** [comment]
I'm having the same issue but with Safari and only Safari. Others browsers works fine. Only difference is my token is not persisted by client, is just a httpOnly. That's works fine with Firefox and Chrome, but only Safari (either mobile and desktop) appears to no sending cookie `Authorization Bearer TOKEN` on requests I needed.

```
Ember 2.18.0
Ember-Simple Auth 1.4.2
```
I already test configuring store `adaptive`, `cookie` and `localStorage` but does not make any change.

I also try to reproduce this is an Angular project with just ajax and in this project Safari persist Cookie to do requests.
