### ISSUE TITLE
Allow new test helpers be used in rendering tests

### ISSUE THREAD

**Issue by alexander-alvarez** [simplabs/ember-simple-auth#1543]
From what I can tell [`owner.setupRouter()`](https://github.com/simplabs/ember-simple-auth/blob/master/addon-test-support/index.js#L27) is the only thing preventing this from working in rendering tests.

What if we did this instead?
```js
if (owner.setupRouter) {
  owner.setupRouter();
}
```

Thoughts?
@0xadada

**Comment by 0xadada** [comment]
Thats literally what we do in the new test helper
https://github.com/simplabs/ember-simple-auth/blob/master/addon-test-support/index.js#L27

**Comment by alexander-alvarez** [comment]
@0xadada I'm not following. I'm proposing we avoid calling `setupRouter` if the `owner.setupRouter` doesn't exist as it doesn't when you use `setupRenderingTest`

**Comment by 0xadada** [comment]
ah, i follow. @alexander-alvarez that seems reasonable

**Comment by marcoow** [comment]
I'm not sure this is a good idea tbh. The actual session service is interconnected with routes, session stores etc. - all of which you don't want to become active in rendering tests (ake component integration tests). I think the way to go is to mock the session service in these tests.

**Comment by alexander-alvarez** [comment]
@marcoow  I wanted to propose the idea since it wasn't too much work to implement and it seemed to me that the session service didn't have anything explicitly tying it to other pieces.

perfectly fine mocking out the session service as an alternative, but I need help pushing forwards https://github.com/simplabs/ember-simple-auth/pull/1542 as an alternative because without either currently I'm SOL

**Comment by marcoow** [comment]
Yes, we certainly should get #1542 (or something similar) in. That is really mostly internal cleanup though - if you use the new acceptance test helpers introduced in 1.5.0, the router not being set up should not be a problem actually.

I'm going ahead and close this one and #1542 certainly is on our list of things to look at as soon as someone finds the time!

**Comment by alexander-alvarez** [comment]
> That is really mostly internal cleanup though - if you use the new acceptance test helpers introduced in 1.5.0, the router not being set up should not be a problem actually.

@marcoow I can't mock out the session service in integration/rendering tests because when `Application.create(config.APP)` (or it's equivalent) is called in the default `tests/test-helper.js`, the application gets created which in turn automatically does `this.get('session')` and resolves the real session service which is cached going forwards and resolved in the tests (see https://github.com/emberjs/ember-test-helpers/issues/324) instead of the mocked one

**Comment by marcoow** [comment]
Ember Simple Auth looks up the session in an instance initializer: https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js#L3 I couldn't see why that would be running for an integration test though. If that is somehow implicitly run for integration tests (`setupRenderingTest`) somehow, combined with the fact that anything that has been looked up already cannot be mocked anymore, that'd indeed be a problem. I'm not sure that'd be a problem in ESA though. Of course we could wrap the above instance initializer in an `if (!Ember.testing) {` but I'm not sure that'd be great.

Maybe @rwjblue could help us better understand this?

**Comment by marcoow** [comment]
> Ember Simple Auth looks up the session in an instance initializer: https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js#L3

That is not actually correct - it looks up the internal session, not the initializer. I think the lookup that is the problem **might** be the on in the application route's `init` although I couldn't see why that would run here. Anyway, I'm reopening this as there is at least some confusion around the whole topic and very likely something wrong somewhere…

**Comment by alexander-alvarez** [comment]
@marcoow From my understanding of debugging https://github.com/alexander-alvarez/ember-cli-qunit-service-registering/tree/test-case-failing
- [Application.create](https://github.com/ember-cli/ember-new-output/blob/master/tests/test-helper.js#L6) runs the initializers once per test suite
- [`setupContext` ](https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/@ember/test-helpers/setup-context.js#L142) boots an application if it is defined (which it is because of ^) and runs the instance-initializers per test context. 
- [setup-session-restoration](https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js#L4) triggers the initialization of the application route, which triggers the `this.get('session')` and which loads (and caches) the real session service.

**Comment by marcoow** [comment]
Ah right, that makes sense. It also means that #1542 should resolve that though.

**Comment by alexander-alvarez** [comment]
Exactly. Is there anything I can do to help?

**Comment by marcoow** [comment]
We need to debug the failing FastBoot tests - I'm having a look now.

**Comment by marcoow** [comment]
This should be fixed by #1547 actually.
