### ISSUE TITLE
Clear session/invalidate session without triggering login

### ISSUE THREAD

**Issue by sumeetattree** [simplabs/ember-simple-auth#1552]
Could we have a way to invalidate the current session and not redirect to the default `baseURL`?

Use Case:
If the verfication url (#/users/verify#access_token=abcxyz) is accessed, invalidate the current session and verify the new user using the verification link.

Currently using the [OAuth2ImplicitGrantCallbackMixin](http://ember-simple-auth.com/api/classes/OAuth2ImplicitGrantCallbackMixin.html) I am seeing this behavior: Both `session.invalidate()` and `session.store.clear()` are redirecting to the login page without triggering verification link.

I have tried intercepting `activate` method of the `OAuth2ImplicitGrantCallbackMixin` but to no avail

```javascript
// users/verify.js
export default Route.extend(OAuth2ImplicitGrantCallbackMixin, {
  ...
  activate() {
    let session = this.get('session');
    if (session && session.get('isAuthenticated')) {
      this.get('session').invalidate(); // <--- Causes a redirect here
      // this.get('session.store').clear() has the same behavior
      this.set('session.verificationURL', window.location.toString());
    }

    return this._super(...arguments);
  },
  ...
```

I am currently working around this by setting a variable on the session service and using that in the `sessionInvalidated` callback in the `ApplicationRouteMixin`

```javascript
// application.js
export default Route.extend(ApplicationRouteMixin, {
...
  sessionInvalidated() {
    let verificationURL = this.get('session.verificationURL');

    if (verificationURL) {
      this.set('session.verificationURL', null);
      window.location.replace(url); // <-- This alone doesn't work if the url is the same
      window.location.reload(); // <-- if the verification url is already loaded we need to force reload
    } else {
      return this._super(...arguments);
    }
  }
```

This works but is obviously not very clean. If I am doing this wrong could you please point me in the right direction?

**Comment by marcoow** [comment]
Overriding `sessionInvalidated` is the only solution here that I could see. You could call the property you're checking for something like `noRedirectAfterLogin` or so though as you're not using the URL you're currently storing anyway?

> Use Case:
> If the verfication url (#/users/verify#access_token=abcxyz) is accessed, invalidate the current session and verify the new user using the verification link.

I'd be interested about that use case though? Why allow someone to login when they are already logged in?

**Comment by sumeetattree** [comment]
> Overriding `sessionInvalidated` is the only solution here that I could see. You could call the property you're checking for something like `noRedirectAfterLogin` or so though as you're not using the URL you're currently storing anyway?

That's my bad. `url` should actually be `verificationURL`

Our app is made to be used on shared systems. So there are plenty of instances where users will leave their systems without logging out. So the next/new/different user needs to be logged in without having to explicitly logout the previous user.

**Comment by marcoow** [comment]
OK, I see. So, as I said what you're doing is the way to do this with ESA 👍
