### ISSUE TITLE
Documentation's CSS Being Loaded in Production

### ISSUE THREAD

**Issue by jherdman** [simplabs/ember-simple-auth#1556]
I noticed the following errors today on my greenfield project using v1.5.1:

<img width="802" alt="screen shot 2018-03-02 at 1 12 40 pm" src="https://user-images.githubusercontent.com/3300/36914463-6882d0e4-1e1b-11e8-8c94-8eed74d19bc2.png">

I tracked these down to usage in ESA's docs. Perhaps we ought to exclude the docs from the npm package?

**Comment by marcoow** [comment]
I don't get how anything from ESA's `docs` directory would end up in your Ember app. Could you elaborate on what you mean by

> I tracked these down to usage in ESA's docs.

specifically?

**Comment by jherdman** [comment]
Hey, sorry about the tardy reply. I'm having a bit of a set back with my production environment.

@marcoow my app is basically greenfield, there are very little changes. I'm not using font-awesome, for instance, so a grep of my node modules and finding _only_ ESA showing up was the red flag that resulted in this issue being opened.

Interestingly if I `ember build production` and then grep for URLs (e.g. font awesome's) I _don't_ see them. Perhaps I just had a bad deploy?

**Comment by marcoow** [comment]
Yep, there must be something wrong with your deployment. I'd have no idea how any of ESA's `docs` folder's contents would end up in your production app.
