### ISSUE TITLE
attemptedTransition is never persisted

### ISSUE THREAD

**Issue by elmisi** [simplabs/ember-simple-auth#1559]
How to reproduce in dummy project:

1.  click on `Protected Page` link
2.  press `CTRL` + `F5` to force Ember reload
3.  login
4.  app redirect to home `/` instead of `/protected` 

Tested on Opera, Chrome and Firefox.

Probably the reason is that `attemptedTransition` is never persisted, it's easy to verify that inspecting the `LocalStorage` (or the cookies).

Furthermore I've tried to save by myself the `attemptedTransition` into the storage but it fails due to a circular reference.

**Comment by marcoow** [comment]
`attemptedTransition` is a JavaScript object with references to other objects etc. We could never persist that and restore it afterwards.

**Comment by deepflame** [comment]
We are having the same issue in connection with the Auth0 addon.

If it is not possible to persist and restore the 'attemptedTransition' could you please explain to the this line @marcoow https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/authenticated-route-mixin.js#L89 ? Isn't that what this line should do? Or do you save the redirect url somewhere else?

**Comment by marcoow** [comment]
@deepflame: that line sets the `attemptedTransition` of the `session` service but as soon as you restart the app (e.g. by reloading), the `session` object is destroyed of course. We could persist the route the attempted transition originally tried to transition to but there are all kinds of edge cases, e.g. when a model was passed to the transition etc.

**Comment by deepflame** [comment]
@marcoow thanks for the swift reply!

I guess what our problem is is that the app redirects to the auth provider (in our case Auth0) and then restarts the whole app when it comes back with a token in the URL for authentication.

To solve this case I should just use the code in the fastboot case ( https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/authenticated-route-mixin.js#L84-L87 ).

I will try this in connection with the Auth0 addon and fix it there. This is probably better than persisting sessions for all ember-simple-auth users.

**Comment by marcoow** [comment]
Sure, you can always just override `beforeModel`.

**Comment by deepflame** [comment]
Maybe this is helpful for anyone. I was overriding `beforeModel` like so:

```javascript
  beforeModel(transition) {
    if (!this.get('session.isAuthenticated')) {
      const fastboot = getOwner(this).lookup('service:fastboot');
      const cookies = getOwner(this).lookup('service:cookies');

      const protocol = (() => {
        if (this.get('_isFastBoot')) {
          return fastboot.get('request.protocol');
        } else {
          return window.location.protocol.replace(/:/, '');
        }
      })();

      cookies.write('ember_simple_auth-redirectTarget', transition.intent.url, {
        path: '/',
        secure: protocol === 'https'
      });

      this.triggerAuthentication();
    } else {
      return this._super(...arguments);
    }
  },
```

Seems to work fine.
