### ISSUE TITLE
Nesting authenticated routes leads to known Ember routing bug

### ISSUE THREAD

**Issue by kitsuneyo** [simplabs/ember-simple-auth#1560]
I followed the advice in the readme to "nest all of an application's routes that require the session to be authenticated under a common parent route", like this:

```
this.route('authenticated', { path: '' }, function() {
    // my authenticated routes
});
```

Now my application `index.hbs` has stopped showing, and another index I nested has stopped working too.

A bit of searching led me to this open Ember.js routing bug, ["Routes with empty paths steal indexes"](https://github.com/emberjs/ember.js/issues/12700). It says nesting under routes with empty paths breaks indexes, which is what I'm experiencing.

Is there a workaround for this? Or is nesting routes not the best approach - using mixins or importing a base route are alternatives.

**Comment by marcoow** [comment]
I think the only workarounds here are:

* specifying a `path` (obviously)
* not nesting at that level but at some lower level (if possible) and then mixing in the `AuthenticatedRouteMixin` into all the routes

As this is a bug in Ember itself, I don't think there's much that ESA can do 😞

**Comment by kitsuneyo** [comment]
Thanks for the response @marcoow. Agree ESA cannot do anything, the issue is really with the readme. Is suggesting that kind of nesting (with `{ path: '' }`) helpful, or is it worth mentioning that the bug can arise?

**Comment by marcoow** [comment]
It seems relatively unlikely that people run into this I think (this being the first report in 5 years or so) so I'd say we rather not bloat the README more.

**Comment by iand675** [comment]
Just want to chime in and say I encountered this issue as well. If I hadn't encountered this issue I'd have probably been inclined to blame myself :)

**Comment by MatthewPringle** [comment]
Yup causing issues for me all well. Probably not a good idea mentioning nesting.
