### ISSUE TITLE
authenticateSession test helper with Ember 3.0.0

### ISSUE THREAD

**Issue by ryedeer** [simplabs/ember-simple-auth#1561]
Hello!

After upgrading our application to Ember 3.0.0, we have experienced the following issue: the `authenticateSession` helper seems to authenticate the user properly but fails to properly return its value: `return app.testHelpers.wait();` in the helper code breaks with `Cannot read property 'wait' of undefined`.

**Comment by marcoow** [comment]
This should be fixed in ESA 1.5.0: https://github.com/simplabs/ember-simple-auth/releases/tag/1.5.0

**Comment by ryedeer** [comment]
We have 1.5.1 in our package. I've tried it with 1.5.0 as well, with the same result. It fails on this line: https://github.com/simplabs/ember-simple-auth/blob/1.5.1/test-support/helpers/ember-simple-auth.js#L17

**Comment by marcoow** [comment]
This works fine with Ember 3.0.0 in the dummy app. If you also updated ember-qunit to 4.3+ (I think) you'll have to use the new test helpers added with ESA 1.5.0 though. Maybe that's the issue?
