### ISSUE TITLE
"No instance intializer named ember-simple-auth" Acting like it doesn't exist

### ISSUE THREAD

**Issue by DnOberon** [simplabs/ember-simple-auth#1564]
I'm running into an issue I haven't seen before. On app launch I'm getting an 

`Assertion Failed: No instance initializer named 'ember-simple-auth'`

I've got it being called in one of my customer initializers, `app/intializers/*.js`.

```
import Ember from 'ember';

export function initialize(appInstance) {
	var router = appInstance.lookup('router:main');
	var segment = appInstance.lookup('service:segment');

	//-----------------------------------------
	// When pages transition, track view
	//-----------------------------------------
	router.on('didTransition', function() {
		Ember.run.debounce(this, function(){
			const routeName    = this.currentRouteName;
			const routeHandler = appInstance.lookup('route:' + routeName);

			const segmentName       = routeHandler.get('_segmentName');
			const segmentProperties = routeHandler.get('_segmentProperties');

			//-----------------------------------------
			// If we have an override, use it
			//-----------------------------------------
			if( segmentName ){
				segment.trackPageView(segmentName, segmentProperties);
				return;
			}

			//-----------------------------------------
			// If not just track normally
			//-----------------------------------------
			segment.trackPageView();
		}, 150);
	});
}

export default {
	name  : 'segment',
	after : 'ember-simple-auth',
	initialize
};

```
I'm new to Ember, and it probably shows, but after doing some google sleuthing I'm not further than I was hours ago. Any help is appreciated.

ember-cli - 2.7.0
ember-simple-auth - 1.5.1
ember - 2.7.0

**Comment by marcoow** [comment]
That instance initializer was removed in #1547 but actually that's a breaking change as you're running into an error now. I'm adding it back in with a deprecation 👍

**Comment by DnOberon** [comment]
Yeah I literally just found it as I saw your comment lol. You're welcome to add it back in, but I was able to handle the change easily once If found out what it was.

Thanks for your quick response :)

**Comment by marcoow** [comment]
Yes, it's easy to fix but it's still a breaking change that we should fix and show a proper deprecation instead.

**Comment by DnOberon** [comment]
True - now if only this level of responsibility and understanding for breaking changes extending into the Go package community :D
