### ISSUE TITLE
How to automatically time the user out?

### ISSUE THREAD

**Issue by spacerobotTR** [simplabs/ember-simple-auth#1566]
I am using ember simple with rails devise. How do I invalidate the session after X amount of minutes of inactivity?

**Comment by marcoow** [comment]
You can call the [session service's `invalidate` method](http://ember-simple-auth.com/api/classes/SessionService.html#method_invalidate) to invalidate the session. Doing so automatically after a certain time of inactivity is out of scope for ESA.
