### ISSUE TITLE
Cookie Store not accessible via session.store

### ISSUE THREAD

**Issue by CrushedPixel** [simplabs/ember-simple-auth#1568]
I'm trying to implement **remember me** functionality as described in the docs.

Here's my code:
```js
// app/session-stores/application.js
import CookieStore from 'ember-simple-auth/session-stores/cookie';

export default CookieStore.extend();
```

Adding some debug code to this file shows it is indeed being evaluated.

```js
// app/controllers/login.js
// [...]
  session: Ember.inject.service(),
  rememberMe: false,
  _rememberMeObserver: Ember.observer('rememberMe', function() {
    const expirationTime = this.get('rememberMe') ? config.APP.SessionTTL : null;
    this.set('session.store.cookieExpirationTime', expirationTime);
  }),
// [...]
```

The `_rememberMeObserver` is triggered, and it does set the `cookieExpirationTime` property on `session.store`, however the `session.store` object does not resemble the Cookie store at all:
```js
STORE {…}__ember1521548879843: null_backburner: Object { DEBUG: false, currentInstance: null, _timerTimeoutId: null, … }_identityMap: Object { _map: {} }_instanceCache: Object { isDestroying: false, isDestroyed: false, _owner: {…}, … }_modelFactoryCache: Object {  }_pendingFetch: Object { _keys: {…}, _values: {}, size: 0, … }_pendingSave: Array []_pushedInternalModels: Array []_relationshipsPayloads: Object { _store: {…}, _cache: {} }_super: function ROOT()_updatedInternalModels: Array []_updatedRelationships: Array []cookieExpirationTime: 1209600recordArrayManager: Object { store: {…}, isDestroying: false, isDestroyed: false, … }__proto__: Object { constructor: Class(), __ember1521548879843: "ember223", _super: ROOT() } login.js:36
```

Therefore, the actual expiration time of the cookie is not set.

**Comment by marcoow** [comment]
You should not use an observer for that. Instead, make `rememberMe` a writeable computed property as [described in the Ember guides](https://guides.emberjs.com/v3.0.0/object-model/computed-properties/#toc_setting-computed-properties).

It seems you're maybe defining your own `session` service that injects the Ember Data store which overrides the service's original [`store` property](https://ember-simple-auth.com/api/classes/SessionService.html#property_store)? If you inject the Ember Data store, make sure you're not naming that injection _"store"_, e.g.

```js
dataStore: Ember.inject.service('store')
```

**Comment by CrushedPixel** [comment]
Regarding the observer, I'm just following the examples in the documentation here:
https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L38-L48

It seems like you're right, this is my session service code:
```js
export default Session.extend({
  // the ember-data store
  store: Ember.inject.service(),
  // [...]
```

It seems like I'll have to use an alias for this one. Thanks!

**Comment by marcoow** [comment]
Ugh, that documentation should be changed!
