### ISSUE TITLE
Docs on testing session persistence.

### ISSUE THREAD

**Issue by omairvaiyani** [simplabs/ember-simple-auth#1574]
I'm impressed with the new ember testing helpers for Ember 3.0.0. Is there a method to test session restoration properly? I know we can perform a unit test on ```restore``` in our authenticator, however, I want to run an ```applicationTest``` that boots the application as per the real world, and checks for the ```Session Store``` to trigger the correct boot up pathway. Right now, my testing environment loads the application under an empty session, before I can trigger ```session.restore()```.

Thanks!

**Comment by marcoow** [comment]
This is something that's not supported by the acceptance test helpers. Actually they all use a special `test` authenticator to authenticate the session and bypass your custom authenticator completely if you have one as there is no generic way that ESA could authenticate the session with every possible custom authenticator. You'd have to write your own test helper if you want to acceptance test your custom authenticator.
