### ISSUE TITLE
Importing graphql mutation breaks authenticator

### ISSUE THREAD

**Issue by lvegerano** [simplabs/ember-simple-auth#1576]
I'm trying to create a graphql base authentication but the `.graphql` mutation imports break the ability for the authenticator to be found. 

ember-simple-auth - 1.6.0
ember-apollo-client - 1.0.0 beta3

<img width="969" alt="storified" src="https://user-images.githubusercontent.com/2464593/38287235-3618ae0c-378f-11e8-943b-55f09e9b6a25.png">

**Comment by marcoow** [comment]
It looks like it fails to create an instance of the _"jwt"_ authenticator (which is not part of ESA). Maybe that authenticator somehow uses your GraphQL code and there is a problem with that?

**Comment by lvegerano** [comment]
It does I'm writing a custom jwt authenticator not using the plugin that is floating around, and just the mere import of the graphql file it breaks.

**Comment by marcoow** [comment]
That's not an ESA issue then.

**Comment by lvegerano** [comment]
How can you come to that conclusion? This import only break inside an authenticator. I was moving auth code from a controller to this authenticator so its a fact that there is no issue with the mutation. But hey, thanks for your help.

**Comment by marcoow** [comment]
It seems you're using a custom authenticator that Ember fails to create an instance of. I simply can't see how this could be an issue in ESA. Do your unit tests for the authenticator run successfully?
