### ISSUE TITLE
DEPRECATION: ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by rinoldsimon** [simplabs/ember-simple-auth#1577]
After installing ember-simple-auth in an Ember project, following error appears when running the server:

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6.0

### Environment
Ember Version: 2.18.2
Ember CLI Version: 2.18.2
ember-simple-auth Version: 1.6.0
### Steps to Reproduce
In the Ember project install ember-simple-auth:

> ember install ember-simple-auth

After that run an Ember command like:

> ember -v

or:

> ember s

**Comment by geekygrappler** [comment]
Are you sure? I couldn't reproduce with Ember version 2.18.2 and ESA version: 1.6.0

Could you add a repo I could check it out on?

Because the `package.json` says we're using babel 6

**Comment by rinoldsimon** [comment]
this is the exact message i get when i run `ember -v` or `ember s`

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: medzbook-client -> ember-simple-auth -> ember-cookies -> ember-getowner-polyfill -> ember-cli-babel

> DEPRECATION:ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: medzbook-client -> ember-simple-auth -> ember-getowner-polyfill -> ember-cli-babel

**Comment by geekygrappler** [comment]
This is a dependency of a dependency. `ember-getowner-polyfill` is still using `ember-cli-babel` 5.x. We can't fix it.

**Comment by BillyRayPreachersSon** [comment]
Out of interest, what version is the minimum version of Ember this addon is trying to support? If it's Ember 2.4, then the `ember-getowner-polyfill` reference can be removed altogether and at least the second of the two warnings @rinoldsimon posted will go away.

We've managed to get from 29 of these warnings down to 7, and 3 of those are from simplabs addons (`ember-simple-auth` and `ember-cookies`). It would be lovely to have no warnings :)

**Comment by marcoow** [comment]
ESA supports Ember 1.12 (!) and up and thus needs the polyfill.

**Comment by BryanCrotaz** [comment]
then please publish a new major version (thus breaking the promise of backwards compatibility) that doesn't use the polyfill and only supports Ember 2.4 upwards
