### ISSUE TITLE
Add note about torii/redirect.html in the guides

### ISSUE THREAD

**Issue by ryanlabouve** [simplabs/ember-simple-auth#1578]
Great article here!: https://github.com/simplabs/ember-simple-auth/blob/master/guides/auth-torii-with-github.md

Would you mind if I PR'd a note about using`http://localhost:4200/torii/redirect.html` instead of `http://localhost:4200` to avoid a security warning from Torii?

Here's some additional details about the security warnings:

> Torii was originally configured to add an initializer that detects when your Ember app has been redirected-to by an OAuth provider, but this has been shown to be a potential vulnerability, and best practice is to use the static /torii/redirect.html page that the Torii addon makes available as of version 0.9.0.

https://github.com/Vestorly/torii#oauth-redirects

**Comment by marcoow** [comment]
Yep, adding that note would be great!

**Comment by marcoow** [comment]
cleaning old issues
