### ISSUE TITLE
session.isAuthenticated is true, but I still receive error when invalidating.

### ISSUE THREAD

**Issue by chilli11** [simplabs/ember-simple-auth#1584]
When I try to invalidate a session with a logout button, I get this error:"Assertion Failed: Session#invalidate requires the session to be authenticated!" The button only displays if session.isAuthenticated is true, and debugging in the console I find that the session is authenticated. Still, it breaks when session.invalidate is called.

Template: 

    <nav>
        {{#if session.isAuthenticated}}
            {{#link-to 'dashboard.account.profile' name="Manage Profile"}}
                <span><span class="adt-icon">c</span> Current Customer</span>
            {{/link-to}}
            <a href {{action 'invalidate'}}><span>Logout</span></a>
        {{/if}}
    </nav>

Component:

    actions: {
        invalidate() {
            if (this.get('session.isAuthenticated'))
                this.get('session').invalidate();
        }
    }

**Comment by marcoow** [comment]
This should be fixed by 1.6.0 (see https://github.com/simplabs/ember-simple-auth/releases/tag/1.6.0). Please reopen if you're still seeing the error with that version.
