### ISSUE TITLE
AuthenticatedRouteMixin doesn't prevent 'model' hook loading while unauthenticated 

### ISSUE THREAD

**Issue by bortevik** [simplabs/ember-simple-auth#1586]
With `AuthenicatedRouteMixin`  for unauthenticated user in `beforeModel` hook shouldn't we return rejected promise to prevent `model` hook take action?

**Comment by marcoow** [comment]
Calling `transitionTo` from `beforeModel` (as the [`AuthenticatedRouteMixin` does](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/authenticated-route-mixin.js#L114)) implicitly aborts the transition.
