### ISSUE TITLE
Error with fastboot when run via fastboot-server

### ISSUE THREAD

**Issue by fran-worley** [simplabs/ember-simple-auth#1588]
It might be that I'm missing something obvious, but installing ember-simple-auth causes the following error when hitting any route (even ones without a simple auth mixin added) run via the [ember-fastboot-app-server](https://github.com/ember-fastboot/fastboot-app-server).

```
Error: The host header did not match a hostWhitelist entry. Host header: null
17/04/2018 20:09:16    at FastBootRequest.host (/usr/src/app/node_modules/fastboot/src/fastboot-request.js:36:13)
```

If I remove simple-auth, the problem goes away. I've tried with v1.6.0 and 1.5.0 and get the same result. Any ideas?

**Comment by marcoow** [comment]
What's your ember-simple-auth setup? I guess this could be related to the cookie session store trying to recover the session from the cookie but would need more investigation…

**Comment by marcoow** [comment]
Yep, a github repo that shows the error would make debugging this much easier 👍

**Comment by fran-worley** [comment]
@marcoow see https://github.com/fran-worley/ember-fastboot-simple-auth-demo
This fails when deployed (using the deployment addons the package.json) and run via `"fastboot-app-server": "^1.1.2-beta.1"`

I use ember-simple-auth very happily in a couple of other ember-apps this was my first experiment with fastboot and I rather fell at the first hurdle!

**Comment by fran-worley** [comment]
That's the one. It was working fine with our basic repo (without the welcome page addon). I installed ember-simple-auth and it broke with the null host issue above, removed ember-simple-auth and it went back to working fine.

**Comment by marcoow** [comment]
So you're using that exact script and then run `node server.js`? Which request is failing then? Just `GET http://localhost:4200`?

**Comment by marcoow** [comment]
The `hostWhitelist` setting in https://github.com/fran-worley/ember-fastboot-simple-auth-demo only includes `localhost`. Make sure to include the host you're serving the deployed app from as well - see http://www.ember-fastboot.com/docs/user-guide#the-host-whitelist.

**Comment by fran-worley** [comment]
@Marco Otte-Witte<mailto:notifications@github.com> thanks for getting back to me a typo on my part as I extracted this out from our private example it included the correct headers when we had it hosted.

Unless I’m mistaken there is more going on here as the error implies that host header is null (I checked this and it’s not). It also wouldn’t explain how that app ran fine hosted in our AWS stack up until the point I installed ember-simple-auth, then then again one I removed ESA.

I’ve parked fast-boot for now as this project is slightly time critical and the benefits of fast-boot don’t quite outweigh the currently limitations. I’m happy to try to help resolve this if you still want to investigate.

**Comment by marcoow** [comment]
I was trying to reproduce this with https://github.com/fran-worley/ember-fastboot-simple-auth-demo and couldn't locally but if you'd deploy that anywhere it would likely not work as the `hostWhitelist` only includes `localhost`. I don't think we can do much at this point. Could you post a stack trace for the original error you were seeing?

**Comment by marcoow** [comment]
@fran-worley: could you post a stack trace for the error you reported and ideally a `curl` of the request you're making that results in the error. I'm afraid we have no way of tracking this down without additional info 😞

**Comment by marcoow** [comment]
closing due to no response
