### ISSUE TITLE
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'ember_simple_auth-session' exceeded the quota.

### ISSUE THREAD

**Issue by OpakAlex** [simplabs/ember-simple-auth#1592]
What this means?

**Comment by marcoow** [comment]
That means that the user's `localStorage` quota is exceeded so there's too much data in `localStorage` for the domain of your app.

**Comment by OpakAlex** [comment]
thanks

**Comment by BernhardSmuts** [comment]
If I could reach through the screen and give you a high-five, a massive hug and a ton of celebratory whiskey, I would!!!

I have been baffled by this for most of the day, and boom! Solved! [digital high five] to you my good sir!

**Comment by SatishChandraPalakoti** [comment]
What's the fix ? how did you do it ?
