### ISSUE TITLE
"_renewExpiration" Promise repeated every second (cookie.js)

### ISSUE THREAD

**Issue by davelindquist-egistix** [simplabs/ember-simple-auth#1595]
We have a longstanding weirdness with ember-simple-auth (used in conjuction with auth0), where there is a promise that ticks over every second (forever).

(We are using ember-simple-auth 1.4.0)

I'm struggling to figure out where it comes from (and whether it is intentional, since this seems rather excessive).

Anyway, it seems that the cycle consists of:
* ```_renewExpiration```
* calls ```_renew```
* returns a ```.then``` promise that calls ```_calculateExpirationTime```
* ```_calculateExpirationTime``` returns ```null```

There also seems to be a cycle (I can't quite determine if it is part of the same cycle or it's own separate cycle) of:
* ```restore```
* calling ```RSVP.resolve(JSON.parse(data))```
* where ```data``` here contains a string of the authentication data -- ```{"authenticated":{"authenticator":"authenticator:auth0-lock","accessToken":"...```

Can anyone point me in the right direction for figuring out what the heck this is doing?  (And why it seems to be re-handling my authentication data once per second?)

Is there something weird if you don't have some 'expiration' setting specified for ember-simple-auth?

Thanks!

**Comment by davelindquist-egistix** [comment]
OK, no sooner do I post this than I finally track down the location that seems to be doing things:

```js
    _syncData() {
      return this.restore().then(data => {
        if (!(0, _objectsAreEqual.default)(data, this._lastData)) {
          this._lastData = data;
          this.trigger('sessionDataUpdated', data);
        }
        if (!testing) {
          cancel(this._syncDataTimeout);
          this._syncDataTimeout = later(this, this._syncData, 500);
        }
      });
    },
```

The ```later(this, this._syncData, 500)``` seems to indicate that it will loop infinitely, executing every half-second, and each time around it seems to re-parse the data out of the cookie, check if it has changed, and if so triggers the ```sessionDataUpdated``` event.

I guess this is then intentional, but it seems awfully 'heavy' somehow.  It's also a pain in the ass when using the Chrome Ember Debugger addon, since the promises are polluted with the ember-simple-auth promise.

Is there really no better way to do this?

**Comment by davelindquist-egistix** [comment]
Yeah, that's unfortunate...  It'd be nice if there was something to 'listen' to.

Is there a reason it has to use a whole slew of immediately-resolved promises to do so?  (Seems like the timer code could be a lot shorter?)

**Comment by marcoow** [comment]
> Is there a reason it has to use a whole slew of immediately-resolved promises to do so? (Seems like the timer code could be a lot shorter?)

I don't think that's necessary actually. If you'd like to submit a PR cleaning that up that'd be great 👍

**Comment by marcoow** [comment]
cleaning old issues
