### ISSUE TITLE
baseURL is deprecated

### ISSUE THREAD

**Issue by erichonkanen** [simplabs/ember-simple-auth#1596]
https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/application-route-mixin.js#L142-L144

https://www.emberjs.com/blog/2016/04/28/baseURL.html

`baseURL` should be replaced with `rootURL`

**Comment by marcoow** [comment]
ESA's `baseURL` is not Ember CLI's `baseURL` - in fact `Configuration.baseURL` gets set to Ember CLI's `rootURL` (and only falls back to `baseURL` for backwards compatibility): https://github.com/simplabs/ember-simple-auth/blob/5d58e01868c90e8bb179e20537765130633b94e0/app/initializers/ember-simple-auth.js#L12

**Comment by marcoow** [comment]
I guess it makes sense to rename `Configuration.baseURL` to `Configuration.rootURL` though to avoid confusion.

**Comment by erichonkanen** [comment]
ahh gotcha, yeah I just assumed that was referring to ember's value but makes sense... good to know thanks
