### ISSUE TITLE
Losing data objects on refresh

### ISSUE THREAD

**Issue by jrock2004** [simplabs/ember-simple-auth#1599]
Ember Version: 2.18.2
Simple Auth Version: 1.6.0

So I have a service that has a function that sets a cart id into the session like `this.get('session').set('data.currentCartId', onlineCart.get('id'));`. If I change click a link to another route and we init the service, we check for that data object, but its not there. Could this be a bug? Any more data you need?

This is how I am trying to read the data from the session

```
this.get('session').get('data.currentCartId')
```

If I console log `this.get('session')` I can see it under content but I cannot retrieve it.

**Comment by marcoow** [comment]
Hm, this might be a duplicate of #805 but you're saying you're only going to a different route and don't even refresh in between?

**Comment by jrock2004** [comment]
I figured it out. My code was in the init of a service and that was firing before the code setting up the session happens
