### ISSUE TITLE
Postlogout URI not working properly when opening session in two or more tabs.

### ISSUE THREAD

**Issue by viganella** [simplabs/ember-simple-auth#1607]
My basic flow is that when user clicks logout, I grab the current URL they are, and set the poslogoutURI to this particular URL. 
This works fine in one tab.
But opening my project in two or more tabs and clicking logout will just return me to the application route (which in my case is blank).

Here is my code for the logout functionality:

**export default Route.extend(AuthenticatedRouteMixin, {
    session: service(),
    beforeModel() {
        if(this.get('session.isAuthenticated')){
            this.get('session').postLogoutURI(window.location.href);
            this.get('session').invalidate(true); 
        }else{
            this.transitionTo('login');
        }
    }**

And postlogoutURI is basically a property for the config.

**Comment by stevenwu** [comment]
The default behaviour when logging out from one tab is to redirect to the base url in all tabs.

Can you recreate this issue in an example app?

**Comment by viganella** [comment]
@stevenwu Thank you for your reply. Actually as you can see from the code my postLogoutURI is the location.href when the user presses log-out and specifically that is /organizations/ID/projects/ID route.
In reality what happens is that after pressing log out if the same page is open in more than 1 tab it redirects me to the root of the application which is a behavior I dont want.
However it works if the user has 1 tab and clicks log-out.

**Comment by marcoow** [comment]
cleaning old issues
