### ISSUE TITLE
ember-simple-auth: only validate the password without logging in

### ISSUE THREAD

**Issue by vanness145** [simplabs/ember-simple-auth#1611]
https://stackoverflow.com/questions/43908737/ember-simple-auth-only-validate-the-password-without-logging-in?rq=1

I came across an issue similar to the above however I don't see any solution at this thread.  

Anyone got any idea on hw to do this?

**Comment by marcoow** [comment]
This is out of scope for ESA. The purpose of this library is to maintain a user session with ways of authenticating and invalidating it. Validating the user's password to authorize particular actions is something that makes sense but can be done in various ways and adding that to the core library would lead to a massive increase in overall complexity for little value for most people.
