### ISSUE TITLE
Question - can I manually create a session - for a single sign on application

### ISSUE THREAD

**Issue by mattstone** [simplabs/ember-simple-auth#1613]
Hello,

I'm trying to create a single sign service across a couple of my sites & apps. The users and sites share the same authentication database

I've been banging my head looking around the documentation but cant't work out a solution.

I can manually update the session like the below, but it does work

```js
this.set('session.isAuthenticated',   true);
this.set('session.data.authenticated', unencrypt(body));
```

I've tried using a custom Authenticator (which I gather are going to depreciated) as marcoow suggested here: https://stackoverflow.com/questions/37942876/can-i-manually-set-session-state-to-authenticated-in-embe-simple-auth

```js
this.get('session').authenticate('authenticator:my-authenticator', sessionData)

// app/authenticators/my-authenticator.js
…
authenticate(sessionData) {
  return Ember.RSVP.resolve(sessionData);
}
```

But when I tried to access the my-authenticator I receive the error:

Error: Assertion Failed: No authorizer for factory authorizer:my-authenticator could be found!

It is possible to manually create a session - or is there another way to achieve this?

Thanks for your time.

**Comment by marcoow** [comment]
I think you're mixing up [authenticators](https://github.com/simplabs/ember-simple-auth#authenticators) and [authorizers](https://github.com/simplabs/ember-simple-auth#authorizers). Only authorizers will be deprecated but in your case where you're only looking to **authenticate** the session, you don't need an authorizer anyway.

It's totally fine to manually authenticate the session without any user interaction and your approach above seems to be correct in general:

```js
this.get('session').authenticate('authenticator:my-authenticator', sessionData)

// app/authenticators/my-authenticator.js
…
authenticate(sessionData) {
  return Ember.RSVP.resolve(sessionData);
}
```

**Comment by marcoow** [comment]
I recommend starting a discussion on stackoverflow.com or the Ember Community Slack if you have more questions around this.
