### ISSUE TITLE
Ember Simple Auth: 'authorize' is deprecated. [deprecation id: ember-simple-auth.session.authorize]

### ISSUE THREAD

**Issue by afuno** [simplabs/ember-simple-auth#1622]
> DEPRECATION: Ember Simple Auth: 'authorize' is deprecated. [deprecation id: ember-simple-auth.session.authorize] See https://github.com/simplabs/ember-simple-auth#authorizers for more details.

Can you please explain to me what I need to do for Apollo (GraphQL)? 

The page does not load (GraphQL query, but query it's working), and in the logs of the browser hangs the message that I provided above.

I passed the authorization. Got a token. Then there was this problem.

The problem is in this code. If the contents of the method are commented out, the contents of the page are displayed. But this is not a solution to the problem of authorization. A token exists in the `data.token`.

```js
restore(data) {
  return new RSVP.Promise((resolve, reject) => {
    if (!isEmpty(data.token)) {
      resolve(data)
    } else {
      reject()
    }
  })
},
```

I borrowed this code from here, since you do not have any documentation: https://github.com/simplabs/ember-simple-auth/issues/1309

**Comment by afuno** [comment]
I added this code to the `app/authorizers/custom.js` file:

```js
authorize(sessionData, block) {
  block('ST-User-Token', sessionData.token);
}
```

And the page began to load. In requests, a header with a token is sent. It seems all good. 
But the message in the logs of the browser, which I gave in the first message, is preserved.

**Comment by marcoow** [comment]
Authorizers should not be used at all. So wherever your `custom` authorizer is being used, e.g. in something like

```js
this.get('session').authorize('authorizer:custom', (headerName, headerValue) => {
  // apply header
});
```

you should do something like this instead:

```js
let token = this.get('session.data.authenticated.token');
// apply header with token
```

**Comment by afuno** [comment]
@marcoow Yes you are right. I'm using that code. But I use it in the method that is called by the Login button.

**app/components/general/main-navigation/user-login.js**:

```js
import Component from '@ember/component'

export default Component.extend({
  session: Ember.inject.service('session'),

  actions: {
    authenticate () {
      let { identification, password } = this.getProperties('identification', 'password')

      this.get('session').authenticate('authenticator:custom', {
        email: identification,
        password: password
      })
      .catch((reason) => {
        this.set('errorMessage', reason.error || reason)
      })
    }
  }
})
```

Then the data is transferred to this file: app/authenticators/custom.js:

```js
  authenticate(data) {
    const variables = {
      email: data.email,
      password: data.password
    }

    return this.get('apollo').mutate({ mutation: signInMutation, variables }).then((data) => {
      return {
        token: data.signIn.token,
        email: data.signIn.email,
        nickname: data.signIn.nickname
      }
    })
  },
```

As for file app/authorizers/custom.js, then:

```js
import Base from 'ember-simple-auth/authorizers/base'

export default Base.extend({
  session: Ember.inject.service('session'),

  authorize(sessionData, block) {
    block('X-ST-User-Token', sessionData.token)
    block('X-ST-User-Email', sessionData.email)
  }
})
```

I collected all my code from your repository. Of the issues, too.

If I do not need to use this code:

```js
this.get('session').authorize('authorizer:custom', (headerName, headerValue) => {
  // apply header
});
```

Then how do I transfer data to app/authenticators/custom.js to perform a mutation?

**Comment by afuno** [comment]
@marcoow and I don't understand why you closed that question :)
You have clear examples in the documentation, which I used. And for some reason I still get these messages.

**Comment by afuno** [comment]
@marcoow Your answer didn't help me at all. And you don't want to try to help me.

Open this issue, please.
