### ISSUE TITLE
[Cleanup] Refactor interesting functions away from mixins

### ISSUE THREAD

**Issue by mike-north** [simplabs/ember-simple-auth#1625]
Currently there are places where functions live on mixins for little or no reason (there may have been very good reasons before, but no longer). 

While leaving the public API surface intact, we should refactor these out so that they **may** be consumed directly

##### Before:

```js
export default Mixin.extend({
  add(x) {
    return this.get('total') + x;
  }
});
```

##### After:

```js
export function add(obj, x) {
  return obj.get('total') + x;
}

export default Mixin.extend({
  add(x) {
    return add(this, x);
  }
});
```

**Comment by marcoow** [comment]
mixins are deprecated now – see #2198
