### ISSUE TITLE
[Cleanup] Remove stubs at the end of each test scenario

### ISSUE THREAD

**Issue by mike-north** [simplabs/ember-simple-auth#1626]
Currently sinon is used without un-stubbing and un-mocking. This runs the risk of introducing non-determinism into the test suite (i.e., "Test 32 passes, but only when Test 14 runs before it").

Sinon's [sandbox feature](http://sinonjs.org/releases/v6.1.3/sandbox) is an easy way to ensure that things are restored at the end of each module -- ensuring that all tests start out with a clean environment.

The easy mode way to do this is

##### Before
```js
import { describe, it } from 'mocha';
import sinon from 'sinon';

describe('My test module', () => {
   it('works properly', () => {
        sinon.stub(....);
   });
});

```

##### After
```js
import { describe, beforeEach, afterEach, it } from 'mocha';
import sinonjs from 'sinon'; // 1. Rename import to sinonjs

describe('My test module', () => {
   let sinon; // 2. Define a sandbox called sinon
   beforeEach(() => { sinon = sinonjs.sandbox.create(); }); // 3. Set it up before each test
   afterEach(() => { sinon.restore(); });  // 4. Tear it down at the end of each test
   it('works properly', () => {
        sinon.stub(....); // << this continues to work with no change required
   });
});

```

**Comment by marcoow** [comment]
I *think* we currently restore each stubbed method individually but the sandbox approach is much better of course. Maybe that didn't exist back in the day…
