### ISSUE TITLE
Clarity on How to Structure a Server Response for Seession Authentication

### ISSUE THREAD

**Issue by hiimtaylorjones** [simplabs/ember-simple-auth#1630]
Hey y'all,

I'm still wrestling a bit with how to exactly structure my API responses to better sync up with Ember Simple Auth.

I'm running the following right now:

```javascript
let { email, password } = this.getProperties('email', 'password');
this.get('session').authenticate('authenticator:oauth2', email, password).catch((reason) => { 
  this.set('errorMessage', reason.error || reason);
});
```

For an invalid response, my server is returning:

```
{
  status_code: "401",
  error: {
    "message": "Invalid email or password"
  },
  result: []
}
```

For a valid response:

```
{ 
  access_token: "64ce61a4dd8a5b786283a355206a65f2840da480d7c60f10f07a8aa51872a4f5"
  token_type: "bearer"
  expires_in: "432000"
  created_at: "1531683221"
  status_code: 200
  message: "Signed in successfully."
  result: {
    id: 1,
    email: "sample_email@site.com"
  }
}
```

So, when I get that invalid response from the server, I'm getting a js error of `TypeError: resason is undefined`. I'm wondering if this is happening because of an error of ESA looking for a message or response that its not getting from the server and thus not kicking the proper response back to the catch section. Is there any insight on what's happening and what the server response should be? 

After all of this, I'd be happy to contribute some documentation on the matter!

**Comment by marcoow** [comment]
The success response should look like this:

```json
{
  "access_token": "64ce61a4dd8a5b786283a355206a65f2840da480d7c60f10f07a8aa51872a4f5",
  "token_type": "bearer",
  "expires_in": "432000"
}
```

The error response should look like this:

```json
{
  "error": "invalid_grant"
}
```

Status codes should generally not be sent in the response body but the respective header. You can read up more on the expected [success](https://tools.ietf.org/html/rfc6749#section-5.1) and [error](https://tools.ietf.org/html/rfc6749#section-5.2) in the spec.

I agree we should improve the documentation though and add detailed info on how the responses should look like.
