### ISSUE TITLE
The .read and .rebuild APIs will stop working in the next Broccoli version

### ISSUE THREAD

**Issue by MatthewPringle** [simplabs/ember-simple-auth#1635]
These notices are being logged on build after adding the plugin

[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: Filter

**Comment by dcyriller** [comment]
Would [this PR](https://github.com/simplabs/ember-simple-auth/pull/1636) solve the issue ?

**Comment by marcoow** [comment]
#1636 should solve that actually
