### ISSUE TITLE
Arrow functions can't be bound

### ISSUE THREAD

**Issue by pichfl** [simplabs/ember-simple-auth#1638]
https://github.com/simplabs/ember-simple-auth/blob/620982458e8bc5debcd188e8c3b59bea7ebc1421/addon/mixins/application-route-mixin.js#L82-L90

According to spec, this should not work, nor should passing arguments that way. See http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions-runtime-semantics-evaluation

I think it _might_ work because the arrow functions are still transpiled by Babel, which is why I ran into this bit because we are in the lucky position to having a project where we don't have to support older browsers.

Possible correction:
```js
A([
    ['authenticationSucceeded', 'sessionAuthenticated'],
    ['invalidationSucceeded', 'sessionInvalidated'],
]).forEach(([event, method]) => {
    this.get('session').on(event, (...args) => {
        this[method](...args);
    });
});
```

**Comment by marcoow** [comment]
Yep, the suggested correction looks good to me - we shouldn't need to add this to the run loop anyway as this is an Ember event.

**Comment by pichfl** [comment]
Sure, will prepare a PR later on. I'll also check the source for other occurrences.
