### ISSUE TITLE
Redirect to external URL to complete logout process

### ISSUE THREAD

**Issue by lougreenwood** [simplabs/ember-simple-auth#1639]
My expected logout flow looks like this:

* User clicks logout link in Ember app
* `authenticator.invalidate()` is called and session is invalidated
* Ember app redirects user to external link (logout page on OAuth2 server)
* User clicks logout button 
* Session is invalidated on OAuth2 server
* OAuth2 server redirects user back to base URL of Ember app

However, it seems that this flow isn't possible using `invalidate()`. I feel this should be as simple as the following code, but for whatever reason, the redirect never occurs:

```
    // app/authenticators/my-authenticator.js
    invalidate() {
        return this._super(...arguments).then(() => {
            window.location.replace(ENV.auth.signOutUrl)
        })
    },
```

If I do this:

```
    invalidate() {
        window.location.replace(ENV.auth.signOutUrl)
    },
```

the redirect happens, but the session isn't properly invalidated in Ember app (and I get errors because I'm not returning a promise).

I've looked into using `invalidationSucceeded` - but I don't want this to propagate across tabs - otherwise it seems that logging out in one tab will lead to all of the users tabs being redirected to the external logout page - this is bad UX...

I'm at a loss - any ideas on how this should be handled?

**Comment by marcoow** [comment]
No, what you're trying to do isn't possible - the session service's `invalidate` method will invalidate the session so that when the returned promise resolves, the session is invalidated already. If you leave the app by redirecting the user to another page, that won't work. You could have a link to another page in your app and from there redirect back to the Ember app with e.g. a query param and then in the app if that param is present, call `invalidate`, e.g.:

```js
if (this.get('doLogout')) {
  this.get('session').invalidate();
}
```

**Comment by lougreenwood** [comment]
I suppose I could manually drop the access token and clear localStorage/cookies in a custom invalidate call-back (one which doesn't call `this._super`) and then redirect.

But I expect that this will leave `session.isAuthenticated` as true - can this property be reset using public methods? It seems to be readonly in the docs: http://ember-simple-auth.com/api/classes/SessionService.html#property_isAuthenticated

**Comment by marcoow** [comment]
That's not something that I'd suggest you do. You could achieve what you want doing this:

* link from your page to the logout page on the OAuth server
* after logging the user out, redirect back to the Ember app (e.g. `ember.app/after-logout`)
* make sure that route does not load any data with the (then invalid) token it still has as that would result in an erro!
* in the `activate` of the `after-logout` route, call `this.get('session').invalidate()`
