### ISSUE TITLE
Import Authenticator into other project file?

### ISSUE THREAD

**Issue by lougreenwood** [simplabs/ember-simple-auth#1641]
Hello,

I'm attempting to import the Authenticator into another file (a mixin).

My reason for this is to use a method defined in the Authenticator within the mixin (the method is to generate query params for an OAuth2 authorise callback).

It seems that using `import Authenticator from 'my-app/authenticators/my-authenticator'` results in an error when I attempt to use the method:

Call:
`await Authenticator.generateAuthRequestQueryParams()`

Error:
`Error while processing route: _my-authenticator.default.generateAuthRequestQueryParams is not a function`

Is there something special or specific to Authenticator objects/files which means they can't be imported and used?

**Comment by marcoow** [comment]
I'd assume that function is defined as an instance method on the prototype. If this is a reusable piece of code I'd consider moving it to `app/utils/generate-auth-request-query-params.js` or so with:

```js
export default function generateAuthRequestQueryParams() {
  …
}
```

**Comment by lougreenwood** [comment]
TBH, organisationally, if possible I'd prefer these to remain in the custom authenticator file - that keeps all auth-related code together and reduces the learning curve of the code-base for future developers (and myself when I forget about the util! :P )

Can you think of any reason that the custom authenticator/methods on it can't be imported?

**Comment by marcoow** [comment]
You can also keep the method in the authenticator file as a named export:

```js
export function generateAuthRequestQueryParams() {
  …
}

export default BaseAuthenticator.extend({
  …
})
```

You **cannot** import the method as you're trying above though - that is simply not how JS/Ember's object model work…
