### ISSUE TITLE
How can I override 'authenticated-route-mixin' beforeModel method?

### ISSUE THREAD

**Issue by ollar** [simplabs/ember-simple-auth#1644]
I want to add some additional checks to this method and need to completely override it. But calling this._super(...arguments) is calling 'authenticated-route-mixin.beforeModel' method which is not preferable for me.

Here is the code:

```js
export default Mixin.create(AuthenticatedRouteMixin, {
  beforeModel(transition) {
    if (
      !this.get('session.isAuthenticated') ||
      !this.get('session.data.authenticated.group')
    ) {
      ....... same code there.....

      this.triggerAuthentication();
    } else {
      return this._super(...arguments);
    }
  },
});
```

This seems to be a question about working with ember mixins but I haven't find any solution in docs and sources and maybe you have already solved this somehow? Thanks.

**Comment by marcoow** [comment]
When you want to completely override a method from a mixin in Ember, you can **never** call `this._super(...arguments)` as that would invoke the original method - there's really no difference between base classes and mixins in that regard. In your case if the conditional is `false`, the original `beforeModel` from the `AuthenticatedRouteMixin` will be used.

Or maybe I'm mis-understanding what you're asking?

**Comment by ollar** [comment]
@marcoow thanks a lot for a quick answer! Yes, you are right I am trying to override this method and already got the behaviour you described. It seems that mixins are not overridable and I need to write my own implementation of them.
Anyway, thanks for helping!
