### ISSUE TITLE
routeAfterAuthentication not working if root path (NOT BASE URL) of application is changed.

### ISSUE THREAD

**Issue by omairrazam** [simplabs/ember-simple-auth#1652]
Hi.
I have observed a specific issue.
This is my router file code.

```js
this.route('authenticated', {path: ''}, function () {
  this.route('devices');
  this.route('dashboard');
  this.route('alerts');
  this.route('account');
  this.route('settings');
  this.route('subscription');
  this.route('groups');
});
```

I wrote this in my env file
` routeAfterAuthentication: 'authenticated.alerts',`

routeAfterAuthentication path doesn't work until I remove  {path:''} from my authenticated route.
is there any workaround for this?

**Comment by marcoow** [comment]
This might be a duplicate of #1560 which is actually a bug in Ember itself.

**Comment by omairrazam** [comment]
ok, thanks. Got it.
I had fixed it by defining a path and for root path I created another route with empy path and then redirected to the path that I consider to be root path.
