### ISSUE TITLE
Memory leak with fastboot

### ISSUE THREAD

**Issue by nutjaa** [simplabs/ember-simple-auth#1653]
I have memory leak issue with fastboot and simple-auth

my reproduce step is 
1. create new ember app 
2. add ember-simple-auth and ember-cli-fastboot 
3. add file app/authenticators/oauth2.js and app/session-stores/application.js 
4. run ember s --prod 
5. run test by using 
`ab -n 2000 -c 40 -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8" -C ember_simple_auth-session=%7B%22authenticated%22%3A%7B%22authenticator%22%3A%22authenticator%3Aoauth2%22%2C%22token_type%22%3A%22Bearer%22%2C%22expires_in%22%3A31536000%2C%22access_token%22%3A%22eyJ0838VYc%22%2C%22refresh_token%22%3A%22de0f24e4e143%22%2C%22expires_at%22%3A1564460474288%7D%7D http://localhost:4200/\
`
6. result memory usage keep going up . see attach 
![selection_055](https://user-images.githubusercontent.com/290633/43953939-d8e19334-9cc4-11e8-8d97-698d0ce90f50.png)

my test project [demo](https://github.com/nutjaa/ember-fastboot-simple-auth-leak-demo)

**Comment by nutjaa** [comment]
But if i remove expire_in & expires_at in request url . it seem no leak 

![selection_056](https://user-images.githubusercontent.com/290633/43954897-63abcacc-9cc8-11e8-8a9e-c66eba91492b.png)

**Comment by marcoow** [comment]
cleaning old issues

**Comment by florianthiel** [comment]
This issue is still present and makes simple-auth in combination with FastBoot unusable. Why has this issue been closed?
