### ISSUE TITLE
Question on using the session storage with a custom authenticator

### ISSUE THREAD

**Issue by gcampionpae** [simplabs/ember-simple-auth#1681]
I am using a custom authenticator and authorizer and would like to store the token in the session storage so that it is deleted when the browser is closed.  I've read through the documentation and cannot seem to figure out how to get it to work. Can someone please help me out?

**Comment by marcoow** [comment]
The authenticator and the storage are not really related concepts. You'd return a promise that resolves with the token from the authenticator's `authenticate` method (and `restore` potentially). Aside from that, if you want to use `sessionStorage` to store session info, you'd configure the [`SessionStorageStore`](http://ember-simple-auth.com/api/classes/SessionStorageStore.html) for your application.
