### ISSUE TITLE
Fastboot mode, isAuthenticated always fasle 

### ISSUE THREAD

**Issue by loxmys** [simplabs/ember-simple-auth#1690]
I'm enable the cookie store

```js
// app/session-stores/application.js
import CookieStore from 'ember-simple-auth/session-stores/cookie';
export default CookieStore.extend();
```

in route

```js
if (this.get('session.isAuthenticated')) {
  this.transitionTo('private.transactions');
} else {
  this.transitionTo('login', { queryParams: { previousUrl: 'private.transactions' } });
}
```

Cookies added after logging in, but this.get('session.isAuthenticated') always false.
Do you know how i can get session.isAuthenticated in fastboot mode?

**Comment by marcoow** [comment]
Hm, this should work out-of-the-box. Which authenticator are you using and what do the session contents look like?

**Comment by bobisjan** [comment]
We have recently experienced this behaviour in our application too. It seems to be broken with `v1.7.0`, using `v1.6.0` works for us as expected.

**Comment by marcoow** [comment]
This seems to be an `ember-fetch`/`fastboot` issue - @mike-north has a good write-up on the cause here: https://github.com/ember-cli/ember-fetch/issues/115#issuecomment-419741647
