### ISSUE TITLE
How can I update token

### ISSUE THREAD

**Issue by Samorodov** [simplabs/ember-simple-auth#1711]
Hi! Thanks for great auth

I have one problem, and can't solve it myself

When I save new record, in response headers I have new token whith actual information. How can I update token after saving?
```
model.save().then(m => {
     //update session token
})
```

Now I try something like this, send token in body and use ajax
```
that.get("ajax").request("questrooms", {
     method: 'POST',
     data: data
}).then((m) => {
     if (m.token) {
            let new_session = that.get('session.data.authenticated');
            Ember.set(new_session,"access_token", m.token);
     }
})
```
but after that ember-auth redirects me to login page

**Comment by marcoow** [comment]
cleaning up old issues
