### ISSUE TITLE
makeRequest doesn't return XHR object

### ISSUE THREAD

**Issue by gtb104** [simplabs/ember-simple-auth#1714]
We upgraded from 1.1.0 to 1.7.0, and now we can't establish a WebSocket connection. After the FastBoot compatibility PR #1035, `makeRequest()` no longer returns the jQuery XHR object, but a Promise instead. We were using that XHR object to pull out some header information (CSRF token specifically) and saving it off for other requests to use. Is there a new way to get the header info from `makeRequest()`? If not, the `request.headers` property should also be returned from the `fetch()` call.

**Comment by gtb104** [comment]
It would be helpful if https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L362-L364 returned the `response` object with a `responseJSON` property like it does in the `if` and the `catch`.
```
            } else {
              response.responseJSON = json;
              resolve(response);
            }
```

**Comment by marcoow** [comment]
We can't change the value that `makeRequest` resolves with now as that would be a breaking change actually. I do agree we should do that though as currently the API is a bit inconsistent. I think the way to go here would be to add a `resolveWithResponse` property similar to [`rejectWithResponse`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L159) that would allow us to introduce this in a non-breaking way.

**Comment by marcoow** [comment]
cleaning up old issues

**Comment by gtb104** [comment]
@marcoow, Any timeline on if/when your alternate suggestion would be implemented?

**Comment by marcoow** [comment]
No - if you'd like to contribute a PR implementing just that, that would be ❤️
