### ISSUE TITLE
Source-links in API documentation for 1.7.0 are broken

### ISSUE THREAD

**Issue by kimroen** [simplabs/ember-simple-auth#1717]
The "source"-links on each method in [the API documentation](https://ember-simple-auth.com/api/classes/AuthenticatedRouteMixin.html#method_beforeModel) doesn't work. 
This seems to have happened during the last API doc update:

https://github.com/simplabs/ember-simple-auth/commit/d109a962593927fad87a99c3069a2078dc8cb28d#diff-d01178e9501c53e34906c75435b42d18R98

Example broken link:

`https://github.com/simplabs/ember-simple-auth/blob/1.7.0//Users/marcoow/Code/ember-simple-auth/tmp/broccoli_yuidoc-input_base_path-odP26Z1c.tmp/0/mixins/authenticated-route-mixin.js#L56`

(correct version: `https://github.com/simplabs/ember-simple-auth/blob/1.7.0/addon/mixins/authenticated-route-mixin.js#L78`)

**Comment by marcoow** [comment]
🤦‍♂️
