### ISSUE TITLE
How to refresh the token? JWT

### ISSUE THREAD

**Issue by mapeveri** [simplabs/ember-simple-auth#1730]
Hi, I am using ember with django-rest-framework-jtw and I have the 3 urls provided by the library: token-auth, verify-token and refresh-token.
My problem is that I do not understand how to use refresh-token in ember-simple-auth. Is the refresh automatic? Or do I have to call it in the restore? If so, how? I have many doubts and I do not finish to understand how it works.
Right now in my application, when the token expires, it gives me an error of "Signature has expired" and I lose the session and I have to refresh and re-login.

Thanks!

**Comment by pichfl** [comment]
You may want to take a look at `ember-simple-auth-token` which contains an authenticator with support for JWT: https://github.com/jpadilla/ember-simple-auth-token

**Comment by mapeveri** [comment]
Hi @pichfl thanks. I'm going to check the library. But Ember-simple-auth does not work for the refresh token?

**Comment by pichfl** [comment]
No, not for the authentication method you're using. Ember Simple Auth is the base add-on providing everything necessary to write your own authenticator with support for specific authentication workflows like the one above.

**Comment by mapeveri** [comment]
OK one question. Should I implement refresh token ?. Or is there a better alternative? Today I have a token that never expires. I understand that it is insecure.

Thanks @pichfl
