### ISSUE TITLE
An "included" property, present on authenticator:oauth2, seems to be missing on authenticator:test

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [simplabs/ember-simple-auth#1732]
(Forgive me if I'm completely barking up the wrong tree, here — I spent some time on this in the Ember discord, and I'm at a loss as to where else to go!)

So I've inherited a legacy Ember project, and in trying to get at least *some* of the tests passing, I'm running up against a difference between the runtime ember-simple-auth data-model and testing data-model.

In our [application setup](https://gist.github.com/ELLIOTTCABLE/66e271acbc8ece91b2f62d358320558e), we do something like this:

```js
  beforeModel({ queryParams }) {
    let { username, password } = queryParams;
    if (username && password) {
      this.get('session').authenticate('authenticator:oauth2', username, password);
    } else if (this.get('session.isAuthenticated')) {
      return this.populateCurrentUser();
    }
  },

  sessionAuthenticated() { this.populateCurrentUser() },

  populateCurrentUser() {
    // create the full user model
    let user = this.get('session.session.authenticated.included')[0];
    // Replace user with ds model
    this.store.pushPayload({ data: user });
    user = this.store.peekRecord('user', user.id);

    // set current user in our session
    this.set('session.data.currentUser', user);
    this.set('session.data.currentUserId', user.id);

    // ...
  }
``` 

Problem is, while it's populated with a bunch of additional useful information after the `oauth2` authenticator runs (i.e. in the real world), that `included` property on `session.session.authenticated` is *empty* after the `test` authenticator runs (we're using the `authenticateSession()` helper from `ember-simple-auth/test-support`.)

I couldn't find any documentation about *any* of this — which properties are supposed to be on `session` (why are they all on the duped `session.session`, for that matter?), when `included` was removed from the test-authenticator (theoretically these tests were previously passing, at some point in history?), what `session.data` is and how it differs from `session.authenticated`, … yikes!

Is this a bug? Did my team just go about this completely the wrong way? How should I extract user data and associate it with the session, in a way that *will* work with the tests?

Thanks for your time,

**Comment by marcoow** [comment]
The `authenticateSession` helper allows you to pass additional data that will be made available via the session - see the example at https://github.com/simplabs/ember-simple-auth#testing.

I wouldn't recommend making the authenticator a full JSON:API response with side-loaded resources though and instead follow [this guide](https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md) for maintaining the current user.
