### ISSUE TITLE
How to Redirecting to outside page on invalidate()

### ISSUE THREAD

**Issue by midhunpm** [simplabs/ember-simple-auth#1734]
Hi,
In my application I am creating a custom authenticator and I wanted to go to a page outside the ember app in the invalidate() method. Our ember application is a module that connects to the main java application and the user login is handled in the main app. To simulate the user session in ember, the two apps communicate via tokens and use simple auth to create a session in ember. So when the user clicks logout in ember app, I need to kill ember session and redirect the user to a page (login page) in the main application and kill the user session in the main app as well.
Is there a way we can accomplish this without using the login route in the ember app to route in case there is no session?

**Comment by marcoow** [comment]
You can use the [`ApplicationRouteMixin`'s `sessionInvalidated` callback](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionInvalidated) to react to the session being invalidated and redirect the user anywhere via `window.location.href = '…'`.
