### ISSUE TITLE
sessionInvalidated called immediately after login - safari / iframe

### ISSUE THREAD

**Issue by pk1m** [simplabs/ember-simple-auth#1740]
Not sure what the best protocol is, my issue is very similar to https://github.com/simplabs/ember-simple-auth/issues/1187 , down to the stack trace.

Our setup is an ember app within an iframe.  
Login works fine on chrome, but on safari sessionInvalidated is called immediately after login.  

Before `sessionInvalidated` is called, it seems like everything is in order, the access_token is pulled and its logged in.  It just decides to log out only in safari.  If i access the ember app directly (iframe url) and login, everything works fine.  Weirdest part is, when I go back to site with ember app in the iframe, i'm able to login fine from then on until this issue pops up again which I haven't determined the cause.

I'm trying to debug, but i'm having trouble with the source of the `sessionInvalidated`.  It doesn't seem to be from manual `session.invalidate()`, i debugged everywhere I call it.   Any ideas or areas I should look?

Here is the site:
https://www.vinceyoungrealty.com/idx

Any help would be appreciated!

**Comment by marcoow** [comment]
I'd add a `.catch` to the `session.authenticate(…)` call:

```js
 this.get('session').authenticate(…).catch((reason) => {
  debugger;
});
```

That should help you find out what's going wrong.

**Comment by pk1m** [comment]
turned out to be caused by safari iframe cookie issue
