### ISSUE TITLE
authenticateSession does not authenticate a User in tests

### ISSUE THREAD

**Issue by belgoros** [simplabs/ember-simple-auth#1742]
I'm using Implicit Grant authentication and redirect a User to the external corporate login page if he is not authenticated in `index` route:
```
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';
import config from '../config/environment';
import isFastBoot from 'ember-simple-auth/utils/is-fastboot';
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';
import window from 'ember-window-mock';

export default Route.extend(UnauthenticatedRouteMixin, {
  session:      service('session'),
   _isFastBoot: isFastBoot(),

  beforeModel: function() {
    if (this.get('session.isAuthenticated')) {
      this.transitionTo('dashboard');
    } else {
      if (!this.get('_isFastBoot')) {
        let oauthUrl = config.oauthUrl;
        let clientId = config.clientID;
        let redirectURI = `${window.location.origin}/callback`;
        let responseType = `token`;
        let scope = `profile%20openid`;
        window.location.replace(oauthUrl
                              + `?client_id=${clientId}`
                              + `&redirect_uri=${redirectURI}`
                              + `&response_type=${responseType}`
                              + `&scope=${scope}`
        );
      }
    }
  }
});
```
In an acceptance test:
```
#tests/acceptance/dashboard-test.js

import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';
import { authenticateSession } from 'ember-simple-auth/test-support';
import setupMirageTest from 'ember-cli-mirage/test-support/setup-mirage';

module('Acceptance | Dashboard', function(hooks) {
  setupApplicationTest(hooks);
  setupMirageTest(hooks);


  test('Authenticated users can visit /dashboard', async function(assert) {
    let shop = this.server.create('shop');
    this.server.create('user', { shop });
    
    await authenticateSession({
      token: 'abcdDEF',
      token_type: 'Bearer'
    });
    await visit('/dashboard');

    assert.equal(currentURL(), '/dashboard', 'user is on dashboard page');
  });
});
```
When putting a break point in `beforeModel` hook of  `index` route, I always pass in to the `else` block, i.e. not authenticated.

What am I missing? Thank you.

Used versions:
```
ember-simple-auth: 1.8.1
ember: 3.7.3
node: v10.12.0
npm: 6.7.0
```

**Comment by belgoros** [comment]
Even after changing the value for `access_token`:
```
await authenticateSession({
      token: 'abcdDEF',
      token_type: 'Bearer'
    });
```
has't solved the problem and `this.get('session.isAuthenticated')` still returns `false` in `index` route `beforeModel` hook.

**Comment by pichfl** [comment]
You should be calling `this._super()` inside `beforeModel()` as [documented here](http://ember-simple-auth.com/api/classes/UnauthenticatedRouteMixin.html#method_beforeModel) to allow Ember Simple Auth to do its work.

**Comment by belgoros** [comment]
@pichfl Nice catch, thank you ! But, unfortunately, even after adding:
```
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';
import window from 'ember-window-mock';

export default Route.extend(UnauthenticatedRouteMixin, {
  session:      service('session'),
   _isFastBoot: isFastBoot(),

  beforeModel: function() {
    this._super(...arguments);
    console.log('+++++++++++ session.isAuthenticated: ' + this.get('session.isAuthenticated'));
...
```
it still returns `false` for `this.get('session.isAuthenticated')`.

**Comment by shankarsridhar** [comment]
@belgoros 
I am on `ember-simple-auth@1.8.0`, and mocking authenticated session just works fine for me.

One thing that might be doing something wrong with, is the `sessionData` that you pass as argument to `authenticateSession`, for mocking the authenticated session.
You might wanna double check that( `authenticateSession(sessionData);`)

**Comment by belgoros** [comment]
@shankarsridhar Thank you for your response. First, I don't know what you mean under POJO, - it is not Java world here, but JS universe 😄 .
As for what I pass in to the  `authenticateSession` in my test, it was clearly indicated in my [previous comment](https://github.com/simplabs/ember-simple-auth/issues/1742#issuecomment-462253013)

**Comment by shankarsridhar** [comment]
> @shankarsridhar Thank you for your response. First, I don't know what you mean under POJO, - it is not Java world here, but JS universe 😄 .

@belgoros I understand your confusion. :)
By POJO, I was referring to *Plain Old Javascript Object*, and it is a common term used in the JS Universe, to refer to javascript objects.

**Comment by belgoros** [comment]
@shankarsridhar it"s the first time I hear about it, glad to know that.

**Comment by marcoow** [comment]
So first of all when you're using the `UnauthenticatedRouteMixin` (with calling `this._super(...arguments)`) in your own `beforeModel` (as @pichfl pointed out), that would actually prevent anyone from entering the route already. As you're not calling `this._super(...arguments)` you might as well remove the mixin though as it doesn't to anything besides implementing `beforeModel`.

The exact session data you're passing in shouldn't actually be relevant in order to get the session mocked correctly as `authenticateSession` will **always** use a test authenticator, thus the data you pass in to `authenticateSession` will never be validated by the `OAuth2ImplicitGrant` anyway in tests.

Can you check what the session contents are in the route's `beforeModel` though? I wonder whether the session data is ever set up correctly at all. You might also want to check whether the session is maybe invalidated automatically due to an error before you reach the `beforeModel` - check the log or maybe put a breakpoint [here](https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L43).

**Comment by belgoros** [comment]
@marcoow Thank you very much for your response.

1. As for removing/keeping `this._super(...arguments);`. If I remove `this._super(...arguments);` as follows:
```
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';
import config from '../config/environment';
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';
import window from 'ember-window-mock';

export default Route.extend(UnauthenticatedRouteMixin, {
  session:      service('session'),
  routeIfAlreadyAuthenticated: 'dashboard',

  beforeModel: function() {
    if (!this.get('session.isAuthenticated')) {
      let oauthUrl = config.oauthUrl;
      let clientId = config.clientID;
      let redirectURI = `${window.location.origin}/callback`;
      let responseType = `token`;
      let scope = `profile%20openid`;
      window.location.replace(oauthUrl
                            + `?client_id=${clientId}`
                            + `&redirect_uri=${redirectURI}`
                            + `&response_type=${responseType}`
                            + `&scope=${scope}`
      );
    }
  }
});
``` 
then the content of `dashobaord` template is not displayed, it is just emty and there are no errors in the browser console.

2. You say:

> when you're using the UnauthenticatedRouteMixin (with calling this._super(...arguments)) in your own beforeModel (as @pichfl pointed out), that would actually prevent anyone from entering the route already

should may be:

> from entering the route if already **authenticated** ? 

That is the actual behaviour, - a user should be redirected to the corporate login page (see `window.location.replace` statement on the last line) if he/she is not authenticated. 
I followed the same way as you used in your [dummy app](https://github.com/simplabs/ember-simple-auth/tree/master/tests/dummy) with the only exception that I'm using `current-user.js` service as it is [explained](https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md#using-a-dedicated-endpoint) in your docs: 
- once getting the token, I hit the backend to fetch the User data and set it on `current-user` service:
```
#services/curretn-user.js
....
async loadCurrentUser() {
    this.get('flashMessages').clearMessages();
    if (this.get('session.isAuthenticated')) {
      let user = await this.get('store').queryRecord('user', { me: true });
      if (user) {
        this.get('flashMessages').success(this.get('intl').t('flash.signed_in'));
        this.get('currentShop').setShop(user.get('shop'));
        this.set('user', user);
        this.get('shopService').loadShops();
        return user;
      } else {
        this._respondWithError();
      }

    } else {
      this.get('flashMessages').info(this.get('intl').t('flash.signed_off'));
      return RSVP.resolve();
    }
  },

  _respondWithError() {
    this.get('flashMessages').danger(this.get('intl').t('flash.authentication.error'));
    return RSVP.reject();
  }
...
```
I tried once again just to display the vaue of `session.isAuthenticated` in `beforeModel` hook in `index.js` route. When executing the `**dashboard-test**` it stilll displays `false`.
```
#routes/index.js
...
  beforeModel: function() {
    this._super(...arguments);
    console.log('+++++++++++ session.isAuthenticated: ' + this.get('session.isAuthenticated'));
    if (!this.get('session.isAuthenticated')) {
      let oauthUrl = config.oauthUrl;
      ...

```
The authentication works correctly when running the app, the only trouble I have is when running this acceptance test:
```
#tests/acceptance/dasnboard-test.js

import { module, test } from 'qunit';
import { visit, currentURL } from '@ember/test-helpers';
import { setupApplicationTest } from 'ember-qunit';
import { authenticateSession } from 'ember-simple-auth/test-support';
import setupMirageTest from 'ember-cli-mirage/test-support/setup-mirage';
import { setupWindowMock } from 'ember-window-mock';

module('Acceptance | Dashboard', function(hooks) {
  setupWindowMock(hooks);
  setupApplicationTest(hooks);
  setupMirageTest(hooks);

  test('Authenticated users can visit /dashboard', async function(assert) {
    let shop = this.server.create('shop');
    this.server.create('user', { shop });

    await authenticateSession({
      access_token: 'abcdDEF',
      token_type: 'Bearer'
    });

    await visit('/dashboard');

    assert.equal(currentURL(), '/dashboard', 'user is on dashboard page');
  });
});
```
What am I missing ? Thank you

**Comment by marcoow** [comment]
Can you try and set up a minimal reproduction app? I think we need an app that exhibits the problem that we can debug.

**Comment by belgoros** [comment]
@marcoow OK, I'll create a simple app without pointing to the corporate login page and come back to you once it is done. Thank you.

**Comment by belgoros** [comment]
@marcoow Marco, I created the app [here](https://github.com/belgoros/decastore-front). Thank you for once again for your help.

**Comment by marcoow** [comment]
Your session gets authenticated just fine but it gets immediately invalidated afterwards as loading the current user fails:

```js
_loadCurrentUser() {
  return this.get('currentUser').loadCurrentUser().catch(() => this.get('session').invalidate());
},
```
