### ISSUE TITLE
Hard refresh on `invalidationSucceeded`

### ISSUE THREAD

**Issue by Redsandro** [simplabs/ember-simple-auth#1747]
What could cause a hard refresh when a session is invalidated? I would like to prevent a hard refresh from happening, and let my SPA handle the invalidated state.

This is in reference to https://github.com/jpadilla/ember-simple-auth-token/issues/261 where using `ember-simple-auth-token` causes my app to do a hard refresh when the refresh_token is failing.

It seems to be because `invalidationSucceeded` is triggered in `ember-simple-auth`:

https://github.com/simplabs/ember-simple-auth/blob/0ab8847ed94812c391f66f79c645127abd771f95/addon/internal-session.js#L139-L141

There is an example in the code as to how this might be achieved:

https://github.com/simplabs/ember-simple-auth/blob/d6071274d0cb8e3855e24bf2687c1a6395379440/addon/mixins/application-route-mixin.js#L28-L30

But I am __not__ listening to `invalidationSucceeded`.

Why does my app do a hard refresh? How can I prevent it?

**Comment by marcoow** [comment]
Reloading is ESA's default behavior (see http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionInvalidated) when the session is invalidated. It is the only way we can reliably make sure all sensitive data is deleted from memory.

**Comment by Redsandro** [comment]
@marcoow can I prevent/disable/override that behavior from within Ember?

(At my own risk)

**Comment by marcoow** [comment]
You can simply override the method added by the mixing and not call `this._super(...arguments);`.

**Comment by Redsandro** [comment]
@marcoow thank you.
