### ISSUE TITLE
Error with ember-octane-blueprint

### ISSUE THREAD

**Issue by shanemcgraw** [simplabs/ember-simple-auth#1748]
With a freshly generated `ember-octane-blueprint` app, glimmer's resolver throws the following:
`Error: Assertion Failed: 'session' is not a recognized type`

Steps to repro:
1. Generate octane app `ember new my-app -b @ember/octane-app-blueprint --yarn`
2. `yarn add ember-simple-auth`
3. `ember serve`

**Comment by NullVoxPopuli** [comment]
Currently if using the module-unification layout, here is what you have to do to get it working: 
in resolver.js:
```js
import Resolver from 'ember-resolver/resolvers/fallback';
import buildResolverConfig from 'ember-resolver/ember-config';
import config from '../config/environment';

let moduleConfig = buildResolverConfig(config.modulePrefix);
/*
 * If your application has custom types and collections, modify moduleConfig here
 * to add support for them.
 */


 moduleConfig.types = Object.assign(moduleConfig.types, {
  'session': { definitiveCollection: 'session' },
  'session-store': { definitiveCollection: 'session-store' },
  'authenticator': { definitiveCollection: 'main' },

 });

 moduleConfig.collections = Object.assign(moduleConfig.collections, {
  authenticators: {
    types: ['authenticator'],
    defaultType: 'authenticator'
  }
});

export default Resolver.extend({
  config: moduleConfig
});
```

**Comment by marcoow** [comment]
@NullVoxPopuli: is

```js
'session': { definitiveCollection: 'session' },
```

necessary? `session` is only a service that's injected, not something I think that the app needs to treat as its own type? Also for completeness I think this is missing

```js
'authorizer': { definitiveCollection: 'authorizer' },
```

but since authorizers are deprecated anyway I guess that's fine ;)

**Comment by marcoow** [comment]
Closing this as MU is delayed anyway and not something that will be supported by ESA before officially released.
