### ISSUE TITLE
Authorization token not sent on all requests with OAuth2 flow

### ISSUE THREAD

**Issue by joshsmith** [simplabs/ember-simple-auth#177]
If a session is active, I'd like to modify requests sent through my `RESTAdapter` to include a bearer token, just like the OAuth2 bearer authorizer does.

The `AuthenticatedRouteMixin` seemed like a reasonable starting point for doing something like this; however, the way it currently works is to block any unauthenticated request.

The high level use case is an application that renders a view differently whether you're logged in or out. For example, your API may show all users to you regardless of your authentication state, but if you pass in an auth token you should see metadata specific to the current user, like whether you're following someone.

I'd be happy to contribute something like this if others find it worthwhile, but I'm not sure where to start. It's also possible this can be done using some other technique that's not yet apparent to me.

Thoughts?

**Comment by PedroPinheiro** [comment]
Hi Josh, I was at the same issue, when I found a configuration that has to be made on server using CORS to allow the client send some headers.
In my case, the webapi services had to be configured as http://www.asp.net/web-api/overview/security/enabling-cross-origin-requests-in-web-api#allowed-request-headers

Hope it's usefull
