### ISSUE TITLE
read-only values in session.data.authenticated are not read only

### ISSUE THREAD

**Issue by mdbr000** [simplabs/ember-simple-auth#1781]
Chrome v72
Ember 2.18.2
ESA 1.4

The ESA doc state: 

> While the special authenticated section in the session data contains the data that was acquired by the authenticator when it authenticated the session and is read-only, all other session data can be written and will also remain in the session after it is invalidated.

However, using Chrome dev tools, one can navigate into Application -> Local Storage and double-click the value, then edit values within the object that is supposed to be read-only.

This is an issue when you are placing user roles into the authenticated session object and expect it to be protected; if it is able to be changed in this way, users can easily change their roles and therefore gain access to UI elements that would otherwise not be shown.

Is there another implementation that would prevent this edit behavior from being allowed?

**Comment by marcoow** [comment]
There's no way to safely disallow what you're describing. Generally, you cannot have any permissions stored on the client that are not also validated on the server side as **everything** that's stored client-side can be tampered with.

**Comment by mdbr000** [comment]
thanks @marcoow - another interesting note is that if you use the localStorage API to change the value, ESA logs you out automatically, but using the method described above, you can change values without being logged out

my assumption was that the behavior would be the same across both methods of manipulation

the issue takes on a different flavor when you consider that the ui displays elements based on computed permissions which are based off of the values in data.session.authenticated - would one possible approach be to use an observer on this roles property and fire an api call to verify its contents whenever it experiences a change? would the observer even detect a change that is executed via the chrome dev tools?

**Comment by marcoow** [comment]
Typically what you do is you'd keep track of roles in the Ember app perhaps and enable/disable parts of the UI based on these roles. As soon as the user visits any of these parts of the UI though, there would likely be some data being loaded. In that case, the server would of course recognize that the requesting user does not actually have access to that piece of data and simply respond with 401.

Generally, the sensible information you'll want to protect is not the UI code but the data that it would display.
