### ISSUE TITLE
Session authentication not stored in chrome.

### ISSUE THREAD

**Issue by S0r13n** [simplabs/ember-simple-auth#180]
I have implemented simpleAuth with a custom authenticator. In Safari and Firefox everything works like it should and the session properties are stored into local storage, but when I use Chrome nothing is stored. Is there something additional I have to do to get it work with Chrome?

Can it be a Chrome settings problem?

I am using the latest version of ember-simple-auth.

Thanks in advance,
René

**Comment by cravindra** [comment]
Hello.

Facing something similar. Did you find a solution?
