### ISSUE TITLE
Disable automatic token refreshing for tests

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#181]
As it causes problems (see #35), also it might actually randomly break tests.

**Comment by johnnyshields** [comment]
@marcoow your commit 75a73a6 affects our tests. can we make this behavior a config variable rather than hardcoding to `if (!Ember.testing)`?

**Comment by marcoow** [comment]
@johnnyshields: hm, why would you ever want that to run in tests?

**Comment by johnnyshields** [comment]
for long-running integration tests which test performance. I think the question is really "why would a library hardcode its behavior to not run in tests, rather than making it configurable?" Its fine if the default config is false for test env, true for non-test so as to affect existing users.

**Comment by marcoow** [comment]
I get your point - changing the behavior of sth. if it's running in test env isn't ideal but at the same time a pretty common pattern in Ember.js as you have to make sure tests are not leaking and run loop events.

I think if you're running long-running integration tests to test performance you shouldn't be running the app in test env anyway though as it will behave differently and might give you a wrong sense of its performance even (for example, ESA will always store the session in memory when running in test mode which of course is much faster than using `localStorage` or a cookie).

**Comment by johnnyshields** [comment]
@marcoow can we make this a config?

**Comment by marcoow** [comment]
@johnnyshields: I honestly don't see the need for doing that

**Comment by johnnyshields** [comment]
could we make a more general config `test_mode` which replaces all usages of `Ember.testing` within the library, which by default is set to the value of `Ember.testing` but can be overridden, so that we are not tightly coupled to Ember itself?

**Comment by marcoow** [comment]
@johnnyshields: I honestly don't see the need for doing that. As I said above - when you're executing long-running integration tests, specifically for performance testing you shouldn't be running the app in test mode anyway.

**Comment by johnnyshields** [comment]
I pray for the day when the Ember community will learn the merits of loose coupling.
