### ISSUE TITLE
Session error handler not working as expected (or at all?)

### ISSUE THREAD

**Issue by MatthewDaize** [simplabs/ember-simple-auth#1826]
To start with, here are the libraries I am using:

Ember Inspector | 3.6.0
-- | --
Ember | 3.8.1
Ember Data | 3.8.0
jQuery | 3.3.1
Ember Bootstrap | 2.6.1
Ember Simple Auth | 1.8.2

I am attempting to implement a basic Oauth2 ember app using the docs and the dummy application as a guide.

I have noticed that the error handler of a failed authentication does not seem to be working as expected (or at all?)...

Note: I am using Mirage to simulate the `/token` endpoint as follows:

> webapp/mirage/config.js
```javascript
import Mirage from 'ember-cli-mirage';

export default function() {
  this.urlPrefix = 'http://localhost:1337'; 

  function formEncodedToJson(encoded) {
    var result = {};
    encoded.split("&").forEach(function(part) {
      var item = part.split("=");
      result[item[0]] = decodeURIComponent(item[1]);
    });
    return result;
  }

  this.post('/token', (schema, request) => {
    var params = formEncodedToJson(request.requestBody);
    console.info(params);

    if (params.password === "success") {
      return {
        "access_token": "PA$$WORD",
        "token_type": "bearer"
      };
    } else {
      var body = {
        "error": "invalid_request",
        "error_description": "Email or password is invalid"
      };
      return new Mirage.Response(400, { "Content-Type": "application/json" }, body);
    }
  });

  this.passthrough('http://localhost:9000/**'); // Passthrough Sentry (if being used)
}
```

> webapp/app/components/login-form.js:
```javascript
import { inject as service } from '@ember/service';
import Component from '@ember/component';

export default Component.extend({
  session: service('session'),
  actions: {
    authenticateWithOAuth2() {
      let { identification, password } = this.getProperties('email', 'password');
      console.info("Attempting login for " + identification);
      this.get('session').authenticate('authenticator:oauth2', identification, password)
        .then(() => {
          this.get('rememberMe') && this.set('session.store.cookieExpirationTime', 60 * 60 * 24 * 14);
        })
        .catch((reason) => {
          console.error("Authentication Error!")
          console.error(reason);
          this.set('errorMessage', reason.error);
        });
    }
  }
});

```

Based on the console output, I can see that Mirage is successfully generating the error and its structured based on the outline here: https://tools.ietf.org/html/rfc6749#section-5.2 (which is also mentioned in the API Docs)...

The issue is, I cannot understand how ember-simple-auth is supposed to be handling the response (assuming that it does?)....

Am I expected to handle the response and output the `error_description` in my own fancy way? Based on the example here: https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/templates/components/login-form.hbs, it looks like the session object is supposed to be handling the response and returning an actual formatted error? Is that a correct assumption?

The response I see in the console (referenced variable: `reason`) is this:
```
Response {type: "default", status: 400, ok: false, statusText: "Bad Request", headers: Headers, …}
bodyUsed: true
headers: Headers {map: {…}}
ok: false
responseJSON: {error: "invalid_request", error_description: "Email or password is invalid"}
status: 400
statusText: "Bad Request"
type: "default"
url: ""
_bodyInit: "{"error":"invalid_request","error_description":"Email or password is invalid"}"
_bodyText: "{"error":"invalid_request","error_description":"Email or password is invalid"}"
__proto__: Object
```

The referenced variable: `reason.error` (as modeled after dummy app) is this:
`undefined`

Thanks for any insight you can provide (and let me know if I forgot some code reference you need)!

**Comment by MatthewDaize** [comment]
Okay.... so I do believe this was mostly my doing... I was trying to troubleshoot this error and inadvertently forgot to turn off `rejectWithResponse` which when false, seems to process the response.

I guess now that was cleared up, I now need to interpret the error/description and make things clear for the end user.

Thanks for reading!

**Comment by marcoow** [comment]
Yes, there is no automatic error handling in ESA. The session would simply not be authenticated and the promise returned from `sesison.authenticate` rejects. Be aware though that

```js
let { identification, password } = this.getProperties('email', 'password');
```

is not going to work - you'll explicitly have to alias `email` to `identification`:

```js
let { email: identification, password } = this.getProperties('email', 'password');
```
