### ISSUE TITLE
OAuth2PasswordGrantAuthenticator custom endpoint not working

### ISSUE THREAD

**Issue by jcfinnerup** [simplabs/ember-simple-auth#1834]
I've defined a custom ` serverTokenEndpoint`, at `api/v1/token`

When im calling the authenticate function on a non-root url in the app, i.e.:
`register/user`

.. then the serverTokenEndpoint takes the "register" part of the URL and prepends it to the endpoint. Ergo i get the error 405 not found at `register/api/v1/token`

I am probably just overseeing something, but any help would be greatly appreciated. ive been stuck here longer than id like to admit .

**Comment by marcoow** [comment]
I think you'll want to define `/api/v1/token` (with leading `/`) as the `serverTokenEndpoint`.
