### ISSUE TITLE
authenticator.restore is not called on application startup if user is not authenticated

### ISSUE THREAD

**Issue by lougreenwood** [simplabs/ember-simple-auth#1844]
Followup of #1643.

It seems that when an application is started, `authenticator.restore()` will only be called if the result of `store.restore()` contains authenticated data:
https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L67

It seems that this is because `internal-session.restore()` relies on the store providing a name for the authenticator which was used to authenticate (which I presume is a proxy for the system's default authenticator, since this is not registered anywhere).

Since the `internal-session.restore()` can't know which authenticator it should restore, it fails.

However, the API docs have a looser description which isn't conditional on an authenticated session:
> This method is invoked by the session either on application startup if *session data is restored from the session store*
http://ember-simple-auth.com/api/classes/BaseAuthenticator.html#method_restore

I'm not sure if this is a long-term bug in the system or ambiguous API docs... but I'm again hitting this issue after re-organising my auth routes caused my previous hack to fail... :(

**Comment by marcoow** [comment]
This is intended - see https://github.com/simplabs/ember-simple-auth/issues/1643#issuecomment-497752947
