### ISSUE TITLE
Wrong assignment in initializer?

### ISSUE THREAD

**Issue by nightire** [simplabs/ember-simple-auth#1846]
https://github.com/simplabs/ember-simple-auth/blob/7a4e1645aacd6ff9bc835474798b6df1eec8d663/app/initializers/ember-simple-auth.js#L11-L13

If I read this correctly, I believe line #12 should be:

```javascript
config.rootURL = config.rootURL || config.baseURL;
```

otherwise, it's pointless to set `rootURL` or deprecated `baseURL` in `ENV['ember-simple-auth']`, because `ENV['ember-simple-auth']['rootURL']` is not the same as `ENV['rootURL']`.

**Comment by marcoow** [comment]
`rootURL` is read-only in the config actually and are not meant to be set via `ENV['ember-simple-auth']` at all - we're setting it to either `rootURL` of `baseURL` from the Ember config as `baseURL` was Ember's old setting and we need to maintain backwards-compatibility with Ember 1.12.
