### ISSUE TITLE
Inconsistent builds with ember-cli-typescript

### ISSUE THREAD

**Issue by lifeart** [simplabs/ember-simple-auth#1854]
Ref: https://github.com/typed-ember/ember-cli-typescript/issues/724

inputs:

typescripted app with application route:
`/app/routes/application.ts`
ember-simple-auth addon installed

addon expose to app namespace  `ember-simple-auth/app/routes/application.js` file.

sometimes (1/10) `/app/routes/application.ts` rewritten by `ember-simple-auth/app/routes/application.js` and this is may produce tricky to debug errors.

how to fix?

have files with `.js` on both sides (`/app/routes/application.ts` -> `/app/routes/application.js`)

why this issue?
- to give developers more inputs about existing problem and add motivation to fix ember internals about merging files with different extensions

**Comment by Turbo87** [comment]
@lifeart I think I understand the issue, but I'm not sure how we can resolve this on our side 🤔

**Comment by lifeart** [comment]
@Turbo87 agree, It's ember-cli internals problem, my suggest - keep this issue alive until fix in `ember-build` side.

**Comment by marcoow** [comment]
I think ember-cli would have to _"normalize"_ all non-`.js` files to `.js` before the merge happens?

**Comment by makepanic** [comment]
There's https://github.com/typed-ember/ember-cli-typescript/issues/780 to document this issue and https://github.com/stefanpenner/broccoli-persistent-filter/issues/166 to track the root cause.

**Comment by sdebarros** [comment]
As discussed with @marcoow one possible solution in our end would be to remove the `application.js` file and check in the initializer of the session if there's a factory for the application route.

**Comment by josemarluedke** [comment]
Hey, this issue is causing non-deterministic results when building an app to production. Any changes to have this solved? 

Also, I have the same issue session-stores.

```
  - my-app/routes/application.{js,ts}
  - my-app/session-stores/application.{js,ts}
``

**Comment by Turbo87** [comment]
> Any changes to have this solved?

as mentioned above, this is largely an issue in ember-cli and/or ember-cli-typescript. there is currently not much we can do about it on our side without breaking a lot of existing apps.

**Comment by BobrImperator** [comment]
From ESA's perspective this PR would be a solution https://github.com/simplabs/ember-simple-auth/pull/2307/files but is not a good one, this week I'll try to work on setup method for users to use explicitly as we want to get rid of the initializer anyway.
