### ISSUE TITLE
Not clear how to set "authenticationRoute", "routeAfterAuthentication" and "routeIfAlreadyAuthenticated"

### ISSUE THREAD

**Issue by alexmasita** [simplabs/ember-simple-auth#1855]
A while back, I could set the above configuration in the environment file but now, it is a bit unclear from the documentation how to set them.  Any pointers would be great.  Thanks

**Comment by pichfl** [comment]
One way this can be handled is to create a new mixins in your application that extends on the one provided by ESA and overrides what you want to override. Then replace all places where you use the mixins from ESA by your custom ones.

`ember generate mixin authenticated-route-mixin` and then add something like this:
```js
import Mixin from '@ember/object/mixin';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Mixin.create(AuthenticatedRouteMixin, {
    authenticationRoute: 'hello',
});
```

usage in your routes:
```js
// app/routes/protected.js
import AuthenticatedRouteMixin from '../mixins/authenticated-route-mixin';
import Route from '@ember/routing/route';

export default Ember.Route.extend(AuthenticatedRouteMixin);
```

**Comment by alexmasita** [comment]
@pichfl, thanks for your swift response.  I get it.  What if the 'routeAfterAuthentication' route had a dynamic segment, is there a way to do that in this new way of doing things.  I guess computed properties can be used but am stumped how to transition to a route like this one below:

` this.transitionTo('public.transport.drivers.choosecab', this.paramsFor('public').user_id);`

**Comment by pichfl** [comment]
`routeAfterAuthentication` is best set in the application route after extending it by the `ApplicationRouteMixin`. Please not that the default implementation here _expects_ a route without parameters. See implementation detail in Line 114 here: 
https://github.com/simplabs/ember-simple-auth/blob/db7cf4fb67b282185a7e6de634affdf76e53c1b3/addon/mixins/application-route-mixin.js#L102-L116

#### Solutions

You can consider overriding the `sessionAuthenticated()` method of the mixin inside your application route. 

Another option that would work without overriding may be to use regular route without params for the `routeAfterAuthentication` and use the `redirect()` method there to gather the data you need from a service or elsewhere and then redirect to your route with params. The method is public, so either way should work. 

For a guide on how to use `this.transitionTo`, please consult the [Ember docs](https://api.emberjs.com/ember/3.10/classes/Route/methods/transitionTo?anchor=transitionTo).

**Comment by alexmasita** [comment]
Thanks for your help.  Would be nice to have this in documentation.

**Comment by mcfiredrill** [comment]
Would this be worth adding to the docs now, or is it moot since there seems to be a plan to remove mixins eventually. https://github.com/simplabs/ember-simple-auth/issues/1619
