### ISSUE TITLE
How is cookieExpirationTime in cookie store supposed to work?

### ISSUE THREAD

**Issue by st-h** [simplabs/ember-simple-auth#1904]
I am having some troubles understanding how the feature related to cookieExpirationTime is supposed to work. 

There is a timer which (from the comments on cookieExpirationTime) seems to be supposed to extend the cookie somehow. The thing that I am missing is that there seems to be no means of actually extending the session server side and no explicit hook where that is supposed to happen. So, it looks like the cookie expiration will be extended on the client, however there is no means to tell the server that the session expiration should be extended as well. After expiring the client will have a token with extended expiration, but the server will report back session expiration on the next request - so, I think I am missing something crucial here...

**Comment by marcoow** [comment]
I think this a mis-understanding. The idea behind the cookie expiration time is that the expiration mechanism is **purely** client side and whatever is in the cookie **never** expires on the server side. Once the cookie expires on the client side though and you lose the secret it contains you are logged out of course and if you have no means to restore the expired cookie you can never log back in.

**Comment by st-h** [comment]
@marcoow thanks for clarifying. I was thinking about scenarios where an attacker might gain access to the token (probably due to a restored browser session in an Internet cafe or something). I think it would be beneficial if the token would expire server side as well (preferably using a relatively short TTL), so that the time frame where such an attack would be possible is limited. However, it's kind of not that easy to determine what means of defence actually is reasonable or necessary. Pretty much if someone finds a way of getting hold of the token, there is little one can do.
