### ISSUE TITLE
runloop timers in FastBoot

### ISSUE THREAD

**Issue by trek** [simplabs/ember-simple-auth#1912]
We ran into an interesting issue with a combination of `OAuth2PasswordGrant`, `FastBoot`, `Cookie` session store and the runloop:

On app boot and authentication [`_scheduleAccessTokenRefresh`](https://github.com/simplabs/ember-simple-auth/blob/c02df7454fb7190fef7dfb76ebe9539d0603eedd/addon/authenticators/oauth2-password-grant.js#L405) will trigger and set up a timer in FastBoot that appears to continually rescheduled itself.

We _additionally_ ran into a similar issue as https://github.com/jpadilla/ember-simple-auth-token/issues/250 where a very large `expires_in` value overruns node's 32-bit signed integer max size when attempting to parse the cookie.

```
(node:15570) TimeoutOverflowWarning: 2591999302267 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:15570) TimeoutOverflowWarning: 2591999302265 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:15570) TimeoutOverflowWarning: 2591999302262 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:15570) TimeoutOverflowWarning: 2591999302259 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
(node:15570) TimeoutOverflowWarning: 2591999302257 does not fit into a 32-bit signed integer.
Timeout duration was set to 1.
```

Both are leading us to believe that `refreshAccessTokens` should _never_ be `true` (the [current default](https://github.com/simplabs/ember-simple-auth/blob/c02df7454fb7190fef7dfb76ebe9539d0603eedd/addon/authenticators/oauth2-password-grant.js#L104)) when run in FastBoot.

Happy to PR if that's the case.

For now, we've set `refreshAccessTokens` to `false`.

**Comment by marcoow** [comment]
Thanks for reporting this! Indeed an access token refresh should never be scheduled in FastBoot - PR would be great!
