### ISSUE TITLE
1.9.2 authenticated-route-mixin - queryParam regression 

### ISSUE THREAD

**Issue by st-h** [simplabs/ember-simple-auth#1915]
Starting ember-simple-auth version 1.9.2 ( I think it's very likely related to 84c076d0b6ebb37143498ef54c33f8fe59c702f7 ) ember shows a pretty strange error when using query params and a route is trying to be accessed that applies the authenticated-route-mixin. As it looks it only shows up when the user is not authenticated and the redirect is triggered. Reverting back to 1.9.1 fixes the issue

```
Assertion Failed: You passed the `application:referral` query parameter during a transition into application, please update to referral
    at assert (index.js:163)
    at Class._hydrateUnsuppliedQueryParams (router.js:974)
    at Class._prepareQueryParams (router.js:801)
    at Class._doTransition (router.js:749)
    at RouterService.transitionTo (router.js:114)
    at Class.triggerAuthentication (authenticated-route-mixin.js:127)
    at authenticated-route-mixin.js:107
    at runIfUnauthenticated (authenticated-route-mixin.js:30)
    at Class.beforeModel (authenticated-route-mixin.js:106)
    at Class.superWrapper [as beforeModel] (utils.js:366)
```

**Likely related**:
When debugging authenticated-route-mixin::triggerAuthentication it looks like 

`this.get('_authRouter')` returns the RouterService

whereas:

`this.get('_router')` returns a different router (probably the internal ember router)

at least: `this.get('_router') != this.get('_authRouter')`

Probably in the 1.9.1. implementation the `_router` property defined in the mixing was overridden with the ember router and has therefore been working (but that is getting a little vague now)

**Comment by st-h** [comment]
To confirm my assumptions, this is using `1.9.1` debugging the `triggerAuthentication` method:

```
Ember.getOwner(this).lookup('service:router')
> RouterService {_router: Class, __INIT_WAS_CALLED__ember15644177776861236198101007__: true}
```

```
this.get('_router')
> Class {currentURL: null, currentRouteName: null, currentPath: null, currentRoute: null, _qpCache: {…}, …}
```

So, `1.9.2` is using a different router than `1.9.1`. However, I am pretty much at a loss what the intended behaviour is/was and what would be the right way to fix this

**Comment by marcoow** [comment]
I think this is a bug in Ember.js actually where the router service is not 100% compatible with calling e.g. `transitionTo` in a route direclty, see emberjs/ember.js#16594

**Comment by st-h** [comment]
@marcoow I think this is correct. I submitted a PR https://github.com/emberjs/ember.js/pull/18244 to fix this, however I think this should be reviewed by someone who is more familiar with the inner workings of the ember routing system.

**Comment by IBue** [comment]
This is related to https://github.com/emberjs/ember.js/issues/17494 and https://github.com/emberjs/ember.js/issues/14875

**Comment by st-h** [comment]
@IBue this bug should be fixed in recent ember releases (at least I was never able to reproduce it after my PR was merged). Are you still experiencing the same error with latest versions?

**Comment by IBue** [comment]
@st-h: With _ember-source_ 3.12.2 + _ember-simple-auth_ 1.9.2/2.1.0 there is still [this](https://github.com/emberjs/ember.js/issues/14875#issuecomment-283152339) error when an unauthenticated redirect (`AuthenticatedRouteMixin#triggerAuthentication()` ) occurs into a route that is either query-parameterized by itself or by its parent.

**Comment by st-h** [comment]
Would be interesting if you are still seeing this with ember >= 3.14.1. (I don't know if the fix has actually been backported yet) However, I am afraid I can not be of more help here right now. I am just a little surprised that I have never seen this issue reappear after upgrading to 3.14.1
