### ISSUE TITLE
OAuth2ImplicitGrantCallbackRouteMixin redirection

### ISSUE THREAD

**Issue by ExpDev07** [simplabs/ember-simple-auth#1921]
Hey! I've got my /login route setup like this:
```javascript
import Route from '@ember/routing/route';
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';
import OAuth2ImplicitGrantCallbackRouteMixin from 'ember-simple-auth/mixins/oauth2-implicit-grant-callback-route-mixin';

export default Route.extend(UnauthenticatedRouteMixin, OAuth2ImplicitGrantCallbackRouteMixin, {

    authenticator: 'authenticator:oauth2'

});
```

And authentication works! When my server redirects the user to "{host}:{port}/login#access_token=abc", they do get authenticated. 
```php
/**
 * {@inheritdoc}
 */
public function authenticated(Request $request, SteamUser $steam)
{
    // Get or create the authenticating user from their steam details.
    $user = $this->get_or_create_user($steam);
    return response()->redirectTo('/login#access_token=' . $user->api_token);
}
```

However, it does not redirect them to the "routeIfAlreadyAuthenticated". For that to happen, I must manually click refresh, in which they get redirected. It should work like I have, right? The two mixins should not override each other?

Any help is appreciated!!

**Comment by ExpDev07** [comment]
Any idea on how I can achieve this or if there's an easy way that's already included in ESA?

**Comment by marcoow** [comment]
The `UnauthenticatedRouteMixin` mixin only redirects the user when they are already authenticated when they first access the route. That's not the case here though because when the user first enters the route, they are not authenticated, but they only get authenticated after they have entered the route (by the `OAuth2ImplicitGrantCallbackRouteMixin`). Redirecting the user to some target route after they become authenticated is done by the [`ApplicationRouteMixin`'s `sessionAuthenticated` method](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionAuthenticated). Are you missing that mixin in the application route maybe?

**Comment by ExpDev07** [comment]
Yup, I was! Now I've created a /callback route that uses both the OAuth2ImplicitGrantCallbackRouteMixin and ApplicationRouteMixin and it works :). However, I've used the "manage current user" guide by ESA, and when the /callback route redirects the user to "/" (index), the "{{currentUser.user}}" is null for like a tiny millisecond, so any template conditionals using that won't show, making kind of a weird user experience. However, when I refresh the page, that doesn't happen ( currentUser.user is made available before the page loads). Any idea what causes this?

**Comment by ExpDev07** [comment]
@marcoow here's an image demonstrating: https://gyazo.com/45b07d0a7014a61fa4f3c37d6de702d6

**Comment by ExpDev07** [comment]
As you can see, it flashes "No user" for like a tiny ms, which isn't the biggest deal, but a weird user experience none-the-less. I'd rather have the user wait a little extra for the whole page to load (as done when reloading browser).

**Comment by ExpDev07** [comment]
Alright, so I think I'm on the right path, but for some reason it's not calling the underlying "sessionAuthenticated" logic that triggers the redirection.

```javascript
import Mixin from '@ember/object/mixin';
import { inject as service } from '@ember/service';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

/**
 * A mixin that changes some of ESA's "ApplicationRouteMixin" default behavior.
 */
export default Mixin.create(ApplicationRouteMixin, {

    /**
     * The user that's currently logged in.
     */
    currentUser: service(),

    beforeModel() {
        // Load the current user here so that it becomes available everywhere.
        return this._loadCurrentUser();
    },
  
    /**
     * Called when the session gets authenticated.
     */
    async sessionAuthenticated() {
        await this._loadCurrentUser();
        this._super(...arguments);
    },
  
    /**
     * Loads the currently logged in user. Invalidates the session if the loading fails.
     */
    _loadCurrentUser() {
        return this.currentUser.load().catch(() => this.session.invalidate());
    }

});
```

**Comment by marcoow** [comment]
@ExpDev07 the above code looks correct, just make sure that's your `application` route, **not** the `callback` route (I think you're saying above the `callback` route has **both** the `OAuth2ImplicitGrantCallbackRouteMixin` and the `ApplicationRouteMixin` which is wrong).

**Comment by ExpDev07** [comment]
Yup, I noticed. I removed the ``ApplicationRouteMixin`` from ``callback`` route and just kept it in my ``application`` route. It works, but it doesn't call super and redirect the user. But when I remove "async" and "await", it does call both ``_loadCurrentUser()`` and the underlying logic which does the redirect. I've got no idea why... My ``current-user`` service just looks like this:

```javascript
import Service from '@ember/service';
import RSVP from 'rsvp';
import { inject as service } from '@ember/service';

/**
 * A service to manage the currently logged in user.
 */
export default Service.extend({

    session: service(),
    store:   service(),

    load() {
        // Check if the session is authenticated.
        if (this.session.isAuthenticated) {
            // Query the store for myself and set it when found.
            return this.store.queryRecord('user', { me: true }).then((user) => {
                this.set('user', user);
            });
        } else {
            // Just resolve.........
            return RSVP.resolve();
        }
    }
    
});
```

Thanks for replying btw!

**Comment by marcoow** [comment]
Hm, yeah - the guide is wrong actually. You cannot call `this._super` after `await` - you'd have to do this (see https://github.com/ember-cli/ember-cli/issues/6282):

```js
async sessionAuthenticated() {
  let _super = this._super;
  await this._loadCurrentUser();
  _super.call(this, ...arguments);
}
```

Can you submit a PR to fix the guide?

**Comment by ExpDev07** [comment]
Yes, I can, but the problem is, that doesn't work either
```javascript
/**
 * Called when the session gets authenticated.
 */
async sessionAuthenticated() {
    await this._loadCurrentUser();
    this._super.call(this, ...arguments);
},
```

It doesn't redirect... once I remove "async" it works...

**Comment by ExpDev07** [comment]
It works, wohoo! Thanks so much, I could absolutely not find this. Yup, I'll update it!

**Comment by ExpDev07** [comment]
https://github.com/simplabs/ember-simple-auth/pull/1924

**Comment by ExpDev07** [comment]
https://github.com/simplabs/ember-simple-auth/pull/1924
