### ISSUE TITLE
ember-simple-auth data adapter mixin doesn't work with Ember 3.13 without jQuery

### ISSUE THREAD

**Issue by BryanHunt** [simplabs/ember-simple-auth#1961]
I used `ember-cli-update` to update a project to EmberJS 3.13 which removes jQuery.  This causes the `beforeSend` hook in the data adapter mixin to not be called and thus the token from `ember-simple-auth-token` to not be sent with any EmberData requests.

To work around this problem, I added the `@ember/jquery` module back and enabled jquery integration in `optional-features.json`.

I found: https://stackoverflow.com/questions/55180689/ember-simple-auth-and-ember-fetch-no-authorization-in-fetch-query but I couldn't get that to work.  I did get authorization to work without jQuery by:

```js
import DS from 'ember-data';
import { inject as service} from "@ember/service"

export default DS.JSONAPIAdapter.extend({
  session: service(),

  ajaxOptions(...args) {
    const hash = this._super(...args);

    let token = this.get('session.data.authenticated.token');
    hash.headers['Authorization'] = `Bearer ${token}`

    return hash;
  }
});
```

**Comment by oliverlj** [comment]
This solution works for me as ember data use fetch now

`import { computed } from '@ember/object';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
    headers: computed('session.data.authenticated.token', function () {
        if (this.session.isAuthenticated) {
            return { 'Authorization': 'Bearer ' + this.session.data.authenticated.token };
        }
    })
});
`

**Comment by oliverlj** [comment]
I don't user options request for the moment

**Comment by TheLooseCannon** [comment]
the mixins are not a part of octane anymore...so what can we do about that?

**Comment by stark7** [comment]
@TheLooseCannon  this is what i'm currently trying to work with

class ApplicationAdapter extends JSONAPIAdapter {
}

export default ApplicationAdapter.extend(DataAdapterMixin, {
});

**Comment by brunoocasali** [comment]
Is possible to use ES6 classes with mixins (it works for every kind of class, component, model...): 

```js
export default class ApplicationAdapter extends JSONAPIAdapter.extend(DataAdapterMixin) {
 // your code
}
```

**Comment by marcoow** [comment]
Closing this as all mixins are deprecated now – see #2198
