### ISSUE TITLE
How to migrate from using authorize

### ISSUE THREAD

**Issue by AddisonG** [simplabs/ember-simple-auth#1998]
I've opened a ticket on stackoverflow asking about this issue: https://stackoverflow.com/questions/58653616/how-to-replace-the-authorize-method-in-ember-simple-auth

I'd like some further instruction on how to do acceptance tests using the `authenticateSession` method.

**Comment by marcoow** [comment]
We should add some explanation in the README for this.

**Comment by AddisonG** [comment]
Thanks @marcoow  and @sdebarros. Works perfectly.
