### ISSUE TITLE
ember-simple-auth-devise invalidate() does nothing

### ISSUE THREAD

**Issue by givanse** [simplabs/ember-simple-auth#201]
ember-simple-auth-devise [invalidate()](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/lib/ember-simple-auth-devise/authenticators/devise.js#L94) does nothing.

```
  /**
Does nothing

@method invalidate
@return {Ember.RSVP.Promise} A resolving promise
*/
  invalidate: function() {
    return Ember.RSVP.resolve();
  }
```

Ember never logs out, not even if a log out is done from the back end.

**Comment by 7sedam7** [comment]
I have the following:

`<a {{ action 'invalidateSession' }}>Logout</a>`

and when I click on Logout i get:

**Uncaught Error: Nothing handled the action 'invalidateSession'. If you did handle the action, this error can be caused by returning true from an action handler in a controller, causing the action to bubble.**

**Comment by marcoow** [comment]
@7sedam7: you're probably not mixing in the `ApplicationRouteMixin` in your application route.

**Comment by 7sedam7** [comment]
Yeah thank you, that was the problem. I have just resolved it few minutes ago.

**Comment by benbabics** [comment]
I just wanted to pass on my findings using ember-simple-auth and the gem 'devise_token_auth'. I was required to send along the uid, client and access-token. Hope this helps someone else. Thanks, @samselikoff for the example.

In `app/authenticators/devise.js`
```
export default DeviseAuthenticator.extend({
  ...
  invalidate: function(session) {
    return Ember.$.ajax({
      url:  '/users/sign_out',
      type: 'DELETE',
      beforeSend(request) {
        request.setRequestHeader( 'uid', session.uid );
        request.setRequestHeader( 'client', session.client );
        request.setRequestHeader( 'access-token', session.accessToken );
      }
    });
  }
  ...
});
```
