### ISSUE TITLE
authorize deprecation cannot be avoided when using DataAdapterMixin

### ISSUE THREAD

**Issue by juanazam** [simplabs/ember-simple-auth#2012]
Hello,

First of all, thanks for the hard work put on the addon and keeping it up to date.

Since the last time I updated the addon, I'm seeing a warning on produced by the override done on `ajaxOptions` on `DataAdapterMixin`. It's great to have deprecation warnings, but it's not great that the own addon code is calling deprecated code and not having any workaround on this.

Is there a way I can avoid this? 

I see this PR is doing that but it's not merged, do we have an ETA on this?
https://github.com/simplabs/ember-simple-auth/pull/1933

Thanks

**Comment by marcoow** [comment]
The fix for this was released in https://github.com/simplabs/ember-simple-auth/releases/tag/2.1.1

**Comment by juanazam** [comment]
Thanks @marcoow
