### ISSUE TITLE
Torii authenticator and refresh token

### ISSUE THREAD

**Issue by davideferre** [simplabs/ember-simple-auth#2031]
I'm using ESA with torii authenticator with custom provider for using oauth2 authorization code flow but it seems that doesn't refresh tokens. When an access token expires I'm logged out. In another app that uses OAuth2PasswordGrant refresh tokens works correctly.
Am I missing any configuration parameters?

**Comment by davideferre** [comment]
I've made PR #2035 extending torii provider for refreshing tokens in oauth2 authorization_code flow.

**Comment by marcoow** [comment]
Closing this as it's out of scope for ESA – logic like that can be added to the authenticator in application land.
