### ISSUE TITLE
Cookies might not be available, fallback to ephemeral store is required

### ISSUE THREAD

**Issue by lstrzebinczyk** [simplabs/ember-simple-auth#2045]
Hello

It is possible to block entirety of cookies in safari, and our customers sometimes do. Since we want to use fastboot, that would make our application just not working at all for these guys. 

It should be possible to implement a fallback in cookie store similiar to that in adaptive store.
Would that be approved?

**Comment by sdebarros** [comment]
This should be possible to implement in a [custom session store](https://github.com/simplabs/ember-simple-auth#implementing-a-custom-store), but it's not something we want to have in ember-simple-auth directly.
