### ISSUE TITLE
Using Cookies to store authentication response data

### ISSUE THREAD

**Issue by hingoman25** [simplabs/ember-simple-auth#2066]
Hi, I am using ember simple auth and currently, when I get an authentication response I store the auth token and user name (I need the username for various purposes) in localStorage. Is there a way to store it in cookies instead to make it more secure? 

Here is what I'm currently doing. When I use resolve(), I end up storing the data into localStorage.

![Screen Shot 2019-12-17 at 5 46 18 PM](https://user-images.githubusercontent.com/13734160/71048954-d9b7d000-20f5-11ea-89c3-f38aab33ba2e.png)

**Comment by marcoow** [comment]
The way you're doing it is the correct way of adding custom data into the session store. If you're using the cookie session store the data will end up in a cookie and not `localStorage`. A cookie will not be more secure than `localStorage` though as it'll necessarily be a JS-readable cookie which is vulnerable to XSS just like `localStorage`.
