### ISSUE TITLE
[Question] Security about server token (and OAuth2 password grant flow)

### ISSUE THREAD

**Issue by Freddy03h** [simplabs/ember-simple-auth#2084]
Hello, I've got a question about security about server token and the Oauth2 password grant flow.

If I understood, we need to create a server token, that will be a proxy, in order to keep `client_id` and `client_secret` on the server side. Others SPAs or clients, running in a browser, can't access it because of CORS. But about an other (proxy) server ?

What prevent someone to inspect and see the server token endpoint, and call it from a server to receive an `access_token` ?

I tried it on the dummy app example, from an http client (even if it's not oauth 2 password grand flow, it's the idea).
<img width="869" alt="Capture d’écran 2020-01-12 à 01 26 11" src="https://user-images.githubusercontent.com/1412159/72212350-88bfaf80-34da-11ea-971b-b2153157ff01.png">

What could prevent someone to call the server token ?
Thank you.

**Comment by marcoow** [comment]
If you create a proxy server that injects `client_id` and `client_secret` into incoming requests, anyone can call that from anywhere. You cannot rely on the client credentials to safely identify the client you expect. The only thing you can use the credentials for is analytics or similar things at best.

Client credentials generally do not make sense for public clients (like a SPA) as there is no way to actually keep them secret (if you embed them into the client) or keep 3rd parties from using them although they cannot actually see them (as in your example).
