### ISSUE TITLE
Release with ember-fetch^7.0.0

### ISSUE THREAD

**Issue by andreyfel** [simplabs/ember-simple-auth#2094]
The latest Ember app blueprint goes with ember-fetch^7.0.0.
The latest Ember-Simple-Auth release doesn't allow ember-fetch^7.0.0.
It causes dependency conflict.
If ESA@^3.0 is not ready I suggest releasing a patch version of ESA^2 with support of ember-fetch@^7, so, it is compatible with the latest Ember.

**Comment by marcoow** [comment]
https://github.com/simplabs/ember-simple-auth/releases/tag/3.0.0
