### ISSUE TITLE
_isFastBoot being overriden (Warning in Ember Octane)

### ISSUE THREAD

**Issue by mkam039** [simplabs/ember-simple-auth#2108]
ember-simple-auth is great!

I'm getting this error in my console though

`isFastBoot computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually. [deprecation id: computed-property.override]`

Is it in the plans to make it a getter?

**Comment by marcoow** [comment]
This should be fixed in 3.0. Be aware that’s not an error but a deprecation btw.

**Comment by mkam039** [comment]
Right, this is not an error.
