### ISSUE TITLE
Usage of headers in ember octane class syntax adapters?

### ISSUE THREAD

**Issue by brunoocasali** [simplabs/ember-simple-auth#2123]
Hello folks!

I faced a really strange issue in my octane app. Some of my functions are sending invalid headers in their requests. 
My backend app requires a custom header called `CurrentStoreId` and I fill it by using a service called `CurrentCompany` with some tracked properties eg. `currentId` as follows:

```js
export default class ApplicationAdapter extends JSONAPIAdapter {
  @service session;
  @service currentCompany;

  host = ENV.HOST;

  @computed('session.data.authenticated.token') // this is the bad part
  get headers() {
    let hash = {};

    if (this.session.isAuthenticated) {
      hash['Authorization'] = `Bearer ${this.session.data.authenticated.token}`;
      hash['CurrentStoreId'] = this.currentCompany.currentId;
    }

    return hash;
  }
}
```

For a reason I don't understand if I remove the `@computed` decorator from the headers getter, the functions which was don't working now works really well.

The README says to define a headers with computed property, but now I need to remove the `@computed` part to get everything work, so the question is:

We must continue using the `@computed` stuff when defining `headers` even when we use the ES6 getters syntax?

**Comment by boydkr** [comment]
The value of a `computed` prop will only update when a member of the dependency list updates, so in this case, updates to `this.currentCompany.currentId` will not cause the `headers` prop to recompute, even though that property is `tracked`.

We just dealt with almost exactly the same issue in our app.  I didn't want to dig into whether access to the `session` service strictly needed to use a compute prop. so I tried splitting it as such:

``` js
export default class ApplicationAdapter extends JSONAPIAdapter {
  @service session;
  @service currentCompany;

  host = ENV.HOST;

  get headers() {
    let hash = {};

    if (this.session.isAuthenticated) {
      hash['Authorization'] = `Bearer ${this.authToken}`;
      hash['CurrentStoreId'] = this.currentCompany.currentId;
    }

    return hash;
  }

 // limit use of @computed to places that need it
  @computed('session.data.authenticated.token')
  get authToken() {
    return this.session.data.authenticated.token;
  }
}
```

**Comment by brunoocasali** [comment]
@boydkr thanks for your reply!

I've got everything working after some attempts and my code is exactly yours:

```
export default class ApplicationAdapter extends JSONAPIAdapter {
  @service session;
  @service currentCompany;

  host = ENV.HOST;

  get headers() {
    let hash = {};

    if (this.session.isAuthenticated) {
      hash.authorization = `Bearer ${this.session.data.authenticated.token}`;
      hash.currentstoreid = this.currentCompany.currentId;
    }

    return hash;
  }

  pathForType(type) {
    return pluralize(underscore(type));
  }
}
```

I'll close this issue,
Thanks a lot for your time @boydkr ;D
