### ISSUE TITLE
session.invalidate() continues to store attemptedTransition

### ISSUE THREAD

**Issue by napafundi** [simplabs/ember-simple-auth#2176]
After invoking `session.invalidate()` on a specific page and attempting to log back in, the user is returned to that page. This is with the `ApplicationRouteMixin`, the `routeAfterAuthentication` set to `index`, and a call to `super.sessionAuthenticated(...arguments)`. It seems that the `attemptedTransition` should be `null` in this scenario, especially since there was no "attempted transition"

**Comment by marcoow** [comment]
I think what you're describing is kind of an edge case scenario (having an `attemptedTransition` from a previous attempt to logging in but I do agree invalidation should unset the property.
