### ISSUE TITLE
How to choose between using different authenticators at runtime when logging in?

### ISSUE THREAD

**Issue by LuisAverhoff** [simplabs/ember-simple-auth#2191]
When the client connects to any endpoint without authorization, the request is rejected with HTTP 401 Unauthorized and provides a WWW-Authenticate response that includes the authentication endpoint that the client should connect to.
 
The client should connect to the base server URL to retrieve the appropriate WWW-Authenticate settings.
 
The auth value should point to the authentication/login route - either on the same server or on a different server/port.

Here are example responses.

```
Token authentication:

WWW-Authenticate:
CustomAuth realm="web", auth="/api/login", creds="userpass", disclaimer="I accept the login disclaimer."
```

 ```
Cookie authentication:

WWW-Authenticate:
CustomAuth realm="web", auth="http://docker-runner.dev.com:8007/api/auth", creds="userpass"
```

My goal as of now is twofold. The first is to retrieve the appropriate authentication endpoint from the WWW-Authenticate header. This will serve as the `serverAuthEndpoint` for the authenticator and lastly, to dynamically pick the correct authenticator based the on authentication scheme that the server supports when logging in.

I've already implemented a `cookie-authenticator.js` and `token-authenticator.js` component.

What would be the best way to go about solving these two tasks?

**Comment by marcoow** [comment]
I guess you'd want to store the `auth` part of the `WWW-Authenticate` somewhere, redirect the user to some route where they can log in and invoke the respective authenticator with the respective path/URL there?

In case you're using ember-data and the `DataAdapterMixin` a good starting point would be overriding [`ensureResponseAuthorized`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/data-adapter-mixin.js#L82) to not invalidate the session but do the above.

**Comment by LuisAverhoff** [comment]
Yes I am using ember data. I'll try out your suggestion and see how far I get.

**Comment by LuisAverhoff** [comment]
@marcoow So I was able to create a `www-authentication-parser` module and store the `auth` property in a custom `auth` service. For my scenario, is the authenticated route mixin and unauthenticated route mixin needed? The workflow I'm thinking of is.

- Application starts up
- User transition to `/` which is a protected route
- If authenticate then everything as proceeds as normal.
- If not authenticate, the route catches the error state after a failed attempt, the `www-authentication-parser` reads in the `www-authenticate` header, stores the value of `authc` in my custom service and redirects to `/login`. The auth endpoint at this point should be configured and the user should be in `/login`.

**Comment by LuisAverhoff** [comment]
What about a situation where the user is not authenticated, the `authc` property is not configured and the user goes to `/login` I'm guessing in this situation I would have to redirect him to the main route because I have no way to authenticate him.

**Comment by LuisAverhoff** [comment]
@marcoow One other thing, if you suggest not invalidate the session on a 401 but simply redirect to `/login`, wouldn't that conflict with the `unauthenticated-route-mixin`? Since that mixin checks if you have already been authenticated and invalidating the session is what causes the session to be unauthenticated.

**Comment by LuisAverhoff** [comment]
What I just thought of is just fetching to the baseURL of the server in the `afterModel` hook in the login route. The `baseURL` of the server is authenticated and so it would fail if not authenticated and then I can parse the `WWW-Authenticate` header. This requires no changes to any of the mixins and only adds an additional hook to the login route which of course extends the `unauthenticated-route-mixin`. Of course this fetch would only happen once if we haven't parse the `WWW-Authenticate` header before. 

The only thing is that it is not obvious why we are fetching to the `baseURL`(presumably to force an unauthorized response in order to parse the `WWW-Authenticate`) headers.

**Comment by LuisAverhoff** [comment]
@marcoow  Is there way for me to manually restore the session in ember-simple-auth at the start of the app? Ember-simple-auth assumes that the user is not authenticated at the start of the app but that makes what I'm trying to do even more difficult. This is the authentication flow I'm going for.

1. At the start of the app, ember-simple-auth restores session and assume that the user is authenticated.
2. Allows transition to protected route.
3. Fetches a protected resource and if it fails, invalidate the session.

**Comment by LuisAverhoff** [comment]
I'm closing this issue as the current api(deprecated mixin) has allowed me to overcome this issue.
