### ISSUE TITLE
Cannot set read-only property '_isFastBoot'

### ISSUE THREAD

**Issue by mpirio** [simplabs/ember-simple-auth#2213]
Hi,

We have this error today : `Uncaught Error: Cannot set read-only property '_isFastBoot' on object: <Boondmanager@route:application::ember319>`.

We use [ember-interactivity](https://github.com/elwayman02/ember-interactivity) addon which use [ember-is-fastboot](https://github.com/elwayman02/ember-is-fastboot) addon. This last addon create a readonly `_isFastBoot` property in our routes.

But in [ember-simple-auth's application-route-mixin#l82](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/addon/mixins/application-route-mixin.js#L82), your addon overwrites this same property with its original value if it exists.

We know mixins are deprecate but would it be possible to correct this problem ? I think a code like this should be ok:

```javascript
if (!this.hasOwnProperty('_isFastBoot')) {
    this._isFastBoot = isFastBoot(getOwner(this));
}
```

I can PR if your are OK. Thanks,

**Comment by marcoow** [comment]
Ugh, tbh I'd just drop ember-is-fastboot – I've never been a fan of micro packages and [this certainly is one](https://github.com/elwayman02/ember-is-fastboot/blob/master/addon/mixins/is-fastboot.js). Also you'll want to get rid of mixins anyway (as [ESA just recently did](https://github.com/simplabs/ember-simple-auth/releases/tag/3.1.0-beta.0)).

**Comment by mpirio** [comment]
Hello,

I understand about micro packages 👍 . But I'm not asking to reintroduce 'ember-is-fastboot' but to improve ESA code so that it does not reassign an already existing property ;)

We'll get rid of mixins soon but it is not for now. Our Ember app is very very big and we upgrade it by steps :)

**Comment by marcoow** [comment]
I'll closes this – the `ApplicationRouteMixin` has been deprecated and I don't think we'll fix this.

**Comment by mpirio** [comment]
I understand...

But It's a little abrupt way of asking the different users of the library to update their code :D , especially for one bad line of code which overwrites a variable that does not belong to it. Like many users, we are in the process of updating our code but we are doing it step by step ;)

Thank you for all your work about ember addons and everything else 👍  !
