### ISSUE TITLE
API documentation still on version 1.8.2

### ISSUE THREAD

**Issue by bitwolfe** [simplabs/ember-simple-auth#2217]
Seems the API documentation at ember-simple-auth.com/api is still on 1.8.2. This makes it rather confusing when the README in the master branch points to it for documentation on the latest changes. How you define where transitions should go for example changed in 3.0.0.

This should probably be updated to help others adopt the new syntax.

**Comment by marcoow** [comment]
Updated: http://ember-simple-auth.com/api/

We really need to automate that…
