### ISSUE TITLE
requireAuthentication is not a function 

### ISSUE THREAD

**Issue by Nippius** [simplabs/ember-simple-auth#2221]
Hi

I upgraded to v3 and was trying to remove the use of AuthenticatedRouteMixin but I'm getting the following error and I can't figure out why:
![image](https://user-images.githubusercontent.com/1528640/85934685-5bc35580-b8de-11ea-85fb-948941dc42ac.png)
This is how my route is defined:
![image](https://user-images.githubusercontent.com/1528640/85934692-962cf280-b8de-11ea-8057-f43662d0d8f8.png)

I'm using ember@3.18
This is pretty much a copy&paste from the tutorial but I can't figure out what I'm doing wrong in order to get this working.

Any help appreciated :) Thank you

**Comment by pichfl** [comment]
Can you verify that you are running `3.1.0-beta.0` which introduces this new API? If you're using yarn, you can run `yarn why ember-simple-auth` to do so.

**Comment by Nippius** [comment]
Doh! 🤦‍♂️ That was it. I assumed the new API was already included in version 3.0. Upgrading to version 3.1.0-beta0 solved it!

Thank you @pichfl
