### ISSUE TITLE
Add docs on how to extends session

### ISSUE THREAD

**Issue by oliverlj** [simplabs/ember-simple-auth#2223]
The session service has to be named session.js in order to work.

My whole project is in typescript to I have a collision between typescript and javascript when I extends the session because the name of the file has to be session (session.ts in my case)

**Comment by marcoow** [comment]
This is a general issue with TypeScript an the way Ember CLI merges the app's and addon's trees. You could have a `my-session.ts` service though that extends ESA's `Session` (I know that's not great but should work).
