### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by andywww12** [simplabs/ember-simple-auth#2228]
Just a small one re the readme. The change actions referenced in the login template haven't been implemented in the controller.

```
  @action
  updateIdentification(e) {
    this.identification = e.target.value;
  }

  @action
  updatePassword(e) {
    this.password = e.target.value;
  }
```

**Comment by simonlennon-advanced** [comment]
thankyou new to ember and scratching my head for about 3 hours now trying to understand why the documentation was wrong
