### ISSUE TITLE
routeAfterAuthentication configuration key bug

### ISSUE THREAD

**Issue by eydamson-dev** [simplabs/ember-simple-auth#2231]
**Error: assertion failed: the route index was not found**
It throws the error when we try to login with invalid credentials then try logging in with valid credentials while having a custom authenticator.

environment.js
```
  ENV['ember-simple-auth'] = {
    routeAfterAuthentication: '/dashboard',
  }
```

router.js
```
  this.route("authenticated", { path: "" }, function () {
    this.route("dashboard");
  });
```

The reason is that it is passing a wrong key to the **getWithDefault** function.
not unless you format your environment config like this
```
  ENV['ember-simple-auth'] = {
    'ember-simple-auth': {
       routeAfterAuthentication: '/dashboard'
    }
  };
```

ember-simple-auth/addon/configuration.js
```
  load(config) {
    this.rootURL =  getWithDefault(config, 'rootURL', DEFAULTS.rootURL);
    // should be 'routeAfterAuthentication' not 'ember-simple-auth.routeAfterAuthentication'
    this.routeAfterAuthentication = getWithDefault(config, 'ember-simple-auth.routeAfterAuthentication', DEFAULTS.routeAfterAuthentication);
  }
```

**Comment by esantelises** [comment]
Above was fixed on https://github.com/simplabs/ember-simple-auth/commit/3ac64c34c8d0f3c80e428f97da383205c664cae7

**Comment by marcoow** [comment]
as @esantelises said
