### ISSUE TITLE
session.isAuthenticated becoming invalidated

### ISSUE THREAD

**Issue by maxwondercorn** [simplabs/ember-simple-auth#2236]
I noticed in development that the app would become unathenticated when making code changes. When the changes were saved the app still appeared to be authenticated after the refresh.  

If you tried to do anything on an authenticated route the app refreshes as if you logged out. Tracing through the issue, somehow `isAuthenticated` had become `false` without `session.invalidate()` being called. While I don't understand the underlying issue changes to the `current-user` service is causing the issue.

Working service basically the same as documented
```
import { set } from '@ember/object';
import Service, { inject as service }  from '@ember/service';

export default class CurrentUserService extends Service {
  @service() session;
  @service() store;

  async load() {
    if (this.session.isAuthenticated) {
      const user = await this.store.queryRecord('user', { me: true });
      set(this, 'user', user);

      const token = this.session.data.authenticated.tokenData;
      set(this, 'token', token);
    }
  }
}
```

The service had been converted to native syntax and `@tracked` added
```
import { computed } from '@ember/object';
import Service, { inject as service }  from '@ember/service';
import { tracked } from '@glimmer/tracking';
export default class CurrentUserService extends Service {
  @service() session;
  @service() store;

  @tracked user;
  
  async load() {
    if (this.session.isAuthenticated) {
      const user = await this.store.queryRecord('user', { me: true });
      this.user = user;

      const token = this.session.data.authenticated.tokenData;
      this.token = token;
    }
  }
}
```

The base cause was changing from  `set(this, 'user', user);` to `this.user = user`.  Going back to the original service fixed the issue.  Testing showed that `@tracked` had no bearing on the problem.

It seems the native class service is working in the production build but I did not do extensive testing.  I'm going back to the original code so we can continue development and don't see this as a priority issue.

```
Ember v3.16
ESA v3.0.0 
using the cookie store and also ember-simple-auth-token v5.1.1
```

**Comment by marcoow** [comment]
Are you sure

```js
 this.store.queryRecord('user', { me: true });
```

does not result in a 401 response (in which case the session would be invalidated automatically)?

**Comment by maxwondercorn** [comment]
I did not explicelty check this because I didn't think it would be relevant. When I get a chance I will verify how the query responds in the problem code.

**Comment by maxwondercorn** [comment]
@marcoow We finally got back to this issue and we have fixed the issue. We were not tacking a variable that should have been tracked. Another learning on our Octane conversion journey..
