### ISSUE TITLE
Can I safely exend the session service? 

### ISSUE THREAD

**Issue by zion** [simplabs/ember-simple-auth#2248]
I recently refactored to the new `this.session.requireAuthentication()` api and I also wanted to restrict some routes to a user role. So I created `services/session.js` and extended the session service from ESA and also added a `requireAdmin()` method to it so I can conduct logic on the data in the store and determine if the authenticated user is of a particular user role, in this case: 'admin'. 

I now see deprecation warnings in the console when running the tests: 

```
WARN: DEPRECATION: Ember Simple Auth: The session service's events API is deprecated; to add custom behavior to the authentication or invalidation handling, override the handleAuthentication or handleInvalidation methods. [deprecation id: ember-simple-auth.events.session-service]
```

Is this not an acceptable way of adding this kind of functionality?

**Comment by pichfl** [comment]
Can you post the content of the `requireAdmin()` method here? 

Extending the `session` service is very much possible and as mentioned in that deprecation even recommended. Using the `.on()` method on that service to react to changes in the auth state is what this deprecation is about.

**Comment by zion** [comment]
here is the service in its entirety...

```
import SessionService from 'ember-simple-auth/services/session';
import { getOwner } from '@ember/application';

export default class ExtendedSessionService extends SessionService {
  requireAdmin(transition){
    let owner = getOwner(this)
    let router = owner.lookup('service:router') || owner.lookup('router:main');
    // Check if authenticated user is an admin
    if(this.data.authenticated.data.attributes['role-id'] > 2){
      // If not an admin, transition to the from route
      router.transitionTo(transition.from.name);
    }
  }
}
```

**Comment by pichfl** [comment]
Hmm, that does look appropriate. Are there other parts of your application that rely on the `.on()` method of the `session` service? Yes, that method is deprecated. It is recommended to use the `handleAuthentication()` and `handleInvalidation()` methods in the extended service instead.

**Comment by zion** [comment]
Yes I do actually. I have a session event initializer. I'll refactor that piece. 

Thanks!
