### ISSUE TITLE
Tutorial in Readme does not use Release Version

### ISSUE THREAD

**Issue by ErvinSabic** [simplabs/ember-simple-auth#2253]
I was pulling my hair out for a while trying to figure out what I was doing wrong while following the tutorial listed on the readme of this repo. :) 

If you follow the tutorial the way it is now you will get an error along the lines of this: 
```
Error while processing route: management.users.index this.session.requireAuthentication is not a function TypeError: this.session.requireAuthentication is not a function
```

I was very confused because I was getting the session service that I was requesting and looking at the source code in the repo the requireAuthentication method should exist. After some help from the EmberJS Discord we found out you need to be using the beta version of ember-simple-auth for this to work. You can get this version via npm by doing `npm i ember-simple-auth@3.1.0-beta.1`.

We need to update the readme to use this beta.

**Comment by ErvinSabic** [comment]
I have created a pull request #2254

**Comment by BryanCrotaz** [comment]
The same thing just hit me - I lost a day trying to work out what typo I'd made. I swear every time I upgrade to a new Ember version I spend half my time dealing with `ember-simple-auth`, and mainly down to documentation issues.

**Comment by BryanCrotaz** [comment]
And if the beta is good enough for the tutorial, why is it not a release?

**Comment by sdebarros** [comment]
Fixed in https://github.com/simplabs/ember-simple-auth/pull/2254
