### ISSUE TITLE
Add client_id and client_secret to OAuth2 config

### ISSUE THREAD

**Issue by dustinfarris** [simplabs/ember-simple-auth#226]
It seems increasingly difficult to reopen `makeRequest` in ember-cli.  I realize that client_secret is mostly redundant in a browser application, but some OAuth2 servers expect it regardless of whether the client is public or confidential.

Would it be possible to just add these specific items to the payload (or set the appropriate header) if they are present in the user's config?

**Comment by mpash** [comment]
This is part of the spec for OAuth, it needs to be implemented. You're not on the OAuth team so you don't get to cherry pick how you think something should be implemented or what designs jive with you. That's not helping anyone but your own self interests.
