### ISSUE TITLE
Issues with extending session service

### ISSUE THREAD

**Issue by st-h** [simplabs/ember-simple-auth#2273]
After noticing the deprecation warnings, I am trying to extend the ESA session service. However, as soon as I override `handleAuthentication`, I can no longer trigger the default behaviour. Adding this simple service to an app and `routing.handleSessionAuthenticated` never gets called:

`services/session.js`
```
@classic
export default class CustomSessionService extends SessionService {

  async handleAuthentication(routeAfterAuthentication) {
    this._super(...arguments);
  }
```

Is it possible to still trigger the default behaviour and extend it when extending the session service?

I also tried to give my service a different name (like 'custom-session.js'), after noticing warnings about a conflict between session.ts and session.js files (using typescript). However, as soon as I tried to inject the custom service, that extends from the ESA service, `this.get('session')` calls within the ESA service start to fail as `this.get('session')` is undefined. I went back to staying with `session.js`. This happens as soon as the service is injected like `@session('custom-session') session`.

**Comment by st-h** [comment]
I found a way that seems to work:

```
async handleAuthentication(routeAfterAuthentication) {
    super.handleAuthentication(routeAfterAuthentication);
}
```

I was unable to make it work as it is described in the guides here: https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md

Other than reported in #2267 it seems like the session service works fine without the @classic decorator.

**Comment by IgorKvasn** [comment]
Hi @st-h 
I encountered the same problem as you, could you please help me, what am I doing wrong? I Combined guide's code with your code but `handleAuthentification` method is still not called :(
```
import BaseSessionService from 'ember-simple-auth/services/session';
import classic from "ember-classic-decorator";

@classic
export default class CustomSessionService extends BaseSessionService {

	async handleAuthentication(routeAfterAuthentication) {
		console.log('-----handleAuthentication');
		super.handleAuthentication(routeAfterAuthentication);
	}

}

```

thanks a lot

**Comment by abel-n** [comment]
@st-h Just bumped into this issue while looking for something else, seems like the guides have been updated so I this issue can be closed.
