### ISSUE TITLE
Different Stores for Different Routes

### ISSUE THREAD

**Issue by atonse** [simplabs/ember-simple-auth#2288]
Hi all,

We have what we think is an interesting use case but shouldn't be exotic.

We have an app that is used by people to get their COVID test results. And we send them their test results via SMS. They get an auto-login link via SMS that has a token for their result, example

Token 1: https://website/m/result?t=83q3fj98sbjirlsie

And we log them in as their user with that link so they can view their result.

However, in the case where people supply the same number for multiple users (like a parent supplies their number for their test result, and 3 kids... so four user accounts in total that have test results), we may deliver four different links via SMS:

Token 1: https://website/m/result?t=83q3fj98sbjirlsie
Token 2: https://website/m/result?t=alsifjsl39jse9fjlij
Token 3: https://website/m/result?t=o8sejlbijslijfliefje
Token 4: https://website/m/result?t=i983jslijfliefjieeifj

The problem is, when the user clicks on the first link, they are logged in using ESA (and the JWT Token authenticator). 

But now due to localStorage, their session is persisted.

Now, they go back to their phone and click on the second link (Token 1). But when they click on it, ESA notices they're already authenticated under Token 1, so just continues to load the page as Token 1.

What we want to do is, for anything under the `/m` route, I want to either:
- REPLACE the token with the new user's token (so they always see the right result)
- Just use the ephemeral store so each link loaded into a different tab has its own auth info.

The problem is that the REST of our app uses localStorage for obvious and legitimate reasons.

So my question is:

- How do I tell ESA to use the ephemeral store ONLY for things under `/m`, and use the regular localStorage store for everything else? And I want to preserve the token in the URL so the users can hit refresh on each tab and see the right result.

We are able to separate our routes, so we want:
* `/` - public, no session
* `/admin` - admin routes (localStorage), admin uses `AuthenticatedRouteMixin`
* `/main` - public user routes (localStorage), main uses `AuthenticatedRouteMixin`
* `/m` - these one-off, ephemeral auth routes, m uses `AuthenticatedRouteMixin`

Happy to clarify further where it makes sense. We are currently using Ember 3.12 but will upgrade to 3.24 eventually, and have full freedom in installing any addons or upgrading to any version to get this to work.

**Comment by atonse** [comment]
We "solved" this (quotes because I'm not sure this is the right way to do it). We just do a session.authenticate again on that route and removed the AuthenticatedRoute mixin which redirects. This overwrites the current session.

But it feels like a hack.

**Comment by marcoow** [comment]
That sounds like the first option I described above which I'd say is fine if that's the behavior you want. Like I said, allowing the session to be authenticated with different credentials/for multiple users **at the same time** isn't something we'd want to support in ESA and would lead to a long list of follow-up problems and questions.

I'd close this for now but feel free to reopen if you think this is something that's somehow wrong in ESA given what's in scope for ESA and out of it as I explained above.
