### ISSUE TITLE
Implicit Injection Deprecated

### ISSUE THREAD

**Issue by jrjohnson** [simplabs/ember-simple-auth#2302]
On a brand new app ESA is throwing two deprecations as of Ember 3.26.1:

```
DEPRECATION: A value was injected implicitly on the 'store' property of an instance of <app@session:main::ember176>, overwriting the original value which was null. Implicit injection is now deprecated, please add an explicit injection for this value. If the injected value is a service, consider using the @service decorator. [deprecation id: implicit-injections] See https://deprecations.emberjs.com/v3.x#toc_implicit-injections for more details.
```
```
DEPRECATION: A value was injected implicitly on the 'session' property of an instance of <app@service:session::ember177>. Implicit injection is now deprecated, please add an explicit injection for this value. If the injected value is a service, consider using the @service decorator. [deprecation id: implicit-injections] See https://deprecations.emberjs.com/v3.x#toc_implicit-injections for more details
```

**Comment by knownasilya** [comment]
Also this breaks in Ember v4 because of this I think.

**Comment by sly7-7** [comment]
@marcoow Do you have any plan how to get rid of these deprecations ?

Currently initializers are both regitering and inject the properties. (the session-store into the session, and the session into the session service) 
As theses objects are not a service, it should be possible to move to the pattern explained here: https://deprecations.emberjs.com/v3.x/#toc_implicit-injections.

If you agree with this direction (defining a getter which use owner.lookup()), I can have a try a making a PR.

**Comment by BobrImperator** [comment]
It looks like this is a correct way to proceed, doesn't seem like anything could break by changing the way we inject dependencies. The only concern would be to check the lookup API maybe, ESA is mostly targeting 3.0+ If I remember well there have been some changes to looking up registered entities.

Please create a PR @sly7-7, this should speed things up or eventually I could pick it up later this week.

**Comment by snewcomer** [comment]
Thanks for this issue!  Btw, this functionality will be removed in v4.0

**Comment by josemarluedke** [comment]
As Ember v4 beta is out, it would be awesome to have this deprecation fixed.
