### ISSUE TITLE
[DEPRECATION] Usage of the Ember Global is deprecated (Ember.libraries.register...)

### ISSUE THREAD

**Issue by marcemira** [simplabs/ember-simple-auth#2309]
## Description
This line here:
https://github.com/simplabs/ember-simple-auth/blob/1cca7aaed927e06efac7fcc5153cea3bc90832eb/packages/ember-simple-auth/index.js#L24 
Is causing the following deprecation:

`
DEPRECATION: Usage of the Ember Global is deprecated.
You should import the Ember module or the specific API instead.
[deprecation id: ember-global]
See https://deprecations.emberjs.com/v3.x/#toc_ember-global for more details.
`

**Comment by brunoocasali** [comment]
Is there any way to fix that without removing this code? I do not found a public replacement :thinking:

**Comment by BobrImperator** [comment]
We should probably go by the example of Ember Inspector, they don't use global Ember but use requireModule api instead.

https://github.com/emberjs/ember-inspector/blob/33b61245f6bef7adca44c262957bb171580fab9e/skeletons/web-extension/scripts/in-page-script.js#L32

**Comment by johanrd** [comment]
Ok, yes, it would be great if the above method could work (If Ember Simple Auth really needs to be registered at all)

For now, this blocks upgrade to Ember 3.27, with the following error message:

```
Uncaught ReferenceError: Ember is not defined at register-version.js:1
Ember.libraries.register('Ember Simple Auth', '3.1.0');
```

That said, `Ember.libraries.register(libraryName, libraryVersion)` still seems to be a part of the official docs of Ember 3.27, so I filed [an issue](https://github.com/emberjs/ember.js/issues/19705) regarding the documentation.

**Comment by josemarluedke** [comment]
As Ember v4 beta is out, it would be awesome to have this deprecation fixed.

**Comment by josemarluedke** [comment]
Would we be open to drop the `libraries.register` entirely? Looking to move to Ember v4 soon, so this deprecation is a blocker.

**Comment by BobrImperator** [comment]
I'm open to that, I've been thinking about that as well since the libraries register feels like a failed experiment, I'd like to see what Ember Inspector does though, they use this functionality as well.

**Comment by brunoocasali** [comment]
Well, the link you sent to me in this comment https://github.com/simplabs/ember-simple-auth/issues/2309#issuecomment-894377115 shows that ember inspector uses a vendor loader and deal directly with `libraries` after requiring the ember global, it seems that this problem will appear in the ember inspector too.

Even if these deprecations do not appear there, for ESA I think the bothering will not be worth it.

**Comment by brunoocasali** [comment]
I've added a draft PR as a proposal to solve this issue :)
