### ISSUE TITLE
Ember 4.1.0: Use of `assign` has been deprecated. Please use `Object.assign` or the spread operator instead.

### ISSUE THREAD

**Issue by xomaczar** [simplabs/ember-simple-auth#2356]
Internal session uses assign from `@ember/polyfills` which has been deprecated since version 4.0

See: [Code Reference](https://github.com/simplabs/ember-simple-auth/blob/bca31c8055840ce5537c2d910482200d18070018/packages/ember-simple-auth/addon/internal-session.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L6)

If there are no arguments against it I can PR Object.assign replacement to remove this deprecation.

**Comment by BobrImperator** [comment]
closed by #2355
