### ISSUE TITLE
Typescript error on accessing prohibitAuthentication 

### ISSUE THREAD

**Issue by usamahamed** [simplabs/ember-simple-auth#2364]
I try to access `prohibitAuthentication` and i have to annotate it with @ts-ignore because there is no type for it in `Session.d.ts` file `types/ember-simple-auth/services/session.d.ts`

ember-simple-auth version `4.2.0`

**Comment by rwwagner90** [comment]
@usamahamed I don't think this addon ships any types. Perhaps that file is your own types and you need to add that method?

**Comment by BobrImperator** [comment]
As Robert said, ESA doesn't provide any types yet, did you install some separate package by any chance?

**Comment by usamahamed** [comment]
@rwwagner90 @BobrImperator I am sorry for late replying, i overlooked the comment somehow 

You right, we can close this issue
