### ISSUE TITLE
CookieExpirationTime not being set

### ISSUE THREAD

**Issue by hoIIer** [simplabs/ember-simple-auth#2410]
Ember 4.2.0
Ember Simple Auth 4.2.0
Ember Simple Auth Token 5.3.0
Fastboot "enabled"

I'm trying to enable my app to maintain authentication after browser is closed and reopened and realized the issue lies with the cookie being set to `session` and not having an expiration time as configured by `cookieExpirationTime`.

I tried the following based on the [cookieStore docs](https://ember-simple-auth.com/api/classes/CookieStore.html#property_cookieExpirationTime) and which had no effect with the cookie continuing to be set to `session` with no expiration:
### login-modal.js
```
        this.session.store.cookieExpirationTime = (24 * 60 * 60);

        yield this
          .session
          .authenticate('authenticator:jwt', {
            username: changeset.get('username'),
            password: changeset.get('password'),
          });
```

Then after reading through other issues I saw the below and tried it. The cookie now shows expiration time and works after browser reopened, however I see two cookies in inspector now:
```
import CookieStore from 'ember-simple-auth/session-stores/cookie';

const CustomCookieStore = CookieStore.extend({
  init() {
    this._super(...arguments);

    this._initialize({
      cookieExpirationTime: 555555,
    });
  },
});

export default CustomCookieStore;
```

What's the correct way to set cookieExpirationTime?

### edit
I discovered the following works but also results in two cookies appearing where one of them has `value` set to the cookieExpirationTime:
```
import CookieStore from 'ember-simple-auth/session-stores/cookie';

export default class ApplicationSessionStore extends CookieStore {
  cookieExpirationTime = (24 * 60 * 60);
}
```
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/230757/167272384-018cf6f1-00ad-42bc-9320-dddd96de6ffc.png">

Does that look correct?

**Comment by BobrImperator** [comment]
Hi, thanks for reaching out :)

The `login-modal.js` example should work but you need to change it to:
```js
        this.session.store.set('cookieExpirationTime', 24 * 60 * 60);

        yield this
          .session
          .authenticate('authenticator:jwt', {
            username: changeset.get('username'),
            password: changeset.get('password'),
          });
```

Also ESA removde the `_initialize` method in `4.2.2` so please upgrade it. You should be able to safely remove the custom store file once you do it.
Lastly, the 2 cookies are expected, one holds data and the other is for keeping the expiration time.

**Comment by hoIIer** [comment]
Hey @BobrImperator ok great I will try out removing the file and updating the modal code, thank you!
