### ISSUE TITLE
ember-polyfills.deprecate-assign deprication in Ember 4.4

### ISSUE THREAD

**Issue by usamahamed** [simplabs/ember-simple-auth#2426]
I am currently upgrading Ember version to `4.4` and now i get this depreciation with id `ember-polyfills.deprecate-assign` 

Seems it comes from `ember-simple-auth/addon/utils/assign.js`

More info: https://deprecations.emberjs.com/v4.x/

versions
`ember-simple-auth`: `4.2.2`
`ember-source` and `ember-cli`: `4.4.0`
`npm`: `16.14.0`
`node`: `8.3.1`

**Comment by BobrImperator** [comment]
In 4.2.0 we've released a fix for that which should use `Object.assign` instead of the polyfill when available.

Is the deprecation happening inside some older browser by any chance?

**Comment by usamahamed** [comment]
@BobrImperator You're right, looks like it was because of this issue https://github.com/ember-cli/ember-fetch/issues/707 

 Sorry for my late reply, vacations time 😆
