### ISSUE TITLE
Need an event for session restoration

### ISSUE THREAD

**Issue by hjdivad** [simplabs/ember-simple-auth#276]
Suppose we want to connect to a websocket in an initializer, but we depend on auth credentials stored in the session.

Reconnecting on the `'sessionAuthenticationSucceeded'` event works, but we'd also want to reconnect on when the session is merely restored.  It makes sense to differentiate authentication from restoration.  How about `sessionRestorationSucceeded` and `sessionRestorationFailed` events on the store?

**Comment by lessless** [comment]
how do you make that observer works? 
in my case 
```javascript
import Ember from 'ember';

export default Ember.Controller.extend({
  didAuthenticate: function() {
    if (this.get('session.isAuthenticated') === true) {
      this.transitionTo('welcome');
    }
  }.observes('session.isAuthenticated').on('init')
});
```
cause an infinitive loop, and if I remove ```on('init')``` than it's not fired at all.
