### ISSUE TITLE
Any other better way to preload current user?

### ISSUE THREAD

**Issue by Supro** [simplabs/ember-simple-auth#317]
Hi, I need to preload user model and set it as a property for session before application is ready. I'm trying to write initializer.

``` javascript
export default {
  name: 'current-user',
  after: 'simple-auth',

  initialize: function(container, application) {
    application.deferReadiness();
    session = container.lookup('simple-auth-session:main');
    if (session.get('isAuthenticated')) {
      container.lookup('store:main').find('user', 'me').then(function(user) {
        session.set('currentUser', user);
        application.advanceReadiness();
      });
    } else {
      application.advanceReadiness();
    }
  }
};
```

But `session.get('isAuthenticated')` every time return `false` because session promises didn't resolved yet. I wrote another initializer which do job, but I don't think it's a proper way.

``` javascript
export default {
  name: 'current-user',
  after: 'simple-auth',

  initialize: function(container, application) {
    application.deferReadiness();
    session = container.lookup('simple-auth-session:main');
    session.restore().then(function() {
      container.lookup('store:main').find('user', 'me').then(function(user) {
        session.set('currentUser', user);
        application.advanceReadiness();
      });
    }, function(){
      application.advanceReadiness();
    });
  }
};
```

Is there any other better way to preload user?
What do you think about to add `sessionRestoreSucceeded` event trigger to [setup](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L235) method and `sessionRestoreFailed` event trigger to [restore](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L210) method?

**Comment by craineum** [comment]
@jmonster or @seanrucker, I am in need of the same solution right now, but am not able to decipher your solution.  Is there anyway you could do a jsbin or some other kind of example code?

**Comment by jmonster** [comment]
@craineum basically change your router.js from something like this:

```js
var Router = Ember.Router.extend();

Router.map(function() {
  this.resource('articles');
  this.resource('posts');
  this.resource('yano-stuff-you-want-to-protect');
  this.route('login');
  this.route('login/callback');
});
```

to something like this:
```js
Router.map(function() {
  this.route('login');
  this.route('login/callback');
  
  this.route('protected', { path: '/' }, function() {
    this.resource('articles');
    this.resource('posts');
    this.resource('yano-stuff-you-want-to-protect');
  });
});
```


and then add the protected mixin to the `ProtectedRoute` to ultimately have articles, posts, etc protected.

**Comment by craineum** [comment]
@jmonster Sorry... I completely blanked that I posted this, figured it out the next day.  Hopefully this will help someone else in the future.

**Comment by dschmidt** [comment]
I was struggling with this yesterday when I was porting my project from some legacy version of simple-auth to the latest beta.
As I stumbled above this old issue I feel others might do too and I should share what I came up with:

First I create a custom authenticator that fetches a user object with ember-data.

``` javascript
import OAuth2 from 'simple-auth-oauth2/authenticators/oauth2';

export default OAuth2.extend({
    user: null,
    fetchUser(identification) {
        // couldn't make proper injection work here when called from restore()
        return this.container.lookup('store:main').find('user', {
            identification
        }).then((users) => {
            return users.get('firstObject'); 
        });
    },
    
    restore(data) {
        return this._super(data).then((response) => {
            return this.fetchUser(response.my_identification_key).then((user) => {
                this.set('user', user);
                return response;
            });
        });
    },
    authenticate(options) {
        return this._super(options).then((data) => {
            return this.fetchUser(options.identification).then((user) => {
                this.set('user', user);
                return data;
            });
        });
    },
    
    invalidate(data) {
        return this._super(data).then(() => {
            this.set('user', null);
        });
    }
});
```
(something around these lines at least)

and then I extend the session to make the user available through the authenticator:

``` javascript
import Ember from 'ember';
import SimpleAuthSession from 'simple-auth/session';

export default SimpleAuthSession.extend({
    authenticatorObject: function () {
        if (Ember.isEmpty(this.get('authenticator'))) {
            return undefined;
        }

        return this.container.lookup(this.get('authenticator'));
    }.property('authenticator'),

    user: function () {
        return this.get('authenticatorObject.user');
    }.property('authenticatorObject.user')
});
```

Hope this is of help to anyone :)

**Comment by marcoow** [comment]
@dschmidt: I would actually not recommend doing that. See the ["authenticated account" example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html) for the recommended way of making the authenticated account available via the session.

**Comment by dschmidt** [comment]
Well, that makes it harder to reference (and compare) the user in a template like this 
``` javascript
{{if (eq model session.user)}}
``` 
If ```session.user``` is a promise you can't do that, either you need to wrap it in a PromiseObject and always reference the ```id``` like 
``` javascript
 {{if (eq model.id session.user.id)}}
```` 
which is more verbose and seems like comparing an implementation detail I shouldn't need to care about when writing a template.

Or I would observe your user promise and always set the user property when it resolves .. seems much hackier than just making sure the isAuthenticated state implies the presence of the user object  IMHO.

**Comment by marcoow** [comment]
You're right, the promise should be wrapped in a `PromiseObject`. Could you prepare a pull request maybe?
