### ISSUE TITLE
Authenticator restore empties the session when using with torii providers

### ISSUE THREAD

**Issue by snovity** [simplabs/ember-simple-auth#345]
I'm trying to use simple-auth with torii providers, and if restore is called on torii authenticator it just empties the session. It happens because none of torii providers implement the `fetch` method and by default it resolves with empty hash for `data` https://github.com/Vestorly/torii/blob/master/lib/torii/torii.js#L19

**Comment by tommyblue** [comment]
@snovity could you please provide the full code you used to let the provider work?

**Comment by snovity** [comment]
@tommyblue my code has evolved from that point, but it was like this

```js
import Ember from 'ember';
import AuthenticatorTorii from 'simple-auth-torii/authenticators/torii';

export var initialize = function() {
  AuthenticatorTorii.reopen({    
    // session data has changed or app that already had persisted session was opened
    restore: function(data) {
      // doing nothing, cause none of torii providers return anything when session is invalidated
      // and it clears the session
      return new Ember.RSVP.Promise(function(resolve) { resolve(data || {}); });
    }
  });
};

export default {
  name: 'reopen-authenticator-torii',
  before: 'simple-auth-torii',
  initialize: initialize
};
```

**Comment by tommyblue** [comment]
thanks @snovity 
now the authentication persists after refresh, but the code causes a strange bug: it's now impossible to sign out with the `invalidateSession` action, I get this error:

```
Uncaught Error: Assertion Failed: Error: Expected a provider named 'null' , did you forget to register it?vendor.js:15936 Ember.assertvendor.js:41532 RSVP.onerrorDefaultvendor.js:60057 __exports__.default.triggervendor.js:61069 Promise._onerrorvendor.js:59300 publishRejectionvendor.js:41506 (anonymous function)vendor.js:12750 DeferredActionQueues.invokevendor.js:12820 DeferredActionQueues.flushvendor.js:12206 Backburner.endvendor.js:12261 Backburner.runvendor.js:30294 runvendor.js:32235 handleRegisteredActionvendor.js:50795 (anonymous function)vendor.js:4548 jQuery.event.dispatchvendor.js:4234 elemData.handle
```

**Comment by snovity** [comment]
@tommyblue it seems torii authenticator expect provider to be always set on authenticator and I have rewritten more then this bit. This should help
```js
    restore: function(data) {     
      var resolveData = data || {};
      this.provider = resolveData.provider;
      return new Ember.RSVP.Promise(function(resolve) { resolve(resolveData); });
    }
```

**Comment by tommyblue** [comment]
thank you @snovity 
works great! :+1:

**Comment by ksamc** [comment]
I think a better approach is to add the fetch method to your Torri provider.

```js
// app/torii-providers/mycustomprovider.js
import FacebookOauth2Provider from 'torii/providers/facebook-oauth2';

export default FacebookOauth2Provider.extend({
  fetch: function(authData){
      return authData; // returns the same data
  }
});
```

You can extend any of Torri's built in providers and add the method. Additional advantage is that you can for example ask your backend api if the session data is still valid.

**Comment by marcoow** [comment]
@ksamc :+1:

**Comment by seawatts** [comment]
This works for me as well. Seems kinda hacky though =/

**Comment by eatpurely** [comment]
@tommyblue I am now seeing this issue again, same chain of events, could not get session to persist after a refresh, now got that working. But can not seem to get past the "Error: Expected a provider named 'null' , did you forget to register it?" error. When in the restore() method this.provider seems to be null before I set it. But also the data from restore(data) is only the user data from the session, there is no data.provider. I have even tried to manually set this.provider = 'facebook'. Still getting error. I am so using torii/facebook-connect and not torii/facebook-oauth2. Could you maybe share some insight how to get past this error? Thanks in advance.

**Comment by dan003400** [comment]
@tommyblue I am now seeing this issue again, same chain of events, could not get session to persist after a refresh, now got that working. But can not seem to get past the "Error: Expected a provider named 'null' , did you forget to register it?" error. When in the restore() method this.provider seems to be null before I set it. But also the data from restore(data) is only the user data from the session, there is no data.provider. I have even tried to manually set this.provider = 'facebook'. Still getting error. I am so using torii/facebook-connect and not torii/facebook-oauth2. Could you maybe share some insight how to get past this error? Thanks in advance.

**Comment by knownasilya** [comment]
Also seeing the same issue as @dan003400

**Comment by knownasilya** [comment]
I solved my problem by returning the data in my extended `authenticate` method inside the resolved promise.

```js
  authenticate() {
    return this._super(...arguments).then(function (data) {
      alert(`authorizationCode:\n${data.authorizationCode}\nprovider: ${data.provider}\nredirec
      return data; 
    });   
  },
```

**Comment by ldong** [comment]
OR

ESA

```
export default OAuth2PasswordGrant.extend({
 authenticate() {
    return this._super(...arguments)
 }
}
```

In your login controller

```
import Ember from 'ember';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),

  actions: {
    authenticate() {
      let { username, password } = this.getProperties('username', 'password');
      this.get('session')
      .authenticate('authenticator:oauth2', username, password)
      .then((data) => {
        console.log(data);
      })
      .catch((error) => {
        this.set('errorMessage', error.message);
      });
    }
  }

});

```
