### ISSUE TITLE
Updated auth token on every api request

### ISSUE THREAD

**Issue by solsberg** [simplabs/ember-simple-auth#375]
I am looking for suggestions on how to support the following scenario. 
My server currently returns a new auth token on every API request which I need to capture from the response headers each time to then use for authorization of the subsequent request. So I can't simply capture the response headers from the initial authentication request and then use the same token for each request in the authorizer. 
The ember-simple-auth authorizer API is able to hook into each API request by providing a hook into the ajax prefilter but it doesn't seem to be able to hook into the ajax response chain in order to capture the updated token and store it for the next request.
Do you see a good way of supporting this? Thanks

**Comment by marcoow** [comment]
Sure, that works as well. I'm not sure whether it's worth adding an abstraction for this to Ember Simple Auth as it's sth. that's rarely used and is easily done via an `.ajaxSuccess` callback in an initializer.

**Comment by achan** [comment]
Any way to do this in 1.0?

**Comment by marcoow** [comment]
@achan: the best way would probably be to do that in your Ember Data adapter's `handleResponse` method.

**Comment by jpakulski** [comment]
@marcoow I am probably missing something but I can not find a way to update the session data as mentioned above.

Our app does not use Ember Data. It does make an ajax call to a Rails API. DeviseTokenAuth is used to secure the API. The token changes on every request.

I added an the following instance initializer (app/instance-initializers/ajax-success.coffee):

```coffeescript
initialize = (applicationInstance)->
  session = applicationInstance.lookup('service:session')

  $(document).ajaxSuccess((event, xhr)=>
    accessToken = xhr.getResponseHeader('access-token')
    client = xhr.getResponseHeader('client')

    if accessToken? and client?
      authenticated = session.get('data.authenticated')
      authenticated.accessToken = accessToken
      authenticated.client = client

      session.set('data.authenticated', authenticated)
      # Assertion Failed: "authenticated" is a reserved key used by Ember Simple Auth!
  )

AjaxSuccessInitializer =
  name: 'ajax-success'
  initialize: initialize

`export {initialize}`
`export default AjaxSuccessInitializer`
```

This fails because data.content is read only.

I can do all sorts of ugly things to get this to work, least of which is: storing the new token in a different property and overwrite the authorizer, but that seems like a lot of work.There must be a better way? Is there a way to do this?

Thank You

**Comment by marcoow** [comment]
You cannot set the `authenticated` section of the session manually. You can set the token though via e.g. `session.set('data.authenticated.<token-property>', accessToken)`.

**Comment by jpakulski** [comment]
Thank You. I tried this but dismissed it because the value did not get saved to localStorage. There seems to be a bug with this? Might be related to [#926](https://github.com/simplabs/ember-simple-auth/issues/926)?

The following (ugly) works:

```coffeescript
  $(document).ajaxSuccess((event, xhr)=>
    accessToken = xhr.getResponseHeader('access-token')

    if session.isAuthenticated and accessToken?
      authenticated = session.get('data.authenticated')
      authenticated.accessToken = accessToken

      # Required if data.authenticated is to propagate to localStorage
      session.set('data.foo', 'bar')

      console.info 'From data.authenticated: ', session.get('data.authenticated.accessToken')
      console.info 'From localStorage: ', JSON.parse(window.localStorage['ember_simple_auth:session']).authenticated.accessToken
  )
```

Thank You again.

**Comment by marcoow** [comment]
Yeah that might be related to #926
