### ISSUE TITLE
ember-simple-auth-devise doesn't add token header

### ISSUE THREAD

**Issue by gopeter** [simplabs/ember-simple-auth#376]
I really don't know if this is a bug, but it drives me crazy. I'm trying to add `ember-simple-auth` with `ember-simple-auth-devise` to my application. All works fine, authentication, login, tokens are written to localStorage, but authorization doesn't work: the token header isn't set. 

I'm using Ember 1.8.1, Ember Data 1.0.0-beta.12, Handlebars 1.3.0, jQuery 1.11.1, Ember Simple Auth 0.7.2 and Ember Simple Auth Devise 0.7.2 for my frontend. My backend is backed with Rails, Grape and Devise.

Both `ember-simple-auth` and `ember-simple-auth-devise` are added to my `package.json`/`bower.json` and installed (otherwise authentication/login wouldn't work :smile_cat:) and the authorizer is set in my `environment.js` file:

```
ENV['simple-auth'] = {
  authorizer: 'simple-auth-authorizer:devise'
};
```

I just played around with some `console.log` debugging. It seems that the `authorize` function don't get fired. All other functions could be logged successfully, except `authorize` and I can't figure out why.

I opened a question on [stackoverflow](http://stackoverflow.com/questions/27385392/ember-simple-auth-doesnt-add-token-to-every-request) too, if this isn't a bug and just a mistake of mine.

**Comment by henriquecf** [comment]
I have had this exactly same problem. Although I configured crossOriginWhitelist and it still does not work. I have tried everything I could but not able to make this work.

Using Ember 1.13, Ember Data 1.13, ember-cli 1.13, ember-cli-simple-auth 0.8, ember-cli-simple-auth-devise 0.8 and bundled versions of ActiveModelAdapter (now separate from ember-data) 1.13

**Comment by holamendi** [comment]
@henriquecf I had the same problem, in my case, the issue was in my SessionsController. Make sure your response after creating a session looks like this.

```ruby
def create
  super do |user|
    data = {
      token:      user.authentication_token,
      email: user.email
    }
    render json: data, status: 201 and return
  end
end
```

The issue was that I was returning user_email instead of email.

**Comment by henriquecf** [comment]
I have even decided to use Oauth after all the problems I have had, but I will try this @holamendi thanks!!
