### ISSUE TITLE
Auth header not being sent if tokenAttributeName is changed & Rails is expecting 'token', not 'user_token'

### ISSUE THREAD

**Issue by matthooks** [simplabs/ember-simple-auth#387]
I ran into a couple of issues using ember-simple-auth and ember-simple-auth-devise (both 0.7.2) with Rails 4.2 and ember-rails.

With the default configuration, ember-simple-auth-devise expects a `user_token` and `user_email` from the server in order to set up a session, and then sends both in the `Authorization` header on subsequent requests e.g. `"Token user_token=\"p-bbux4Br1ULzvzjTGGv\", user_email=\"test@example.com\""`.

The `authenticate_with_http_token` method within Rails, however, uses [`"token="`](https://github.com/rails/rails/blob/25b14b4d3238d5474c60826ee1b359537af987ef/actionpack/lib/action_controller/metal/http_authentication.rb#L400) as a key to find the token from the `Authorization` header. This means that the token that it finds ends up parsed like: `user_token="p-bbux4Br1ULzvzjTGGv` instead of just `p-bbux4Br1ULzvzjTGGv`, causing the authentication filter to fail, at least as it is written in the ember-simple-auth-devise README. (issue 1)

To attempt to fix the problem, I set the `tokenAttributeName` setting within ember-simple-auth-devise to `token`. Since this setting also changes what ember-simple-auth expects back from the server, the [`authorize` function](https://github.com/simplabs/ember-simple-auth/blob/8cdbab604b8ea6618c00304e8750039ccdc863c1/packages/ember-simple-auth-devise/lib/simple-auth-devise/authorizers/devise.js#L69) within ember-simple-auth-devise `get`s `token`, instead of the `user_token` (which the server returns, at least as it is written in the README). Thus, the `Authorization` header on the outgoing API request is not set, causing the token authentication to fail. (issue 2)

Double whammy.

I was able to finally solve the issue by changing `user_token` to `token` in the response from the `create` action in my session controller.

The Rails function should probably be configurable to properly parse the Authorization header, but I also wonder if in the mean time we should set the default `tokenNameAttribute` to be `token` instead of `user_token` since that's what Rails is expecting, and devise is a Ruby plugin?

**Comment by marcoow** [comment]
You're right, the token should always be sent as `token`. Pull request would be cool.

**Comment by marcoow** [comment]
fixed in #394

**Comment by Tonkonozhenko** [comment]
How can I get latest changes from master for my Rails app?
Now I attach library via Rails Assets

```ruby
# Gemfile
source 'https://rails-assets.org'
gem 'rails-assets-ember-simple-auth'
```

**Comment by marcoow** [comment]
This hasn't been released yet - next version will probably ship later this week. Using master directly doesn't work really - you'll have to build your own, see the README for reference.

**Comment by vasilakisfil** [comment]
kudos @matthooks. Changing both the server json response and the tokenAttributeName to 'token' worked like a charm.

**Comment by simo163** [comment]
I installed the last version of ember simple auth devise but it seems like the request does not include the token in the header.  My configuration is: 
````
  ENV['simple-auth-devise'] = {
       tokenAttributeName: 'token',
       identificationAttributeName: 'email',
	serverTokenEndpoint: ENV.host + '/users/sign_in',
	authorizer: 'devise'
  };
  
  ENV['simple-auth'] = {
	// crossOriginWhitelist: ['*'],
	authorizer: 'simple-auth-authorizer:devise'
  };
```

when I uncomment crossOriginWhitelist: ['*'] the ember app sends OPTIONS request instead of GET. any idea how I would what's wrong?

**Comment by jackweinbender** [comment]
I'm in the same boat---using the `-token` authorizer. I can't seem to get the `Authorization` header to work, even whitelisting `['*']`.

**Comment by talhaobject90** [comment]
I had a situation to attach the token with the header manually . (to upload images via ember-uploader to carrier-wave in rails api).
I done it this way 
```
// in controller
export default Ember.Controller.extend({
  session: Ember.inject.service('session'),
  var authenticated = controller.get('session.data.authenticated');
   ajaxSettings: function() {
         var settings = this._super.apply(this, arguments);
         settings.headers = {
           'Authorization':'Token token="'+ authenticated.token +'", email="'+ authenticated.email+'"'
           };
         return settings;
       }
```
Is it okay to get the token with controller.get('session.data.authenticated) ?
i am afraid this is a reliable method or not.
If there is any better method. please share me.

Thanks

**Comment by marcoow** [comment]
You should always use the [session service's `authorize` method](http://ember-simple-auth.com/api/classes/SessionService.html#method_authorize) to generate authorization data.

**Comment by talhaobject90** [comment]
@marcoow , 

Thanks for a quick reply.

I had set it in my devise authenticator as you said
```
import DeviseAuthorizer from 'ember-simple-auth/authorizers/devise';
export default DeviseAuthorizer.extend({
  actions: {
    authorize: function(){
      this.get('session').authorize('authorizer:devise', (headerName, headerValue) => {
        XHR.setRequestHeader(headerName, headerValue);
        // jqXHR.setRequestHeader(headerName, headerValue); I tried jqXHR too
      });
    }
  }
});
```
but it's not sending token with header , my ember-uploader request is redirected like this in console
```
XMLHttpRequest cannot load http://localhost:3000/siteimages/28. The request was redirected to 'http://localhost:3000/users/sign_in', which is disallowed for cross-origin requests that require preflight.```

 my previous method worked well  .but this one not .Is it any problem with the devise authenticator implementation? 

Thanks

**Comment by benbabics** [comment]
Any word on this? I'm encountering the same issue. I've whitelisted both '*' and the auth0 domain, and I'm still getting a 401 because the Authorization header isn't being added to the request. Any help is much appreciated.

**Comment by marcoow** [comment]
In order to have a request authorized you can either use the [`DataAdapterMixin`](http://ember-simple-auth.com/api/classes/DataAdapterMixin.html) if it is an Ember Data request or use the [session service's `authorize` method](http://ember-simple-auth.com/api/classes/SessionService.html#method_authorize) directly if it is e.g. a plain jQuery request:

```js
this.get('session').authorize('authorizer:devise', (headerName, headerValue) => {
  const headers = {};
  headers[headerName] = headerValue;
  Ember.$.ajax({
    url: '…',
    headers
  });
});
```

Auto-authorization of all requests was removed in ESA 1.0.

**Comment by benbabics** [comment]
That worked. Thanks for your help, @marcoow.

**Comment by bmatmentel** [comment]
HI, 
I am having the same problem with sending the header. I understood from doing gizillion searches, that I need to include the header in the authorizers. But @marcoow 's comment seems to indicate that the header needs to be attached to the actual request? Can somebody please clarify?
To clarify: I have a service to get the information of the current user from the back-end and add it to the session. I am having a lot of problems with what sounds a very simple task.

**Comment by benbabics** [comment]
@bmatmentel I applied to his change to my application adapter:

```
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  namespace: 'api',
  host: 'http://myapi.herokuapp.com',
  authorizer: 'simple-auth-authorizer:jwt',
  headers: {
    'Content-type': 'application/json'
  }
});
```

`authorizer` added the Authorization header and `headers` hash added the `Content-Type` header for me.

**Comment by bmatmentel** [comment]
Thanks @benbabics!
But what worked for me at the end, I found it here: https://github.com/simplabs/ember-simple-auth/issues/798, in a comment by @gte451f, 
I was to able to include the code in the authorizer. What happens is that the signature from  `authorize` changed from ` authorize: function (jqXHR, requestOptions)` to ` authorize(sessionData, block)`.

**Comment by marcoow** [comment]
@bmatmentel: when reading stuff about authorization on stackoverflow or on blogs make sure the content is for ESA 1.0 - the 1.0 release changed authorization quire significantly.

**Comment by bmatmentel** [comment]
@marcoow Thanks for the comment, But I am new to this. Can you point to more info on ESA 1.0? Also, how do you make sure contents in blogs refer to it when it is not explicitly specified?

**Comment by marcoow** [comment]
All info on this repo as well as on the ESA website relates to the latest version of course. If you're upgrading from a previous version you can follow this guide on our blog: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10.

If blogs don't specify the version of ESA they refer to you have no way of knowing really - just be aware that quite some things changed with ESA 1.0
