### ISSUE TITLE
What if authentication route is an external URL?

### ISSUE THREAD

**Issue by samselikoff** [simplabs/ember-simple-auth#389]
In an app I'm working on now, the authentication route is actually external to the Ember application, and is managed by a different system. This system emails users a link that they click which automatically brings them to the Ember app, authenticates them using query params, then logs them in.

The various mixins have been great for achieving the automatic log in, but redirecting to an external URL when authentication fails or the session is destroyed has been a bit of work, especially regarding testing. Essentially I made something like this on the app route:

```js
redirectToRecovery: function() {
  if (config.environment === 'test') {
    this.transitionTo('signup');

  } else {
    window.location.replace(config['simple-auth'].authenticationUrl);
  }
}
```

and just invoke that method on the various hooks (`sessionInvalidationSucceeded`, `sessionAuthenticationFailed` etc.). Also, the `signup` route just happens to be an unprotected route in the app, so in my tests I can verify users cannot access protected routes. This is clearly not the best solution.

Any thoughts on a simpler way to accomplish this? Would you accept some PRs along these lines if I have some time to work on it?

**Comment by marcoow** [comment]
Whenever authentication needs to be triggered the mixins will invoke the [`authenticateSession` action](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-ApplicationRouteMixin-authenticateSession) which by default will simply transition to `Configuration.authenticationRoute`. If your authentication route is external to the Ember application you could simply override that action and implement the redirect there. Of course you'd still have to handle the test environment where you don't want to redirect to another URL.

Does that solve your use case?

**Comment by samselikoff** [comment]
Ah, yes I believe it does. Thanks Marco!

**Comment by jackmatt2** [comment]
`authenticateSession` is now deprecated, what is the new way to achieve this?

**Comment by marcoow** [comment]
@jackmatt2: you call the `authenticate` method on the session service as explained in the README: https://github.com/simplabs/ember-simple-auth#basic-usage

**Comment by jackmatt2** [comment]
Does not work when the login page is hosted elsewhere. In my case a jsp page.

**Comment by marcoow** [comment]
@jackmatt2: sounds like that might be sth. for stackoverflow

**Comment by jackmatt2** [comment]
Yep, added it.
