### ISSUE TITLE
what happens in ember 2.0 with the login controller?

### ISSUE THREAD

**Issue by mgenev** [simplabs/ember-simple-auth#390]
As I'm sure you've heard, the controllers  are going away in Ember 2.0, does that mean you'll be switching Ember Simple Auth to use a component instead? I'm trying to code future proof...

**Comment by marcoow** [comment]
Yes, the login controller will probably be replaced by a login component then (which simply means renaming the `LoginControllerMixin` to `LoginComponentMixin`).

This isn't really an issue yet though...
