### ISSUE TITLE
Invalidating a session then immediately authenticating

### ISSUE THREAD

**Issue by samselikoff** [simplabs/ember-simple-auth#391]
My app has a route that looks like this:

> http://localhost:4200/auth?email=bob@acme.com&token=123

We email this link to our users, and when they click it, they are authenticated with their email/token (essentially username and pw), and a session is created.

I'm doing this using `AuthRoute` and `AuthController`. Here's the controller:

```js
import Ember from 'ember';
import AuthenticationControllerMixin from 'simple-auth/mixins/authentication-controller-mixin';

export default Ember.Controller.extend(AuthenticationControllerMixin, {

  authenticator: 'simple-auth-authenticator:devise',
  queryParams: ['email', 'token'],

  attemptAuthentication: function() {
    this.send('authenticate', {
      identification: this.get('email'),
      password: this.get('token')
    });
  }

});
```

and the route

```js
import Ember from 'ember';

export default Ember.Route.extend({

  setupController(controller, model) {
    controller.attemptAuthentication();
  }

});
```

Essentially, when the user visits `/auth` with his credentials, the app automatically logs him in.

Here's where I'm stuck. If a user already has a session when they visit `/auth`, I'd like to invalidate that session before attempting to authenticate a new session with the url params.

I thought `AuthRoute#beforeModel` would be a good place for this, so I tried

```js
beforeModel: function(transition) {
  if (this.get('session.isAuthenticated')) {
    return this.get('session').invalidate();
  }
}
```

This seems to work when I click around my app, but I'm getting an error in my test:

```js
test("as an authenticated user, visiting auth with valid credentials logs in the user", function() {
  authenticateSession();
  visit('/auth?email=bob@acme.com&token=123');

  andThen(function() {
    equal(currentPath(), 'reminders.index');
  });
});
```

> Error: Can't trigger action 'sessionInvalidationSucceeded' because your app hasn't finished transitioning into its first route. To trigger an action on destination routes during a transition, you can call `.send()` on the `Transition` object passed to the `model/beforeModel/afterModel` hooks.

Any ideas why? And, is this the best way to handle this?

**Comment by marcoow** [comment]
You cannot send actions (which the `ApplicationRouteMixin` does after the session is invalidated) before the transition into the app's first route is complete. You're (implicitly) triggering an action though by invalidating the session in the route's `beforeModel`.

I would simply handle invalidation of the session in the `attemptAuthentication` method if the session is found to be authenticated. You would also change the application route's `sessionInvalidationSucceeded` action to not reload the page in that case.

Why do you need to invalidate the session before anyway? Its content would be replaced with whatever the authenticator returns anyway.

**Comment by samselikoff** [comment]
Originally I wasn't going to worry about invalidating the existing session, which would certainly be simpler. However if I don't, and a session exists when the user hits `/auth`, the redirect to `authenticationRoute` never occurs. Also, neither `sessionAuthenticationSucceeded` or `sessionAuthenticationFailed` are hit.

I added a debugger a breakpoint to the devise authenticator's `authenticate` method, and it is indeed being called, and everything seems to work (the promise is resolved). But then the app just stays on `/auth`. Any ideas?

**Comment by marcoow** [comment]
I think in your case it's better not to use the mixing as those make assumptions about how the flow of session authentication/invalidation goes that are not correct in your case. There's an example that shows how to use the library without the mixing in the repo.

**Comment by samselikoff** [comment]
I switched to

```js
this.get('session').authenticate('simple-auth-authenticator:devise', data).then(null, function(error) {
  _this.set('errorMessage', error);
});
```

from example 9, and I'm actually seeing the same behavior. When authentication succeeds from an already authenticated session, it just stops, and none of the hooks are called. Any other tips?

**Comment by marcoow** [comment]
Yes, if you don't use the mixins there are no automatic transitions etc. you need to hook up event listeners to the session events manually, e.g. in an initializer.

**Comment by samselikoff** [comment]
I have via `sessionAuthenticationSucceeded` in my app route w/ApplicationRouteMixin. Would you expect behavior to be any different if authentication was attempted when a session already exists?

**Comment by marcoow** [comment]
That's what I mean - the mixins (which only exist for convenience, you can use the library without them) make assumptions about the flow of session authentication and invalidation, e.g. so that they always transition to different routes when the session is authenticated or invalidated. In your case where that flow isn't really what you want, it's probably better to not use the mixins and handle the session events manually (see [this example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/9-custom.html)).

**Comment by samselikoff** [comment]
Ahh I see, not just the login mixin but all the mixins. Ok, will do. Thanks!

**Comment by marcoow** [comment]
Yeah, especially the `ApplicationRouteMixin` as that maps the various session events to the route actions and provides default implementations for those.
