### ISSUE TITLE
Ephemeral storage changes should trigger `sessionDataUpdated`

### ISSUE THREAD

**Issue by calexicoz** [simplabs/ember-simple-auth#392]
The Ephemeral storage is recommended for testing, but it does not behave like LocalStorage when it comes to changes to the session. In particular, since no `sessionDataUpdated` is triggered, the following scenario is hard to test:

```javascript
test('visiting / and logging out', function() {
  authenticateSession();
  visit('/'); // Authenticated route
  click('a:contains("Logout")'); // invalidateSession action

  andThen(function() {
    equal(currentPath(), 'users.sign_in');
  });
});
```

The session will be invalidated, but not other events will be triggered. This differs from production/dev behavior which is unexpected.

Is there a simple work-around, or maybe I'm testing this the wrong way? Any guidance would be welcome.

Thanks!

**Comment by marcoow** [comment]
The `sessionDataUpdated` event is only necessary for external changes in the stores (e.g. from another day ab or window) which cannot happen with the ephemeral store. 

Your test should work actually. What do you mean no other events are triggered?

**Comment by calexicoz** [comment]
For some reason I thought the `sessionDataUpdated` event was what caused the route transition when invalidating the session. I'll see if I can isolate the case on a test app/repo and reproduce the error.

**Comment by calexicoz** [comment]
I was able to isolate the error in a simple test app with only 2 routes: index and login.
It's a new app generated with Ember CLI 0.1.4. I just added Ember Simple Auth and some boilerplate.

https://www.dropbox.com/s/yq24x48dh7x3wos/app2.tgz?dl=0

**Comment by marcoow** [comment]
I still don't understand what the error actually is. You say the session gets invalidated so that seems to be ok. Do you mean the `sessionInvalidationSucceeded` action on the application route doesn't get invoked?

**Comment by marcoow** [comment]
Can you set up a jsbin for that?

**Comment by calexicoz** [comment]
I'll try. Maybe I am not understanding how the addon is supposed to work. I thought that when the session gets invalidated, the addon triggers a route transition to send you back to the login page. This is what the test "tests":

- Get authenticated
- Go to an authenticated page
- Click a logout button which sends the `invalidateSession` action
- Be redirected to the login page

From what I have seen, this works just fine when I run my app, which uses the LocalStorage adapter. But the above test fails, ie you stay on the same page, there is no route transition to login.

**Comment by calexicoz** [comment]
I'll setup a jsbin this evening.

**Comment by calexicoz** [comment]
Also, in the test app [I linked](https://www.dropbox.com/s/yq24x48dh7x3wos/app2.tgz?dl=0), you should be able to run it with `ember serve` and then go to <http://localhost:4200/tests>. There is just that one test.

**Comment by calexicoz** [comment]
Hi. I got around to create a jsbin. So here it is: http://jsbin.com/nosagawezu/2/edit?html,js,output

In that example, I expected to be redirected to the index after the login succeeded, and to be redirected to the login page, after the logout succeeded. But maybe I'm not understanding how this works. Do I need to transition manually? Looking at [sessionAuthenticationSucceeded](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-ApplicationRouteMixin-sessionAuthenticationSucceeded) and [sessionInvalidationSucceeded](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-ApplicationRouteMixin-sessionInvalidationSucceeded), it looks like there should be a transition, so I'm a bit confused.

**Comment by marcoow** [comment]
As you're faking the login and call `restore` to authenticate the session the `sessionAuthenticationSucceeded` event isn't triggered. Also in your example you can only logout from the index page so there's no transition after logout as you already are on the index page.

**Comment by calexicoz** [comment]
I'm closing this. I misunderstood how these events are supposed to work and when they happen. I'll spend more time on the docs. Thanks for the help.
