### ISSUE TITLE
torii adapter not being invoked

### ISSUE THREAD

**Issue by wayne-o** [simplabs/ember-simple-auth#396]
I have an adapter:

https://github.com/wayne-o/sonatribe/blob/torii/src/sonatribe-ui/app/torii-adapters/facebook-oauth2.js

Which follows the convention for adding an adapter so that I can send the auth code to the server to log in on my api once authenticated. However the adapter isn't being invoked. Should this still work when using torii with the simple auth stuff?

**Comment by marcoow** [comment]
Please post these kinds of general questions on stackoverflow.com and use this for issues. If it is an issue it should probably go into the Vestorly/torii issue tracker.

**Comment by wayne-o** [comment]
done: http://stackoverflow.com/questions/27890654/ember-simple-auth-and-torii

**Comment by OrKoN** [comment]
Hi @wayne-o  Have you found a solution? I think that I have the same problem but the link to SO is dead

**Comment by wayne-o** [comment]
I am getting there - I am doing this for an OS project - here is the UI part of the code:

https://github.com/wayne-o/sonatribe-ui

I'm about to do some refactoring though to clean it up so you may want to hold off lifting any code from it.
