### ISSUE TITLE
Seeing double login after invalidateSession is called

### ISSUE THREAD

**Issue by ultimatemonty** [simplabs/ember-simple-auth#397]
After calling `invalidateSession` and then attempting to log back in my app is reloading the login screen again. If I login a second time things work perfectly. I was trying to step through the simple-auth code and it looks like it's failing for me at [line 165 in session.js](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L165). I never get into the `then` method when it fails. 

I also noticed that I'm getting a random `?` in my URL when logging in. The URL when on the login route is `localhost:1337/#/login`. After attempting a login it changes to `http://localhost:1337/?#/home` Unsure if this had anything to do with my issue.

To summarize:
* `invalidateSession` kills the session cookie and reloads the app at the root URL
* Enter valid credentials and attempt to login - `authenticate` never hits the `then` at [line 165 in session.js](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L165), login route reloads
* Enter valid credentials and attempt to login, `authenticate` hits the `then` at [line 165 in session.js](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L165), session authenticated, and everything is fine
* Random `?` being added at login.

Using  Simple Auth 0.7.2 and Cookie-Store 0.7.2

**Comment by marcoow** [comment]
When you use the (optional) `ApplicationRouteMixin` there will always be a transition to the login screen after session invalidation. If you don't want that to happen always you need to either not use the mixin (then you need to handle the session events manually though) or override the `sessionInvalidationSucceeded` action and customize the behavior for these special cases.

**Comment by ultimatemonty** [comment]
This ended up being an issue with my submit button component. It manifested itself in a strange way which initially led me to think is was ESA causing the issues. Closing.
