### ISSUE TITLE
Customize param names for sign in

### ISSUE THREAD

**Issue by arunthampi** [simplabs/ember-simple-auth#401]
I use a `login` parameter (which can be either username or email) in my Devise setup, so is it possible to have it be configurable instead of hard-coded like so? https://github.com/simplabs/ember-simple-auth/blob/1aa36a67dd089a8cd5a12bba9e7b016f46ad01bc/packages/ember-simple-auth-devise/lib/simple-auth-devise/authenticators/devise.js#L120

If that's the case should it be using `identificationAttributeName`? I can whip up a patch if this suggestion sounds good.

**Comment by marcoow** [comment]
Yeah, I'd say that's a bug and should be changed to `tokenAttributeName`. Please be sure to change the documentation as well if necessary.

**Comment by arunthampi** [comment]
Do you mean `identificationAttributeName`? Here's the pull request: https://github.com/simplabs/ember-simple-auth/pull/403, thanks!

**Comment by marcoow** [comment]
Oh yeah sure, I meant `identificationAttributeName`.
