### ISSUE TITLE
data returned from torii authenticator is undefined

### ISSUE THREAD

**Issue by jmimi** [simplabs/ember-simple-auth#402]
When I use torii authenticator for login the returend data is undefiend.
I test with google-oath2 and facebook-oauth2.
```
this.get('session').authenticate('simple-auth-authenticator:torii', 'google-oauth2').then(function(authorization) {
                console.log('google) auth => ' + authorization); // undefiend

            }, function() {
            });
```

**Comment by marcoow** [comment]
The promise resolves without a value. You can access session data via the session instead - check the README and API docs.

**Comment by jmimi** [comment]
Thanks for response.
I checked out API docs but I could not know where could I read authorization code?

**Comment by marcoow** [comment]
http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Authenticators-Base-authenticate

Anything the authenticator resolves with can be accessed via the session, e.g. if the authenticator resolves with `{ token: 'token' }` you can get that token via `this.get('session.token')` once the session is authenticated.

**Comment by jmimi** [comment]
Thanks a lot
