### ISSUE TITLE
Feature request: isNotAuthenticated

### ISSUE THREAD

**Issue by JoshSmith** [simplabs/ember-simple-auth#404]
Is there any possibility of getting an `isNotAuthenticated` boolean?

**Comment by marcoow** [comment]
What would be the use case of that?

**Comment by marcoow** [comment]
Any feedback? I'd say instead of having the extra property you can simply use

```handlebars
{{#unless session.isAuthenticated}}
```

as opposed to

```handlebars
{{#if session.isAuthenticated}}
```

**Comment by JoshSmith** [comment]
That's honest a much better approach.
