### ISSUE TITLE
Page refresh nukes the current user

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#405]
I want to be able to survive a page refresh meaning that the user will remain logged in.

For some reason this does not work, have I missed something?

**Comment by marcoow** [comment]
Yes, you most likely missed sth.

Please post questions like this on stackoverflow.com and if you actually find a bug in the library open an issue and make sure you include enough information so that people can reproduce the bug and eventually fix it.

**Comment by ivaylopivanov** [comment]
Ok, I've made a fresh install using ember-cli and the latest ember-simple-auth, copy-paste the dummy app, and when I refresh, I need to log in again. Whats the catch?
