### ISSUE TITLE
Cookie isn't saving on refresh

### ISSUE THREAD

**Issue by joshpfosi** [simplabs/ember-simple-auth#406]
I apologize for my dumb question, but looking over the docs it seems like `ember-simple-auth` should preserve a client side session across page reloads, however I'm running a fresh install of the library (setup exactly as laid out in the docs - which are beautiful btw), and I log in, and if I refresh I have to log in again. I thought I might need to explicitly use `simple-auth-session-cookie-store`, but upon adding this to my `config/environments.js`:

```
  ENV['simple-auth'] = {
    authorizer: 'simple-auth-authorizer:devise',
    store: 'simple-auth-session-store:cookie'
  }
```

I get this error: `Uncaught TypeError: Cannot read property 'on' of undefined`.

Not sure if I'm missing something fundamental here.

**Comment by marcoow** [comment]
How did you install the library? Did you install the cookie store extension library?

**Comment by joshpfosi** [comment]
Via

```
npm install --save-dev ember-cli-simple-auth-cookie-store
ember generate ember-cli-simple-auth-cookie-store
```

Originally, I didn't realize this original component was necessary. After running the above commands the error has gone away but reloading the page still returns me to the login page (presumably because the session isn't being saved).

**Comment by marcoow** [comment]
Can you check whether it's being saved and post the contents befor and after reload here?

**Comment by joshpfosi** [comment]
So I logged in, check cookies:

```
Name:	ember_simple_auth:session
Content:	%7B%22authenticator%22%3A%22simple-auth-authenticator%3Adevise%22%2C%22token%22%3A%22rXriQ3SsrWMVY8PxokBV%22%2C%22email%22%3A%22test%40test.com%22%2C%22role%22%3A%22admin%22%2C%22entity%22%3Anull%7D
Domain:	localhost
Path:	/
Send for:	Any kind of connection
Accessible to script:	Yes
Created:	Monday, January 19, 2015 at 5:27:41 PM
Expires:	When the browsing session ends
```

Reloaded the page and the cookie is gone. Is that the information you needed? Thanks for the assistance!

**Comment by marcoow** [comment]
Your server responds with `token` and `email` while it should be `user_email`.

**Comment by joshpfosi** [comment]
I see. Changing the response of the server does not eliminate the issue though :(.. Really appreciate your effort helping me.

**Comment by marcoow** [comment]
Can you post the cookie contents again?

**Comment by joshpfosi** [comment]
Sure:

```
Name:	ember_simple_auth:session
Content:	%7B%22authenticator%22%3A%22simple-auth-authenticator%3Adevise%22%2C%22token%22%3A%22rXriQ3SsrWMVY8PxokBV%22%2C%22user_email%22%3A%22test%40test.com%22%2C%22role%22%3A%22admin%22%2C%22entity_id%22%3Anull%2C%22entity_type%22%3Anull%7D
Domain:	localhost
Path:	/
Send for:	Any kind of connection
Accessible to script:	Yes
Created:	Tuesday, January 20, 2015 at 12:07:20 PM
Expires:	When the browsing session ends
```

As before, refreshing the page clears the cookie.

**Comment by marcoow** [comment]
The problem must be that [this check](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/lib/simple-auth-devise/authenticators/devise.js#L95) fails for some reason and the method returns a rejecting promise. I couldn't see why this would fail actually though - you'll have to do some debugging I'm afraid.
