### ISSUE TITLE
Using ember-cli-pretender to mock responses in tests

### ISSUE THREAD

**Issue by hchood** [simplabs/ember-simple-auth#408]
I'm using [ember-cli-pretender](https://github.com/rwjblue/ember-cli-pretender) to mock server responses in tests for my ember-cli/rails-api app.  I've replicated the issue here:
https://github.com/hchood/ember-simple-auth-pretender-test

This works fine in all of my integration tests except those for logging in or signing up using `ember-simple-auth-oauth2`.  For whatever reason, the mocks are never called in those tests:

```js
// frontend/tests/acceptance/signing-in-test.js

// ...
module('Acceptance: Signing In', {
  setup: function() {
    application = startApp();

    server = new Pretender();

    server.post('/api/v1/token', function(request) {
      // test never hits this breakpoint
      debugger;

      // ...
    });
  },

  teardown: function() {
    Ember.run(application, 'destroy');
  }
});

test('user signs in', function() {
  visit('/login');

  fillIn('input[name="email"]', 'helen@example.com');
  fillIn('input[name="password"]', 'secretpassword');

  click('input[type="submit"]');

  andThen(function() {
    // tests
  });
});
```

However, login appears to work fine in development.

I'm not sure if this is a bug or there's something in the internals of the library that doesn't play nice with pretender.  Any insight would be appreciated!

**Comment by quaertym** [comment]
You should replace line:
```
server.post('/api/v1/token', function(request) {
```
with this:
```
server.post('http://localhost:3000/api/v1/token', function() {
```

This is the path the request is made. See [trek/pretender docs](https://github.com/trek/pretender#unhandled-requests) as well.

**Comment by marcoow** [comment]
The problem is that Pretender doesn't mock cross origin requests. Since your tests are served from http://localhost:4200 (or a different port even when you're running `ember test`) and the authenticator requests http://localhost:3000 Pretender won't mock that request. The simple fix is to simply

configure a relative endpoint for the authenticator to use in the test environment in `config/environment.js`:

```js
if (environment === 'test') {
  …
  ENV['simple-auth-oauth2'].serverTokenEndpoint = '/api/v1/token';
  …
}
```

**Comment by hchood** [comment]
Ahhh. Thanks so much Marco!
