### ISSUE TITLE
`authenticateSession()` test helper must be called after a `visit()` call

### ISSUE THREAD

**Issue by kevinansfield** [simplabs/ember-simple-auth#409]
As per the issue I initially raised on the ember.js repository: https://github.com/emberjs/ember.js/issues/10263

The `authenticateSession()` helper returns a call to `wait()`, however this causes an infinite loop crash if there has not been a previous `visit()` call as that method sets up the router which `wait()` relies upon.

Is this simply a documentation issue for the `ember-simple-auth-testing` package or can the helper be updated to work around the problem?

**Comment by marcoow** [comment]
The [tests in the example project](https://github.com/simplabs/ember-cli-simple-auth-example/blob/master/tests/integration/authentication-test.js) work and they don't call `visit` before calling `authenticateSesison`. Is this sth. introduced in a later Ember version maybe?

**Comment by kevinansfield** [comment]
Ah, yes. Digging a little deeper it appears to be something that has changed between the latest beta and current canary.

**Comment by marcoow** [comment]
I'd say that should be fixed in Ember as it doesn't make sense to have to visit a route only to setup the router so that the `authenticateSession` can work.

**Comment by marcoow** [comment]
Fixed in Ember.
