### ISSUE TITLE
Refresh on sign in

### ISSUE THREAD

**Issue by joshpfosi** [simplabs/ember-simple-auth#411]
I am using ember-simple-auth in two applications. Recently, I've noticed that after a successful sign in, the page instantly refreshes (losing the session due to my previous issue storing it in cookies). This doesn't occur in production. I thought it was some weird issue with livereload of the ember server but it disabling it has no effect. As anyone else experienced this issue? Any advice on where this would be happening? I am trying to debug it but my time is really limited right now.

**Comment by thomchop** [comment]
I'm having a similar issue. When the page refreshes local storage is cleared.

**Comment by thomchop** [comment]
I've resolved the issue. In my custom authenticator's restore method I needed to receive the session data as a parameter and then to return a promise that resolves with the data if the session is valid. If the promise doesn't resolve (or resolves with no data), the session store is cleared. Or so it seems.

**Comment by joshpfosi** [comment]
Okay, thanks! This issue actually vanished for me after I reversed through my commit log trying to find where I introduced it. Upon returning all the way back to my master commit, the issue never resurfaced. Now it only occurs occasionally when the ember server has a socket hang up which is strange but likely unrelated.
