### ISSUE TITLE
local-storage for app, ephemeral for mocha

### ISSUE THREAD

**Issue by bjornstar** [simplabs/ember-simple-auth#415]
I'd really like a way to use the ephemeral session store with mocha and local-storage with my app using the same `environment`. Is this possible? I really do not want to have to run my app two different ways to switch back and forth between my app and my tests.

Using the ember test helpers I can setup and tear down an entire ember application with a unique config for every test. I'd love to be able to control simple-auth the same way as my app.

I'm new to ember and spent several hours pulling my hair out trying to configure `simple-cli` from within my mocha tests and eventually gave up on that approach. I ended up adding an initializer that checks the pathname and injects the test config when on the test page but I feel like this approach is more of a hack than anything else.

Any thoughts?

**Comment by marcoow** [comment]
This is really simple to configure with Ember CLI: https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-testing#configuration

**Comment by bjornstar** [comment]
I guess I didn't state my problem clearly enough. I am new to Ember and maybe missing something obvious.

I want to be able to run one server, open my app http://localhost:4200 in one tab using `local-storage` and in another tab open mocha http://localhost:4200/tests using `ephemeral`

Using the environment config will only allow me to use one of those settings.

**Comment by marcoow** [comment]
That would be an issue for https://github.com/ember-cli/ember-cli - to have http://localhost:4200/tests running in `test`environment (which would probably make sense).

**Comment by bjornstar** [comment]
Ok, I'll take it over there. Thanks for your quick response!
