### ISSUE TITLE
Regexp in cookie store read method returns blank value

### ISSUE THREAD

**Issue by Supro** [simplabs/ember-simple-auth#417]
Method is https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-cookie-store/lib/simple-auth-cookie-store/stores/cookie.js#L153
``` javascript
  read: function() {
    var value = document.cookie.match(new RegExp(this.cookieName + name + '=([^;]+)')) || [];
    return decodeURIComponent(value[1] || '');
  },
```
For me, name in read method returns value ``37286``, and regular expression is ``/ember_simple_auth:session37286=([^;]+)/`` but my document.cookie don't contain this value and match returns blank

``` javascript
  ember_simple_auth:session=%7B%22authenticator%22%3A%22authenticator%3Acustom%22%2C%22
```

If I'm removing name from match everything works fine

``` javascript
  read: function() {
    var value = document.cookie.match(new RegExp(this.cookieName + '=([^;]+)')) || [];
    return decodeURIComponent(value[1] || '');
  },
```

Is this bug, or something wrong in my configurations?

**Comment by marcoow** [comment]
Yes, this was a bug - no idea where that `name` var came from.
