### ISSUE TITLE
How to use custom authorizer once defined?

### ISSUE THREAD

**Issue by peyterkim** [simplabs/ember-simple-auth#418]
Once a custom authorizer has been defined and registered? How do you implement the authorization of future requests?

**Comment by peyterkim** [comment]
Is it in the beforeSend hook on the request?

**Comment by marcoow** [comment]
https://github.com/simplabs/ember-simple-auth#implementing-a-custom-authorizer

**Comment by peyterkim** [comment]
But where do I call the authorize method?

**Comment by marcoow** [comment]
You don't call it. You configure the authorizer and Ember Simple Auth calls `authorize` in it.

**Comment by peyterkim** [comment]
Okay, so is there a way to configure the authorizer so that if a request is not authorized, that the user be redirected to a sign in page?

**Comment by marcoow** [comment]
If a request results in a 401 response the `authorizationFailed` session event will be triggered.

**Comment by peyterkim** [comment]
So, I have a custom authorizer below, but how do I check if the request being made returns a 401 or not?

```javascript

var CustomAuthorizer = Base.extend({
	authorize: function(jqXHR, requestOptions) {
		console.log('AUTHORIZING');
		if (this.get('session.isAuthenticated') && !Ember.isEmpty(this.get('session.token'))) {
			jqXHR.setRequestHeader('ApiKey', this.get('session.token'));
		}
	}
});
```

**Comment by peyterkim** [comment]
How can I authorize requests being made in a controller?
