### ISSUE TITLE
Use cookie storage if local-storage is unavailable in the browser.

### ISSUE THREAD

**Issue by bradplank** [simplabs/ember-simple-auth#419]
It would be nice if simple-auth had the ability to use the following test, and a backup store option:
```javascript
try {
    localStorage.setItem("testKey","testValue)");
    // localStorage is supported
} catch (e) {
    // private mode identified... - getting QUOTA_EXCEEDED_ERR: DOM Exception 22
    // set simple-auth to use `simple-auth-session-store:cookie` as the backup store
    session.set('store', 'simple-auth-session-store:cookie');
}
```

**Comment by marcoow** [comment]
I'd say it's up to the application to do exactly this if it needs to support old browsers. Also the cookie store is in an extension library so this wouldn't really be possible in the base library.

**Comment by bradplank** [comment]
Makes sense, the base library would have to fall back to the ephemeral store by default, and possibly the cookie store if configured by the application?

The primary issue is for even fairly new browsers like iOS 7's mobile safari, calling `localStorage.setItem(this.key, data);` in the local-storage.js, persist method causes a JavaScript exception to be thrown.

**Comment by marcoow** [comment]
The application can always change the configuration to use a different store if it detects e.g. `localStorage` isn't available. That's more flexible than doing it in the library automatically and also easier comprehensible if it's done explicitly in the application itself.

**Comment by bradplank** [comment]
No worries, thanks for answering my questions.

**Comment by bretreece** [comment]
>> The application can always change the configuration to use a different store if it detects e.g. localStorage isn't available.

I'm new at Ember and trying to figure how to do this. Any pointers?
