### ISSUE TITLE
restore in custom authenticator does not work with ajax request

### ISSUE THREAD

**Issue by sandreas** [simplabs/ember-simple-auth#420]
I have implemented a custom authenticator, which uses server side sessions. It is possible to delete/invalidate active sessions via an extra admin interface, that has nothing to do with the ember app. In that case i would like to logout the user, if the page is refreshed (via F5). Therefore i need to validate the current session on server side, which means, that i have to store the sessionId in a cookie (amplify.store) and send an ajax request to the server to restore the session after a page refresh.

The following code does not work (no ajax request performed):

```javascript
App.CustomAuthenticator = SimpleAuth.Authenticators.Base.extend({
    tokenEndpoint: '/api/sessions',
    restore: function (data) {
        return new Ember.RSVP.Promise(function (resolve) {
            Ember.$.ajax({
                url: _this.tokenEndpoint + '/' + amplify.store('sessionId'),
                type: 'GET'
            }).then(function () {
                Ember.run(function () {
                    resolve(data);
                });
            }, function (xhr) {
                Ember.run(function () {
                    amplify.store('sessionId', null);
                    reject(data);
                });
            });
        });
    }
});
```

Is there anything wrong with this code?

**Comment by marcoow** [comment]
The authenticator doesn't have an `authenticate` method so the session can never be authenticated with it and so the `restore` method will never be called.

**Comment by sandreas** [comment]
Thank you for the quick answer... I'm very sorry, i should have mentioned that i removed parts of the original code to save space. Here is the complete code... As already said, the restore method does not work with Ajax. The console output is "restore called", but no network traffic or Ajax request is performed. 

```javascript
App.CustomAuthenticator = SimpleAuth.Authenticators.Base.extend({
    tokenEndpoint: location.href + '/api/sessions',
    sessionId: '',
    sessionName: '',
    restore: function (data) {
            console.log('restore called');
	    var _this = this;
		return new Ember.RSVP.Promise(function (resolve) {
            Ember.$.ajax({
                url: _this.tokenEndpoint + '/' + amplify.store('sessionId'),
                type: 'GET'
            }).then(function () {
                Ember.run(function () {
                    resolve(data);
                });
            }, function (xhr) {
                Ember.run(function () {
                    amplify.store('sessionId', null);
                    reject(data);
                });
            });
        });
    },
    authenticate: function (credentials) {
        var _this = this;
        return new Ember.RSVP.Promise(function (resolve, reject) {
            Ember.$.ajax({
                url: _this.tokenEndpoint,
                type: 'POST',
                data: credentials,
                contentType: 'application/json'
            }).then(function (response) {
                Ember.run(function () {
                    _this.sessionId = response.sessions[0].id;
                    _this.sessionName = response.sessions[0].name;
                    resolve({token: _this.sessionId, sessionName: _this.sessionName});
					amplify.store('sessionId', _this.sessionId);
                });
            }, function (xhr, status, error) {
                Ember.run(function () {
                    reject(xhr);
                });
            });
        });
    },
    invalidate: function () {
        var _this = this;
        return new Ember.RSVP.Promise(function (resolve, reject) {
            Ember.$.ajax({
                url: _this.tokenEndpoint + '/' + amplify.store('sessionId'),
                type: 'DELETE'
            }).then(function () {
                resolve();
            }, function (error) {
                reject();
            })
        });
    }
});
```

As you see, the session resource follows the recommendations of jsonapi.org. I would love to use the ember data store for this, but i did not find any hints for that in the documentation or examples.

**Comment by marcoow** [comment]
In general that should work. Have a look at the OAuth 2.0 authenticator, that [makes an AJAX request in its `restore` method](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L104) as well.

**Comment by sandreas** [comment]
I retried and it does not work with ajax for me. It seems that every Ember.$.ajax call breaks the javascript, because console.log output does not show after any Ember.$.ajax (see the bottom of the commented code). BUT: There is no error output...

Performing without ajax works fine and output after resolve works.

Could it be possible, that restore is called before Ember.$ is available and errors are suppressed?

```javascript
App.CustomAuthenticator = SimpleAuth.Authenticators.Base.extend({
    tokenEndpoint: location.href + '/api/sessions',
    sessionId: '',
    sessionName: '',
    restore: function (data) {
            console.log('restore called');
	    var _this = this;
		return new Ember.RSVP.Promise(function (resolve) {
            /*
           // does not work
           Ember.$.ajax({
                url: _this.tokenEndpoint + '/' + amplify.store('sessionId'),
                type: 'GET'
            }).then(function () {
                Ember.run(function () {
                    resolve(data);
                });
            }, function (xhr) {
                Ember.run(function () {
                    amplify.store('sessionId', null);
                    reject(data);
                });
            });
            console.log('this console.log will never show');
             */
            // works like expected
            console.log('try without ajax');
            if( amplify.store('sessionId')) {
                   resolve(data);
            }
            console.log('without ajax worked');
        });
    },
    authenticate: function (credentials) {
        var _this = this;
        return new Ember.RSVP.Promise(function (resolve, reject) {
            Ember.$.ajax({
                url: _this.tokenEndpoint,
                type: 'POST',
                data: credentials,
                contentType: 'application/json'
            }).then(function (response) {
                Ember.run(function () {
                    _this.sessionId = response.sessions[0].id;
                    _this.sessionName = response.sessions[0].name;
                    resolve({token: _this.sessionId, sessionName: _this.sessionName});
					amplify.store('sessionId', _this.sessionId);
                });
            }, function (xhr, status, error) {
                Ember.run(function () {
                    reject(xhr);
                });
            });
        });
    },
    invalidate: function () {
        var _this = this;
        return new Ember.RSVP.Promise(function (resolve, reject) {
            Ember.$.ajax({
                url: _this.tokenEndpoint + '/' + amplify.store('sessionId'),
                type: 'DELETE'
            }).then(function () {
                resolve();
            }, function (error) {
                reject();
            })
        });
    }
});
```

**Comment by marcoow** [comment]
No, that's not possible. `Ember.$` is available at this point. Maybe you can set a breakpoint or add a try catch around the AJAX call or so...

**Comment by sandreas** [comment]
Here is a sample with mockjax that demonstrates the behaviour. I could not use jsbin, because a reload is required to demonstrate the restore...

http://fynder.de/ember-tests/simple-auth-bug.html#/

Howto:
- Click on the button (username and password are prefilled)
- Open Browser Console
- Click on "reload page..." 
- See console output
- Open Page source and view the restore method

Hope it helps to find out, why this fails ;) Sorry for being rigid...

**Comment by marcoow** [comment]
You didn't define `_this` so when it tries to make the request to `url: _this.tokenEndpoint + '/' + …` it fails with _"ReferenceError: _this is not defined"_;

**Comment by sandreas** [comment]
Thank you, I'm so sorry for wasting your time. I don't know why the error did not come up, but now it works. Is there any possibility to donate? It's a great lib.

**Comment by marcoow** [comment]
The beste donation is contribution ;) Pick an issue, submit a PR etc. Thanks!

**Comment by amirshakya2010** [comment]
I tried to call restore method but it says  this.get(...).restore is not a function.

**Comment by marcoow** [comment]
@amirshakya2010: `restore` is private API that you should never call directly.

**Comment by amirshakya2010** [comment]
@marcoow: Can i use auto login with simple auth plugin
