### ISSUE TITLE
sessions controller setup, shouldn't it be user_token instead of token?

### ISSUE THREAD

**Issue by Geokoumpa** [simplabs/ember-simple-auth#421]
I had some trouble persisting session through page reloads. It only worked when I changed server response token to user_token. Is that normal?

**Comment by marcoow** [comment]
I _guess_ this is about the devise authenticator.

If you want people to help you you need to add more info.

**Comment by marcoow** [comment]
The attribute has been renamed to `token` on master but no new version has been released yet so the code that you installed still requires `user_token`. This will change in 0.8.0.
