### ISSUE TITLE
Ensure error is passed through in oath2 authenticator 

### ISSUE THREAD

**Issue by kevinansfield** [simplabs/ember-simple-auth#428]
I had an issue that was made harder to debug due to no error being passed through from the oauth2 authenticators `authenticate` rejection: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L164

The reason I tripped up is that the error message appears on the statusText attribute of the xhr and the stack etc is available on the passed error object but the I was only given `undefined` as there was no `responseJSON` or `responseText`. Would it make sense to pass the error object through in the rejection if the json response is empty?

**Comment by marcoow** [comment]
Maybe it would make sense to change the line to 

```
var reason = ((xhr.responseJSON || xhr.responseText) || xhr.statusText);
reject(reason);
```

**Comment by marcoow** [comment]
closing this for now - PR would be cool.
