### ISSUE TITLE
authorizationFailed function not transitioning

### ISSUE THREAD

**Issue by peyterkim** [simplabs/ember-simple-auth#430]
Everything is working as expected except when it hits the authorizationFailed, the code inside isn't getting executed.
```javascript
    authorizationFailed: function(){
      console.log('authorizationFailed');//the console DOES log this out
      this.get('session').invalidate('authenticator:custom', {});
      console.log(this.get('session')); //still returns authenticated session
      this.transitionTo('index'); //does not transition to index
    }
```

**Comment by marcoow** [comment]
`Session#invalidate` is asynchronous so the session will actually not be invalidated before the returned promise resolves.

**Comment by peyterkim** [comment]
So how would I get that desired effect?

**Comment by marcoow** [comment]
You can simply use the `ApplicationRouteMixin` that implements the `authorizationFailed` action.

**Comment by peyterkim** [comment]
That's what I'm currently doing. Are you saying don't override the method?

**Comment by marcoow** [comment]
Yes, that shouldn't be necessary as what you want to have os the default implementation anyway.

**Comment by peyterkim** [comment]
@marcoow - hmm, it's not getting called.

**Comment by peyterkim** [comment]
Also, I understand why `Session#invalidate` wouldn't get called, but shouldn't `this.transitionTo('index')` still get executed?

**Comment by peyterkim** [comment]
@marcoow any word on this?

**Comment by marcoow** [comment]
Can you give this to Stackoverflow? Doesn't look like this is actually an issue with the library itself.
