### ISSUE TITLE
Retrieving user info after getting successful authenticated token

### ISSUE THREAD

**Issue by chadwtaylor** [simplabs/ember-simple-auth#431]
Was able to implement `ember-simple-auth` with `ember-cli-simple-auth-token` and my API server was able to successfully return a token enabling `session.isAuthenticated` state.

What I am unsure is how one can then proceed to retrieve the authenticated user data (ie: `/users/1`)? A pointer or two would be greatly appreciated.

Thanks,
Chad

**Comment by marcoow** [comment]
Checkout [this example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html#L132). There's also numerous questions and answers about this topic on Stackoverflow.
