### ISSUE TITLE
does simple-auth-devise work on ember 1.7.0

### ISSUE THREAD

**Issue by feitian124** [simplabs/ember-simple-auth#432]
i try use ember 1.7.0 with simple auth 0.7.3 and devise plugin 0.7.3.
the login is all right but the following request didn't set the headers, i saw someone met same  problem and resolved by cross domain white list, i am using --proxy to the server so it should not that problem. 
I cloned the example project, it works well,(it use ember 1.7.0 and auth 0.6.7 howere) then the only difference i can tell is version problems. does `simple-auth` 0.7.3 require higher version of ember?

**Comment by feitian124** [comment]
find the root case, if config `identificationAttributeName: 'username'`, then the server should response `useername` also.

**Comment by hlogmans** [comment]
Whoops, ran into this, too. Because for devise the identificationAttributeName needs to be 'email' instead of user_email. Maybe this should be in the README, because to have email as identification is quite common.
