### ISSUE TITLE
Feature request: async store

### ISSUE THREAD

**Issue by ursm** [simplabs/ember-simple-auth#433]
Hi,
I tried to make simple-auth-chrome-storage-store, but that was difficult. `chrome.storage` has  only async API ([documentation is here](https://developer.chrome.com/extensions/storage#sync-properties)). However, `SimpleAuth.Storage.Base.restore()` expects to return the data immediately.
Are there any plans about this?

**Comment by marcoow** [comment]
No, there are no plans for this but pull requests are welcome.

**Comment by ursm** [comment]
Thank you for your quick reply, I'll try this.
