### ISSUE TITLE
Authorize requests during integration tests

### ISSUE THREAD

**Issue by jme783** [simplabs/ember-simple-auth#434]
Hi there!

I would like to set up a simple integration tests on an authenticated route. This route hits a remote API that uses oAuth to authorize the request. Currently, I am using the `authenticateSession()` method to authenticate properly, but I notice that when the integration tests run there is no `Authorization: Bearer <token>` present in the request, and causes the test to fail.

Is there a way to include a token in an integration test? What is best practice here, is it in fact better to stub out the API call and not actually hit the endpoint used in the ember application? Would greatly appreciate your advice on this. Love the library and thanks!

**Comment by marcoow** [comment]
`authenticateSession` uses a fake authenticator that always resolves restoration, authentication and invalidation. It doesn't add a token or anything to the session. The whole purpose of the helper is to make the session authenticated in the context of the Ember app - it couldn't really add any token or so anyway as it doesn't know what authentication/authorization mechanism you're using outside of the test environment anyway and how that mechanism works/what it requires in terms of tokens etc. (for example OAuth 2.0 works with `access_token` whereas devise works with `token` and `user_email` and these names are also configurable).

I would always stub all API requests in tests anyway. If you have to (or really want to) use actual authenticators/authorizers in tests you should define your own helper.
