### ISSUE TITLE
Can't sign-in when 'identificationAttributeName' is not 'email' and multiple tabs open using devise

### ISSUE THREAD

**Issue by adibsaad** [simplabs/ember-simple-auth#437]
Using 0.7.3. To replicate

1. Have the app open in two tabs
2. Make sure in config/environment.js

```
  ENV['simple-auth-devise'] = {
    tokenAttributeName: 'token',
    identificationAttributeName: 'login'
  }
```

3. Set your back-end up so that this actually works.

4. If a user successfully signs in, it'll sign out after ~0.5 seconds and reloads both tabs.

**Comment by marcoow** [comment]
Cannot reproduce. Are you sure your server correctly responds with

```
{
  "token": "<token>",
  "login": "<login>"
}
```

for `session#create`?

**Comment by adibsaad** [comment]
Hmm... I still have it set it up exactly like I had it before, but I can't replicate it it either. Seems to be working now.

**Comment by marcoow** [comment]
Please reopen if it turns out to actually be a bug in Ember Simple Auth.
