### ISSUE TITLE
After upgrade to 0.7.3: Post parameters for signin mixed up

### ISSUE THREAD

**Issue by AW-UC** [simplabs/ember-simple-auth#441]
I'm using an Simple-Auth/Devise-Rails configuration like https://github.com/givanse/ember-cli-simple-auth-devise. It worked fine with 0.7.2 but with 0.7.3 my Rails server puts:

    Started POST "/users/sign_in" for 127.0.0.1 at 2015-02-16 17:07:03 +0100
      ActiveRecord::SchemaMigration Load (2.0ms)  SELECT "schema_migrations".* FROM "schema_migrations"
    Processing by SessionsController#create as JSON
      Parameters: {"user"=>{"password"=>"[FILTERED]", "user_email"=>"admin@test.de"}}
    Can't verify CSRF token authenticity
    Completed 401 Unauthorized in 33ms
    
I'm aware of the changes in #394 and thought it would be enough to change my session controller accordingly:

    class SessionsController < Devise::SessionsController
      def create
        respond_to do |format|
          format.html { super }
          format.json do
            self.resource = warden.authenticate!(auth_options)
            sign_in(resource_name, resource)
            data = {
                token: self.resource.authentication_token,
                user_email: self.resource.email,
                user_id: self.resource.id
            }
            render json: data, status: 201
          end
        end
      end
    end
    
However, this does not help. Any breaking changes I missed?

**Comment by AW-UC** [comment]
**Update:**
Reverting back to 0.7.2 makes the login working again. Now, my server puts:

    Started POST "/users/sign_in" for 127.0.0.1 at 2015-02-16 17:21:24 +0100
    Processing by SessionsController#create as JSON
      Parameters: {"user"=>{"email"=>"admin@test.de", "password"=>"[FILTERED]"}}
    Can't verify CSRF token authenticity

So, that `Can't verify CSRF token authenticity`-part seems not to be the problem. But `email` and `password` elements are reversed in the parameter hash. How did that come?

**Comment by AW-UC** [comment]
Ok, i see it is because of #403. Is the change of the order intended?

**Comment by marcoow** [comment]
@AW-UC: the fact that the order has changed is just a side effect of #403. I'm not sure why that breaks CSRF protection for you.

**Comment by AW-UC** [comment]
@marcoow Even stranger, that login works in 0.7.2 despite `Can't verify CSRF token authenticity` message.

**Comment by marcoow** [comment]
Is the Ember Simple Auth version actually the only difference between the working and non working versions here? Seems kind of unlikely that a change of parameter order could lead to the described behavior.

**Comment by AW-UC** [comment]
Well, I updated ESA when also updating ember-cli from 0.1.4 to 0.1.15. But ESA 0.7.2 works fine with EC 0.1.15.
I further traced the problem: The order of parameter in the data hash is indeed irrelevent. But is doesn't work with `user_email` only with `email`. After changing lines 134-137 of 0.7.3's `simple-auth-devise.amd.js` to the following, login works again:

    data[_this.resourceName] = {
      email: credentials.identification,
      password: credentials.password
    };

What also works is leaving that file as it is and setting `identificationAttributeName: 'email'` in `environment.js`. Somehow similar to #437. This is strange, because all Devise-related settings in the rails app us `user_email`. I guess https://github.com/givanse/ember-cli-simple-auth-devise would depend on setting `identificationAttributeName: 'email'` as well.

**Comment by medemas** [comment]
Thank you, @AW-UC!!! I've been going crazy trying to figure this out, for an interview project due on Monday.

Just to be clear, in lines 134-137 of 0.7.3's `simple-auth-devise.amd.js` there was not any property set for `credentials.identification` at all. So, what I found was:
```
data[_this.resourceName] = {
  password: credentials.password
};
```
I added in `email: credentials.identification` to get things working. Thanks for the clue!

Things are working now, but I am still seeing `Can't verify CSRF token authenticity` showing within each Rails log, even on successful logins. Is this a benign bug, or is something crucial still not working correctly?

**Comment by marcoow** [comment]
@AW-UC, @medemas: sounds like your problems are caused by the server expecting the user identification being sent as `email` while Ember Simple Auth [defaults to `user_email`](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/lib/simple-auth-devise/configuration.js#L7). Configuring `identificationAttributeName` to be `email` should fix it. Can you verify that's correct and this can be closed?

**Comment by AW-UC** [comment]
Yes, as I said in my post above, configuring that value fixes it. I just thought that ESA's behaviour of defaulting to `user_email` was supposed to make it work more or less out of the box with device. If I need to seet that config value, I'm happy with it, too.
@medemas That code change was just for debuging. Don't apply it. Just change the config.

**Comment by AW-UC** [comment]
That `Can't verify CSRF token authenticity` warning is still there, though. But this would be a new issue I guess.

**Comment by marcoow** [comment]
@AW-UC: is the CSRF token actually included in the request? That's not sth. Ember Simple Auth does. 

Also I think devise doesn't token Auth out of the box Sinai don't think there's a default for the user identification argument.

**Comment by AW-UC** [comment]
Allrigt, then I misunderstood the intend of the PR. However, I think it definately necessary to update https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/README.md, because the suggested way to setup Devise with Rails will depend on also setting `identificationAttributeName`.
The CSRF token is indeed not included in the request. I traced the cause of the `Can't verify CSRF token authenticity` warning to one line in my Rails-app's `application_controller.rb`:
If it includes

    protect_from_forgery with: :null_session
the warning is shown. That setting returns an empty session to an unverified request, instead of reseting the session. It is the recommended setting for APIs: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/app/controllers/application_controller.rb.tt
Not sure whether it safe to remove it, though. Maybe add the use of an API key then, to make it safer?
tl;wr, this issue can be closed, unless you want to keep it until https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/README.md is updated.

**Comment by marcoow** [comment]
Not sure why you suggest the README should be updated - it uses `user_email`, which is also the default value of `identificationAttributeName`.

If the CSRF token isn't included in the request then the error you're seeing is expected of course - closing this. You can use e.g. https://github.com/abuiles/rails-csrf to automatically include the CSRF token in requests.

**Comment by AW-UC** [comment]
@marcoow Well, I'm following exactly the suggestions of the README, so I also use `user_email`. That is what baffled me in the first place, because I still need to set `identificationAttributeName` to `email`. So, I still think the README has to be updated or this issue is indeed a bug.

**Comment by marcoow** [comment]
Please post requests, responses for your login requests.

**Comment by AW-UC** [comment]
The post request params:

    user[email]    admin@test.com
    user[password]    test
The request headers also include a session cookie. Can this be correct? It looks like

    _test-app_session=Yzg5....

The response:

    {"token":"axXE2XwyNLVY3z82ytDu","user_email":"admin@test.com","user_id":1}

There is no login error. However, I have to do this in my Rails-apps session_store.rb

    Rails.application.config.session_store :cookie_store, key: '_test_app_session'
instead of 

    Rails.application.config.session_store :disabled
to persist the login. Is this related to that session cookie?
If I remove `identificationAttributeName: 'email'` I get for the post request:

    user[password]    test
    user[user_email]    admin@test.com

and response:

    devise.failure.user.unauthenticated
Any ideas?

**Comment by marcoow** [comment]
I don't get how this is a bug. When you configure `identificationAttributeName: 'email'` the email is sent as `user[email]`, if you configure it as `'user_email'` it is sent as `user[user_email]`. That's as expected.

It seems your Rails app expects `user[email]` as input but responds with `user_email` though - you'd have to decide on one.

**Comment by AW-UC** [comment]
Yes, probably not a bug. I just thought if you follow the suggestions of https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/README.md that would already setup the rails app to expect `user_email` instead of `email`. Maybe I just misunderstood that.
What to you think about needing

    Rails.application.config.session_store :cookie_store, key: '_test_app_session'
in my `session_store.rb`?

**Comment by marcoow** [comment]
As far as I see the README uses `user_email` everywhere - I really don't understand the problem here. Ember Simple Auth has ne dependency on any Rails session mechanism so your setting should be irrelevant.

**Comment by AW-UC** [comment]
Yes, the README uses `user_email` everywhere. And my app also uses `user_email` everywhere. In fact all files of my app are like the files in the README. Still need to set `identificationAttributeName` though. I just thought I wouldn't need this, but apparently I was wrong.
As for the sessions, I agree that it is strange, but the setting does matter. Of course, that might be an issue not related to ESA.

**Comment by hlogmans** [comment]
Well, quite some misunderstanding here :) Gladly the hints in the various comments helped me to get things running: for Devise I also need to change 'user_email' to 'email' in the config initializer. And without the cookies the session is lost immediatly. The local store does not seem to solve this. So I'm a bit confused why I need to disable the cookies, as explained in the readme.

**Comment by marcoow** [comment]
The easiest solution to this is to either leave Ember Simple Auth's configuration with the default values and make sure the server uses `user_email` everywhere or to make sure the server uses `email` everywhere and change Ember Simple Auth's config accordingly.

If the session is only persisted when the Rails app uses session cookies that does mean the Ember Simple Auth/Devise integration doesn't work at all!

**Comment by hlogmans** [comment]
@AW-UC see this issue: https://github.com/simplabs/ember-simple-auth/issues/432
After changing the code I could set it to disabled.

**Comment by AW-UC** [comment]
@hlogmans great! what exactly did you change?

**Comment by AW-UC** [comment]
Alright, I just noticed that I have an additional issue here. I defined a custom session for Ember Simple Auth. If I use that custom session I need:

    Rails.application.config.session_store :cookie_store, key: '_test_app_session'
If I don't use it, I can go with:

    Rails.application.config.session_store :disabled
Actually, that custom session just extends Ember Simple Auth's session and really shouldn't mess with! @marcoow Any ideas.

**Comment by marcoow** [comment]
If you need `Rails.application.config.session_store :cookie_store, key: '_test_app_session'` that means that requests aren't actually authorized by Ember Simple Auth but by Rails' session cookie which means sth. is wrong with your custom session mist likely.

Please move this to Stackoverflow though as it develops into a more general discussion of diverse questions...

**Comment by AW-UC** [comment]
@marcoow thanks for your help so far :) here is the Stackoverflow question, if you are interested: http://stackoverflow.com/questions/28702988/ember-cli-simple-auths-custom-session-for-a-rails-api-depends-on-rails-session

**Comment by michaeldeitcher** [comment]
If the default behavior is to send the email as 'user_email' instead of just 'email' does anyone know how to configure devise to match this behavior? Thanks in advance.

**Comment by hlogmans** [comment]
@michaeldeitcher, it is much easier to change it the other way around: simple auth settings for devise can be changed in the config, the main problem was that your rails app you have to update your session controller like in the docs, but you have to change user_email to email there as well.

  def create
    super do |user|
      data = {
        token:      user.authentication_token,
        email: user.email
      }
      render json: data, status: 201 and return
    end
  end

**Comment by michaeldeitcher** [comment]
Ok I changed it by setting the ember-simple-auth-devise configuration in my config/environment.js file and everything is working swimmingly for me. Thanks!

  ENV['simple-auth-devise'] = {
    identificationAttributeName: 'email'
  };

**Comment by jakekdodd** [comment]
I just spent some time working through this after upgrading to 0.7.3 from 0.6.7, and I'm still trying to get everything working.

@marcoow I think the confusion is that people expect ESA-Devise to work out of the box with Devise. But it doesn't, because if you configure Devise using the instructions in the README, Devise expects the identification to be `email`, and not `user_email`. Therefore, as several people have mentioned, you need to set `identificationAttributeName: 'email'` in `environment.js`. This is the update to the README that @AW-UC mentioned, and I think it's warranted.

**Comment by AW-UC** [comment]
Well, it all depends on how you configured your user model in Rails. Indeed, the model generated by Devise with e.g. `rails generate devise User` will use `email` and not `user_email`. That is why you will need to set `identificationAttributeName: 'email'`. Of course, you could also change the rails migration file prior to migrating.

**Comment by fivetwentysix** [comment]
I have to agree with @jakekdodd, this is confusing.

**Comment by jakekdodd** [comment]
@AW-UC Convention over Configuration means that the vast majority of users will have `email` and not `user_email` as their authentication field. 

The new `identificationAttributeName` is a great feature, but sane defaults should work out of the box with Devise.

@marcoow This seems to be the thing that's tripping people up:

```ruby
class SessionsController < Devise::SessionsController
  respond_to :html, :json

  def create
    super do |user|
      if request.format.json?
        data = {
          token:      user.authentication_token,
          user_email: user.email
        }
        render json: data, status: 201 and return
      end
    end
  end
end
```

seems to return `401` if `identificationAttributeName` is set to `user_email` and your Devise authentication field is `email`, regardless of whether you've configured your API to consistently use `user_email`. I'll see if I can produce a reduced example to demonstrate the regression.

**Comment by marcoow** [comment]
I see how this causes a lot of confusion. I guess the best fix would be to change `identificationAttributeName`'s default to just `email` and update the [README](https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise#server-side-setup) accordingly.

**Comment by AW-UC** [comment]
@marcoow yes, that would certainly be best, because hardly anyone will use `user_email` instead of `email` with devise.

**Comment by AW-UC** [comment]
@marcoow just ask for a hand on this, if you don't feel like doing the commit yourself.

**Comment by marcoow** [comment]
@AW-UC: sure, go ahead and open a PR - should be pretty simple.
