### ISSUE TITLE
Q. How to i listen for the sessionDataUpdated  trigger?

### ISSUE THREAD

**Issue by shopapps** [simplabs/ember-simple-auth#443]
Hi,

In your refreshAccessToken method of the oauth2 module,  I can see there is a trigger fired:

_this.trigger('sessionDataUpdated', data);

would you be able to show a simple example of how how i could listen for that trigger, so that I can react to it accordingly?  At the moment I have copy/pasted the oauth2 authnticator script and placed it in authenticators/custom.js to allow me to play with it, but cant seem to be able to listen for the sessionDataUpdated trigger?

thanks.

**Comment by marcoow** [comment]
The session listens to `sessionDataUpdated`, it's not actually a public event. Observing updates of session properties can simply be done with regular Ember observers.

Please ask questions like this on Stackoverflow though.
