### ISSUE TITLE
sessionInvalidationSucceeded causes page refresh

### ISSUE THREAD

**Issue by michaelBenin** [simplabs/ember-simple-auth#445]
https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L200

I'd like to invalidate session without a page refresh, is this possible?

**Comment by marcoow** [comment]
Just define your own `sessionInvalidationSucceeded` action on your application route that overrides the one from `ApplicationRouteMixin`.

**Comment by michaelBenin** [comment]
Awesome, thank you so much. Great library!
