### ISSUE TITLE
Invalid login credentials shouldn't cause a promise rejection

### ISSUE THREAD

**Issue by theazureshadow** [simplabs/ember-simple-auth#449]
Promise `reject` should really be used in exceptional situations, not in normal flow, but the authenticators in ember-simple-auth reject when the username and password are invalid (which is normal and expected). Example in [oauth2](https://github.com/simplabs/ember-simple-auth/blob/3d6bd48e5efc89f761023f5b234824eccd1b3ab5/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L143).

    @return {Ember.RSVP.Promise} A promise that resolves when an access token
        is successfully acquired from the server and rejects otherwise

We collect statistics about promise rejection in order to track down bugs, and this is a major source of noise.

To work around this, we had to add our own `authenticate` action and use a `_super()` call to get access to the actual promise and `catch` it there (so it doesn't bubble up to our promise failure handler). If there's a better workaround, that would be helpful as well.

**Comment by marcoow** [comment]
As far as I understand them, promises are simply a mechanism to handle operations that will asnynchronously succeed or fail. And in the case of authentication, invalid credentials are one (of many) failure cases. 

Also, the use of rejected promises for these things couldn't be changed in ESA anyway as the whole library is built around that concept.

**Comment by theazureshadow** [comment]
@marcoow: Thanks for your response. Is the approach I described the best way to discard the promise rejection safely? I'd prefer some sort of hook so I can let ESA's magic fully handle authentication, rather than intercepting the action, attaching a `reject` handler, and re-triggering it.

Using `reject` only in exceptional situations is part of [the w3c's recommendations for the use of promises](http://www.w3.org/2001/tag/doc/promises-guide#rejections-should-be-exceptional), but of course it is a library's decision whether a `403` is considered an "exceptional" situation -- and I can totally see the argument in this case.

**Comment by marcoow** [comment]
You can not change e.g. the authenticator's `authenticate` method so that the returned promise will never reject as the session does certain things in that case (see e.g. [here](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L165)). Of course you could attach sth. to the promise that prevents it from being counted in the statistics or so…
