### ISSUE TITLE
default oauth2-bearer authorizer doesn't work with torii

### ISSUE THREAD

**Issue by albertjan** [simplabs/ember-simple-auth#452]
The torii provider returns content to the session containing a `authorizationCode` in most cases (accept for `facebook-connect` that uses `accessToken`). The oauth2-bearer authorizer looks for a property called `access_token`.

@marcoow Would you consider a PR adding a `torii-oauth2-autorizer` and maybe a `torii-fb-connect-authorizer`? Or one that catches both cases? The twitter oauth1 response token is in `oauth_token` I think. But I have no experience with that

**Comment by marcoow** [comment]
In general, the authenticator and authorizer have to fit together as the authorizer uses data that the authenticator retrieves from some source. As the torii authenticator connects with various sources and doesn't actually know what the data it gets looks like, it's not actually possible to have a torii authorizer that works with all sorts of torii authenticators. That's the reason why no authorizers exist in the torii package.

Providing all sorts of authorizers for all sorts of torii providers is beyond the scope of the library. Ember Simple Auth provides a clear interface for creating these authorizers (which also requires almost no code).

**Comment by albertjan** [comment]
Might be a good idea to add to the docs that you have to write your own authorizer when using torii.

**Comment by marcoow** [comment]
Sure, PR welcome.
