### ISSUE TITLE
Unwanted redirect to index page after successful login

### ISSUE THREAD

**Issue by joshpfosi** [simplabs/ember-simple-auth#454]
I've recently started experiencing a strange issue using this library. After I successfully authenticate a session, I would like to redirect to a specific page, but for some reason I am always redirected to the index page. Anyone else having this issue?

Relevant files and versions:

```javascript
// routes/application.js
import Ember from 'ember';
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  beforeModel: function() {
    // ensure transition attempt it made, so sessionAuthenticatedRoute can retry
    this._super();
    return this.csrf.fetchToken();
  }
});
```

```javascript
// routes/signin
import Ember from 'ember';

export default Ember.Route.extend({
  actions: {
    sessionAuthenticationSucceeded: function() {
      var route = this;
      //route.transitionTo('testz');
      //this.store.find('user', this.get('session.id')).then(function(user) {
      //  route.transitionTo('testz');
      //}, function() {
      //  console.log("failed to find user");
      //  route.transitionTo('index');
      //});
    },
    sessionAuthenticationFailed: function() {
      this.controllerFor('signin').set('credErrors', true);
    }
  }
});
```

```javascript
// bower.json
{
  "name": "shearwater",
  "dependencies": {
    "handlebars": "~1.3.0",
    "jquery": "2.1.3",
    "ember": "1.8.1",
    "ember-data": "1.0.0-beta.14.1",
    "ember-resolver": "~0.1.11",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "rwjblue/ember-cli-test-loader#0.0.4",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.4",
    "qunit": "~1.15.0",
    "ember-simple-auth": "0.7.2",
    "bootstrap": "~3.3.1",
    "spin.js": "~2.0.2",
    "materialize": "~0.95.0"
  },
  "resolutions": {
    "jquery": ">=2.1.1"
  }
}
```

**Comment by joshpfosi** [comment]
After upgrading to 0.7.3 I am experiencing issues due to #403. Working to resolve them by adding `identificationAttributeName: 'email'` to my `config/environment.js` but this isn't working. I'm going to leave the issue open until I resolve the strange redirection but got to muddle through this first!

**Comment by marcoow** [comment]
Use [this configuration setting](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Configuration-routeAfterAuthentication) to specify the route you want to be redirected to after authentication.

Your comment is unrelated to this issue of course.

**Comment by joshpfosi** [comment]
Was not aware of that option. Can that be set dynamically depending on the session returned?

**Comment by marcoow** [comment]
If you want dynamic redirects you should implement your own [`sessionAuthenticationSucceeded` action](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-ApplicationRouteMixin-sessionAuthenticationSucceeded).

**Comment by joshpfosi** [comment]
That's what I thought. I did that (as in the snippet above), but still was redirected afterward.

**Comment by joshpfosi** [comment]
To confirm, after updating to 0.7.3 I am still experiencing this issue.

**Comment by marcoow** [comment]
You need to implement `sessionAuthenticationSucceeded` on he application route.

**Comment by joshpfosi** [comment]
Doing so still results in the redirect :(

**Comment by ninja-** [comment]
@joshpfosi I am experiencing the same thing (?). After logging in, I see the index controller and it refreshes to "/" url after 0.5s. Have you figured it out?

**Comment by joshpfosi** [comment]
I haven't! Its an intermittent problem that is currently resolved. I'll let you know if it happens again and if I make any headway!

**Comment by ninja-** [comment]
@joshpfosi in my case it was something related to invalid configuration of devise. I don't remember exactly, but I fixed it.
