### ISSUE TITLE
Could not find module on new ember install

### ISSUE THREAD

**Issue by joshhornby** [simplabs/ember-simple-auth#463]
I have a brand new ember-cli app with the following versions:

```bash
version: 0.2.0
node: 0.12.0
npm: 2.7.0
```

I have followed the commands outlined in the readme:

```bash
npm install --save-dev ember-cli-simple-auth
ember generate ember-cli-simple-auth
```

This then adds the following onto my package.json

```json
"ember-cli-simple-auth": "^0.7.3",
```

I then add the following code into my router.js:

```js
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';
```
The error is:

```
Uncaught Error: Could not find module `simple-auth/mixins/application-route-mixin` imported from `my-app/router`
```

Like I mentioned above this is a fresh ember app so I was surprised to see this error, am I doing something silly?

**Comment by marcoow** [comment]
You should use the newer `ember install:addon ember-cli-simple-auth` command. However, running the installation and generation individually should still work. Can you make sure `"ember-simple-auth"` is in your `bower.json` after running the generator?

**Comment by joshhornby** [comment]
Ah yes this fixed the issue. 

It was in the bower.json before but after running this command it seems to fix my issue. Thanks.

**Comment by rtm** [comment]
I am having the same problem using ember-cli 0.2.3.

After running `ember install ember-cli-simple-auth`, I see `ember-cli-simple-auth` in my `package.json`, and `ember-simple-auth` in my `bower.json`. Inside `bower_components`, I see `ember-simple-auth` with files such as `simple-auth.js`. However, the import

    import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';

fails with the same error reported above:

     Uncaught Error: Could not find module `simple-auth/mixins/application-route-mixin` imported from `frontend/application/route`

I'm confused by where the `simple-auth` being imported is supposed to be found. There is no directory called `simple-auth` anywhere within my tree including dependencies.

**Comment by devinrhode2** [comment]
Hmmm.. getting this again on ember-cli 1.13.13. Ember install ember-simple-auth adds this entry to the package.json: "ember-simple-auth" but there is not bower package that gets installed or added to the bower.json.

**Comment by devinrhode2** [comment]
I see I just need to follow the proper steps to update to 1.0 http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10
