### ISSUE TITLE
Authorizer not active?

### ISSUE THREAD

**Issue by deepflame** [simplabs/ember-simple-auth#466]
I wanted to implement a custom token authentication mechanism and saw that "the right way" to do this in SimpleAuth is to implement a custom authorizer.

I did this and can see in the Ember-Inspector that an instance of the authorizer is in the container.
When I now make AJAX requests the authorizer is not being used.

Is the authorizer only working in model-hooks? I do AJAX requests within the controller...

Any idea what I could debug? Otherwise I would move the code over to the authenticator...

**Comment by deepflame** [comment]
I use 'Ember.$.getJSON' or 'Ember.$.ajax' and it does **not** fire inside the app. When I try it in the debugging console however it works and it halts at my debugger statement.

Any idea?

**Comment by deepflame** [comment]
Think the problem is that I do requests in my components as well. Then I do a request in the model hook of the route it is working fine.

**Comment by marcoow** [comment]
Do your AJAX requests go to a different origin maybe and you didn't whitelist that origin in Ember Simple Auth's config?

**Comment by deepflame** [comment]
thanks for the suggestion. I will check this later.

**Comment by marcoow** [comment]
@deepflame: any updates?

**Comment by marcoow** [comment]
Please reopen if it's still an issue.

**Comment by deepflame** [comment]
it is still an issue but did not find the time yet to check further. I added the code now to the authenticator and it is working as well. Maybe the problem is that I use the components from an Ember Addon. These components internally request an API, but this request is not going through the authenticator (?).

Thanks for the input. I will reopen if this gets important again.
