### ISSUE TITLE
Add access_token to URL

### ISSUE THREAD

**Issue by felixkiss** [simplabs/ember-simple-auth#470]
I have a model `invoice` with a property `pdfUrl` that points to the PDF version of the invoice.

```js
import DS from 'ember-data';

export default DS.Model.extend({
  // ...
  pdfUrl: DS.attr('string')
});
```

The URL is presented as a link to the user (`target="_blank"`).

Because the link is handled by the browser and not Ember, the `Authorization: Bearer xxx` is not included in the headers.

Since emper-simple-auth also allows the access_token to be included via query parameter, I think there has to be a way to get the token and add it to the URL.

Something like this:
```js
  pdfUrlWithAccessToken: function() {
    var token = ?;
    return this.get('pdfUrl') + '?access_token=' + token;
  }.property('pdfUrl')
```

How would you approach this?

**Comment by marcoow** [comment]
You could inject the session into the model but I wouldn't suggest that. The better solution is probably to generate the URL in the controller or component where the session is available anyway. Also that's the better separation of concerns.

**Comment by felixkiss** [comment]
Ok, I now generate the URL in the controller (`controllers/invoices/create.js`):

```js
import Ember from 'ember';

export default Ember.Controller.extend({
  pdfUrl: function() {
    return this.get('model.pdfUrl') +
           '?access_token=' + this.get('session.access_token');
  }.property('model.pdfUrl', 'session.access_token'),
});
```

But how would you do it in `controllers/invoices/index.js`? (i.e. for a list of invoices)

And how would I inject the session into the model? How is DI (http://emberjs.com/guides/understanding-ember/dependency-injection-and-service-lookup/) done in ember-cli?

**Comment by marcoow** [comment]
The best solution would probably be to use a component for displaying each component and inject the token into the URL there. Also that way you would reuse the same logic for single and collection routes.

Injecting the session into the model would work like this:

```js
container.injection('model:invoice', 'session', 'simple-auth-session:main');
```

but I wouldn't suggest doing that.
