### ISSUE TITLE
Devise: session not invalited serverside

### ISSUE THREAD

**Issue by ninja-** [simplabs/ember-simple-auth#471]
I am trying to follow the official way to use devise.
The problem I see is that after calling 'invalidateSession' you are properly logged out even after refreshing the page - clientside.
But...if you try then to login with random user & password '/sign_in' will return your user data, just like if you were still logged in. And log you in.

EDIT:
Soo...I see that readme mentions this problem.
But disabling cookies is not a proper fix.
https://github.com/plataformatec/devise/blob/master/app/controllers/devise/sessions_controller.rb#L16
We just need to override more, adding store: false to authenticate() call

**Comment by ninja-** [comment]
Actually....here's my fully working solution. README's update would be welcome

```ruby
class SessionsController < Devise::SessionsController
  respond_to :html, :json

  def create
    super do |user|
      if request.format.json?
        data = {
          token: user.authentication_token,
          email: user.email
        }
        render json: data, status: 201 and return
      end
    end
  end

  def auth_options
    super.merge! store: false
  end
end
```

**Comment by marcoow** [comment]
I think that should be


```ruby
def auth_options
  if request.format.json?
    super.merge(store: false)
  else
    super
  end
end
```

Can you verify that works and submit a pull request?

**Comment by ninja-** [comment]
@marcoow no, actually  the
```ruby
  before_filter :authenticate_user!
```

part needs to be removed too together with all other stuff relating to html

**Comment by marcoow** [comment]
@ninja- I'm pretty sure the only thing you need to make sure is that no cookie gets set for JSON requests.

**Comment by marcoow** [comment]
@ninja- any updates?

**Comment by ninja-** [comment]
@marcoow my setup works great for me. are you asking about PR for documentation's update or something else?

**Comment by ninja-** [comment]
I noticed one thing, without cookies the session doesn't stay  after page refresh. How to solve it?

**Comment by givanse** [comment]
I remmember a similar discussion here https://github.com/simplabs/ember-simple-auth/issues/201 and here https://github.com/simplabs/ember-simple-auth/issues/204

**Comment by marcoow** [comment]
> @marcoow no, actually the
>  before_filter :authenticate_user!
> part needs to be removed too together with all other stuff relating to html

if that's the case it probably means that your server is responding with a token for JSON session creation requests as well as issuing a session cookie which it shouldn't. Please check whether after logging in you have a Rails session cookie in the browser.

**Comment by ninja-** [comment]
@marcoow, what are you referring to? Yes I do indeed have a session cookie, but I am using session for other stuff. The 'logged in' status is not saved in the session.

**Comment by marcoow** [comment]
@ninja-: I see. However, you don't actually want to use a session for REST APIs as you want that to be stateless. Also if `authenticate_user!` redirects users that are not logged in to a specific page also for JSON requests that's actually wrong. You should instead only do that for HTML requests.

**Comment by BenMorganIO** [comment]
For logout, why not just submit a `DELETE /logout`?

I'm currently dealing with a Spree implementation. the Admin requires the token to be stored. No if, maybes, or buts. I've already tried.

If you do the `DELETE /logout`, then you're left with one last issue: refreshing the page and discovering you've been "logged out", when you're not...

How does devise store the session? I believe its a cookie. What if we searched instead for the applications session cookie instead of hacking around to set an authentication token.

I'm willing to work with the current workflow, but the application I'm working on is a Spree app. I currently do not have the luxury to manipulate the `Spree::UserSessionsController` or the `Devise::SessionsController` even to the level that Ember Simple Auth requires of me.

**Comment by marcoow** [comment]
@BenMorganIO: if you have a server session that's stored in a cookie you don't actually need most of ESA (especially the authorizer that adds the `Authorization` header etc.) as the cookie is sent with each request anyway.

Usually when implementing a REST backend you don't want to use a session cookie though as that adds state to the API. When using token based authorization instead for logging out it's sufficient to delete the token client side as that effectively logs the user out as no more authorized requests can be made as the authorization secret isn't known anymore.

What you and @ninja- seem to be trying to do is to make Ember Simple Auth work with a classic server session based backend which is just not what the library is built for. Of course you can extend the authenticators etc. to make it work but essentially the library is built to work with stateless (= no session cookie) REST backends.

**Comment by BenMorganIO** [comment]
@marcoow merci. This makes sense.

I don't think I have enough Ember knowledge to roll my own Devise + Spree + Ember library. You wouldn't happen to be able to provide a simple example?

**Comment by marcoow** [comment]
@BenMorganIO: check out the examples folder - there's a very simple example for the devise package as well. Basically the one thing you have to make sure on the server side is that you don't create a session cookie (and no session in general) for any API requests and also only use the `Authorization` header to authorize API users.

**Comment by Leooo** [comment]
I didn't manage to make any of the solutions above work on my side: the session just keeps being valid. I'm converting to Ember a Rails app where I was heavily using the session, and I don't want to get rid of authenticate_user! hooks at this stage.

What i did was adding a before_filter to sign out the user when the Authentication header is not correct. This seems to work well at this stage. +1 for better solutions to ember-simple-auth for making sure that devise doesn't persist the current user in the session (other than just getting rid of the whole session).

````javascript
class ApplicationController < ActionController::Base
  before_filter :authenticate
  before_filter :authenticate_user!

  (..)

  private

    def authenticate
      authenticate_user_from_token || render_unauthorized
    end

    def authenticate_user_from_token
        authenticate_with_http_token do |token, options|
          user_email = options[:email].presence
          user2= user_email && User.find_by_email(user_email)

          if user && Devise.secure_compare(user.authentication_token, token)
            sign_in user, store: false
            @current_user=user #for devise current_user helper
            return true
          end
        end
      end
      def render_unauthorized
        sign_out(current_user) if !current_user.blank?
      end
    end
end
````
