### ISSUE TITLE
`controller.transitionTo` is deprecated

### ISSUE THREAD

**Issue by geoffreyd** [simplabs/ember-simple-auth#472]
I'm running Ember 1.10 and it's giving me

    DEPRECATION: transitionTo is deprecated. Please use transitionToRoute.

This is coming from the controller mixins (specifically the `authenticateSession` action). Only routes should be calling `transitionTo`

**Comment by marcoow** [comment]
Ember Simple Auth [doesn't call `transitionTo` in controller mixins](https://github.com/simplabs/ember-simple-auth/search?utf8=✓&q=transitionTo) - maybe you're mixing in one of the route mixins into a controller?

**Comment by geoffreyd** [comment]
My apologies, I thought I had checked that, but there was one that slipped in. Thank you.
