### ISSUE TITLE
Links active class not set after successful login

### ISSUE THREAD

**Issue by engwan** [simplabs/ember-simple-auth#473]
I'm not sure this is an ember-simple-auth issue.

More info here: http://stackoverflow.com/questions/29250684

This only happens when this is called:

    attemptedTransition.retry();

and not when this is called:

    this.transitionTo(Configuration.routeAfterAuthentication);

**Comment by marcoow** [comment]
This is most likely not an Ember Simple Auth issue - please reopen if it actually turns out to be one.

**Comment by engwan** [comment]
So I did more investigation into Ember's source code and I logged the parameters to `isActiveIntent` which is called to check if the current link is active.

It seems that the link's route is compared against `application/login` instead of the retried transition's route which is `application/index`

So I guess it's a bug with Ember's retrying of transitions that doesn't update the state properly.

**Comment by marcoow** [comment]
Yes, looks like it. I'd suggest you open an issue on emberjs/ember.js.

**Comment by engwan** [comment]
Yeah, I checked their issues and indeed found these:

https://github.com/emberjs/ember.js/issues/5208

https://github.com/emberjs/ember.js/issues/10557

**Comment by mattcoker** [comment]
Just for anyone that stumbles across this in the future, here is a workaround for redirection on authentication. Rather than rely on the `routeAfterAuthentication` configuration setting, you can manually handle this with the following in your authentication action:

    authenticate: function() {
        let credentials = this.getProperties('identification', 'password');
        this.get('session').authenticate('authenticator:jwt', credentials).then(() => {
            this.transitionToRoute('protected');
        }).catch();
    }
