### ISSUE TITLE
How to know when simple auth is restoring

### ISSUE THREAD

**Issue by varblob** [simplabs/ember-simple-auth#475]
I would like to put up a loading state when the session is restoring but looking through the docs / code I can't find any hooks for when simple auth is restoring.  

Am I missing something?

**Comment by marcoow** [comment]
There is no event for that? What's the use case for this?

**Comment by varblob** [comment]
Thanks for getting back so quick.

What I would like to do is show a popup that says "restoring your session..." while the session is restoring.

**Comment by marcoow** [comment]
Is that when the app initially loads or when the session changes while the app is running? Also what authenticator do you use (because restoring would only take moments usually)?

**Comment by varblob** [comment]
I'm using the restore both when they hit the first authenticated route and if the session times out midway through.  I started with the devise authenticator but I ended up writing my own auth service yesterday that uses devise.  Reading through this lib was extremely informative in that regard.  The time it takes to restore is not normally that much but I wanted to handle the case of if it was longer since the internet is rather unpredictable especially on mobile.

**Comment by marcoow** [comment]
The `restore` method is also called whenever __anything__ in the session changes and the authenticator has to decide whether the session is still valid. Showing sth. in the UI whenever that happens would most likely lead to that thing being displayed in cases where you would not actually want that. Also the default devise authenticator never makes any AJAX calls during session restoration but only checks for the presence of 2 keys in an object which will always be fast.

**Comment by varblob** [comment]
aha, that is good to know, I misunderstood restore.
I've already taken a different path with my own auth service but I'm going to close this issue since I think this would have resolved it if I were still using simple-auth.
