### ISSUE TITLE
How can I fix warning - Cannot find module "simple-auth/mixins"?

### ISSUE THREAD

**Issue by rvan1** [simplabs/ember-simple-auth#476]
I'm working on an ember app, developed with the old EAK and grunt (now updated for ember 1.10 and HTMLBars), which includes "ember-simple-auth": "~0.6.2" as a bower dependency, and clarifies how the developer was intending to implement authorization. So I've been looking at the git project & blogs and examples. The app had a 'login' route so I've added the loginForm template and LoginIndexController with 'authenticate' action. I've been trying to import the 'convienience mixins', but grunt build 'can't find module simple-auth/mixins/application-route-mixin'.

I've tried including (script src) '/vendor/ember-simple-auth/simple-auth.js' in index.html, but I get a warning that 'simple-auth' is already registered. I can see in this file that it 'exports' the mixins, so seems I need a loader or initializer.

The project from git includes 'lib' in 'packages' and this has the mixins as 'js' files so I suppose I could drop them into my project's 'mixins' directory and reference them from there, but don't think I should have to. 

Why aren't the mixins loaded or registered?

**Comment by marcoow** [comment]
You're probably using the [bower AMD distribution](https://github.com/simplabs/ember-simple-auth-component) then. When you correctly load [this file](https://github.com/simplabs/ember-simple-auth-component/blob/master/simple-auth.amd.js) the `"simple-auth/mixins/application-route-mixin"` module should be available.

**Comment by rvan1** [comment]
Hi Marco, nice job on the simple-auth project. 

Yes the project uses a 'minimal AMD loader' (github.com/stefanpenner/loader.js) which apparently now is called the 'ember-cli/loader' so am not sure if there's some EAK/CLI conflict with that (since I've updated dependencies and have the cli version now). I've looked at the 'examples/amd.html' which works OK. It includes the '...amd.js' file after the 'loader', so tried that, but still the module isn't found during build, so it aborts. 

How can I tell my project to load/register 'simple-auth.amd' rather than 'simple-auth'?

**Comment by marcoow** [comment]
Not sure how your build tool actually works... The only advice I could give you is to switch to Ember CLI but you're probably aware of the need to do that anyway. I'm planning to make Ember Simple Auth Ember-CLI-only before 1.0.

**Comment by rvan1** [comment]
To switch to CLI, I'd have to re-write the gruntfiles as brocfiles which I don't know how to do. I've tried running it through the CLI migrate process which just generates a broken app and 100's of debug questions with no answers. 

The app is built from EAK with grunt and gruntfile which was once fairly standard Ember stuff. It sets up some grunt configs and registers several build tasks. I've tried adding 'require('simple-auth/ember')' to the gruntfile, but 'cannot find module 'simple-auth/ember'. I've tried 'requiring' simple-auth in app.js, but same result. I've tried adding an initializer to 'app.js' with 'Ember.SimpleAuth.setup(application)', as is done in the 'ember-app-kit-simple-auth' example, but doesn't work either.

**Comment by marcoow** [comment]
Somehow Ember Simple Auth's AMD file isn't correctly loaded in your project. This isn't actually a bug in Ember Simple Auth though. I'd suggest you post that on stackoverflow and also provide some more info.

**Comment by rvan1** [comment]
Not a bug, right, just thought you'd know how to get a handle on the mixins. Stackoverflow, OK, I'll try. 

EAK-based ember apps use future ES6 module standard, so aren't necessarily AMD or CommonJS, but I think they are reverted or transpiled to AMD spec and loaded as AMD spec since ES6 isn't supported yet. It seems though that the simple-auth module gets loaded or registered OK, but how to reference in sub modules is my mystery.

I have the 'ember app kit simple auth' example working, but it depends on some old versions. ember-simple-auth version 0.1 uses a module syntax like 'Ember.SimpleAuth = Ember.Namespace.create', which is how I see some other vendor modules and I suppose is ES6. Your latest offering doesn't have that syntax. I suppose if I set my project to depend on that old version, it might work. And if I were to setup the 'ember app kit simple auth' example to depend on the latest version, it probably would not.

Alright, thanks for looking at it.
