### ISSUE TITLE
Cookie store logout glitches

### ISSUE THREAD

**Issue by rchrd2** [simplabs/ember-simple-auth#477]
Hello, 

I have been using the cookie store on a production site and have been experiencing occasional glitches where I am logged out without asking to be logged out. It doesn't have to do with the expiration time either.

I am able to consistently log my self out of the site simply by requesting to open the page with javascript. Here's an example html file that logs me out. This is just one way to trigger a log out, but in practice, I have been logged out for other reasons. Maybe this test file can help find the root cause? 

Also, when I switch to the localstorage backend, this test file does not trigger logout.

```
<html>
  <head>
    <script>
    function dothing() {
      popitup('http://localhost:4200');
    };
    function popitup(url) {
    	newwindow=window.open(url,'name');
    	if (window.focus) {newwindow.focus()}
    	return false;
    }
    </script>
  </head>
  <body>
    <a href="javascript:dothing();">Do it</a>
  </body>
</html>
```

These are my simple auth settings:

```
  ENV['simple-auth'] = {
    // We use cookies to easy single sign on between server
    store: 'simple-auth-session-store:cookie',
    authorizer: 'simple-auth-authorizer:oauth2-bearer',
    crossOriginWhitelist: ['*'],
  };
  ENV['simple-auth-cookie-store'] = {
    cookieName: 'ember_simple_auth_session',
    // The expiration time in seconds to use for the cookie. A value of `null` will
    // make the cookie a session cookie that expires when the browser is closed.
    cookieExpirationTime: 10 * 365 * 12 * 24 * 60 * 60,  // ~ 10 years
  };
  
```

package.json 
```
    "ember-cli-simple-auth": "^0.7.3",
    "ember-cli-simple-auth-cookie-store": "^0.7.3",
    "ember-cli-simple-auth-oauth2": "^0.7.3",
    "ember-cli-simple-auth-testing": "^0.7.3",
    "ember-cli-simple-auth-torii": "^0.7.3",
```

**Comment by marcoow** [comment]
Which authenticator are you using?

**Comment by rchrd2** [comment]
Oauth2 https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js

**Comment by marcoow** [comment]
Are you using refresh tokens as well? Does the authenticator make any AJAX requests when restoring the session in the opened window?

**Comment by rchrd2** [comment]
We are not using refresh tokens. I don't believe it makes any custom ajax requests. The application uses Ember Data and eventually grabs a user model based on a session.get('user_id'), but I'm not sure if it gets to that point before it logs out. It logs out immediately when using the example script above.

**Comment by marcoow** [comment]
Can you check whether it makes any requests? Maybe you're requesting the user too early and receive a 401 response which will invalidate the session.

**Comment by rchrd2** [comment]
I'll get back to you on this. One thing to note is that the problem does not happen with the LocalStorage adapter. It only happens with the cookie adapter. I originally thought it had to do with some sort of permissions built-into ember simple-auth. Thanks.

**Comment by marcoow** [comment]
could you set up a JSBin for this if the issue still exists? Would make it much easier for me to take a look - thanks!

**Comment by marcoow** [comment]
Any update on this?

**Comment by rchrd2** [comment]
We ended up switching our application to LocalStorage and the issues went
away. I'm not sure how to put together a demo. Is there an example JS Bin
with ember-simple-auth installed I can fork?

**Comment by marcoow** [comment]
You can use one of the examples for reference.

**Comment by marcoow** [comment]
closing this as it's almost 1 year old - @rchrd2: please reopen if still relevant.
