### ISSUE TITLE
Ember-CLI chokes on broken JSHint syntax

### ISSUE THREAD

**Issue by sukima** [simplabs/ember-simple-auth#478]
The README explains that you want to

```js
import 'simple-auth-testing/test-helpers';
```

Since importing the module will cause the module to evaluate. This is acceptable from the latest specs on ES6 however because Ember-CLI by default uses JSHint as part of their test suite new apps that use this module will unfortunately have failing tests.

There is already an [issue open (#2286)](https://github.com/jshint/jshint/issues/2286) open about this for JSHint.

The only work-around I know of is to use this syntax:

```js
import whoGivesAFlyingBleep from 'simple-auth-testing/test-helpers';
```

Then force JSHint to ignore the unused variable error with `unused: true` in your `tests/jshintrc` file. Which sadly means that **every** unused variable won't get caught. Obviously not an ideal situation.

Perhaps another test helper module that doesn't auto execute and instead exports the function that could be executed manually?

**Comment by marcoow** [comment]
Instead of adding `unused: true` to `test/.jshintrc`, you can also add that as an inline configuration comment to `test/helpers/start-app.js`.
