### ISSUE TITLE
Authorization on non xhr requests

### ISSUE THREAD

**Issue by ashton** [simplabs/ember-simple-auth#480]
Why authorizers only authorize XHR requests? Why can't I use something like `session.authorize()` like is done in authentication? I would like to authorize my routes regardless if it's an XHR request or not.

**Comment by marcoow** [comment]
There is no way Ember Simple Auth could authorize non-XHR requests. Routes are never authorized in Ember Simple Auth terms but might only require the session to be authenticated.
