### ISSUE TITLE
Unable to find 'simple-auth/mixins/application-route-mixin' when installing via Ember CLI v 0.2.3

### ISSUE THREAD

**Issue by jamesdixon** [simplabs/ember-simple-auth#481]
Hello,

Ember newbie here. Following the directions in the README, I've installed the package using the following command:

`ember install ember-cli-simple-auth`

During that install, I get the following output:

```
version: 0.2.3
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
Installed browser packages via Bower.
installing
The 'ember generate' command requires an entity name to be specified. For more details, use 'ember help'.
```

Take note that I'm running Ember CLI 0.2.3, which was recently released.

Although that last message was suspicious, I attempted to setup Simple Auth using the following code from the README:

```
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';
export default Ember.Route.extend(ApplicationRouteMixin);
```

Unfortunately, I'm getting the following error in the browser console:

```
Uncaught Error: Could not find module 'simple-auth/mixins/application-route-mixin' imported from 'business/routes/application'     loader.js:110
``` 

Can anyone help a guy out?

Thanks!
James

**Comment by marcoow** [comment]
did you restart the Ember CLI server after installing the addon?

**Comment by jamesdixon** [comment]
Doh! That was it. Thanks!

**Comment by devinrhode2** [comment]
Had this error come up, and it's addressed in the notes for upgrading to ember-simple-auth 1.0: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10
