### ISSUE TITLE
0.8.0: Can access session's data only via session's store

### ISSUE THREAD

**Issue by AW-UC** [simplabs/ember-simple-auth#482]
I'm using the standard Simple-Auth-Devise-Setup with 0.8.0. Now I want to extend the Session to include a currentUser value. This worked in 0.7.3:

    //app/sessions/custom.js
    import Ember from 'ember';
    import Session from 'simple-auth/session';
    
    export default Session.extend({
      currentUser: function() {
        var userId = this.get('user_id');
        //...
      }.property('userId')
To achieve the same in 0.8.0, I now have to get the `user_id` via the session's store:

    var userId = this.store._lastData.secure.user_id;
If this is the intended behaviour just close this issue.

**Comment by marcoow** [comment]
All data that the authenticator provides is now stored in the session's `secure` property, thus you need to change the `currentUser` property to:

```js
currentUser: function() {
  var userId = this.get('secure.user_id');
  //...
}.property('secure.userId')
```

**Comment by AW-UC** [comment]
@marcoow Thanks, I missed that change.

**Comment by matheusdavidson** [comment]
Hey @marcoow , sorry for asking in a closed issue but how can i change the currentUser value later? i have implemented something like you suggested here but my problem is when i need to update currentUser, it updates the model, but when i refresh the page the updated info is gone cause ember simple auth gets the user from secure in local storage which is not updated by my code.

**Comment by matheusdavidson** [comment]
i tried to update secure as well using ``` this.set('session.secure.user', user)``` but it does not update the local storage object causing problems when i reload.

**Comment by marcoow** [comment]
@matheusdavidson: If you're using the computed property as shown above, you change the current user by changing the session's `secure.userId` property. You shouldn't do that directly but instead invalidate the session and authenticate it with the new user.
