### ISSUE TITLE
Restore promise doesn't run

### ISSUE THREAD

**Issue by blisst** [simplabs/ember-simple-auth#484]
I am having issues with the `restore` hook for `SimpleAuth.Authenticators.Base`.

The docs say that the session is authenticated when the Promise returned by `restore` resolves.

Below, the logic in my returning Promise never actually runs/resolves, but the session acts as if it is authenticated.

Here is my code:

```
import Base from 'simple-auth/authenticators/base';
import Ember from 'ember';

var FacebookParseAuthenticator;
var adapterName = 'application';
var parseUserModelName = 'parseUser';


FacebookParseAuthenticator = Base.extend({  
  restore: function(user) {
    console.log('CALLING RESTORE');

    var self, adapter, store;
    self = this;

    store = this.container.lookup('store:main');
    adapter = store.adapterFor(adapterName);
    
    if (user == null) {
      adapter.set('sessionToken',null);
      return Ember.RSVP.reject();
    }

    adapter.set('sessionToken',user._sessionToken);
    console.log('sessionToken set');



    return new Ember.RSVP.Promise(function(resolve,reject) {
      console.log('This is running');
      FB.getLoginStatus(function(response) {
        console.log('loginstatus',response);
        /* MORE LOGIC WANTED */

       resolve(response);
       });
    });
  },
});
```

Therefore, I expect the console output to be something to the effect of
```
CALLING RESTORE
sessionToken set
This is running
loginstatus Object
Attempting transition to /       
Preparing to transition from '' to 'index'   // i.e. session successfully authenticated
```

Instead I get no evidence that the Promise logic is being called
```
fb-parse.js:22 CALLING RESTORE
fb-parse.js:40 sessionToken set
ember.debug.js:46432 Attempting URL transition to /
ember.debug.js:23508 Preparing to transition from '' to 'index'
ember.debug.js:46429 Transition #0: application: calling beforeModel hook
ember.debug.js:46429 Transition #0: application: calling deserialize hook
ember.debug.js:46429 Transition #0: application: calling afterModel hook
ember.debug.js:46429 Transition #0: index: calling beforeModel hook
ember.debug.js:46429 Transition #0: index: transition was aborted
ember.debug.js:46432 Attempting transition to login
ember.debug.js:23508 Preparing to transition from '' to 'login'
ember.debug.js:46429 Transition #1: application: calling beforeModel hook
ember.debug.js:46429 Transition #1: application: calling deserialize hook
ember.debug.js:46429 Transition #1: application: calling afterModel hook
vendor.js:58584 Transition #0: detected abort.
vendor.js:58584 Transition #1: login: calling beforeModel hook
vendor.js:58584 Transition #1: login: calling deserialize hook
vendor.js:58584 Transition #1: login: calling afterModel hook
vendor.js:58584 Transition #1: Resolved all models on destination route; finalizing transition.
vendor.js:35610 Transitioned into 'login'
vendor.js:58584 Transition #1: TRANSITION COMPLETE.
```

**Comment by marcoow** [comment]
So you have an existing authenticated session and reload the page so that the authenticator's `restore` method is called or what's actually triggering session restoration? The info you provide is a bit sparse…

**Comment by blisst** [comment]
Yes sorry.  I am debugging by making sure I get an authenticated session by checking:
`container.lookup('simple-auth-session:main').isAuthenticated == true`

Then I exit the tab, load a new one, such that `restore` is called.
It is being called with a `user` which has the right `user._sessionToken` and everything.

**Comment by marcoow** [comment]
I'm not sure I understand what's the actual issue here…

**Comment by blisst** [comment]
See how I am returning a Promise in the `restore` method?

The logic in the Promise never actually runs.  It never has the chance to resolve.  

As soon the Promise is returned from `restore`, the route immediately transitions to "/", i.e. the *post-authentication* route, even though, the logic within the returned Promise never actually runs.  

It even could have been rejected: the logic just never runs, and therefore the authentication doesn't actually complete.

Does that make sense?

**Comment by marcoow** [comment]
Basically the application shouldn't even display anything before session restoration has finished on application start (see here: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/setup.js#L113)

**Comment by marcoow** [comment]
Any updates on this?

**Comment by erichonkanen** [comment]
@marcoow this is possibly the same issue I raised that I am running into with the ember-cli-simple-auth-token package.. ever since updating to use 0.8.0-beta for some reason the restore() method isn't working after page refresh... in my case I end up calling [`resolve(data)`](https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L131) and then just blank white screen... token refresh is still scheduled correctly and will keep going but the app is stuck...

package.json
```
{
  "name": "picstream",
  "version": "0.0.0",
  "description": "Small description for picstream goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.0",
    "ember-cli": "0.2.7",
    "ember-cli-6to5": "^3.0.0",
    "ember-cli-app-version": "0.3.1",
    "ember-cli-bootstrap-sassy": "0.0.12",
    "ember-cli-coffees6": "^0.1.3",
    "ember-cli-dependency-checker": "0.0.7",
    "ember-cli-htmlbars": "^0.6.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.1",
    "ember-cli-sass": "^3.1.0-beta",
    "ember-cli-simple-auth": "0.8.0-beta.3",
    "ember-cli-simple-auth-token": "0.7.2",
    "ember-cli-uglify": "1.0.1",
    "ember-data": "1.13.4",
    "ember-export-application-global": "^1.0.0",
    "express": "^4.8.5",
    "glob": "^4.5.3"
  }
}
```

bower.json
```
{
  "name": "picstream",
  "dependencies": {
    "handlebars": "2.0.0",
    "jquery": "2.1.3",
    "loader.js": "ember-cli/loader.js#1.0.1",
    "ember": "1.9.1",
    "ember-data": "1.13.4",
    "ember-resolver": "~0.1.11",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli/ember-cli-test-loader#0.1.0",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.0.2",
    "ember-qunit": "0.1.8",
    "ember-qunit-notifications": "0.0.5",
    "qunit": "~1.17.1",
    "bootstrap-sass-official": "~3.3.3",
    "ember-simple-auth": "0.8.0-beta.3"
  }
}
```

I tried working through this again last night and no luck. Being that I wrote the jwt custom authenticator (inspired by your oauth2 package), Im hoping to be able to also debug this as there are people running into it when updating...

**Comment by jnhuynh** [comment]
Bumping this. I have the following code in the my restore method.

```js
  restore(data) {
    if (Ember.isEmpty(data.uid)) {
      Ember.RSVP.reject();
    } else {
      console.log(data); // this prints out
      Ember.RSVP.resolve(data);
    }
  },
```

I have a custom session that observes the `secure` property on the session, which should be set when the `restore` promise resolves. The restore promise never resolves so I get an empty object when I run `this.get('secure')` on my session.

**Comment by blisst** [comment]
I apologize it took so long for me to come back with a clarification, and I apologize I meant to file this issue with `ember-cli-simple-auth`.
```
restore: function(data) {
    var self, adapter, store;
    self = this;
    store = this.container.lookup('store:main');
    adapter = store.adapterFor(parseUserModelName);

    if (!data) {
      adapter.set('sessionToken', null);
      return Ember.RSVP.reject();
    }

    return new Ember.RSVP.Promise(function(resolve, reject) {
      Parse.FacebookUtils.logIn("user_likes,email", {
        success: function(user) {
          //***** THIS NEVER RUNS *****//
          adapter.set('sessionToken', user.getSessionToken());
          resolve({
            user_id: data.user_id,
            user_type: data.user_type,
            parse_user_id: data.parse_user_id,
            sessionToken: user.getSessionToken(),
          });
        },
        error: function(err) {
          //***** THIS NEVER RUNS *****//
          reject(err);
        }
      })
    });
  },
```

**Comment by blisst** [comment]
Having gone back through my code and stepped through the actual simple-auth code, I can
