### ISSUE TITLE
Simple Auth with users in ember-data

### ISSUE THREAD

**Issue by jimmyjamieson** [simplabs/ember-simple-auth#485]
Is there any examples of using simple-auth with login/retrieving and saving with ember-data?

For example, I'd like to offer users a simple login form and two providers (google, facebook). Whatever they use to login, I can store an user_id,name,email, password (if set) using ember-data > database.

And then allow them to add data to posts when authenticated while storing their user_id for model get-post> user: DS.belongsTo('user_id').

Is it possible?

**Comment by marcoow** [comment]
I cannot recommend that approach as it's easy to hack that and simply manipulate the requests so they assign a different user id. Instead your API needs to make sure it assigns new records to the user that's identified via the token in the `Authorization` header (or whatever authorization mechanism you're using).

**Comment by jimmyjamieson** [comment]
Ah, I understand now, thanks. 

I'm going to have to think more about this, as the users need to be able to view/edit/delete their listings whenever they login.

It's my first ember project just for learning, but it would be good to have something out of it at the end.
