### ISSUE TITLE
The `ember generate` command requires an entity name to be specified.

### ISSUE THREAD

**Issue by cnemeth** [simplabs/ember-simple-auth#488]
I get this message when installing ember-cli-simple-auth and  ember-cli-simple-auth-torii (ember-cli version 0.2.3.).

$ ember install ember-cli-simple-auth
version: 0.2.3
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
  cached git://github.com/dockyard/qunit-notifications.git#0.0.6
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

$ ember install ember-cli-simple-auth-torii
version: 0.2.3
Installed packages for tooling via npm.
installing
Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.8.0-beta.1
Installed browser packages via Bower.
installing
The `ember generate` command requires an entity name to be specified. For more details, use `ember help`.

**Comment by marcoow** [comment]
This is an issue with Ember CLI, see simplabs/ember-cli-simple-auth#26
