### ISSUE TITLE
Transition to previous route after authenticate

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#492]
Is there a way to pass simple-auth the originating route path name so that after a successful authentication a call to `transitionToRoute(pathname)` can be made to restore the original route before the login?

If not then is there a recommended way to achieve this?

**Comment by marcoow** [comment]
That should actually work out of the box if you're using the `ApplicationRouteMixin`.

**Comment by kgish** [comment]
Yes thanks, I now hook into the `sessionAuthenticationSucceeded` action like this:
```
actions: {
    ...
    sessionAuthenticationSucceeded: function() {
        var previousRouteName = this.controllerFor('application').get('previousRouteName');
        this.transitionTo(previousRouteName);
    },
    ...
}
```
