### ISSUE TITLE
Promise result undefined when resolving from custom authenticator

### ISSUE THREAD

**Issue by jamesdixon** [simplabs/ember-simple-auth#493]
Hi,

I created a custom authenticator for Firebase ([full source here](https://github.com/jamesdixon/ember-cli-simple-auth-firebase)) and while it appears to work great, I am running into one issue that I can't seem to track down the cause of. Hopefully, it's just a stupid mistake of mine :) 

After calling the `authenticate` method from my controller and successfully resolving the promise, the result is undefined. However, if the promise is rejected (ex: invalid login), it successfully returns the error message from Firebase.

**Custom Authenticator**
```javascript
authenticate: function(options) {

    return new Promise(function(resolve, reject) {

        this.get('firebase').authWithPassword({
            'email': options.email,
            'password': options.password
        }, function(error, authData) {
            Ember.run(function() {
                if (error) {
                    reject(error);
                } else {
                    resolve(authData);
                }
            });

        });
    }.bind(this));
}
```

**Relevant Code from Controller**
```javascript
_this.get('session').authenticate('authenticator:firebase', {
    'email': _this.get('email'),
    'password': _this.get('password')
}).then(function(success) {
    console.log(success);			// undefined
}, function(error) {
    console.log(error.message);       // firebase error
});
```

I've tried passing `resolve` a number of different values to see if it was an issue with the object that Firebase returns (`authData`), but no luck -- the promise resolves, but there's no result. Again, all functions work perfectly, it's just that the `result` property of the resolved promise is undefined.

Any suggestions would be greatly appreciated. Thank you!

Best,
James

**Comment by marcoow** [comment]
The session's `authenticate` method doesn't resolve with anything. Instead, anything the authenticator resolves with will be available via the session's `secure` property, e.g. `session.secure.token`.

**Comment by jamesdixon** [comment]
Ah, that explains it. Thank you!

Related: you mentioned session.secure.token; how would I access this from my controller? I tried this.get(‘session’).secure.token, but no luck.

Best,
James

**Comment by marcoow** [comment]
`this.get('session.secure.token')` as long as you're on 0.8.0-beta.1, in earlier versions that would be `this.get('session.token')`.

**Comment by jamesdixon** [comment]
Perfect. Thank you again!

**Comment by anish714** [comment]
I had to dig.  This worked for me.

The response gets tagged onto the session instead.


`export default Ember.Route.extend(ApplicationRouteMixin, {
`...
Then inside the function 

```
     var session = this.get('session');
     var data = session.get('data');
     console.log(data.authenticated);

```
