### ISSUE TITLE
Refresh causes logout

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#494]
If I am logged in and `session.isAuthenticated` is true, when I cause the browser to refresh I get logged out.

I've tried this using both localstorage and cookie stores but no luck.

I've followed all the instructions to the best of my ability, and wonder what I might be doing wrong.

Here's what I put in my `config/environment.js` file:
```
ENV['simple-auth'] = {
    authorizer: 'simple-auth-authorizer:oauth2-bearer',
    authenticationRoute: 'login',
    routeAfterAuthentication: 'index',
    routeIfAlreadyAuthenticated: 'index',
    store: 'simple-auth-session-store:cookie'
};

ENV['simple-auth-oauth2'] = {
    serverTokenEndpoint: '/api/v1/token',
    serverTokenRevocationEndpoint: '/api/v1/revoke'
};

ENV['simple-auth-cookie-store'] = {
    cookieExpirationTime: 60
};
```

**Comment by jamesdixon** [comment]
I'm not using the `simple-auth-oauth2` authenticator, but I do know the authenticators have a `restore()` method that is responsible for restoring the session when the page is refreshed. It seems that there may be some issue with this that's leading to your problem. You may want to try debugging that [particular part](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L98) of the `simple-auth-oauth2` library to see what's going down.

**Comment by kgish** [comment]
@jamesdixon Thanks for the tip!

I did some late night debugging of the `restore(data)` method being called when refreshing the browser and discovered that the data passed to this method is:
```
{
    "0": 200,
    "1":{},
    "2": {
        "access_token": "DDSHs55zpG51Mtxnt6H8vwn5fVJ230dF",
        "token_type":"Bearer"
    }
}
```
The local storage reveals the following value for the `ember_simple_auth:session` key:
```
{
    "secure": {
        "0": 200,
        "1": { },
        "2": {
            "access_token":"DDSHs55zpG51Mtxnt6H8vwn5fVJ230dF",
            "token_type":"Bearer"
        },
        "authenticator": "simple-auth-authenticator:oauth2-password-grant"
    }
}
```
However, looking at the code in the `restore()` method, it expects
```
data.access_token,
data.expires_at
etc.
```
which will not work as this is found in `data.2` and NOT `data`.

I wonder if this is a bug or if I happen to be doing something wrong.

Thanks in advance for the help.

**Comment by marcoow** [comment]
@kgish: you're returning the wrong result from the server - it should just be

```js
{
  "access_token": "DDSHs55zpG51Mtxnt6H8vwn5fVJ230dF",
  "token_type":"Bearer"
}
```

Looks like in your server code you're calling some method with `[200, {}, { "access_token": "DDSHs55zpG51Mtxnt6H8vwn5fVJ230dF", "token_type":"Bearer" }]` which you would e.g. in github.com/rack/rack but doesn't seem to be supported by your framework of choice.

**Comment by kgish** [comment]
Yes indeed, a bug in my mock server. Now fixed!
