### ISSUE TITLE
Authorization header sent everywhere

### ISSUE THREAD

**Issue by vasilakisfil** [simplabs/ember-simple-auth#496]
I have an issue with this plugin. If I am signed in, authorization header is sent everywhere, not only to my API endpoint. It is sent to s3 bucket (resulting to the following error: <Error><Code>InvalidArgument</Code><Message>Unsupported Authorization Type</Message><ArgumentName>Authorization</ArgumentName><ArgumentValue>Token token="Op+VpQzIsvrraICwdMz1GtOHenc7xzN2Z5W6izwAkbPLulnRNb/TVQp1sfCRxKdxo/3fyN7lfMVOwk8tsVj8lQ==", email="filippos@kollegorna.se"</ArgumentValue><RequestId>8580C0866889F24F</RequestId><HostId>LBj3pDNXj2qidX31cIPIvCVDz57JAz9Wyck+DrHuAjJFcFP.....) , it is sent to cloudinary which results to a CORS issue since cloudinary api does not allow Authorization header to be sent.

**Comment by marcoow** [comment]
This can only happen if you configure the `crossOriginWhitelist` as '*', otherwise it would be a severe bug.

**Comment by vasilakisfil** [comment]
Damn you are right, thanks!
