### ISSUE TITLE
testing events such as sessionAuthenticationSucceeded

### ISSUE THREAD

**Issue by jmonster** [simplabs/ember-simple-auth#498]
Hello there, I'm trying to write some tests but noticing that `authenticateSession()` doesn't trigger `sessionAuthenticationSucceeded` to execute. I was wondering if you had any suggestions for the best way to run/verify the results of such an event handler?

For example, I'm trying to verify that when two values in localStorage do not much that localStorage is cleared. So, the test is rather straightforward:

``` js
describe('when the user ID is the same', function() {
  beforeEach(function() {
    localStorage.setItem('last_user_id','1');
  });

  it('retains the cache', function() {
    authenticateSession().then(function() {
      expect(localStorage.getItem('foo')).toEqual('bar');
    });
  });
});

describe('when the user ID has changed', function() {
  beforeEach(function() {
    localStorage.setItem('last_user_id','2');
  });

  it('clears out the cache', function() {
    authenticateSession().then(function() {
      expect(localStorage.getItem('foo')).toEqual(null);
    });
  });
});
```

Thank you :)

**Comment by marcoow** [comment]
`sessionAuthenticateSucceeded` should be  triggered when using the test helpers.

**Comment by jmonster** [comment]
Welp, I threw some console.logs in both `sessionAuthenticationSucceeded` and `sessionAuthenticateSucceeded` and neither are printing out from the `authenticateSession()` call in my tests. `¯\_(ツ)_/¯`

**Comment by marcoow** [comment]
You're right, I just verified in the [example app](https://github.com/simplabs/ember-cli-simple-auth-example) - will look into it.

**Comment by marcoow** [comment]
The problem is that the automatic mapping of route events to route actions happens in the [application route's `beforeModel` hook](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L54) which means that with a test like that:

```js
test('a protected route is accessible when the session is authenticated', function(assert) {
  authenticateSession();
  visit('/protected');

  andThen(function() {
    assert.equal(currentRouteName(), 'protected');
  });
});
```

where the app isn't actually on any route yet before invoking `authenticateSession`, the mapping code hasn't run when the session is authenticated so that the session's event is never caught and mapped to the application route's action.

If you change the test to

```js
test('a protected route is accessible when the session is authenticated', function(assert) {
  visit('/');
  authenticateSession();
  visit('/protected');

  andThen(function() {
    assert.equal(currentRouteName(), 'protected');
  });
});
```

it actually works as expected.

While that automatic mapping that happens as soon as you mix in the `ApplicationRouteMixin` is convenient and something most people rely on, it's not really clean and could probably be improved. I don't really see a way to fix this though.

**Comment by jmonster** [comment]
Hmm.. at first I still had issues, but I went ahead and added `invalidateSession` in a beforeEach and that seems to have cleared it up for me (along with your `visit` suggestion); thank you kindly!

**Comment by marcoow** [comment]
@jmonster is this still an issue with 1.0?

**Comment by jmonster** [comment]
We haven't gotten to migrate yet from 0.6 but I think we will before the end of 2015; I'll try to remember to comment again :)

**Comment by marcoow** [comment]
@jmonster: any update on this?

**Comment by jmonster** [comment]
We've migrated to v1.0.1 👏

I'll have to double check the tests, but we are having an issue with something related to this in our actual application code. We had to manually trigger the event in our OAuth callback route to get reliable behavior:

```js
const code = transition.queryParams.code;
const session = this.get('session');
session.authenticate('authenticator:oauth2', null, code)
.then(() => {
  // This reliably triggers sessionAuthenticated callback every time.
  session.trigger('authenticationSucceeded');
});
```

If I recall correctly, we encountered that this event is not being triggered if the user is already logged in but their OAuth tokens were invalid (and thus they stepped through the OAuth login process again). Manually triggering it on the session resolved our issue(s) but doesn't smell right?

**Comment by marcoow** [comment]
Yeah, the event is only triggered when the session actually goes from not authenticated to authenticated. You might want to invalidate the session before testing the event.

**Comment by dustinfarris** [comment]
Potentially related, I have a basic login test with redirection test:

```js
test('logging in', function(assert) {
  visit('/');
  fillIn('.username', 'me');
  fillIn('.password', 'correct');
  click('.submit');
  
  andThen(() => {
    assert.ok(currentSession(this.application).get('isAuthenticated'));
    assert.equal(currentURL(), '/dashboard');
  });
});
```

in my config/environment.js i have:

```
'ember-simple-auth': {
  routeAfterAuthentication: 'dashboard'
}
```

This works in development, and in testing when testing with Chromedriver, however it fails with Phantom.  I put a console.log in my `sessionAuthenticated` handler in my application route, and it is not firing in Phantom.

**Comment by dustinfarris** [comment]
nvm, this was a result of using ember-mirage and checking a token with String.prototype.includes which Phantom does not support.

https://github.com/simplabs/ember-simple-auth/issues/1019

**Comment by stevenwu** [comment]
Please upgrade to the [latest release](https://github.com/simplabs/ember-simple-auth/releases) and reopen this if you have any issues.
