### ISSUE TITLE
Completed 401 Unauthorized in session auth

### ISSUE THREAD

**Issue by JeskTop** [simplabs/ember-simple-auth#499]
Hi.
In my application, I have a url to download the file and excel. Like this:
```
<a href="api/orders.xls" class="btn btn-circle btn-icon-only btn-default">
  {{fa-icon 'download'}}
</a>
```
If I do this, I will get the `401 Unauthorized error`. And I use 
```
  ENV['simple-auth'] = {
    authorizer: 'simple-auth-authorizer:devise'
  };

  ENV['simple-auth-devise'] = {
    identificationAttributeName: 'email'
  };
```
Is it use `simple-auth-authorizer:devise` could not fix this problem? I found some issues and guides, they use cookies store to save the token.
But I think use cookies is not safe. But I don't know how to send the auth token to the server if I use session stroe.
Is there another way I should be handling this? Thx.

**Comment by marcoow** [comment]
The authorizers only authorize AJAX requests. For regular requests you'd have to add the token to the URL, e.g.:

```hbs
<a href="api/orders.xls?access_token={{session.secure.access_token}}" class="btn btn-circle btn-icon-only btn-default">
  {{fa-icon 'download'}}
</a>
```
