### ISSUE TITLE
Access user_id

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#500]
In addition to the `access_token` and `token_type` my server returns the `user_id` with the response.

Is there someway that `ember-simple-auth` can expose this value, beyond saving it in the local-storage?

**Comment by kgish** [comment]
Sure I could do something like this, but it's not the most elegant manner and will more than likely break in a later version.
```
var session = this.container.lookup('simple-auth-session:main');
var user_id = session.content.secure['user_id'];
```

**Comment by marcoow** [comment]
@kgish: see the ["Authenticated Account" example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html) for info on how to access the authenticated account returned from the server via the session.

**Comment by kgish** [comment]
Looked through the code but couldn't find anything relevant to my question, maybe I'm not looking close enough. Can you please give me a more specific answer?

**Comment by marcoow** [comment]
All values that the authenticator resolves with on authentication are accessible via the session's `secure` property, e.g. `session.get('secure.user_id')`. The example above show how to build a `Session.user` property with that.

**Comment by kgish** [comment]
Okay, that's what I suspected but wanted to make sure that was correct. Thanks again.
