### ISSUE TITLE
Compile a list of projects/companies using ESA

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#501]
…so that could be added to the website. So far the only one I'm aware of is
- ghost (https://ghost.org / https://github.com/TryGhost)

**Comment by seriousben** [comment]
* http://foko.co/ (Hitting production soon!)

**Comment by LevelbossMike** [comment]
https://www.runtastic.com/

**Comment by marcoow** [comment]
http://app.terminapp.com

**Comment by AndrewAskins** [comment]
We use ESA for Ink, and love it! Thanks for all your work.

https://krit.it/ink

**Comment by marcoow** [comment]
I was just told that heroku is using ESA for their dashboard - nice 👍

**Comment by quaertym** [comment]
https://ofisko.com

**Comment by davidbilling** [comment]
http://www.timevillage.org/

Works very well! =)

**Comment by 2468ben** [comment]
http://crowdly.com, ESA + torii has been amazing for our apps.

**Comment by constantm** [comment]
https://leap.ly (when we roll out the new Ember frontend)

**Comment by dukex** [comment]
http://uhura.io / http://github.com/uhuraapp/uhura-frontend Podcast player

**Comment by mhesler** [comment]
https://frontoffice.wealthserv.com/desktop/login
Activity Client and Lead management for insurance representatives
http://www.bluesun.ca/crm

**Comment by manuel-reil** [comment]
app.alyne.com is now live using ESA in combination with auth0. Working well. Thanks for the efforts.

**Comment by Kilowhisky** [comment]
Company: http://blueskynetwork.com/ 
Product: SkyRouter

Thanks for ESA!

**Comment by NullVoxPopuli** [comment]
https://aeonvera.com
Event Registration and Point of Sale.
Thanks a ton for ESA!

**Comment by marcoow** [comment]
heroku is using ESA actually

**Comment by Duder-onomy** [comment]
https://thedyrt.com is using ESA

**Comment by constantm** [comment]
https://www.fundco.com/

**Comment by BryanCrotaz** [comment]
https://members.pixelpipesignage.com

**Comment by marcoow** [comment]
Hashicorp is using ESA for https://registry.terraform.io/
