### ISSUE TITLE
Send client_id in authentication requestion for OAuth2 Password Grant

### ISSUE THREAD

**Issue by bbooth** [simplabs/ember-simple-auth#503]
My Authorization server requires me to send a client id.  Can we make this an option in the config.

**Comment by marcoow** [comment]
Adding a config option for `client_id` should be fine. Want to submit a pull request?

**Comment by bbooth** [comment]
Yeah I have been trying to put something together, but I can't seem to get end to end testing working.  I have tried to ```bower link``` my fork and then ```bower link ember-simple-auth``` to test my changes, but ember-cli does not like that.  End up getting a nasty stacktrace about Invalid Version: * (which I think is how bower sets it after linking).  How do you typically test this stuff out?

**Comment by marcoow** [comment]
Ember Simple Auth's bower package is currently in an external repository which makes testing non-released versions a little hard. While that needs to be fixed, for now you can simply use the [examples included in the repository](https://github.com/simplabs/ember-simple-auth/blob/master/examples/1-simple.html) which will use your local code.

**Comment by csprocket777** [comment]
I JUST ran into this with a new project. Is this available yet somewhere?

**Comment by bbooth** [comment]
Currently have a pull request under review.  #508

**Comment by marcoow** [comment]
1.0 has been released with this feature
