### ISSUE TITLE
Authenticator for handling OAuth2 Authorization Code and Assertion Flow

### ISSUE THREAD

**Issue by kunerd** [simplabs/ember-simple-auth#506]
Resulting from reading [this](http://stackoverflow.com/questions/29851214/ember-cli-torii-and-multiple-providers) and similar question on Stackoverflow, and my own researches on this topic I thought about creating a special authenticator. This authenticator should handle the OAuth2 Authorization Code or respectively the OAuth2 Assertion Flow.

** OAuth2 Authorization Code **
This flow needs to send the a received `code` to it's back-end, where it has to be verified. After that the third-party `access_token`, which was requested from the server is send back to the client. This is the default flow, that torii provides.

** OAuth2 Assertion Flow **
Is similar to the Authorization Code flow, but after the `code` is verified, the third-party `access_token` is exchanged with a token generated by the custom API. This flow is therefore the `sign in with` flow for custom API's.

I think this is a very common use case and there should be an ember-simple-auth addon for it. What do you think about this?

**Comment by marcoow** [comment]
The way to implement both of these is basically to extend the torii authenticator, override the `authenticate` method and when the promise returned by that resolves, trigger the token verification/exchange with the backend server. I guess that the server API for that might be pretty different for different implementations as that's also not part of the OAuth 2.0 standard so I'm not sure how Ember Simple Auth would assist there other than providing a simple way of extending the base torii authenticator (which I hope it already does).

**Comment by kunerd** [comment]
Especially the Authorization Code flow is part of the standard and torii does only handle to get the `authorization code` from the authorization server. But, after that the code has to be verified with the help of a custom server implementation, because the `client_secret` is needed to accomplish this step. The custom server then obtains an `access_token` in exchange with the `code`, `client_id` and `client_secret`. The server API for this flow is defined by the standard. Also there are some security benefits resulting from this flow:

>The authorization code provides a few important security benefits,
>   such as the ability to authenticate the client, as well as the
>   transmission of the access token directly to the client without
>   passing it through the resource owner's user-agent and potentially
>   exposing it to others, including the resource owner.
https://tools.ietf.org/html/rfc6749#section-1.3.1

I also understand your objections, because there is no authentication of the browser app until the point described above. This authentication is indeed highly dependent of the custom API implementation, which is used by the ember app.

**Comment by marcoow** [comment]
The point is that the interaction between the User Agent (the browser) and the Client (the Ember app's API server) isn't part of the spec in the sense that it doesn't define how requests and responses should look (e.g. the interaction between User Agent and Client here: https://tools.ietf.org/html/rfc6749#section-4.1) so it would be hard to build support for that into the library as every application might implement that differently. That's why I'm saying providing an easy way of subclassing the torii authenticator is probably the best the library can do.

**Comment by kunerd** [comment]
But the response (in our case it should be called request, see below) is described in https://tools.ietf.org/html/rfc6749#section-4.1.2.

The response to the client should look like:
>     HTTP/1.1 302 Found
>     Location: https://client.example.com/cb?code=SplxlOBeZQQYbYS6WxSbIA
>     &state=xyz

, but torii interrupts it. That's the reason I thought we could forward it from ember-simple-auth, while following the same specs. This kind of flows are also described by Google and Facebook.

**Comment by marcoow** [comment]
That response is what torii uses to identify a successful login. That isn't handled by Ember Simple Auth  at all because it uses torii for that. As I said above, passing that auth code to your own API server to verify/convert it is part of the spec but not spec'd out in detail as that can be implement in whatever way that fits the respective app.

**Comment by kunerd** [comment]
Yes, I understand. Maybe a more detailed example, which shows how to extend ember-simple-auth-torii would be nice, because many people are extending the oauth2-authenticator at the moment.
I think this issue could be closed now. Thanks for your help.

**Comment by marcoow** [comment]
Yeah, I see. There's a really good article on that topic here: http://engineering-blog.alphasights.com/stateless-authentication-with-ember-simple-auth-and-torii/
