### ISSUE TITLE
Bad interaction between tabs when using localStorage

### ISSUE THREAD

**Issue by opsb** [simplabs/ember-simple-auth#507]
If I have two tabs open at the login screen (logged out) and try to login I end up being logged out again immediately.

The cause is that when the user logs into the first tab the localstorage events are fired in the second tab which then fires a sessionDataUpdated event. At https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L321 the content included with the sessionDataUpdated event is checked for a 'secure' property which is never present. Because it isn't present ember-simple-auth clears the session which causes the first tab to go through the same process, it checks for the secure 'property' and because it isn't there also clears the session.

I couldn't work out where the secure property was supposed to be set. What's the expected lifecycle here?

**Comment by marcoow** [comment]
I cannot reproduce this. Can you setup an example repo maybe?

**Comment by gauthierm** [comment]
I had the same issue and it turned out I was not passing `data` through in my authenticator `restore()` method promise resolution.

**Comment by tehmaestro** [comment]
I always have this problem.
  Whenever there are 2 tabs opened of the same app, if I try to login in one tab, I instantly get logged out.
  I am passing data in my restore method.

**Comment by marcoow** [comment]
@tehmaestro: please provide sample code that illustrates the problem or, even better, set u a JSBin.

**Comment by tehmaestro** [comment]
I'll try and make one.

**Comment by marcoow** [comment]
Any updates on this?

**Comment by hwhelchel** [comment]
I was seeing this too locally using the devise authenticator. I was passing back `authentication_token` instead of `token` from my rails api. When ember simple auth tried to synchronize the tabs it looked for `token` in the session and could not find it. Therefore it logged me out of both tabs. When I started passing `token` instead of `authentication_token` it worked perfectly.

**Comment by opsb** [comment]
@marcoow it looks like this is a bug in op-firebase-auth (which provides an authenticator for firebase). The problem seems to be that firebase doesn't update it's logged in status in other tabs until after authenticator.restore is called (due to the localStorage key being updated), https://github.com/tbarho/op-firebase-auth/blob/master/addon/authenticators/firebase.js#L12. It's probably best to close this issue and I'll open a new one on that repo.

**Comment by marcoow** [comment]
@opsb: not sure how firebase works but if this is actually an issue in the other repo this one should be closed.

**Comment by opsb** [comment]
@marcoow I've confirmed the issue is on the op-firebase-auth project, so I'll close this one.
