### ISSUE TITLE
Why not use a third party implementation of the token authentication

### ISSUE THREAD

**Issue by pupeno** [simplabs/ember-simple-auth#509]
I'm using ember for the first time, so, maybe I'm missing something, but instead of implement token auth as described on your documentation, why not using something like:

https://github.com/lynndylanhurley/devise_token_auth

**Comment by marcoow** [comment]
The README only describes the API requirements that Ember Simple Auth has. You can use whatever library you want to implement those on the server side.

**Comment by pupeno** [comment]
Being new to emberjs, I don't know and I can't yet evaluate whether devise_token_auth works or not.
