### ISSUE TITLE
sessionInvalidationSucceeded() arguments?

### ISSUE THREAD

**Issue by justinaray** [simplabs/ember-simple-auth#511]
I would like to be able to take some authenticator-dictated action after successful session invalidation; specifically, redirecting to a URL.

Since the store cleaning and other actions will occur after SimpleAuth.Session.invalidate() promise resolution, the only 'safe' place to do a redirect would be in the sessionInvalidationSucceeded action.

I could use properties or a service to accomplish this, but in the spirit of separation of concerns, i would like my authenticator to build and pass me the url.  Could the promise resolution data be passed from the invalidate call to the sessionInvalidationSucceeded(data) action?

Since this would be an API change, i thought it prudent to start a dialog rather than just submitting a PR.

**Comment by marcoow** [comment]
You can simply redirect to a URL from the authenticator's `imvalidate` method.

**Comment by justinaray** [comment]
Thanks for the response @marcoow.

Correct me if I'm wrong, but if i redirect within the `invalidate` method, don't I introduce a race condition in which I may or may not run the Session cleanup code (especially the store cleanup)?

Currently, I do have a redirect in the `invalidate` method but I put it inside a `setTimeout` to help defeat the race condition.  This didn't feel clean to me and I was hoping to clean it up with a redirect in the `sessionInvalidationSucceeded` action so I could be sure the store was cleaned up.

Thanks again!

**Comment by marcoow** [comment]
Sure, you're right of course. If you need information from the authenticator to later decide where to redirect or so you'd have to store that somewhere, for example in `localStorage` or so.

**Comment by justinaray** [comment]
Phew, I was worried I was missing something :smile:

Do you think this is a common enough use-case that the `sessionInvalidationSucceeded` action could be updated to include the promise resolution from the `Authenticator`?  I am pretty swamped this week, but could eventually submit a PR for this work.

If you think this is a one-off case, I can/will store the redirect URL in `localStorage` or a property of the `Session` object.

**Comment by marcoow** [comment]
I don't think that's a very common use case actually. Also I don't think it's a great API if `Session.invalidate` resolves with a value.
