### ISSUE TITLE
Deprecation warning in latest ember, since access to instances in initializers is deprecated

### ISSUE THREAD

**Issue by steffenbrem** [simplabs/ember-simple-auth#517]
Hi,

In the latest ember version, you cannot access instances of a container in the intializer anymore, see: http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers. Currently, this library triggers a lot of deprecation errors in latest ember version.

Any plans on updating simple-auth to support later ember versions?

**Comment by jasich** [comment]
:+1:

**Comment by marcoow** [comment]
PR would be great. Of course that would have to be backwards compatible and also work with Ember versions that don't have instance initializers.

**Comment by EmergentBehavior** [comment]
:+1:

**Comment by Keeo** [comment]
:+1:

**Comment by mattma** [comment]
+1

**Comment by rbwsam** [comment]
:+1:

**Comment by jozefvaclavik** [comment]
:+1:

**Comment by johnhamelink** [comment]
Yes please! :+1:

**Comment by jzgit** [comment]
:+1:

**Comment by vmalloc** [comment]
:+1:

**Comment by hooddanielc** [comment]
:+1:

**Comment by kaiwah** [comment]
:thumbsup:

**Comment by GeeWizWow** [comment]
:+1:

**Comment by felixkiss** [comment]
:+1:

**Comment by charlatan154** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)

**Comment by uppfinnarn** [comment]
:+1:

**Comment by steffenbrem** [comment]
:+1:

**Comment by quaertym** [comment]
We need more :+1:

**Comment by steffenbrem** [comment]
@quaertym Yes indeed

**Comment by engwan** [comment]
:+1:

**Comment by akatov** [comment]
:+1:

**Comment by mikejerome** [comment]
:+1:

**Comment by AW-UC** [comment]
I guess the need to be backwards compatible makes this overly complicated. I just refactored my Simple-Auth-Custom-Session to use an Instance Initializer. It works nice, but a backwards compatible version would be a horrible code mess.

**Comment by marcoow** [comment]
It needs to be backwards compatible. We cannot just force everyone to update to the latest ember.

**Comment by chrisvdp** [comment]
But you can tell people on older Ember versions to use older simple-auth versions. [example](https://github.com/ef4/liquid-fire#ember-compatibility-table)

**Comment by marcoow** [comment]
That would be a pain though as either people on old Ember versions wouldn't get bug fixes anymore or we would have to maintain 2 versions of Ember Simple Auth. I'm sure we can figure a backwards compatible solution out.

**Comment by ofridagan** [comment]
@AW-UC could you please share what you did?

**Comment by miguelcobain** [comment]
:+1:

**Comment by AW-UC** [comment]
As requested, I share my refactored code. Before, I used a custom session like this:
```js
// app/sessions/custom.js
import Ember from 'ember';
import DS from 'ember-data';
import Session from 'simple-auth/session';

export default Session.extend({
  currentUser: Ember.computed('secure.user_id', function() {
    var userId = this.get('secure.user_id');
    if (!Ember.isEmpty(userId)) {
      return DS.PromiseObject.create({
        promise: this.container.lookup('store:main').find('user', userId)
      });
    }
  })
});
```
The `container.lookup()` is deprecated here. If one wants to stick to registering a custom session, this would be a possible solution:
```js
// app/sessions/custom.js
import Session from 'simple-auth/session';
export default Session.extend({
  property: 'value'
//...
});
```
```js
// app/instance-initializers/custom-session.js
//...
function initialize(application) {
  var session = application.container.lookup('session:custom');
  var store = application.container.lookup('store:main');

  session.currentUser = Ember.computed('secure.user_id', function() {
    //...
  })
}
//...
```
IMHO, you only want to do this, if for some reason you still need to define properties during `Session.extend()` or you want to refactor it in a backwards compatible way. In the later case, you would do stuff in `Session.extend()` under the condition that `Ember.FEATURES.isEnabled('ember-application-instance-initializers') === false`.
**In most cases**, I think it is cleaner to not register a custom session at all, but do a custom instance initialization of the SimpleAuthSession. So in your `environment.js` you delete e.g. `
ENV['simple-auth'] = { session: 'session:custom' },` and remove e.g. `app/sessions/custom.js`. Then you just do:
```js
// app/instance-initializers/custom-session.js
import Ember from 'ember';
import DS from 'ember-data';

function initialize(application) {
  var session = application.container.lookup('simple-auth-session:main');
  var store = application.container.lookup('store:main');

  session.reopen({
    currentUser: Ember.computed('secure.user_id', function() {
      var userId = this.get('secure.user_id');
      if (!Ember.isEmpty(userId)) {
        return DS.PromiseObject.create({
          promise: store.find('user', userId)
        });
      }
    })
  })
}

export default {
  initialize: initialize
};
```
This latest example, is what I do in my app and it works fine. But suggestions for improvements are welcome ;-)

**Comment by marcoow** [comment]
@AW-UC: instead of reopening the session (I think `reopen` in general is a code smell) you could simply define an initializer that injects the store into the session. That way you could simply do `this.store.find('user', userId)` instead of `this.container.lookup('store:main').find('user', userId)`.

**Comment by AW-UC** [comment]
@marcoow yeah, I am totally unhappy with `reopen` as well, but I haven't found any other way to make it work in an instance initializer. Injecting services doesn't seem to work well in an instance initializer (still buggy?), but of course I could use a normal initializer:
```js
// app/initializers/custom-session.js
import Ember from 'ember';
import DS from 'ember-data';
import Session from 'simple-auth/session';

function initialize(container, application) {
  var CustomSession = Session.extend({
    storeService: Ember.inject.service('store'),
    currentUser: Ember.computed('secure.user_id', function () {
      var userId = this.get('secure.user_id');
      if (!Ember.isEmpty(userId)) {
        return DS.PromiseObject.create({
          promise: this.get('storeService').find('user', userId)
        });
      }
    })
  });
  application.register('session:custom', CustomSession);
}

export default {
  name: 'custom-session',
  after: 'ember-data',
  initialize: initialize
};
```
But then I get the `'lookup' was called on a Registry` deprecation again :-(

**Comment by marcoow** [comment]
You can just add another initializer and define an injection of store into session:

```js
application.inject('session:custom', 'store', 'store:main');
```

**Comment by AW-UC** [comment]
@marcoow thanks, it works well. but only, if it is not injected as `store`, because the session already has a `store` property.

**Comment by marcoow** [comment]
@AW-UC right, forgot about that - fixed in above comment

**Comment by ludalex** [comment]
:+1:

**Comment by AW-UC** [comment]
FYI, this how the `ember-intl` addon handled this:
1. Split initializers: https://github.com/yahoo/ember-intl/commit/4ad7c4094c753547b1e863adaac7b8a417d568d9
2. Fallback: https://github.com/yahoo/ember-intl/commit/ad3c8337a5a24f103fa46f2ecc2d5a6ed34d3163

**Comment by marcoow** [comment]
I think we can actually make that part of #522 and simply require a newer Ember version then given the fact that instance initializers also work in Ember versions prior to 2.0

**Comment by brandonparsons** [comment]
Hi @marcoow - what is your recommendation for how to handle this ? (i.e. ignore deprecations for now, custom session, wait for 522?)

**Comment by marcoow** [comment]
@brandonparsons: I think it should be part of #522. I won't have that ready until 2.0 beta 1 comes out so any help with that would be welcome!

**Comment by jeremytm** [comment]
:+1:

**Comment by juggy** [comment]
My latest PR fixes this and is backward compatible.

**Comment by brandonparsons** [comment]
@juggy @marcoow Is your PR good to use until #522 lands?

**Comment by mmahalwy** [comment]
@juggy any update on the PR?

**Comment by juggy** [comment]
Yes you can use PR #560 until #522 is done.

**Comment by mmahalwy** [comment]
Awesome! Thank you!

**Comment by injaon** [comment]
:+1:

**Comment by marcoow** [comment]
fixed in #522

**Comment by NullVoxPopuli** [comment]
was there ever a consensus on how to set `currentUser`? and access it from `{{session.currentUser}}` in a template?

I currently have this:

```javascript
// app/instance-initializers/custom-session.js

import Ember from 'ember';
import DS from 'ember-data';

function initialize(application) {
  var session = application.container.lookup('simple-auth-session:main');
  var store = application.container.lookup('store:main');

  session.reopen({
    currentUser: Ember.computed('secure.token', function() {
      var token = this.get('secure.token');
      if (!Ember.isEmpty(token)) {
        return DS.PromiseObject.create({
          /*
            the id of 0 here doesn't actually matter,
            the server alwasy returns the current user.
            This is just to route to the show action on the controller.
          */
          promise: store.find('user', 1)
        });
      }
    })
  });
}

export default {
  initialize: initialize
};

```
 
The user is retrieved, but `{{session.currentUser}}` is empty.

:-\

**Comment by vmalloc** [comment]
I think session.secure is now session.data.authenticated. Replace that and
you should be fine.

**Comment by NullVoxPopuli** [comment]
I don't know if that's correct.

when I have "secure.token", the request is made, but when I do session.data.authenticated, no request is made to obtain the user.

**Comment by Keeo** [comment]
@NullVoxPopuli `secure.token` is for 0.8.0, `session.authenticated.token` is for 1.0.0 or jj-abrams branch.

**Comment by NullVoxPopuli** [comment]
looks like this repo doesn't have a tag for 1.0.0. :-\

I tried changing the package.json from 0.8.0 to 1.0.0 as well as bower.json.

:-\

**Comment by Keeo** [comment]
@NullVoxPopuli sorry, 1.0.0 is coming soon,.. You should stick with 0.8.0 till there is finished documentation for it.

Anyway you can override session and do it like this (for 0.8.0):
https://gist.github.com/Keeo/8c688f5e131b32cdb6c0
*I didn't test this code, but it's looking good to me.*

**Comment by kjhangiani** [comment]
1.0.0 has some enormous breaking changes, there's no way I can trivially upgrade ESA, however, at the same time, I'd like to handle these deprecations so I can push forward ember to 1.13 and 2.0.  Is there a release of 0.8.0 branch that takes care of these container/lookup deprecations?

I'm currently using 0.8.0

**Comment by marcoow** [comment]
I wrote an upgrade guide here: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10. A version of 0.8.0 that works with Ember.js 2.0 would be quite complex and was considered not worth the effort. Upgrading to 1.0 is not as hard as it might first appear.

**Comment by kjhangiani** [comment]
Thanks for the link, that will help considerably.

I might give that a go tomorrow.. too late now for me to break everything :)  

Quick question - Is the session in 1.0.0 available in the registry as service:session, since it's just an ember service now?  For injection purposes, in an instance initializer

**Comment by marcoow** [comment]
sure - `service:session`

**Comment by BransonGitomeh** [comment]
a clean install of this addon now breaks ember with a ```container.lookup is not a function err````

**Comment by MattNguyen** [comment]
In the previous `currentUser` examples, why is `DS.PromiseObject` used to wrap `store#find`? Seems unnecessary when `store#find` returns a promise.

cc @Awem

**Comment by dschmidt** [comment]
you can access `currentUser.name` in a template with `DS.PromiseObject`
