### ISSUE TITLE
no way to clean up $.ajaxPrefilters

### ISSUE THREAD

**Issue by kbullaughey** [simplabs/ember-simple-auth#518]
`ember-simple-auth` uses jquery's `$.ajaxPrefilter` to add the `Authorization` header. However, this is causing problems with my tests. My acceptance/integration tests work as expected because the whole app is set up and initializers have been run. But when unit tests that deal with ember-data are run after acceptance tests, the ajaxPrefilters have not been cleaned up (as this is done globally once). This causes my unit tests to fail. If I disable my acceptance tests, all my unit tests pass. Furthermore, it seems there is no way to remove filters set up via `$.ajaxPrefilter`. 

With respect to testing, it seems like the use of ajaxPrefilter is undesirable because it represents undesirable state leakage that persists across tests. 

I'm not sure what the best solution is. Perhaps the state-leakage could be encapsulated by having a public API that can activate/deactivate the filter. Ideally, deactivation would happen automatically when the app is destroyed. 

Thoughts?

**Comment by kbullaughey** [comment]
I created a work around for myself by overriding `$.ajaxPrefilter` with a version that wraps all functions it receives in conditional variants that I can enable and disable at will:

    // Replace the implementation of $.ajaxPrefilter with one that is enabled only
    // during acceptance tests and gets cleaned up.
    var origAjaxPrefilter = Ember.$.ajaxPrefilter;
    var ajaxPrefilterEnabled = false;
    var enableAjaxPrefilter = function() {
      ajaxPrefilterEnabled = true;
    };
    var disableAjaxPrefilter = function() {
      ajaxPrefilterEnabled = false;
    };
    Ember.$.ajaxPrefilter = function() {
      // We wrap the function in a method that makes it conditional on whether we
      // want the prefilter to be on or off.
      var configureArgs = toArray(arguments);
      var originalHandler = configureArgs.slice(-1)[0];
      var wrappedPrefilter = function() {
        var args = toArray(arguments);
        if (ajaxPrefilterEnabled) {
          originalHandler.apply(this, args);
        }
      };
      configureArgs[configureArgs.length-1] = wrappedPrefilter;
      origAjaxPrefilter.apply(Ember.$, configureArgs);
    };
    
But it would be nice if this were somehow handled automatically by `ember-simple-auth`. Also my solution applies globally to all `$.ajaxPrefilter` calls, which although one might want, doesn't keep the solution confined to `ember-simple-auth`. In my case, this is okay, but not sure if that is true for everyone.

**Comment by marcoow** [comment]
To keep the simplicity of the library `$.ajaxPrefilter` is actually essential as it enables the no-effort-activation of automatic request authorization. However, your point is correct of course that that behavior leaks state.

A good alternative to the current implementation would probably to define a set of adapters that hook into things like `$.ajaxPrefilter`, Ember Data adapters or, for testing purposes an NOP so that it's more controllable.

A quick fix would probably to not define an authorizer for the testing environment at all which would solve your problem right away.

Also see #270 
cc @jayphelps

**Comment by marcoow** [comment]
will be fixed in #522
