### ISSUE TITLE
Make Ember Simple Auth an Ember CLI addon only

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#519]
With Ember CLI being the official standard way for building Ember applications it doesn't make sense anymore to keep the globalized and AMD distributions as that adds a lot of overhead and also makes it hard to install the library in Ember Cli applications from github directly. Instead for the 1.0 release the library should use the Ember CLI addon in the main repository which would also make it much simpler to include Acceptance Tests in the main repository.

**Comment by bradplank** [comment]
+1

**Comment by rlivsey** [comment]
This would be great, I just noticed today that I was running an old version of simple-auth because I'd been updating the version in package.json but not in bower.json so it hadn't actually updated anything!

**Comment by jpadilla** [comment]
:fireworks: that's great to hear, should simplify a few things on your side regarding maintainability

**Comment by tzellman** [comment]
I'd be happy to help if needed.

**Comment by piotrpalek** [comment]
@marcoow do you consider moving to the new initializers while doing this or should this be a seperate issue?
see: http://emberjs.com/deprecations/v1.x/#toc_access-to-instances-in-initializers

**Comment by marcoow** [comment]
Yes, this would also switch to instance initializers.

**Comment by piotrpalek** [comment]
Nice :+1:

**Comment by miguelcobain** [comment]
I think that all the efforts for maintaining a globals version should go directly to this addon: https://github.com/ef4/ember-giftwrap

**Comment by maysam-tayyeb** [comment]
+1

**Comment by marcoow** [comment]
see #602
