### ISSUE TITLE
Authenticator - restore infinite loop on resolved promise on IE11

### ISSUE THREAD

**Issue by kaiwah** [simplabs/ember-simple-auth#521]
Currently testing our ecommerce ember application and on Firefox/Chrome it works fine (when logged in). However on IE11, when a person is logged it, it loops through restore function regardless of 200/Success response from the server.

I traced it back to the culprit @ **"bindToStoreEvents"** which does a _this.container.lookup(container).restore(content). 

Looking at my network log, everything returned from our API is as it should be and all promises get properly resolved but restore function still keeps getting called in an infinite loop.

I can stop the loop by returning false on the restore function instead of returning a promise.

**Comment by marcoow** [comment]
Does that maybe only happen when you have multiple tabs/windows open at the same time? Also which session store are you using?

**Comment by kaiwah** [comment]
Hi @marcoow , I am testing with only 1 window/tab opened and still have the same issue.

In terms of the session store, I am using default (so local storage adapter).

Authenticate and Invalidate functions work fine. But right after authenticating, the restore loops over and over.

**Comment by alkamin** [comment]
This just started happening to me as well.  Same conditions, except it is happening in Chrome.  After authentication, the restore function is being called continuously.

**Comment by alkamin** [comment]
I was able to resolve this by re-installing all the dependencies (both npm and bower).

**Comment by alkamin** [comment]
Ok, turns out there was a another tab with the app running on a different screen.  Is this expected behavior?

**Comment by marcoow** [comment]
No, that's definitely not expected behavior.

**Comment by XrXr** [comment]
We had the same problem with our app on 0.7.3 for IE 10 and up. After looking into it it was caused by  IE firing the storage event for the window making the change and `simple-auth/utils/objects-are-equal` returning false for equal data.

Upgrading to 0.8.0-beta.2 fixed the issue for us. (It has a new `objects-are-equal` that is good, which prevents the infinite loop caused by the [storage event handler](https://github.com/simplabs/ember-simple-auth/blob/0.7.3/packages/ember-simple-auth/lib/simple-auth/stores/local-storage.js#L79))

**Comment by seriousben** [comment]
Thanks @XrXr

**Comment by kaiwah** [comment]
Can confirm, updating to 0.8.0-beta.2 fixed the issue. Thanks @XrXr

**Comment by marcoow** [comment]
:+1:

**Comment by maxkwallace** [comment]
I'm still seeing what appears to be this issue, using version 1.0.1 with IE11 on Windows 7.

The `sessionDataUpdated` event is being triggered in a loop, from:

```
      _ember['default'].$(window).bind('storage', function () {
        var data = _this.restore();
        if (!(0, _emberSimpleAuthUtilsObjectsAreEqual['default'])(data, _this._lastData)) {
          _this._lastData = data;
          _this.trigger('sessionDataUpdated', data);
        }
      });
```

which is running my `restore` function in a loop, via:

```
       if (!!authenticator) {
          delete content.authenticated.authenticator;
          _this5.container.lookup(authenticator).restore(content.authenticated).then(function (authenticatedContent) {
  // ...
```

Has anyone else run into this? I'm going to upgrade to 1.1.0-beta.2 and see if that fixes things.

**Comment by maxkwallace** [comment]
Update: as of upgrading to 1.1.0-beta.2, I can no longer replicate the issue-- things seem to be fixed on my end.

**Comment by lolmaus** [comment]
Opening more than one tab of our Ember app boosts the CPU usage of every tab to 100%.

Debugging leads to this piece of ESA:

```js
        restore: function() {
            var e = window.preloadEmberSession;
            if (e) {
                var t = JSON.stringify({
                    authenticated: n({}, e, {
                        authenticator: "authenticator:custom-oauth2"
                    })
                });
                localStorage.setItem(this.key, t)
            }
            return this._super()
        },
```

Upgrading from 1.0.1 to 1.1.0-beta.4 did not fix the issue.

Will you reopen this ticket or should I create a new one?

**Comment by marcoow** [comment]
@lolmaus: that's not part of ESA but I assume of a custom authenticator that you're using. As you're modifying `localStorage` there that might very well lead to an endless loop as the session store might trigger a `sessionDataUpdated` event which leads to the authenticator's `restore` method being called which modifies `localStorage` again etc.

**Comment by lolmaus** [comment]
@marcoow Testing without that method override.
