### ISSUE TITLE
Session data lost after refresh

### ISSUE THREAD

**Issue by bel3atar** [simplabs/ember-simple-auth#523]
Hi,
I am writing some data to the session and it ends up lost after refreshing the page, or opening another tab.
To reproduce this:
```javascript
this.set('session.X', 'Y');
```
This code correctly alters the localStorage, but after a page refresh all is lost.

**Comment by marcoow** [comment]
Is this when the session is authenticated? Please post the complete session content in `localStorage` here. Also which version of Ember Simple Auth are you using?

**Comment by bel3atar** [comment]
I am using the latest ember-simple-auth and I'm doing authentication with torii's "facebook-connect". So basically localStorage is populated by torii.
After refreshing the page the session is still authenticated, but I lose the things I've added manually using the instruction of my previous comment.

**Comment by marcoow** [comment]
What's the actual content of `localSorage` before and after the reload?

**Comment by bel3atar** [comment]
before the reload, localStorage has
```json
{
   "secure":{
      "authenticator":"simple-auth-authenticator:torii",
      "userId":"...",
      "accessToken":"...",
      "provider":"facebook-connect"
   },
   "X":"Y"
}
```
after reload:
```json
{
   "secure":{
      "authenticator":"simple-auth-authenticator:torii",
      "userId":"...",
      "accessToken":"...",
      "provider":"facebook-connect"
   }
}
```

**Comment by marcoow** [comment]
This should actually be working with 0.8.0-beta.1.

**Comment by bel3atar** [comment]
sorry I made a mistake. accessToken and userId are wiped too,
so before refresh:
```json
{
   "secure":{
      "authenticator":"simple-auth-authenticator:torii",
      "userId":"...",
      "accessToken":"...",
      "provider":"facebook-connect"
   },
   "X":"Y"
}
```
and after refresh
```json
{
   "secure":{
      "authenticator":"simple-auth-authenticator:torii",
      "provider":"facebook-connect"
   }
}
```

**Comment by marcoow** [comment]
Hm, looks like the provider's `fetch` method doesn't resolve with the correct data (see [invocation here](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-torii/lib/simple-auth-torii/authenticators/torii.js#L41)). Probably the Ember Simple Auth code is wrong anyway as it shouldn't actually require the provider to resolve with the session data - will change that in the next 0.8.0 beta.

**Comment by Kilowhisky** [comment]
I am getting the same issue but i am not using the torii library. 

Here is what i did:

1. Place an init function on the application route and throw a debugger statement there.
2. Place a debugger statement inside the restore function on my custom auth provider. 

Here is what happens

1. On init of the application route set a session property `this.get('session').set('locale,'en-us');`
2. View local storage to see that the property is present. 
3. Refresh the page
4. On the debugger breakpoint on the authenticators restore function view the local storage object. At this point in time localStorage still has the `locale: 'en-us'` property. 
5. Let the restore function resolve its promise. 
6. Hit the debug point on the application route
7. Check local storage to see that the `locale:'en-us'` property is now missing. 

For me anything i had present in the secure section of session was restored. Everything else went missing.

**Comment by marcoow** [comment]
Right, that's a bug - PR would be great!

**Comment by bartocc** [comment]
Guys, I am using 0.8.0 and I find this all the issue.
I must add that the session is not authenticated

Local storage is

```json
{"secure":{}}
```

In a controller action, I do
```js
this.set('session.foo', 'bar');
```

Local storage value is then

```json
{"secure":{},"foo":"bar"}
```

I reload the page and get the following local storage

```json
{"secure":{}}
```

I'll try with an authenticated session to see if it behaves differently

**Comment by alejandrogutierrez** [comment]
Having same issue.

**Comment by alejandrogutierrez** [comment]
NVM. I am using devise authenticator and I was returning an invalid token key from server.

**Comment by dukex** [comment]
I had the same problem using jj-abrams branch, 
I fixed with 

``` js
ENV['ember-simple-auth'] = {
  base: {
    store: 'session-store:local-storage'
  }
...
```

**Comment by bartocc** [comment]
@alejandrogutierrez 's comment made me double check what authenticator we were using and I realized it was a custom one that failed to implement the restore method correctly.

Sorry for the noise

**Comment by cesarizu** [comment]
This is happening for me with ember-2.2.0 and ember-simple-auth-1.0.0. I'm using a `OAuth2PasswordGrant` and no special configuration. The `localStorage` before and after reload are the same:
```
{
  "ember_simple_auth:session":"{\"authenticated\":{\"authenticator\":\"authenticator:oauth2\",\"access_token\":\"XXX\",\"token_type\":\"bearer\",\"expires_in\":7200,\"refresh_token\":\"YYY\",\"created_at\":1450794201,\"expires_at\":1450801401673}}"
}
```
I'm calling `this.get("session").set("someProperty", someValue")` and as long as I don't refresh, I can retrieve it from the session.

**Comment by indr** [comment]
Just in case someone comes here with the same 'problem':
```js
this.get('session').set('test1', 'value1'); // doesn't work
this.get('session').set('data.test2', 'value2'); // works
this.set('session.test3', 'value3'); // doesn't work
this.set('session.data.test4', 'value4'); // doesn't work
```

**Comment by tommathewXC** [comment]
Thank you indr. This was precisely my problem too.
