### ISSUE TITLE
(OAuth2 Authenticator) Invalidate method does not POST to serverTokenRevocationEndpoint

### ISSUE THREAD

**Issue by green-arrow** [simplabs/ember-simple-auth#524]
In the `invalidate` function of the OAuth2 Authenticator, the `access_token` and `refresh_token` are sent to the `serverTokenRevocationEndpoint`, if one is configured. The problem is in how this function checks for the existence of the tokens:

```javascript
// data[tokenType] is never defined,
// since everything lives under data.secure
if (!Ember.isEmpty(data[tokenType])) {
  requests.push(_this.makeRequest(_this.serverTokenRevocationEndpoint, {
    token_type_hint: tokenType, token: data[tokenType]
  }));
}
```

**Comment by marcoow** [comment]
Good point. That wasn't updated when the `secure` key was introduced. PR would be great!

**Comment by marcoow** [comment]
Actually that's already fixed as the session only passes the secure session data to the authenticator's `invalidate` method.

**Comment by green-arrow** [comment]
@marcoow when I was investigating the `data` passed to the `invalidate` method, the only thing available  was the `secure` hash. No `access_token` was present directly off of `data`.

**Comment by marcoow** [comment]
which version are you using?

**Comment by green-arrow** [comment]
```
DEBUG: Ember Simple Auth           : 0.8.0-beta.1
ember.debug.js:5197 DEBUG: Ember Simple Auth OAuth 2.0 : 0.8.0-beta.1
ember.debug.js:5197 DEBUG: Ember Simple Auth Testing   : 0.8.0-beta.1
```

**Comment by marcoow** [comment]
please update to 0.8.0-beta.2

**Comment by green-arrow** [comment]
I updated to beta.2, but the debug statements still say beta.1. I've confirmed that the package.json in `node_modules/ember-cli-simple-auth` says beta.2. Have the ember inspector debug statements been updated to reflect the correct version?

**Comment by marcoow** [comment]
you need to update the bower package as well. That's going to get easier once #522 gets merged.
