### ISSUE TITLE
Ember data request authorization

### ISSUE THREAD

**Issue by izukingz** [simplabs/ember-simple-auth#528]
Hello,
My Ember data request does not have the authorization added in the header.
I tried adding it manually in the adapter using: 
headers: {
    "Authorization": 'Token: ' + Ember.get('session.secure.token')
  }

But it returns undefined. Normal ajax request does add the authorization. How do i fix this.

Thanks

**Comment by izukingz** [comment]
Adding more info, I am using custom authorizer and authenticator. The authorizer gets called when i do a ajax request and it gets added to the header. If i use Ember data this.store.find(...), it does not call the authorizer and if i modify the adapter to add the header (above), i don't get access to the session.

**Comment by marcoow** [comment]
Is your API running on a different origin? Did you configure the [`crossOriginWhitelist`](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Configuration-crossOriginWhitelist) accordingly?

**Comment by izukingz** [comment]
No the api is running in same origin. I receive the authorization if i use ajax. i did not configure crossOriginWhitelist as there is no need to.

**Comment by marcoow** [comment]
Please post the source of your custom authorizer as well as your configuration here.

**Comment by izukingz** [comment]
I use the example you gave, with small modification:

authorize: function(jqXHR, requestOptions) {
          if (this.get('session.isAuthenticated') && !Ember.isEmpty(this.get('session.secure.token'))) {
            jqXHR.setRequestHeader('Authorization', 'Token: ' + JSON.stringify(this.get('session.secure.token')));
          }
        }

ENV['simple-auth'] = {
        authenticationRoute: 'index',
        routeAfterAuthentication:'home',
        authorizer: 'authorizer:custom'
      };

**Comment by marcoow** [comment]
Is the `authorize` method ever called? Is `session.secure.token` present?

**Comment by izukingz** [comment]
it doesnt get called if i use Ember data for the request. It gets called if i use $.ajax. The session is present as i successfully logged in.

**Comment by marcoow** [comment]
Is Ember Data actually sending an AJAX request then?

**Comment by izukingz** [comment]
I do see the request in the network. Just that there is no authorization header. Let me dig deeper to see if i can find the issue. i just needed clarification that this is an intended feature before investigating further. Thanks for the quick responses. Will let you know what i find.

**Comment by simo163** [comment]
@izukingz did you solve this issue? I can't send the token in the header when sending simple ajax requests. The rest works to me perfect, I think the oposite happens to you.

**Comment by simo163** [comment]
@izukingz the thing is I have empty the session.secure.token

**Comment by izukingz** [comment]
For my case (which may be related to yours), I'm running my ember app on a separate port from my node server. i use proxy to send the requests to my backend. I don't get the token sent. If i whitelist the server, i have issues communicating to it. If i deploy my app on my backend server, i get the token.

**Comment by simo163** [comment]
Thank you @izukingz for your quick answer. When I was working on Ember 1.3 I was whitelisting the server and it worked. Now I switched to Ember 2.0 while ember-simple-auth had some changes and crossOriginWhitelist doesn't work anymore to me in ENV['simple-auth']. I tried to use the https://github.com/ember-cli/ember-ajax plugin and add the token to the headers but session.secure is empty.

**Comment by ruiwanbing** [comment]
I have the same issue @izukingz . I run my ember app and backend in localhost with different ports and use proxy to send requests to the back. But, when calling the backend, the authorization token is gone .  How could I add the authorization token?

**Comment by izukingz** [comment]
@ruiwanbing, It's been a while I had this issue. Currently scanning my project and I don't use custom authorizer any longer. I use Oauth2 authenticator and authorizer.

-- authenticators/Oauth2.js

import OAuth2PasswordGrant from 'ember-simple-auth/authenticators/oauth2-password-grant';
export default OAuth2PasswordGrant.extend({
  serverTokenEndpoint: '/my-endpoint'
});

-- authorizers/Oauth2.js

import OAuth2Bearer from 'ember-simple-auth/authorizers/oauth2-bearer';
export default OAuth2Bearer.extend();


-- login controller
session: Ember.inject.service('session'),

-- action
this.get('session').authenticate('authenticator:oauth2', username, password).catch((reason) => {
    
 });

Hope this helps

**Comment by izukingz** [comment]
@ruiwanbing,  Note that if you are using my example above, your server should return a JSON with access_token field.

{access_token:"your secret string. Could be JSON object stringified"}

**Comment by dballona** [comment]
I have the same issue

**Comment by dballona** [comment]
I have the same issue. When inspecting the response through the "Network" tab, the authorization header is present although it's not present on `handleResponse`.
