### ISSUE TITLE
Inconsistent parameters to Authenticators.Base#restore and #invalidate

### ISSUE THREAD

**Issue by akatov** [simplabs/ember-simple-auth#531]
In my custom authenticator derived from Base the restore hook is getting just the data that I resolved with in the authenticate hook, e.g. in my case `{"my": "secret"}`.

The invalidate hook however gets the full contents of the store, i.e. in my case `{secure: {"authenticator": "authenticator:custom", "my": "secret"}}`.

Is this the intended behaviour? Why?

**Comment by marcoow** [comment]
This is already fixed in master: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L199

**Comment by akatov** [comment]
:+1:
