### ISSUE TITLE
Using currentSession() test helper issue

### ISSUE THREAD

**Issue by chrism** [simplabs/ember-simple-auth#533]
Hi,

Since using 8.0 I now access my currentUser variable via `session.secure.currentUser`.

This works well in my application but I can't seem to get it to work using currentSession().

For example neither, 

    currentSession().set('currentUser', { name: 'John Smith'} );

nor

    currentSession().set('secure.currentUser', { name: 'John Smith'} );

seem to work.

Any ideas what i'm doing wrong?

Thanks.

**Comment by marcoow** [comment]
What's actually stored in `session.secure.currentUser`? It's usually better to only store e.g. the current user's ID in the session and then add a computed property to the session that loads the user for that ID as shown e.g. here https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html#L133.

**Comment by chrism** [comment]
Thanks very much indeed, I have tried to follow that example and created a custom session, removing all extra data so that my `authenticate` function only returns data in this format

```
      return {
        userId: userId,
        token: token
      };
``` 

After refactoring this I can access the userId correctly from session.secure like this

```
$E.get('session')
Class {store: (...), container: Registry, toString: function, isAuthenticated: (...), authenticator: "authenticator:instatube"…}
$E.get('session.secure.userId')
"524f31a5-17d1-4640-9e0b-a02fd94505fc"
```

& I have also added custom session which should return the computed property for user now.

app/sessions/custom.js
```js
import Ember from 'ember';
import Session from 'simple-auth/session';

export default Session.extend({
    user: function() {
      debugger;
      var userId = this.get('secure.userId');
      if (!Ember.isEmpty(userId)) {
          return this.container.lookup('store:main').find('user', userId);
      }
    }.property('secure.userId')
});
```

And yet, when I try to access the user property via

```
$E.get('session.user')
```

it is undefined, and the debugger is not invoked.

Do I need to initialize or register the custom session in some way?

I'm using a custom authenticator and working on Ember 13.0-beta1.

**Comment by marcoow** [comment]
You need to [change the configuration](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Configuration-session) so that the custom session class actually gets used.

**Comment by chrism** [comment]
Argh sorry - it works perfectly now after adding

```
session: 'session:custom'
```

to simple-auth in the config/environment.js

Thanks so much for your help.

**Comment by natecox** [comment]
@chrism @marcoow
The custom session that is being used here is a great idea that I'm going to be implementing myself, but I'm curious about the placement of the file which extends the session. The example above has the file placed in `app/sessions/custom.js`; is that the proper location for the file? 

How do I know that it will be loaded before the rest of the app starts trying to set sessions and so forth?

**Comment by marcoow** [comment]
@natecox: Yes, `app/sessions/custom.js` is the correct place for the session. Ember CLI will take care of making it available as `session:custom` then.

**Comment by natecox** [comment]
That makes sense, and answers other questions that I've had regarding file structure actually.

Do you know how a custom session function would handle returning promise chains? I'd like to add a 'profile' property to the session, but in order to query it properly I need to first look up a token association table and then return the profile on that record. The pseudocode is essentially as follows:

```
Session.extend({
  profile: function() {
    var store = [lookup store],
        uid = this.get('content.secure.uid');
    return store
      .find('assocTable', {orderBy: 'uid', equalTo: uid})
      .then(function(ids) {
        return ids.get('firstObject.profile');
      });
  }.property('content.secure.uid')
});
```

**Comment by marcoow** [comment]
@natecox: you should use a `PromiseObject` in that case, see e.g. [this example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html#L136).
