### ISSUE TITLE
currentUser lost with two windows open

### ISSUE THREAD

**Issue by tmayr** [simplabs/ember-simple-auth#536]
This might be related to #523 

Every time I open a second tab, the currentUser object is 'lost' on the old one, this is caused by

```
  bindToStorageEvents: function() {
    var _this = this;
    Ember.$(window).bind('storage', function(e) {
      var data = _this.restore();
      if (!objectsAreEqual(data, _this._lastData)) {
        _this._lastData = data;
        _this.trigger('sessionDataUpdated', data);
      }
    });
  }
```

I'm not 100% clear on why, or if it's intentional or not, but data has a class instance of currentUser while _lastData has just an object referencing the currentUser which is being set as the new data session.

![bug](https://cldup.com/NhxakGajKb-3000x3000.png)
(first object represents *data*, second object represents *_lastData*)

You can even see the *session.currentUser* change on the first window you have open

![bug2](https://cldup.com/CttdV6cvGR-3000x3000.png)
(first object is on first load, second object is after opening a second tab)

It might also be related to the *persist* model as I can see it's setting some *currentUser objects* and some *currentUser classes*, starting here it went over my head pretty quickly so I'm not even sure.

Just in case it's related, this is my code for getting the currentUser
```
import Session from "simple-auth/session";
import Ember from 'ember';

export default {
  name: 'cusotm-session',
  before: 'simple-auth',
  initialize: function(container, app) {

    Session.reopen({
      setCurrentUser: function() {
        if(this.get('isAuthenticated')){

          var _this = this;
          var store = container.lookup("store:main");

          Ember.$.ajax(url).then(function(data){
            var me = store.push('user', data.load.me);
            _this.set('currentUser', me);
            // custom app logic unrelated to the user
          });
        }
      }.observes('isAuthenticated')
    });
  }
};
```

I'd love to provide more info, not sure what else could be relevant, pretty new to ember so my apologies if theres any obvious mistake I'm not aware of.

**Comment by marcoow** [comment]
You shouldn't store class instances in the session, only POJOs, storing class instances isn't supported. Checkout [this example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html) for adding a `currentUser` property to the session.

**Comment by tmayr** [comment]
Alright, I understand, so there's no way to use that user computed properties I guess? is that intended?

**Comment by marcoow** [comment]
You can use a computed property to make the current user accessible via the session but not store an actual user object in the session.
