### ISSUE TITLE
Docs refer to a nonexistent attribute 'secure' in the global session context

### ISSUE THREAD

**Issue by vmalloc** [simplabs/ember-simple-auth#538]
I believe the actual data is saved in `content`, and not in `secure`

**Comment by marcoow** [comment]
Secure data (that's the data the authenticator resolves with when authenticating the session) is stored in the session's `secure` property, everything else is stored in the session directly (or actually its `content` property that it proxies to).

**Comment by vmalloc** [comment]
I tried returning extra data from my authenticator, but I could not find any `secure` property anywhere (got `undefined` when tried accessing it...) What am I missing?

**Comment by marcoow** [comment]
That should work. Please provide more info and code.

**Comment by vmalloc** [comment]
The code is here (I apologize in advance for the complexity): https://github.com/slash-testing/backslash/blob/develop/webapp/app/login/route.js.

What I'm essentially doing is passing the auth code from torii to my custom authenticator (authenticators/token.js). It then proceeds to POST to the backend server (https://github.com/slash-testing/backslash/blob/develop/webapp/app/authenticators/token.js). 

At this point, if I understand correctly, whatever's returned from the POST is supposed to be saved to `session.secure`, but it is `undefined` on my end (although I see all other steps taking place as expected...

**Comment by robclancy** [comment]
I have just run into this issue as well, I am using a modified devise authorizer and this line (https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-devise/lib/simple-auth-devise/authorizers/devise.js#L69) is always undefined. I changed it to `this.get('session').content` and it is working fine now.

**Comment by marcoow** [comment]
@vmalloc: what's the response of ´POST /login´? Also, `Session.authenticate` doesn't resolve with any value - you'd probably want to change the `googleLogin` action to

```js
googleLogin: function() {
  let self = this;
  self.get('torii').open('google-oauth2').then(function(auth) {
    return self.get('session').authenticate('authenticator:token', auth).then(function() {
      return self.get('session.secure');
    },
    function(error) {
      self.controllerFor('application').send('login_error', error);
    });
  });
}
```

@robclancy: what does your authenticator's `authenticate` method look like?

**Comment by robclancy** [comment]
```
authenticate(credentials) {
    return new Ember.RSVP.Promise((resolve, reject) => {
      let data                = {};
      data = {
        password: credentials.password
      };
      data[this.identificationAttributeName] = credentials.identification;

      this.makeRequest(data).then(function(response) {
        Ember.run(function() {
          resolve(response);
        });
      }, function(xhr) {
        Ember.run(function() {
          reject(xhr.responseJSON || xhr.responseText);
        });
      });
    });
```

I don't think I changed it from the devise one other than config values, but I can't remember.

**Comment by marcoow** [comment]
What's the server response then? Also you're both on the latest version right?

**Comment by robclancy** [comment]
I did this last week so is that version, my response contains the email and token like so...

```
email: "email@gmail.com"
token: "secret"
```

This isn't much of an issue for me as I am going to change the response and what it should use etc at some point but with everything at default other than config I was seeing this issue. I am also on latest ember and ember-cli afaik (new project, could be out of date from a couple weeks of changes).

**Comment by vmalloc** [comment]
@marcoow  even with your proposed change `secure` isn't being set.

Here's how my response from `/login` looks like:
```
{"auth_token": "...", "user_info": {"email": "vmalloc@gmail.com", "roles": ["admin"], "user_id": 1, "verified_email": true}}
```

**Comment by vmalloc** [comment]
@marcoow why is this bug closed as invalid? from the discussion I see no indication we're doing anything wrong, and even with the latest version `session.secure` is still undefined...

**Comment by marcoow** [comment]
just to be sure, is the resolve or the reject callback invoked here?

```js
googleLogin: function() {
  let self = this;
  self.get('torii').open('google-oauth2').then(function(auth) {
    self.get('session').authenticate('authenticator:token', auth).then(function() {
      self.get('session.secure');
    },
    function(error) {
      self.controllerFor('application').send('login_error', error);
    });
  });
}
```

Also what's the content of `this.get('session.content')`?

**Comment by vmalloc** [comment]
I just double checked and the promise resolves correctly. Still no `secure`.

`session.content` is something like:
```
Object {auth_token: "{"user_id": 1, "user_info": {"family_name": "Yaari…": ["admin"]}}.CLXn_A.KCaNZeHaShwO6xLIG5IKvqtT-R0", __ember_meta__: Meta}
```

**Comment by marcoow** [comment]
Your `bower.json` specifies ember simple auth 0.7.3 - please change that to 0.8.0 and retest.

**Comment by vmalloc** [comment]
Whooops - changed `package.json` and forgot bower. Changing now and retesting...

**Comment by vmalloc** [comment]
Now it's even more strange. Same code with 0.8.0 on bower yields this in `content`, still no `secure`:
```
{"secure":{"authenticator":"authenticator:token","auth_token":"{\"user_id\"...
```
Meaning the `secure` object is now under `session.content.secure` instead of `session.secure`...

What am I doing wrong?

**Comment by vmalloc** [comment]
Oh - actually strike that. I had another issue messing up my session state. It works now. Thanks a lot for the patience man!

**Comment by marcoow** [comment]
The session is an `Ember.ObjectProxy` so `session.content.secure` is essentially the same as `session.secure`.
