### ISSUE TITLE
cookie-store: session isn't restored on refresh

### ISSUE THREAD

**Issue by florent-blanvillain** [simplabs/ember-simple-auth#540]
I upgraded from `ember-simple-auth:0.6.7` to `0.8.0-beta.2` and it doesn't work anymore.
I thinks it might be related to the new secure key introduced in `0.8.0-beta.1`; it seems this key is now included in the cookie value :
`{"secure":{"authenticator":"authenticator:grails","username":"florentblanvillain@gmail.com","roles":["USER"],"access_token":"2giektv95s0n4cid7gblandq0gf23"}}`

**Comment by marcoow** [comment]
That's already fixed on master. Will be released in the next days.

**Comment by florent-blanvillain** [comment]
Ok, thank you !
