### ISSUE TITLE
Can't get sessionAuthenticationSucceeded to be called

### ISSUE THREAD

**Issue by rathwell** [simplabs/ember-simple-auth#541]
Hello, 

I cannot seem to get the sessionAuthenticationSucceeded override to actually get called.  Am I missing something, or is this no longer intended to work?

Below is my Application route, and I am currently using ember-simple-auth 0.8.0-beta.2, ember 1.12.0 and ember-data 1.0.0-beta.18, but I was not able to get this working with the previous versions of all of these either.

```
import Ember from 'ember';
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
    beforeModel: function(transition) {
        this._super(transition);

        // initialize session promise here so current user data 
        // will be resolved for all routes (on page refresh or first load)
        return this.get('session').initSession();
    },
    actions: {
        sessionAuthenticationSucceeded: function() {
            console.log('sessionAuthenticationSucceeded...called');
            this.get('session').initSession().then(() => {
                console.log('sessionAuthenticationSucceeded...initSession resolved');
            });
        }
    }
});
```

Any help or guidance would be greatly appreciated.  Thanks.

**Comment by marcoow** [comment]
Overriding the `sessionAuthenticationSucceeded` should actually work that way. I don't think having an `initSession` method is so great though - you should use computed properties that depend on the session's `isAuthenticated` property (and any other data that the authenticator resolves with) instead.

**Comment by rathwell** [comment]
The problem with using computed properties is that they do not persist to local storage.  This is fine for the current user, but I also have a "current group" property that the app depends on.  Since it is not persisted, it would reset to the default value on every page refresh.

I can obviously tweak it to work, but either way I would like to know how to get the overriding of ```sessionAuthenitcationSucceeded``` action to work.  Do you have idea of the types of things that might cause it not to work?

If not, I'll look into it a bit more.

**Comment by marcoow** [comment]
You can store values in the session outside of the `"secure"` key that will then survive a page refresh. I don't really see why your `sessionAuthenitcationSucceeded` action wouldn't be called though. Be aware though that `sessionAuthenitcationSucceeded` isn't triggered when the user is already authenticated when the application starts.

**Comment by rathwell** [comment]
Ok, thanks.  I'll play with it a bit more.

Re: the values surviving a page refresh, I thought what I was seeing was
that computed properties were not persisting, even if they were later set
with, e.g., ```this.set('session.currentGroup')```, but if I just set the
values without having a computed property then they would persist.  I could
very well be wrong, I was fairly tired when trying it.

Re: ```sessionAuthenticationSucceeded``` not being called on login, when
logging out and logging back in this action was not triggered.  I can try
it with an empty project tonight and see if it works, and if so figure out
what is causing the issue in my current project.

**Comment by marcoow** [comment]
Any updates on this?

**Comment by rathwell** [comment]
I gave up at the time, but trying again just now it does seem to be working.  I upgraded to 0.8.0 (from 0.8.0-beta2) last night.  Assuming that is what fixed it, but I can't say for sure.

Thanks.

**Comment by robguilfoyle** [comment]
I'm having the same issues, placing an override in the Application route doesn't get triggered upon authentication success.

**Comment by dukex** [comment]
@robguilfoyle What version of ember-simple-auth are you using?

**Comment by robguilfoyle** [comment]
@dukex: Thanks for following up. It turned out after some serious head scratching I was using a `beforeModel` method and not calling `this._super`, which lead to this error.
