### ISSUE TITLE
Update example applications

### ISSUE THREAD

**Issue by cibernox** [simplabs/ember-simple-auth#542]
I've been trying to update to 0.7.3 to 0.8.0-beta.2 and remove the warnings about deprecated mixins without success.

It's hard to grasp the overall picture of how a 0.8.0-style authentation without a sample application.

Updating the current sample applications (or create new examples while this branch is still in beta) will help a lot.

**Comment by marcoow** [comment]
It would be great if the examples were Ember CLI applications - definitely would have to be once #522 merge of course. PR would be great!

**Comment by marcoow** [comment]
The example applications will have to be rewritten and moved to another app when 1.0 is ready anyway.
