### ISSUE TITLE
routeEntryComplete not cleaned up between acceptance tests

### ISSUE THREAD

**Issue by kbullaughey** [simplabs/ember-simple-auth#543]
The `routeEntryComplete` [local variable](https://github.com/simplabs/ember-simple-auth/blob/0a1120c0d324a3250eca9943ca04855855289aba/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L3) represents state leakage that doesn't get cleaned up between acceptance tests. On the very first acceptance test this flag gets set true, but then on subsequent acceptance tests it's still true, which means the target used for sending actions is the route rather than the transition and I get the error: 

> Error: Can't trigger action 'sessionInvalidationSucceeded' because your app hasn't finished transitioning into its first route. To trigger an action on destination routes during a transition, you can call `.send()` on the `Transition` object passed to the `model/beforeModel/afterModel` hooks.

Maybe this needs to be stored in something accessible to an initializer and set to false each time the application is created?

**Comment by marcoow** [comment]
Right - PR would be great!

**Comment by kbullaughey** [comment]
Submitted as #544.

I wasn't sure how to actually test this by writing a spec, so I just tested that the function can be called and then call it in the `setup()` which is called by the initializer. Would one need a dummy application an acceptance tests to test this? I didn't see any in the repo... I can confirm, however, in my own application that it solves my original problem.

**Comment by marcoow** [comment]
This will be fixed by #522 when all this will be handled in the application route's `beforeModel` method.
