### ISSUE TITLE
Why is ApplicationRouteMixin#invalidateSession() deprecated?

### ISSUE THREAD

**Issue by gauthierm** [simplabs/ember-simple-auth#547]
I understand that it is just a wrapper to `Session#invalidate()`, but is is quite useful to be able to use it as an action in the application template. If it were removed from ember-simple-auth I'd end up with the same method in my application route.

**Comment by marcoow** [comment]
Yes, that's correct - you just implement the action yourself. Either in the application route, another route, a controller or a component.
