### ISSUE TITLE
cookie-store: `restore` fails if no JSON is stored in cookie

### ISSUE THREAD

**Issue by ohcibi** [simplabs/ember-simple-auth#549]
The current implementation of `restore` clearly fails if the cookie does not contain valid json (i.e. there is no json stored in the cookie)

```javascript
      restore: function() {
        var data = this.read(this.cookieName);
        if (Ember.isEmpty(data)) {
          return {};
        } else {
          return JSON.parse(data); // fails if data contains no json
        }
      },
```

Also `persist` stores the data as JSON string no matter what. `renew` however seems to respect the possibility that the stored data is actually no json

```javascript
   data           = Ember.typeOf(data) === 'string' ? data : JSON.stringify(data || {});
```

JSON should just always be optional. I'd make a PR, just want to make sure that I'm not missing something.

**Comment by marcoow** [comment]
The content of the cookie should always be either JSON or empty. Would be cool if you could come up with a PR that removes unnecessary code though.

**Comment by ohcibi** [comment]
I've realized that the cookie stores some meta data as well. Wouldn't it be better to store the meta data in another cookie? This would better integrate with backends which maintain the content of the cookies. The expiration time is another thing. Its also maintained by the backend over here and I don't need to set it in `renew`

About unnecessary code: there is a `variable != {}` in `renew` here: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-cookie-store/lib/simple-auth-cookie-store/stores/cookie.js#L240
`x != {}` is always `true`... is this intentional?

**Comment by marcoow** [comment]
The cookie must be ignored by the backend. It's only used by Ember Simple Auth. To store its internat data. Request authorization is done via the authorizer of your choice.

**Comment by marcoow** [comment]
Closing this as I think it's more a misunderstanding than an actual bug.

**Comment by ohcibi** [comment]
It might be a misunderstanding but left like this it cannot be combined with other authenticators. In my use case the ember app is embedded in another app that does the authentication. It simply stores the token in a cookie and other metadata in other cookies. I only need to restore the token which fails because ember-auth expects a json string in the cookie. So I need to use a custom cookie store which just returns the cookie value if its not parseable json. It would increase compatibility if the store just puts the token in one cookie. There is not even a need to use json or serialization at all. Cookies are key-value stores anyways.

**Comment by marcoow** [comment]
The cookie is only used to store Ember Simple Auth's internal state and should never used by any other part of your system - neither server nor other front end components. If you want to integrate with another system via a cookie, use a dedicated cookie for that with a special authenticator that reads the authentication state that cookie.

**Comment by ohcibi** [comment]
Thats what I have tried. The problem is that the authenticators `restore` method is not called if the store could not read a parseable json string from the cookie I have configured with `cookieName`. Where should I read my special cookie if not in `restore`?

**Comment by marcoow** [comment]
`restore` validates an already existing ESA session. What you want to do is to use the cookie in the `authenticate` method and depending on whether it makes up a valid session resolve from that (the resulting session state will then be stored in ESA's own cookie).
