### ISSUE TITLE
Breaks Ember Inspector with Ember 1.13

### ISSUE THREAD

**Issue by NathanJang** [simplabs/ember-simple-auth#554]
Here is what I have installed in a completely new Ember (CLI) project:

```
DEBUG: -------------------------------
DEBUG: Ember             : 1.13.0
DEBUG: Ember Data        : 1.0.0-beta.19
DEBUG: jQuery            : 1.11.3
DEBUG: Ember Simple Auth : 0.7.3
DEBUG: -------------------------------
```

I am running Ember Inspector 1.8.1 on Chrome 44.0.2403.39 beta (64-bit) on the first beta of OS X El Capitan (OS X 10.11 (15A178w)). I have also tried this with Simple Auth 0.8.0-beta.3.
Also tested on the latest stable version of Chrome 34.0.1847.131 on OS X Yosemite.

When I open the Ember Inspector, it shows the "Ember application not detected!" screen. Reverting to Ember 1.12 does not yield this error, and neither does uninstalling Simple Auth from Ember 1.13.

**Comment by marcoow** [comment]
It seems more likely to me that this is a problem with Ember 1.13 than with Ember Simple Auth.

**Comment by NathanJang** [comment]
So far this issue has been specific to using it with Simple Auth though.

**Comment by marcoow** [comment]
So when you remove Ember Simple Auth from the project it works again?

**Comment by NathanJang** [comment]
That's correct.

**Comment by marcoow** [comment]
maybe @teddyzeenny can help? It's a bit hard when you're not getting any errors or so…

**Comment by NathanJang** [comment]
After more testing, I've discovered that there issues with Ember Inspector under other conditions. I shall open an issue there.
