### ISSUE TITLE
example with ember-cli, multiple providers

### ISSUE THREAD

**Issue by phatle** [simplabs/ember-simple-auth#555]
I can not find any tutorials to add ember-simple-auth to ember-cli app(ember 2.0.0beta). I saw that the guide is outdated. 

Thanks,

**Comment by marcoow** [comment]
This will be implemented in #522 - currently Ember 2.0 isn't supported as ESA needs to be converted to that it uses instance initializers.

**Comment by phatle** [comment]
Thanks
