### ISSUE TITLE
Restore does not work with 0.8.0-beta.3 + ember-cli-simple-auth-token

### ISSUE THREAD

**Issue by erichonkanen** [simplabs/ember-simple-auth#557]
Hello,

Posting this here since this may be related to the latest updates to the simple-auth package...

I'm trying to determine what has changed that breaks the [restore](https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/addon/authenticators/jwt.js#L101) functionality in the latest [ember-cli-simple-auth-token](https://github.com/jpadilla/ember-cli-simple-auth-token/releases/tag/v0.7.1)

Ive gone through the changelog and notice the breaking change relating to the `secure` keyword in the stored session data but not sure if that's related.

Just wondering if you have any ideas? Again the restore functionality worked in the 0.6.0 tag of the token package and so the breaking change may or may not be related to change in simple auth since the latest tag 0.7.1 requires using 0.8.0-beta.2+

Any help appreciated!

**Comment by marcoow** [comment]
The changes with the shouldn're require changes in the authenticators. You might want to ask for help in the https://github.com/jpadilla/ember-cli-simple-auth-token repo.

**Comment by erichonkanen** [comment]
@marcoow that's what I thought, I did submit an issue there but as one of the contributors I thought I'd also run it by you since you wrote the simple auth package and maybe Im missing something.. 

Did you get a chance to glance at that restore method?

Also, why isn't the jwt package listed anywhere on the simple auth side?

**Comment by marcoow** [comment]
https://github.com/jpadilla/ember-cli-simple-auth-token isn't part of Ember Simple Auth, it's an authenticator/authorizer package that you can use with ESA. I'm not sure how that's implemented internally.

**Comment by erichonkanen** [comment]
right I know that, just wondering why it isn't also listed as it makes use of ESA and is similar to e.g. esa oauth/esa devise etc..

anyways no worries ill keep looking into this thanks
