### ISSUE TITLE
Does not transition to /login

### ISSUE THREAD

**Issue by benedikt-d** [simplabs/ember-simple-auth#558]
I'm trying to implement Simple auth. I'm not getting the application to transit to /login when I use:
```javascript
import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin,{
});
```

I'm just getting a blank page instead. Also the documentation does not state where I can change the path it transitions to. As far as I understand it it should transition to /login as a standard.

**Comment by marcoow** [comment]
if you're seeing a blank page there's probably an error. Did you check the console? How do you routes look?

**Comment by benedikt-d** [comment]
Despite some deprecations and the warning that no authorizer is defined yet there is no error in the console. I'm using Ember 1.13.0 Ember Data 1.13.0 Ember Simple Auth : 0.8.0-beta.3 

```javascript
this.route('nowblankpages', {path: '/'}, function() {
  	this.route('alsoblank');
    this.route('nowblankpage', {path: '/:nowblankpage_id'});
  });
this.route('notblank');
```

**Comment by marcoow** [comment]
which route are you mixing the `AuthenticatedRouteMixin ` mixin into?

**Comment by benedikt-d** [comment]
the nowblankpages one ;-)

**Comment by marcoow** [comment]
And you actually have a login route, right? Please post your complete router.

**Comment by benedikt-d** [comment]
```javascript
import Ember from 'ember';
import config from './config/environment';

var Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('conversations', {path: '/'}, function() {
  	this.route('new');
    this.route('conversation', {path: '/:conversation_id'});
  });

  this.route('settings');
  this.route('contacts', function() {
    this.route('new');
  });
  this.route('login');
  this.route('register');
});

export default Router;
```

**Comment by benedikt-d** [comment]
I don't know if it might cause a problem that I'm using the pod structure in Ember CLI? Just guessing around in the dark here.

**Comment by marcoow** [comment]
That shouldn't be a problem

**Comment by benedikt-d** [comment]
I made a repo to reproduce my problem.
https://github.com/benedikt-d/EmberSimpleAuthProblem

**Comment by benedikt-d** [comment]
Very dumb mistake: Forgot to include the ApplicationRouteMixin in the Application route. There should be an error in the console though.

Also I'm still wondering where I can change the route the application is switching too?

**Comment by marcoow** [comment]
You can configure the `authenticationRoute`: http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Configuration-authenticationRoute

**Comment by benedikt-d** [comment]
https://github.com/simplabs/ember-simple-auth/pull/559
Maybe useful maybe not..
