### ISSUE TITLE
Spec with client_id and client_secret

### ISSUE THREAD

**Issue by bakura10** [simplabs/ember-simple-auth#56]
Hi,

Currently, Ember-Simple-Auth passes client_id and client_secret in post body. However, according to the spec (http://tools.ietf.org/html/rfc6749#section-2.3.1) this should be discouraged and we should use the Authorization header, using a base64 encoded string of "id:secret".

**Comment by ghostcodelover** [comment]
where do you doing this

Ember.SimpleAuth.Authenticators.OAuth2.reopen({
  serverTokenEndpoint: window.ENV.API_ENDPOINT + '/oauth/token',
  makeRequest: function(data) {
    data.client_id = window.ENV.OAUTH_ID;
    return this._super(data);
  }
});
