### ISSUE TITLE
Make session Ember.inject.service compatible

### ISSUE THREAD

**Issue by sukima** [simplabs/ember-simple-auth#561]
When the simple-auth-session is registered it uses the name `simple-auth-session:main`.

However, `Ember.inject` has only two functions allowed `controller` and `service` each resolves to either `controller:name` or `service:name` respectively. This means that someone who wants to use [`Ember.inject.service`](http://emberjs.com/api/classes/Ember.inject.html#method_service) in unable to because the helper looks for `service:simple-auth-session` not `simple-auth-session:main`.

The register setup should be ok with the former for the typical injection.

**Comment by marcoow** [comment]
see #522 - the session will be a service in 1.0.
