### ISSUE TITLE
Session inside component

### ISSUE THREAD

**Issue by Keeo** [simplabs/ember-simple-auth#562]
After upgrade from 0.7.3 to 0.8.0 I had to find out that session is no longer injected into components. I couldn't find anything related to this change, only merged issue(https://github.com/simplabs/ember-simple-auth/pull/372) mentioning that session is injected into components automatically. If this is desired behavior it should be mentioned somewhere or do I have migration bug in app?

**Comment by marcoow** [comment]
The session should definitely be injected into components - if it's not that's a bug. Please provide more info though or ideally set up a JSBin that illustrates the problem.

**Comment by Keeo** [comment]
Well that was pain to find but I finally got it.
Session is not injected into component when generated component.js file is deleted. I made repository showcasing issue. There are two components, one with default.js file and other without and some fake authorization process but thats not important.

https://github.com/Keeo/ember-simple-auth-bug-showcase/commit/e1a8e2d981e070231544a88efe9efdeedc0d47b2

**Comment by marcoow** [comment]
That's more an Ember CLI issue then I'd say (if not intentional anyway).

**Comment by Keeo** [comment]
Agree, especially that ember-cli is still at version for ember 1.12.
