### ISSUE TITLE
How to redirect to login page if get the 401 error?

### ISSUE THREAD

**Issue by JeskTop** [simplabs/ember-simple-auth#563]
Hi, 
I update my `ember-simple-auth` version 0.7.3 to 0.8.0. The user will get the 401 errors in console, but page can not redirect to login page. The problem like: http://stackoverflow.com/questions/30708081/how-to-redirect-to-login-page-if-get-the-401-error-when-i-use-ember-simple-auth

Any help please.

**Comment by nahtnam** [comment]
I am having this same issue.

**Comment by marcoow** [comment]
Did you configure the `crossOriginWhitelist`? If not, Ember Simple Auth will not include the `Authorization` header in requests to 3rd origins and thus not handle 401 (it only handles 401 errors for requests that it has authorized).

**Comment by nahtnam** [comment]
@marcoow But the requests are on the same domain. I am using Ember-CLI-Rails and so they both run on localhost:3000.

The authorization header is being successfully sent, but if I return a 401 (if the token is invalid), it just gets stuck on the loading route.

**Comment by marcoow** [comment]
Put a breakpoint here and check whether it is reached at all: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L238

**Comment by nahtnam** [comment]
@marcoow Ok, so I think I figured it out. Lets say I have a route for `/status` that returns 401. If you go to http://localhost:3000/status directly, it will redirect you to `/login` **but**, if you go to http://localhost:3000 and then use the navbar (`link-to`) to go to `/status`, it will just get stuck.

Let me know if that doesnt make sense, and ill explain it better.

Also, I put `debugger;`'s on that line you told me to but it is never called, when I use the navbar or when I directly go to `/status`.

**Comment by marcoow** [comment]
if the `authorizationFailed` action is never called it should actually never redirect you.

**Comment by nahtnam** [comment]
@marcoow Oh lol, my bad. I made a custom mixin but never changed the import. Now, when you directly go to /status, you get redirected but that code is never executed, but if you use the link-to, it does get executed but it doesnt enter the if statement (which makes sense).

Arent you supposed to have some code that stops the transition and redirects after the if statement?

**Comment by marcoow** [comment]
Not sure what you mean. The way the handler works is it invalidates the session after a 401 as it's assumed to be stale then.

**Comment by nahtnam** [comment]
@marcoow But how do we get it to redirect to `/login` after the session is invalidated?

**Comment by marcoow** [comment]
The [`sessionInvalidationSucceeded` action[(https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L212) handles the case when the session is invalidated and by default simply reloads the application's root url.

**Comment by nahtnam** [comment]
And how do I call that? Currently, I dont think its being executed.

**Comment by marcoow** [comment]
You don't manually call that at all - it's called automaticall whenever the session fires the `sessionInvalidationSucceeded` event - see https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L57.

**Comment by nahtnam** [comment]
Im a bit confused.

If `authorizationFailed`, then I want to redirect to either the root url or
the login route. If the user is logged out, and gets a 401, nothing happens
currently.

On Mon, Aug 3, 2015 at 10:37 AM Marco Otte-Witte <notifications@github.com>
wrote:

> You don't manually call that at all - it's called automaticall whenever
> the session fires the sessionInvalidationSucceeded event - see
> https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L57
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simplabs/ember-simple-auth/issues/563#issuecomment-127341250>
> .
>
-- 
Thanks.

**Comment by marcoow** [comment]
please provide sources - configuration, application route etc.

**Comment by nahtnam** [comment]
Not at home right now (will add code later).

Basically what I am trying to say is that it should call
`sessionRequiresAuthentication` after this line:
https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L240

On Mon, Aug 3, 2015 at 10:42 AM Marco Otte-Witte <notifications@github.com>
wrote:

> please provide sources - configuration, application route etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simplabs/ember-simple-auth/issues/563#issuecomment-127343650>
> .
>
-- 
Thanks.

**Comment by JeskTop** [comment]
I also use `Ember-CLI-Rails`. Can you tell me how to fix this problem ? @nahtnam

**Comment by nahtnam** [comment]
@JeskTop I noticed that if you get a 401, ember simple auth tries to logout.

You will never come across this situation if you put the authenticated route mixin.

**Comment by JeskTop** [comment]
@nahtnam Like this?
```
export default Ember.Route.extend({
  ...
  actions: {
    error(error, transition) {

      if (error && error.status === 401) {
        // error substate and parent routes do not handle this error
        return this.transitionTo('login');
      }

      // Return true to bubble this event to any parent route.
      return true;
    }
  }
});
```

**Comment by nahtnam** [comment]
@JeskTop I guess it would be better to extend this: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L212

**Comment by marcoow** [comment]
Automatic mapping of 401 to an error action on the application route has been dropped altogether in 1.0. You can now handle 401 e.g. in the Ember Data adapter and use the session service to invalidate the session there.

**Comment by gep13** [comment]
@marcoow what is the correct approach to handle redirecting to the login page, if a 401 response is received from an API call which is going through the DataAdapter?  I am handling the check in the `handleRepsonse` method, and calling invalidate, however, I don't see how I can correctly navigate to a different URL.  Can you provide any guidance please?  Thanks!

**Comment by marcoow** [comment]
You can use the [`DataAdapterMixin`](http://ember-simple-auth.com/api/classes/DataAdapterMixin.html) which does the same thing already. When the session is invalidated, the [`ApplicationRouteMixin`'s `sessionInvalidated` method](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionInvalidated) will be called which by default reboots (reloads) the application.

**Comment by gep13** [comment]
@marcoow well, that was stupidly simple!  Don't know how I missed that.  Thanks for the nudge!

**Comment by villander** [comment]
@marcoow But even doing reload of the application the error 401 keeps appearing in browsers or in the monitoring tool (Rollbar, Airbrake and etc) how to prevent this error from being leaked to the browser?

```
Ember Data Request GET https://gateway-api.example.com/app/merchant/processors returned a 401 Payload (Empty Content-Type) [object Object]
````
