### ISSUE TITLE
authenticate resolve after transition sucessfull

### ISSUE THREAD

**Issue by miguelcobain** [simplabs/ember-simple-auth#566]
I'm using the session's `authenticate` method on my login controller to perform authentication.
That methods returns a promise, and I'm using it to set a `isLoading` property on my controller.
This way I can conditionally show spinners, disable inputs, etc.

However, the route I'm transitioning to after authentication sucessful (through the `routeAfterAuthentication` configuration property), has a model hook that takes some time to resolve.

As a result, I'm seeing some UI flickering, because the `authenticate` promise resolves before the `model` hook of the `routeAfterAuthentication` route.

I was trying to avoid the use of `needs` in the target route and using `afterModel` to set the `isLoading` property back to false.

Ideally, the `authenticate` promise would only resolve when the transition to the target route successfully completed transition.
Is this possible?

**Comment by marcoow** [comment]
No, that'd not possible as the session doesn't actually know anything about the transition that's happening - it only sees the authenticator that returns a promise that will resolve at some point in time at which the session is authenticated and returns resolves the promise it returns as well.

**Comment by miguelcobain** [comment]
Right. Makes sense. Any ideas to achieve this? 
I believe it should be a common scenario.

**Comment by miguelcobain** [comment]
I ended up using the loading substate for the target route.
When authentication is successful I get a nice loading feedback.
