### ISSUE TITLE
Inadequate examples or concrete documentation of serverTokenEndpoint configuration.

### ISSUE THREAD

**Issue by cellis** [simplabs/ember-simple-auth#570]
For instance, the `serverTokenEndpoint` is not explained at all in the readme, and for that matter, neither are any of the other config variables. I'm trying to setup a devise backend with a rails server. I don't want to serve it with `ember server --proxy` so I need to whitelist the server's domain and add CORS support to the server. But how do I configure the frontend to connect to serverTokenEndpoint?

Viewing the docs for [simple auth devise](https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise) does not mention any way to change this variable, besides [importing it](http://ember-simple-auth.com/ember-simple-auth-devise-api-docs.html#SimpleAuth-Authenticators-Devise-serverTokenEndpoint): "`This value can be configured via SimpleAuth.Configuration.Devise#serverTokenEndpoint.`", but that is not explained in enough detail either.

Maybe I missed something?

**Comment by twbrandt** [comment]
I have a working demo at https://github.com/twbrandt/ember_auth_demo_web_client. Specifically, look at config/environment.js, where these values are set: https://github.com/twbrandt/ember_auth_demo_web_client/blob/master/config/environment.js

**Comment by cellis** [comment]
@twbrandt, thanks, this is very helpful and along the lines of what I'd expected. But I still think that info should be clarified in the readme.

**Comment by marcoow** [comment]
You're right - that should be explained better. Lots of the docs is going to change with #522 though anyway.

**Comment by marcoow** [comment]
should be fixed in 1.0
