### ISSUE TITLE
Ember-simple-auth-testing issue with authenticateSession()

### ISSUE THREAD

**Issue by ziggurat** [simplabs/ember-simple-auth#571]
@marcoow After running 
    
    authenticateSession();

I got this:

    currentSession().isAuthenticated (false)

Is that ok?

**Comment by marcoow** [comment]
You should alway use `get`:

```js
currentSession().get('isAuthenticated');
```

**Comment by ziggurat** [comment]
Still getting false. Will try to upload a sample project.

**Comment by ziggurat** [comment]
Could not reproduce it on a new project. Obviously something wrong with my project :) 

Sorry for the trouble.
