### ISSUE TITLE
Ember-CLI - Could not find module

### ISSUE THREAD

**Issue by lukeclewlow** [simplabs/ember-simple-auth#573]
Hi, I'm quite new to Ember-CLI, so apologies if I'm overlooking something straight forward here! I'm following the instructions outlined here: http://log.simplabs.com/post/90339547725/using-ember-simple-auth-with-ember-cli

However, when I get to 

```import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';```

I recieve the error

```Could not find module `ember-simple-auth/mixins/application-route-mixin` imported from `dashboard/routes/application` ```

Am I using the wrong path? I'm certain this is something simple, but just can't get past it!

Thanks for your help!

**Comment by jvenator** [comment]
@lukeclewlow I'm having the same issue with ember-cli 0.2.7 and ember 1.13.1. Would you mind sharing what your solution was? I can ping you outside of github if you'd like.

**Comment by lukeclewlow** [comment]
I think I ended up uninstalling the addons and then using the ```npm install --save-dev simple-auth``` and  ```ember g simple-auth``` instead of just ```ember install simple-auth``` and it miraculously seemed to solve my problem. 

Hope it works for you too!

**Comment by jvenator** [comment]
thanks for the fast reply. did you mean to write `npm install --save-dev ember-simple-auth` and `ember g ember-simple-auth` ?

also, did you use this on it's own or with torii?

**Comment by lukeclewlow** [comment]
Sorry, that is what I meant. I just didn't use the ```ember install``` 

I used it on its own for the time being.
