### ISSUE TITLE
oauth2 authorizer not found in container

### ISSUE THREAD

**Issue by fayimora** [simplabs/ember-simple-auth#576]
Hi, 

I am getting this weird error and I'm not sure why
![screen shot 2015-07-01 at 22 56 05](https://cloud.githubusercontent.com/assets/648684/8465804/92cc4470-2044-11e5-96a1-1e96ffd464d5.png)

Any ideas what's happening? This was a perfectly working app before I upgraded ember-cli from `0.2.1` to `0.2.7`. I checked the changelogs for ember-cli but couldn't find anything.

Here is my config:
```js
    ENV['simple-auth'] = {
      store: 'simple-auth-session-store:local-storage',
      crossOriginWhitelist: ['http://localhost:9000'],
      authorizer: 'simple-auth-authorizer:oauth2-bearer',
    };

    ENV['simple-auth-oauth2'] = {
      serverTokenEndpoint: ENV.api_host+'/oauth2/access_token'
    };
```
Cheers

**Comment by marcoow** [comment]
Have you installed both `ember-cli-simple-auth` and `ember-cli-simple-auth-oauth2`?

**Comment by fayimora** [comment]
Oh shoot thanks. I didn't have `ember-cli-simple-auth-oauth2` in my `package.json`. Silly me.
