### ISSUE TITLE
Devise: Using a different identificationAttributeName for sign_in POST vs Authorization token

### ISSUE THREAD

**Issue by nybblr** [simplabs/ember-simple-auth#577]
When authenticating a User to Devise, I send along `email` and `password` attributes.

The response is a `token` and `id` (the user's ID). I want to use the user's ID in the session *instead* of the email because it allows the user's email address to change without needing to log in/out again, and is more in line with traditional session authorization.

However, `identificationAttributeName` is used both for sign in **and** making the Authorization header as of: https://github.com/simplabs/ember-simple-auth/pull/403

It seems like there should be a separate configuration attribute for specifying login parameters (e.g. email and password) vs token header (e.g. user ID and token).

Thoughts? Hardwiring `password` as the authentication attribute feels strange too.

**Comment by nybblr** [comment]
@marcoow thoughts?

**Comment by marcoow** [comment]
I think hardwiring `password` shouldn't be a problem really as far as I know, devise always uses password based authentication.

Also having authentication and authorization work with the same attributes makes the whole thing much simpler. It should be easy to just write your own authorizer though that uses id and token instead of email and token.

**Comment by nybblr** [comment]
True, it is easier — but it seems less practical. If the user changes there email address, suddenly their session becomes invalid (or you get weird failures in other tabs/browsers that haven't gotten the update yet).

Defaulting to using the same attribute for authen and author seems like an okay default, but maybe not a realistic option for a lot of folks given many platforms (e.g. Rails) store a user ID in the cookie/session?

**Comment by marcoow** [comment]
The fact that users are logged out when their email changes might be the reason devise uses the email though.

**Comment by marcoow** [comment]
closing - please reopen if the problem persists

**Comment by matthooks** [comment]
Authenticating via `email` and authorizing via `id` is now possible since `identificationAttributeName` can be defined differently in the authorizer and authenticator as of ESA 1.0.0.

For example:

```
import DeviseAuthorizer from 'ember-simple-auth/authorizers/devise';

export default DeviseAuthorizer.extend({
  identificationAttributeName: 'id'
});
```

```
import DeviseAuthenticator from 'ember-simple-auth/authenticators/devise';

export default DeviseAuthenticator.extend({}); // Defaults to email
```

Then make sure things are handled properly in your controllers.

**Comment by nybblr** [comment]
Thanks @matthooks for the follow up; The new architecture made the change a one liner, and all's well!

**Comment by matthooks** [comment]
No problem, happy to help.
