### ISSUE TITLE
Pass response content via authenticators' resolved promises?

### ISSUE THREAD

**Issue by anulman** [simplabs/ember-simple-auth#580]
Hi simplabs :smile: 

Big fan of simple-auth here. I was just wiring up a login form against an API that passes the necessary user data as a sideloaded JSON object in the response.

Is there a reason you don't pass the response content up through the base authenticator's resolved promise [here](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/session.js#L177-L180)?

I think it would be very convenient / user-friendly to do so, as then you could write something like:

```javascript
// pseudocode / not exact
this.get('session').authenticate(data).then(function(response) {
  this.store.push('user', response.body.user);
});
```

Thanks!

**Comment by anulman** [comment]
P.S. I'd be happy to send through a PR with a test + edit if this is a feature you agree with

**Comment by marcoow** [comment]
All data that the authenticator resolves with is already accessible via the session's `secure` property (e.g. `this.get('session.secure.token')`). Making e.g. the current user accessible via the session is best done via a custom session with a computed property - see [this example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html).

Also there isn't necessarily a response for every authenticator you might be using - e.g. when you're authenticating against the Facebook SDK with a custom authenticator or so.

**Comment by anulman** [comment]
I understand. However, consider an authentication response that includes sideloaded data you may not want persisted in the session:

```
{
  token: 'foo',
  email: 'bar@baz.com',
  user: {
    // ...
  }
}
```

Let's assume `email` is mapped to the auth strategy's `identifier`. We definitely want to persist email && user in localstorage between reloads/visits, but the user object may be a lot of data (and adds risk!) to store there as well.

For sideloaded responses like this (which saves a round trip!), you currently need to:
 - read and persist `user` from the session;
 - rm `user` from the session;
 - add a `userId` to the session; and
 - manually persist the session again, as `user` is injected to `content.secure`.

Proposed resolution:
- store only the token and identifier in the secure object
    - alternately, let the auth strategy define what response objects to include in the secure object
- store all additional data on the base session for easier manipulation
    - alternately, pass all additional data through the resolved promise for manual handling

If this is not an edit you would consider, perhaps it would be best to add a notice about sideloading behaviour to the README?

**Comment by anulman** [comment]
Sample workaround code:

```
// routes/users/login

export default Ember.Route.extend({
  // ...

  actions: {
    authenticate: function(data) {
      let _this = this;
      let session = this.get('session');

      session.authenticate('simple-auth-authenticator:devise', data).
        then(function() {

        let sessionSecure = session.get('content.secure');
        let user = sessionData.user;

        // create user record in the store
        _this.store.push('user', user);

        // replace session's user object with only the id, for later fetching
        delete sessionSecure['user'];
        let newContent = {
          secure: sessionSecure,
          userId: user.id
        }

        session.set('content', newContent);
        session.get('store').persist(newContent); // not running automatically
      });
    }
  }

  // ...
});
```

```
// initializers/user-session

export default {
  // ...

  initialize: function(container) {
    Session.reopen({
      store: SimpleAuthLocalStorageStore,

      currentUser: Ember.computed('content.userId', function() {
        var id = this.get('content.userId');

        if (!Ember.isEmpty(id)) {
          return container.lookup('store:main').find('user', id);
        }
      })
    });
  }

  // ...
};
```

**Comment by marcoow** [comment]
You can solve the case you describe with a custom authenticator that only resolves with the data you want stored in the session and that also gets the Ember Data store injected and pushes the side loaded user record to that directly so that is's already present when the computed property in the session loads it from the store.

**Comment by anulman** [comment]
I understand that's the canonical approach, and an answer for this specific use case. Thanks :)

More broadly speaking, why does Simple Auth assume that all response data belongs in the session, vs. letting authenticators decide?

**Comment by marcoow** [comment]
Ember Simple Auth doesn't assume all response data to go into the session as it doesn't even assume there's a request/response at all. All data that the authenticator's `authenticate` method resolves with will go into the session, if the authenticator makes a request, that could very well only be a subset of the response.
