### ISSUE TITLE
ajaxError hook is only setup if using an authorizer

### ISSUE THREAD

**Issue by danpaz** [simplabs/ember-simple-auth#581]
I ran into an issue where the global [`ajaxError` hook](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/setup.js#L67) was not getting called on a 401 from the server. After some debugging I realized that [this line](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/setup.js#L94) was preventing the ajaxError hook from being setup _if no authorizer is configured_.

```
  if (!Ember.isEmpty(Configuration.authorizer)) {
    var authorizer = container.lookup(Configuration.authorizer);
    Ember.assert('The configured authorizer "' + Configuration.authorizer + '" could not be found in the container!', !Ember.isEmpty(authorizer));
    authorizer.set('session', session);
    ajaxPrefilter.authorizer = authorizer;
    ajaxError.session = session;

    if (!didSetupAjaxHooks) {
      Ember.$.ajaxPrefilter('+*', ajaxPrefilter);
      Ember.$(document).ajaxError(ajaxError);
      didSetupAjaxHooks = true;
    }
  } else {
    Ember.Logger.info('No authorizer was configured for Ember Simple Auth - specify one if backend requests need to be authorized.');
  }
```

I am using a [cookie store strategy](https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-cookie-store), so naturally I do not have an authorizer configured as it is not needed in this case. I can see the logic for not setting up the ajaxPrefilter hook but I think the ajaxError hook is still necessary if no authorizer is configured.

Anyway, I was able to get this working by generating "base" authorizer, but I would prefer not to have to do that. Maybe `Ember.$(document).ajaxError(ajaxError);` can be pulled out of this conditional so that it is always setup. What do you think?

**Comment by marcoow** [comment]
You should not use the cookie on the server side. The cookie is only used by Ember Simple Auth to store it's internal state and its internal structure might also change. Instead use an authorizer that passes the token in the `Authorization` header. The only purpose of the cookie store is when you need to support a browser that doesn't support `localStorage` or when you want to make sure the client session expires automatically.

**Comment by d6u** [comment]
@marcoow I think "want to make sure the client session expires automatically" is a valid use case right? So that means we have to use cookies in all cases.

**Comment by marcoow** [comment]
Sure, you can use the cookie store. You just should never use the cookie on the server side but configure an authorized instead.

**Comment by danpaz** [comment]
To clarify, I am not using the ember-simple-auth cookie on the server side. I essentially have two cookies, one generated server-side to authenticate api requests, and one from ember-simple-auth to track `isAuthenticated` within the ember-app (not used on the server). Using a server-side generated cookie is actually a pretty [common setup with passportjs](http://passportjs.org/docs/configure). One concern I had was how to keep the two cookies in sync, but it is actually not too hard because ember-simple-auth listens to ajax responses to decide the `isAuthenticated` state -- 200 from login means isAuthenticated, 401 means invalidate the session, etc. This is why I would like to take advantage of the `ajaxError` hook in the ember-simple-auth library, to react to 401s, without needing an authorizer.

**Comment by marcoow** [comment]
ESA is essentially a library for building token based authentication for stateless REST APIs. You're using it to track the authentication state on top of a stateful server API. You could do that just as well by simply checking for presence of that server issues cookie and wouldn't even need ESA for that.
