### ISSUE TITLE
Proper handling of session timeout on server

### ISSUE THREAD

**Issue by philippmayrth** [simplabs/ember-simple-auth#584]
Hi *,

what would be the proper handling of a session timeout by the server? eg. Where do i start the timer in Ember.js.

Philipp

**Comment by marcoow** [comment]
You can use token expiration. If you're using ESA's OAuth 2.0, that actually implements OAuth 2.0 expiration already: http://tools.ietf.org/html/rfc6749#appendix-A.14, If you're using a different strategy you can simple track the token expiration on the server and return a 401 if a request comes in with an expired token.
