### ISSUE TITLE
Update initializer to be an instance initializer

### ISSUE THREAD

**Issue by jnhuynh** [simplabs/ember-simple-auth#587]
Ember has [deprecated accessing the container instance insider of initializers][deprecated-initializers]. Instead there is this notion of `instanceInitializers`. We should update to mirror that.

We will need to update `setup.js` to work different or break it up into two separate methods. One that gets called by an `initializer` that has access to the registry and application and another to be called by `instanceInitialzier` that has access to the `instance.container`.

[deprecated-initializers]:http://emberjs.com/deprecations/v1.x/#toc_deprecate-access-to-instances-in-initializers

**Comment by jcope2013** [comment]
https://github.com/simplabs/ember-simple-auth/issues/517
https://github.com/simplabs/ember-simple-auth/pull/564
https://github.com/simplabs/ember-simple-auth/pull/560

**Comment by jnhuynh** [comment]
Sorry about that, should have checked more thoroughly.
