### ISSUE TITLE
Overriding 'host' configuration in the adapter causes custom authorizer not to run

### ISSUE THREAD

**Issue by ziggurat** [simplabs/ember-simple-auth#591]
Setting up a simple custom authorizer is not working when extending and setting the ```host``` property of the adapter. Example:

    import Base from 'simple-auth/authorizers/base';

    export default Base.extend({
      authorize: function(jqXHR, requestOptions) {
        jqXHR.setRequestHeader('AuthorizationCode', 'code');
        jqXHR.setRequestHeader('AuthorizationProvider', 'provider');
      }
    });

That works ok, but if I add this adapter:

    import DS from 'ember-data';
    
    export default DS.JSONAPIAdapter.extend({
      host: 'http://otherhost:2300'
    });

The authorizer never gets called.

I have created a sample project with the bug here: https://github.com/ziggurat/custom-authorizer-never-called

**Comment by marcoow** [comment]
You need to [configure `crossOriginWhitelist`](http://ember-simple-auth.com/ember-simple-auth-api-docs.html#SimpleAuth-Configuration-crossOriginWhitelist).
