### ISSUE TITLE
How do you lookup torii in a non-deprecated way?

### ISSUE THREAD

**Issue by JoshSmith** [simplabs/ember-simple-auth#592]
I extend an `OAuth2` authenticator with `facebook-oauth2` and use torii as a provider. When initializing torii, though, I do the following:

```
var FacebookAuthentication = {
  name: "facebook-authentication",
  before: "simple-auth",
  after: "torii",
  initialize: function(container, application) {
    var authenticator, torii;
    torii = container.lookup('torii:main');
    authenticator = FacebookAuthenticator.create({
      torii: torii
    });
    application.register("authenticator:facebook", authenticator, {
      instantiate: false
    });
  }
};
```

And of course I get deprecation warnings about it.

How should I be approaching this now?

**Comment by JoshSmith** [comment]
It actually looks like this might be a dupe of #517. If so, feel free to close.

**Comment by marcoow** [comment]
you need to use an instance initializer.
