### ISSUE TITLE
Cookie store makes authenticator's restore() and makeRequest functions keep on calling

### ISSUE THREAD

**Issue by ramesh1242** [simplabs/ember-simple-auth#594]
Hello,

I have been using Ember Simple Auth for authentication in my ember application. I am using simple-auth-oauth2 authenticator with refresh tokens. Earlier I used 'localStorage' Store for storing data. It was working perfectly without any issues.

For Invalidating session on browser close I switched to cookie based session store. After this change, it is continuously making calls to oauth2 authenticator's restore and makeRequest functions but I didn't see this behavior when I was using  'localStorage' Store.

Below are the environment setting I used:
ENV['simple-auth'] = {
    store: 'simple-auth-session-store:cookie',
    crossOriginWhitelist: ['*']
  };

ENV['simple-auth-cookie-store'] = {
    cookieName: 'my-custom-cookie-name',
    cookieExpirationTime: 60    
  };

What might be  the cause for this behavior. Can somebody please explain about this. 
Thanks in advance.

**Comment by marcoow** [comment]
What's the content of your cookie when the described situation occurs? Also does the cookie content change during these continuous calls?

**Comment by ramesh1242** [comment]
Hello Marco, Thanks for your reply.

The cookie content is access_token, token_type, refresh_token and expires_in. 
Yes, access_token is getting changed during these continuous calls.

**Comment by marcoow** [comment]
Please copy/paste the cookie content as well as your configure here.

**Comment by marcoow** [comment]
closing - please reopen if the problem persists.
