### ISSUE TITLE
Deprecation warning on Ember 1.13.5

### ISSUE THREAD

**Issue by dmagunov** [simplabs/ember-simple-auth#596]
Hello,

on Ember 1.13.5 I've get next deprecation "DEPRECATION: `lookup` was called on a Registry. The `initializer` API no longer receives a container, and you should use an `instanceInitializer` to look up objects from the container. See http://emberjs.com/guides/deprecations#toc_deprecate-access-to-instances-in-initializers for more details."

**Comment by marcoow** [comment]
see #595, #587, #522 etc.

**Comment by dmagunov** [comment]
@marcoow one more question. It's not working with latest Ember version?

**Comment by EVILoptimist** [comment]
@dmagunov 0.8.0 is currently working for me with Ember.js 1.13.5

**Comment by dmagunov** [comment]
@EVILoptimist  with custom Authenticator?

**Comment by EVILoptimist** [comment]
@dmagunov  https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-oauth2
