### ISSUE TITLE
Consider using something other than "content"

### ISSUE THREAD

**Issue by davewasmer** [simplabs/ember-simple-auth#598]
The ESA 1.0 blog post mentioned plans to ditch the proxying behavior of the session service, and instead access the session data directly via the `content` property.

I'm all for ditching the proxying behavior, but I'd like to suggest that you consider a name other than `content` for the data namespace. `content` is used by proxy objects everywhere, and it's generally a bad idea to reach into the `content` of a proxy directly. Even though the session service will _not_ be a proxy any longer,I know when I see an object with a `content` property, my first assumption is that it is a proxy. And it's often quite difficult to tell if it's not.

I'm imagining all sorts of potential confusion when newcomers try using the service session like a proxy, and either end up confused as to why their `service.myProperty` is undefined, or they start binding directly to `content.myProperty` on other proxy objects because that's how ESA says to do it.

**Comment by marcoow** [comment]
Good point - suggestion for an alternative would be nice ;)

**Comment by davewasmer** [comment]
Fair enough :wink:

Perhaps `data`?

**Comment by marcoow** [comment]
Sounds good. Would you want to send a PR (targeting the `ember-cli-addon` branch)?
