### ISSUE TITLE
CORS Cookie

### ISSUE THREAD

**Issue by philippmayrth** [simplabs/ember-simple-auth#600]
Hi,

awesome plugin!
can someone help me with activating a CORS Cookie? This is what I've tried so far:

```
// authorizers/custom.js
import Base from 'simple-auth/authorizers/base';

export default Base.extend({
  authorize: function(jqXHR, requestOptions) {
  	requestOptions.withCredentials = true;
  	jqXHR.crossDomain = true;
  }
});
```

```
// config/environment.js
......
	'simple-auth': {
		authorizer: 'authorizer:custom',
		crossOriginWhitelist: ['http://localhost']
	},
.....
```

And on the Server I added the header Access-Control-Allow-Credentials: true.
Note: The rest of the CORS headers are already there and they are working only the CORS Cookie makes some problems.

Thanks for your advice.
Philipp

**Comment by marcoow** [comment]
Not sure what you're trying to do or what the problem is but you don't want to send a cookie from the client to the server as you're using an authorizer which sets the `Authorization` header and thus replaces the cookie.

**Comment by philippmayrth** [comment]
"...which sets the Authorization header and thus replaces the cookie."
Ok I see, knowing this I came up with this code in an initializer. Thanks!

```
  $.ajaxPrefilter( function( options, originalOptions, jqXHR ) {
	  options.crossDomain ={
	    crossDomain: true
	  };
	  options.xhrFields = {
	    withCredentials: true
	  };
});

´´´

**Comment by marcoow** [comment]
What do you need these settings for?

**Comment by philippmayrth** [comment]
I´m running an Ember-Cli Dev Server on http://localhost:4200 and the api on http://localhost:80. The API uses Cookies for authentication, now always I wanted to test if an API Call is working I had to build the whole project and run it on http://localhost:80. That was quite annoying - but thats over now ;-)

**Comment by marcoow** [comment]
As I said above, you shouldn't use a Cooke for authorization - at least that's not how ESA works. It will inject the `Authorization` header instead.
