### ISSUE TITLE
When observing secure.access_token and the session is restored is it supposed to trigger twice on the same data?

### ISSUE THREAD

**Issue by kitsunde** [simplabs/ember-simple-auth#606]
I'm implementing my own session and I'm using the OAuth2 authenticator. I was trying to set the logged in user on auth which is getting triggered twice in the following code:

```javascript
var SessionWithCurrentUser = Session.extend({
  setUserOnLogin: function(){
    if (Ember.isEmpty(this.get('secure.access_token'))){
      return;
    }
    console.log("this happens twice with the same", this.get('secure.access_token'));
  }.observes('secure.access_token'),
  test: function(){
    console.log("this happens once")
  }.observes('isAuthenticated')
});
```

Is that supposed to happen when nothing has changed. I will observe `isAuthenticated` for my purposes, but I wanted to highlight it since I found it surprising.

**Comment by marcoow** [comment]
You shouldn't use an observer to provide the authenticated user via the session - see e.g. [this example](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html) for info how to do it.

**Comment by kitsunde** [comment]
That wasn't really what I was asking, but I'll take that as a yes. ;)

I've seen your example, thanks. I'm using an observer because I want to have my user pre-loaded, it's pretty awkward to poke the property to achieve the same thing. But sure I suppose I could make a service that pokes it.

**Comment by marcoow** [comment]
When you want to make sure the user is loaded already you should load it in the route's `model` hook instead.

**Comment by kitsunde** [comment]
I understand why you're suggesting that and why your example is structured that way, but I don't want to wait for the data to load in between being logged in and moving onto the various other views or referencing it in various actions or components. I really do want to pre-load it on an application level.

Thanks for your suggestion though.
