### ISSUE TITLE
`container.lookup` is removed in Ember.js beta 4 and up

### ISSUE THREAD

**Issue by mattma** [simplabs/ember-simple-auth#607]
I am getting the error below

```
DEBUG: -------------------------------
DEBUG: Ember             : 2.0.0-beta.5
DEBUG: Ember Data        : 2.0.0-beta.1
DEBUG: jQuery            : 2.1.4
DEBUG: Ember Simple Auth : 0.8.0
DEBUG: -------------------------------
simple-auth.amd.js:375Uncaught TypeError: container.lookup is not a function
```

I tried to narrow down the error source, and confirmed it is not an Ember error. 

Ember has been deprecated `container.lookup` at `2.0.0-beta.5`. Please, see the [changelog](https://github.com/emberjs/ember.js/blob/v2.0.0-beta.5/CHANGELOG.md#200-beta4-july-31-2015). Check out the last item in the list. `#11897 [CLEANUP] Remove globals lookup from templates.`

I have tested in `2.0.0-beta.5` and `2.0.0-beta.4`. it does not work. 
and in `2.0.0-beta.3`, it works fine. Since `container.lookup` is a function.

There are several places in `simple-auth.amd.js` uses `container.loopup`. Is it on your roadmap to update to the latest Ember?

**Comment by marcoow** [comment]
see #602
