### ISSUE TITLE
[jj-abrams] application route's beforeModel() not called

### ISSUE THREAD

**Issue by mdehoog** [simplabs/ember-simple-auth#608]
The `beforeModel(transition)` function on the application route is not being called, due to the `setup-session-restoration.js` instance-initializer reopening the route class and overriding beforeModel() without calling `this._super` correctly.

`this._super` is called asynchronously (see https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/instance-initializers/setup-session-restoration.js#L9), which is apparently not supported:

http://emberjs.com/blog/2014/03/30/ember-1-5-0-and-ember-1-6-beta-released.html#toc_ever-present-_super-breaking-bugfix

Also see this answer: http://stackoverflow.com/a/25902755

**Comment by marcoow** [comment]
fixed by #609/#625
