### ISSUE TITLE
Lockstep versioning with Ember?

### ISSUE THREAD

**Issue by elbeezy** [simplabs/ember-simple-auth#614]
I'm sure this has been considered/discussed but wanted to throw it out there since I didn't see an existing issue. IMO it would be immensely helpful to users to version the new ESA (the jj-abrams PR) as 2.0.

**Comment by marcoow** [comment]
I'm not so sure about that as it would only really make sense if ESA was part of the "official" Ember bundle (like ember-cli, ember data, liquidfire etc). If we align the 2.0 version then we would also have to align all following versions including patch level releases etc.

While it might make sense to have ESA be part of the "official" bundle (easier discoverability being the biggest win probably), not being part of that bundle allows for bigger flexibility of course.

**Comment by marcoow** [comment]
Don't think this is going to happen anytime soon actually.
