### ISSUE TITLE
sessionAuthenticationSucceeded event.

### ISSUE THREAD

**Issue by alejandrogutierrez** [simplabs/ember-simple-auth#615]
I want to overwrite sessionAuthenticationSucceeded event to extend the behaviour after transition.
Like this:

```javascript
import Ember from 'ember';
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  actions: {
    sessionAuthenticationSucceeded: function() {
      this._super().promise.then(function() {
        // Do something great after transition to Configuration.routeAfterAuthentication.
      }
    }
  }
});
```

But I'm getting a problem because of sessionAuthenticationSucceeded event is not returning the transition.

The problem is here:
https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L155

I think it should be:
```javascript
return this.transitionTo(Configuration.routeAfterAuthentication);
```

What do you think. Am I missing something?

**Comment by marcoow** [comment]
When you want to do sth. **after** the transition you should probably do that in the route you're transitioning to.

**Comment by alejandrogutierrez** [comment]
I want to do something only when the transition goes from login to index route. If I do that thing in the route I'm transitioning to I'll get that thing every time I reload the page, right?

I want to set an alert message with a text like ''Signed in successfully". I do this in the route I'm transitioning to I'll get the message even when I reload the page.

Am I missing something?

**Comment by marcoow** [comment]
Sure, you're right. In that case though it's probably better to do that where you call the session's `authenticate` method, e.g.

```js
this.get('session').authenticate(…).then(() => {
  // show the flash message here
})
```

**Comment by alejandrogutierrez** [comment]
If I do this:
```javascript
this.get('session').authenticate(…).then(() => {
  // show the flash message here
})
```

The callback is getting executed before the route I'm transitioning to has executed its route hooks (beforeModel, setupController, renderTemplate, etc). I think that it is not a good place to put that functionality.

**Comment by alejandrogutierrez** [comment]
The most obvious place to add it's after transition has finished.
Why isn't this a good solution?

```javascript
return this.transitionTo(Configuration.routeAfterAuthentication);
```

**Comment by marcoow** [comment]
You can simply override the application route's `sessionAuthenticationSucceeded` event (or not use the mixin at all and handle the session events manually - `ApplicationRouteMixin` is actually just an optional convenience mixin). Be aware thought that `transitionTo` doesn't return a promise that resolves after the transition completes but a transition object.
