### ISSUE TITLE
ember-simple-auth dependency version of torii have deprecated code that won't work in ember 2.0.0

### ISSUE THREAD

**Issue by ziggurat** [simplabs/ember-simple-auth#616]
The current torii version in the dependency is old and contains code that was deprecated in the last versions of ember (1.13.X) and removed in ember 2.0.0. This causes deprecation warnings in 1.13 but crashes when using ember > 2.0.0. Is it possible to update the dependency version?

**Comment by marcoow** [comment]
PR against the `jj-abrams` branch would be cool.

**Comment by ismay** [comment]
Any updates on this? Looking forward to using ember-simple-auth with ember 2.0.

**Comment by marcoow** [comment]
@ismay: want to submit a PR?

**Comment by ismay** [comment]
@marcoow  What needs to be done exactly? I'm rather busy atm, but I might be able to find time for a simple PR.

**Comment by marcoow** [comment]
@ismay: should be sufficient to add the latest version of torii to the [`package.json`](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/package.json).

**Comment by marcoow** [comment]
fixed in `jj-abrams`
