### ISSUE TITLE
Handle 302s Properly

### ISSUE THREAD

**Issue by nahtnam** [simplabs/ember-simple-auth#617]
Hey!

I noticed that ember simple auth doesnt really handle 302's. When my server returns one, instead of redirecting or transitioning routes, it just makes another api call.

I think ember-simple-auth should redirect or transition to the route specified in the 302 if it does get one. My current use case is if the user has not completed their registration, I want them to be redirected to the settings page, but there is no way I can do that via the API. I have extended the application route to do that, but if someone bypasses it or implements their own website using my api, I want ember to be able to handle it.

Thanks.

**Comment by marcoow** [comment]
ESA ist form authentication/authorization only and 302 doesn't really have anything to do with that. 

Also you don't want to use server side redirects with single page apps anyway.

**Comment by nahtnam** [comment]
@marcoow So what are you supposed to return for an incomplete registration? 302 seems to be the only valid answer.

**Comment by marcoow** [comment]
You have to return an error (with status 422 or so) and handle that on the client side. You can just not redirect from the server as the server API shouldn't even know about the client routes at all.

**Comment by nahtnam** [comment]
You are right. Thank you for your help/explanation.
