### ISSUE TITLE
ember-simple-auth.js:423: Uncaught TypeError: container.lookup is not a function

### ISSUE THREAD

**Issue by edsonschleiwabion** [simplabs/ember-simple-auth#620]
I cloned the project, checkout the 0.8.0 tag version and run the $ grunt server Command, I need to implement a custom server authentication, but the example doesn't works.

http://localhost:8000/examples/

then I selected the "Custom Server example" Option

http://localhost:8000/examples/6-custom-server.html

Then the console show the following error and erro stack:

Uncaught TypeError: container.lookup is not a function

Line 423:  this.applicationRootUrl = container.lookup('router:main').get('rootURL') || '/';

```javascript
ember-simple-auth.js:
423 Uncaught TypeError: container.lookup is not a function(anonymous function) 
@ ember-simple-auth.js:423__exports__.default 
@ ember-simple-auth.js:1646__exports__.default.initialize 
@ ember-simple-auth.js:449(anonymous function) 
@ ember.js:4161(anonymous function) 
@ ember.js:4184visit 
@ ember.js:2194DAG.topsort 
@ ember.js:2305_emberRuntimeSystemNamespace.default.extend._runInitializer 
@ ember.js:4183_emberRuntimeSystemNamespace.default.extend.runInitializers 
@ ember.js:4159_emberRuntimeSystemNamespace.default.extend.boot 
@ ember.js:4068_emberRuntimeSystemNamespace.default.extend.domReady 
@ ember.js:4054Backburner.run 
@ ember-template-compiler.js:284Backburner.join 
@ ember-template-compiler.js:323run.join 
@ ember-template-compiler.js:8566run.bind 
@ ember-template-compiler.js:8629jQuery.Callbacks.fire
@ jquery-2.1.3.js:3094jQuery.Callbacks.self.fireWith 
@ jquery-2.1.3.js:3206jQuery.extend.ready 
@ jquery-2.1.3.js:3412completed 
@ jquery-2.1.3.js:3428

```

**Comment by marcoow** [comment]
The examples use the latest Ember Release version which now is 2.0 which isn't supported by ESA 0.8. 1.0 will be released soon though (see #602) so the examples won't be fixed anymore (unless someone wants to submit a PR of course).
