### ISSUE TITLE
simple-auth-authenticator:devise .authenticate does not return server response when promise resolves

### ISSUE THREAD

**Issue by clov3rly** [simplabs/ember-simple-auth#622]
The [API docs](http://ember-simple-auth.com/ember-simple-auth-devise-api-docs.html#SimpleAuth-Authenticators-Devise-authenticate) for the authenticate method state (in highlighted yellow):

> If the credentials are valid and authentication succeeds, a promise that resolves with the server's response is returned

Maybe I'm missing something, but I should then be able to access the server response by tacking on a `.then` function to the call to `authenticate`, as below:

```
#controllers/login.js
import Ember from 'ember';
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';

export default Ember.Controller.extend(LoginControllerMixin, {
  actions: {
    authenticate: function() {
      var 
        data = this.getProperties('identification', 'password')
      
      return this.get('session')
        .authenticate('simple-auth-authenticator:devise', data)
        .then(function(value) { 
          console.log(value);      // => undefined
        })
    }
  }
});
```

Am I misunderstanding the promise contract (entirely possible), or is this a bug?

I can see the server's response data in the devtools network tab.

**Comment by marcoow** [comment]
The authenticator's `authenticate` method is called by the session which will take the value it resolves with and store it in its `secure` property so what you'll want to is:

```js
import Ember from 'ember';
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin';

export default Ember.Controller.extend(LoginControllerMixin, {
  actions: {
    authenticate: function() {
      var data = this.getProperties('identification', 'password')

      return this.get('session')
        .authenticate('simple-auth-authenticator:devise', data)
        .then(() => {
          console.log(this.get('session.secure'));
        })
    }
  }
});
```

**Comment by yock** [comment]
@marcoow Is this explanation still valid? In working with 1.1.0-beta3 I'm finding both the `response` object and `session.secure` to be undefined.

**Comment by marcoow** [comment]
This isn't really up to date anymore but the [API of the session service](http://ember-simple-auth.com/api/classes/SessionService.html) is generally still quite similar.
