### ISSUE TITLE
Could not find module `simple-auth/mixins/application-route-mixin` imported from `searchapp-admin-gui/routes/application`

### ISSUE THREAD

**Issue by edsonschleiwabion** [simplabs/ember-simple-auth#627]
package.json

{
  "name": "ZZZZ",
  "version": "0.0.0",
  "description": "Small description for ZZZZ goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "1.0.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.12",
    "ember-cli-stylus": "1.0.4",
    "ember-cli-uglify": "1.0.1",
    "ember-cli-windows-addon": "^1.2.2",
    "ember-export-application-global": "^1.0.2",
    "ember-simple-auth": "simplabs/ember-simple-auth#jj-abrams"
  },
  "dependencies": {
    "ember-cli-babel": "^5.0.0",
    "ember-cli-jquery-ui": "0.0.19",
    "ember-cli-htmlbars": "0.7.6"
  }
}

bower.json

{
  "name": "ZZZZ",
  "dependencies": {
    "ember": "~1.12.0",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.4",
    "ember-qunit": "0.3.2",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.15",
    "jquery": "^1.11.1",
    "loader.js": "ember-cli/loader.js#3.2.0",
    "qunit": "~1.17.1",
    "jquery-ui": "1.11.4"
  }
}

ember-cli-build.js

var EmberApp = require('ember-cli/lib/broccoli/ember-app');
module.exports = function(defaults) {
    var app = new EmberApp(defaults, {});
    return app.toTree();
}

Error:
```javascript
Uncaught Error: Could not find module `simple-auth/mixins/application-route-mixin` imported from `ZZZZ/routes/application`requireFrom 
@ loader.js:110reify 
@ loader.js:97mod.state 
@ loader.js:140tryFinally 
@ loader.js:21requireModule 
@ loader.js:139Ember.DefaultResolver.extend._extractDefaultExport 
@ ember-resolver.js:367resolveOther 
@ ember-resolver.js:109superWrapper
 @ ember.debug.js:17185exports.default.EmberObject.default.extend.resolveRoute 
@ ember.debug.js:4746exports.default.EmberObject.default.extend.resolve 
@ ember.debug.js:4590resolve 
@ ember.debug.js:4433resolve 
@ ember.debug.js:2109Registry.resolve 
@ ember.debug.js:1715factoryFor 
@ ember.debug.js:1317instantiate 
@ ember.debug.js:1375lookup
 @ ember.debug.js:1273Container.lookup 
@ ember.debug.js:1208setupSessionRestoration 
@ setup-session-restoration.js:10initialize 
@ simple-auth.js:8(anonymous function) 
@ ember.debug.js:4110(anonymous function) 
@ ember.debug.js:4126visit 
@ ember.debug.js:2147DAG.topsort
 @ ember.debug.js:2259Namespace.default.extend._runInitializer 
@ ember.debug.js:4125Namespace.default.extend.runInstanceInitializers 
@ ember.debug.js:4108Namespace.default.extend.didBecomeReady 
@ ember.debug.js:4140Queue.invoke 
@ ember.debug.js:878Queue.flush
 @ ember.debug.js:943DeferredActionQueues.flush 
@ ember.debug.js:748Backburner.end 
@ ember.debug.js:173Backburner.run 
@ ember.debug.js:228Backburner.join 
@ ember.debug.js:247run.join 
@ ember.debug.js:15506run.bind 
@ ember.debug.js:15568jQuery.Callbacks.fire
 @ jquery.js:3148jQuery.Callbacks.self.fireWith 
@ jquery.js:3260jQuery.extend.ready 
@ jquery.js:3472completed 
@ jquery.js:3503
```

**Comment by marcoow** [comment]
Please check the [dummy app](https://github.com/simplabs/ember-simple-auth/tree/jj-abrams/tests/dummy) for guidance on how to use the `jj-abrams` branch.
