### ISSUE TITLE
Session data in a model 

### ISSUE THREAD

**Issue by owenek1** [simplabs/ember-simple-auth#628]
Hi everybody, 
I have a problem with using custom session data in a model. I want to use a user id in order to retrieve a company that is assigned to a specific user. In the route for company profile I am doing something like that: 
```javascript
export default  Ember.Route.extend(AuthenticatedRouteMixin,
{
  model: function(){
    return Ember.RSVP.hash({
      company: this.store.find('company',this.get('session.content.currentUser.companyId')),
      industries: this.store.find('industry')
    });
  }
});
}
```
Everything works when you go to that route from different route, but if you will refresh the page (F5) then I got following error: company.profile Assertion Failed: You may not pass `undefined` as id to the store's find method. In the console we can see following: 
![selection_061](https://cloud.githubusercontent.com/assets/5931978/9354967/f89a4116-4674-11e5-8837-fc301f3e63d2.png)

Does somebody of you can help me with solving it out? How can I wait for the session to be set and then let model to fetch their data? I am using a custom:session in following way: 
```javascript
export default Session.extend({
    setCurrentUser: function() {
      var accessToken = this.get('secure.access_token');
      var userId = this.get('secure.user_id');
      var _this = this

      if (!Ember.isEmpty(accessToken)) {
          return _this.container.lookup('store:main').find('user', userId).then(function(user) {
          _this.set('content.currentUser', user);
        });
      }
    }.observes('secure.access_token')
});
```

Thanks!

**Comment by marcoow** [comment]
See the ["authenticated account example"](https://github.com/simplabs/ember-simple-auth/blob/master/examples/4-authenticated-account.html#L132) to learn how to make the current user available via the session - the main point is you'd want to add a computed property that returns a promise instead of using an observer.

**Comment by owenek1** [comment]
Hello @marcoow, I have done it as you suggested. The only problem is that I want to use a session data (companyId that is assigned to the user) in a model call. Currently my route for user profile looks like that: 

```javascript
import Ember from 'ember';
import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin';

export default Ember.Route.extend(AuthenticatedRouteMixin, {
	model: function() {
	    return Ember.RSVP.hash({
				industries: this.store.findAll('industry'),
				industryroles: this.store.findAll('industryrole'),
				company: this.store.find('company',this.session.get('user.companyId'))
		});
	},
	setupController: function(controller, model) {
      controller.set('industries', model.industries);
      controller.set('industryroles', model.industryroles);
      controller.set('company', model.company);
  }
});
``` 
Everything works correctly, expect that when you are in user/profile route and you press F5 the I have the error of undefined id for store. Do I need to do some additional steps ?

**Comment by marcoow** [comment]
Post this on stackoverflow - this is about how ember and promises work and doesn't relate to ESA really.
