### ISSUE TITLE
sessionAuthenticationSucceeded not triggered

### ISSUE THREAD

**Issue by deafff** [simplabs/ember-simple-auth#630]
in simple-auth, setup: function(authenticator, secureContent, trigger) 
there is a line: 
trigger = !!trigger && !this.get('isAuthenticated');

I'm having trouble understanding the logic behind this. Shouldn't it say trigger = trigger && this.get('isAuthenticated') instead? 
Because as it is, even if trigger is true and isAuthenticated is true, sessionAuthenticationSucceeded is not triggered and route is not transitioned as it should.
Or maybe this should be better parenthesized/commented for clarity?

**Comment by marcoow** [comment]
`trigger = !!trigger && !this.get('isAuthenticated');` is the same as `trigger = trigger && !this.get('isAuthenticated');` if `trigger` is a boolean already - otherwise it will make sure that `trigger` is a boolean before using its value as one.

What's the actual bug though?

**Comment by deafff** [comment]
sessionAuthenticationSucceeded is not triggered after authentication (trigger ends up as false, even though in my opinion, if trigger is passed in as true and isAuthenticated is true, sessionAuthenticationSucceeded should run.

**Comment by marcoow** [comment]
The event will be triggered when `trigger` is passed as `true` and `this.get('isAuthenticated')` is `false` (it will not trigger the event when the session was already authenticated).

**Comment by deafff** [comment]
oh, ok, now I get it, I wasn't invalidating the previous session before trying to log in again. thanks, you can delete this.
