### ISSUE TITLE
401 error does not trigger authorizationFailed action

### ISSUE THREAD

**Issue by DVG** [simplabs/ember-simple-auth#631]
When I have a token expire on the server, the 401 error is rendering the error page rather triggering the authorizationError action.

I'm currently using an "empty" authorizer:

```
`import Ember from 'ember'`
`import Base from 'simple-auth/authorizers/base'`

CustomAuthorizer = Base.extend({})

initialize = (container, app) ->
  container.register('authorizer:custom', CustomAuthorizer)

AuthorizerInitializer =
  name: 'authorizer'
  before: 'simple-auth'
  initialize: initialize

`export {initialize}`
`export default AuthorizerInitializer`
```

This is because my app consumes multiple APIs, so I'm setting the authorization header for each API at the adapter level like this:

```
ApplicationAdapter = DS.ActiveModelAdapter.extend
  namespace: 'api/v1'
  headers: Ember.computed "session.authToken", "session.email", ->
    return { "Authorization": "Token token=#{@get("session.authToken")}, email=#{@get("session.email")}" }
```

And a very similar setup with different tokens for the other API's adapter.

I can see by setting breakpoints that I'm hitting [this line](https://github.com/simplabs/ember-simple-auth/blob/6eec0d10a2287dbb2b8067a3deb9a4db099860a9/packages/ember-simple-auth/lib/simple-auth/setup.js#L62) where I would expect the request to be "authorized" and the 401 would thereby trigger the authorizationFailed action.

**Comment by marcoow** [comment]
Is [this](https://github.com/simplabs/ember-simple-auth/blob/6eec0d10a2287dbb2b8067a3deb9a4db099860a9/packages/ember-simple-auth/lib/simple-auth/setup.js#L69) ever executed?

**Comment by DVG** [comment]
Yes.

> jqXHR.__simple_auth_authorized__
true

> jqXHR.status
401

For the record, the error page has already rendered at the breakpoint, and it runs the line to trigger the action, but it doesn't invalidate the session or redirect to login.

**Comment by DVG** [comment]
Nevermind!

After digging into the application route mixin, I realized the events were registered in the before model hook, which I was unwisely overriding without calling super.
