### ISSUE TITLE
Change the URL to get the Account by ID /accounts/{id}

### ISSUE THREAD

**Issue by edsonschleiwabion** [simplabs/ember-simple-auth#632]
Using as base the dummy sample project of the jj-adams branch, I create a new app, now I put it in a login.war file, I create the required servlets /token, /revoke, /accounts, I update the configuration for the  /token and /revoke but I couldn't find where to change the /accounts/{id} that is called after the login process.

      ENV['simple-auth'] = {
        base: {
          store: 'session-store:local-storage'
        },
        oauth2: {
          serverTokenRevocationEndpoint: '/login/revoke',
          serverTokenEndpoint: '/login/token'
        }
      };

where I change it to execute /login/accounts/{id} ?

**Comment by marcoow** [comment]
The request to load the account isn't actually part of ESA but comes from an example [session account service](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/tests/dummy/app/services/session-account.js) that you might implement in your application as well - requesting whatever route works for you.

**Comment by edsonschleiwabion** [comment]
Sorry,
but I didn't get what I need to change there.
Do you know a link that explain what is necessary to change to update the url to /login/accounts ?

**Comment by marcoow** [comment]
The service is sth. that you would implement in your own application in a way that fits your needs. It uses an `account` Ember Data model that you might or might not use in your own app as well.

**Comment by edsonschleiwabion** [comment]
reading the doc of : http://emberjs.com/api/data/classes/DS.RESTAdapter.html

I update the file : /app/adapters/application.js
export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:application',
  namespace: 'login'
});

now it is using the correct URL.
