### ISSUE TITLE
v1.0 authorizer - no way to modify query parameters?

### ISSUE THREAD

**Issue by dennis** [simplabs/ember-simple-auth#634]
In our authorizer in 0.8 I  had access to jqXHR and therefor was able to add an additional query parameter, which I need for the backend.

Now,  in 1.0 it seems that I am only able to add HTTP headers in the authorizer. Is this correct? Any plans of adding support, so I can modify the query parameters?

**Comment by marcoow** [comment]
The authorizer now call a callback with the authorization information that you can us e.g. in your ember data adapter (or wherever you need to add authorization data) to add a request header.

**Comment by dennis** [comment]
I understand, and this is how device is implement, if I'm not mistaking. But I need to append a token URL parameter to the API calls, not add a request header.

So that Ember.$.ajax({ type: "GET", url: "/user" }).. would end up making this request:
GET /user?token=abcdef...

Thanks for your time

**Comment by marcoow** [comment]
You can do whatever you want to in the callback you're providing to the authorizer's `authorize` method:

```js
this.get('session').authorize(this.get('authorizer'), (headerName, headerValue) => {
  // add query param here instead of setting a header…
});
```

**Comment by antulik** [comment]
It's either i don't get it, or it's very complicated to use DataAdapterMixin and set query parameters at the same time. Can somebody assist me with example?
