### ISSUE TITLE
ESA (jj-abrams) fails to load properly on 2.0.1

### ISSUE THREAD

**Issue by jtippett** [simplabs/ember-simple-auth#639]
Hi there,

on a brand new app (ember-cli) ESA fails to load with an error I'm not experienced enough to figure out:

```setup-session-restoration.js:12 Uncaught TypeError: Cannot read property 'beforeModel' of undefined```

I've uploaded the repo here: https://github.com/jtippett/esa-load-fail

As can be seen, the only additions i've made to the naked app are to update ember and add ESA, and add a config setting per the ESA dummy app's example.

Any guidance as to how to move past this would be greatly appreciated...

**Comment by Ferdev** [comment]
Same problem here. As a workaround, you can create an empty application route:

`app/application/route.js`
    
    import Ember from 'ember';

    export default Ember.Route.extend();

That should fix your issue.

**Comment by pmkhoa** [comment]
Having this similar issue on Ember 2.0.1. This is the console output:
```javascript
Uncaught TypeError: Cannot read property 'beforeModel' of undefinedsetupSessionRestoration 
// @ setup-session-restoration.js:12initialize
initialize: function initialize(instance) {
  setupSessionRestoration['default'](instance);
}
```
```javascript
// @ simple-auth.js:8
...
var container = instance.container;
var applicationRoute = container.lookup('route:application');
var session = container.lookup('session:main');
var originalBeforeModel = applicationRoute.beforeModel;
```
I'm not sure if this is related to container.lookup method or not. But I hope to hear your thought about this. Thanks!

**Comment by marcoow** [comment]
Does your application define an application route?

**Comment by pmkhoa** [comment]
Oh. That's silly! I had a typo for my application route (applications). Thanks for you help!
Also, is the new version still using crossOriginWhitelist ?

**Comment by marcoow** [comment]
No, `crossOriginWhitelist` doesn't exist anymore as automatic authorization of all outgoing requests has been removed.

**Comment by marcoow** [comment]
The `jj-abrams` now makes sure that there is an application route by defining an empty one (which would be overridden by the one in the application if present).
