### ISSUE TITLE
Overwriting Authenticators

### ISSUE THREAD

**Issue by jorgedavila25** [simplabs/ember-simple-auth#642]
Hi,

I've been trying to overwrite Ember Simple Auth torii Authenticator, and I've tried many ways (including creating a custom one, and copying/pasting the content). However, I haven't been successful. What's the best way to overwrite a method or two of an existing authenticator? 

Thanks so much! 

Cheers,
Jorge

**Comment by marcoow** [comment]
You shouldn't try overriding any authenticators at all but extend one and use the extended one then.
