### ISSUE TITLE
target undefined hanndling authorizationFailed in ApplicationRouteMixin.beforeModel

### ISSUE THREAD

**Issue by jpaas** [simplabs/ember-simple-auth#643]
When my oauth token is no longer valid, the authorizationFailed event is sent to ApplicationRouteMixin.beforeModel.

But when it hits this line...
https://github.com/simplabs/ember-simple-auth/blob/0.8.0/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L72

the target is undefined which causes an error.

Environment:
Ember Inspector 1.9.0
Ember 1.13.5
Ember Data 1.13.6
jQuery 2.1.4
Ember Simple Auth 0.8.0
Ember Simple Auth OAuth 2.0 0.8.0
Ember Simple Auth Testing 0.8.0

**Comment by marcoow** [comment]
should be fixed in 1.0
