### ISSUE TITLE
Refresh token not used

### ISSUE THREAD

**Issue by sebgie** [simplabs/ember-simple-auth#644]
We are in the middle of preparing the release of Ghost 0.7. `ember-simple-auth` was updated to version 0.8 since the last release and during testing we discovered now that sessions are expiring sooner than they did before. 

I was able to track this behaviour down to refresh_token not being used to acquire a new access_token if the existing access_token becomes invalid.

Setup:
- access_token: 1 hour
- refresh_token: 1 week
- store: local storage

Reproduction 1:
- log in and acquire a valid access_token
- close browser tab and wait for > 1 hour
- open browser and go back to page
- you are logged out now

Reproduction 2 (faster):
- log in and acquire a valid access_token
- edit the access_token stored in local storage to make it invalid
- visit a page that requires authentication
- you are logged out now

I'm quite sure that ember-simple-auth 0.7.3 used the refresh_token and attempted to create a new access_token before the user was logged out. Did this change or is any additional setup needed to make it work again?

Any help or pointers would be highly appreciated to help us get a release together :).

**Comment by marcoow** [comment]
In the second case you will always be logged out as you'd receive a 401 error which always results in the session being invalidated.

The first scenario should actually work as the OAuth 2.0 authenticator should try to refresh an expired access token on session restoration: https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L104.

**Comment by sebgie** [comment]
Thank you very much for your quick reply!

I missed the part about 401 leading to session invalidation.

Anyway, your answer helped me to find another interesting behaviour. We use OAuth2.reopen() (https://github.com/TryGhost/Ghost/blob/2e9932b8eb77a1bda9e4f3a3f31afafc4fd6bfa9/core/client/app/instance-initializers/authentication.js#L17) to add a client_id to the token request. This works except for the case when the access_token is expired and the session is restored. This would be the explanation why the first scenario didn't work. Could this be something that has changed between 0.7.3 and 0.8?

**Comment by marcoow** [comment]
[`refreshAccessToken`](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-oauth2/lib/simple-auth-oauth2/authenticators/oauth2.js#L260) uses `makeRequest` as well so it should also have the client_id in the request. I think that might run before the `reopen` though in which case the method would not already have been changed…

1.0 (which I hope to release soon) will support client_id out of the box though. You could also use 1.0 from the [`jj-abrams`](https://github.com/simplabs/ember-simple-auth/tree/jj-abrams) branch already. The public API shouldn't change much anymore - if at all.

**Comment by kevinansfield** [comment]
Thanks @marcoow - we both came to the same conclusion regarding `refreshAccessToken` running before our override was taking effect. I've submitted a fix here https://github.com/TryGhost/Ghost/pull/5756.

Glad to hear that 1.0 is to be released soon, I'll be sure to update and test once we're past our imminent release.

**Comment by sebgie** [comment]
@marcoow thank you for your answers! Helped debugging the problem tremendously!

Really looking forward to 1.0 :+1:!
