### ISSUE TITLE
Session get invalidated right after session authenticate successfully if I have two sessions one is secured(https) and another non-secured(http) for my website opened in the same browser 

### ISSUE THREAD

**Issue by msalahz** [simplabs/ember-simple-auth#648]
I recently added SSL certificate support for my website and after that I had a strange issue when I have two sessions open in my browser for my website and the only different is that the first is secured and the second is non-secured, the issue happen when i try to login in one of them the other session get refreshed and show content and then both sessions get invalidated.

**I'm using the following versions :**
```
Ember : 1.13.6
jQuery : 1.11.3
Ember Simple Auth : 0.8.0
Ember Simple Auth Cookie Store : 0.8.0
```

After digging I found the following:
1- If I logged in non-secured session cookie created without secured flag.
2- Secured session restore session from created cookie and update the cookie but this time with a secure flag 
3- Some how both sessions get invalidated right after that.( I couldn't figure out the main reason for that )

The temp solution I found is to always create cookie without secure flag by update the following [line](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-cookie-store/lib/simple-auth-cookie-store/stores/cookie.js#L88) :
``` _secureCookies: window.location.protocol === 'https:',```
to :
``` _secureCookies: false,//window.location.protocol === 'https:',```

and this will make sure the cookie is shared between secured and non-secured sessions

any suggestion how to do permanently solve this issue ?

**Comment by marcoow** [comment]
I'm not sure whether the bug is actually in ESA or that bug is that the site is served both via HTTP and HTTPS - you should probably always redirect to the HTTPS version when someone requests HTTP. Always using non-secure cookies isn't really desirable of course.

**Comment by msalahz** [comment]
The issue is in ESA Cookie store because it forcing setting secure flag according to host protocol while creating a cookie when it should be optional or configurable and notice that secure flag doesn't allow sharing cookie between secured and non-secured sessions and I'm not force HTPS for the full web app I'm planning to use it only in case some one want to embed code from my web app in a secured web app

**Comment by marcoow** [comment]
@msalahz: you can always extend the cookie store and override that behavior. I guess the way to go would probably to make this easier to override but I think defaulting to the host protocol is actually the right thing to do.

**Comment by msalahz** [comment]
Thanks, Extending cookie store allowed me to do what I need.
