### ISSUE TITLE
Torii is installed but not configured in config/environment.js!

### ISSUE THREAD

**Issue by ksnyde** [simplabs/ember-simple-auth#649]
I'm on the cf733480d68511d402927f26e60ce55ec8bf8825 commit of jjabrams and am planning on using OAuth2 Authenticator but I notice that Torii has been installed and when I run `ember serve` I get:

> Torii is installed but not configured in config/environment.js!

I seem to be able to progress at this point but this warning (and likely the auto-installation of Torii) is an undesired effect.

**Comment by ksnyde** [comment]
I think maybe the auto-installation of Torii is actually intended now but the warning message still seems like an issue.

**Comment by rlivsey** [comment]
This was [introduced here](https://github.com/simplabs/ember-simple-auth/pull/636) and I think the plan is to back out the dependency and document that you need to install it if you're using Torii.

There's [a pull request](https://github.com/emberjs/ember.js/pull/12275) open regarding backing out the change, but not for the documentation yet.

**Comment by rwjblue** [comment]
@rlivsey - Unless I am misunderstanding something, the pull request link above is wrong (it points to a recent PR to Ember itself).

**Comment by rlivsey** [comment]
@rwjblue well spotted, I've obviously too many tabs open, copied the wrong URL!

(since edited) should have been https://github.com/simplabs/ember-simple-auth/pull/641

**Comment by marcoow** [comment]
torii isn't automatically installed in the `jj-abrams` branch anymore
