### ISSUE TITLE
Uncaught Error: Attempting to inject an unknown injection: `service:store`

### ISSUE THREAD

**Issue by ryanlitalien** [simplabs/ember-simple-auth#653]
Hi, I'm using the `jj-abrams` branch. (this was originally working on master before upgrading to Ember 2.0.0 and Ember 2.0.1) I have a basic devise authenticator that properly returns the data from the API, but has an issue storing that into the session store. My app closely resembles the dummy app. I'm a bit stuck and not sure what to debug next. Thanks.

```
app/authenticators/devise.coffee
---

`import Devise from 'ember-simple-auth/authenticators/devise'`
`export default Devise.extend()`
```

and it's throwing this error:

![image](https://cloud.githubusercontent.com/assets/1479756/9697574/89cd323c-535f-11e5-824a-d671a9e11194.png)

The source of the error is `devise.js` line 122:
![image](https://cloud.githubusercontent.com/assets/1479756/9697617/2be1094e-5361-11e5-9143-f546bda20710.png)

First part of the stack trace:
![image](https://cloud.githubusercontent.com/assets/1479756/9697610/f89b5bb6-5360-11e5-94dc-619bbc5ce17b.png)

Beginning of stack trace:
![image](https://cloud.githubusercontent.com/assets/1479756/9697614/1152b226-5361-11e5-8a3f-935e5603dfe4.png)

**Comment by marcoow** [comment]
Looks like you're using the Ember Data store service somewhere but probably you aren't on a recent Ember Data version so that service doesn't exist.

**Comment by ryanlitalien** [comment]
@marcoow Thanks. I had Ember Data in my bower.json, but not package.json. Nice catch.

**Comment by prudvi** [comment]
https://github.com/simplabs/ember-simple-auth/issues/653#issuecomment-137922173 what is solution for this?

**Comment by yandiro** [comment]
This thread reminded me to update ember-simple-auth from `3.0.0 `to `3.1.0-beta.0`.

Maybe this will help somebody!
