### ISSUE TITLE
How does Two-Factor Auth play with OAuth 2.0?

### ISSUE THREAD

**Issue by f3ndot** [simplabs/ember-simple-auth#654]
Hello!

Currently looking into how I can integrate Two-Factor Authentication into my Ember App using Ember Simple Auth OAuth 2.0.

Briefly pouring over the RFC, I see it doesn't leave any room for the client to provide additional parameters outside of the required set of `grant_type`, `username`, `password`– Which you've followed to a T.

My current plan for the backend is to, when provided with the above required set for a 2FA'd user, respond back with an error (be it `X-Some-OTP-Header: required`, or in the `error` and `error_description` keys) informing the app that 2FA is required. A subsequent request is then sent with the OTP, provided by the user, in the header as `X-Some-OTP-Header: 123123`. But, that's just spitballing and would require ember-simple-auth to support custom headers.

How do you envision a world where 2FA and OAuth 2.0 coexist in Ember, using your library? Is it possible?

**Comment by marcoow** [comment]
I don't know how 2FA would integrate with OAuth 2.0 but of course you can implement a custom authenticator in Ember Simple Auth that does what you describe above.

**Comment by f3ndot** [comment]
Seeing that GitHub and others use the `X-` header strategy as a workaround, would you be opposed to a PR that extends Ember Simple Auth OAuth 2.0 to support the passing/parsing of headers in the options hash?

**Comment by marcoow** [comment]
Don't think it should be added to the library right away since the OAuth 2.0 authenticator can easily be extended. Would be interested in the solution you come up with in a custom authenticator though.

**Comment by f3ndot** [comment]
@marcoow I've created a working solution by amending the OAuth 2 authenticator's `makeRequest` to send a `X-VendorName-OTP` header if the `authenticate` options hash contains a OTP parameter.

In order to get access to the headers during an error/reject (as the backend would fail, indicating that a OTP is required *only* through headers) I had to change `authenticate` to reject with the raw `xhr` instead of the response text/json:

```js
makeRequest: function(url, data, otp) {
  return Ember.$.ajax({
    url:         url,
    type:        'POST',
    data:        data,
    dataType:    'json',
    beforeSend:  function(xhr) {
      if (otp) {
        xhr.setRequestHeader('X-VendorName-OTP', otp);
      }
    },
    contentType: 'application/x-www-form-urlencoded'
  });
},
```
```js
authenticate: function(options) {
  var _this = this;
  return new Ember.RSVP.Promise(function(resolve, reject) {
    // skipping edited code...
    _this.makeRequest(_this.serverTokenEndpoint, data, options['otp']).then(function(response) {
      // ...
    }, function(xhr, status, error) {
      Ember.run(function() {
        reject(xhr);
      });
    });
  });
},
```

All other OAuth 2 authenticator methods are untouched. All I needed was to deal with headers :smile:

**Comment by f3ndot** [comment]
Then simply, I can drive my Ember app as follows:

```js
// app/routes/login.js
import Ember from 'ember';
import UnauthenticatedRouteMixin from 'simple-auth/mixins/unauthenticated-route-mixin';

export default Ember.Route.extend(
  UnauthenticatedRouteMixin,
{
  actions: {
    sessionAuthenticationFailed: function(xhr) {
      if (xhr.getResponseHeader('X-VendorName-OTP') === 'required') {
        // display that a two-factor verification code is required to
        // the user
        this.set('controller.hideUsernameAndPasswordFields', true);
        this.set('controller.displayOTPField', true);
      } else {
        // regular error handling here
      }
    }
  }
});
```

**Comment by marcoow** [comment]
Looks good - you shouldn't use the `sessionAuthenticationFailed` though but handle the rejection of the promise returned from `this.get('session').authenticate(…)` as the `sessionAuthenticationFailed` is going to be removed in 1.0 anyway.
