### ISSUE TITLE
  sessionAuthenticationSucceeded not called

### ISSUE THREAD

**Issue by DoryZi** [simplabs/ember-simple-auth#655]
Hi,

When working on the main branch, that get's called, but I also get many deprecation.
So I try to use this latest one, jjabrams branch, but then the   sessionAuthenticationSucceeded in my application route doesn't get called, why is that?

**Comment by dukex** [comment]
The jj-abrams change the ```sessionAuthenticationSucceeded``` to ```authenticationSucceeded```, rename your method and will work fine

Reference: 
https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/mixins/application-route-mixin.js#L51

**Comment by marcoow** [comment]
as @dukex says
