### ISSUE TITLE
Storage is always Ephemeral

### ISSUE THREAD

**Issue by GCorbel** [simplabs/ember-simple-auth#656]
Hello,

I'm working with Ember 2.0.0 and this pull request #602. 

I added this line in `config/environment.js` : 

    ENV['simple-auth'] = {
      store: 'simple-auth-session-store:local-storage'
    }

When I set a value in a session, it works but, when I reload the page, it disappear.

In the Ember Inspector, I checked at Container-> session-store and the value is Ephemeral. I checked in my code and Ephemeral is nowhere.

What can I do?

Thanks.

**Comment by marcoow** [comment]
Your configuration is wrong - configure the store like this instead:

```js
ENV['simple-auth'] = {
  store: 'session-store:local-storage'
}
```

**Comment by GCorbel** [comment]
The problem is persisting. I copy/paste your code in my environment.js and it still not work. Furthermore, `store: 'simple-auth-session-store:local-storage'` is written in the README.

Thanks for your fast answer.

**Comment by marcoow** [comment]
see the dummy app's config: https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/tests/dummy/config/environment.js#L34

**Comment by GCorbel** [comment]
It works partially. When I do `@controllerFor('application').get('session').get('user_id')` in a route, I have the user id when I just created the session but when, I reload, it undefined.

Sorry for the inconvenience. I check in the code and in the Readme and I don't find the solution.

Thanks again!

**Comment by marcoow** [comment]
You should use the session service instead of using it via another controller.

**Comment by GCorbel** [comment]
I changed for this (in coffee script) to find the data stored : 

    { service } = Ember.inject

    export default Ember.Route.extend
      session: service('session')
      model: (params) ->
        id = @get('session').get('user_id')
        console.log id
        @store.find('user', id)

And this for sign in form.

    { service } = Ember.inject

    export default Ember.Controller.extend
      session: service('session')
      actions:
        submit: ->
          data = @getProperties('email', 'password')
          session = @get('session')
          session.authenticate('authenticator:custom', data).then(=>
            session.set('identification', data.email)
            session.set('user_id', data.user_id)
            @transitionToRoute '/'
          , (data)=>
            @set('errors', data.errors)
          )

Sorry for the inconvenience. I don't like to ask like that but I don't know when to search. I'm not an Ember expert. Thanks.

**Comment by GCorbel** [comment]
I continue to search without result.

Just a question : Do you think session can be extracted from `ember-simple-auth` to another module? Session and authentication are two thinks. I think it can be clearer to do a separation.

**Comment by GCorbel** [comment]
I continued to try.

I changed my code to be as in the Readme.

    export default Ember.Controller.extend
      session: Ember.inject.service('session')
      actions:
        submit: ->
          data = @getProperties('email', 'password')
          session = @get('session')
          session.authenticate('authenticator:custom').then(=>
            session.set('identification', data.email)
            session.set('user_id', data.user_id)
            debugger
            @transitionToRoute '/'
          , (data)=>
            @set('errors', data.errors)
          )

I saw In the localstorage -> localhost `{"authenticated":{"authenticator":"authenticator:custom","token":"58c06d2159b94ec1f7ae95f86cf972216da3d1cf"}}`. When I use `session.set('test', 'test')`, the data is not changed. I can use `session.session.set('test', 'test')` but the data is not changed too. When I do `session.session.store.persist()` the data is changed.

I supposed the first `session` should be called `sessionService`. Is it because I don't understand something or is there a bug?

Thanks again.

**Comment by ameech** [comment]
I'm also running into this same issue. When I login and receive my token it's set in my local storage, but when I refresh the page I become unauthenticated.

**Comment by marcoow** [comment]
@GCorbel: try setting the data on session.data instead of just the session, e.g.: `session.set('data.identification', data.email)`.

**Comment by GCorbel** [comment]
Same think. The session is kept until I reload the page. Can you confirm this is a bug and not my mistake?

**Comment by ameech** [comment]
I am using this: https://github.com/jpadilla/ember-cli-simple-auth-token and the issue stemmed from the timeFactor being too low, so it was constantly being dropped.

**Comment by marcoow** [comment]
@GCorbel: that's a bug - non-authenticated data is lost on restoration.

**Comment by marcoow** [comment]
@GCorbel: please post your code and config

**Comment by GCorbel** [comment]
This is my `config/environment.js` file : 

    /* jshint node: true */

    module.exports = function(environment) {
      var ENV = {
        modulePrefix: 'social-learning',
        environment: environment,
        baseURL: '/',
        locationType: 'auto',
        EmberENV: {
          FEATURES: {
            // Here you can enable experimental features on an ember canary build
            // e.g. 'with-controller': true
          }
        },

        APP: {
          // Here you can pass flags/options to your application instance
          // when it is created
        }
      };

      if (environment === 'development') {
        // ENV.APP.LOG_RESOLVER = true;
        // ENV.APP.LOG_ACTIVE_GENERATION = true;
        // ENV.APP.LOG_TRANSITIONS = true;
        // ENV.APP.LOG_TRANSITIONS_INTERNAL = true;
        // ENV.APP.LOG_VIEW_LOOKUPS = true;
      }

      if (environment === 'test') {
        // Testem prefers this...
        ENV.baseURL = '/';
        ENV.locationType = 'none';

        // keep test console output quieter
        ENV.APP.LOG_ACTIVE_GENERATION = false;
        ENV.APP.LOG_VIEW_LOOKUPS = false;

        ENV.APP.rootElement = '#ember-testing';

        ENV['ember-simple-auth'] = {
          store: 'session-store:ephemeral'
        }
      }

      if (environment === 'production') {

      }

      ENV['ember-simple-auth'] = {
        base: {
          store: 'session-store:local-storage'
        }
      };
      return ENV;
    };


And this is a route (in coffee script) : 

    export default Ember.Route.extend
      session: Ember.inject.service('session')
      setupController: ->
        session = @get('session')
        console.log session.get('user_id')
        session.set('user_id', 1)
      model: (params) ->
        @store.findAll('user')


This first time `console.log session.get('user_id')` gives undefined and this is normal. When I go to the same page without reloading, I have `1` is written in the console. When I reload the page, I have `undefined` again.

Is there something wrong in my code?

**Comment by marcoow** [comment]
You cannot set data on the session directly or at least that would not be stored in the session store. Use `session.set('data.user_id')` instead and make sure you're on the latest revision of the `jj-abrams` branch.

**Comment by GCorbel** [comment]
It works! Thanks!

I think you're one of the greatest maintainer I seen. You answer quickly with a good answer each time. Thanks a lot!
