### ISSUE TITLE
refreshModel: true and transition retries after logging in.

### ISSUE THREAD

**Issue by jakemauer** [simplabs/ember-simple-auth#658]
Hey marcoow, forgive me if this isn't the proper place to discuss this but I'm running head-first into the issues described in this bug: https://github.com/emberjs/ember.js/issues/10945, specifically sukima's first comment. 

We have a route like `/post/1/comments?someParam=true` where the query params are set to `refreshModel: true` in the comments route. When we visit that URL as a logged out user, we're successfully redirected to login and once we log in the `modelFor('post')` in our comments `model` route returns undefined. If there are no query params in the initial URL, everything works peachy. 

Before we go headfirst into implementing sukima's observer-based workaround, I wanted to see if you had any suggestions on how to deal with this weird case. 

Thank you for all your work on this project and your time.

**Comment by marcoow** [comment]
I don't think this will is an issue with ESA. It looks more like an issue with Ember itself. You can easily override the `sessionAuthenticationSucceeded` action in ESA and use sth. other than `ttandition.retry` to prevent the error.
