### ISSUE TITLE
Non-authenticated session data isn't persisted

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#660]
Since the session service's `data` property aliases directly to the session's `content` property, the session's `setUnknownProperty` method isn't called when anything is written to the session service's `data` property, e.g.

```js
this.set('session.data.test', 'value');
```

**Comment by marcoow** [comment]
fixed in `jj-abrams`

**Comment by jpaas** [comment]
@marcoow I'm running the current jj-abrams branch and any property I set in session.data does not get stored in local storage.

**Comment by marcoow** [comment]
@jpaas use `this.get('session').set('data.test', 'value');`

**Comment by jpaas** [comment]
That fixes it! Thanks so much! Holy cow what turnaround time.
