### ISSUE TITLE
Session invalidation to sync with transition

### ISSUE THREAD

**Issue by youroff** [simplabs/ember-simple-auth#661]
Is there a way to sync session invalidation with transition? Right now I can see how what was taken from session disappears from the page and only after that router gets to `authenticationRoute`. It doesn't look pretty at all.

**Comment by marcoow** [comment]
You can override the `sessionInvalidationSucceeded` action in the application route and do your custom handling there.

**Comment by youroff** [comment]
Does this look correct for you? I'm on `jj-abrams`, and it's not working:
```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  actions: {
    sessionInvalidationSucceeded() {
      alert('Does this ever run?');
    }
  }
});
```

Could you point at the piece of code that runs this?

**Comment by marcoow** [comment]
On `jj-abrams` it would have to be:

```js
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  sessionInvalidated() {
    alert('Does this ever run?');
  }
});
```

**Comment by youroff** [comment]
Oh, thank you so much. It worked! :)
Though I noticed that alert fired twice. Is that how it supposed to be?

**Comment by marcoow** [comment]
No that shouldn't fire twice actually

**Comment by youroff** [comment]
Sorry for misleading comment. I does fire once, I just had two tabs open with an app.

But I still have issues with storing data in session. If I set something like `this.set('session.some_key', 'some value')` it's visible within one tab only and disappears on page reload, while keeping user authenticated. I'm pretty sure on previous version it was shared between tabs. What I do wrong?

**Comment by marcoow** [comment]
I fixed that yesterday. Make sure you're running the latest revision of the `jj-abrams` branch.

**Comment by youroff** [comment]
Oh, thank you very much!
