### ISSUE TITLE
Documentation of authenticator promise restrictions

### ISSUE THREAD

**Issue by durkie** [simplabs/ember-simple-auth#663]
session.authenticate doesn't behave like a normal promise, and it would be great to have a note of this in the documentation.

Say your login controller looks like this: 
```
export default Ember.Controller.extend({
actions: {
    authenticate: function() {
      var controller = this;
      var data = this.getProperties('identifier', 'password');
      controller.get('session').authenticate('authenticator:custom', data).then(function(response) {
        console.log(response);
      }, function(error) {
        console.log(error);
      });
...
```

This 90% acts like a normal promise, in that both the resolve and reject functions will be run at appropriate times. The big difference from a normal promise is that resolve never seems to be run with arguments since all of the response data get pulled in to the session data store. `console.log(response);` will always return undefined, whereas `console.log(this.get('session.secure.XXX'));` will work fine in the resolve function.

Making things more confusing to someone debugging this is that reject is always run with its arguments, and `console.log(error);` works just fine.

**Comment by marcoow** [comment]
I don't think a promise has to resolve with a value.

The expectation that the promise's `authenticate` method should resolve with the server's response is a misconception that many people have. Ember Simple Auth makes that data available though the session though and there might even be no server response at all as there's potentially no server request at all depending on which authenticator you use.

The docs need to be updated for 1.0 anyway of course - see #602

**Comment by durkie** [comment]
You're right -- it doesn't have to resolve with a value, but it gets really confusing when you're explicitly trying to resolve with a value.

Say your custom authenticator looks like:
```
...
export default Base.extend({
  authenticate: function(credentials) {
    var _this = this;
    return new Ember.RSVP.Promise(function(resolve, reject) {
      var data = {};
      data['session'] = { password: credentials.password};
      data['session']['identifier'] = credentials.identifier || credentials.email || credentials.username;
      _this.makeRequest(data).then(function(resp, status, xhr) {
        Ember.run(function() {
          console.log(resp);
          resolve(resp);
        });
      }, function(xhr, status, error) {
        Ember.run(function() {
          reject(xhr.responseJSON || xhr.responseText);
        });
      });
    });
  },

...

makeRequest: function(data) {
    let _this = this;
    return new Ember.RSVP.Promise(function(resolve, reject) {
      Ember.$.ajax({
        url:        config.domain + _this.serverTokenEndpoint,
        type:       'POST',
        data:       data,
        dataType:   'json',
        success:    function(data, status, xhr) { resolve(data, status, xhr) },
        error:      function(xhr, status, error) { reject(xhr, status, error) },
        beforeSend: function(xhr, settings) {
          xhr.setRequestHeader('Accept', settings.accepts.json);
        }
      });
    });
  }
```

The `console.log(resp);` statement will log the response from the server, as expected. However, even though you're calling `resolve(resp)`, `resp` will not actually be passed as an argument to `resolve`, so running `resolve(resp)` is basically the same as running `resolve()`. To me this is unexpected behavior.

**Comment by durkie** [comment]
And, to make matters more confusing, `resolve` in the above authenticator *must* be given an argument or else the response data won't be stored in the session. Just spent a few hours figuring that out :/

**Comment by marcoow** [comment]
It seems you're confusing 2 methods here - the session' `authenticate` method that returns a promise that resolves without any value if authentication succeeds and the authenticator's `authenticate` method that resolves with the authentication data if it successfully acquired that using the mechanism it implements. The latter method is private API and is called by the session.

Just because the one method returns a promise that resolves with a value doesn't mean the other one has to as well. Also resolving with a value from the session' `authenticate` method would mean that there are now 2 ways of reading the session data - via the value the promise resolves with and via the session directly. I don't think that would make anything any simpler.

**Comment by durkie** [comment]
Yeah -- it does seem like I'm getting them mixed up. But that's what I was hoping to address with this issue: not that anything should be changed in the logic of ember simple auth, but that it is a confusing flow: you have two identically-named, promise-returning functions linked by an opaque controller. It's easy to think they're more directly linked than they are, and I think it'd be helpful to point it out more prominently in the docs.

**Comment by marcoow** [comment]
Docs should be correct in the 1.0 API docs.
