### ISSUE TITLE
Simple Auth Devise and Full Path for sign_in

### ISSUE THREAD

**Issue by joaoribeirost** [simplabs/ember-simple-auth#668]
Hello,

I'm currently working with this ember-cli addon and the ember-cli-chrome add-on. However, when I try to login throught the chrome extension it tries to do the following request:

```
POST chrome-extension://extension-id/users/sign_in net::ERR_FILE_NOT_FOUND
```
How can I define the full path (http://localhost:3000) in this addon so the POST request goes to the right place?

Thanks in advance, 
Joao

**Comment by marcoow** [comment]
Just configure the `serverTokenEndpoint` with the full URL instead of just the path: http://ember-simple-auth.com/ember-simple-auth-devise-api-docs.html#SimpleAuth-Configuration-Devise-serverTokenEndpoint
