### ISSUE TITLE
 Cannot read property 'authorize' of undefined TypeError: Cannot read property 'authorize' of undefined

### ISSUE THREAD

**Issue by gordonbisnor** [simplabs/ember-simple-auth#670]
I'm getting an error that I have not been able to figure out:

```Cannot read property 'authorize' of undefined TypeError: Cannot read property 'authorize' of undefined```

Which is coming from ember-simple-auth/services/session.js:
```authorize: function authorize(authorizerFactory, block) {
      var authorizer = this.container.lookup(authorizerFactory);
      authorizer.authorize(block);
    }
```

This is my adapter:
```import ENV from 'hustle/config/environment';
import DS from 'ember-data';
import ActiveModelAdapter from 'active-model-adapter';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default ActiveModelAdapter.extend(DataAdapterMixin, {
	authorizer: 'authorizer:application',
	host: ENV.apiHost,
	namespace: "api/v1",
  buildURL: function(record, suffix) {
    return this._super(record, suffix) + ".json";
  }
});
```
For some reason ```this.container.lookup(authorizerFactory);``` is coming up undefined, and then the next line is calling ```authorize()``` on undefined.

*I'm using:*
- Ember Data 2.0.0
- Ember 2.0.0
- "ember-simple-auth": "simplabs/ember-simple-auth#jj-abrams"

Any ideas?

**Comment by marcoow** [comment]
Did you define the application authorizer in `app/authorizers/application.js`?

**Comment by gordonbisnor** [comment]
I hadn't. And thank for the incredibly fast response!

**Comment by corrspt** [comment]
@marcoow I also had this problem but I was able to figure it out by comparing the dummy app that you usually link to in the issues.

Seems as I wasn't the only that tripped on the subject but considering that this addon is in a "transition" state (with the whole jj-abrams branch), what would be the best way to document this situation right now? I'm asking this in terms of how I could help out (with a documentation PR, or something else).

Best regards and thanks for the addon, I'm currently using it to create a new Ember App!

**Comment by marcoow** [comment]
@corrspt: this will eventually be covered in the README of course. If you want to go ahead and submit a PR that updates the authorization section accordingly that would be great of course!

**Comment by corrspt** [comment]
Ok, I'll try to help! I assume this would a be PR on the jj-abrams branch?

**Comment by marcoow** [comment]
exactly
