### ISSUE TITLE
Testing Generated Application Route with #jj-abrams error (session not found?)

### ISSUE THREAD

**Issue by corrspt** [simplabs/ember-simple-auth#673]
Hi

I'm facing an issue which I'm not sure why it's happening. These are my findings:

I'm using (package.json)
```javascript
"ember-cli": "1.13.8",
"ember-simple-auth": "simplabs/ember-simple-auth#jj-abrams",
"ember-cli-simple-auth-testing": "0.8.0",
"ember-cli-simple-auth-token": "git+https://github.com/mmahalwy/ember-cli-simple-auth-token.git#feeb43d1dfd6f6b6ebe24c5874ef4baaded27c95",
```

and (bower.json)
```javascript
"ember": "2.0.0",
"ember-data": "2.0.0",
"ember-simple-auth": "0.8.0",
```

When running the tests I get the following error while testing the default application route
```javascript
Unit | Route | application: it exists (1, 0, 1)
TypeError: Cannot read property 'on' of undefined
```

The test is the following (the default generated test):
```javascript
import { moduleFor, test } from 'ember-qunit';

moduleFor('route:application', 'Unit | Route | application', {
});

test('it exists', function(assert) {
  var route = this.subject();
  assert.ok(route);
});
```

The application route itself (app/routes/application.js) is
```javascript
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
const { service } = Ember.inject;

export default Ember.Route.extend(ApplicationRouteMixin, {
  session: service('session'),

  actions: {
    logout: function() {
      var session = this.get('session');
      session.invalidate();
    }
  }
});
```

I've since added the ember-simple-auth-testing package and imported into my start-app.js like the following
```javascript
import Ember from 'ember';
import Application from '../../app';
import config from '../../config/environment';
import initializeTestHelpers from 'simple-auth-testing/test-helpers';
initializeTestHelpers();

export default function startApp(attrs) {
  var application;
```

From debugging I've found that the error occurs on here (application-route-mixin.js) in the function:
```javascript
_mapSessionEventsToActions: Ember['default'].on('init', function () {
      var _this = this,
          _arguments = arguments;

      Ember['default'].A([['authenticationSucceeded', 'sessionAuthenticated'], ['invalidationSucceeded', 'sessionInvalidated']]).forEach(function (_ref) {
        var _ref2 = _slicedToArray(_ref, 2);

        var event = _ref2[0];
        var method = _ref2[1];

        _this.get('session').on(event, Ember['default'].run.bind(_this, function () {
          _this[method].apply(_this, _arguments);
        }));
      });
    }),
````
The line 
```javascript
_this.get('session').on(event, Ember['default'].run.bind(_this, function () {
```

Apparently this.get('session') returns null in this situation. It would seem to me that I have something not setup properly but the application seems to run ok, so it must be something regarding the tests?

I've this in my environment.js
```javascript
if (environment === 'test') {

    ENV['ember-simple-auth'] = {
      base: {
        store: 'session-store:ephemeral'
      }
    };
```

Thanks in advance for any tips/help!

EDIT: I'm not particularly interested in the result of this default test as you can Imagine, but I assume that any test that I may want to do in this route will fail because of this issue

**Comment by marcoow** [comment]
When you're using the `jj-abrams` branch, make sure you don't have any other `ember-cli-simple-auth-*` packages in the `package.json` and also remove the `"ember-simple-auth": "0.8.0",` from `bower.json`.

That's also all described here: https://github.com/simplabs/ember-simple-auth/pull/602

Please reopen if there's actually a bug after you fixed that.

**Comment by corrspt** [comment]
Hi @marcoow 

Thanks for the reply, but unfortunately the issue still remains. I've removed all ember-simple-auth from bower.json and all ember-cli-simple-auth* from package.json (even the ember-cli-simple-auth-token which I need in my app, just to see if it was the cause). 
I've done rm -rf bower_components and node_modules and then bower install and npm install, but the result is the same.

Any idea that I could test, why would the application-route-mixins.js wouldn't be able to access the session (especially since I inject the session in the application route)?

**Comment by ancashoria** [comment]
The issue is still happening

**Comment by Dhaulagiri** [comment]
I had the same problem, and I was able to fix it by making sure the session was injected into my test:

```
import { moduleFor, test } from 'ember-qunit';

moduleFor('route:application', 'Unit | Route | application', {
  // Specify the other units that are required for this test.
  needs: ['service:session']
});

test('it exists', function(assert) {
  var route = this.subject();
  assert.ok(route);
});

```

**Comment by daanwissing** [comment]
@Dhaulagiri I had exactly the same issue, this helped. Thanks! :+1:

**Comment by datasc123** [comment]
@Dhaulagiri : This helped me solving the issue  :+1:
