### ISSUE TITLE
Problem with overriding sessionInvalidationSucceeded().

### ISSUE THREAD

**Issue by igorstajic** [simplabs/ember-simple-auth#677]
I need to stop ember from returning to the root URL after session is invalidated. So I tried to override the *sessionInvalidationSucceeded()* action. 
The issue I'm facing now is that even though the overridden *sessionInvalidationSucceeded()* gets called first, the **main** *sessionInvalidationSucceeded()* method still gets called after it anyways (and does window.location.replace(Configuration.applicationRootUrl)). I'm not sure what I might be doing wrong.

**Comment by marcoow** [comment]
Which version of ESA are you using? Also please post your application controller's source here.

**Comment by igorstajic** [comment]
I am using version 0.8.0. 
And actually I don't have and application controller at all. This is the source of the route:
```
import Ember from 'ember';
import ApplicationRouteMixin from 'simple-auth/mixins/application-route-mixin';
import AuthenticatedRouteMixin from 'simple-auth/mixins/authenticated-route-mixin';
export default Ember.Route.extend(ApplicationRouteMixin, AuthenticatedRouteMixin, {
	model: function() {
		return this.store.query('authentication', {
			//TODO Pass auth provider as param.
			'emailAddress': this.session.content.secure.userEmail
		});
	},
	actions: {
		sessionInvalidationSucceeded: function() {
			console.log('Testing...');
			this.transitionTo('logout');
		},
		closeSession: function() {
			this.get('session').invalidate();
		}
	}
});
```
Also, this is the route from which I call the closeSession action. For some reason, when I define *sessionInvalidationSucceeded* in the application route, it never gets called.

**Comment by igorstajic** [comment]
I found out what the problem was, i've had ApplicationRouteMixin included in the application route as well as in this route above. So it was triggering sessionInvalidationSucceeded for the second time.

But still, I don't see why it doesn't call the overridden method in my application route.
Anyways, thanks for the response.

**Comment by marcoow** [comment]
This is Ember's event bubbling - the first route's or controller's implementation of the action in the route hierarchy will be called.
