### ISSUE TITLE
Authorization bearer token gets dropped after full page refresh

### ISSUE THREAD

**Issue by duizendnegen** [simplabs/ember-simple-auth#684]
Using the `jj-abrams` branch, a user stays logged in across full page refreshes, but their token doesn't get transmitted anymore to the backend (causing it to reject the request).

Config
```js
ENV['torii'] = {
    providers: {
      'azure-token-oauth2': {
        tennantId: '...',
        apiKey: '...',
        redirect_uri: "localhost:4200",
        nonce: "...",
        responseType: 'id_token'
      }
    }
  }

  ENV['ember-simple-auth'] = {
    base: {
      store: 'session-store:local-storage'
    }
  };
```

and the `azure-token-oauth2` is
```js
import Ember from 'ember';
import Torii from 'ember-simple-auth/authenticators/torii';
import raw from 'ic-ajax';

const { service } = Ember.inject;

export default Torii.extend({
  torii: service('torii'),

  authenticate() {
    return new Ember.RSVP.Promise((resolve, reject) => {
      this._super(...arguments).then((data) => {
        data["access_token"] = data["authorizationCode"];
        resolve(data);
      }, reject);
    });
  }
});
```

Looking at the `data-adapter-mixin` the `beforeSend` hook doesn't find any headers to include...
Pointers are very much welcomed.

**Comment by marcoow** [comment]
You need to implement the `fetch` method for the torii provider you're using - see the [dummy app](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/tests/dummy/app/torii-providers/facebook.js).

**Comment by duizendnegen** [comment]
you are a gentleman and a scholar!
yes, that fixed my problems - thanks
