### ISSUE TITLE
Make setup public to handle manual setting of authenticator?

### ISSUE THREAD

**Issue by barelyknown** [simplabs/ember-simple-auth#685]
I'd like to be able to manually set the session content like this:

```javascript
$E.get('session.session').setup('authenticator:oauth2', {
  "authenticated": {
    "authenticator":"authenticator:oauth2",
    "access_token":"c4094c87ad2097e9c7a87bf21c8b3988ced251ffe30416f4b1d29343966873ee",
    "token_type":"bearer",
    "created_at":1443199461
  }
})
```

The current use case is to handle a confirmation link when a new user account is created and needs to be confirmed by clicking on a URL in an email. I'm passing the token in that link so that the client can "login" the user automatically. The setup function appears to be what should be used to do this, but it's marked private right now.

**Comment by marcoow** [comment]
You should never do that. Instead, simply call the session's `authenticate` method with an authenticator that resolves with the data you want.
