### ISSUE TITLE
Naming clash with Ember Data store causes restore to fail

### ISSUE THREAD

**Issue by timiyay** [simplabs/ember-simple-auth#690]
Using `ember-simple-auth` 0.8.0, my session data wasn't being restored between page loads. Turns out, it was caused because I was injecting Ember Data's `store` service into my authenticator, which was overwriting simple auth's `store`. Fair enough.

However, it would be nice if Simple Auth could avoid this clash, by picking a slightly-more-unique name, like `sessionStore` or something.

FYI I still haven't solved my issue, as renaming the variable like `modelStore: Ember.inject.service('store')` still causes the `restore()` method to not be called.

**Comment by timiyay** [comment]
I was able to workaround the issue, by doing a dynamic lookup of the Ember Data store from my app's registry, like so:

```
let store = MyApp.registry.lookup('service:store');
```

I had to do this lookup, as any combination of different property names still caused `restore()` to not be called. For example, the following renaming did _not_ work:

```
modelStore: Ember.inject.service('store')
```

**Comment by marcoow** [comment]
Doesn't look this is actually a problem with Ember Simple Auth. Renaming the injection to `modelStore` should work - I can't really say why it doesn't in your case. The ability to extend the ESA session will be removed in 1.0 anyway so no need to think of a new name for the `store` property.
