### ISSUE TITLE
Does the library support OAuth2.0 authorization code grant

### ISSUE THREAD

**Issue by faeronsayn** [simplabs/ember-simple-auth#694]
I'm wondering if this library supports the authorization code grant flow as described in this RFC https://tools.ietf.org/html/rfc6749#section-4.1

If not, could you point me in the right direction on how one would be able to implement such a flow? My main concern is that this flow is redirection based and I'm not sure how that will work with `ember-simple-auth`

**Comment by marcoow** [comment]
The way to implement the authorization code flow with ESA is to extend the torii authenticator as done in the dummy app: https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/tests/dummy/app/authenticators/torii.js

The torii authenticator will use torii to acquire the authorization code that the implementation in the subclass then sends to your own API where it is verified and exchanged for a Bearer token.
