### ISSUE TITLE
jj-abrams: debug message shown on production

### ISSUE THREAD

**Issue by jcbvm** [simplabs/ember-simple-auth#696]
When building my Ember app, i can still see debug messages in the console when authentication is needed:

    The authenticator "authenticator:main" rejected to restore the session - invalidating…

Is this meant to be or should this debug message not be visible when built with production enviroment?

**Comment by marcoow** [comment]
This is just for debugging and will not be visible in production.

**Comment by jcbvm** [comment]
The issue is that it is visible for me in production

**Comment by marcoow** [comment]
It's [logged with `Ember.Logger.debug`](https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/internal-session.js#L210) so either sth. is wrong with your build or there's a bug in `Ember.Logger.debug`,

**Comment by jcbvm** [comment]
Will investigate it further
