### ISSUE TITLE
Can I override Configuration.authenticationRoute to an external url?

### ISSUE THREAD

**Issue by samtes** [simplabs/ember-simple-auth#698]

**Comment by marcoow** [comment]
No

**Comment by samtes** [comment]
I am building an ember app with a node backend and was using simple-auth with this <a href="https://auth0.com/blog/2015/08/11/create-your-first-ember-2-dot-0-app-from-authentication-to-calling-an-api/?utm_content=buffer0317f&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer"> set up</a> except I used simple-auth-session-store:cookie for store and simple-auth-cookie-store. Everything was fine. 
Later it was decided to use a central web authentication server which takes you to a different login page which generates a cookie (domain based) if you have the correct credentials. Therefore, we no longer need to have login route in our apps where all the simple-auth authenticators and authorizers come in play. Any idea how I can implement this?

**Comment by marcoow** [comment]
You'd have to register an initializer that automatically authenticates the session with a custom authenticator on startup when that cookie that central website issues is present.

**Comment by samtes** [comment]
I get that but how do I save the cookie in my store with a custom cookieName if authenticated?
originally I had this code in my environment.js which did it for me. 

ENV['simple-auth'] = {
    authorizer: 'authorizer:custom',
    routeAfterAuthentication: "/",
    crossOriginWhitelist: [ENV.REST_ENDPOINT],
    store: 'simple-auth-session-store:cookie'
  }

  ENV["simple-auth-cookie-store"] = {
    cookieName: "connect.sid"
  };

**Comment by samtes** [comment]
I made it work this way but I'm sure there must be a better way. 

- I still have login route which will automatically calls authenticate method in the authenticator:custom file which authenticates by validating the cookie with the central server or by redirecting to the central webserver login page wich generates the cookie.     
- still using simple-auth because I stores cookie if authenticated and also because of the useful mixins
- I'm authenticating in application before each route transition to check if cookie exists and also if it is valid or not
- if not valid the backend will destroy the session in which case "application-route-mixin" will redirect to the login route
- all other routes have authenticated-route-mixin for checking if session is authenticated and redirecting to login if not 

app/routes/application.js

import Ember from "ember";
import ENV from "airwatcher/config/environment";
import ApplicationRouteMixin from "simple-auth/mixins/application-route-mixin";

export default Ember.Route.extend(ApplicationRouteMixin, {
  model: function () {
    var self = this;
    return new Ember.RSVP.Promise(function(resolve, reject) {
      self.store.find("authenticate").then(function (response) {
        var result = response.toArray()[0].get("data").result;
        var loginUrl = response.toArray()[0].get("data").url || null;
        var token = response.toArray()[0].get("data").token;
        var userID = response.toArray()[0].get("data").userID;

        if (result) {
          Ember.run(function () {
            resolve({
              token: token,
              userID: userID
            });
          });
        } else {
          Ember.run(function () {
            resolve(window.location.replace(loginUrl));
          });
        }
      }, function (reason) {
        reject(reason);
      });
    });
  }
});


ap/routes/login.js

import Ember from "ember";
import LoginControllerMixin from "simple-auth/mixins/login-controller-mixin";

export default Ember.Route.extend(LoginControllerMixin, {
  model : function () {
    return this.authenticate();
  },
  redirect: function () {
    if (this.get("session.isAuthenticated")) {
      this.transitionTo("login");
    }
  },

  renderTemplate: function () {
    this.render("login", {
      view: "login"
    });
  },

  setupController: function (controller) {
    controller.set("errorMessage", null);
  },

  authenticate: function () {
    var self = this;

    this.set("errorMessage", "");

    return this.get("session").authenticate("authenticator:custom").then(function (some) {
      self.transitionTo("index");
    }).catch(function (err) {
      self.set("errorMessage", message);
    });
  }
});

app/authenticators/custom.js

import Base from "simple-auth/authenticators/base";
import Ember from "ember";
import ENV from "airwatcher/config/environment";

export default Base.extend({
  tokenEndpoint: ENV.AUTHENTICATE_ENDPOINT,
  needs: ["login"],

  restore: function (data) {
    return new Ember.RSVP.Promise(function (resolve, reject) {
      if (!Ember.isEmpty(data.token)) {
        resolve(data);
      } else {
        reject();
      }
    });
  },

  authenticate: function () {
    var self = this;
    return new Ember.RSVP.Promise(function (resolve, reject) {
      Ember.$.ajax({
        url: self.tokenEndpoint,
        type: "GET",
        xhrFields: {
          withCredentials: true
        }
      }).then(function (response) {
        var result = response.authenticate[0].result;
        var loginUrl = response.authenticate[0].url || null;
        var token = response.authenticate[0].token;
        var userID = response.authenticate[0].userID;

        if (result) {
          Ember.run(function () {
            resolve({
              token: token,
              userID: userID
            });
          });
        } else {
          Ember.run(function () {
            resolve(window.location.replace(loginUrl));
          });
        }
      }, function (xhr, status, error) {
        var response;
        if(error === "Unauthorized"){
          response = JSON.parse(xhr.responseText);
        } else {
          response = { message: "Authentication failed. The server may be down" };
        }
        Ember.run(function () {
          reject(response.message);
        });
      });
    });
  }
});
