### ISSUE TITLE
Why OPTIONS method instead of GET for /accounts ? And so Authorization:Bearer ... is'nt send.

### ISSUE THREAD

**Issue by Axxon** [simplabs/ember-simple-auth#699]
Hello, i try to connect my api with ember-simple-auth jj-abrams branch  (latest commit ...254d38d) and try to load user data after session authentification succeed, this is done by a OPTIONS method (I work with password grant).
The dummy exemple try it with a GET method ... so where come from that http verb ?
I had read that OPTIONS request can't have custom headers.
The hash.beforeSend seems to have correct argument "Bearer {$my_token}.
Could you explain or search with me what's wrong ?

**Comment by joelkallman** [comment]
It sounds like you might be running into a CORS problem, which is controlled by the browser and server.

The OPTIONS method is a "preflight" request the browser makes automatically when a cross domain request is initiated. The browser considers a request as cross domain when either the protocol (e.g http), domain (e.g localhost or example.com) or port (e.g. 80, 8080, etc) are different.

The browser is expecting to receive back from the server some `Access-Control-*` HTTP headers that tell it whether or not the initiating domain has the capabilities to execute the desired request.

If the server response allows the browser to make the request, then the browser will then make the request (GET, POST, PUT, etc.)

For example, this basic response example from the server would allow any domain to access the server.

        HTTP/1.1 200 OK
        Access-Control-Allow-Origin: *




Here's some more details on the subject:
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS)

**Comment by marcoow** [comment]
@joelkallman great explanation 👍

**Comment by Axxon** [comment]
Thanks you very much, with that, that's work now for me !
