### ISSUE TITLE
Ajax request does not include token in header

### ISSUE THREAD

**Issue by simo163** [simplabs/ember-simple-auth#701]
this issue could be repeated that I found many posts asking the same, moreover I could not see what wrong. I am wondering why a normal ajax request does not include token in header.

**Comment by fernandes** [comment]
@simi we are facing the same problem here, we are using the ``jj-abrams` branch, do you?

**Comment by jamesdixon** [comment]
Also running into the same issue running the `jj-abrams` branch.

**Comment by marcoow** [comment]
Auto-authorization has been dropped. You now need to explicitly authorize e.g. in your adapter - see the dummy app: https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/tests/dummy/app/adapters/application.js

**Comment by simo163** [comment]
@fernandes yes I do as well. @marcoow I confirm we are based in the dummy example but unfortunately not working.

**Comment by marcoow** [comment]
@simo163: please provide code, e.g. your Ember Data adapter etc.

**Comment by simo163** [comment]
@marcoow here you're, Thanks in advance for looking at it!

```
import DS from 'ember-data';
import Ember from 'ember';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

const {
  RESTAdapter
} = DS;

const {
  pluralize,
  decamelize,
  underscore
} = Ember.String;

export default RESTAdapter.extend(DataAdapterMixin, {
  host: x,
  namespace: y,
  authorizer: 'authorizer:application',

  pathForType(type) {
    var decamelized = decamelize(type);
    var underscored = underscore(decamelized);
    return pluralize(underscored);
  }
});
```

**Comment by marcoow** [comment]
@simo163: which Ember Data version are you using?

**Comment by simo163** [comment]
@marcoow ember-data 2.0.0

**Comment by marcoow** [comment]
@simo163: put a breakpoint here https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/mixins/data-adapter-mixin.js#L40 and check whether that's actually called.

**Comment by simo163** [comment]
@marcoow logs 2, 3 and 4 are inside ajaxOptions function

```
1.Preparing to transition from '' to ' profile.password'
2.test
3.Authorization
4.Bearer b8f464374bf98536ad641386d5053b026b9b6ed1beef28584729c86d33b5a7f8
5.Transitioned into 'profile.password'
6.PUT http://api.xyz.local/v1/users/me 401 (Unauthorized)
```

**Comment by marcoow** [comment]
not sure what you're logging there but looks like the header is generated correctly

**Comment by simo163** [comment]
@marcoow line 1 and 5 shows the redirect to the page, so it calls the ajaxOptions function correctly when I access it. But the PUT request (line 6) is not authorized due to inexistent token.

**Comment by marcoow** [comment]
so what does the request look like?

**Comment by simo163** [comment]
I use to do it two ways:

1. using ic-ajax
```
var options = {
  type: 'PUT',
  data: {
    user: {
      attr1: "x",
      attr2: "y"
    }
  }
};
this.get('ajax').request(url, options).then(function () {
  // do something
}, function (response) {
  // show erros
});
```

2. using Ember ajax
```
var data = {
    user: {
      attr1: "x",
      attr2: "y"
    }
  }
var promise = new Ember.RSVP.Promise(function (resolve, reject) {
  Ember.$.ajax({
    type: 'PUT',
    url: url,
    data: JSON.stringify(data),
    beforeSend: function (xhr) {
      xhr.setRequestHeader("Accept", "application/json");
      xhr.setRequestHeader("Content-Type", "application/json");
    },
    success: function (data) {
     resolve(data);
    }, failure: function (data) {
      reject(data);
    }
  });
});
promise.then(function () {
  // do something
}, function (data) {
  // show erros
});
```

**Comment by marcoow** [comment]
not sure what that is - anyway, you're not setting the `Authorization` header in neither of the 2.

**Comment by simo163** [comment]
when we were using previous version of ember-simple-auth I think 0.8.0-beta.2, it included the Authorization. 

To set it manually, how can we access to the access token in session from a controller e.g.? session.authenticated.access_token and session.secure.token are empty.

**Comment by marcoow** [comment]
auto-authorization was dropped - please see the dummy app

**Comment by simo163** [comment]
@marcoow could you please mention where in the dummy is an ajax request example?

**Comment by fernandes** [comment]
@simo163 this is how we solved, our application adapter is like the one on [dummy app](https://github.com/simplabs/ember-simple-auth/blob/3da1ee1405ba2e369e22bf2d2903f2e44aa90de9/tests/dummy/app/adapters/application.js):

```javascript
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.RESTAdapter.extend(DataAdapterMixin, {
  authorizer: 'authorizer:application'
});
```

if we don't need to customize the adapter for a model, ember _automagically_ creates a new adapter and inherits our adapter and its ok, if we need to customize an adapter for some model, we need to inherits `Application` adapter, like this:

```javascript
import Ember from 'ember';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
import Application from './application';

export default Application.extend();
```

solution by my team mate @silviolrjunior

**Comment by simo163** [comment]
@fernandes thanks for sharing your solution, could you please explain me where the second code goes? I actually also don't understand what do you mean with "customize adapter for a model or some".

**Comment by fernandes** [comment]
hi @simo163 

I mean, if you don't need to [customize an adapter] ember automatically create one for you and inherits `app/adapters/application.js`, if you need to customize, don't forget to inherit application adapter by yourself.

**Comment by simo163** [comment]
Thanks @fernandes! I see what you mean! :thumbsup:

**Comment by fernandes** [comment]
glad to hear, @simo163 :+1:

**Comment by pmkhoa** [comment]
I saw this question asked about the token doesn't include in the Header of Ajax request using with Ember Data.
However, my application doesn't use Ember Data, but instead Ember Ajax (pure ajax) approach to pull / post data. I was wondering is it possible to inject the token globally to the application whenever I initiate the Ajax Request?

Thanks!

**Comment by marcoow** [comment]
@pmkhoa: use the session service's [`authorize` method](http://ember-simple-auth.com/api/classes/SessionService.html#method_authorize).

**Comment by constantm** [comment]
If anybody still has issues with this, here is a code sample to help:

```javascript
this.get('session').authorize('authorizer:devise', (headerName, headerValue) => {
	Ember.$.ajax({
		headers: {
			'Authorization': headerValue
		},
		type: "POST",
		url: "/your_url_here"
	});
});
```

**Comment by marcoow** [comment]
@constantm: you should use `headerName` as well:

```js
this.get('session').authorize('authorizer:devise', (headerName, headerValue) => {
    Ember.$.ajax({
        headers: {
            `${headerName}`: headerValue
        },
        type: "POST",
        url: "/your_url_here"
    });
});
```

**Comment by constantm** [comment]
@marcoow Ah thanks! I tried using `headerName` without `${headerName}`, which obviously didn't work very well. :)

**Comment by pmkhoa** [comment]
@marcoow, @constantm:  is that a way to add the header token globally? If so, where do I put the code to make it work? Thanks!

**Comment by marcoow** [comment]
You could define an `$.ajaxPrefilter` - wouldn't really recommend that as you would usually only want Ember Data requests to be authorized or if you're using plain AJAX you should have an abstraction (e.g. a service) for that which sends the requests and would be the correct place to authorize requests.

**Comment by constantm** [comment]
If you're going to go the service route, there's a really nice Ember addon, [Ember Ajax](https://github.com/ember-cli/ember-ajax/), with excellent support for setting headers.

**Comment by pmkhoa** [comment]
@marcoow, @constantm: Thanks for your recommendation. I will give it a try!

**Comment by simo163** [comment]
I am using Ember-ajax and it facilitates a lot the headers handling.

**Comment by kmmathis** [comment]
I've created an ajax service for making all my calls, but I'm still confused on how to actually set the header in my service. Is the token available to me as a property somewhere in the session service, or do I need to authorize the session in my ajax service every time I make a request?
