### ISSUE TITLE
Compatible with Ember-CLI 1.13?

### ISSUE THREAD

**Issue by fullofcaffeine** [simplabs/ember-simple-auth#702]
I see it says it's not compatible with 2.0, what versions specifically it is compatible with? Is it compatible with 1.13.6?

**Comment by dknutsen** [comment]
The most recent release (0.8.0) isn't compatible with 2.0 but Ember 2.0 compatibility is basically complete, it's just not officially released yet and is currently in a branch (jj-abrams). A lot has changed so make sure you read the docs/dummy app code in the jj-abrams branch if you want to use it in 2.0. The jj-abrams version is also fully compatible with 1.13.X (I used it when upgrading through all the various 1.13 versions). 

I'd suggest also taking a look at #602 before getting started.

Hope that helps!

**Comment by fullofcaffeine** [comment]
@dknutsen Thanks a lot for the comprehensive answer! I'll look into @jj-abrams' branch.
