### ISSUE TITLE
CSRF?

### ISSUE THREAD

**Issue by fullofcaffeine** [simplabs/ember-simple-auth#703]
What's the take on CRSF, being that it `ember-simple-auth` uses token authentication and there's no persistent session created by Rails? 

Thanks!

**Comment by fullofcaffeine** [comment]
Well, I guess it doesn't make much sense, since each time the user logs in, a new token is generated and assigned to the clientside session, somewhat like what you'd do with CSRF (either get from the DOM or get form an API endpoint). So, i'd say CSRF only makes sense when using a session in the backend, like Devise with cookies, for example.

**Comment by marcoow** [comment]
Correct, auth tokens basically have the same characteristics as the CSRF token mechanism that e.g. Rails uses.
