### ISSUE TITLE
routeAfterAuthentication with Dynamic segments

### ISSUE THREAD

**Issue by HenryVonfire** [simplabs/ember-simple-auth#704]
Hi, I have a case in which I perform a login in a nested route with a dynamic segment (i.e. `/libraries/:library_id/login`) and I want to transit to another route under the same path after authenticating (i.e. `libraries/:library_id/interface`) but even if I set `routeAfterAuthentication` to a fixed route like `/libraries/abc/interface` it can't find it. 

I assume that this is actually not supported and I've found a workaround in which I go to a static route and then transitioning from it to the one I want, but I don't know if there's a better way of doing it.

**Comment by marcoow** [comment]
That's not actually not supported. You can just override the `ApplicationRouteMixin`'s `sessionAuthenticationSucceeded` method though.
