### ISSUE TITLE
Updating session secure data in the controller

### ISSUE THREAD

**Issue by maheshiv** [simplabs/ember-simple-auth#708]
Hi,
I have used simple-auth 0.8.0 for one of the application and used custom authenticator. I have set email, authenticationToken to the session-secure key and used in headers. In our app we have an provision to update their email, so whenever user has updated the email, i need to update the session-secure email. When i try to update the value using this.set('session.secure.email', this.get('model').get('email')) and checked in localStorage, the value is not updated but when i do this.get('session.secure.email') will yield the updated value. 
Is it not possible to update session-secure value?
The main issue here is when i refresh the page, the session restore method is called and will use old email in the headers and redirect to login page.

**Comment by joelkallman** [comment]
Try `this.get('session').set('secure.email', this.get('model.email'))`

**Comment by asennikov** [comment]
If I'm not mistaken, it's better to use `data` property now:
`this.get('session').set('data.email')`

And it should be available after page refresh:
`this.get('session.data.email')`

**Comment by maheshiv** [comment]
@asennikov: Thanks.

**Comment by nahtnam** [comment]
I have sort of a similar question.

In my pre-1.0 app, I set up a file in `/app/sessions/user.js` that had this code:
```
import Ember from 'ember';
import Session from 'simple-auth/session';

export default Session.extend({
  currentUser: Ember.computed('secure.uid', 'isAuthenticated', function() {
    var uid = this.get('secure.uid');
    if(uid && this.get('isAuthenticated') ) {
      return this.container.lookup('service:store').find('user', uid);
    }
  })
});
```

This would make an api request to `/users/:uid` and then popular the session store with the user data. How can I go about doing this? (I prefer this way over setting everything in authenticated because its related to a users model so I can call `model.save()`, etc.)

**Comment by marcoow** [comment]
@nahtnam: see the section on custom sessions here: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10

**Comment by nahtnam** [comment]
I never knew this existed. Thank you!

**Comment by nahtnam** [comment]
I tried out this:

```js
import Ember from 'ember';
import DS from 'ember-data';
import SessionService from 'ember-simple-auth/services/session';

export default SessionService.extend({
  store: Ember.inject.service(),

  currentUser: Ember.computed('data.authenticated.access_token', function() {
    var accountId = this.get('data.authenticated.access_token');
    console.log(accountId);
  })
});
```

and it doesnt console.log() anything. The file is located in `/app/services/session.js`, and im injecting it into the application controller:
```js
import Ember from 'ember';
import ENV from '../config/environment';

export default Ember.Controller.extend({
  session: Ember.inject.service('session'),
  loginUrl: ENV.loginUrl,

  actions: {
    invalidateSession: function() {
      this.get('session').invalidate();
    }
  }
});
```

**Comment by nahtnam** [comment]
I figured it out by looking at Ghosts implementation. 

Sorry for the trouble.

**Comment by TangMonk** [comment]
Same issue in 1.0,

When I set `this.set('session.data.currentUser', data);`, and refresh the page, the change will lost, and localStorage still not changed

**Comment by marcoow** [comment]
@TangMonk: you cannot write to the `authenticated` data of the session. Also you shouldn't store a complete use in the session at all but only sth. that would allow you to load the user from the store again later on, e.g. `this.set('session.data.userId', userId);`

**Comment by mdehoog** [comment]
@TangMonk @marcoow note that `this.set('session.data.userId', userId);` won't persist the data in the session across reloads, because the persist logic is implemented in the session's `set` method (https://github.com/simplabs/ember-simple-auth/blob/978242a758172b1a5d93843672ef3ef01574ab27/addon/services/session.js#L117). Instead, use:
`this.get('session').set('data.userId', userId);`

**Comment by marcoow** [comment]
@mdehoog: persistence is implemented in the internal session's `set` method, not the session service's. However there are some problems with that currently and I'm working on improving that for the next release.

**Comment by nahtnam** [comment]
Um, so which one are we supposed to use?

```
this.set('session.data.userId', userId);
```
or
```
this.get('session').set('data.userId', userId);
```

**Comment by marcoow** [comment]
Actually it shouldn't matter. If you find it does that's a bug.

**Comment by nahtnam** [comment]
:+1:

**Comment by mdehoog** [comment]
Sorry for being unclear. If you use `this.get('session').set('data.userId', userId);`, the `set` method I linked to in the session service replaces the `data.userId` key with `session.userId`, which then causes the `setUnknownProperty` method to be called on the internal session, which updates the store.

If you instead use `this.set('session.data.userId', userId);`, the `set` method on the session service is not called, which in turn means the internal session's `setUnknownProperty` is not called, so the store is not updated.

Should I open a bug for this?

**Comment by marcoow** [comment]
yes please
