### ISSUE TITLE
Small readme error - authorizers

### ISSUE THREAD

**Issue by nicnash** [simplabs/ember-simple-auth#709]
Line 234
In the authorizers section 
> // app/authorizers/oauth2.js
> import OAuth2Bearer from 'ember-simple-auth/authenticators/oauth2-bearer';

> export default OAuth2Bearer.extend();

I believe you mean 
> // app/authorizers/oauth2.js
> import OAuth2Bearer from 'ember-simple-auth/**authorizers**/oauth2-bearer';

> export default OAuth2Bearer.extend();

**Comment by marcoow** [comment]
Right, PR would be cool
