### ISSUE TITLE
Devise Authentication broken in jj-abrams branch

### ISSUE THREAD

**Issue by wzowee** [simplabs/ember-simple-auth#712]
Commit afb8b23f3f9a8cceddc9f6bcaa208b4d48b1462f has broken Devise Authentication in the jj-abrams branch.

The change in devise.js from  

    authenticate(credentials) {

to 
  
    authenticate(identification, password) {

has resulted in incorrectly shapped form params being sent to the server.

    user[email][identification]:test@gmail.com
    user[email][password]:somepassword

The problem is being caused by the use of .apply at https://github.com/simplabs/ember-simple-auth/blob/jj-abrams/addon/internal-session.js#L20 , the contents of the args array are being assigned to identification instead of being broken out into the individual arguments.

**Comment by marcoow** [comment]
PR that fixes that would be great

**Comment by wzowee** [comment]
Applogies - will close this - appears there was a change in the api for authenticate that I missed in the documentation.

Where previously you would use:

    var credentials = this.getProperties('identification', 'password');
    this.get('session').authenticate('authenticator:devise', credentials).then( () => {

now you do 

    let { identification, password } = this.getProperties('identification', 'password');
    this.get('session').authenticate('authenticator:devise', identification, password).then( () => {
