### ISSUE TITLE
Feature request - Add demo app

### ISSUE THREAD

**Issue by dbachet** [simplabs/ember-simple-auth#720]
Hi,

I have been doing a demo app for 0.8.0 version of ESA with a "devise" backend.

Do you plan to add some examples or demo apps inside the repo for the 1.0 version?  

I would be interested in helping with this.

**Comment by marcoow** [comment]
Devise could be added to the dummy app with a mock devise server. PR would be great!

**Comment by JeskTop** [comment]
:+1:

**Comment by marcoow** [comment]
Just to be clear - there is a dummy app included in the repo (https://github.com/simplabs/ember-simple-auth#how-do-i-use-it), it just doesn't use devise.

**Comment by abhayathapa** [comment]
@marcoow I created app like dummy as mentioned but I get error as `POST http://localhost:4200/token 404 (Not Found)` with facebook. Can we create a separate demo repo using ember-simple-auth in package.json. That would be really helpful.

**Comment by marcoow** [comment]
@abhayathapa you don't seem to have a server that supports the `authorization_code` OAuth 2 grant type. Check the mock server in the dummy app for reference. If you're using Rails you might want to use https://github.com/simplabs/rails_api_auth.

**Comment by dbachet** [comment]
@marcoow excellent, I will try to address that asap.

**Comment by abhayathapa** [comment]
@marcoow  @dbachet Devise and facebook login repo with briefing about backend would be really useful

**Comment by marcoow** [comment]
Not sure all of these should go into the dummy app actually. Would be cool if someone would send a PR for the example app: https://github.com/simplabs/ember-simple-auth-example

**Comment by JeskTop** [comment]
My app update to 1.0 from 0.7.x and my rails code counld not work.
```
def authenticate_user_from_token!
    authenticate_with_http_token do |token, options|
      user_email = options[:email].presence
      user = user_email && User.unscoped.find_by_email(user_email)
      if user && Devise.secure_compare(user.authentication_token, token)
        sign_in user, store: false
      end      
    end  
  end
```
So I think if `ember-simple-auth` has a demo app for 0.8.0 version of ESA with a "devise" backend will be better.

**Comment by dbachet** [comment]
@marcoow I started to update the demo app from https://github.com/simplabs/ember-simple-auth-example repo. 

You talked about a "mock devise server". So far I added a plain rails app into the repo to make it work with ESA version 1.0 first.

Should it be done via the https://github.com/simplabs/ember-simple-auth-example/blob/master/server/routes/token.js ? I'm not very comfortable with it but I can find out that works.

**Comment by marcoow** [comment]
@dbachet: yes, it should either be a mock server using https://github.com/simplabs/ember-simple-auth-example/blob/master/server/routes/token.js or an actual Rails app which should live in a separate repo then though.

**Comment by dbachet** [comment]
@marcoow alright, thx for feedback!

**Comment by jimbeaudoin** [comment]
All the works is done for rails in the closed PR. If you start a new repos for rails you can take a look at it.

**Comment by jimbeaudoin** [comment]
Please don't do a mock server for Devise. You are breaking this rules http://12factor.net/dev-prod-parity. ;)

**Comment by marcoow** [comment]
@jimbeaudoin: that's actually just going to be a demo app anyway that shows how to use ESA with devise.

**Comment by jimbeaudoin** [comment]
@marcoow Ok. I respect your work and this is your project. :v:

**Comment by dbachet** [comment]
@marcoow @jimbeaudoin I have been trying to at least use the version 1.0 with my rails server at first.

https://github.com/simplabs/ember-simple-auth-example/compare/master...stackbuilders:add-example-for-devise

As I want to use ESA with a different backend host I wanted to be able to redirect the requests to localhost:3000. But neither `ember server --proxy http://localhost:3000` nor adding an adapter did the trick. Indeed I get 

<img width="488" alt="screenshot 2015-10-29 a 19 26 45" src="https://cloud.githubusercontent.com/assets/675579/10828141/129e6070-7e73-11e5-8512-4ccb04dc98b7.png">

associated with a Ember server error after waiting for some time

```
POST /users/sign_in - - ms - -
Error proxying to http://localhost:3000
socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at Socket.socketCloseListener (_http_client.js:247:23)
    at Socket.emit (events.js:129:20)
    at TCP.close (net.js:485:12)
POST /users/sign_in 408 30017.082 ms - 303
```

and finally this on Rails server side

```
[2015-10-29 19:16:51] ERROR invalid body size.
```

Would you have a little clue how to avoid that? 

If I get this to work I would like to add some comments in the README so that people could know how to use it.

Thx

**Comment by marcoow** [comment]
@dbachet you can configure the authenticator to speak to the Rails app directly without proxying - set [`serverTokenEndpoint`](http://ember-simple-auth.com/api/classes/DeviseAuthenticator.html#property_serverTokenEndpoint) accordingly.

**Comment by jimbeaudoin** [comment]
@dbachet you get this error probably because you are running the mock server and you want to proxy to another one. You need to rename or remove the mock server folder to make you request go to your rails backend without interference or do like @marcoow just said. I didn't test with `serverTokenEndpoint`

**Comment by dbachet** [comment]
@marcoow excellent! Thx

**Comment by JeskTop** [comment]
When I update ESA version, I have this probles. http://stackoverflow.com/questions/33474274/ember-simple-auth-devise-after-update-authenticate-with-http-token-alway-empt  Do you have an idea ? Thx.

**Comment by abhayathapa** [comment]
@jimbeaudoin @marcoow Using devise as backend rails app.. what is the best way to create new signup from ember.. Is it just creating new user record on ember side and saving it? What is the best way to send request to RegistrationController of devise ?

**Comment by stevenwu** [comment]
Closing this as it's over a year old. Join us in #e-simple-auth @ [Ember Community Slack](https://ember-community-slackin.herokuapp.com/) if there are more questions.
