### ISSUE TITLE
In the dummy app, you're returning a promise in a promise?

### ISSUE THREAD

**Issue by constantm** [simplabs/ember-simple-auth#725]
Not a real issue. I'm just wondering why a promise is being created manually when this.store also returns a promise, causing a promise within a promise?

https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/services/session-account.js#L13

**Comment by dschmidt** [comment]
It's a PromiseObject not a Promise. It allows you to directly access `sessionAccount.user.name` from the template.

**Comment by constantm** [comment]
Ah okay, thanks. Would you mind explaining why you would not be able to access `sessionAccount.user.name` from the template when not wrapping it in a PromiseObject? I think don't understand 100% what you mean, since I removed the wrapper and it still worked as before in the template.

**Comment by dschmidt** [comment]
http://emberjs.com/api/data/classes/DS.PromiseObject.html

Ah, maybe I was wrong on the template bit. Could be that the view layer automatically handles the Promise directly. But you need this for data bindings in your code. For example try to base a computed property on `user.name` or observe it.

**Comment by Exelord** [comment]
I think its not working well.
When I inject the service and next in component login in some action I type eg.
```
if (this.get('sessionAccount.account.firstName'){
console.log('ok')
}
```

It wont works :/
Is that cuz it returns a promsie rather than instance of ember data model. Am I wrong? What can be solution for that?

**Comment by constantm** [comment]
@Exelord I think the best would be to create an Ember Twiddle and ask for help on the Ember Slack channel.

**Comment by marcoow** [comment]
@Exelord, yes, that's because `account` returns a promise so you're actually getting the `firstName` property from the promise on which it doesn't exist. You'd want to resolve that promise in the route's `model` method.

**Comment by Exelord** [comment]
Hmm, It has a sense but what if I need access to account in many components whatever route they are? There is an option for resolving a promise eg. in initializer?

**Comment by marcoow** [comment]
You can just inject the account service as it is used in the test app in all components you need access to the session account. If you need to resolve the promise first the best place for that would be in the route's `model` method.
