### ISSUE TITLE
Can't find authenticators or authorizers except for base

### ISSUE THREAD

**Issue by tsteuwer** [simplabs/ember-simple-auth#737]
Library Version
Ember Inspector 1.9.3
Ember 1.13.5
Ember Data 1.13.5
jQuery 1.11.3
Ember Simple Auth 0.8.0

When I try and 

```
import Base from 'simple-auth/authorizers/oauth2-bearer'
```

or

```
import Base from 'simple-auth/authenticators/oauth2-password-grant';
```

It can not find them. This was installed via ember install ember-simple-auth.

**Comment by dknutsen** [comment]
I could be wrong but I don't think authenticators and authorizes were added until ESA 1.0.0 (which was officially released last week), you're using ESA 0.8.0. I would recommend changing your ember-simple-auth version to "1.0.0" in your package.json.

**Comment by tsteuwer** [comment]
Ok, so it just hasn't been updated on NPM?

**Comment by dknutsen** [comment]
Should have been, we're actually using it in our app and I did a build with it today. Not sure why it wouldn't have installed 1.0.0 via ember-cli...

**Comment by marcoow** [comment]
The OAuth 2 authenticator and authorizer were called just oauth2 in 0.8.0, e.g. `'simple-auth/authenticators/oauth2'`. As @dknutsen says though you should upgrade to 1.0 if possible.

**Comment by tsteuwer** [comment]
Just an FYI, I just tried with 1.0.0, this issue still happens.
