### ISSUE TITLE
Configuration setup

### ISSUE THREAD

**Issue by Exelord** [simplabs/ember-simple-auth#739]
Hi,
I use configuration from ReadMe
```
ENV['ember-simple-auth'] = {
  basURL: 'api/'
};
``` 
but there is no result. I use `DeviseAuthenticator` and also try to extend the object like:
```
export default DeviseAuthenticator.extend({
  baseURL: 'http://api.local:3000/',
});
```

There is another way or the correct one to setup API url?

**Comment by nahtnam** [comment]
Check out #731
