### ISSUE TITLE
How do I manually set the token? 

### ISSUE THREAD

**Issue by nahtnam** [simplabs/ember-simple-auth#741]
Hey! 

I am authenticating using openid which means that I have to redirect the user to a different url and then have the backend processes it. Here is the process:

1. User goes to the external site and signs in
2. They get redirected to my api server which handles the authentication. 
3. The user gets redirected to my ember app: ember.com/login/:token

At step 3, I want to take the token param and insert it into to ESA. 

How would I go about doing that? 

Thanks.

**Comment by dukex** [comment]
Today I'm setting the token using a private API 
https://github.com/uhuraapp/uhura-frontend/blob/master/app/mixins/controllers/authentication.js#L59

I'll be happy if someone find a good way to do it

**Comment by nahtnam** [comment]
Is setting up a custom authenticator the best/only way?

**Comment by marcoow** [comment]
Yes, using a custom authenticator is the way to do this. Should also be pretty straight forward in your case.

**Comment by rashed0** [comment]
http://rashed0.tip.me/

**Comment by rashed0** [comment]
http://rashed0.tip.me/

**Comment by rashed0** [comment]
http://rashed0.tip.me/

**Comment by rashed0** [comment]
http://rashed0.tip.me/

**Comment by rashed0** [comment]
http://rashed0.tip.me/

**Comment by rashed0** [comment]
http://rashed0.tip.me/

**Comment by rashed0** [comment]
http://rashed0.tip.me/
