### ISSUE TITLE
session.data may not fetch data when manually refresh app

### ISSUE THREAD

**Issue by nightire** [simplabs/ember-simple-auth#743]
I think this might be a bug, but I'm not sure if its ember-simple-auth's responsibility.

Suppose I have a controller with some parameters:

```javascript
import Ember from 'ember'
import moment from 'moment'

export default Ember.Controller.extend({
  session: Ember.inject.service(),
  queryParams: ['storeId', 'bookingDate', 'storeBeginTime'],
  storeId:     Ember.computed.alias('session.data.authenticated.employee.storeId'),
  bookingDate: moment().format('YYYY-MM-DD'),
})
```

I save the `storeId` when user logged in, so I need `session` service to fetch it back. in the default situation, that means all params with the default value, all things are okay.

But when other params have changed, e.g: `bookingDate` changes to another date, and I manually refresh the app (pasting url in another tab or refresh the browser), storeId will be `undefined`.

Currently, I'd have to use `localStorage` to replace the `session` service, so code above becomes to:

```javascript
import Ember from 'ember'
import moment from 'moment'

export default Ember.Controller.extend({
  session: Ember.inject.service(),
  queryParams: ['storeId', 'bookingDate', 'storeBeginTime'],
  storeId:     JSON.parse(localStorage.getItem('ember_simple_auth:session')).authenticated.employee.storeId,
  bookingDate: moment().format('YYYY-MM-DD'),
})
```

In this way, `storeId` can be guaranteed to be fetched. This could be a bug, hope someone to look into it.

**Comment by fidlip** [comment]
What browser do you use? I'm experiencing this in IE11.

**Comment by nightire** [comment]
@fidlip FYI, Chrome dev channel & Chrome beta

**Comment by fidlip** [comment]
Thanks, so it will be another bug. In chrome I'm OK. Bye

**Comment by marcoow** [comment]
You shouldn't write to the session's `authenticated` data. In fact when you try to do that it should actually raise an error but I think there's a bug that prevents that error currently.

**Comment by nightire** [comment]
@marcoow Is that so? But how we save the `currentUser` with its useful data that returns from the signin endpoint of API server?

I read about `session.data` is written in the localStorage by default, so I manually add `currentUser` information with it. If this is not recommended with ember-simple-auth, then I really need to consider other ways.

**Comment by marcoow** [comment]
you don't save the current user, you only save the current user's id or so - check the dummy app in the repo

**Comment by nightire** [comment]
@marcoow One thing I have to explain, we have to deal with a legacy api server, before it compatible with REST or JSON API, some pain points should be fixed by manually.

the `User` server returns after successfully log in is totally different between the actual `User` in App's Data Model, and we have to save this non-sense fake user out of data store, otherwise we have to define a wired model only for this, so only a `user.id` doesn't fill our requirements, in fact api server doesn't return `user.id` to us at all, it returns a `storeId`, then we need to use this to fetch more depth data.

This is why we need to save & fetch `storeId` by using session service, but I would like to listen other better ideas.

**Comment by nightire** [comment]
This might related with https://github.com/emberjs/ember.js/issues/11592, because of a CP based QP

**Comment by nightire** [comment]
I'm closing this because queryParams shouldn't be a CP currently, this behavior maybe changes in the future.
