### ISSUE TITLE
Post requests not authorized

### ISSUE THREAD

**Issue by cimtico** [simplabs/ember-simple-auth#745]
For some reason my post requests aren't being authorized.
I added set this as my authorizer:

import OAuth2Bearer from 'ember-simple-auth/authorizers/oauth2-bearer';

    export default OAuth2Bearer.extend({
      authorize: function(){
        console.log("Authorizing");
        console.log(arguments);
        return this._super.apply(this, arguments);
      }
    });

and have this in my application adapter

    import ENV from "../config/environment";
    import Ember from 'ember';
    import ActiveModelAdapter from 'active-model-adapter';
    import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

    export default ActiveModelAdapter.extend(DataAdapterMixin, {
      authorizer: 'authorizer:oauth2',
      ...
    });

I can see get requests working just fine (I can see the log message and the token in the headers), but when I attempt a post request it seems it is not going through the authorizer (no header or console log message).

Any suggestions?

**Comment by cimtico** [comment]
as an additional note, the request is being done through Ember.$.post (which I'm guessing isn't affected by the adapter's ajaxOptions).

**Comment by marcoow** [comment]
are you doing that request manually?

**Comment by cimtico** [comment]
Yes

    resume: function (store, type, snapshot) {
        var model = snapshot.record;
        var url = this.buildURL(type.modelName, model.get("code"), snapshot) + '/resume';
        return Ember.$.post(url);
    }

So I'm wondering how to set it up so that the bearer will get automatically inserted on all requests (as it was working before the 1.0 release).

**Comment by marcoow** [comment]
In that case you'd need to use the [session service's `authorize` method](http://ember-simple-auth.com/api/classes/SessionService.html#method_authorize).

**Comment by cimtico** [comment]
Would it be possible to get it done as a global setting instead of having to re-write all the requests?

**Comment by marcoow** [comment]
No, that's not a good idea for several reasons (actually it was removed in 1.0 as it was causing more problems than it solved). You can add an abstraction that all AJAX requests get send through in your app or you could use an `$.ajaxPrefilter` but I wouldn't really suggest doing that.
