### ISSUE TITLE
Addon incompatible with ember-coffeescript

### ISSUE THREAD

**Issue by wuron** [simplabs/ember-simple-auth#747]
After upgrading ember-simple-auth from 0.8.x to 1.0.x if crashes on ember build. I have [ember-cli-coffeescript](https://github.com/kimroen/ember-cli-coffeescript) installed and have my app route defined as `routes/application.coffee` which seems to conflict with `routes/application.js` provided with addon.

**Comment by marcoow** [comment]
You need to implement the application route in plain JS as `application.js`. There's nothing Ember Simple Auth can do to prevent this error. You could argue it's an error in Ember CLI but in general the best solution is to switch to ES2015 instead of coffeescript anyway ;)
