### ISSUE TITLE
Documentation mismatch for facebook authenticator, How to import provider/authenticator?

### ISSUE THREAD

**Issue by mattmazzola** [simplabs/ember-simple-auth#751]
I'm trying to integrate the new ember-simple-auth into my ember app and use the facebook authenticator from torii and I am confused by the documentation.  I've successfully done this with the old version of ember-cli-simple-auth.

I ran:
```
ember install ember-simple-auth
ember install ember-cli-simple-auth-torii
```

And went through and set all the route mixins, authenticators, and authorizers up, and made the changes to configuration file, but I'm not sure how to use the included torii providers in the new ember simple auth.

I found the documentation for using Facebook authenticator on this page:
[http://ember-simple-auth.com/api/classes/ToriiAuthenticator.html]
which says to use this:
```
import FacebookOauth2Provider from 'torii/providers/facebook-oauth2';

export default FacebookOauth2Provider.extend({
  fetch(data) {
    return data;
  }
});
```
in a file at `app/authenticators/facebook.js` and then if this worked (see below) I would be able to make a call to authenticate using this authenticater with `this.get('session').authenticate('authenticator:facebook');`

However, when I run the app, there is an error:
`Uncaught Error: Could not find module 'torii/providers/facebook-oauth2' imported from 'client/authenticators/facebook'`

I can see the path to the torii folder in the node modules at
`/node_modules/ember-cli-simple-auth-torii/node_modules/torii/lib/torii/providers/facebook-connect.js`

But I can't figure out how to import the Facebook authenticator with the new addon.

Any tips?

**Comment by marcoow** [comment]
Did you install the `torii` addon? Also you need to define the provider in `app/torii-providers/facebook.js`, not `app/authenticators/facebook.js`.

**Comment by mattmazzola** [comment]
I see on that same documentation page it says:
`In order to use this authenticator, the application needs to have the torii addon installed and must inject the torii service into the authenticator:`
And the torii addon links directly to the torii repo instead of the ember-cli-simple-auth-torii repo.

Does this mean I should be using:
`npm install torii --save-dev`
Instead of using the addon which wraps this library?
`ember install ember-cli-simple-auth-torii`

Also, I thought that when I make the call to authenticate using a specific provider it would have the form:
`this.get('session').authenticate('authenticator:facebook');`

And in order for it to resolve 'authenticator:facebook' i would need a file at the path `app/authenticators/facebook` which happens to be the provider from torii.

If I move the facebook file to `app/providers/facebook` will the call above still be the same to use it?

**Comment by marcoow** [comment]
You will authenticate the session with

```js
this.get('session').authenticate('authenticator:tori', 'provider:facebook');
```

Check the API docs as well as the dummy app for reference.

`ember-cli-simple-auth-torii` Is deprecated and you shouldn't be using it anymore.
