### ISSUE TITLE
Backwards compatibility?

### ISSUE THREAD

**Issue by Fryie** [simplabs/ember-simple-auth#753]
I currently use an older version of ember-simple-auth that stores its data under ```session.secure```. I would very much like to upgrade the library and as far as I understand, the session data is now stored under ```session.data.authenticated```. My question is whether this might cause strange behaviour or errors on clients that still have the old data lying around in local storage.

If a user just has to log in again, that's fine. But I just want to make sure there's no chance of a JS error being thrown or non-deterministic behaviour that causes weird bugs or anything like that. So in essence, is there anything I have to take care of?

**Comment by marcoow** [comment]
Users will just have to login again as the current session that they have in `localStorage` Won't be valid anymore.

**Comment by Fryie** [comment]
Thanks, as long as nothing breaks that's ok.
A general migration path might be helpful. :) Other than that I'm liking the "recent" changes so far, it makes the whole library much more streamlined.

**Comment by marcoow** [comment]
I wrote a blog post about updating to 1.0 here: http://log.simplabs.com/post/131698328145/updating-to-ember-simple-auth-10

**Comment by Fryie** [comment]
ah awesome! Maybe a link in the README might be helpful. Thanks again!

**Comment by Fryie** [comment]
see #754
