### ISSUE TITLE
sessionDataUpdated: how to use it?

### ISSUE THREAD

**Issue by youroff** [simplabs/ember-simple-auth#755]
What's the proper way to assign event-handle for this event?

**Comment by marcoow** [comment]
You never handle that event, it's handled by the session and you can fire it from custom authenticators or session stores.

**Comment by youroff** [comment]
May I ask you for more details?
So I create application.js in /app/session-stores, where I extend Adaptive store. What I do next?
My final goal is to notify another service about changes in session store. I tried to attach observer on `session.data.some_custom_key`, but it didn't work.

**Comment by marcoow** [comment]
Observing the respective property on the session service should actually work. You don't need a custom session store for that.
