### ISSUE TITLE
incrementProperty on session key doesn't fire change notification (across different tabs)

### ISSUE THREAD

**Issue by youroff** [simplabs/ember-simple-auth#757]
So I was experimenting with state sharing across tabs and discovered that session in other tabs doesn't (or not always) notify observer about change if it was made with 'incrementProperty'.

Way to reproduce:

```
this.get('session').incrementProperty('data.counter')
```

```
_trackCounter: function() {
   alert("Yay, counter value increased");
}.observes('session.data.counter')
```

**Comment by youroff** [comment]
I played with this one more and found that if I output incremented property in template it's also not always shown correctly. But what is worse, observer not always works for second level properties, like `data.counter` if it's attached without `.on('init')`. Maybe I just misunderstand how observers work, but inside of one app it all works good.

**Comment by youroff** [comment]
Oh, I think I know the reason. As said in docs:
"If you never get a computed property, its observers will not fire even if its dependent keys change. You can think of the value changing from one unknown value to another."

So as long as session storage passed on as computed property, that may be the case. How do you think, can it be fixed somehow?

**Comment by marcoow** [comment]
This is probably the same bug as e.g. #805

**Comment by marcoow** [comment]
yes, this is the same as #805 - we'll track everything there
