### ISSUE TITLE
session-store clear() not called on invalidate?

### ISSUE THREAD

**Issue by csetera** [simplabs/ember-simple-auth#758]
I see in the ember-simple-auth code that the session-store implementation provides a clear() hook.  I've created a new application-scoped session store that extends from the Base session store implementation and overrides the clear() function.  However, I don't see that function ever being called when the session is invalidated.  Looking at the source code, I see the clear logic in internal-session.js, but I don't see anything in the code that would suggest to me that the session-store clear() function is going to be called from anywhere.  Am I missing something or is that functionality not currently working?

**Comment by csetera** [comment]
I should add that overriding sessionInvalidated on my application route (with the ApplicationRouteMixin) *does* fire as expected

**Comment by csetera** [comment]
For the moment, this seems to work, but doesn't seem like it should be necessary.  (Application route):
```
  sessionInvalidated: function() {
  	this.get('session').get('session').get('store').clear();
  }
```

**Comment by marcoow** [comment]
The session store's `clear` method is only really being used in tests as the session isn't cleared completely when it is invalidated (only the `authenticated` section is deleted, all other session data stays intact).
