### ISSUE TITLE
ESA 1.0.1 not compatible with ember-data < 1.13?  handleResponse doesn't exist on beta18

### ISSUE THREAD

**Issue by kjhangiani** [simplabs/ember-simple-auth#759]
Not sure if this is mentioned anywhere, as I can't see a minimum requirement for ember-data (only ember at 1.12), but it does seem like ember-simple-auth requires ember-data 1.13 (if ember-data is used).

In particular, the DataAdapterMixin uses the handleResponse callback, however, handleResponse does not exist until ember-data 1.13, ajaxError and ajaxSuccess are used on prior versions.

I'm working on polyfilling this to make our app work right now, but might want to update the minimum requirements somewhere and mention the ember-data version.

There are also issues with ember-data beta19.2 due to initializers, store:main, store:application, and service:store registry names... I could not actually even get anything to load on beta19.2.  Rolling back to 19.1 fixed some of the initializer issues, but broke other parts of our app, hence forcing me to rollback to beta18.

Here's some of the issues I encountered:

Ember 1.11.3, ESA 0.8, ember-data beta16 = everything works, but ESA is using old API

upgraded to:

Ember 1.12.1, ember-data beta19.2, ESA 0.8 = everything works, but tons of deprecations due to initializer/instance initializer errors

After following the ESA upgrade guide and upgrading to ESA 1.0.1 and refactoring our session service, upgraded to:

Ember 1.12.1, ember-data beta19.2, ESA 1.0.1 = everythings broke, due to some interaction between ESA 1.0.1 and ember-data beta 19.2, related to store:main, store:application names

Downgraded ember-data:

Ember 1.12.1, ember-data beta 19.1, ESA 1.0.1 = ESA works, initializer deprecations mostly fixed, but ember-data beta 19.1 broke some other parts of our app (unrelated to ESA, some change to component 2way bindings).  handleResponse also still does not exist.

Downgraded ember-data again:

Ember 1.12.1, ember-data beta 18, ESA 1.0.1 = ESA works for initial authentication, login/logout, but fails when a 401 response is returned, due to DataAdapterMixin using handleResponse instead of ajaxError

**Comment by kjhangiani** [comment]
This is my current solution, seems to work, just not sure if that "return true" affects anything on ajaxError vs handleResponse


    /**
		adapters/application.js

                @TODO: NOTE, ember-data 1.13 changes ajaxError and ajaxSuccess to use handleResponse
		this is a polyfill for ESA compatibility with ember-data beta18
	**/
	ajaxError: function(jqXHR) {
		// if 401, ESA needs to invalidate
		if (jqXHR && jqXHR.status === 401) {
			if (this.get('session.isAuthenticated')) {
				this.get('session').invalidate();
			}
			return true;
		} else {
			return this._super.apply(this, arguments);
		}
	}

**Comment by marcoow** [comment]
You're right - this should be mentioned in the docs.
