### ISSUE TITLE
Upgrading from 0.8, `Cannot read property 'hasRoute' of undefined` on Ember 1.13

### ISSUE THREAD

**Issue by kenips** [simplabs/ember-simple-auth#761]
Hi there, I'm upgrading from 0.8 and getting a `Cannot read property 'hasRoute' of undefined` error in my acceptance test cases.

Upon probing I see that the error is from Ember itself (using 1.13) during transitionTo and triggered by `ApplicationRouteMixin` on `sessionAuthenticated`. Removing `ApplicationRouteMixin` solves the issue - but I'm wondering what the proper solution is? I don't recall seeing transition with the previous test helpers.

**Comment by kenips** [comment]
Sorry my bad! Just side effect of plying into application-route in the tests!

**Comment by kbullaughey** [comment]
I am having this problem too...what was the solution?

**Comment by kenips** [comment]
If I remember this correctly it was caused by me opening the application route in my test via reopen. Using lookup fixed it.

**Comment by kbullaughey** [comment]
I found the solution to my problem. I was fetching the route using a helper too early, if I waited until after `visit` resolved, everything worked, for some still unknown reason. Thanks for your help.
