### ISSUE TITLE
Documentation on integrating torii and ember-simple-auth

### ISSUE THREAD

**Issue by venkatd** [simplabs/ember-simple-auth#762]
I had some trouble getting torii and ember-simple-auth working together. Here is how I got it working.

**app/authenticators/torii.js**
```
import Ember from 'ember';
import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii';

export default ToriiAuthenticator.extend({
  torii: Ember.inject.service()
});
```

I can define a torii provider at **app/torii-providers/my-torii-provider.js**.

Then in my app, I can call:
```
this.get('session').authenticate('authenticator:torii', 'my-torii-provider', {someOption: 123});
```

The result that comes back from the torii can be accessed through `session.get('data')`

Pretty cool! What's the best place to update the docs?

**Comment by marcoow** [comment]
I guess the best option would be to update the [API docs for the `ToriiAuthenticator`](http://ember-simple-auth.com/api/classes/ToriiAuthenticator.html) and extend the example to include a torii provider and a sample invocation of `this.get('session').authenticate(…)`.
