### ISSUE TITLE
session data not available in instance intializer. 

### ISSUE THREAD

**Issue by Kilowhisky** [simplabs/ember-simple-auth#764]
I don't know if this is supposed to work or is not a supported feature but i cannot access the `session.data` content in an instance initializer.  It just returns a blank object with a bare 'authenticated' property. 

For instance.

```
export function initialize(instance) {

    // Get the  service
    var  service = instance.lookup('service:session');
    var i18n = instance.lookup('service:i18n');

    // Restore the locale from local storage
    i18n.set('locale', service.get('data.locale') || 'en-US');

    // Observe the locale changes and store them in the settings object
    Ember.addObserver(i18n, 'locale', function(){
        service.set('data.locale', i18n.get('locale'));
    });
}

export default{
  name: 'restore-locale',
  initialize: initialize,
  after: 'ember-simple-auth'
};
```

Through testing i can confirm that all the initialzers are running before this block is called.

**Comment by marcoow** [comment]
The session data isn't restored from the session store when the initializers run. Session data is restored in the application route's `beforeModel` method so you'd want to run your code after that.

**Comment by Kilowhisky** [comment]
Ahh... i see it now. Maybe i should have read the initializer before i called it a bug!  

Any reason for this? It is just so that you can block the app while its restoring? 

I'll close the issue now but i'm just wondering.

**Comment by marcoow** [comment]
Yeah, the reason is that restoration might take some time and it needs to run after the application has booted up so a potential loading route would be displayed while restoration is in progress. If it is run in an initializer and defers application readiness you'd only see a blank page until it has finished.
