### ISSUE TITLE
Not working cookieDomain option

### ISSUE THREAD

**Issue by Exelord** [simplabs/ember-simple-auth#767]
Hi,
I noticed that var cookieDomain after extending class `ember-simple-auth/session-stores/cookie` not working :/

thats my code:
`app/session-stores/application.js`
```
import Cookie from 'ember-simple-auth/session-stores/cookie';

export default Cookie.extend({
  cookieDomain: '.localhost',
});

```

**Comment by marcoow** [comment]
What specifically isn't working for you?

**Comment by Exelord** [comment]
If i set the cookieDomain cookies aren't stored :/

**Comment by marcoow** [comment]
I don't think `.localhost` works at all. This is most likely not a bug in ESA.

**Comment by Exelord** [comment]
Should I need some more config? Eg. in config file? I have a clean setup and if `cookieDomain` is set to null there is no problem.

**Comment by marcoow** [comment]
I think you cannot specify `.localhost` as the cookie domain at all as browsers don't allow it. Try setting a cookie with that cookie domain manually in the console and check whether that works.

**Comment by Exelord** [comment]
You have a right! This was a security reason on some browser eg. chrome. Thanks for help and sorry for making issue :/
:+1:

**Comment by villander** [comment]
@marcoow and @Exelord This means that the cookieStore already works for `.localhost`  (which includes all subdomains) as `bb.localhost`, `xx.localhost`,  `esa.localhost` ?

**Comment by marcoow** [comment]
See above - I don't think setting `.localhost` as a cookie domain works at all. You'll probably have to run a proxy in development if you need subdomain cookie sharing.
