### ISSUE TITLE
Visiting more than 1 authenticated route in acceptance test fails to redirect

### ISSUE THREAD

**Issue by thijsvdanker** [simplabs/ember-simple-auth#769]
When visiting more than 1 authenticated route in my acceptance test, the second time the test report that the user was not redirected to the login page but currentURL() resolves to /protected-route.

```js
test('Unauthenticated users can not visit routes that require authentication', function(assert) {
    // When I visit a protected route.
    visit('/protected-route');

    andThen(function() {
      // Then I get redirected to the login page.
      assert.equal(currentURL(), '/login');
    });

    // When I visit it again.
    visit('/protected-route');
    andThen(function() {
      // Then I get still get redirected to the login page.
      assert.equal(currentURL(), '/login');
    });
});
```

The test in this gist visits the same route twice, but I see the same behaviour when using different routes.

Full test in this gist: https://gist.github.com/thijsvdanker/891cdf85e1066e69682d

**Comment by marcoow** [comment]
Cannot reproduce this. Can you set up a demo project that generates this error? You can just fork this repo and change the [`'Acceptance: Authentication'` test](https://github.com/simplabs/ember-simple-auth/blob/master/tests/acceptance/authentication-test.js) so that it generates this error - it didn't fail for me though.

**Comment by thijsvdanker** [comment]
When using Mocha + chai (both in your repo and in my own project) the test passes!
When using qunit in my project, the test fails. Not sure why and it's probably not something that should be fixed on the ESA side.
Thanks for the response though!
