### ISSUE TITLE
Windows Phone session promise doesn't resolve

### ISSUE THREAD

**Issue by mapohjola** [simplabs/ember-simple-auth#770]
This only happens on Windows Phone 8

I have an authenticator that extends the oauth2 authenticator:
```
promise = this.get('session').authenticate('authenticator:my-auth', data.identification, data.password);
promise.then(function () {
          console.log('promise success')
}
```
but the promise doesn't resolve, I am also getting 
`Invalid character` error from the JSON.parse() row
```
/**
Returns all data currently stored in the `localStorage` as a plain object.
@method restore
@return {Object} The data currently persisted in the `localStorage`.
@public
*/
restore: function restore() {
      var data = localStorage.getItem(this.key);
      return JSON.parse(data) || {};
}
```

**Comment by marcoow** [comment]
What's the content of `localStorage` when this error happens?

**Comment by mapohjola** [comment]
It seems to be undefined, having a hard time debugging on WP

**Comment by mapohjola** [comment]
So it seems that the authenticate request returns an error
```
{
       "readyState": 0,
       "status": 0
       "statusText": "Error: Access is denied"
}
```
and somehow the authenticate promise is not resolved nor rejected.

**Comment by marcoow** [comment]
Maybe you're not handling that error in your custom authenticator and are not rejecting the promise correctly in that case. This is really more a question for stackoverflow or maybe slack though, not actually an issue.

**Comment by mapohjola** [comment]
I'm just extending the oauth2 authenticator, so no this is not the case.

**Comment by shen6653** [comment]
I think I hit the same issue. The error indicates that the key contains invalid character. Looks like it complains the key ("ember_simple_auth:session") contains ':' character in my case.

https://msdn.microsoft.com/query/dev12.query?appId=Dev12IDEF1&l=EN-US&k=k(VS.WebClient.Help.SCRIPT1014)

**Comment by shen6653** [comment]
Actually I got 'invald character' error in restore() function at JSON.parse(e), where e is undefined and this.key is 'ember_simple_auth:session'. Checked localstorage, the value for 'ember_simple_auth:session' is undefined. So looks like a problem with JSON.parse() an undefined string.

restore:function(){var e=localStorage.getItem(this.key);return JSON.parse(e)||{}}

**Comment by shen6653** [comment]
What about changing
JSON.parse(e) || {}
to
JSON.parse(JSON.stringify(e || {}));

**Comment by shen6653** [comment]
The problem went away after upgrading to ember-simple-auth 1.1.0-beta.1.
