### ISSUE TITLE
Readme still indicates config in environment.js

### ISSUE THREAD

**Issue by technomage** [simplabs/ember-simple-auth#771]
The change log indicates config has moved to the authorized or authentication subclass, but the read me still indicates using environment.js.

**Comment by marcoow** [comment]
`config/environment.js` is still used for some things - actually the things mentioned in the docs. Is there anything in the docs that doesn't work for you?

**Comment by technomage** [comment]
It was more an issue with the change log implying all config removed from environment.js

**Comment by marcoow** [comment]
Ok, I see. I think the README and API docs make it clear though.
