### ISSUE TITLE
You are trying to use the torii authenticator but torii is not available

### ISSUE THREAD

**Issue by wayne-o** [simplabs/ember-simple-auth#772]
The following results in:

```
You are trying to use the torii authenticator but torii is not available. Inject torii into the authenticator with "torii: Ember.inject.service()".
``` 

But I have injected the torii service?

```
import Torii from 'ember-simple-auth/authenticators/torii';
import Ember from 'ember';

export default Torii.extend({
	torii: Ember.inject.service(),
	restore(data) {

		},
		authenticate(provider, options) {
			return new Ember.RSVP.Promise((resolve, reject) => {
				return this._super(provider, options)
					.then((authResponse) => {
						
					});
			});
		},
		invalidate() {

		}
});
```

**Comment by marcoow** [comment]
Did you install torii (`ember install torii`)?

**Comment by wayne-o** [comment]
Yeah - I will try removing and re-adding. It is the latest though.

**Comment by wayne-o** [comment]
Still same issue I'm afraid

**Comment by wayne-o** [comment]
Anything else I can provide to help with this?

**Comment by marcoow** [comment]
Check in Ember Inspector that the torii service is actually present (`'services:torii'`).

**Comment by abhayathapa** [comment]
@wayne-o  I had hard time figuring out but with `"torii": "Vestorly/torii#0.6.0-beta.7"` in your package.json it works

**Comment by marcoow** [comment]
torii 0.6.0 has actually been released already: https://github.com/Vestorly/torii/releases/tag/0.6.0 No need to use the beta anymore.

**Comment by wayne-o** [comment]
Yeah already on 0.6.1...

here is before I click the login (facebook) button:

<img width="1440" alt="screen shot 2015-11-11 at 14 00 09" src="https://cloud.githubusercontent.com/assets/178060/11092624/abb4a6da-887c-11e5-84ed-ee93b038f8d8.png">

And after clicking:

<img width="1440" alt="screen shot 2015-11-11 at 14 00 40" src="https://cloud.githubusercontent.com/assets/178060/11092629/b21f6e7e-887c-11e5-8d9f-91eee4b12776.png">

**Comment by wayne-o** [comment]
Any clues on this one?

**Comment by wayne-o** [comment]
Anyone?

**Comment by wayne-o** [comment]
Is there a slack channel or anything for ESA?

**Comment by marcoow** [comment]
There's an `ember-simple-auth` tag on stackoverflow - usually questions with that tag are answered pretty quickly. There is no slack room for ESA yet - maybe you can get someone to create one in the Ember.js Community Slack, I'd appreciate that.

**Comment by wayne-o** [comment]
Sorted! 

I figured this one out - I still had my torii instance initializer... oops :p

**Comment by marcoow** [comment]
👍
