### ISSUE TITLE
Transitioning to route that was requested by the user after login

### ISSUE THREAD

**Issue by faeronsayn** [simplabs/ember-simple-auth#777]
So I'm not sure if this is currently possible with some configuration of the plugin, but I was wondering if we can somehow store the user's requested route before we redirect them to the `login` route, and after success fully authenticating to redirect them to the route that they requested. 

Currently, there is a configuration option to redirect them to a static route after authentication like the index page, is there a configuration to do what I've described above?

If not, could someone point me in the right direction and if there are code examples, that would also be much appreciated :)

**Comment by marcoow** [comment]
What you're describing is already supported out of the box when you use the [`AuthenticatedRouteMixin`](http://ember-simple-auth.com/api/classes/AuthenticatedRouteMixin.html) as well as the [`ApplicationRouteMixin`](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html).

**Comment by faeronsayn** [comment]
Great, thanks!
