### ISSUE TITLE
Catching Server Down Event on Authenticate (CORS preflight failure)

### ISSUE THREAD

**Issue by angelosarto** [simplabs/ember-simple-auth#778]
When calling the authenticate method and the backend is down the authenticate method fails since the preflight OPTIONS request is not successful.  

~~This error does not seem to pass back through to authenticate e.g. in the controller this code will NOT catch the event.~~
In this case the `reason` is empty.

    this.get('session').authenticate(authenticator, credentials).catch((reason) => {

Is this the responsibility of the authenticator to not catch this and throw it to the user level, or is there some other way I can hook this event?

**Comment by marcoow** [comment]
Which authenticator are you using?

**Comment by angelosarto** [comment]
https://github.com/jpadilla/ember-cli-simple-auth-token

Should I close and open it there?

**Comment by marcoow** [comment]
If you're using ember-cli-simple-auth-token - yes, please do so.
