### ISSUE TITLE
Encapsulating session data

### ISSUE THREAD

**Issue by Fryie** [simplabs/ember-simple-auth#779]
With the upgrade to 1.0 I've had to change a lot of instances of ```session.currentUser``` to ```session.data.currentUser```. While also being somewhat more cumbersome to type, I worry about proper encapsulation, especially if internals are going to change again at some point. It is, in any case, a violation of Demeter's Law.

I would like to ask if it would make sense to expose the data stored in the service by a more clearly defined interface.
This could be a getter / setter pair for "normal" data in the session (one could follow the jQuery convention here, using a ```data``` method with one or two arguments, or use ```setData```/ ```getData```) and an additional getter for the read-only data in ```session.data.authenticated```.

I think the current implementation leaks too much information about the session service to collaborators which has implications e.g. for mocking.

**Comment by marcoow** [comment]
`session.data` as well as `session.data.authenticated` are not internals but public API that's guaranteed not to change (at least not until the next major release) as ESA follows SemVer.

I don't really see a need to change anything there.

**Comment by Fryie** [comment]
Right, my point is that I generally dislike reaching deep into the structure of an object as it both increases coupling and makes setting up mocks more involved. E.g. a session mock would have to look something like this:
```
var session = Ember.Object.create({
  data: { authenticated: {} }
});
```

That said, it was only a design suggestion, so I'll be happy to close the issue if you see no advantage to this approach.
For what's it worth, it's always possible - and maybe even sensible - never to use the ```session``` directly in the application but to encapsulate everything related to authentication in a service.
