### ISSUE TITLE
Re-add support/build scripts for globalized and bower distributions

### ISSUE THREAD

**Issue by mhesler** [simplabs/ember-simple-auth#780]
We are not using Ember CLI for our Ember projects making it difficult to integrate.

**Comment by marcoow** [comment]
You'd have to try and create a globalized or AMDfied build yourself. Providing these builds caused huge overhead in ESA and as only very few people are not using Ember CLI these days it doesn't seem worth it really. Also you need to update at some point anyway so I really think it's better for projects to upgrade to Ember CLI which is the future anyway than for ESA to keep supporting deprecated way of building Ember apps.

**Comment by mhesler** [comment]
We use a different build system that works with our technology stack.  Incorporating Ember CLI at this point isn't an option.  This decision has left me with two options: fork it or remove ember-simple-auth and replace it.
You've put together a good extension for simply dealing with authentication, but this decision is limiting your audience and adoption.
