### ISSUE TITLE
Uncaught Error with ember-simple-auth and ember-cli-simple-auth-token

### ISSUE THREAD

**Issue by celicoo** [simplabs/ember-simple-auth#781]
I'm trying for the first time use ember-cli-simple-auth-token with ember-simple-auth and i'm missing some configuration i think, cause the following message keeps showing in my terminal:

Could not find module `simple-auth/authenticators/base` imported from `simple-auth-token/authenticators/token`

I'm following this steps:

ember install ember-simple-auth
ember install ember-cli-simple-auth-token
ember generate simple-auth-token

I'm using the following versions:

ember-cli-simple-auth-token: ^0.7.3
ember-simple-auth: 1.0.1

And that's all my dependencies:

broccoli-asset-rev
ember-breadcrumbs
ember-cli
ember-cli-app-version
ember-cli-babel
ember-cli-content-security-policy
ember-cli-cors
ember-cli-dependency-checker
ember-cli-htmlbars
ember-cli-htmlbars-inline-precompile
ember-cli-ic-ajax
ember-cli-inject-live-reload
ember-cli-moment-shim
ember-cli-qunit
ember-cli-release
ember-cli-sass
ember-cli-simple-auth-token
ember-cli-sri
ember-cli-uglify
ember-data
ember-disable-proxy-controllers
ember-export-application-global
ember-moment
ember-new-computed
ember-simple-auth

Thanks in advance.

**Comment by marcoow** [comment]
I think ember-cli-simple-auth-token doesn't work with Ember Simple Auth 1.0 yet. Please open an issue on their repo.
