### ISSUE TITLE
doorkeeper expects Authorization header on token revocation

### ISSUE THREAD

**Issue by jpaas** [simplabs/ember-simple-auth#785]
I'm using ember-simple-auth with doorkeeper and I discovered that none of my tokens are being revoked upon signout. Rightly or wrongly (I'm not sure), Doorkeeper looks up the token based on the Authorization header before processing the revoke request. If it does not find a token, it simply performs a no-op and returns 200. Ref https://github.com/doorkeeper-gem/doorkeeper/blob/4313541e4d806cd8e5cad20d4ca4444171c113d2/app/controllers/doorkeeper/tokens_controller.rb#L15

It seems that ember-simple-auth is not setting the Authorization header when sending the revoke request which is why the token does not get revoked. Would it be possible to have the Authorization header set on the revoke request?

**Comment by marcoow** [comment]
I think the `Authorization` header does actually not have to be passed for token revocation requests as per the spec. You could easily extend the authenticator though and customize the revocation method to include the header.

**Comment by marcoow** [comment]
What doorkeeper does there is it validates the client credentials. That is not the user's bearer token. When you specify a client ID for the OAuth 2.0 authenticator (http://ember-simple-auth.com/api/classes/OAuth2PasswordGrantAuthenticator.html#property_clientId) it will include that in all requests it makes to the authorization server. Client secret is not supported by Ember Simple Auth for obvious reasons - I'm not sure whether doorkeeper might require it though.

**Comment by jpaas** [comment]
@marcoow: Thanks for looking into this. So you're saying its not skipping the token revocation because of the missing bearer token? If that's true, I'm not quite sure why my tokens are not being revoked, or what I have to do to ensure they are.

**Comment by marcoow** [comment]
Do you specify the clientId correctly on the OAuth 2.0 authenticator? It should be whatever doorkeeper expects. Also make sure doorkeeper works with an empty client secret as you cannot include that in requests sent from the Ember app.

**Comment by jpaas** [comment]
I was not specifying the clientId on my OAuth2PasswordGrantAuthenticator. I added it, but it doesn't seem to do anything from a doorkeeper pov. I did debug the doorkeeper behavior on /oauth/revoke a bit further using curl and it definitely requires the Bearer token. This is actually documented here https://github.com/doorkeeper-gem/doorkeeper/wiki/API-endpoint-descriptions-and-examples#post-oauthrevoke. So you're saying that in order to send the bearer token, I need to extend the OAuth2PasswordGrantAuthenticator? Is it the makeRequest method I need to override?

**Comment by marcoow** [comment]
ESA implements the "Form Encoded Body Parameter" way of revoking a token: https://tools.ietf.org/html/rfc6750#section-2.2. If doorkeeper expects sth. else you need to override the `invalidate` method of the OAuth2PasswordGrantAuthenticator.
