### ISSUE TITLE
getter/setter for session.data.authenticated

### ISSUE THREAD

**Issue by pmkhoa** [simplabs/ember-simple-auth#789]
On my application, I created a service to keep track of current user by storing data in the session.data.authenticated. I wonder if it's possible to user setter and getter to modify the data inside session.data or not. Here is an example of it:

    currentUser: Ember.computed('session.data.authenticated', function() {
       const currentUser = this.get('session.data.authenticated');
        if (!Ember.isEmpty(currentUser)) {
            return currentUser;
        }
    }),
  
    updateCurrentUserFirstName(firstName) {
         if (!Ember.isEmpty(this.currentUser)) {
             this.set('session.data.authenticated.firstName', firstName);
         }
     },

Currently, the session data is being modified properly, but when I reload the browser, it goes back to its original state. Any suggestions?

**Comment by marcoow** [comment]
You should never modify the authenticated session data manually as that's all maintained by the session and the authenticator. That's most likely also why it gets reset on reload. Actually writing to the authenticated session data should trigger an exception but apparently that's not currently working as intended.

**Comment by pmkhoa** [comment]
So basically authenticated session data is for read-only. The only time when these data being written is when user authenticates?

**Comment by marcoow** [comment]
Yes, authenticated session data is read only and maintained by the internal session and the authenticator (not only when the session is authenticated, also when it is restored or authenticated from another tab or window).

**Comment by pmkhoa** [comment]
That sounds good. Thanks for your response! :+1:

**Comment by TangMonk** [comment]
@marcoow 
But where to store currentUser object?
