### ISSUE TITLE
How to inject currentUser to all controllers and routes?

### ISSUE THREAD

**Issue by TangMonk** [simplabs/ember-simple-auth#794]
There are almost old post and answers on the google.

That's my solution, I save the user info into localStorage, and retrieve from service.

initializers/current-user.js 

``` javascript
export function initialize( container, application ) {
  var currentUser =Ember.Object.create(JSON.parse(localStorage.getItem('ember_simple_auth:session')).authenticated.currentUser)
  application.register('currentUser:main', currentUser, {instantiate: false})
  application.inject('route', 'currentUser', 'currentUser:main');
  application.inject('controller', 'currentUser', 'currentUser:main');
}

export default {
  name: 'current-user',
  initialize: initialize
};

```

is is the perfect way?

**Comment by anilmaurya** [comment]
@TangMonk you don't have to retrieve user from `localStorage`, `ember-simple-auth` will do this for you.

If you look at dummy app https://github.com/simplabs/ember-simple-auth/tree/master/tests/dummy , you will see that you can write service(https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/services/session-account.js) and inject it (https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/components/main-navigation.js#L7) whenever required.

**Comment by marcoow** [comment]
I guess @anilmaurya answered this
