### ISSUE TITLE
Redirect if signed in

### ISSUE THREAD

**Issue by orgertot** [simplabs/ember-simple-auth#797]
Hi,
I want to check if the user is authenticated in my index template. 
If yes redirect to some other template. transitionToRoute would be the key i think! Sorry I´m new..

Thank you very much for making ember!

**Comment by anilmaurya** [comment]
@orgertot In your `app/routes/application.js`

```
session: Ember.inject.service(),

beforeModel: function(transition){  
    if(transition.targetName === 'index'){
      if(this.get('session').get('isAuthenticated')){
        this.transitionTo('home');  // Transition to 'home' page from index page
      }
    }
  }
```

**Comment by orgertot** [comment]
Wow that was pretty easy :+1:
