### ISSUE TITLE
How to inject token in ajax request

### ISSUE THREAD

**Issue by orgertot** [simplabs/ember-simple-auth#798]
Hi,
sorry for that (maybe) silly question. Im super new to this topic :shipit: 

I created a custom authorizer:
```javascript
import Ember from 'ember';
import Base from 'ember-simple-auth/authorizers/base';
export default Base.extend({
    authorize: function(jqXHR, requestOptions) {
        var accessToken = this.get('session.content.secure.token');
        if (this.get('session.isAuthenticated') && !Ember.isEmpty(accessToken)) {
            jqXHR.setRequestHeader('Authorization', 'Bearer ' + accessToken);
        }
    }
});
```
And now i want to include the token in a ajax request in my controller (this is my code without the token send):
```javascript
// app/controllers/workouts.js
import Ember from 'ember';
import config from '../config/environment';

export default Ember.Controller.extend({
  requestEndpoint: config.ServerIp+'/workouts',
  workouts: function() {
	    Ember.$.ajax({
	        type: "GET",
	        url: requestEndpoint
	    }).success(function(data) {
	    	return data;
	    })
  }.property()
});
```

Thank you very much for helping and understanding this great module! :+1:

**Comment by marcoow** [comment]
You use the [session service's `authorize`](http://ember-simple-auth.com/api/classes/SessionService.html#method_authorize) method to authorize arbitrary code blocks, e.g.:

```js
// app/controllers/workouts.js
import Ember from 'ember';
import config from '../config/environment';

export default Ember.Controller.extend({
  session: Ember.inject.service(),
  requestEndpoint: config.ServerIp+'/workouts',
  workouts: function() {
      this.get('session').authorize('authorizer:oauth2-bearer', (headerName, headerValue) => {
        // inject header here
        Ember.$.ajax({
            type: "GET",
            url: requestEndpoint
        }).success(function(data) {
            return data;
        });
      });
  }.property()
});
```

**Comment by orgertot** [comment]
Thanks. But now is the session.content.secure.token undefined. I dont know why.. Maybe you have a tip for me?

```javascript
// authorizers/custom.js
import Ember from 'ember';
import Base from 'ember-simple-auth/authorizers/base';
export default Base.extend({
	session: Ember.inject.service(),
    authorize: function(jqXHR, requestOptions) {
    	console.log(Object.keys(this.get('session')));
        var accessToken = this.get('session.content.secure.token');
        if (this.get('session.isAuthenticated') && !Ember.isEmpty(accessToken)) {
            jqXHR.setRequestHeader('Authorization', 'Bearer ' + accessToken);
        }
    }
});
```

```javascript
// authenticators/custom.js
...
    authenticate: function(options) {
        return new Ember.RSVP.Promise((resolve, reject) => {
            Ember.$.ajax({
                type: 'POST',
                url: this.tokenEndpoint,
                data: JSON.stringify({
                    email: options.identification,
                    password: options.password
                }),
                contentType: 'application/json;charset=utf-8',
                dataType: 'json'
            }).then(function(response) {
                Ember.run(function() {
                    resolve({
                        token: response.token
                    });
                });
            }, function(xhr, status, error) {
                var response = xhr.responseText;
                Ember.run(function() {
                    reject(response);
                });
            });
        });
    },
...
```

**Comment by marcoow** [comment]
`session.content.secure` was changed to `session.data.authenticated` in 1.0 so you'll want to get `session.data.authenticated.token` now.

**Comment by orgertot** [comment]
Ah okay! The development is so fast, that there are just a few tutorials up to date.
I now have the error:
```javascript
Uncaught TypeError: jqXHR.setRequestHeader is not a function
```

I dont understand exactly how this jqXHR is filled, anyway....

Danke fürs schnelle Helfen!

**Comment by marcoow** [comment]
The above was really just example code - not sure how you can set request headers in your case but the point is that `headerName` and `headerValue` contain the data you need.

**Comment by orgertot** [comment]
Yeah i got that. But the authorizers/custom.js failes at ```Uncaught TypeError: jqXHR.setRequestHeader is not a function```.
So the jqXHR is filled by the module, isnt it?

**Comment by marcoow** [comment]
Ah, I see. The authorizer doesn't get a `jqXHR`, it only gets the session data and a block that it calls with authorization data if the session is authenticated - see the API docs: http://ember-simple-auth.com/api/classes/BaseAuthorizer.html#method_authorize.

**Comment by orgertot** [comment]
Ah okay! I searched a little bit in jquery docs but didnt find a way to have a good alternative to jqXHR.setRequestHeader(), do you? Or do i have to pass the key and value to the controller to insert it there?

**Comment by orgertot** [comment]
I figured it out. Thanks very much! :+1:

**Comment by orgertot** [comment]
new question -> closing that one

**Comment by gte451f** [comment]
@orgertot I have the same problem, the example you listed with jqXHR used to work on older versions of Simple Auth but the params have changed so that the old example no longer works.

You mentioned that you figured it out, what did you do to modify the request header?

**Comment by andorov** [comment]
@gte451f thanks!

**Comment by twisted1919** [comment]
@marcoow - how about when calling `this.store.find...` from a route, is it okay to change the adapter in something like:
```
headers: Ember.computed('session', function() {
        var token = 'Bearer ';
        if (!Ember.isEmpty(this.get('session.data.authenticated.access_token'))) {
            token += this.get('session.data.authenticated.access_token');
        }
        return {
          'Authorization': token,
        };
    })
```
or is there a better way?

**Comment by bmatmentel** [comment]
Thanks @gte451f , saved my day (or my days...).

**Comment by michael-lynch** [comment]
There are lot of tutorials out there with the old `jqXHr` method. I'm glad I found this thread. However, when I invoke the `block()` callback, I get a CORS error:

```
authorize(sessionData, block) {
    if(this.get('session.isAuthenticated')) {
        block('X-Authorization', 'Token: ' + sessionData.token);
    }
}
```

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4500/users. (Reason: CORS preflight channel did not succeed).`

I have `http://localhost:4500/` set in the ENV `crossOriginWhitelist`.

```
ENV['ember-simple-auth'] = {
    authenticationRoute: '/',
    store: 'simple-auth-session-store:local-storage',
    authorizer: 'authorizer:custom',
    crossOriginWhitelist: ['http://localhost:4500/'],
    routeAfterAuthentication: '/dashboard'
};
```
Am I missing something?

**Comment by marcoow** [comment]
This is an issue on your server side that doesn't seem to support CORS. Read more [on how CORS works and how to enable it here](https://www.html5rocks.com/en/tutorials/cors/).

Also be aware that the `crossOriginWhitelist` option doesn't exist anymore (it's not needed anymore as we're no longer auto-authorizing outgoing requests.)
