### ISSUE TITLE
Redirect after login does not work

### ISSUE THREAD

**Issue by quaertym** [simplabs/ember-simple-auth#799]
If I remember correctly, `v0.8.0` was redirecting to the previously visited authenticated route after login. This does not work in `v1.0.1`. Do you think this is a bug?

**Comment by orgertot** [comment]
No. In the last version its working. 
Did you set the config right?

**Comment by quaertym** [comment]
@orgertot What is the config for this?
I use this in a project that is more than a year old. It was working previously in `0.8.0` and now it does not.

**Comment by phedinkus** [comment]
I'm having this problem right now. Here's the workflow that's broken:

 - Visit `/sign-in`
 - Enter my credentials
 - Authenticate and redirects to `/contests` 
 - Logout
 - Unauthenticate and redirects to `/sign-in`
 - Repeat log in sequence
 - Authenticate and redirects to `/` <===== Here is where it goes off the rails. Should go to `/contests`

Here's my router: 
```
Router.map(function () {
  this.route('sign-in');
  this.route('sign-out');
  this.route('password-reset', {path: '/users/password/edit'});
  this.route('protected', {path: '/'}, function () {
    this.route('contests', function () {...}
  }
 // more routes
}
```
And in my environment.js I have the following overwriting the auth hooks:
```
  ENV['ember-simple-auth'] = {
    authenticationRoute:         'sign-in',
    routeAfterAuthentication:    'protected.contests',
    routeIfAlreadyAuthenticated: 'protected.contests'
  };
```

**Comment by marcoow** [comment]
I cannot reproduce this. Can you setup a demo project that shows the behavior?

**Comment by gte451f** [comment]
I am having a similar problem.  In my case application-route-mixin:sessonAuthenticated is not being fired.  Perhaps I'm doing something wrong in my custom authenticator?

```javascript
authenticate: function (identification, password) {
    console.log('authenticators:custom:authenticate was called');
    var self = this;
    return new Ember.RSVP.Promise(function (resolve, reject) {
      // make XHR request to api
      self.makeRequest({email: identification, password: password}).then(function (response) {
        // perform some validation to verify that we got a valid response from API
        if ((typeof response.token === 'undefined') || (typeof response.id === 'undefined')) {
          var errorMessage = "<h4>Could not log you into the system: </h4> No valid user found";
          this.get('notify').alert({raw: errorMessage, closeAfter: 10000});
        } else {
          console.log('authenticators:custom:authenticate....resolving');
          Ember.run(null, resolve, response);
        }
      }, function (xhr, status, error) {
        // user local error handling mixin
        self.handleXHR(xhr);
      });
    });
  },
```

**Comment by marcoow** [comment]
@gte451f: you're never rejecting the returned promise in case of errors:

```js
authenticate: function (identification, password) {
    console.log('authenticators:custom:authenticate was called');
    var self = this;
    return new Ember.RSVP.Promise(function (resolve, reject) {
      // make XHR request to api
      self.makeRequest({email: identification, password: password}).then(function (response) {
        // perform some validation to verify that we got a valid response from API
        if ((typeof response.token === 'undefined') || (typeof response.id === 'undefined')) {
          var errorMessage = "<h4>Could not log you into the system: </h4> No valid user found";
          this.get('notify').alert({raw: errorMessage, closeAfter: 10000});
          // <- REJECT HERE!
        } else {
          console.log('authenticators:custom:authenticate....resolving');
          Ember.run(null, resolve, response);
        }
      }, function (xhr, status, error) {
        // user local error handling mixin
        self.handleXHR(xhr);
        // <- REJECT HERE!
      });
    });
  },
```

**Comment by gte451f** [comment]
Ah!  Will try it and let you know if the problem persists.

**Comment by gte451f** [comment]
For what it's worth, I had disabled the application route mixin
```javascript
// app/routes/application.js
...
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
export default Ember.Route.extend(ApplicationRouteMixin, {
...
});
```

**Comment by bthomas14** [comment]
Seeing similar issues to gte451f using torii - authenticationSucceeded is not being triggered after successful login. I am rejecting returned promise in case of errors - any other reasons this would be happening?

here's what my authentication function looks like:
```javascript
authenticateWithFacebook: function() {
      console.log("in authenticateWithFacebook");
      var that = this;

      this.get('session').authenticate('authenticator:torii', 'facebook-connect').then(function(result) {
          console.log("facebook authentication successful!");
          
         // initiate new user sign up flow if new user
          if (that.get('currentUser.is_new_user')) { // new user
            console.log("new user, transitioning to modal");
            that.render('modals/signUp', {
              into: 'application',
              outlet: 'modal',
              controller: 'modals.signUp'
            });
          }
          
          // call fb api to get/update user info
          that.getFbInfo();
        }).catch(function(reason) {
          console.log("facebook authentication failed, " + reason);
          //that.transitionTo('index');
        });
    },
```

And, here is my authenticator:
```javascript
  authenticate() {
    var that = this;
    return new RSVP.Promise((resolve, reject) => {
      this._super(...arguments).then((data) => {
        raw({
          url:      '/auth/facebook/callback?'  + Ember.$.param({ token: data.accessToken }),
          type:     'GET',
          dataType: 'json',
        }).then((response) => {
          console.log("successfully authorized user");
          
         // store user data in currentUser service
          that.get('currentUser').set('is_new_user', response.meta.new);
          that.get('currentUser').setLocation(response.user.zip);

          resolve({
            access_token: response.user.oauth_token,
            provider: data.provider
          });
        }, reject);
      }, reject);
    });
  },
```

**Comment by dennismende** [comment]
The problem of @phedinkus is that after a logout the attemptedTransition property of the session service is not null. It is the baseURL.

Could be the case that window.location.replace in the sessionInvalidate function is not equal to reloading the browser tab manually.

```javascript
sessionInvalidated() {
  if (!Ember.testing) {
    window.location.replace(Configuration.baseURL);
  }
}
```

**Comment by XaserAcheron** [comment]
In case this helps any future Googlers like myself, I ran into a variant of this caused by a simple bit of 'oops'. The short version is that if you define `beforeModel` or `sessionAuthenticated` in your application route, don't forget to call `this._super()`. Fixed it right up for me once I re-added the missing line.

Big thanks to @robguilfoyle over on #541 for setting me on the right track.

**Comment by marcoow** [comment]
I think this is actually not a bug in ESA? Please reopen if I'm missing sth.

**Comment by imsreena7h** [comment]
@XaserAcheron I have used beforeModel in application route(actually in the index.js route)
 could you show me an example code that how to use `this._super() `with `beforeModel`

**Comment by kikollovet** [comment]
I found out a way!!! Hope you all enjoy it a lot!!! Here where I found: https://browntreelabs.com/redirection-in-ember-simple-auth/

to implement it just in the login method that is a promisse put this inside the 
`.then(() =>{ this.get('session.attemptedTransition').retry()});`

Don´t forget that all routes that are just authorized when you are logged in have to have
`export default Route.extend(AuthenticatedRouteMixin,{`
