### ISSUE TITLE
Handlebars dont wait for Ember Ajax

### ISSUE THREAD

**Issue by orgertot** [simplabs/ember-simple-auth#801]
Hey,

My Problem is that the handlebars is not wating for the ajax request to be finished.

My console is like this:
It starts with "starting" from the function in the controller.
Then the {{log workouts}} in the template which is undefined because the ajax is yet not ready.
And at the end the data from the request.

So this is a part of my code of my workouts controller
```javascript
workouts: function() {
  		console.log("starting");

		this.get('session').authorize('authorizer:custom', (headerName, headerValue) => {
		    var obj = {};
		    obj[headerName] = headerValue;

			Ember.$.ajax({
		        type: "GET",
		        url: this.requestEndpoint,
		        headers: obj,
		    }).success(function(data) {
		    	console.log("ajax: "+JSON.stringify(data));
		        return data;
		    }).error(function(error) {
		    	return error;
		    });
		});	
  }.property()
```

And the Handlebars Template is like this:
```
{{log workouts}}
```
How do I solve this?
Maybe:
Is there a way to transform this code into a promise? Or is there a "wait for ember" option?

**Comment by marcoow** [comment]
Please post this on stackoverflow as it doesn't actually relate to ESA - also much more likely that you'll get help there as more people are going to see it.

**Comment by orgertot** [comment]
OKay! Im sorry! http://stackoverflow.com/questions/33938601/handlebars-dont-wait-for-ember-ajax
