### ISSUE TITLE
Test Redirect after invalidateSession

### ISSUE THREAD

**Issue by gte451f** [simplabs/ember-simple-auth#803]
I'm having some trouble testing a login then logout behavior. Is special handling required to force simple-auth to redirect in a test?  Or maybe the problem is that the failing assert occurs before the redirect as occured?

```javascript
test('protected route CAN be visited when session is authenticated', function (assert) {
  var self = this;
  authenticateSession(this.application, {
    "id": "103",
    "userName": "demo"
  });
  //a protected route
  visit('/dash');

  andThen(function () {
    assert.equal(currentURL(), '/dash');   // << pass
    invalidateSession(self.application);   //   << redirect now??
    visit('/dash');  // try to force redirect...doesn't seem to make a difference
    andThen(function () {
      assert.equal(currentURL(), '/auth/login');  // << fails...still on previous route.../dash
    });
  });
});
```

**Comment by luismendozamx** [comment]
@gte451f It is probably caused due to not using the async test helpers correctly. Both `andThen` and `visit`are async helpers. You shouldn't have to nest them, they are meant to replace the chaining of unresolved promises.

You should try this:

```js
test('protected route CAN be visited when session is authenticated', function (assert) {
  var self = this;

  authenticateSession(this.application, {
    "id": "103",
    "userName": "demo"
  });

  //a protected route
  visit('/dash');

  andThen(function () {
    assert.equal(currentURL(), '/dash');
  });

  invalidateSession(self.application); 

  visit('/dash');

  andThen(function () {
    assert.equal(currentURL(), '/auth/login');  // << fails...still on previous route.../dash
  });
});
```

Regarding the redirects, I'm not sure how that is handled by simple-auth in the testing environment.

**Comment by marcoow** [comment]
By default Ember Simple Auth will actually reload the baseUrl of your application, thus restarting the app and clearing out all (potentially sensitive) in memory data. Of course you don't want that to happen in testing as it would restart the test suite each time so ESA simply does nothing on session invalidation in test mode.
