### ISSUE TITLE
ESA Torii wrapper doesn't pass session data to Torii close.

### ISSUE THREAD

**Issue by kevintechie** [simplabs/ember-simple-auth#807]
Because some api's require deleting access tokens on logout, the Torii close() wrapper needs to pass the provider name and session data similar to how fetch() is wrapped.

Working fetch() code: https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/torii.js#L54
Problematic close() code: https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/torii.js#L106

close() may not return a response body, so you probably need to add:
```
data = data || {};
```
before calling `this._resolveWith();`

**Comment by marcoow** [comment]
PR adding this would be great!

**Comment by kevintechie** [comment]
Pull request added.https://github.com/simplabs/ember-simple-auth/pull/808

**Comment by marcoow** [comment]
This is fixed actually
