### ISSUE TITLE
Inject session service globally

### ISSUE THREAD

**Issue by teckays** [simplabs/ember-simple-auth#809]
As the guides say, I have to inject `session: Ember.service.inject()` the session service in every route, controller or component I wish to access the `session` data from. However, It becomes a little redundant injecting the session service everywhere. Is it possible to inject it globally so that it's accessible everywhere in the app modules and components? I've tried using Ember initializers and didn't have much success just yet.

**Comment by jcope2013** [comment]
if your on ember 2.1

``` 
instance-initializers/session-injection.js

import Ember from 'ember';

export default {
  name: "session-injection",
  after: 'ember-simple-auth',

  initialize(appInstance) {
    appInstance.inject('route', 'session', 'service:session');
    appInstance.inject('controller', 'session', 'service:session');
    appInstance.inject('component', 'session', 'service:session');
  }
} ```

if your on ember 2.0

change ``` appInstance.inject ``` to ``` appInstance.registry.injection ```

**Comment by teckays** [comment]
@jcope2013 thank you, it worked. I tried using `initializers` instead of `instance-initializers`.
