### ISSUE TITLE
The authenticator "authenticator:devise" rejected to restore the session - invalidating…

### ISSUE THREAD

**Issue by abhayathapa** [simplabs/ember-simple-auth#810]
I have both torii and devise implemented on a project.And using default session store ie Adaptive. When i refresh page session persists with Facebook login, it works fine . But with devise login, once i refresh the page, it logs out with `The authenticator "authenticator:devise" rejected to restore the session - invalidating…` 

My devise authenticator is 
```
import DeviseAuthenticator from 'ember-simple-auth/authenticators/devise';
export default DeviseAuthenticator.extend();
```

**Comment by marcoow** [comment]
What does the session data in `localStorage` look like before the reload?

**Comment by abhayathapa** [comment]
`ember_simple_auth:session - {"authenticated":{"authenticator":"authenticator:devise","access_token":"e589V-96nj3x6s4_3A12","user_id":19}}`

**Comment by marcoow** [comment]
The Devise authenticator uses `token` and `email` for the token and identification attributes [by default](http://ember-simple-auth.com/api/classes/DeviseAuthenticator.html#property_identificationAttributeName). If your sever responds with `access_token` and `user_id` you need to override these attributes.

**Comment by abhayathapa** [comment]
Thanks @marcoow it worked

**Comment by iodum** [comment]
@marcoow I have same problem. I tried to set params to my devise authenticator like this:
```
import DeviseAuthenticator from 'ember-simple-auth/authenticators/devise';
export default DeviseAuthenticator.extend({
    tokenAttributeName: 'token',
    identificationAttributeName: 'email',
});
```

But data don't change at localStorage
```
ember_simple_auth:session: "{"authenticated":{"authenticator":"authenticator:devise","user_token":"FwE-raRDeLUyYNP5UYvH","user_email":"test@test.com"}}"
```
