### ISSUE TITLE
Session account service is lost on page reload

### ISSUE THREAD

**Issue by abhayathapa** [simplabs/ember-simple-auth#811]
This is my services/session-user.js
```
import Ember from 'ember';
import DS from 'ember-data';

const { service } = Ember.inject;

export default Ember.Service.extend({
  session: service('session'),
  store: service(),
  user: Ember.computed('session.data.authenticated.user_id', function() {
    const userId = this.get('session.data.authenticated.user_id');
    if (!Ember.isEmpty(userId)) {
      return DS.PromiseObject.create({
        promise: this.get('store').find('user', userId)
      });
    }
  })
});
```
Before reload, both `sessionUser.user` and `session.isAuthenticated` works
Whenever page is reloaded with torii authenticator, the `session.isAuthenticated` is working but `sessionUser.user` seems to get lost.

**Comment by marcoow** [comment]
What does the session data in `localStorage` look like before the reload?

**Comment by abhayathapa** [comment]
I only have this in localStorage `ember_simple_auth:session - {"authenticated":{"authenticator":"authenticator:torii","access_token":"CAAPtthUIkrIBABScmKzqg77rPkZCEZAZASBOEZCKmomiNSuHiJY2VEXlX2k5lzPzPT47xm6sd47EMIXlFBSIch8LRYZAofdKz2oPZCFZBFrB05KMFbpy2aaLCmeAgG3wazU2FIpIrAQCZAC849tKiMTtqPlIh2SXjYYOK7B20aNY6HJHDrYYW78ZAgfOWEj6fdOYAB","provider":"facebook-oauth2","user_id":45}}` 

Looks like sessionUser is not stored in localStorage.After reload it is just
`{"authenticated":{"authenticator":"authenticator:torii","provider":"facebook-oauth2"}}`

**Comment by ivaylopivanov** [comment]
+1

**Comment by marcoow** [comment]
Did you override the torii provider's `fetch` method so that it returns the passed data [as shown in the docs](http://ember-simple-auth.com/api/classes/ToriiAuthenticator.html#method_restore)?

**Comment by abhayathapa** [comment]
I have `providers/facebook.js` as shown in docs. But after page reload,  I only have this in local storage `{"authenticated":{"authenticator":"authenticator:torii","provider":"facebook-oauth2"}}` , looking at server side, I dont get token either. My authenticator/torii.js is
```
import Ember from 'ember';
import Torii from 'ember-simple-auth/authenticators/torii';
import raw from 'ic-ajax';

const { RSVP } = Ember;
const { service } = Ember.inject;

export default Torii.extend({
  torii: service('torii'),

  authenticate() {
    return new RSVP.Promise((resolve, reject) => {
      this._super(...arguments).then((data) => {
        raw({
          url:      'api/users',
          type:     'POST',
          dataType: 'json',
          data:     { 'grant_type': 'facebook_auth_code', 'auth_code': data.authorizationCode }
        }).then((response) => {
          resolve({
            // jscs:disable requireCamelCaseOrUpperCaseIdentifiers
            token: response.token,
            provider: data.provider,
            user_id: response.user_id
          });
        }, reject);
      }, reject);
    });
  }
});
```
And i authenticate in login.js as `this.get('session').authenticate('authenticator:torii', 'facebook-oauth2')`

**Comment by marcoow** [comment]
The torii provider has to be in `torii-providers/facebook.js`, not `providers/facebook.js`. Also you're not actually using that anyway when you're calling `this.get('session').authenticate('authenticator:torii', 'facebook-oauth2')`. That would have to be `this.get('session').authenticate('authenticator:torii', 'facebook')` instead.

**Comment by abhayathapa** [comment]
I had `torii-providers/facebook.js` but changed to providers/facebook.js after seeing the doc  mentioned above. After using `this.get('session').authenticate('authenticator:torii', 'facebook')` it worked. Thanks. 

One last problem, as Im using both devise and torii, my devise sends header properly to server with my `authorizers/application.js` as
```
import DeviseAuthorizer from 'ember-simple-auth/authorizers/devise';
export default DeviseAuthorizer.extend();
```
And `adapters/application.js` as
```
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
export default DS.RESTAdapter.extend(DataAdapterMixin, {
  namespace: 'api',
  authorizer: 'authorizer:application' 
});
```

How do i set header from frontend to server with torii as well as im using both. Thanks in advance

**Comment by marcoow** [comment]
I fixed the path in the docs: aff0330. Thanks for finding that.

Regarding the authorization question: please post that on stackoverflow or open another issues if you feel sth. is wrong with ESA itself.

**Comment by GabKlein** [comment]
@abhayathapa I have the same exact behavior. 
I'm using `this.get('session').authenticate('authenticator:torii', 'facebook')` and my authorizer receives: 
```
{"authenticator":"authenticator:torii","provider":"facebook"}
```

with `torii-providers/facebook.js`
```
import Oauth1Provider from 'torii/providers/oauth1';
export default Oauth1Provider.extend({
  name: 'facebook',
  open: function(options){
    var name = this.get('name'),
        url  = this.buildRequestTokenUrl();

    return this.get('popup').open(url, ['token', 'email'], options).then(function(authData) {
      authData.provider = name;
      return authData;
    });
  }
});
```
with `authorizers/application.js`
```
import DeviseAuthorizer from 'ember-simple-auth/authorizers/devise';
export default DeviseAuthorizer.extend();
```
with `authenticators/torii.js`
```
import Ember from 'ember';
import ToriiAuthenticator from 'ember-simple-auth/authenticators/torii';
export default ToriiAuthenticator.extend({
  torii: Ember.inject.service()
});
```

I cannot figure out where `{"authenticator":"authenticator:torii","provider":"facebook"}` comes from since `torii-providers/facebook` returns {token: "...", email: "..."}

**Comment by marcoow** [comment]
@GabKlein: you need to implement `fetch` in your torii provider so that it returns a promise that resolves with the session data it gets passed as the only argument (and which it might modify before resolving with it).

**Comment by GabKlein** [comment]
Thank you very much @marcoow it works :+1: Thanks for rocking!

**Comment by marcoow** [comment]
always happy to help 👍🏻
