### ISSUE TITLE
Session data undefined when injecting session service in a another service

### ISSUE THREAD

**Issue by jpoiri** [simplabs/ember-simple-auth#814]
Hi,

I am building a service that when its initialized it retrieves the locale from the session however the locale is always undefined at this point since the session data is seem to be empty but when I retrieve the locale from session in the application route the locale is there. Is there a function that needs to called in order to get session data in a service?

Service:

    export default Ember.Service.extend({

	session: Ember.inject.service('session'),

	init() {
		this.get('log').debug('Initializing mx-i18n service...');
		Ember.debug('Authenticated: ' + this.get('session.isAuthenticated'));
		Ember.debug('Service session Locale: ' + this.get('session.data.locale'));
	},

Application Route:

    import Ember from 'ember';
    import moment from 'moment';
    import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

    export default Ember.Route.extend(ApplicationRouteMixin, {

	  beforeModel(transition) {
		  Ember.debug('Application route session locale: ' + this.get('session.data.locale'));
	  },

Console logs:

    DEBUG: -------------------------------
    ember.debug.js:5938DEBUG: Ember             : 2.2.0
    ember.debug.js:5938DEBUG: Ember Data        : 2.2.0
    ember.debug.js:5938DEBUG: jQuery            : 2.1.4
    ember.debug.js:5938DEBUG: Ember Simple Auth : 1.0.0
    ember.debug.js:5938DEBUG: -------------------------------
    ember.debug.js:5938DEBUG: Initializing mx-i18n service...
    ember.debug.js:5938DEBUG: Authenticated: false
    ember.debug.js:5938DEBUG: Service session Locale: undefined
    ember.debug.js:51902Attempting URL transition to /
    ember.debug.js:51899Transition #0: application: calling beforeModel hook
    ember.debug.js:5938DEBUG: Application route session locale: en

**Comment by jpoiri** [comment]
This only way I managed to make it work but I am not sure if this the correct way to do this

	init() {
		this.get('log').debug('Initializing mx-i18n service...');
		let data = this.get('session.store').restore();
		Ember.debug('Restore locale: ' + data.locale);
    }

**Comment by marcoow** [comment]
The application route's `beforeModel` method runs after the session is restored. I assume your service's `init` method runs earlier. You'd have to make sure you're not initing your service until after the application route's `beforeModel` has run or initialize the service explicitly from that method, e.g.

```js
import Ember from 'ember';
import moment from 'moment';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  yourService: Ember.inject.service(),

  beforeModel(transition) {
    yourService.setup().
  }

});
```

**Comment by jpoiri** [comment]
Ok so there is no way to restore the session before the application route?

**Comment by marcoow** [comment]
The session will always be fully restored before your application route's `beforeModel` method runs.

**Comment by jpoiri** [comment]
ok thanks
