### ISSUE TITLE
use of const breaks Safari

### ISSUE THREAD

**Issue by jspavlick** [simplabs/ember-simple-auth#819]
I just upgraded from 0.7.3 to 1.0.1, and was troubled to find that support for Safari and Mobile Safari has been dropped. 

```SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.``` 

Happens inside

```
define('my-app/initializers/ember-simple-auth', ['exports', 'ember', 'my-app/config/environment', 'ember-simple-auth/configuration', 'ember-simple-auth/initializers/setup-session', 'ember-simple-auth/initializers/setup-session-service'], function (exports, Ember, ENV, Configuration, setupSession, setupSessionService) {

    'use strict';

    exports['default'] = {
        name: "ember-simple-auth",
        initialize: function(registry) {
            const config = ENV['default']["ember-simple-auth"] || {};
            config.baseURL = ENV['default'].baseURL;
            Configuration['default'].load(config);

            setupSession['default'](registry);
            setupSessionService['default'](registry);
        }
    };

});
```

and

```
define('my-app/tests/helpers/ember-simple-auth', ['exports', 'ember-simple-auth/authenticators/test'], function (exports, Test) {
...omitted for brevity...
});
```

(Shame on you, Apple) 

While this is not Ember Simple Auth's fault per-say, it is still troubling. 

Is there a known workaround other than manually editing `const` to `var` before deploying to production? Perhaps some sort of Ember CLI pre-processor that converts ES6 to ES5?

Perhaps I am using too old a version of Ember CLI? I am using 1.13.1 (Yes, shame on me)

**Comment by marcoow** [comment]
Ember CLI processes all code with Babel which should transpile `const` to `var`. If that doesn't happen for these 2 modules that would seem to be an Ember CLI issue really. Do you see any other occurences in compiled code?

**Comment by jspavlick** [comment]
No, I do not see `const` anywhere else in the compiled code. I upgraded from Ember CLI 1.13.1 to 1.13.5 (bit of a pain, but got it running) and it works now. 

So yes, this does seem to be an Ember CLI issue. Sorry about that! However, 1.13.1 is pretty old, so I doubt filing a bug for it would be very helpful. 

I'm going to close the issue now. Thanks!
