### ISSUE TITLE
Documentation Request - oauth2 serverTokenEndpoint configuration

### ISSUE THREAD

**Issue by temecom** [simplabs/ember-simple-auth#826]
I see that you have answered this question numerous times and there are a lot of misleading examples out there from the earlier ember-cli-simple-auth. I spent several hours trying to get this to work. Soooo. 
May I suggest that you put it in the documentation for the authenticator? 

To change the properties like the URL to the authentication server add them in the constructor eg: 
 
```js
// app/authenticators/oauth2.js
import OAuth2PasswordGrant from 'ember-simple-auth/authenticators/oauth2-password-grant';

export default OAuth2PasswordGrant.extend({
  serverTokenEndpoint: 'http://localhost:3000/token'
});
```

**Comment by marcoow** [comment]
Which part did you have problems with? Having to extend the authenticator and override the property or finding out which property you'd want to override? The properties are actually all documented in the API docs: http://ember-simple-auth.com/api/classes/OAuth2PasswordGrantAuthenticator.html#property_serverTokenEndpoint.

Configuring things by extending base classes and overriding properties is pretty common I think - think of e.g. Ember Data adapters.

**Comment by temecom** [comment]
Yes pretty common but not obvious to anyone trying to use it. The older examples that come up in a search are misleading as well... no fault of yours but it would avoid confusion if it was front and center in your documentation.

Eg: 
https://github.com/jpadilla/ember-cli-simple-auth-token
http://stackoverflow.com/questions/26239481/change-server-token-end-point-for-ember-simple-auth-devise-add-on

**Comment by seymores** [comment]
I agree with @temecom as I have spent hours trying to find out the proper way to configure the OAuth2PasswordGrantAuthenticator's serverTokenEndpoint property.
This does not work as I thought it would work the same way from the readme's configuration section.

    ENV['ember-simple-auth'] = {
      serverTokenEndpoint: 'http://localhost:8080/xxxtoken'
    }

**Comment by nahtnam** [comment]
:+1: I had to make an issue to figure this one out! #731
