### ISSUE TITLE
Custom authorizer not setting xhr.setRequestHeader

### ISSUE THREAD

**Issue by svparijs** [simplabs/ember-simple-auth#828]
I've been trying to figure out why my authorizer while authenticated won't just set the xhr.setRequestHeader token. 

It might be related to http://stackoverflow.com/questions/31967655/simple-auth-token-jwt-authorization-not-setting-authorization-header. In any case its not documented and it would be useful to just work out of the box...

**Comment by marcoow** [comment]
If you're using ESA 1.x, authorizers won't set request headers anymore see [README](https://github.com/simplabs/ember-simple-auth#authorizers).

**Comment by svparijs** [comment]
ESA stands for? I'm currently on Ember 1.13 if that is what you ment?

**Comment by marcoow** [comment]
Ember Simple Auth

**Comment by svparijs** [comment]
Right...

In the docs it says you can adjust the heades with the block function: https://github.com/simplabs/ember-simple-auth#implementing-a-custom-authorizer
Is this correct? Or how should I use this?

Passing my token to the server is not working, I've made a custom authorizer and used the https://github.com/jpadilla/ember-simple-auth-token

**Comment by marcoow** [comment]
> If you're using ESA 1.x

are you?

Custom authorizers don't set header but call a callback with arguments that contain some sort of authorization info that the authorizer gets from the session.

**Comment by svparijs** [comment]
Yes, I'm using "ember-simple-auth": "1.0.1".
Ok so I'm misunderstanding the block function. So how should I proceed to get the correct token loaded in the header?

Because as far as I understand this should just work: https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authorizers/token.js#L86

**Comment by marcoow** [comment]
You do sth. like this

```js
this.get('session').authorize('authorizer:some-authorizer', (headerName, headerValue) => {
  xhr.setRequestHeader(headerName, headerValue);
});
```

You can also use the [`DataAdapterMixin`](http://ember-simple-auth.com/api/classes/DataAdapterMixin.html) if you want a header to be inserted into Ember Data requests.

Also please post questions like this on Stackoverflow.

**Comment by svparijs** [comment]
Ok thanks for the quick feedback.

**Comment by introvert** [comment]
I'm trying to do the same thing (add token to every ajax request that is sent), but these instructions are still unclear to me. With the code above, should I override the authorize function or something else? If someone could share an example, that would be much appreciated..
