### ISSUE TITLE
version in console and ember inspector still 1.0.0

### ISSUE THREAD

**Issue by kellyselden** [simplabs/ember-simple-auth#836]
while `npm ls --depth=0` gives me `├── ember-simple-auth@1.0.1`

I'm not sure why it isn't updating, maybe a bug? Can anyone else repro?

**Comment by notmessenger** [comment]
I have been noticing the same thing in my console as well

`DEBUG: Ember Simple Auth : 1.0.0`

**Comment by notmessenger** [comment]
Seems to already be identified in https://github.com/simplabs/ember-simple-auth/issues/750

**Comment by kellyselden** [comment]
@notmessenger Thanks.
