### ISSUE TITLE
Restore Documentation for Oauth2 not clear enough

### ISSUE THREAD

**Issue by nahtnam** [simplabs/ember-simple-auth#837]
Hey!

I feel as though the docs for restore arent clear enough. Here is what it says right now.

> Restores the session from a session data object; will return a resolving promise when there is a non-empty access_token in the session data and a rejecting promise otherwise.

> If the server issues expiring access tokens and there is an expired access token in the session data along with a refresh token, the authenticator will try to refresh the access token and return a promise that resolves with the new access token if the refresh was successful. If there is no refresh token or the token refresh is not successful, a rejecting promise will be returned.

Here's where I was confused:

> If the server issues expiring access tokens

How do we provide that information? At first I set `expires_at` to a timestamp and that didnt work. After asking on slack, I found out that I had to set `expires_in`. Looking at the source code, im still confused between expires_at and expires_in.

Honestly I feel like the docs should include sample json that is sent/received for each request.

Thanks.

**Comment by remzr7** [comment]
+1

**Comment by marcoow** [comment]
There should also be a link to the RFC which has detailed info on token expiration - PR would be cool
