### ISSUE TITLE
Adding Accept header to Devise Authenticator

### ISSUE THREAD

**Issue by vzelenko** [simplabs/ember-simple-auth#838]
Is there a way to add a custom Accept header to the Devise Authenticator?  My API is expecting something like:  'Accept: application/vnd.test-api.v1', and I am not familiar enough with Ember to override what Devise sets in 'makerRequest(data)' function.

**Comment by marcoow** [comment]
see #835

**Comment by vzelenko** [comment]
Thank you.  I'll close this issue as a dupe.
