### ISSUE TITLE
restore() hook in the base authenticator never gets invoked

### ISSUE THREAD

**Issue by philippmayrth** [simplabs/ember-simple-auth#839]
In my authenticator the restore() hook never gets called not on a page reload and not even if the app is opened in a second tab while already authenticated in a noter one. Im using the Adaptive store with Ember.js 2.2.0 and ember-simple-auth 1.0.1. Does anyone know how to fix this?

Thanks for your help in advance!

```
// authenticators/custom.js
import Base from 'ember-simple-auth/authenticators/base';
import config from '../config/environment';

export default Base.extend({
	
	restore: function(data) {
		alert("restore hook invoked.");
        // Return the appropriate promise... 
	},

	authenticate: function(options) {
		..
	},

	invalidate: function(data) {
  		..
  	}
  
});
```

```
// session-stores/application.js
import Adaptive from 'ember-simple-auth/session-stores/adaptive';

export default Adaptive.extend();
```

**Comment by philippmayrth** [comment]
Does anyone have new information here?

**Comment by marcoow** [comment]
What's the content of the session store (most likely `localStorage`) after you login (before the reload)?

**Comment by philippmayrth** [comment]
Sorry for the delay - took me some time to get the old code in the upgrade branch up and running.

After login before reload as well as after reload it is exactly what I expect:
`{"authenticated":{"authenticator":"authenticator:custom","session":{"expires":"2084-02-17T15:56:04+00:00"}}}`

**Comment by marcoow** [comment]
That does look good actually. you dont't have to define the adaptive store BTW as that's the default.

**Comment by philippmayrth** [comment]
ok, cool. Now what does this mean how do I fix the problem?

**Comment by oswaldoacauan** [comment]
Same problem here.

```
Ember: 2.3.0
Ember Data: 2.3.3
jQuery: 2.1.4
Ember Simple Auth: 1.0.0
```

**Comment by marcoow** [comment]
Any news on this? I just read you're saying above _"After login before reload as well as after reload it is exactly what I expect"_ which would indicate that the authenticator actually restores successfully as the session would get invalidated and cleared otherwise.

**Comment by philippmayrth** [comment]
No, the data in the session is exactly what I expect to be after login. As the restore() hook never gets called this data isn't overridden (would be the same data anyway). So the problem still exists.

**Comment by marcoow** [comment]
If the session is still there after reload then some authenticator is actually restoring it successfully. You might want to place a breakpoint [on this line](https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L53) and check which authenticator actually gets invoked.

**Comment by philippmayrth** [comment]
I´ve set a breakpoint on the authenticate, invalidate and restore functions. Authenticate is the only one thats ever called. I guess the reason that the data in the session is the same as directly after login is due to the fact that it doesn't get deleted by invalidate. Somehow the simple-auth still recognizes the session as invalid at least from the templates.

**Comment by marcoow** [comment]
Can you setup a public repo that illustrates the problem or grant me access to your code?

**Comment by philippmayrth** [comment]
Yes, we can do a TeamViewer session. Ive updated the lib to 1.1.0-beta.3 the session auth seems to work now even on reload. Now the problem is that the login route is displayed for some time and before that the app navigates to the correct route.
If you want to look at the problem with the old version I had I can easily downgrade that.

**Comment by marcoow** [comment]
@philippmayrth: can we do that monday afternoon? Seems like you're in Germany so same time zone as Munich?

Of course access to the repo would be easier but I guess that's not an option?

**Comment by marcoow** [comment]
@philippmayrth: what's the status of this?

**Comment by philippmayrth** [comment]
Can be closed. Thanks for your help.

Mit freundlichen Grüßen
Philipp Mayr

Kreuzberg 10
86672 Thierhaupten
0151 29185883
philipp-mayr.de
