### ISSUE TITLE
Still 1.0.0 version but i'm on 1.0.1.

### ISSUE THREAD

**Issue by ginolon** [simplabs/ember-simple-auth#841]
Why still 1.0.0 version also after I run 

```
ember install ember-simple-auth
```

![esauth](https://cloud.githubusercontent.com/assets/7945858/12081062/e39a97f0-b26e-11e5-808a-24383e3013f1.png)

**Comment by marcoow** [comment]
I forgot to update the version in https://github.com/simplabs/ember-simple-auth/blob/master/vendor/ember-simple-auth/register-version.js when I released 1.0.1 - will be fixed with 1.1.
