### ISSUE TITLE
Feature Request - Configurable Container Names 

### ISSUE THREAD

**Issue by justinaray** [simplabs/ember-simple-auth#843]
I may be missing it, but it seems that there is no way to configure the container names in 1.0.x.  [This commit](https://github.com/simplabs/ember-simple-auth/commit/f2d94a8480aac4d5be5a82ada7dfcefd058e13e3)  added it before in the 0.8.x days.  Is this something we could support going forward?

Willing to fork and PR! ;)

Our app has a session service that predates ESA and I was able to work around this by changing the ESA session container name in 0.8.3.  To make matters worse, this service also has colliding properties, so it seems that allowing configurable container names is the easiest approach.

**Comment by marcoow** [comment]
As the session isn't automatically injected anymore this setting isn't necessary anymore. If the route/controller/component that you want to inject the session into already has a `session` property you can simply inject the service with a different name, e.g.:

```js
sessionService: Ember.inject.service('session')
```

If you already have a `session` service defined in your application you can define the ESA one with another name:

```js
// app/services/auth-session.js
import SessionService from 'ember-simple-auth/services/session';

export default SessionService.extend();
```

**Comment by justinaray** [comment]
Thanks for the response @marcoow.

I did notice that I could change the service name like you mention; however, won't other classes that are hardcoded to `inject.service('session')` fail to find the correct service then?  Ex: application-route-mixin.js?
