### ISSUE TITLE
Authorizer does not go to proper depth when authenticator is specified.

### ISSUE THREAD

**Issue by kylemellander** [simplabs/ember-simple-auth#844]
I was having trouble with the DataAdapterMixin not sending data in the headers.  When I dug down a bit, I discovered that in the authorizer's (I discovered it in the DeviseAuthorizer) authorize() function ended up with data that looked like this:

data = {authentication: "authenticator:devise", user: Object}

When it tried to then find the user information, it didn't go deep enough to properly populate the data.

I am unsure whether my input data is incorrect, but it seems like the function should look for my user information.

**Comment by simonc** [comment]
This has been fixed in master but it not yet released. If you face the issue, you can apply the following workaround until next release:

```javascript
import Devise from 'ember-simple-auth/authorizers/devise';

export default Devise.extend({
  // FIXME: Waiting for ember-simple-auth > 1.1.0
  authorize(data, block) {
    this._super(data['user'], block);
  }
});
```

**Comment by kylemellander** [comment]
Yes, this was merged in but did not get closed.

**Comment by simonc** [comment]
Yup 😁 Will there be an intermediate release like v1.1.1 before v1.2 for bugfixes?
It's a good think the workaround is there, without it it would be unusable for us ^^
