### ISSUE TITLE
Cannot get custom data from session.data attribute

### ISSUE THREAD

**Issue by danr1979** [simplabs/ember-simple-auth#848]
Hi.

I'm running ember-simple-auth 1.0.1 and Ember 2.2.0 with Ember Data 2.2.0.

I've got things working and I'm able to authenticate my Ember app with the server-side PHP API backend running Firebase PHP-JWT.  When generating my token on the server side to send back to ember-simple-auth I pass in a "data" attribute containing a "userId" and a few other custom values as follows:

    $token = array(
			'iss' => env('HOST_NAME'),
			'aud' => env('HOST_NAME'),
			'exp' => $expires,
            'data' => array(
                'userId' => $user->id,
                'roles' => $roles,
                'permissions' => $permissions
            )
	);

	$jwt = JWT::encode($token, $key, 'HS512');

However, in my Ember app if I try to access this data after authenticating like so:

    this.get('session.data')

all I see is the default "authenticated" key with the "exp" and "token" etc inside.  How do I go about accessing my custom data values ("userId", "roles" etc)?  I've read the documentation but I can't find an example of the data being access, only set.

I'd appreciate any help anyone can offer.

Thanks.

**Comment by marcoow** [comment]
What authenticator are you using? What's the exact response you're sending back from the server once the user authenticates?

**Comment by danr1979** [comment]
Thanks for your quick response. 

I'm using the JWT authenticator by jpadilla (https://github.com/jpadilla/ember-simple-auth-token), which could be causing the problem perhaps.

I don't have the exact response to hand as it's on my work machine but it looks like a valid JWT to me. It seems to be being interpreted correctly as I can access the "session.isAuthenticated" property  & see the "data" property, although the latter doesn't contain my custom data elements as I mentioned.

I'll try to get the exact response tomorrow.

Thanks again.

**Comment by danr1979** [comment]
The response the server is returning when authentication succeeds is as follows:

   {"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwczpcL1wvZGV2LnNlY3VyZS1vcGVyYXRpb25zLmNvbSIsImF1ZCI6Imh0dHBzOlwvXC9kZXYuc2VjdXJlLW9wZXJhdGlvbnMuY29tIiwiZXhwIjoxNDUyNjcyODY2LCJkYXRhIjp7InVzZXJJZCI6IjUiLCJyb2xlcyI6W10sInBlcm1pc3Npb25zIjpbXX19.ivO289WrKI2q-HBLhiHm5tiYZSeqKr1yPueddjW5gZD2s986OaR62sr7fA-Y7tonzj4hmk9H5yCjY1f_hjK2MQ"}

This appears to be a valid token and, interestingly, when the token is passed back to the server in subsequent requests to other API resources I can pick up the "data" fields from it in PHP.  This includes my custom fields so they are present in the token but appear to not be being recognized on the client side.

Hopefully this helps to understand what is amiss?

Thanks.

**Comment by marcoow** [comment]
Please open an issue at https://github.com/jpadilla/ember-simple-auth-token as this is most likely unrelated to Ember Simple Auth itself (ESA doesn't know anything about JWTs).

**Comment by danr1979** [comment]
Ok thanks.

I've logged the ticket as you advised so if anyone wants to see how this progresses please visit:

https://github.com/jpadilla/ember-simple-auth-token/issues/120
