### ISSUE TITLE
Could not find module `<app-name>/tests/helpers/ember-simple-auth`

### ISSUE THREAD

**Issue by kgish** [simplabs/ember-simple-auth#849]
According to the [documentation](https://github.com/simplabs/ember-simple-auth#testing), the following line should be added for tests:
```
import { currentSession, authenticateSession, invalidateSession } from '<app-name>/tests/helpers/ember-simple-auth';
```
However, when I try this I get the following error:
```
Could not find module `<app-name>/tests/helpers/ember-simple-auth`
```
The file is present but it is available as `bower_components/ember-simple-auth/simple-auth-testing.js`

or it can be copied into the `<app-name>/tests/helpers` directory, should be documented.

**Comment by marcoow** [comment]
The docs you mention only apply to ESA >= 1.0.0. You shouldn't have ESA in bower.json anymore when you're using that version.

**Comment by marcoow** [comment]
Closing this as the docs you're referring to only apply to ESA >= 1.0.0 where you're not supposed to have `ember-simple-auth` in your `bower.json` anymore but in `package.json` instead.

**Comment by januszm** [comment]
Hmm, @marcoow I'm quite new to Ember and I must say the docs are not clear to me in this case, I need to import those helpers for my acceptance tests to pass but when I add

```
import { currentSession, authenticateSession, invalidateSession } from 'my_app/tests/helpers/ember-simple-auth';
```

I get error:
```
Error: Could not find module `my_app/tests/helpers/ember-simple-auth` imported from `my_app/tests/acceptance/issues-list-test`
```

my `package.json`:

```
    "ember-simple-auth": "1.2.0-beta.1",
    "ember-simple-auth-token": "2.1.0",
```

**Comment by januszm** [comment]
UPDATE it was the underscore in the applicaiton name. Sorry about that, I didn't realize Ember converts underscores to dashes in this case.

**Comment by paulbhartzog-ps** [comment]
This error still exists even WITH ESA in package.json
