### ISSUE TITLE
Setting property on 'session.data.authenticated' doesn't throw exception

### ISSUE THREAD

**Issue by octronic** [simplabs/ember-simple-auth#856]
According to the docs and issue #789 setting properties in `session.data.authenticated` should throw an error since it is supposed to be read-only. It seems like this is not the case:

We are currently using ember-simple-auth 1.0.1, ember 2.3.0-beta-3 and the devise-authenticator. On successful authentication we save the id of the authenticated user in `session.data.authenticated.currentUserId` (so when the logged in user transitions to 'my profile' we use that id to get his user information)

By accident we found out that we can set that id to some other value in our app like this:
`this.get('session').set('data.authenticated.currentUserId', someOtherId);`

It didn't save `someOtherId` to the local storage though (viewing in browser it still showed the original `currentUserId`. But accessing `this.get('session.data.authenticated.currentUserId')` returned the value of `someOtherId`.

**Comment by marcoow** [comment]
This is similar to #805 - we'll track everything there
