### ISSUE TITLE
Error handling in case of 401 / Unauthorized

### ISSUE THREAD

**Issue by pogopaule** [simplabs/ember-simple-auth#858]
It seems that the data adapter's error handling in case of a 401 response is quite strange.
It simply [returns true](https://github.com/simplabs/ember-simple-auth/blob/1.0.1/addon/mixins/data-adapter-mixin.js#L100), which leads to the problem that all handlers for failing promises (on [routes](https://github.com/pogopaule/esa-401-handling-demo/blob/master/app/routes/application.js#L13) or on [the promise itself](https://github.com/pogopaule/esa-401-handling-demo/blob/master/app/routes/application.js#L6-L8)) receive `true` as a parameter.

I'd rather expect some form of an error object that I can ask for its HTTP error status.
Or do I miss something?

You can check out [my demo project](https://github.com/pogopaule/esa-401-handling-demo), demonstrating that issue

Note: I think this issue has already been addressed in #768, but IMHO this is still a problem.

**Comment by marcoow** [comment]
I guess it should return the error then - want to prepare a PR that fixes that?

**Comment by marcoow** [comment]
Looking at the Ember Data source it seems like it should return a `DS.AdapterError`.

**Comment by jayeff** [comment]
I opened a PR which should address this issue. Feedback is appreciated.
