### ISSUE TITLE
Provide the ability to change the localStorageKey from the default (ember_simple_auth:session)

### ISSUE THREAD

**Issue by xomaczar** [simplabs/ember-simple-auth#859]
Running two different app versions side by side and having a single shared session does not work. When invalidating session in tab1 with app@v1 running, the app@v2 session in tab2 also gets invalidated.

**Comment by xomaczar** [comment]
Got it working by overwriting session-stores/application.js. Took a bit of time to find it.

**Comment by marcoow** [comment]
👍
