### ISSUE TITLE
`authenticationSucceeded` event not thrown on successful restore for session

### ISSUE THREAD

**Issue by acorncom** [simplabs/ember-simple-auth#860]
We're using a token setup (using `ember-simple-auth-token`) and storing the token in localStorage so it can be retrieved on page reload or in a second tab.  So far, so good (it's all working properly and storing the token and related information including a public api key in local storage).

However, our app relies on handling the `authenticationSucceeded` event post-authentication (either initially when the user logs in or when restoring from local storage).  Per what I'm seeing in the docs, that's also what is intended to have happen:

Under `authenticationSucceeded` event here http://ember-simple-auth.com/api/classes/SessionService.html it says:

> Triggered whenever the session is successfully authenticated. This happens when the session gets authenticated via authenticate but also when the session is authenticated in another tab or window of the same application and the session state gets synchronized across tabs or windows via the store (see sessionDataUpdated).

But I'm not seeing that behavior on a restore from local storage.  Instead, it looks like the [`_setup` method` in `internal-session.js`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L88) isn't passed the trigger variable when restoring as seen here: https://github.com/simplabs/ember-simple-auth/blob/master/addon/internal-session.js#L55

Am I mis-reading the docs or missing something?  Or is this a bug?  I may be able to send in a PR, but wanted to make sure I wasn't wasting your time with a bogus PR ;-)

Thanks for all the work on this add-on, it's been really handy!

**Comment by marcoow** [comment]
`sessionAuthenticated` only runs after authentication, not restoration. If you want to run sth. in both cases  you might want to follow the pattern implemented here: https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/routes/application.js

That pattern will also be introduced as part of the library at some point probably.

**Comment by acorncom** [comment]
Thanks, that's the info I needed.  Appreciate the input!
