### ISSUE TITLE
Support accessing request options from custom authorizer

### ISSUE THREAD

**Issue by eduardoweiland** [simplabs/ember-simple-auth#862]
When implementing a custom authorizer, sometimes it may be necessary to have access to the request data. An example is when accessing a [HMAC-secured API](http://www.9bitstudios.com/2013/07/hmac-rest-api-security/), in which case the request data must be hashed and the resulting hash is used to authorize the request.

Currently, the authorizer is called only with the session data and a callback function that adds the header to the request in the [session service](https://github.com/simplabs/ember-simple-auth/blob/49edaa18e4860acf0d355badcae6d797bd18dc2b/addon/services/session.js#L224). The [callback function](https://github.com/simplabs/ember-simple-auth/blob/49edaa18e4860acf0d355badcae6d797bd18dc2b/addon/mixins/data-adapter-mixin.js#L78) is passed from the DataAdapterMixin to the authorizer.

A possible workaround is to override ajaxOptions() and, instead of passing a callback function, pass an object with the request data and the callback function. But it will be nice to have a standard way to access the request data from the authorizer.

**Comment by marcoow** [comment]
see #870

**Comment by marcoow** [comment]
closing this as we won't need it anymore once we have #979
