### ISSUE TITLE
Custom authorizer is not called

### ISSUE THREAD

**Issue by gauravdott** [simplabs/ember-simple-auth#865]
I am using ember-django-adapter with ember-simple-auth and have written the custom authorizer for token authentication. I am able to obtain the token from server but not able to inject it into the api requests using the adapter.

app/authorizers/application.js

```es6
import Ember from 'ember';
import Base from 'ember-simple-auth/authorizers/base';

const { service } = Ember.inject;

export default Base.extend({

  session: service('session'),

  init: function () {
    console.log('Intialize authorizer');
  },

  authorize(data, block) {
    const accessToken = data['access_token'];
    if (this.get('session.isAuthenticated') && !Ember.isEmpty(accessToken)) {
      block('Authorization', `Token ${accessToken}`);
      console.log("authorizer called with token: " + accessToken);
    }
  }
});
```

app/adapters/application.js

```es6
import Ember from 'ember';
import DRFAdapter from 'ember-django-adapter/adapter/drf';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

const { service } = Ember.inject;

export default DRFAdapter.extend(DataAdapterMixin, {
  session: service('session'),
  authorizer: 'authorizer:application'

});
```

app/authenticators/token.js

```es6
import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';

export default Base.extend({
  serverTokenEndpoint: 'http://localhost:8000/ember-auth/',

  authenticate: function(email, password) {
    return new Ember.RSVP.Promise((resolve, reject) => {
      Ember.$.ajax({
        url: this.serverTokenEndpoint,
        type: 'POST',
        data: JSON.stringify({
          email: email,
          password: password
        }),
        contentType: 'application/json;charset=utf-8',
        dataType: 'json'
      }).then(function(response) {
        console.log('Got token: ' + response.token);

        Ember.run(function() {
          resolve({
            token: response.token
          });
        });
      }, function(xhr) {
        var response = xhr.responseText;
        Ember.run(function() {
          reject(response);
        });
      });
    });
  },

  invalidate: function() {
    console.log('invalidate...');
    return Ember.RSVP.resolve();
  }
});
```

Ember tries to transition to protected route but due to non injection of Authorization header the request fails with 403 error.

Any help is appreciated.

**Comment by marcoow** [comment]
The authenticator resolves with

```es6
resolve({
  token: response.token
});
```

but in the authorizer you're using `const accessToken = data['access_token'];` which is null then of course so that the Authorization header will actually be sent with an empty token.

**Comment by deivinsontejeda** [comment]
I'm trying to migrate from ember-simple-auth `0.8.0` to `1.0.0` but I'm having trouble with custom authorizer. Basically I need to set some headers for each request made.

On `0.8.0` version I had a custom Authorizer with following code:

```javascript
    import Base from 'simple-auth/authorizers/base';
    
    export default Base.extend({
      authorize: function(jqXHR) {
        if (this.get('session.isAuthenticated')) {
          jqXHR.setRequestHeader('Authorization', 'Bearer token');
          jqXHR.setRequestHeader('X-Custom-Header', 'data');
        }
      }
    });
```

I'm a bit confused how I would to translate previous code into new ember-simple-auth version `1.0.0`.

BTW, I have similar code of @gauravdott and authorizer is not called.

**Comment by deivinsontejeda** [comment]
I have figured out what going on with authorizer, quote [doc](https://github.com/simplabs/ember-simple-auth#authorizers)

> Unlike in previous versions of Ember Simple Auth, authorization will not happen automatically for all requests the application issues anymore

As I understand (and tested on my code) you need call this `this.get('session').authorizer('authorizer:application', (data, header) => { })` in order to perform you custom authorizer.

In my case I need to fix a lot of code in order to set the app headers :-1: I do not know what is the reason of this changes but it would be good know it.

**Comment by marcoow** [comment]
@deivinsontejeda auto authorization introduced some global state and in general was very implicit - that's the reason why it was removed in 1.0. If you're doing a lot of non Ember Data (where you could use the [`DataAdapterMixin`](http://ember-simple-auth.com/api/classes/DataAdapterMixin.html)) requests, I'd suggest you use a service to do so which would then be the only part of the application that would have to call the session's `authorize` method to add auth headers.

**Comment by deivinsontejeda** [comment]
Thanks for suggestion. Indeed I have thought add something you said. But I
wonder what about a initializer which set necessary header using
Ember.$.ajaxPrefilter, makes sense this approach?

**Comment by marcoow** [comment]
I would not recommend using a global hook anymore as that can never be reset. That adds a lot of pain in e.g. testing mode and was the main reason it was removed in 1.0.

**Comment by deivinsontejeda** [comment]
I know this is no the focus of this issue but I would like heart any suggestions about this tiny [service](https://gist.github.com/deivinsontejeda/72b68592e49ef3fe1b1d) which wrap request to set custom HEADER or whatever you want.

**Comment by deivinsontejeda** [comment]
If it's a decent approach I promise (async) I will write down a post about this. I pretty sure many devs would like to know how this was fixed.
