### ISSUE TITLE
Unable to store localStorage session key when app opens in two tabs

### ISSUE THREAD

**Issue by pmkhoa** [simplabs/ember-simple-auth#866]
Strange bug that happened on my application that when I logged in the token key is not stored in the localStorage at all.
To reproduce the issue:
- Use ember-simple-auth version 1.0.0
- Setup localStorage as session store in config/environment.js.
- Open the application login route in 2 tabs.
- Then login using any of those tabs.

The error got after login: `Uncaught SyntaxError: Unexpected token u` (in Chrome), `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data` (in Firefox)
Under browser localStorage debug: `ember_simple_auth:session    undefined`

Please look into this issue. Thanks!

**Comment by marcoow** [comment]
If you want to use `localStorage` store with ESA 1.0 you don't configure that in 1.0 but instead define the store in `app/session-stores/application.js` (and extend the [`LocalStorageStore`](http://ember-simple-auth.com/api/classes/LocalStorageStore.html) in that file). Configuring the store in `config/environment.js` worked pre 1.0.

**Comment by pmkhoa** [comment]
I'm not quite sure I understood what you wrote. Could you give me an example of how to configure that? I'm using ESA 1.0. Thanks so much!!

**Comment by marcoow** [comment]
You cannot configure the session store to use in `config/environment.js`. See the README for more info on choosing the store to use for the application: https://github.com/simplabs/ember-simple-auth#session-stores

**Comment by pmkhoa** [comment]
I see. I was using ESA since pre 1.0, and was not aware of this change. Thanks!
