### ISSUE TITLE
Fake authentication in development?

### ISSUE THREAD

**Issue by phikes** [simplabs/ember-simple-auth#871]
Hi,

thanks for this awesome project. Although the documentation is really good
I was not able to solve the following problem myself.

**I want to fake authentication in development.**

What I tried was using the test helper `authenticateSession`, but it seems there
are some dependencies missing which are only available in the test environment.

I also tried to implement a simple authenticator based on the test authenticator:

```coffeescript
`import Test from 'ember-simple-auth/authenticators/test'`

`export default Test.extend()`
```

This doesn't seem to persist the authentication upon a page reload? The following
code in my template is not executed:

```handlebars
<a {{action 'authenticate'}}>Testlogin</a>
{{#if session.isAuthenticated}}
  {{#each model.user.favoriteTags as |tag|}}
    <div class="favorite-tag">{{tag.name}}</div>
  {{/each}}
{{/if}}
```

I tried to authenticate the following way:

```coffeescript
RecipesController = Ember.Controller.extend
  session: Ember.inject.service 'session'
  actions:
    authenticate: ->
      @get('session').authenticate 'authenticator:test'
```

Bear with me, since I am new to Ember ;-).

Thanks for your help in advance and all the best wishes from Aachen,

Phil

**Comment by marcoow** [comment]
The test helpers and the test authenticator should only be used in the test environment.

I'd be interested in hearing about the use case that you have for faking authentication. If you simply want to store data in the session you don't need it to be authenticated but can simply do so with e.g. `this.get('session').set('data.key', 'myValue');`.

**Comment by phikes** [comment]
Thanks for the fast reply! :) 

I am using ember-cli-mirage and don't have any backend servers running at the moment. Which is why I want to fake authentication. It's more than just storing data in the session, because I want to use the `isAuthenticated` helper in my templates :/. Or am I missing something?

**Comment by marcoow** [comment]
If you actually want to authenticate users you can do that with mirage as well - simply handle the authentication requests in mirage and respond with a token.

**Comment by phikes** [comment]
Thank you, of course. Why didn't I think of that! Have a nice weekend!
