### ISSUE TITLE
Tri-State Session (no session, unauthenticated/authenticated session)

### ISSUE THREAD

**Issue by Turbo87** [simplabs/ember-simple-auth#872]
I was wondering if anyone here has some ideas on the following scenario:

The API basically requires a session for everything, but some actions like user signup require an unauthenticated session, while others require an authenticated session. So far I've focused only on the authenticated state and that worked quite well with ember-simple-auth and a custom authenticator, but now user signup is needed and I'm wondering if there is a proper way to work with unauthenticated sessions in ember-simple-auth. Note that the unauthenticated session still has a token that needs to be sent though but on the server side it will be marked as either unauthenticated or authenticated.

Any ideas?

**Comment by marcoow** [comment]
You could simply use a custom authorizer that injects the unauthorized token when the session is not authenticated and the real token when the session is authenticated.

**Comment by Turbo87** [comment]
hmm, but the authorizer would only be called if the ESA session is authenticated, right?!

**Comment by marcoow** [comment]
Right. this should actually not be handled on the authorizer level but in the Ember Data adapter or network request service if you're using one.

**Comment by marcoow** [comment]
Closing this as I don't think it's actually something ESA should support.
