### ISSUE TITLE
Any reason why {{session.isAuthenticated}} is always false?

### ISSUE THREAD

**Issue by twisted1919** [simplabs/ember-simple-auth#874]
Hi guys, having a small issue here, I have this template:
```
 // application.hbs
{{#if session.isAuthenticated}}
        <a {{action 'invalidateSession'}}>Logout</a>
    {{else}}
        {{#link-to 'guest.index'}}Login{{/link-to}}
    {{/if}}
```
And after logging in, i always see the login link.
If i do `{{log session.isAuthenticated}}` in the .hbs i see undefined. same goes for the session object itself `{{log session}}`
In the route, doing a `console.log(this.get('session.isAuthenticated'))` returns correct value.

Using Ember 2.1

Any idea?

**Comment by marcoow** [comment]
You're probably not injecting the session service in the controller or component that backs the template in question.

**Comment by twisted1919** [comment]
Hmm, i actually am doing this in application.js route:
```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
    session: Ember.inject.service('session'),
    setupController (controller, model) {
        console.log(this.get('session.isAuthenticated'));
        this._super(controller, model);
    },
    actions: {
        invalidateSession: function() {
            this.get('session').invalidate();
        }
    }
});
```
But i do not have any controller, maybe that's the issue, as route info does not get passed to templates but controller info is?

**Comment by marcoow** [comment]
Yes, you need to inject the service into the controller as that is the template's context.

**Comment by bdiz** [comment]
I'm getting this as well starting with 1.1.0-beta.1.

I'm injecting the session service in my templates associated component (not using controllers). When I go back to 1.0.1 `session.isAuthenticated` works as expected.

I'll try to dig some to figure it out.

**Comment by bdiz** [comment]
@rmachielse Looks like this commit is where `session.isAuthenticated` stops working: https://github.com/simplabs/ember-simple-auth/commit/6e5527183674659b3ed3c547c1ce382a57f4cb5f

**Comment by rmachielse** [comment]
@bdiz I am using 1.1.0-beta.3 succesfully already, also with session.isAuthenticated in a template. Is there a way I can reproduce this issue? Are you sure the session is injected in the correct scope?

**Comment by bdiz** [comment]
@rmachielse I have the problem in 1.1.0-beta.3 as well. 

My set up is as follows (component and template): 
```
import Ember from 'ember';

export default Ember.Component.extend({
  session: Ember.inject.service('session'),
  actions: {
    invalidateSession() {
      this.get('session').invalidate();
    },
    authenticateSessionWithGoogle() {
      this.get('session').authenticate('authenticator:torii', 'google-oauth2').catch((reason) => {
        alert(reason.error || reason);
        this.set('errorMessage', reason.error || reason);
      }); 
    }   
  }
});
```
```
  {{#if session.isAuthenticated}}
    <a {{action 'invalidateSession'}}>Logout</a>
  {{else}}
    <a {{action 'authenticateSessionWithGoogle'}}>Login with Google</a>
  {{/if}}
```
Even with authentication successful, `session.isAuthenticated` does not evaluate true. The commit before 6e55271, that is 1915445, evaluates to true upon successful authentication.

**Comment by bdiz** [comment]
@rmachielse yes, the dummy app works with 1.0.1-beta.3. Not sure what the dummy app is doing differently from my app...the dummy app does some re-routing which I don't have. I'll have to look into it more.

**Comment by marcoow** [comment]
@bdiz: what's in the session store (`localStorage` or cookie)? Also how do you figure that authentication was successful? Does the app redirect to the `routeAfterAuthentication`? Are you able to access authenticated routes?

**Comment by bdiz** [comment]
Hi @marcoow : localStorage does not change from `{"authenticated":{}}`.

The reason I think it authenticates though is because the session promise resolves.

```
export default Ember.Component.extend({
  session: Ember.inject.service('session'),

  actions: {
    authenticateSessionWithGoogle() {
      this.get('session').authenticate('authenticator:torii', 'google-oauth2').then(() => {
        alert('authentication succeeded'); // This alert pops up.
      }, (reason) => {
        alert('authentication failed');
        this.set('errorMessage', reason.error || reason);
      });
    }
  }
});
```

I don't know how to check for the redirect to `routeAfterAuthentication`. I'm using torii pop-up and it closes as it normally does. 

I do not yet have any authenticated routes in my app yet. Soon I'll be adding some authenticated ajax requests and I can update you on how that goes.

**Comment by marcoow** [comment]
@bdiz: can you post the source of your authenticator and torii provider here?

**Comment by bdiz** [comment]
Authenticator:
```
import Ember from 'ember';
import Torii from 'ember-simple-auth/authenticators/torii';

export default Torii.extend({
  torii: Ember.inject.service('torii')
});
```
Torii provider:
```
    torii: {
      providers: {
        'google-oauth2': {
          apiKey: '95163626347-qov1ohph603olellp9h16bqfnunj71q7.apps.googleusercontent.com',
          redirectUri: 'http://localhost:4200'
        }
      }   
    } 
```

**Comment by marcoow** [comment]
@bdiz: can you open a separate issue for this? Also would be great if you could setup a public project that shows the issue of course.

@rmachielse: could you check again whether there's an uncaught regression in 6e55271? Given it's a big any quite complex change there might very well be edge cases that the test suite as well as the dummy app don't reveal.

**Comment by bdiz** [comment]
@marcoow @rmachielse Added new issue: https://github.com/simplabs/ember-simple-auth/issues/927

**Comment by JakeTun** [comment]
Hi !. 
I thinks its not a problem or return false. Because I solved this problem by changing my code.
The first time I use in my Asp.net MVC C# project.  
@if  (Session["IsAuthenticated"] != null )
{
}
else{}
When i use this code , it just login and not moving to my Dashboard.
Then i change my code to.
Session["Email"] != null) 
And it's work!....
Because I login my system using Email, If you are using ID or user name, that 's fine too.
