### ISSUE TITLE
Setup test runner for ember  versions 2.0, 2.1 and 2.2

### ISSUE THREAD

**Issue by Charizard** [simplabs/ember-simple-auth#875]
From the [ember-try.js](https://github.com/simplabs/ember-simple-auth/blob/master/config/ember-try.js) config, I see that the test is run against Ember versions `beta`, `canary`, `release` and `v1.12`.

But the tests are not run against `v2.0`, `v.2.1` and `v.2.2`. So need to update the config with these versions.

**Comment by marcoow** [comment]
Please provide details - issues with title only but without any explanation don't help anyone.

**Comment by Charizard** [comment]
@marcoow Sorry, have updated the description.

**Comment by marcoow** [comment]
I don't think we need to run against every single supported version really as each one of them is used as either beta, release or canary at some point anway and they won't change later on. If we wanted to do that we'd have to include 1.13 as well and would have to add a new version every 6 weeks.

**Comment by Charizard** [comment]
Makes sense :+1:

**Comment by Charizard** [comment]
@marcoow Sorry, was thinking about this again. When we say that `Ember Simple Auth supports all Ember.js versions starting with 1.12.`, then shouldn't every release be tested against all ember versions starting from 1.12 (Of course until ESA decides to drop support for old ember versions).

For example the lastest [1.1.0-beta.1 release](https://github.com/simplabs/ember-simple-auth/releases/tag/1.1.0-beta.1) is not tested against Ember v1.12 to v2.2 and it might let's say break in v1.12 and v1.13.

**Comment by Charizard** [comment]
Or another solution would be for ESA to specifically mention (for example) that ESA v1.0 will work on Ember v1.13 to v2.0 and ESA v1.1 will work only on Ember v2.1 and above.

**Comment by marcoow** [comment]
That's a good point actually. I'm not sure it's so great to add a new entry to the test matrix for every Ember.js release as the matrix would grow very big very fast given there would be a new entry every 6 weeks then.

**Comment by Charizard** [comment]
> I'm not sure it's so great to add a new entry to the test matrix for every Ember.js release as the matrix would grow very big very fast given there would be a new entry every 6 weeks then.

So then ESA can say that specific versions of ESA will work with specific version of ember. What do you think?

**Comment by marcoow** [comment]
Basically the question is whether it's ok to assume ESA will work with any version between the earliest and latest ones it is tested against although not every single version is tested against every Ember.js version. 

I think for the sake of simplicity and shorter build times that should be ok.
