### ISSUE TITLE
An examples of integrations with Azures AD adal.js

### ISSUE THREAD

**Issue by visualjeff** [simplabs/ember-simple-auth#880]
Has anybody attempted to integrate with Azure's AD (a.k.a [adal.js](https://github.com/AzureAD/azure-activedirectory-library-for-js))?

If so, would you care to chat about your implementation?

**Comment by marcoow** [comment]
Post questions on stackoverflow please.

**Comment by visualjeff** [comment]
Sorry.  FYI: I'm working on an implementation I hope to share.
