### ISSUE TITLE
Possible bug in observer logic

### ISSUE THREAD

**Issue by adam-knights** [simplabs/ember-simple-auth#883]
I'm following https://github.com/emberjs/ember.js/pull/12892 - because it relates to a bug that's critical to us.

The pull request mentions that when this code goes into Ember it will likely cause warnings in 2.4 and then assertions in 2.5, the OP found issues with Ember simple auth with his build, and feels it shows up something wrong with the observer logic here.

Opening this issue as a heads up incase there is anything easy to spot early. I had a quick look through the code but couldn't work out what it could be myself. May need to wait for this to go into Canary if its not obvious.

**Comment by marcoow** [comment]
Can you add some more detail? ESA doesn't use observers I think.

**Comment by adam-knights** [comment]
Literally just got the info from the pull request at the moment - when this hits Canary I'll be pulling it to test our app anyway, and we use ESA so happy to update or close this issue if all good then?

I may well pull the current pull request today if I get a chance anyway.

**Comment by marcoow** [comment]
Please reopen when there is actually a problem.
