### ISSUE TITLE
Authorization information not added for ajax call outside of Ember Data

### ISSUE THREAD

**Issue by adam-knights** [simplabs/ember-simple-auth#884]
In a particular component I have

```
import Ember from 'ember';
const { service } = Ember.inject;

export default Ember.Component.extend({
  session: service('session'),

  ...

  this.get('session').authorize('authorizer:oauth2', () => {
              // Use ajax as there is no data relationship here
              Ember.$.ajax({
                url: notifyAllUrl,
                method: 'POST',
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                data: JSON.stringify({
                  id: orderId
                })
              }).done(function() {
                // do stuff
              });
            });
});
```

Authorization information is added to the headers fine for all our Ember data bits. Having read the frontpage readme it said that this is not done for every request anymore, and suggested adding the `this.get('session').authorize('authorizer:oauth2', () => {`, but this hasn't worked, and I think it should?

Ember data has it by having done

```
export default DS.RESTAdapter.extend(DataAdapterMixin, {
  namespace: 'api',
  authorizer: 'authorizer:oauth2'
});
```

But this particular POST still doesn't have `Authorization: Bearer 893u2ijhfowi...` and I had hoped that would do it.

I imagine I am doing something wrong rather than a bug, but would be happy to propose an addition to the readme if it will help others.

**Comment by marcoow** [comment]
See the [API docs for the session service's `authorize` method](http://ember-simple-auth.com/api/classes/SessionService.html#method_authorize). The block is called with the authorization data created by the authorizer __which can then be inserted into request headers__.
