### ISSUE TITLE
Injecting Store in Custom Authenticator

### ISSUE THREAD

**Issue by shailendragnit** [simplabs/ember-simple-auth#887]
I am trying to inject store by initializes in my custom authenticator but it is note working. It throws error "Attempting to inject an unknown injection: `store:main`".

import CustomAuthenticator from '../authenticators/custom';
/*import CustomAuthorizer from '../authorizers/custom';*/
export function initialize(application) {
  application.register('authenticator:custom', CustomAuthenticator);
  application.inject('authenticator:custom', 'store', 'store:main');
}

export default {
    name: 'authentication',
    before:'ember-simple-auth',
    after: 'store',
    initialize: initialize
};

**Comment by marcoow** [comment]
Instead of injecting the store in an initializer you should inject it explicitly in the custom authenticator's implementation:

```js
// app/authenticators/custom.js
…
export default Base.extend({
  store: Ember.inject.service()
})
```

It looks like you're on an older Ember Data version though that doesn't define the store service.

**Comment by marcoow** [comment]
Doesn't seem to be a problem with ESA.
