### ISSUE TITLE
Calling this.get('session').authenticate('authenticator:custom') on start

### ISSUE THREAD

**Issue by vladikoff** [simplabs/ember-simple-auth#888]
Hey, I'm migrating to the latest version of ember-simple-auth.

My main question is: how do I trigger 
```
this.get('session').authenticate('authenticator:custom');
```

on application start up?

In my case I have a **custom** OAuth flow, user clicks "login", navigates away, comes back with a session on the server. ember-simple-auth used to [query /status](https://github.com/vladikoff/fxa-oauth-console/blob/master/app/initializers/authentication.js#L39) on application load but with the new version of simple-auth I'm not sure how to make it do that anymore.

Here's the migration patch : https://github.com/vladikoff/fxa-oauth-console/commit/4d233f679ffef912a40b1fa9c3abd00dc7804a2a

**Comment by marcoow** [comment]
Ember Simple Auth restores the session on application startup (in the application route's `beforeModel`). If the ESA session isn't authenticated at this point but you want to authenticate it yourself with a custom authenticator (from some data you get from the server in the query string or a cookie or whatever) you can do that of course. A good place for that would be in the application route's `beforeModel` which only runs after the session was either restored successfully or not.

**Comment by vladikoff** [comment]
Awesome! thanks for your help `beforeModel` it is and it seems to mostly work now.

Quick question, with the new setup this works in the RESTAdapter:

```
  headers: Ember.computed(function () {
    return {
      'Authorization': 'Bearer ' + this.get('session.data.authenticated.token')
    };
  }),
```

This works in the `hbs` template:

```
{{#if session.isAuthenticated}}
```

but getting the data does not work anymore:

```
{{session.data.authenticated.email}}
```

How do I get session data into the template? Before I just used `      {{session.data.email}}`. 

Thanks again and thanks for keeping the docs organized!
