### ISSUE TITLE
Should `sessionInvalidationFailed` be mapped to a method in application-route-mixin?

### ISSUE THREAD

**Issue by justinaray** [simplabs/ember-simple-auth#889]
It's possible to forward the event and manually add a listener, but should `sessionInvalidationFailed` be mapped to the application-route-mixin by default?

If semver prevents adding a new method to the application-route-mixin, perhaps we could just add this event to the list that are forwarded from the internal session to the session service?

**Comment by marcoow** [comment]
The session only exposes the 2 events ([`authenticationSucceeded`](http://ember-simple-auth.com/api/classes/SessionService.html#event_authenticationSucceeded) and [`invalidationSucceeded`](http://ember-simple-auth.com/api/classes/SessionService.html#event_invalidationSucceeded)) as only these can happen and  might not always be a consequence of a method call (as they might be triggered by a change to the session that originated in another tab or window).

Session invalidation failing though will only happen when the session service's [`invalidate`](http://ember-simple-auth.com/api/classes/SessionService.html#method_invalidate) method is called in which case you can just handle rejection of the returned promise.
