### ISSUE TITLE
 Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by sajt** [simplabs/ember-simple-auth#900]
When I run the tests, what was by ember generated. I get the 
`cannot read property 'on' of undefined` error.
How I find this is in the ember-simple-auth/mixins/application-route-mixin at line 89:
`_this.get('session').on(event, _ember['default'].run.bind(_this, function () {
     _this[method].apply(_this, _arguments);
 }));`
In that code the `_this.get('session')` is undefined, but `_this.session` is the injected service.
Why and how can I solve this?

**Comment by marcoow** [comment]
Please post the full source of your test here. Also which versions of Ember.js, Ember Data, Ember Simple Auth and Ember CLI are you using?

**Comment by marcoow** [comment]
Please reopen if the problem persists but then also provide the info as listed above.

**Comment by boobala** [comment]
I encountered the same problem, is there any solution for it?

**Comment by marcoow** [comment]
> Please post the full source of your test here. Also which versions of Ember.js, Ember Data, Ember Simple Auth and Ember CLI are you using?

**Comment by dopin** [comment]
I encountered too.

* Ember 2.7.1
* Ember DATA 2.7.0
* Ember Simple Auth 1.1.0
* Ember CLI 2.7.0

I also use ember-cli-auth-token 1.1.1.
The test code is just auto generated by ember-cli.

```js
import { moduleFor, test } from 'ember-qunit';

moduleFor('route:application', 'Unit | Route | application', {
  needs: ['service:session']
});

test('it exists', function(assert) {
  let route = this.subject();
  assert.ok(route);
});
```
