### ISSUE TITLE
custom fields in request payload

### ISSUE THREAD

**Issue by acerov** [simplabs/ember-simple-auth#902]
Hi devs,
I am using JWT,
how can I send some custom data/field to authenticate method generated request payload?
I tried to put myCustomField to credentials but that is not passed to request payload, just "email" and "password" went through.
`this.get('session').authenticate(authenticator, credentials)`

**Comment by marcoow** [comment]
Which authenticator are you using?

**Comment by acerov** [comment]
@marcoow I was using `authenticator:jwt`
but this thread helped me create "custom authenticator" and solved my issue:
[https://github.com/jpadilla/ember-simple-auth-token/issues/117](url)
Thank you anyway.
