### ISSUE TITLE
Using expires_in will delay refreshing tokens on restore - even if tokens have already expired

### ISSUE THREAD

**Issue by bttf** [simplabs/ember-simple-auth#906]
When the restore hook is called, if `expires_in` is only  set, simple auth will schedule token refresh only after the duration of `expires_in` value elapses.

This is a problem for us currently when tokens expire outside the browser, i.e. when the browser is closed. 

In this case, if tokens expire while the browser is closed, on the next restore hook, simple auth will delay refreshing tokens. It would be nice if it somehow knew they expired and would refresh them immediately.

**Comment by marcoow** [comment]
Actually tokens should be refreshed immediately in the `restore` method: https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js#L107. Can you maybe setup a repo somewhere that shows the problem?

**Comment by bttf** [comment]
The tokens only get refreshed immediately if `expires_at` field is populated. In the case that it is not, and only `expires_in` is set, the logic will follow through to `_scheduleAccessTokenRefresh` where it will calculate a new `expiresAt` on the fly, without taking into account the time in which the token was first generated, leaving the case unchecked where the token may have expired already.

**Comment by marcoow** [comment]
Wouldn't `expires_at` always be set as it gets set at login and also if the token is successfully refreshed?

**Comment by bttf** [comment]
We are using the cookie store currently - it seems the cookie stored does not contain `expires_at` unless the response includes it.. Will look into it further

**Comment by bttf** [comment]
Nevermind - we are using our app in an embedded fashion and are setting cookies manually on login - simple auth does indeed set `expires_at` after tokens are refreshed (and presumably at login as well). Apologies for the noise.

**Comment by marcoow** [comment]
Don't worry - you should never set ESA's cookies manually though but always go through the authenticator. The content of the `authenticated` part of the session cookie is actually private API and might change in any future version without prior notice.

**Comment by bttf** [comment]
👍
