### ISSUE TITLE
ember_simple_auth:session resetting on page refresh

### ISSUE THREAD

**Issue by srsgores** [simplabs/ember-simple-auth#907]
Perhaps I am misunderstanding [the ``restore()`` method](http://ember-simple-auth.com/api/classes/BaseAuthenticator.html#method_restore), but my localStorage key for ``ember_simple_auth:session`` will reset itself on page reloads:

![image](https://cloud.githubusercontent.com/assets/1750837/13194092/60ff0da4-d743-11e5-9a5f-968a446fd243.png)

But the localStorage key appears to populate correctly, on `authenticate()`:

![image](https://cloud.githubusercontent.com/assets/1750837/13194106/c7589656-d743-11e5-8c48-384f7516cde8.png)

My authenticator:

```
import Ember from "ember";
import Base from "ember-simple-auth/authenticators/base";
import config from "../config/environment";
import ajax from "ember-ajax";

export default Base.extend({
	authURL: `${config.db.url}/_session`,
	restore(data) {
		return new Ember.RSVP.Promise(function (resolve, reject) {
			if (!Ember.isEmpty(data.session_name)) {
				resolve(data);
			}
			else {
				reject();
			}
		});
	},

	authenticate(options) {
		return new Ember.RSVP.Promise((resolve, reject) => {
			return Ember.$.post(this.authURL, {
				username: options.identification,
				password: options.password
			}).then((response) => {
				Ember.run(() => {
					let parsedResponse = JSON.parse(response);
					resolve(parsedResponse);
				});
			}, (xhr, status, error) => {
				Ember.run(() => {
					reject(xhr.responseJSON || xhr.responseText);
				});
			});
		});
	}
});
```

What can I do to fix persistence of the ``session``?

**Comment by marcoow** [comment]
Your authenticator checks for a `data.session_name` value in the `restore` method. However, the value in your session data is actually just `name`. There should also be sth. in the logs saying that the authenticator rejected restoration.

**Comment by srsgores** [comment]
@marcoow, can you be a little more specific in terms of what I can do to fix restoration?

**Comment by marcoow** [comment]
You change this

```js
if (!Ember.isEmpty(data.session_name)) {
```

to:

```js
if (!Ember.isEmpty(data.name)) {
```

The whole session doesn't sound like a reasonable mechanism to make sure people cannot take over other people's sessions though.

Please move this to stackoverflow if you have more questions.

**Comment by srsgores** [comment]
Thanks!  Worked
