### ISSUE TITLE
Updating 1.1.0-beta.1 causes redirection issue

### ISSUE THREAD

**Issue by pmkhoa** [simplabs/ember-simple-auth#908]
When updated to the 1.1.0 beta 1 version, I always get redirection to the "routeAfterAuthentication" when refresh browser on any application route. Like refreshing /account, /team ... get redirect to /projects

Development env:
- Ember Cli: 2.3.0
- Ember: 2.3.1
- ESA: 1.1.0 beta 1

ESA configuration:

    ENV['ember-simple-auth] = {
        routeAfterAuthentication: '/projects'
    }

Please advise. Thanks!

**Comment by marcoow** [comment]
Which session store are you using? What is in the session store before the refresh?

**Comment by pmkhoa** [comment]
I use Cookie for session store. The session was set after authenticated, and it was always there when I refresh browser.

**Comment by marcoow** [comment]
What is in the session store before the refresh? Which authenticator are you using?

Provide as much info as possible please  to make it as easy as possible for people to help you…

**Comment by marcoow** [comment]
@pmkhoa: any news on this?

**Comment by pmkhoa** [comment]
@marcoow I'm reproducing the err in the new repo, and will give you an update soon. Thanks for your help on this so far. I really appreciate it.

**Comment by pmkhoa** [comment]
@marcoow 
Here is more detail info:

**Application server**
The app is running locally using self-signed ssl.

**Token format:**
```MTQ1NjUxNDQ0OXx4bnZwWXp1OE5fX3QwVFRNNi1oYy1KYkhLdmhLdnVHbUxYQmc1NU9pNDdEdzctREdqME44SllqTUZjUWRVVTQzOTRJcGNhUklkZjN0VEdoQldzdVg1VlgwRUhPdU1zZ1dJTy1wRFhGc ...```

As you can see from the screenshot, the application is authenticated, and token value is present all the time after validation:
<img width="1353" alt="screenshot 2016-02-26 12 01 24" src="https://cloud.githubusercontent.com/assets/1144585/13363905/d133a426-dc80-11e5-84fa-a134dcff9d92.png">

**Authenticators/custom**
```
// app/authenticators/custom.js
import Ember from 'ember';
import config from '../config/environment';
import Base from 'ember-simple-auth/authenticators/base';

export default Base.extend({
    restore: function(data) {
        return new Ember.RSVP.Promise( (resolve, reject) => {
            if (!Ember.isEmpty(data.token)) {
                resolve(data);
            } else {
                reject();
            }
        });
    },

    // Authenticate & Invalidate are running as expected.
     return new Ember.RSVP.Promise(function(resolve, reject){
            Ember.$.ajax({
                url: config.API.loginEndpoint,
                type: 'POST',
                data: JSON.stringify({
                    email: options.email,
                    password: options.password
                }),
                contentType: 'application/json;charset=utf-8',
                dataType: 'json'
            }).then(function(res, status, xhr) {
                Ember.run(function() {
                    resolve({
                        token: xhr.getResponseHeader("Session-Token") // Save token from response header
                    });
                });
            }, function(xhr, status, error) {
                Ember.run(function() {
                    reject(new Error('Error: ' + xhr.status + ' ' + xhr.responseText));
                });
            });
        });

    invalidate: function(data) {
       ...
    }
});
```
What happening during the redirection is that the restore function being called multiple times. I'm not sure if this is a bug, or is intentional. For instance, if I visit ``/projects route``, ``restore`` will be called twice. But if I visit ``projects/123/log``, ``restore`` will be called 3 times. They all returned the same token value.

Also, it's worthy to note that Ember CLI 2.3.0 will use `"ember-resolver": "^2.0.3"`.

**Comment by marcoow** [comment]
One problem I see in your code is that you configure `routeAfterAuthentication` as `'/projects'` while it actually expects an Ember.js route which would be `projects` in this case (without the leading `/`). Not sure whether that could cause the problems you're seeing but you might want to change that and test again so we can be sure.

**Comment by pmkhoa** [comment]
That was my typo, I used `routeAfterAuthentication` as `'projects'` in my config file.
I created this repo to reproduce the issue here: https://github.com/pmkhoa/esa-issue
I use ESA 1.1.0-beta.2, and latest Ember CLI. It just a boilerplate application that includes `/login`, `/projects`, and `/account` routes (protected). If you're logged-in, and reload browser on `/account` route, it will redirect to `/projects`.
I hope this makes it easier for you to debug. Thanks a lot!!

**Comment by marcoow** [comment]
Thanks for creating that demo repo - that's always the best way to track sth. down of course!

That seems to be an issue with the cookie store. If you change it to use the adaptive or `localStorage` store everything works fine again. It happens in the ESA demo app as well.

**Comment by pmkhoa** [comment]
Thank you!
