### ISSUE TITLE
Can not disable Ephemeral for testing

### ISSUE THREAD

**Issue by dex07** [simplabs/ember-simple-auth#909]
Previously I used ember-cli-simple-auth.
Today I upgraded to ember-simple-auth. 

The issue that I faced with after upgrading is my failed tests.
My Server requires token authentication.
The first test is to log in and receive token.
It is expected that the token persists in following tests but it does not.

It seems that the reason is in session-store:test that is Ephemeral.
Is there any way to disable it?

**Comment by marcoow** [comment]
You cannot disable the ephemeral session store in testing mode.

**Comment by zachfedor** [comment]
@marcoow, if we write our own authenticateSession test helper in order to use a custom authenticator, will the ephemeral session store still be used? I'm assuming that the ephemeral store is preferred in testing because it just persists to memory. I can't find documentation on the test authenticator and we've been having some difficulty with it so that's why I'm just using our custom one. Is this a bad idea?

**Comment by marcoow** [comment]
What are the issues with the test authenticator?

The ephemeral session store will always be used in tests as that is the only session store that is free of side effects.

**Comment by zachfedor** [comment]
I'm trying to test that the correct session data is persisted in our app to be used later. I'm using ember-cli-mirage to mock data, so the test goes something like this:

```
let user = server.create('user');
authenticateSession(this.application, { id: user.id });
visit('/profile');
andThen(function() {
    assert.equal(find('#user_name').text().trim(), user.name);
});
```

These tests are on a route that loads a model using `this.store.findRecord('user', this.get('session.data.authenticated.id'));` which works perfectly when serving the app (through localstorage, of course).

When testing, the model isn't loaded so the assertion fails. I attempted to debug with something like this:
```
let session = currentSession(this.application);
let data = session.get('data');
console.log(data);   // returns { authenticated: { authenticator: 'authenticator:test', id: 1 }}
console.log(data.authenticated);   // returns { }
```
The fact that I couldn't interact with that `data` object and assert that `data.authenticated.id` was actually equal to the user's id worried me.

**Comment by marcoow** [comment]
What happens if you change

```js
console.log(data.authenticated)
```

to

```js
console.log(data.get('authenticated'))
```

**Comment by zachfedor** [comment]
data doesn't have a `get` method. I also tried `session.get('data.authenticated')` which also returns an empty object.

**Comment by marcoow** [comment]
Please provide the full test - looks like you might be accessing the session data too early (before authentication has resolved).

**Comment by zachfedor** [comment]
that was it. I added some async logic and I'm getting the proper session data. thanks for the help @marcoow!

and thanks for a great ember addon!

**Comment by marcoow** [comment]
Sure, no problem!
