### ISSUE TITLE
Could not find module `ember-simple-auth/mixins/application-route-mixin` imported from `myapp/routes/application`

### ISSUE THREAD

**Issue by fhals** [simplabs/ember-simple-auth#919]
I have followed steps in [documentation](https://github.com/simplabs/ember-simple-auth#basic-usage). But I got error like this
`Error: Could not find module "ember-simple-auth/mixins/application-route-mixin" imported from "myapp/routes/application"`
And the content of my application.js is:
> //routes/application.js
>
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
>
export default Ember.Route.extend(ApplicationRouteMixin);

Do you have any idea to solve this? Is this my fault or a bug? Thanks

**Comment by marcoow** [comment]
Please provide your `package.json` and `bower.json`. Also please run `rm -rf node_modules bower_components && npm install && bower install` and check whether the problem persists.

**Comment by fhals** [comment]
Here are my file.

> //package.json
{
  "name": "myapp",
  "version": "0.0.0",
  "description": "Small description for myapp goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-ajax": "0.7.1",
    "ember-cli": "2.3.0-beta.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.3.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-load-initializers": "^0.5.0",
    "ember-resolver": "^2.0.3",
    "ember-simple-auth": "1.0.1",
    "loader.js": "^4.0.0"
  }
}

>//bower.json
{
  "name": "nolsks-auth",
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "jquery": "1.11.3"
  },
  "resolutions": {
    "ember": "2.3.0"
  }
}

Actually, I have done it. I deleted node_modules and bower components then installed it all again, but the error still exist.

**Comment by li-xinyang** [comment]
**Do NOT remove `node_module` and `bower_components`**

If you have encountered this issue, most likely it is because you have not restart the Ember server.
