### ISSUE TITLE
Broccoli fails to build due to collision with app/application.js

### ISSUE THREAD

**Issue by foxnewsnetwork** [simplabs/ember-simple-auth#924]
### The Problem
If you run another language preprocessor such as coffee, live, emberscript, or typescript, and have declared your own `routes/application.coffee`, `routes/application.ts` or whatever, the broccoli build pipeline fails because `ember-simple-auth` ships with `app/routes/application.js`

```shell
The Broccoli Plugin: [CoffeeScriptFilter] failed with:
Error: EEXIST, file already exists '/home/ia/miku/gumi/rin/tmp/coffee_script_filter-output_path-QcUkJJxp.tmp/dummy/routes/application.js'
```

### Howto: Reproduce
Using the latest ember-cli
```sh
version: 2.4.1
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
node: 0.12.0
os: linux x64
```
do the following:
```sh
ember addon beaver
cd beaver
ember install ember-cli-coffeescript
ember install ember-simple-auth
touch tests/dummy/app/routes/application.coffee
ember s
```

### Temporary Work-around
The easiest work-around is to write your `app/routes/application.coffee` to `app/routes/application.js` 

### My Humble Suggestion
Please delete `app/routes/application.js` from ember-simple-auth's directory. There is no reason why an addon needs to ship with `app/routes/application.js` (especially considering it just looks like it was auto-scaffolded), it's at best ignored by regular js users, and causes irritation with anyone using another language pre-processor.

**Comment by foxnewsnetwork** [comment]
also, I can pr if we're ok with my suggestion

**Comment by marcoow** [comment]
Ember Simple Auth hooks up its session restoration code to the `beforeModel` method of the application route (see https://github.com/simplabs/ember-simple-auth/blob/master/addon/instance-initializers/setup-session-restoration.js). Therefore it needs to make sure that an application route exists. If there's a better way I'd be happy to change the current implementation - removing the route is no solution though.

**Comment by foxnewsnetwork** [comment]
In that case, we could have a blueprint that attempts to place an `routes/application.js` into your project when the user installs `ember install ember-simple-auth`, and an assert in the instance initializer to remind the user an application route is required. Would that be acceptable?

**Comment by marcoow** [comment]
I wouldn't want people having to run a generator after installing the addon. Actually I think it should be possible to check whether the application defines an application route and if not use the automatically generated one instead.

The fact that the build breaks when the app tree has the same file with 2 different extensions is also not really a problem of ESA anyway but either of Ember CLI itself or of the addons that add support for Coffeescript etc. and should be fixed there anyway. Other addons might define default implementation for parts of the app itself, potentially leading to the same problem.

**Comment by foxnewsnetwork** [comment]
> not really a problem of ESA anyway but either of Ember CLI itself or of the addons that add support for Coffeescript etc

You're right. It really is bad form to abandon the obvious clean answer to compensate for a framework level problem that might be (though probably not, lol) solved any-day by the cli core team. I guess the best thing for folks like me would be to just submit to using js for the application route.

**Comment by marcoow** [comment]
closing this as it's not actually an issues with ESA
