### ISSUE TITLE
Add option to disable while developing

### ISSUE THREAD

**Issue by jackmatt2** [simplabs/ember-simple-auth#925]
Is there already an option to disable simple-auth while developing.  It is annoying because every time a file changes the live reload is executed and you have to login again.

**Comment by marcoow** [comment]
You cannot disable Ember Simple auth in development mode as it's an integral part of your application. If the session gets lost after reloads sth. seems wrong either with the session store or with the authenticator.

**Comment by jackmatt2** [comment]
OK thanks. I am working on someone else's code base so I was not sure if this was the expected behaviour.  I have checked ''Disable Cache while DevTools is open", could that be the issue?

**Comment by jackmatt2** [comment]
Yes, this was an issue with custom code in the `restore()` function that was invalidating the session. Cheers.
