### ISSUE TITLE
sessionAccount value get undefined after login, but has the value if the browser refreshed?

### ISSUE THREAD

**Issue by rizkytahara** [simplabs/ember-simple-auth#928]
I'm trying to get the sessionAccount for the username value after the user has login; but when I `console.log`, what I've got is `undefined`. If I refresh the browser, then there is a value of the username on the console.

How do I get the sessionAccount value right after the user login (without refreshing the browser) ?

```
Ember : 2.4.2
Ember Data : 2.4.0
jQuery : 2.2.1
Ember Simple Auth : 1.1.0-beta.3
```

**Comment by marcoow** [comment]
There is no concept of a `sessionAccount` in ESA currently. Please post the code that you're using to handle it.

**Comment by rizkytahara** [comment]
It's the `sessionAccount` service at the `test/dummy` folder to store the current user data. ( https://github.com/simplabs/ember-simple-auth/blob/master/tests/dummy/app/routes/application.js#L7 )

I want to access the `sessionAccount` at the `route` to get the current user data, but it is `undefined` after a user success logged in and redirected to the protected page.

The `sessionAccount` data at the `template` is shown by doing `{{sessionAccount.account.name}}`, but at the `route` the `sessionAccount` data shows `undefined` right after a user success logged in, unless the browser is refreshed.

So, when a user success logged in and redirected to the protected page, the template can show the current user data, but not for the route (unless the browser is refresh manually).


Here are some code that I'm using:

```
// app/services/session-manager.js

import Ember from 'ember';

const { inject: { service }, RSVP } = Ember;

export default Ember.Service.extend({
  session: service('session'),

  store: service(),

  setCurrentUser() {
    return new RSVP.Promise((resolve, reject) => {
      const access_token = this.get('session.data.authenticated.access_token');

      if (!Ember.isEmpty(access_token)) {
        return this.get('store').queryRecord('biscuit/user', {
          include: 'menus.translations'
        }).then((user) => {
          this.set('currentUser', user);
          resolve();
        }, reject);
      }

      resolve();
    });
  },
});
```


```
// app/routes/application.js

import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

const { service } = Ember.inject;

export default Ember.Route.extend(ApplicationRouteMixin, {
  session: service('session'),

  sessionManager: service('session-manager'),

  beforeModel() {
    return this._setCurrentUser();
  },

  sessionAuthenticated() {
    this._super(...arguments);
    this._setCurrentUser().catch(() => this.get('session').invalidate());
  },

  _setCurrentUser() {
    return this.get('sessionManager').setCurrentUser();
  },
});
```

```
// app/routes/backend/dashboard.js

import Ember from 'ember';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

const { service } = Ember.inject;

export default Ember.Route.extend(AuthenticatedRouteMixin, {
  session: service('session'),

  sessionManager: service('session-manager'),

  model() {
    console.log(this.get('sessionManager.currentUser.name'));
  }
});
```

I'm using the `sessionManager` as the alias for `sessionAccount`.

When I `console.log` the `sessionManager.currentUser.name` at the dashboard for the first time after the user success logged in, it shows `undefined`; but if I refresh the page manually, it shows the users data.

or am I missing something to get the current user data at the route ?

**Comment by rizkytahara** [comment]
any idea sir?

**Comment by AbdullaM5** [comment]
I solved problem this way:
```
// app/routes/application.js
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';

export default Ember.Route.extend(ApplicationRouteMixin, {
  session: Ember.inject.service('session'),
  isAuthenticated: Ember.computed.reads('session.isAuthenticated'),

  model() {
    if (this.get('isAuthenticated')) {
      return Ember.RSVP.hash({
        currentUser: this.store.findRecord('user', 'me')
      });
    }
  }
});
```
```
// app/instance-initializers/session-events.js
export function initialize(appInstance) {
  const applicationRoute = appInstance.lookup('route:application');
  const session          = appInstance.lookup('service:session');

  session.on('authenticationSucceeded', function() {
    applicationRoute.refresh();
  });
}

export default {
  name: 'session-events',
  after: 'ember-simple-auth',
  initialize: initialize
};
```

**Comment by rizkytahara** [comment]
@AbdullaM5 Thanks, the `applicationRoute.refresh();` worked.. :)
