### ISSUE TITLE
Custom authorizer without popup

### ISSUE THREAD

**Issue by maletor** [simplabs/ember-simple-auth#932]
I have a standalone API that accepts access tokens created from GitHub OAuth.

The flow starts with a static link: `https://github.com/login/oauth/authorize?client_id=xxxx`. This is simple enough and brings the resource owner to the authorization page. (Later we can add `state`.)

Then, they are redirected back to _Ember_. Ember receives the authorization grant code and sends it to the API where the API send the code with the client secret to GitHub and returns an access token and finally that is returned back to ember-simple-auth.

Once the access token is stored in the session we can pass the token to the API where it validates the token against GitHub. You could of course cache the responses from GitHub for an indeterminate amount of time.

This way we keep our resource server separate from the authentication server. If you see any flaws or ways this flow can be improved, please let me know. If you like this solution, maybe we can incorporate parts of it into the library or documentation. This is useful where application state is pretty worthless before authentication (most applications) and pop ups are undesired for user experience reasons or the OAuth provider does not provide a pop up authorization grant form.

Related issues:
1. https://github.com/Vestorly/torii/issues/116
2. https://github.com/Vestorly/torii/issues/203

``` js
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType
});

Router.map(function() {
  this.route('protected', { path: '/' }); // ApplicationRouteMixin should redirect here upon success.
  this.route('login'); // Should display a "Login with GitHub link"
  this.route('callback'); // The OAuth application's redirect_uri.
});

export default Router;
```

``` js
import Ember from 'ember';
import Base from 'ember-simple-auth/authenticators/base';

const { RSVP, isEmpty, run } = Ember;

export default Base.extend({
  serverTokenEndpoint: 'http://localhost:5500/oauth/token',

  restore(data) {
    return new RSVP.Promise((resolve, reject) => {
      if (isEmpty(data['access_token'])) {
        reject();
      } else {
        resolve(data);
      }
    });
  },

  authenticate(code) {
    return new RSVP.Promise((resolve, reject) => {
      const data = { code };
      const serverTokenEndpoint = this.get('serverTokenEndpoint');

      return this.makeRequest(serverTokenEndpoint, data).then(
        (response) => run(null, resolve, response),
        (xhr) => run(null, reject, xhr.responseJSON || xhr.responseText)
      );
    });
  },

  invalidate() {
    return RSVP.resolve();
  },

  makeRequest(url, data) {
    const options = {
      url,
      data,
      type:        'POST',
      dataType:    'json',
      contentType: 'application/x-www-form-urlencoded'
    };

    return Ember.$.ajax(options);
  }
});
```

This part I am less sure about, semantically. We don't really have a model, but it was the only way I could get the `code` param.

``` js
import Ember from 'ember';
import UnauthenticatedRouteMixin from 'ember-simple-auth/mixins/unauthenticated-route-mixin';

export default Ember.Route.extend(UnauthenticatedRouteMixin, {
  session: Ember.inject.service(),

  queryParams: {
    code: {
      refreshModel: true
    }
  },

  model(params) {
    const code = params['code'];
    const authenticator = 'authenticator:custom';
    this.get('session').authenticate(authenticator, code).catch((reason) => {
      console.log(reason);
    });
  }
});
```

**Comment by marcoow** [comment]
Just to be sure - the rotue you're showing there is the `callback` route, right? I'm not really seeing any problems with this flow.

It might make sense to add an authorization code authenticator to ESA that would be similar to yours then. We'd have to check with the spec again though whether there are any specific to be aware of: https://tools.ietf.org/html/rfc6749#section-1.3.1

**Comment by maletor** [comment]
Yes, that's the `callback` route. 

If we add `AuthorizationCodeAuthenticator`, I think it only makes sense that we add an `AuthorizationCodeRoute` to mixin to `Ember.Route` too so the user isn't left with a half baked solution.

I think we'd also want to add `state` to the authorization URL and to the `session.data` object for verification. Or does storing `state` in localStorage defeat the purpose of it in the first place since we are trying to prevent CSRF and localStorage would be retrievable...?

**Comment by marcoow** [comment]
I think the first step would be to add the authenticator as such and then expand on that once it is in and people using it provide feedback.

**Comment by stevenwu** [comment]
We may revisit this when we have more bandwidth. Any RFCs and PRs are welcome.

**Comment by chrismllr** [comment]
Working through something similar currently, building a custom Okta authenticator. Is there a best practice thats been developed since this issue was closed?

Currently, I am hindered by the fact that the public API for `session` is limited to `restore`, `authenticate`, and `invalidate`.... So I am utilizing my `authenticate` to toggle the redirect, as well as handle the resolution on the callback route:

```js
// sign-in controller

class SignIn extends Controller {
  @action signIn() {
     this.session.authenticate('authenticator:okta');
  }
}
```

```js
// oauth-callback route

class OauthCallback extends Route {
  async beforeModel(transition)
     await this.session.authenticate('authenticator:okta');
     this.transitionTo(Config.APP.defaultRoute);
  }
}
```

Which makes the authenticate method a little complex:
```js
// okta authenticator

class OktaAuthenticator extends Base {
  async authenticate(possibleTransition) {

    // must be the oath-callback route, parse the tokens from redirected URI
    if (possibleTransition) {
       const { token } = await this.client.parseFromURL();
       return resolve({ token });
    }
    
    // otherwise this must be login, so enter auth flow 
    return this.client.getWithRedirect()
  }
}
```

This may be the best way to handle this, but I wanted to make sure I'm not missing something.
