### ISSUE TITLE
Allow customized authenticator to accept headers

### ISSUE THREAD

**Issue by marshallshen** [simplabs/ember-simple-auth#933]
I notice that there's no way to pass headers in [overriding authenticator](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L106-L116).

Is this something on the roadmap? I would love to submit a PR for this, and I want to check before I start on it :)

Thanks!

**Comment by marcoow** [comment]
[`makeRequest`](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/devise.js#L140) takes an `options` argument that gets passed to `$.ajax` - you can simply specifiy request headers there.
