### ISSUE TITLE
Using AuthenticatedRouteMixin, how do I have the route redirect upon invalidating the session?

### ISSUE THREAD

**Issue by NullVoxPopuli** [simplabs/ember-simple-auth#934]
session.invalidate is called on a parent route, but a sub-route implements AuthenticatedRouteMixin.

I want the subroute to be redirected away from upon logout. 

Is this possible? if so, how?

**Comment by marcoow** [comment]
You can subscribe to the [session service's `invalidationSucceeded` event](http://ember-simple-auth.com/api/classes/SessionService.html#event_invalidationSucceeded).
