### ISSUE TITLE
Session is not being loaded (even injecting it)

### ISSUE THREAD

**Issue by andrehigher** [simplabs/ember-simple-auth#938]
I am starting to use `ember-simple-auth` and I am getting a weird issue when instantiate `authenticate` method chaining from `session`.

Look my code:

```
export default Ember.Route.extend({
  session: Ember.inject.service('session'),
  ....

   init() {
      let self = this;
	 Ember.$.ajax({
           ....
           success: function(response) {
		console.log(response);
		self.get('session').authenticate('authenticator:acdc', response).catch((reason) => {
	        self.set('errorMessage', reason.error || reason);
	      });
           });
      ....
    }
});
```

The error is:
```
session.js:165 Uncaught TypeError: Cannot read property 'authenticate' of undefined
```

Debugging this error, I went to `session.js` file and session is getting the `undefined` value.

``` 
#session.js
authenticate: function authenticate() {
      var session = this.get('session');   <-  undefined
      return session.authenticate.apply(session, arguments);
    }
```
Is it related with `init` function that are trying to reach `session` before it being initialized? 

ps: versions:
ember cli: 1.13.15
node: 4.3.0
npm: 2.14.10
os: darwin x64

**Comment by marcoow** [comment]
You shouldn't be doing that in `init`. You most likely want to do what you're doing in `beforeModel`.

**Comment by andrehigher** [comment]
@marcoow Even inside `beforeModel` I'm getting session undefined.

should I make some specific config about it?

**Comment by marcoow** [comment]
Maybe you're not on the latest Ember Simple Auth version actually? What do your `package.json` and `bower.json` files look like?

**Comment by andrehigher** [comment]
package.json:
```
{
  ...
  "private": true,
  "dependencies": {
    "grunt": "^0.4.5",
    "grunt-connect-proxy": "^0.2.0",
    "grunt-contrib-watch": "^0.6.1",
    "load-grunt-tasks": "^3.3.0",
    "phantomjs-prebuilt": "^2.1.3",
    "time-grunt": "^1.0.0"
  },
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "1.13.15",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-js-cookie": "0.0.1",
    "ember-cli-materialize": "^0.18.6",
    "ember-cli-moment-shim": "1.1.0",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "^5.3.0",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-composability": "^0.1.3",
    "ember-data": "1.13.15",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-legacy-views": "^0.2.0",
    "ember-modal-dialog": "^0.7.7",
    "ember-moment": "6.1.0",
    "ember-new-computed": "^1.0.3",
    "ember-radio-button": "^1.0.7",
    "ember-simple-auth": "1.0.1",
    "js-cookie": "^2.1.0"
  }
}
```

and bower.json:
```
{
  ...
  "dependencies": {
    "ember": "2.3.0",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-data": "2.3.3",
    "ember-load-initializers": "0.1.7",
    "ember-qunit": "0.4.16",
    "ember-qunit-notifications": "0.1.0",
    "ember-resolver": "~0.1.20",
    "jquery": "^2.2.0",
    "loader.js": "ember-cli/loader.js#3.4.0",
    "qunit": "~1.20.0",
    "materialize": "~0.97.0",
    "moment": "^2.11.2",
    "jquery-mask-plugin": "^1.13.4",
    "jquery-validation": "^1.14.0",
    "js-cookie": "^2.0.4"
  },
  "resolutions": {
    "jquery": "~2.2.0"
  }
}
```

**Comment by andrehigher** [comment]
@marcoow Ohh.. I see the latest version is 1.1.0 right?

**Comment by andrehigher** [comment]
it's so weird @marcoow. I updated to version: `1.1.0-beta.3` (which is the latest one) and i'm getting the same error.

**Comment by marcoow** [comment]
Yeah, that shouldn't make a difference. Probably better to go back to 1.0.1 for now anyway.

I guess you have stale tmp files lying around somewhere. You might want to `rm -rf node_modules/ bower_components tmp dist` and try again.

**Comment by andrehigher** [comment]
<img width="586" alt="screen shot 2016-03-23 at 6 04 05 pm" src="https://cloud.githubusercontent.com/assets/1289441/14000817/b15e2512-f121-11e5-8534-67fdd6d64a6b.png">

**Comment by seawatts** [comment]
I'm also getting this same error on `1.1.0-beta.3`

**Comment by marcoow** [comment]
Check in the Ember Inspector "container" section whether the `session` service is actually present.

**Comment by andrehigher** [comment]
@marcoow Actually I see the `session` service inside `container`.

**Comment by andrehigher** [comment]
<img width="1278" alt="screen shot 2016-03-28 at 11 19 06 am" src="https://cloud.githubusercontent.com/assets/1289441/14079814/ed1eb16c-f4d6-11e5-8c95-f6453e376eef.png">

**Comment by marcoow** [comment]
Would be great if you could somehow give me access to the repo or set up a public project that also shows the same behavior.

**Comment by andrehigher** [comment]
It's working now. The issue was that someone removed `config.modulePrefix` from `app.js` so for some reason the `session` was not being injecting into app. 

I'm getting another problem about authenticator but this thread can be closed. 

Thanks @marcoow for your help. Really appreciate that.
