### ISSUE TITLE
Redirecting to index after logging in; authentication does not persist

### ISSUE THREAD

**Issue by MarkMT** [simplabs/ember-simple-auth#939]
Using the devise authenticator and adaptive store, when I hit a protected route I transition immediately to login as expected. If I sign in with incorrect credentials I get an invalid sign in error message as expected. If I sign in with correct credentials I get a 200 from my backend server but the protected route appears only momentarily before redirecting to the index route. If I then return to the protected route I am again directed to the login route. 

Any clues on what might be going on here?

**Comment by marcoow** [comment]
Are you on ESA 1.1.0-beta.3?

**Comment by MarkMT** [comment]
No, I'm on 1.0.1, via ember install.

**Comment by MarkMT** [comment]
I just upgraded and I'm seeing the same behavior.

**Comment by MarkMT** [comment]
Turns out my server response is empty. What should it look like? I'm using [gonzalo-bulnes/simple_token_authentication](https://github.com/gonzalo-bulnes/simple_token_authentication) on the backend.

**Comment by marcoow** [comment]
The devise authenticator expects sth. like this:

```json
{ "token": "<token>", "email": "<email>" }
```

unless you configure `tokenAttributeName` or `identificationAttributeName` to be different than `token` and `email` respectively.

**Comment by MarkMT** [comment]
What I've figured out so far is that the problem seems to be caused by my use of ActiveModelSerializer's json-api adapter. That of course is needed for ember-data access to the api server. Not sure at the moment what the solution is, but I'm guessing that someone else must have solved this before.

**Comment by MarkMT** [comment]
Ok, problem solved...not an esa issue, but in case anyone comes here looking in the future...seems the issue was related to my use of active_model_serializers with the json_api adapter as required for ember-data. The standard devise session create action responds with the resource which I guess ams attempts to serialize (still not sure why it didn't produce anything at all). However I just overrode the create action and replaced `respond_with resource` in order to render raw json:
```
 render :json => {:email => current_person.email, :authentication_token => current_person.authentication_token}
```

**Comment by marcoow** [comment]
I guess the authenticator should definitely validate the server response in `authenticate` to catch errors like these early on. Currently we simply resolve the promise on any successful response, see #942.

**Comment by MarkMT** [comment]
Yeah that would definitely be useful.
