### ISSUE TITLE
DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge]

### ISSUE THREAD

**Issue by urbany** [simplabs/ember-simple-auth#940]
Hi, this line seems to be using a method deprecated in Ember@2.5.0-beta.3
https://github.com/simplabs/ember-simple-auth/blob/4259dc65be4d32c3ff6d46defe00cb70f928e55e/addon/internal-session.js#L143

More info: https://github.com/emberjs/ember.js/pull/12303

Setup:
```
Ember             : 2.5.0-beta.3
Ember Data        : 2.5.0-beta.3
jQuery            : 2.2.1
Ember Simple Auth : 1.1.0-beta.3
```

**Comment by gertjanwytynck** [comment]
Hi @urbany: See this PR #941
