### ISSUE TITLE
Use cookieName/localStorageKey based on project name

### ISSUE THREAD

**Issue by Turbo87** [simplabs/ember-simple-auth#950]
Right now the `ember_simple_auth:session` key is used for every project using this addon, which can lead to problems when the same domain is shared or when running on `localhost`.

The `getOwner()` method returns an object with an `application` property, which itself has a `name` property that could be used to generate a `<application-name>:session` key instead, which would most likely be sufficiently unique.

**Comment by marcoow** [comment]
You can actually configure the cookie name: https://github.com/simplabs/ember-simple-auth/blob/master/addon/session-stores/cookie.js#L65

**Comment by Turbo87** [comment]
@marcoow I know that, but it is pretty tedious having to overwrite the session-store in every single app when it can easily be handled by the lib itself. What's the reason for rejecting this proposal?

**Comment by marcoow** [comment]
I don't really see a need for this TBH given that there will never be a conflict unless multiple apps are served from the same origin. Also customizing the property is pretty easy and straight forward.
