### ISSUE TITLE
Adapter namespace is ignored

### ISSUE THREAD

**Issue by Baukereg** [simplabs/ember-simple-auth#951]
I have set a namespace in the application adapter:

```
import DS from 'ember-data';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';

export default DS.JSONAPIAdapter.extend(DataAdapterMixin, {
  namespace: 'api/v1'
});
```

Yet when I log in, `http://localhost:4200/api/token-auth/` is called and the namespace seems to be ignored.

I'm using simple auth token as well, so I'm not sure if this problem is simple auth only.

```
"ember-simple-auth": "1.1.0-beta.1",
"ember-simple-auth-token": "1.0.0",
```

**Comment by marcoow** [comment]
That behaves as expected. If you want to use the same namespace you're using for the adapter for the authenticator you'd have to configure it for the authenticator as well.
