### ISSUE TITLE
Static image requests (GET request to a back-end API) does no have the Authorization Header

### ISSUE THREAD

**Issue by eighteight** [simplabs/ember-simple-auth#952]
I am using password grant. Everything seems to work perfectly (which suggests that I have setup authenticators, authorizers and mixins correctly). However, I see that the static image requests, for the images embedded into html pages, the GET requests are coming with no Authorization Header. 

How can this be fixed (I want to serve static content using the same Authorization as a the rest of the site).

Thanks.

**Comment by marcoow** [comment]
You have to append the token to the image URL.

Please only open issues for actual bugs etc. though and refer to stackoverflow.com for questions.
