### ISSUE TITLE
Cannot get application authenticated using authenticateSession for Testing

### ISSUE THREAD

**Issue by pmkhoa** [simplabs/ember-simple-auth#956]
Hi Marco,

I'm trying to write some acceptance test for my app authentication. It seems trivial to look at the code that you wrote for your dummy app, however, I cannot get it working on mine. Here are some sample code that I wrote: https://github.com/pmkhoa/esa-issue/blob/master/tests/acceptance/login-test.js#L27

``` javascript
test('visiting /projects', function(assert) {
    authenticateSession(application);
    visit('/projects');
    andThen(function() {
        // assert.equal(currentSession(application).get('isAuthenticated'), true)
        assert.equal(currentURL(), '/projects');
    });
});
```
The `/projects`  is protected route, and user can visit it after the app is authenticated. I don't know what went wrong here. Any ideas?

Thanks a lot!

**Comment by ryanlabouve** [comment]
This has bitten me before.

The `this.application` that you were needing to pass to `authenticateSession` was getting setup from `/tests/helpers/module-for-acceptance.js`. https://github.com/pmkhoa/esa-issue/blob/master/tests/helpers/module-for-acceptance.js#L8

I removed a few lines where you had set that up manually and the test worked as expected. Here's a gist of the modified file:
https://gist.github.com/ryanlabouve/c86bcfd1956a04d6d4f0c226528ce44b

Hope this helps!

**Comment by pmkhoa** [comment]
Hi @ryanlabouve.
Thank you for your advise. It really helped, and everything is working now. It's kind of strange that there was no resource related to this little tweak on the internet.

**Comment by BryanCrotaz** [comment]
I just lost 4 hours on this - please give an example in the readme

**Comment by marcoow** [comment]
@BryanCrotaz: want to submit a PR that [extends the example in the README](https://github.com/simplabs/ember-simple-auth#testing) a bit?
