### ISSUE TITLE
OAuth2 revoke token request is not fired with correct authentication header

### ISSUE THREAD

**Issue by pijey** [simplabs/ember-simple-auth#960]
I'm using OAuth2 to secure my REST API (with Spring Security OAuth2) and ember-simple-auth with an OAuth2 authenticator for my ember app. Login works fine and API calls contain the *Authorization* header with the token.

However on logout, when trying to revoke a token (by setting *serverTokenRevocationEndpoint* in the oauth authenticator), a POST request is sent with an *Authorization* header that contains the clientId, not the token.

IMO, the token revocation endpoint shoud only be accessible by authenticated users (and an authenticated user should only be able to revoke its own tokens, but that's a server matter :) ) so in my case, I'm getting a 401.

I overrode the makeRequest method with the following (ugly) hack to make it work :

```javascript
makeRequest(url, data) {
	const options = {
	  url,
	  data,
	  type:        'POST',
	  dataType:    'json',
	  contentType: 'application/x-www-form-urlencoded'
	};

	const clientIdHeader = this.get('_clientIdHeader');
	if (!isEmpty(clientIdHeader)) {
	  	options.headers = clientIdHeader;
	}
	const token = data.token;
	if(!isEmpty(data.token_type_hint)){
		options.headers = {Authorization: `Bearer ${token}`};
	}

	return Ember.$.ajax(options);
	},
```
By default, should'nt the revoke request header contain the token *Authorization* header ?

Thanks!

**Comment by marcoow** [comment]
That's according to the spec, the `/token` and `/revoke` requests contain the client authentication (which is the client id for public clients) in the `Authorization` header. For the `/revoke` request the token to revoke is in the request body anyway.

**Comment by pijey** [comment]
Thanks for your response! Sorry I did not check the OAuth spec first.
So with public clients, either you don't secure the revoke endpoint (which IMO is not a good practice) or users can't revoke their tokens... 
I agree with the *wontfix* label since it would not follow the spec but what do you think of this problem ?

Thanks and great addon BTW !

**Comment by marcoow** [comment]
Not sure what you mean be "securing the endpoint" - the token is the same regardless of whether it's sent in the `Authorization` header or the request body. In general all requests that interact with the OAuth 2.0 server have the client credentials (which for public clients is the client id) in the `Authorization` header  while all requests that interact with the resource server have the token that the OAuth 2.0 server issued in the `Authorization` header.

**Comment by pijey** [comment]
In fact, I'm using the *password* grant type and the *revoke* endpoint is not in the Oauth2 server but I put it in the resource server (since Spring Security does not provide this endpoint natively) so I think it's the origin of the problem. I guess it's one limitation of OAuth2 when used to **authenticate** whereas it was designed to **authorize**.

Thanks for your explanation and sorry for the time loss ! I'll look into the OAuth2 spec to see if this protocol is the best choice for this project.
