### ISSUE TITLE
"isAuthenticate" at load method in a service

### ISSUE THREAD

**Issue by asantiago** [simplabs/ember-simple-auth#961]
Hello,

I have a service, with a initializer to inject it in all routes and controllers. In the load method, the "isAuthenticated" property, of the session, always return false at the init. After that, it changes to true, if it exists a previous session, and notify the change in the observer property correctly. I tried everything to start my service after session is full charged. I put in my initializer the property {after:'ember-simple-auth'}, i tried to restore the store manually and after access in the promise, without any success.

After that, the authentication header is put it correctly in all the calls to my api, but i need to know in that moment if the user is authenticated or not.

I think maybe is related with a problem with the localStorage, but I'm not sure....

The code:
`<pre>
 test: Ember.observer('session.isAuthenticated', function(){
      console.log(this.get('session.isAuthenticated'));
      console.log(this.get('session.data'));
  }),

  load: function() {
    if (this.get('session.isAuthenticated')) {
       return this.refreshUser();
    } else {
        return this.initUser();
    }
}.on('init'),
</pre>
`

Anyway, thank you for the plugin, its very usefull. ;D

**Comment by asantiago** [comment]
If I remove the initializer, it works.... my initializer:

`<pre>

export function initialize(application) {
  application.inject('route', 'user', 'service:user');
  application.inject('controller', 'user', 'service:user');
}

export default {
  name: 'user-injector',
  initialize: initialize,
  after: 'ember-simple-auth'
};

</pre>`

**Comment by marcoow** [comment]
The session will never be authenticated in an initializer as session restoration runs in the application route's `beforeModel`. If you want to do setup work depending on the session state you can do that in the `beforeModel` of the application route.

**Comment by asantiago** [comment]
Thank you very much.
