### ISSUE TITLE
Document an example of how to set/get the current user

### ISSUE THREAD

**Issue by andrewhavens** [simplabs/ember-simple-auth#966]
There seem to be many examples, with wildly different approaches, as to how to set and get the current user (for displaying the name of the user in the nav bar, or displaying an account page for the current user to modify their user record). The problem is that all of them are outdated and the code samples do not work anymore. It would be great if the readme provided an example that works with the current version of Ember Simple Auth since this would be a common request.

**Comment by marcoow** [comment]
Yeah, that's a good point. For now the way the current user is handled in the dummy app included in this repo is the canonical example. We're also planning to support that mechanism by means of hooks or so that Ember Simple Auth provides in a future version to make it even easier to use.

**Comment by marcoow** [comment]
this has been replaced by #1040
