### ISSUE TITLE
sessionInvalidated() is never called automatically?

### ISSUE THREAD

**Issue by eighteight** [simplabs/ember-simple-auth#969]
Here's the problem I have: once the access_token is invalidated by the server, the front never goes to the baseUrl. Manual invalidation works fine.

Is automatic call to sessionInvalidated in ApplicationRouteMixin on access_token should be even expected?

Currently, what's happening, is that the token gets invalidated by the server and all subsequent requests produce ugly errors on the website.

The sessionInvalidated method below is only called when the user manually invalidates the session, but never automatically.

Is this me, or the bug in the ember-simple-auth?

```js
export default Ember.Route.extend(ApplicationRouteMixin, {
  sessionInvalidated() {
    alert('Does this ever run?');
  },
  actions: {
    goBack() {
      history.back();
    },
    error(error) {
      console.error(error);

      return this.render('error', {
        into: 'application',
        model: {
          error: error,
        },
      });
    },
  },
});
```

**Comment by marcoow** [comment]
When you're using the `DataAdapterMixin` and the server responds with a 401 status code for any request, the session will be invalidated and the browser will be reloaded at the appliation's `baseURL`.

What server responses do you actually receive once the token was invalidated?

**Comment by eighteight** [comment]
I get a 500 status from the server when the token cannot be refreshed.

Not sure how easy it would be to fix the server side to have it return 401.

Which method could I override in ember-simple-auth to take a 500 as a sign of invalidation?

Thanks a lot!

**Comment by marcoow** [comment]
A 500 error only means that *anything* went wrong on the server side. That error does not indicate that the token was invalidated or so and really shouldn't be used for that.

**Comment by eighteight** [comment]
I fixed the server side and now it returns 401 on token expiration. However in ember-simple-auth all I am getting a warning about the error

```
Access token could not be refreshed - server responded with Unauthorized
```

in oauth2-password-grant.js (_refreshAccessToken method).

What was supposed to happen on getting 401 so that I get automatic redirect to the base?

Thanks.

**Comment by marcoow** [comment]
The session will not be invalidated automatically when refreshing the access token fails but only when the server sends a 401 for any Ember Data requests.

**Comment by eighteight** [comment]
I fixed that by overriding _refreshAccessToken method's error handler:

```
...
, (xhr, status, error) => {
      this.trigger('sessionDataInvalidated', data);
      Ember.Logger.warn(`Access token could not be refreshed - server responded with ${error}.`);
      reject();
    }
```

**Comment by luisjuniorj** [comment]
@eighteight could you elaborate how you do this work?

**Comment by eighteight** [comment]
@luisjuniorj I am overriding the above method of OAuth2PasswordGrant class in my oauth2 authenticator, by putting the customized version into it (along with makeRequest, authenticate etc)

```
  _refreshAccessToken(expiresIn, refreshToken) {
    const data = {grant_type: 'refresh_token', refresh_token: refreshToken};
    const serverTokenEndpoint = this.get('serverTokenEndpoint');
    return new RSVP.Promise((resolve, reject) => {
      this.makeRequest(serverTokenEndpoint, data)
        .then(
          response => {
            run(
              () => {
                expiresIn = response['expires_in'] || expiresIn;
                refreshToken = response['refresh_token'] || refreshToken;
                const expiresAtString = response['accessTokenExpiresAt'];
                const expiresAt = new Date(expiresAtString).getTime();
                const data = Ember.merge(response, {
                  expires_in: expiresIn,
                  expires_at: expiresAt,
                  refresh_token: refreshToken,
                });
                this._scheduleAccessTokenRefresh(expiresIn, expiresAt,
                  refreshToken);
                this.trigger('sessionDataUpdated', data);
                resolve(data);
              });
          },
          (xhr, status, error) => {
            this.trigger('sessionDataInvalidated', data);
            Ember.Logger.warn(
              `Access token could not be refreshed - ` +
              `server responded with ${error}`
            );
            reject();
          }
        );
    });
  },
```

**Comment by luisjuniorj** [comment]
tks
