### ISSUE TITLE
Allow override of config variables authenticationRoute, routeAfterAuthentication, routeIfAlreadyAuthenticated in mixin.

### ISSUE THREAD

**Issue by timjcook** [simplabs/ember-simple-auth#975]
In the 3 `simple-auth` route mixins `AuthenticatedRouteMixin`, `UnauthenticatedRouteMixin` and `ApplicationRouteMixin`, the redirect routes defined in `config/environment.js` are used to redirect the user to the correct routes based on if they are logged in, not logged in and should be etc.
I am finding that for an app with multiple user roles (ie. a `User` login and an `Admin` login) I am wanting to override these definitions.
eg. if someone who is not logged in went to `user/dashboard`, I think it should be redirected to `user/login`, which can be defined in the `config` file, BUT if that same person hit `admin/dashboard`, I would like that to go to `admin/login`, however it will also redirect to `user/login` which could be confusing.

My thought is that the 3 mixins defined above had an overridable variable that defaulted to the config definition, eg `AuthenticatedRouteMixin` might define: (see related code [here](https://github.com/simplabs/ember-simple-auth/blob/9d5a37b1ece0b82ee504e6cd6f367458b1d3120d/addon/mixins/authenticated-route-mixin.js#L55-L65))
```javascript
authenticationRoute: Ember.computed(function() {
  return Configuration.authenticationRoute;
}),
```
which I could then redefine in my admin routes to `admin/login` (I'd probably extend the mixin and include that override so I can easily add to all admin routes).

Would love to hear if people agree with this approach, or if others have any other alternatives, I'll have a look into a PR over the next little while.

**Comment by marcoow** [comment]
Seems good 👍
