### ISSUE TITLE
Unable to successfully configure baseURL

### ISSUE THREAD

**Issue by ljonesfl** [simplabs/ember-simple-auth#976]
As I am writing a chrome extension, I need to be able to authenticate against a different url than the application baseURL.
Setting ENV['ember-simple-auth'].baseURL in environment.js to the auth server url works fine and I can see that the variable is set successfully by adding a log at the end of the file.

When I do an authenticate, the system still submits to http://localhost:4200/users/sign_in

Am I missing something in the configuration?

**Comment by marcoow** [comment]
The `baseURL` setting doesn't configure the authenticator but is mostly used internally. It's also read-only (the API docs don't correctly indicate that though). If you want to configure the authenticators have a look at the respective API docs, e.g. http://ember-simple-auth.com/api/classes/OAuth2PasswordGrantAuthenticator.html#property_serverTokenEndpoint or http://ember-simple-auth.com/api/classes/DeviseAuthenticator.html#property_serverTokenEndpoint

**Comment by thegranddesign** [comment]
@marcoow FWIW, I just spent over an hour trying to figure out why I couldn't set `baseURL` before finally landing here.  How am I supposed to set the [destination after session invalidation](https://github.com/simplabs/ember-simple-auth/blob/master/addon/mixins/application-route-mixin.js#L111) if I can't set the `baseURL`?

**Comment by marcoow** [comment]
@thegranddesign: ESA will always reload the root of your application after Logout so e.g. `https://example.com` or `https://example.com/path` if you're serving your app from `/path`. If guess making `Configuration.baseURL` private API would probably already help reduce confusion.

Of course you can always override the [`ApplicatinRouteMixin`'s `sessionInvalidated`](http://ember-simple-auth.com/api/classes/ApplicationRouteMixin.html#method_sessionInvalidated) method to do sth. else after session invalidation.
