### ISSUE TITLE
Default keys for cookies are not RFC standard compliant

### ISSUE THREAD

**Issue by wzrdtales** [simplabs/ember-simple-auth#977]
The default key names of this plugin are `ember_simple_auth:session` and `ember_simple_auth:session:expiration_time` those are not standard compliant b/c of the colon in them.
Have a read of this gist that gives a good summary: https://gist.github.com/jeremiahlee/ff7dfb60572211dce306

This causes problems as soon as you use cookies and your backend is itself standard compliant and validates cookies or also if the backend validates the headers, one example would be `hapi.js` you will be denied to access those applications with an error like 

    {"statusCode":400,"error":"Bad Request","message":"Invalid cookie value"}

And the behavior of `hapi.js` is not wrong, they do deny the request right, but ember-simple-auth's default key names are wrong, so I would suggest to change those.

**Comment by marcoow** [comment]
Hm, good point. Thought I checked when I decided on these names… Want to submit a PR?

**Comment by wzrdtales** [comment]
@marcoow Can do, haven't thought about how to name them instead yet. Replace with `-` would be an option though.

**Comment by marcoow** [comment]
Yeah, I'd say replacing `:` with `-` or `_` should be fine (we should check which one is actually allowed though to be sure - this change is going to log all users out after the next reload).

**Comment by wzrdtales** [comment]
Yes true, except for those who overwrite the default key name.

`-` and `_` are both fine: https://tools.ietf.org/html/rfc2616#section-2.2

**Comment by wzrdtales** [comment]
I guess you will also need to announce this as a *probably* breaking change, as the users of `ember-simple-auth` do need to adjust the cookie name in their backend too if they were using the default ones.

**Comment by marcoow** [comment]
No, this doesn't change any API. The cookie is not supposed to be used directly be the backend - it's internals and name might be changed any time as it is considered private API in its entirety.

The only side effect of this change is that all users will be logged out when deploying this but I don't consider that a breaking change really as that probably happens for other reasons from time to time anyway
