### ISSUE TITLE
Deprecate Authorizers

### ISSUE THREAD

**Issue by marcoow** [simplabs/ember-simple-auth#979]
Authorizers are a bit too complex and the implementation is not great currently. While they seem to offer a lot of flexibility they actually don't deliver as they are quite tightly coupled to the authenticator as they depend on values being retrieved by them. Instead we could probably provide a better mechanism for adding for injecting headers into outgoing requests as that's the use care in a majority of the projects out there. I'm thinking about an API somewhat like this for Ember Data adapters, e.g.:

``` js
import JSONAPIAdapter from 'ember-data/adapters/json-api';
import DataAdapterMixin from 'ember-simple-auth/mixins/data-adapter-mixin';
import config from '../config/environment';

const { comuted, inject: { service } } = Ember;

export default JSONAPIAdapter.extend(DataAdapterMixin, {
  session: service(),
  host: config.apiHost,
  headers: computed('session.data.authenticated.token', function() {
    let token = this.get('session.data.authenticated.token');
    return { Authorization: `Bearer ${token}` };
  })
});
```

I'm not sure whether Ember Data currently supports `headers` being a computed property but I guess that could probably be added. It might be cool if it could even support it returning a promise as there's the use case that a single use token for each request might be needed that would have to be retrieved as sort of a pre-flight request in which case the computed property would return a promise that resolves with the header then.

/cc @pangratz

**Comment by srvance** [comment]
Ember Data does support computed properties for `headers`. What value does DataAdapterMixin add in that case? If `headers` would have to be declared in each adapter, this seems it would lead to a proliferation of boilerplate in cases where you had model-specific adapters. This is particularly bad when you have multiple data sources as ED has no layer of adapter between application and model.

**Comment by marcoow** [comment]
When you're using multiple adapters in the vast majority of cases they share a common base adapter. If that's not the case you could use a mixin to share the code that sets the custom headers.

**Comment by srvance** [comment]
I agree. If you're writing them all yourself, that's certainly an option.

I've recently been working with `ember-data-github` which tries to supply it's own token-passing mechanism based on a `headers` CP. I could monkey patch its adapter base class in an initializer or extend the model adapters adding an initializer in each one. The former is a bit ugly and the latter a bit laborious. I would see the latter as even worse without authorizers.

While the abstraction of an authorizer doesn't add a lot, I see it as useful for these kinds of cases. I would postulate that authorizers haven't been used very much because of a lack of documentation more than a bad design.

**Comment by marcoow** [comment]
The point is that authorizers don't do much anyway. Previously they did more but were also tightly coupled to jQuery's AJAX API. In the case of the [OAuth 2.0 Bearer authorizer](https://github.com/simplabs/ember-simple-auth/blob/master/addon/authorizers/oauth2-bearer.js) what it does is really trivial and I'm not sure it's worth it keeping the concept around. I think sth. like `DataAdapterMixin` is far more valuable for most people.

**Comment by srvance** [comment]
I can see that. I don't like the way `headers` overrides everything. I wish it were additive instead. If there were a nice way to roll that into the mixin, that would be great.

BTW, the example above should
```js
return { Authorization: `Bearer ${token}` };
```
I believe.

**Comment by marcoow** [comment]
> I can see that. I don't like the way headers overrides everything. I wish it were additive instead. If there were a nice way to roll that into the mixin, that would be great.

Yeah, that's a very good point.

**Comment by drauschenbach** [comment]
Agreed. I started out with my own OAuth authenticator with email/password credentials, then started to hit snags as soon as I tried adding in GitHub and Google as identity services. All I'm ever querying is my own models -- I have no use for querying GitHub models as the GitHub example shows -- GitHub is  just an identity service to me, and this use case seems to be really hard for me to pull together.

**Comment by drauschenbach** [comment]
By the way, here is how I got two authenticators working, one as my primary OAuth authenticator and authorizer, and a 2nd being Torii to use GitHub (and then others) as an identity service:

From my login controller:
1. `session.authenticate('authenticator:torii', 'github').then(...)`
2. `this.get('target').send('setDisableDefaultSessionInvalidation', true')` // disable page reload on logout
3. `session.destroy()` // destroy torii GitHub session
4. `this.get('target').send('setDisableDefaultSessionInvalidation', false')` // restore the usual reload-on-logout
5. `session.authenticate('authenticator:auth', 'oauth:github:'+username, githubAccessCode)` // authenticate with my normal OAuth backend using GitHub identity.

Then in my application route:

```javascript
export default Ember.Route.extend(ApplicationRouteMixin, {
  disableDefaultSessionInvalidation: false,
  ...
  sessionInvalidated() {
    if (!this.get('disableDefaultSessionInvalidation')) {
      this._super()
    }
  },
  ...
  actions: {
    error: function(adapterError) {
      //let code = Number(_.get(adapterError,'errors[0].status'))
      _.forEach(adapterError.errors, (error) => {
        this.get('notify').error(error.detail, {autoClear:false})
      })
    },
    setDisableDefaultSessionInvalidation(disable) {
      this.set('disableDefaultSessionInvalidation', disable)
    }
 }
```

**Comment by marcoow** [comment]
Yeah, that's not a bad idea. This mechanism is very much coupled to Ember Data though - authorizers were originally meant to be much more widely applicable than that.

**Comment by marcoow** [comment]
cleaning up old issues
