### ISSUE TITLE
authenticate method should use the underlying adapter/serializer

### ISSUE THREAD

**Issue by vasilakisfil** [simplabs/ember-simple-auth#986]
When I have set the default JSONAPI adapter in my app and I run authenticate through that addon, shouldn't it pickup automatically the underlying adapter and format the params appropriately ?

I personally use the devise authenticator but although I have a jsonapi adapter/serializer I see the data like the regular AMS-style.

**Comment by marcoow** [comment]
Ember Simple Auth's authenticators don't use JSON API. The Devise authenticator works with Devise and uses what Devise expects on the server side. The OAuth 2.0 authenticator implements the respective spec.

You can easily implement your own authenticator that works with JSON API of course. I'm not actually sure it's a good idea to use JSON API for authentication at all though as it's really built for reading and writing resources. I think in most cases it's better to keep your authentication mechanism(s) separate from that.

**Comment by vasilakisfil** [comment]
hmm I disagree, creating/destroying a session is yet another REST api endpoint and if the API is built in JSONAPI it should also be built in JSONAPI. Anyway thanks!

**Comment by vasilakisfil** [comment]
I still think that this is valid. For the record, here is how I just managed to do it (using 1.1.0) version:

```javascript
//app/authenticators/devise.js
import Ember from 'ember';
import Devise from 'ember-simple-auth/authenticators/devise';
const { RSVP: { Promise }, run } = Ember;

export default Devise.extend({
  store: Ember.inject.service('store'),
  serverTokenEndpoint: 'http://localhost:3000/api/v1/sessions',
  tokenAttributeName: 'token',
  identificationAttributeName: 'email',

  makeRequest(data) {
    return this.get('store').createRecord('session', data.user).save().then(
      function(session) {
        session.set('password', null);
        return session.toJSON();
      }
    );
  },
});
```

In that way when you send a POST request to `sessions` API, in your response you can include the user object as well which will *automatically* pushed in the store.

In the `master` branch, I think there is a `_validate` method that is called once the response is received, you might have to override that as well if you use the `master` branch. Hope it helps!

**Comment by jamesdixon** [comment]
For anyone who may come across the question of how to get your authentication request into a JSONAPI-compliant payload, you can do something like this with a custom authenticator:

```js
// authenticators/json-api.js

import { inject as service } from '@ember/service';

// NOTE: I'm extending the ember-simple-auth-token authenticator, but this can be used with the base ESA authenticator.
import Base from 'ember-simple-auth-token/authenticators/token';

export default Base.extend({
  ajax: service(),

  authenticate(credentials) {

    const { email, password } = credentials;

    const data = {
      data: {
        type: 'token',
        attributes: {
          email,
          password
        }
      }
    };

    return this.get('ajax').post(this.serverTokenEndpoint, { data }).catch((err) => {
      throw new Error(err.payload.message);
    });
  }
});

```

Usage:

```js
    login(email, password) {
      return this.get('session').authenticate('authenticator:json-api', {
        email,
        password
      });
    }
```
