### ISSUE TITLE
inactivity timeout

### ISSUE THREAD

**Issue by lmcardle** [simplabs/ember-simple-auth#987]
What is the best practice for adding an inactivity timeout to ember-simple-auth? For example, after x seconds since the last API request, i want to automatically log the user out. Additionally, after each successful request to the API, I want to restart the timer.

Right now I am thinking the best way to do this is to create my own data-adapter-mixin which is a copy of ember-simple-auth's mixin with the exception of overriding this one method (this would timeout after 60 seconds from the last API response):
```
handleResponse(status) {
    if (status === 401 && this.get('session.isAuthenticated')) {
      this.get('session').invalidate();
    } else {
      Ember.run.debounce(this, () => {
        this.get('session').invalidate();
      }, 60000);
    }
    return this._super(...arguments);
  }
}),
```

Is there a better way?

**Comment by marcoow** [comment]
That's probably a good way of implementing a timeout based on API requests.

In general, please use github for issues and stackoverflow.com for general questions.
