### ISSUE TITLE
Different refresh token endpoint

### ISSUE THREAD

**Issue by pjcarly** [simplabs/ember-simple-auth#989]
Is it possible to define a different refresh token endpoint from the regular login endpoint?

**Comment by marcoow** [comment]
No, you can only set the [`serverTokenEndpoint`](http://ember-simple-auth.com/api/classes/OAuth2PasswordGrantAuthenticator.html#property_serverTokenEndpoint). I think as per RFC6749 you actually have to use `/token` anyway.
