### ISSUE TITLE
Redirecting after login not working properly

### ISSUE THREAD

**Issue by jstoup111** [simplabs/ember-simple-auth#991]
I've got Ember 2.5.0.

When I navigate to a route `users.show` I've got code that sets `session.attemptedTransition` and redirects to `login`. When logging in, it attempts to redirect to the route, however `transition.retry()` aborts the current transition, there by stopping the attemptedTransition and I'm redirected to the index. Any ideas on a fix for this?

**Comment by marcoow** [comment]
> When I navigate to a route users.show I've got code that sets session.attemptedTransition and redirects to login.

Does that mean you're not using the `AuthenticatedRouteMixin` on the `users.show` route?

**Comment by jstoup111** [comment]
Yes that is correct. It appears to attempt to transition correctly, but I'm not seeing ```AuthenticatedRouteMixin``` work either. I've got a few protected routes and it attempts to transition to them but then aborts it and transitions me to ```index```. Let me know what logs you'd like to see to help debug a little better.

**Comment by marcoow** [comment]
Can you post your route's code? I'm not sure I understand your setup 100%. Also, why aren't you using `AuthenticatedRouteMixin`?

**Comment by jstoup111** [comment]
Because the route can be viewed without logging in. Doing an action on the page requires signing in. I'd like to have any user be able to view the page, but be forced to login if they try to perform an action.

Regardless it looks like my issue isn't isolated to this particular use-case. When I use the mixin it fails and does not transition properly. Here is my code using AuthenticatedRouteMixin that isn't working

routes/foo/new.js
```
import Route from '../application';
import AuthenticatedRouteMixin from 'ember-simple-auth/mixins/authenticated-route-mixin';

export default Route.extend(AuthenticatedRouteMixin, {
  model() {
    return Ember.RSVP.hash({
      me: this.store.findRecord('account', 'me')
    });
  },

  setupController(controller, model) {
    controller.set('me', model.me);
  }
});
```

routes/application.js
```
import Ember from 'ember';
import ApplicationRouteMixin from 'ember-simple-auth/mixins/application-route-mixin';
import ResetScrollMixin from 'ember-cli-reset-scroll';

const {service} = Ember.inject;

export default Ember.Route.extend(ApplicationRouteMixin, ResetScrollMixin, {
  title(tokens) {
    tokens = Ember.makeArray(tokens);
    return tokens.reverse().join(' - ');
  },
  sessionAccount: service('session-account'),
  metaTags:       service('meta-tags'),

  beforeModel() {
    return this._loadCurrentUser();
  },

  afterModel(model) {
    if(typeof this._createHeadTags === 'function') {
      this.set('headTags', this._createHeadTags(model));
    }
  },

  sessionAuthenticated() {
    this._super(...arguments);
    this._loadCurrentUser().catch(() => this.get('session').invalidate());
  },

  _loadCurrentUser() {
    return this.get('sessionAccount').loadCurrentUser();
  }
});
```

**Comment by marcoow** [comment]
I'm not sure how your session account service works but is it correct that you load the current user in the application route's `beforeModel` method regardless of whether the session is actually authenticated?

**Comment by jstoup111** [comment]
It's the same code as the dummy app.

**Comment by marcoow** [comment]
So when you access `/foo/new` it doesn't transition to `/login`? Do you see any errors on the console? Does it transition anywhere else instead or simply redirect at all?

**Comment by jstoup111** [comment]
Sorry for not clarifying. It transitions to `/login` properly. After logging in, it does not redirect to the route that I was currently at. It attempts to, but ends up redirecting to the index route instead.

**Comment by marcoow** [comment]
Do you see any errors or warning in the console?

> When I navigate to a route users.show I've got code that sets session.attemptedTransition and redirects to login

Can you post the code for this as well? It sounds like you have code that conflicts with ESA's functionality.

**Comment by jstoup111** [comment]
Sorry for the delay. Here's the console.

```
Preparing to transition from 'login' to 'clubs.edit'
ember.debug.js:53450 Attempting transition to index
ember.debug.js:53447 Transition #3: clubs.edit: transition was aborted
4ember.debug.js:53450 Attempting transition to index
ember.debug.js:53447 Transition #4: index: calling beforeModel hook
ember.debug.js:53447 Transition #3: detected abort.
ember.debug.js:53447 Transition #4: index: calling deserialize hook
ember.debug.js:53450 Attempting transition to loading
ember.debug.js:27999 Intermediate-transitioned into 'loading'
```

```
import Ember from 'ember';
import Route from '../application';

export default Route.extend({
  session: Ember.inject.service(),

  model(params, transition) {
    if(!this.get('session.isAuthenticated')) {
      // TODO isn't transitioning properly for some reason
      this.set('session.attemptedTransition', transition);
    }

    return Ember.RSVP.hash({
      club: this.store.findRecord('club', params.id)
    });
  },

  setupController(controller, model) {
    controller.set('club', model.club);
  },

  titleToken(model) {
    return model.club.get('name');
  }
});
```

To be clear, that code, and any route that has `AuthenticatedRouteMixin` fails to redirect after logging. It attempts to and aborts the redirection and I'm not sure why.

**Comment by marcoow** [comment]
```js
// TODO isn't transitioning properly for some reason
this.set('session.attemptedTransition', transition);
```

only sets a property on the session and doesn't initiate a transition at all. You should be able to just use the `AuthenticatedRouteMixin` in that route if you require the session being authenticated in order to access it which seems to be what you want.

**Comment by jstoup111** [comment]
@marcoow `AuthenticatedRouteMixin` does not redirect after logging in. I think I mentioned that in my last comment.

**Comment by marcoow** [comment]
Sorry, I'm not following. With the code you have you'll never see a transition when the session is not authenticated as you're not using the `AuthenticatedRouteMixin` and also never initialize a transition yourself.

**Comment by marcoow** [comment]
Hm, how does your code that authenticates the session look like?

**Comment by jstoup111** [comment]
I'm basically using the code from the dummy app. Again I'd like to point out that this is with Ember 2.5 and NOT 2.4. That could potentially be the issue here.

authorizors/application.js
```
import OAuth2Bearer from 'ember-simple-auth/authorizers/oauth2-bearer';

export default OAuth2Bearer.extend({});
```

authenticators/oauth2.js
```
import OAuth2PasswordGrant from 'ember-simple-auth/authenticators/oauth2-password-grant';
import config from '../config/environment';

export default OAuth2PasswordGrant.extend({
  serverTokenRevocationEndpoint: config.host + '/oauth/revoke',
  serverTokenEndpoint:           config.host + '/oauth/token'
});
```

services/session-account.js
```
import Ember from 'ember';

const { inject: { service }, RSVP } = Ember;

export default Ember.Service.extend({
  session: service('session'),
  store: service(),

  loadCurrentUser() {
    return new RSVP.Promise((resolve, reject) => {
      const accountId = this.get('session.data.authenticated.account_id');
      if (!Ember.isEmpty(accountId)) {
        return this.get('store').find('account', accountId).then((account) => {
          this.set('account', account);
          resolve();
        }, reject);
      } else {
        resolve();
      }
    });
  }
});
```

**Comment by marcoow** [comment]
Can you try and setup a small demo project showing the behavior? This is really hard to debug only based on some snippets of the actual code.

**Comment by jstoup111** [comment]
I figured it out after looking at https://github.com/simplabs/ember-simple-auth/issues/256

My issue was importing and extending `routes/application.js`. It was calling the `sessionAuthenticated` multiple times hence the transitions getting aborted.
