### ISSUE TITLE
Reorganize README with Table of Contents and Sub-Files

### ISSUE THREAD

**Issue by kylemellander** [simplabs/ember-simple-auth#999]
Currently, the README is long and sometimes a bit hard to find exactly what you need.  I propose that we reorganize the README to:
- [ ] Have a Table of Contents that allows people to quickly find what they need.
- [ ] Keep essential information on the main README and create a directory of subtopic readme's which people can use to find more specific information pertaining to specific apps.

**Comment by kylemellander** [comment]
As long as this is approved, I can work on this.

**Comment by kylemellander** [comment]
@marcoow As long as this is approved, I can work on this.

**Comment by marcoow** [comment]
This has been addressed already
